### ISSUE TITLE
[RFXCOM] New PacketType: IT

### ISSUE THREAD

**Issue by rtvb** [openhab/openhab2-addons#1019]
I have some Flamingo FA500 switches lying around that are supported by the RFXCOM device through the IT protocol. It would be great if the binding will support that protocol, too.

Product page:
http://www.elro.eu/en/products/cat/flamingo/electricite/wireless-control-flamingo/2-switches-with-remote-control6

RFXtrx User Guide (see: 2.2.2. Alphabetic list):
http://www.rfxcom.com/WebRoot/StoreNL2/Shops/78165469/MediaGallery/Downloads/RFXtrx_User_Guide.pdf

Reverse engineering for Arduino:
**rf433 code for ELRO Flamingo home devices (FA500)**
https://forum.arduino.cc/index.php?topic=201771.0
##

**Comment by martinvw** [comment]
I started working on this, I think it should be ready soon, I will first do some internal testing.

Note the FA500 in combination with the RFXCom only supports transmitting, see also the FAQ of the userguide.

**Comment by martinvw** [comment]
It works!

However, for me its way easier to build this in based on my other pull requests, because they allow me to add the rights tests and have a better support for fetching the SubTypes.

So if the following pull requests are merged (they are already approved) I will add new pull requests for this change:
https://github.com/openhab/openhab2-addons/pull/1247
https://github.com/openhab/openhab/pull/4629

**Comment by martinvw** [comment]
@rtvb are you still interested in this, I just completed the code changes required for OH2 and can provide you with a test-jar

**Comment by rtvb** [comment]
I will surely give this a test drive. Give me some time however. I will post my findings and create an issue if needed.

**Comment by martinvw** [comment]
You don't have to create an issue you can just mention it here, in openHAB 2 is has not yet been merged so you have to use my custom jar or compile yourselves from my branch. If it works I'll create the pull request.

**Comment by rtvb** [comment]
@martinvw I noticed an update in the wiki and your commit for the 1.9 release. Can you provide a link to a '1.9.0' .jar for use with my current 1.8.3 installation?

**Comment by martinvw** [comment]
Its in the official daily snapshots but this should also work:

http://mtin.nl/1019/org.openhab.binding.rfxcom-1.9.0-SNAPSHOT.jar

**Comment by rtvb** [comment]
I have installed the binding and configured some virtual switches like in the wiki:

```
Switch Virtual_FA500S_1 <light> (Debug) { rfxcom=">2901.1:LIGHTING5.IT:Command" } 
Switch Virtual_FA500S_2 <light> (Debug) { rfxcom=">2901.2:LIGHTING5.IT:Command" }
```

(I can successfully get the input from the remote)

I cannot pair this ID `2901` with my socket. This is what the debug log shows:


```
Raw data = 0D01FF140053E2000C2701020000
 - Packet type = INTERFACE_MESSAGE
 - Seq number = 20
 - Sub type = UNKNOWN
 - Command = RESET
 - Transceiver type = _433_92MHZ_TRANSCEIVER
 - Firmware version = 226
 - Firmware type = Ext
 - Hardware version = 1.2
 - Undecoded packets = false
 - RFU6 packets = false
 - RFU5 packets = false
 - RFU4 packets = false
 - RFU3 packets = false
 - FineOffset / Viking (433.92) packets = false
 - Rubicson (433.92) packets = false
 - AE (433.92) packets = false
 - BlindsT1/T2/T3 (433.92) packets = false
 - BlindsT0 (433.92) packets = false
 - ProGuard (868.35 FSK) packets = false
 - FS20 (868.35) packets = false
 - La Crosse (433.92/868.30) packets = true
 - Hideki/UPM (433.92) packets = true
 - AD (433.92) packets = false
 - Mertik (433.92) packets = false
 - Visonic (315/868.95) packets = false
 - ATI (433.92) packets = false
 - Oregon Scientific (433.92) packets = true
 - Meiantech (433.92) packets = false
 - HomeEasy EU (433.92) packets = false
 - AC (433.92) packets = true
 - ARC (433.92) packets = true
 - X10 (310/433.92) packets = true
 - HomeConfort packets = false
 - KeeLoq (433.92) packets = false
```

**Comment by martinvw** [comment]
Can you show me the debug log of what happens when you actually send the LIGHTING5.IT command?

And did you send that command while being in range of the socket which is blinking with the red light (ie learning mode)

**Comment by rtvb** [comment]
The FA500S does not have a blinking red light; I need to send an ON command within 10 seconds after plugging it in. I did that. Please find a more elaborate debug log.

_My personal guess would be a) that the protocol is not yet enabled on the RFXCOM device or b) I need a firmware upgrade?_

The thing is, I do not have access to a Windows machine to use their configuration app.

```
2016-12-24 06:43:26.393 [DEBUG] [.rfxcom.internal.RFXComBinding] - Received command: Virtual_FA500S_1 ON
2016-12-24 06:43:26.395 [DEBUG] [.rfxcom.internal.RFXComBinding] - Received command (item='Virtual_FA500S_1', state='ON', class='class org.openhab.core.library.types.OnOffType')
2016-12-24 06:43:26.397 [DEBUG] [.rfxcom.internal.RFXComBinding] - Transmitting data: 0A140F19000B5501010000
2016-12-24 06:43:26.446 [DEBUG] [.b.r.internal.RFXComConnection] - Data received:
Raw data = 0D01FF190053E2000C2701020000
 - Packet type = INTERFACE_MESSAGE
 - Seq number = 25
 - Sub type = UNKNOWN
 - Command = RESET
 - Transceiver type = _433_92MHZ_TRANSCEIVER
 - Firmware version = 226
 - Firmware type = Ext
 - Hardware version = 1.2
 - Undecoded packets = false
 - RFU6 packets = false
 - RFU5 packets = false
 - RFU4 packets = false
 - RFU3 packets = false
 - FineOffset / Viking (433.92) packets = false
 - Rubicson (433.92) packets = false
 - AE (433.92) packets = false
 - BlindsT1/T2/T3 (433.92) packets = false
 - BlindsT0 (433.92) packets = false
 - ProGuard (868.35 FSK) packets = false
 - FS20 (868.35) packets = false
 - La Crosse (433.92/868.30) packets = true
 - Hideki/UPM (433.92) packets = true
 - AD (433.92) packets = false
 - Mertik (433.92) packets = false
 - Visonic (315/868.95) packets = false
 - ATI (433.92) packets = false
 - Oregon Scientific (433.92) packets = true
 - Meiantech (433.92) packets = false
 - HomeEasy EU (433.92) packets = false
 - AC (433.92) packets = true
 - ARC (433.92) packets = true
 - X10 (310/433.92) packets = true
 - HomeConfort packets = false
 - KeeLoq (433.92) packets = false
2016-12-24 06:43:31.404 [ERROR] [.rfxcom.internal.RFXComBinding] - No acknowledge received from RFXCOM controller, timeout 5000ms due to java.util.concurrent.TimeoutException: waiting timed out
```

**Comment by martinvw** [comment]
I fear your version is to old, see the version history in the manual, especially the date. 

> Version 5.20– Feb 18, 2016
BlindsT12 Confexx CNF24-2435 added
IT FA500, PROmax... added
Ext2 fimware overview added in chapter 2 Auriol Z31055B-TX added
Chuango, Eminent security sensors added

Note that  mine also looks different (I do have a led, or at least something that emits red light)
![img_1197](https://cloud.githubusercontent.com/assets/2625279/21465844/c94e7fbc-c9b3-11e6-9479-4a2cb7b16d87.JPG)

I will also take a look at the unknown warning in the above message.

**Comment by martinvw** [comment]
The Unknown was sent by the controller meaning that it received an unknown / unexpected command request.

**Comment by martinvw** [comment]
I'm willing to upgrade your device, but I fear that you live somewhere near Rotterdam, I live near Haarlem.

**Comment by rtvb** [comment]
I have the black outdoor version of the device.

Thanks for your offer. I live near Rotterdam. I will probably need to try a pc from work or my son's gaming computer. Will let you know what happens after that. 

(Mac user since 2007)

**Comment by rtvb** [comment]
I was able to get my son away from his gaming PC. 😄 
An upgrade to the latest EXT2 firmware did the trick. 🤦‍♂️ 
Now I'm finally able to use those cheap ass switches with openHAB. 😉

**Comment by martinvw** [comment]
Hooray!

Did you test it with the OH1 binding or with OH2 binding or both?

**Comment by rtvb** [comment]
I downloaded the 1.9.0 jaar to be used with my 1.8.3 installation.

**Comment by martinvw** [comment]
I just tested it on my own environment switching the Christmas lights works on OH2 with this changes

**Comment by rtvb** [comment]
Since the PR has been merged, shouldn't we close this issue?
