### ISSUE TITLE
openHAB 2 and Homematic CCU2

### ISSUE THREAD

**Issue by openhab-6043** [openhab/openhab2-addons#1020]
Hi 
I have a CCU2 with the latest Firmware, a Hue and Sonos Systems. All items are configured in openHAB PaperUI and state is green. Except Homematic CCU2. I'm not able to get this up and running.

Status: OFFLINE - COMMUNICATION_ERROR Only -1 bytes received reading signature

On the CCU2 I get 
Jun 12 16:52:47 homematic-ccu2 daemon.warn cuxd[308]: process_rpc_request(192.168.1.135) - illegal XMLRPC(init) request

192.168.1.135 is the openHAB host

any ideas would be great
##

**Comment by openhab-6043** [comment]
hmmm strange
in the log I see

Jun 13 08:42:26 homematic-ccu2 daemon.info cuxd[308]: INIT 'binary://openhab.validation:1000' '(null)'
Jun 13 08:42:56 homematic-ccu2 daemon.info cuxd[308]: INIT 'binary://172.16.159.1:9125' '(null)'

But there are no 172.16 IP's in use

**Comment by ThomDietrich** [comment]
Hey! I can't help with the described problem, just wanted to tell you that I have been using homegear for 1-2 years and it's working great with openhab(2). If you're willing to sell your CCU2 and have homegear and openhab2 on the same Raspberry Pi, you can get a prepared image here: https://www.homegear.eu/index.php/Downloads

**Comment by MHerbst** [comment]
@openhab-6043 Is this issue still open? If yes can you test it with latest Snapshot?

**Comment by MHerbst** [comment]
No answer to my question for more than 3 weeks. @martinvw I think we can close this issue.

**Comment by martinvw** [comment]
If needed you can reopen it.

**Comment by CreatingYourApp** [comment]
I had the same issue and got it resolved by entering port numbers for callback (9200), XML-RPC (9201) and BIN-RPC (9202) port numbers.

Even though, 

`netstat -lnp `

didn't show any other service listening to the default ports 9125 and 9126, it seems that the default ports are either not used correctly or not working for some other reason. However, entering port numbers in those empty fields did solve my issue.
