### ISSUE TITLE
Z-Wave cannot change polling period

### ISSUE THREAD

**Issue by fignuts** [openhab/openhab2-addons#1043]
Attempting to set polling period on a z-wave device via habmin fails with

     [ding.zwave.handler.ZWaveThingHandler] - NODE 3: pollingPeriod (500.0) cannot be set - using default

Is there any other way to configure polling interval like refresh_inerval in oh1?

**Comment by cdjackson** [comment]
How are you trying to set this? I suspect the issue is because there's a decimal place on the end of the value and it's related to the following bug in ESH -:

https://github.com/eclipse/smarthome/issues/1477

**Comment by fignuts** [comment]
I am trying to set the value via the "Polling Period" entry box in the "Device Configuration" section when viewing the Thing in Habmin. It lists 1800 (I assume that is the default). I enter any other number, click save, and this error shows up in the log.

**Comment by cdjackson** [comment]
Ok - so as above, the problem is because of this error in ESH.

**Comment by robschoon** [comment]
Does anyone know of a work-around for this bug? Need to change the polling for a few zwave things.

**Comment by cdjackson** [comment]
It looks like ESH has decided to change this to use BigDecimal so I'll update the binding to do the same.
