### ISSUE TITLE
[DSC alarm]  OpenHab2 attempts port-4025 TCP connection to every host on WAN subnet

### ISSUE THREAD

**Issue by haunma** [openhab/openhab2-addons#1044]
I recently started seeing messages like the following in my kernel log:
```
    ...
    net_ratelimit: 405 callbacks suppressed
    neighbour: arp_cache: neighbor table overflow!
    neighbour: arp_cache: neighbor table overflow!
    neighbour: arp_cache: neighbor table overflow!
    ...
```
Further investigation showed that my machine (a router/firewall) was flooding the WAN interface with ARP requests to every host in the subnet, once every ~ 10 minutes. My ISP assigns me an IP in a /20 subnet, so this is a lot of addresses! It turns out the culprit was openhab2, which was essentially port scanning my the entire ISP local network attempting to find machines with port 4025 open.

Based on the port number, I suspect the problem is in the DSC alarm binding. I'm not sure why it is searching for an Envisalink module as the configuration dialog already has a place to fill in the Envisalink IP address.

More generally, because OH2 doesn't seem to have any config files and the UI is still in development, I'm not sure if there is a global place to tell it which network interfaces it should bind to. It's definitely not ok to assume that all network interfaces on the machine are local ones.

The binding version is 2.0.0-SNAPSHOT installed through the Paper UI a couple of weeks ago.

**Comment by watou** [comment]
The code in question is [here](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/discovery/EnvisalinkBridgeDiscovery.java).  I would agree that portscanning a subnet as a means of discovery (or incorrect results if a host uses the port for something else) can lead to problems and the user should be able to disable that.

**Comment by RSStephens** [comment]
@haunma thanks for the feedback.  I have been contemplating disabling this feature as there are issues with the port scan.  I will probably turn off the the background scanning, which runs every 10 minutes, and just leave the ability to do a manual scan from PaperUI.  I am going to submit a PR soon for other issues and will implement this.  Thanks.

**Comment by lolodomo** [comment]
Issue to close ?

**Comment by RSStephens** [comment]
Hello @lolodomo,

I have removed the background discovery for the binding so that it doesn't run automatically every 10 minutes.  A scan can still be performed, but it would need to be initiated manually through the PaperUI.  I would think the issue could be closed at a his point.
