### ISSUE TITLE
HomeKit Extension ColorItem

### ISSUE THREAD

**Issue by viruzofficial** [openhab/openhab2-addons#1052]
I've tried to set up items (**Switchable and Lighting**) wich are linked to a Lamp over the Philips Hue Bridge and have the Type **ColorItem**. Homekit gives me an error that this item is Type **ColorItem** and not expected **DimmerItem** (With **both** Tags). As referenced in the HomeKit Binding Documentation ColorItems should be supportet for Switchable and Lighting.

**Comment by kaikreuzer** [comment]
@beowulfe Could you have a look?

**Comment by beowulfe** [comment]
On it - HomeKit actually has support for color lights, which I still plan on getting into the addon. I'll add support for Switchable and Lighting on ColorItem in the meantime.
