### ISSUE TITLE
[zwave] NPE during add of Fibaro FGMS-001

### ISSUE THREAD

**Issue by mhilbush** [openhab/openhab2-addons#1057]
NPE occured during the inclusion of a Fibaro FGMS-001 motion sensor.  Appears to have occurred performing secure inclusion.

I was using binding version 2.0.0.201606240102 (from last night's build).

Debug log and node.xml are attached.
[openhab.txt](https://github.com/openhab/openhab2-addons/files/331756/openhab.txt)
[node4.txt](https://github.com/openhab/openhab2-addons/files/331750/node4.txt)

I also needed to make a minor database change (add another Type:ID) to this device, as well as the Aeon ZW-100.

**Comment by cdjackson** [comment]
Please disable security for now.

**Comment by mhilbush** [comment]
Thanks!  Why didn't I think of that?  :-(

Looks like you need to:
- Select the Z-Wave Serial Controller thing in HABmin
- Click on Tools and select "Show Advanced Settings"
- Select "Z-Wave Network Settings"
- For "Secure Inclusion Mode", select "Do Not Use Security"

I'll rediscover this device tomorrow with the new build that has the DB changes.

**Comment by mhilbush** [comment]
Disabling security is a good workaround.  Thanks.

**Comment by mhilbush** [comment]
@cdjackson What do you want to do about this issue?  If security is not supported yet, do you want to close this issue until security support is added?  I don't see the point in keeping it open.

**Comment by cdjackson** [comment]
OK, let's close it for now until I get this working...
