### ISSUE TITLE
[Homekit] If Item has mor than one Tag it won't appear inHomekit

### ISSUE THREAD

**Issue by Nibles** [openhab/openhab2-addons#1074]
If an Item has more than one Tag it won't appear as Homekit Accesory.
Am I doing something wrong, or can someone else confirm this?
I am using latest build from cloubees.

**Comment by kaikreuzer** [comment]
@beowulfe ?

**Comment by Nibles** [comment]
After more Tests it Seams that The Tag Switchable seam to work if there are additional Tags, but Lightening and CurrentTemperature do not.

Also the Group Tag Termostat does not work, but this is already an Existing Issue.

If moore Detail is neded please Tell me.

**Comment by viruzofficial** [comment]
I can confirm this behaviour. With the latest build i am not able to get a item displayed with the [ "Lighting" ] Tag when other Tags are set.
