### ISSUE TITLE
[zwave] Strips-MaZW (Sensative) main channel not working

### ISSUE THREAD

**Issue by IOOOTAlan** [openhab/openhab2-addons#1077]
Greetings,
I'm testing the aforementioned device using the zwave binding and I can't see status updates regarding the `Binary sensor` channel, which I assume is the one that should tell me if the door/window is open or closed. However, in the log I can see traffic regarding the device node while moving the magnet near it.
I'm attaching the binding log. The device is node 11. [strip-mazw.zip](https://github.com/openhab/openhab2-addons/files/339398/strip-mazw.zip)
Do you think it could an issue in the database?

**Comment by mhilbush** [comment]
It looks like the device is generating an ALARM report.  Did you try setting config parameter 1 (Notification Type) to 0 (Binary Sensor Report)?  It looks like the default is 1.

**Comment by watou** [comment]
Is this a case where you would create an association to the controller to receive updates?

**Comment by IOOOTAlan** [comment]
@mhilbush: yes, I tried setting it but it didn't change anything. Also tried the third option (basic report i.e. a value of 2 in config_1_1) to no avail.
@watou: I really don't know... Any means we could understand if this is the case?

**Comment by cdjackson** [comment]
I would probably suggest to discuss this sort of issue on the forum since the device is in use by a few people.

**Comment by cdjackson** [comment]
> On 29 Jun 2016, at 16:41, Alan <notifications@github.com> wrote:
> 
> @mhilbush <https://github.com/mhilbush>: yes, I tried setting it but it didn't change anything. 
> 
> 

When you make configuration changes, are you waking up the device? Does the PENDING flag go away.

**Comment by IOOOTAlan** [comment]
@cdjackson you were right, the device was not reconfigured following the change.
I had to put in in a listening mode by using the inclusion procedure described in the manual.
After this, I now see the `Binary sensor` like this:
 - ON when magnet is away (door/window open)
 - OFF when magnet is near (door/window closed)

I guess it was only a configuration issue and a misunderstanding of how the whole thing works on my part.
Thanks everyone for the assistance!

**Comment by NickWaterton** [comment]
I don't know if anyone is still seeing this, but I'm having exactly the same problem.

Was working using the 1.9 binding, moved to 2.0 and now this issue. I have woken the device up, and checked that the device is configured to binary_sensor (this was how I had it configured before).

I receive tamper_alarm when I wake it up, and battery-level, but not sensor_door (which is the whole point). I can see the SENSOR_BINARY events coming in in the zwave log.

I think it's something to do with the item type. sensor_door is defined as a Contact type (OPEN CLOSE) - which was how I was using it.

If I define the item as a Switch, then it seems to respond as OPEN/CLOSE - (I can see it in Habmin), but a Switch can't receive OPEN/CLOSE events.

You say above:
After this, I now see the Binary sensor like this:

ON when magnet is away (door/window open)
OFF when magnet is near (door/window closed)

But I'm not sure how this can be as it's a Contact type. This is using the release version of OH2.

Any idea? it's a bit of a sticker for me, as this is my door sensor!

Thanks.

**Comment by IOOOTAlan** [comment]
@NickWaterton it's been a while since I've tested those devices...
Will try to perform a test as soon as I can and report back.

**Comment by cdjackson** [comment]
You should not use sensor binary - this has problems in the device (ie firmware bug) - use notifications instead.

There is a large thread about this on the forum - I suggest to discuss this there if you have problems.

**Comment by NickWaterton** [comment]
Well I swear to God I searched everywhere for a solution yesterday. But I didn’t find that thread!

So I switched the strip to notifications (the one thing I didn’t try) and now it works fine.

Thanks for the tip.

Nick Waterton P.Eng.
National Support Leader - Nuclear Medicine, PET and RP
GE Healthcare

2300 Meadowvale Boulevard
Mississauga, ON  L5N 5P9  Canada

GE imagination at work

**Comment by NickWaterton** [comment]
Got a tip from Chris to switch the device to notifications, and that fixed the problem. So sensor_binary and basic both don’t work on this device, but notifications do.

Nick Waterton P.Eng.
National Support Leader - Nuclear Medicine, PET and RP
GE Healthcare

2300 Meadowvale Boulevard
Mississauga, ON  L5N 5P9  Canada

GE imagination at work
