### ISSUE TITLE
[zwave] Qubino ZMNHBD reacting slowly on switch

### ISSUE THREAD

**Issue by pail23** [openhab/openhab2-addons#1083]
I have installed a Qubino ZMNHBD Flush 2 relays with 2 Lamps connected. When I press the physical switch connected to the relays, the channel switch_binary changes its state immediately, but it takes minutes until switch_binary1 (or switch_binary2) changes its state.

When I use OpenZWave, all channels ract immediately. Can this be improved in openhab2 as well?

I have attached the xml file

[node33.zip](https://github.com/openhab/openhab2-addons/files/342187/node33.zip)

**Comment by cdjackson** [comment]
If things are slow, then it probably means there’s something up with the network, or the device isn’t initialised, or another device is slowing things down due to timeouts. I would suggest to check the logs to see what’s happening.

**Comment by cdjackson** [comment]
I would suggest to discuss the issue on the forum once you've looked at the logs. You can use the online log viewer at cd-jackson.com

**Comment by pail23** [comment]
OK, I will check the log files. Thanks for the hint to the log viewer.

What could speak against a network or initialization problem is that switch_binary (which is on if either one or the other light is switched on) reacts fast but the channels switch_binary1 and switch_binary2 are not.

**Comment by cdjackson** [comment]
Strange - they should be the same. Anyway, check the log - if things look strange, or you can’t work it out, then open a discussion on the forum and if we find a problem, then we can open an issue to fix it.

Cheers
Chris
