### ISSUE TITLE
[YamahReceiver] Wrong data type used for item type "Dimmer"

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab2-addons#1085]
Openhab complains about a wrong data type:
```
[s.c.internal.items.ItemUpdater:72   ] - Received update of a not accepted type (DecimalType) for item yamahareceiver_yamahaAV_5f9ec1b3_ed59_1900_4530_00a0deb80907_volume
```
The problem is caused by this statement in line 193 of YamahaReceiverHandler.java:
```
updateState(YamahaReceiverBindingConstants.CHANNEL_VOLUME, new DecimalType(state.getVolume()));
```
It can be solved by changing `DecimalType(state.getVolume()` to `PercentType((int) state.getVolume())`

**Comment by kaikreuzer** [comment]
If you already identified the bug, would you also be able to create a PR for it?

**Comment by MHerbst** [comment]
Yes, I think so.
