### ISSUE TITLE
Pulseaudio: pulseaudio.handler.PulseaudioHandler - device not found

### ISSUE THREAD

**Issue by stodir** [openhab/openhab2-addons#1095]
Hello,

I configured a Pulseaudio bridge and a Pulseaudio sink in the Paper UI.

The bridge has the parameters listed in the REST-API output bridge.txt and looks fine for me.
[bridge.txt](https://github.com/openhab/openhab2-addons/files/345221/bridge.txt)

The sink has the parameters listed in the REST-API output sink.txt and is always offline.
[sink.txt](https://github.com/openhab/openhab2-addons/files/345222/sink.txt)

I have configured the following item:
`Switch Test "Status Mute" <audio> {channel="pulseaudio:sink:pa_kueche_test:mute"}`

The item is used in a sitemap:
`Switch item=Test mappings=["OFF"="Ein", "ON"="Aus"]`

If I now use the switch item in the sitemap I see the following in the openhab.log and nothing else happens:
`[WARN ] [pulseaudio.handler.PulseaudioHandler] - device S1 not found`

When I am using pactl to list all sinks I get the output in pactl.txt
[pactl.txt](https://github.com/openhab/openhab2-addons/files/345223/pactl.txt)
##

**Comment by wborn** [comment]
Is this still an issue @stodir? There have been compatibility fixes meanwhile (https://github.com/openhab/openhab2-addons/pull/1556).

**Comment by stodir** [comment]
Hello,

since the pulseaudio binding was not working I used the exec-binding to control pulseaudio.

So I do not know if the issue still exists. Currently I do not have the time to configure and test pulseaudio.

I suggest to close the ticket. As soon as I have the time I will try the pulseaudio binding again.
