### ISSUE TITLE
Lutron binding: support Caseta Smart Bridge Pro

### ISSUE THREAD

**Issue by actong** [openhab/openhab2-addons#1118]
The Smart Bridge Pro (but not Smart Bridge) includes a telnet integration option that is similar to what other Lutron product lines use.  Some modifications to the binding are necessary in order to get it to talk to the Smart Bridge Pro.
##

**Comment by crossfireprod** [comment]
I believe all that should need to be done is echo the login credentials twice.  The integration protocol is otherwise the same, to my knowledge.
