### ISSUE TITLE
[astro] Positional job not starting

### ISSUE THREAD

**Issue by mhilbush** [openhab/openhab2-addons#1125]
This was noticed in build 407.  Not sure if it is related to the ESH fix for the intermittent binding startup issue.  

Debug log shows daily job starting, but not the positional job (which should run every 5 minutes by default) for Azimuth and Elevation.

```
2016-07-14 07:24:20.727 [INFO ] [ding.astro.handler.AstroThingHandler] - Scheduled astro DailyJob at midnight for thing astro:moon:local
2016-07-14 07:24:20.754 [INFO ] [ding.astro.handler.AstroThingHandler] - Scheduled astro DailyJob at midnight for thing astro:sun:local
2016-07-14 07:24:20.818 [DEBUG] [g.astro.internal.job.AbstractBaseJob] - Starting astro DailyJob for thing astro:sun:local
2016-07-14 07:24:20.822 [DEBUG] [g.astro.internal.job.AbstractBaseJob] - Starting astro DailyJob for thing astro:moon:local
2016-07-14 07:24:20.905 [DEBUG] [ding.astro.handler.AstroThingHandler] - Publishing planet Moon for thing astro:moon:local
2016-07-14 07:24:20.910 [DEBUG] [ding.astro.handler.AstroThingHandler] - Publishing planet Sun for thing astro:sun:local
```

**Comment by kaikreuzer** [comment]
The latest change on the Astro binding in this regard was https://github.com/openhab/openhab2-addons/pull/1079.

@gerrieg Could you have a look at this issue, please?

**Comment by lolodomo** [comment]
@gerrieg : if you make a change, set quartzScheduler and schedulerFuture to null in the constructor of AstroThingHandler.
I noticed that sometimes the thing remains in state INITIALIZING at startup and even if I am not sure it may be the reason.

**Comment by mhilbush** [comment]
Oddly, it seems to work when running from within the IDE.

**Comment by gletellier** [comment]
Hello,
Same issue for me. I am only able to get the positional job started by removing the Astro thing and adding it back with PaperUI.

**Comment by mhilbush** [comment]
In my comment above, I reported that the problem does not occur when running in the IDE.

As a next step, I rebuilt the binding with a few additional debug logging statements.  When I deployed the new astro jar file into my system, the Positional job started correctly.

Here's what I did.  Please let me know if I did something wrong.

I did this on the Windows box where I have the IDE installed:
- Built the astro binding using "mvn clean install" in the openhab2-addons directory.

I did this step and the remaining steps on the linux box where I have openhab installed:
- Uninstalled the Astro binding using PaperUI
- Stopped openHAB
- Removed astro from my addons.cfg file
- Copied the newly built astro jar file from the Windows box into the addons directory
- Started openHAB

Assuming I did this correctly, why would the Positional job start correctly when the astro binding jar was in the addons directory?  Is there something different about how a binding is loaded from the addons directory versus how it's loaded when it's installed through Paper UI?

**Comment by kaikreuzer** [comment]
Well, very likely a startup order issue - the binding should be ok with being started early, but it doesn't seem to be the case. Log files with ESH debug on will help analyzing such problems.

**Comment by mhilbush** [comment]
Attaching a log file with debugging enabled for:
- org.eclipse.smarthome
- org.openhab.binding.astro

The astro binding startup is at the end of the log file.

[astro-debug-2016-07-17.txt](https://github.com/openhab/openhab2-addons/files/367801/astro-debug-2016-07-17.txt)

This section of code in restartJobs is not being executed because `linkedPositionalChannels` is 0.  When I run openHAB with the astro jar file in the addons directory, `linkedPositionalChannels` in non-zero.  Very odd.

```
                        if (linkedPositionalChannels > 0) {
                            // positional intervalJob
                            jobIdentity = PositionalJob.class.getSimpleName();
                            Date start = new Date(System.currentTimeMillis() + (thingConfig.getInterval()) * 1000);
                            trigger = newTrigger().withIdentity("positionalJobTrigger", thingUid).startAt(start)
                                    .withSchedule(simpleSchedule().repeatForever()
                                            .withIntervalInSeconds(thingConfig.getInterval()))
                                    .build();
                            jobDetail = newJob(PositionalJob.class).withIdentity(jobIdentity, thingUid)
                                    .usingJobData(jobDataMap).build();
                            quartzScheduler.scheduleJob(jobDetail, trigger);
                            logger.info("Scheduled astro {} with interval of {} seconds for thing {}", jobIdentity,
                                    thingConfig.getInterval(), thingUid);
                        }
```
This is about as far as I can take it at this point.  I hope this helps point to the root cause.

**Comment by kaikreuzer** [comment]
That's a good observation. With linkedPositionalChannels, the astro binding makes the assumption that `channelLinked` is called for all channels after the handler is initialized, but this seems to be a false assumption in case the handler comes after the links.

**Comment by kaikreuzer** [comment]
Ok, having read the ESH documentation, I think it is indeed a bug in the framework, not in the binding, see https://github.com/eclipse/smarthome/issues/1871.

**Comment by mhilbush** [comment]
Thanks for tracking this down!

Can I infer from this that putting the binding in the addons directory had the effect of causing the handler to be initialized before the links?

**Comment by kaikreuzer** [comment]
I cannot tell - it sounds as if it should actually be the other way round, but only a detailed bug analysis will tell...

**Comment by mhilbush** [comment]
With the installation of build 447, I can confirm that the positional jobs now are starting, presumably as a result of this fix:
https://github.com/eclipse/smarthome/pull/1890

I'm closing this issue.
