### ISSUE TITLE
my.openHAB still persist data

### ISSUE THREAD

**Issue by lumachan** [openhab/openhab2-addons#1126]
I would like to disable openHAB 2 My.openHAB persistence.

By default, it's enabled. So I have created a myopenhab.persist file. Empty or not, the binding still persist data.

See https://community.openhab.org/t/my-openhab-org-myopenhab-persist/9387 and https://community.openhab.org/t/myopenhab-persistence/11577

Thanks
##

**Comment by lumachan** [comment]
Hi, any news, @belovictor around here ?

**Comment by kaikreuzer** [comment]
Yes, there are some news! See https://community.openhab.org/t/myopenhab-replaces-my-openhab/18258. The new service does not have this issue anymore, so I am closing this one here.
