### ISSUE TITLE
Sonos Alarm Channel not working

### ISSUE THREAD

**Issue by michaeljoos72** [openhab/openhab2-addons#1133]
Hi

Tried to use this channel for a Sonos Play1:
**Alarm is running (Set to ON if the alarm was triggered)**

The status never changes to ON. All other channels are working except this.

A known issue?

Thanks
Michael

**Comment by kaikreuzer** [comment]
Not known to me.
As the Sonos code is maintained at ESH, may I ask you to enter the issue at https://github.com/eclipse/smarthome/issues? Thanks!

**Comment by lolodomo** [comment]
@michaeljoos72 : for your information, I proposed a PR fixing this issue and others.
