### ISSUE TITLE
EcoLink Door Contact DWZWAVE2  not working

### ISSUE THREAD

**Issue by milty456** [openhab/openhab2-addons#1142]
I am unable to get this to work in openhab.
If i load up openzwave, I can see the sensor opening/closing fine
In open hab, my item stays Uninitialized.
It looks like the battery item comes over eventually
However the Contact Item never gets set.
I am using zwave and 26:Command=basic for my item binding string
Everything i read leads me to believe it is correct.  I am lost please help
I'm using version 1.8.3 of zwave and openhab

**Comment by cdjackson** [comment]
I suggest you discuss this on the forum. Since this is an Oh1 question it also shouldn't be raised in the Oh2 repo.
