### ISSUE TITLE
[ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-ui-coemtvisu'

### ISSUE THREAD

**Issue by peuter** [openhab/openhab2-addons#1150]
I see this error, when I start openhab2-beta3 (installed via apt repo):

[ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-ui-coemtvisu': No matching features for openhab-ui-coemtvisu/0.0.0

Although the cometvisu bundles seem to be loaded, I get an 404 error when I try to open the CometVisu in the browser. Is there some typo in the feature definition, which could cause that error? I tried to grep for 'openhab-ui-coemtvisu' in the sources but didn't find anything. Maybe someone can give me a hint where to look.

**Comment by maggu2810** [comment]
I assume there could be a type (oem instread of ome).

**Comment by maggu2810** [comment]
I assume it will work if you are using a more recent snapshot. I do not find a typo there anymore (in the sources).

**Comment by kaikreuzer** [comment]
just tested the latest snapshot, all is fine there.
