### ISSUE TITLE
Z-Wave binding in openhab/openhab-syno-spk

### ISSUE THREAD

**Issue by acseven** [openhab/openhab2-addons#1158]
Hi,

I'm using OpenHAB2 pre-release from **openhab/openhab-syno-spk**, and I'm struggling to understand (beginner... ) why some devices are present here in the addons but not in that package. 

Basically I have these devices on my network:

- Aeon Labs/AEOTEC Z-Stick Gen5 USB Z-Wave Controller
- Fibaro Roller shutter controllers FGR221 
- Fibaro Roller shutter controllers FGRM222

Only the last one is actually recognized, the rest are not (listed as "Unknown device"). 

Can you tell me if there is a proper way of using this database on an existing install?

Thank you

**Comment by cdjackson** [comment]
I don’t know if the SPK package is built nightly or not, but the database is embedded into the binding, so you need to have the latest one to get the latest database.

However, there is also an issue with the system at the moment in that under some circumstances a device will show as unknown. It’s linked to this issue in ESH -:
https://github.com/eclipse/smarthome/issues/1791 <https://github.com/eclipse/smarthome/issues/1791>

**Comment by acseven** [comment]
Thanks for your help. The package is downloading this file during installation:
`https://bintray.com/artifact/download/openhab/mvn/org/openhab/distro/openhab-offline/2.0.0.b3/openhab-offline-2.0.0.b3.zip`
The thing is, I don't know if the setup process is broken or not. In any case, I should find two Fibaro roller shutter devices listed on your database, but there's just one:
![scrn](https://cloud.githubusercontent.com/assets/1176371/17220603/d7860f0a-54e7-11e6-882c-36030cfb89d9.png)

Is there any way that I can get the addons jar file for the binding and place it somewhere to be used instead of whichever is being used?
From here, I mean:
https://github.com/openhab/openhab2-addons/releases

**Comment by acseven** [comment]
Oh, and I can't find any entry for the Z-Stick Gen5:

![scrn2](https://cloud.githubusercontent.com/assets/1176371/17220698/4d6aeb00-54e8-11e6-9fca-168a77fb6a73.png)

**Comment by cdjackson** [comment]
So the b3 version is quite old now and will definitely be out of date for the database.

What you can try is to download the latest JAR from cloudbees. The log on to the console, type “list |grep ZWave” and the stop the bundle (stop and then the bundle number). Then drop the new JAR into the addons folder.

**Comment by cdjackson** [comment]
There is no entry for the gen5 stick - use the serial controller.

**Comment by acseven** [comment]
Yeah, I have yet to find how to access openhab's console on my setup. In any case, I found the bindings stored here:
`/volume1/@appstore/OpenHAB2/runtime/karaf/system/org/openhab/binding/`

Got `openhab2-offline-2.0.0-SNAPSHOT.deb` from [cloudbees](https://openhab.ci.cloudbees.com/job/openHAB-Distribution/) and following the same folder structure, copied the `org.openhab.binding.zwave-2.0.0-SNAPSHOT.jar` file to my `/public/OpenHAB2/addons/` folder. After restarting the entire OpenHAB2 package I still can't see any other binding package other than `binding-zwave - 2.0.0.b3`. But even after removing the b3 binding I still can't see the newest one:

![scren4](https://cloud.githubusercontent.com/assets/1176371/17222091/8ea6ec1c-54ee-11e6-886e-b0baff04ba9f.png)

Also, should this make make any difference? I don't see any new package showing up with these on:
![scrn-](https://cloud.githubusercontent.com/assets/1176371/17222150/c69b52de-54ee-11e6-8179-ddc7be0659c3.png)


As for the Gen5 stick, I was only mentioning it because I had found an entry for it [your database website](http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/265), but I see it's not marked as valid. 

Thanks again for helping out a lost noob.

**Comment by cdjackson** [comment]
I don’t think you can simply change the list of bindings like that - Karaf keeps a cache of running bindings, so messing around with the store will very likely not change the running binding.

**Comment by acseven** [comment]
Ok, finally found how to access the console. In my case, within the NAS terminal session: `ssh karaf@127.0.0.1 -p 8101` 

```
openhab> list|  grep ZWave
196 | Installed |  80 | 2.0.0.201607280102    | ZWave Binding
197 | Active    |  80 | 2.0.0.b3              | ZWave Binding
```
With a little [doc reference](http://docs.openhab.org/administration/bundles.html) I tried to get bundle 196 running, but it threw out this error:

```
openhab> bundle:start 196
Error executing command: Error executing command on bundles:
	Error starting bundle196: Could not resolve module: org.openhab.binding.zwave [196]
  Another singleton bundle selected: osgi.identity; osgi.identity="org.openhab.binding.zwave"; type="osgi.bundle"; version:Version="2.0.0.b3"; singleton:="true"
```

Would other bundles should need updated versions as well?

**Comment by cdjackson** [comment]
As stated earlier, you need to stop the currently running bundle first - you can’t have two bindings running at the same time.

**Comment by acseven** [comment]
It is stopped, sorry for not mentioning it:

```
openhab> list|grep ZWave
196 | Installed |  80 | 2.0.0.201607280102    | ZWave Binding
197 | Installed |  80 | 2.0.0.b3              | ZWave Binding
openhab> start 196
Error executing command: Error executing command on bundles:
	Error starting bundle196: Could not resolve module: org.openhab.binding.zwave [196]
  Another singleton bundle selected: osgi.identity; osgi.identity="org.openhab.binding.zwave"; type="osgi.bundle"; version:Version="2.0.0.b3"; singleton:="true"

```

**Comment by cdjackson** [comment]
Ok - maybe it needs to be uninstalled, not just stopped.

**Comment by acseven** [comment]
You're right, that made it start:
```
openhab> list | grep ZWave
200 | Active    |  80 | 2.0.0.201607280102    | ZWave Binding
```

And finally there's some visible progress, thanks very much! 
![scrn5](https://cloud.githubusercontent.com/assets/1176371/17226435/5a545356-5501-11e6-9563-5e1e70836154.png)


The older FGR221 roller shutter controllers do have a limitation though: they don't have a percentage selector like  the FGRM222. Using the Paper UI interface you can actually set it to a value, if typed in. On the other hand, the older one (FGR221) has more controls for fully open, fully close and stop.

Other than this I just have to find out how to use all of this. Thank you very much for your help, I wouldn't have got there without it.

Also, I did have to disable "Access Remote Repositories" from "Configure Extension Management" because the beta3 bundle reappeared and self-activated after I uninstalled it.

**Comment by cdjackson** [comment]
No problem - glad it’s working.
