### ISSUE TITLE
RFXCom fails to communicate after detection

### ISSUE THREAD

**Issue by kylegordon** [openhab/openhab2-addons#1163]
After installing the latest snapshot of OpenHAB2 and installing the RFXCom binding from the UI, it detects my RFXCom 433 transceiver on /dev/ttyUSB0 but then fails to communicate with it.

I've obtained the following log entries

2016-07-29 14:41:37.788 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'rfxcom:RFXtrx433:A1WRPEJT' to inbox.
2016-07-29 14:42:48.696 [INFO ] [ernal.connector.RFXComJD2XXConnector] - Connecting to RFXCOM device 'A1WRPEJT'.
2016-07-29 14:42:48.716 [ERROR] [g.rfxcom.handler.RFXComBridgeHandler] - Connection to RFXCOM transceiver failed: device not opened (3)

The serial number was autodetected, and certainly matches the udev appointed name at /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1WRPEJT-if00-port0

There are no processes holding open the device (not even openhab/java), so I'm unsure as to why it's failing. OpenHAB2 is running as root, and the RFXCom is on firmware version 78.

**Comment by paulianttila** [comment]
@kylegordon: this is a know problem. Both Linux and OS X have native drivers for FTDI based devices, which prevent JD2XX connections to work (discovery works, but connection not). See more information and work around from the forum https://community.openhab.org/t/rfxcom-2-0-binding/4427/5.

**Comment by kylegordon** [comment]
@paulianttila Many thanks for the information! I now have it working :+1: 

One thing to note is that it failed with by-id naming, so instead of the persistent /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1WRPEJT-if00-port0 name I had to use the ephemeral /dev/ttyUSB0

My RFXCom devices are now all filling up the inbox. I should deal with that :-D

Closes #1163
