### ISSUE TITLE
Freebox binding: bridge thing remaining sometimes in INITIALIZING state

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab2-addons#1170]
Unfortunately, the PR #1127 seems to not have fixed fully the initialization problem.
With recent builds (432), I can sometimes see the bridge thing remaining in INITIALIZING state at startup.

**Comment by lolodomo** [comment]
@kaikreuzer : there is not a lot of code run in initialize() (of the bridge) but at least one HTTP call.Could it explain that the thing remains in INITIALIZING state ???
I can move this code to a thread and finally do nothing at all in initialize() but could the thing manager be updated to reduce a little this constraint ?

**Comment by kaikreuzer** [comment]
I have no clue. From the code it looks as if in any case an updateStatus() is called right away, so I do not know why this does not happen. Only debugging will help, I guess...
Do you see this happening in the IDE as well or only in the distro? How often does it occur?

**Comment by lolodomo** [comment]
Fix was merged.
