### ISSUE TITLE
New Atlona binding

### ISSUE THREAD

**Issue by tmrobert8** [openhab/openhab2-addons#1171]
I've written a full binding for Atlona PRO3 hdbaset matrix switches that works great on mine.  Trying to figure out the procedure to contribute it and this seems the first step (according to https://github.com/openhab/openhab-distro/blob/master/CONTRIBUTING.md).  Never used github before so the next steps are a bit murky - any advice would be great (otherwise I'll be muddling my way through the doc).

Tim
##

**Comment by kaikreuzer** [comment]
Hi Tim,

Thanks for your efforts!
The second step would be to make sure that your code respects [our guidelines](http://docs.openhab.org/developers/development/guidelines.html).
If you think all looks good, you can go ahead and create a pull request. This is fairly easy, all you need is to have a branch in your own fork on github that contains your code. The Github UI will then directly show you a button for creating a PR.
There is nothing really special in openHAB, so you can check out the standard documentation at
https://help.github.com/categories/collaborating-on-projects-using-issues-and-pull-requests/
https://help.github.com/articles/creating-a-pull-request/

One thing to be aware of is that you need to sign-off your commits by adding a line to the commit message. Please see [our docs for that](http://docs.openhab.org/developers/contributing/contributing#sign-your-work).

Good luck!

**Comment by tmrobert8** [comment]
Well - did something wrong I think.  Forked it to tmrobert8/openhab2-addons with 1171-atlona branch but when I try to create a pull request across forks - it's not listed anywhere.  Any help would be appreciated...

**Comment by tmrobert8** [comment]
Nevermind - I think I figured it out and submitted the pull request

**Comment by kaikreuzer** [comment]
Indeed :-)

**Comment by kaikreuzer** [comment]
FTR: https://github.com/openhab/openhab2-addons/pull/1176

**Comment by wborn** [comment]
This binding got merged with https://github.com/openhab/openhab2-addons/pull/1252.
