### ISSUE TITLE
[HomeKit] Color Support

### ISSUE THREAD

**Issue by saperlot** [openhab/openhab2-addons#1184]
@beowulfe My Color Item acts like a Dimmer on Homekit, is there a way to change the color with Siri?
I know command like "set light blue" are supported by Siri. Do you know how you can support this by your wonderful homekit plugin?
Cheers
##

**Comment by saperlot** [comment]
May it is now supported by just the Hue's but probably there are enhancements with IOS10?

**Comment by beowulfe** [comment]
Sorry, missed this until now @saperlot 

I'll take a look and see what it takes. I have a Hue bulb in my closet that I never setup, I'll have to get it configured and play around.

**Comment by saperlot** [comment]
No Problem, i did some reasearch on this topic, I do not have acces to their specs, But found something on the availble dev sites at apple:

>  For example, the default characteristics of a Light Bulb service are Hue, Saturation, Brightness, and On. (The On characteristic is the same as the power state characteristic type, described in Accessing Values of Characteristics.) Some characteristics are mandatory and others are optional. For example, the On characteristic is mandatory, and the Hue, Saturation, and Brightness characteristics are optional.

May you easily could add those characteristics.

**Comment by koaxfr** [comment]
Any news on this? I'm actually also very curious if controlling color item with homekit would be possible. As of right now (using souliss binding) I can only turn on/off my led strip and can't get the brightness to actually do anything.

**Comment by beowulfe** [comment]
See https://github.com/openhab/openhab2-addons/pull/1292
