### ISSUE TITLE
Harmony binding device labels disappear

### ISSUE THREAD

**Issue by rocket59** [openhab/openhab2-addons#1185]
Per the title when a device/thing is first added a label can be successfully assigned. However if the thing is subsequently edited the label will simply disappear. When inputting a label when editing, the label will no longer 'take' either.

When an additional harmony device is added or one is edited the labels of other existing devices will also disappear.

**Comment by digitaldan** [comment]
Yep I can see this as well, something is not right with how I;'m setting labels in general with this binding.  I'll take a look.

**Comment by rocket59** [comment]
Thanks!

**Comment by rocket59** [comment]
Sorry, accidentally closed the issue.

**Comment by rocket59** [comment]
Thanks for fixing this. Can I ask when will it find its way to the latest OH2 snapshot? I downloaded #452 today but the issue is still there.

**Comment by mhilbush** [comment]
Looks like there hasn't been an OH2 build in a few days.  Not sure why.  

@kaikreuzer Will the next OH2 nightly build also include an updated ESH build?  There are quite a few ESH updates since the one included in the current OH2 build (since August 3, I think).

**Comment by kaikreuzer** [comment]
> Looks like there hasn't been an OH2 build in a few days. Not sure why.

2 days to be exact. Simply because there were no code changes during that time.

> Will the next OH2 nightly build also include an updated ESH build? 

Hopefully this weekend, yes. The ESH build was very unstable over the last 2 weeks, that's why I didn't trigger a stable one. As soon as a new one is there, I will communicate this at https://community.openhab.org/c/openhab-2/news-important-changes, so make sure you are subscribed to that category.

**Comment by kaikreuzer** [comment]
FYI: https://community.openhab.org/t/diverse-updates-from-esh/13427

**Comment by rocket59** [comment]
All labels working perfectly - thanks!
