### ISSUE TITLE
Squeezebox binding not reconnecting after squeeze server restart

### ISSUE THREAD

**Issue by mhilbush** [openhab/openhab2-addons#1186]
The squeezebox binding is not reconnecting to the squeeze server following an outage or restart of the squeeze server.  This occurs when upgrading the squeeze server, applying OS patches that require a reboot of the host running the squeeze server, losing network connectivity, etc.  When this occurs, the server and player status becomes OFFLINE.  The only solution I found is to restart the binding or OH2.

In the process of diagnosing this, I also discovered the following:
- `requestPlayerJob` in `SqueezeBoxPlayerDiscoveryParticipant `is not being canceled when the `SqueezeBoxServerHandler `is removed and/or the binding is restarted;
- Squeeze server and player ONLINE/OFFLINE status is not being updated in some conditions;
- Squeeze player properties are not being saved to the player thing; and
- REFRESH is causing class cast exceptions in `handleCommand`

I'd like to submit a PR to correct the above issues.  So far I've:
- forked a copy of the openhab2-addons repo
- cloned my fork locally
- made changes to the binding files, tested, and committed to a local branch
- pushed the changes to a new branch in my fork here:
  - https://github.com/mhilbush/openhab2-addons/commit/c14bd26588a566004152b0d325ef370bf53989a3

My testing covered the following:
- verified reconnection to the server following stop/start of the squeeze server, and reboots of the host running the squeeze server;
- verfied correct status updated following deletion and rediscovery of server and player things and inbox entries in a variety of different sequences;
- verified REFRESH doesn't cause exceptions;
- verified properties are saved to the player thing;
- verified RequestPlayerJob is canceled (and scheduled) in various server handler and binding restart conditions;
- confirmed existing functionality still works.

Before I do the PR, can/should someone take a look at my changes?  This is my first PR, so I'm not completely sure I did everything right so far.

One thing I did notice is that SqueezeBoxPlayerDiscoveryParticipant.java shows many changes arising from Eclipse wanting to reformat the original code.  I didn't know what to do about that...

Thanks for any help/feedback.

**Comment by digitaldan** [comment]
Thanks for the pr!  I will absolutely take a look and get back to you as soon as I can

**Comment by digitaldan** [comment]
>Before I do the PR, can/should someone take a look at my changes? This is my first PR, so I'm not completely sure I did everything right so far.

Looks good to me, only one or two things I would comment on, why don't you go ahead and submit a PR and we can discuss on that.

>One thing I did notice is that SqueezeBoxPlayerDiscoveryParticipant.java shows many changes arising from Eclipse wanting to reformat the original code. I didn't know what to do about that...

I ported this over a while ago (and have not touched it since obviously!), since then there have been many changes to OH2/ESH which includes some formatter changes so I would not worry about it.  

I have not yet tested it out yet, I'll do that my time tonight or tomorrow.

**Comment by mhilbush** [comment]
Ok.  Thanks, Dan.  I just submitted the PR.
