### ISSUE TITLE
Milight openhab2 binding example config files

### ISSUE THREAD

**Issue by ploef** [openhab/openhab2-addons#1199]
Hi,

Because I'm frequently updating Openhab2 at the moment I realy would like to use the config files (items, things, eg.). 
Could anybody help me out here? So where and how to configure the bridge and the different (RGBW) color groups?

Regards,
Peter
##

**Comment by davidgraeff** [comment]
@ploef unfortunately I do not use the config files but if u have figured it out already I would happily add an example provided by you. In contrast to oh 1 thinks are defined in the same way across all bindings

**Comment by pfink** [comment]
When I look at #1322, it seems like @patrickse gained expierence with that. @patrickse: Maybe you could share your complete file based configuration here?

**Comment by patrickse** [comment]
Up to now, I´ve just auto-discover and just added the items I need manually to support the tags. As far as I know there are no tags in Habmin at the moment. (but maybe I am wrong). Look at #1322 there are some example items for my milight installation.

**Comment by patrickse** [comment]
Sorry for letting you wait.. got a new born at home ;)... So I finally managed to define my milight bridge as a thing inside .thing file.

```
Bridge milight:bridge:ACCF23284AA1      "Milight Bridge"@"Wohnzimmer"           [ ADDR="192.168.178.23", PORT=8899, REFRESH=2, ID="ACCF23284AA1" ]
```

**Comment by hmerk** [comment]
Doku has been updated, just a small detail for V3+ bridges missing.
This issue can be closed.
