### ISSUE TITLE
ZWave Binding- Initialization Fails with CT101

### ISSUE THREAD

**Issue by cpparkin** [openhab/openhab2-addons#1200]
ZWave Initialization fails with CT101 Radio Thermostat, no nodeX.xml created.  Log file attached.
[openhab.txt](https://github.com/openhab/openhab2-addons/files/430884/openhab.txt)

**Comment by cdjackson** [comment]
Sorry, but can you move this over to the zwave tracker - it'll get lost if we leave it here.

https://github.com/openhab/org.openhab.binding.zwave/issues/new
