### ISSUE TITLE
max binding thermostat plus missing offset values

### ISSUE THREAD

**Issue by sutyagin** [openhab/openhab2-addons#1207]
Hi
There are seems to be missing temperature offset settings for thermostat plus valve. The normal thermostat is showing all settings but not for plus. The DEBUG logs are the same for both valves but Paper and Habmin not
##

**Comment by marcelrv** [comment]
Pls assign to me. I'll check what's going on

**Comment by marcelrv** [comment]
fixed with PR #1625

**Comment by dominicdesu** [comment]
I guess this can be closed? 😃

**Comment by martinvw** [comment]
Thanks!
