### ISSUE TITLE
installed extentions become unavailable after openhab2 restart

### ISSUE THREAD

**Issue by marcotglb** [openhab/openhab2-addons#1215]
I'm using an oh2 build of about August/10.
I've used the online flavor.

I can install or deinstall JSONPATH or REGEX (or other I can imagine) extentions using PaperUI
They work fine just after installation.

Then, if i restart OH2 I see the folowing messages in the log.
2016-09-02 12:02:39.723 [WARN ] [.core.transform.TransformationHelper] - Cannot get service reference for transformation service of type REGEX
2016-09-02 12:02:39.751 [WARN ] [.core.transform.TransformationHelper] - Cannot get service reference for transformation service of type JSONPATH

Any idea about why is this happening ?
Thanks. Marco

**Comment by kaikreuzer** [comment]
I just tried it with build 469 and cannot reproduce it. Transformation services are there also after a restart.

If your problem still exists, please open the issue at https://github.com/openhab/openhab-distro/issues (which is the better place for it). Thanks!

**Comment by marcotglb** [comment]
I reinstalled  a new build yesterday (Sept/8) and it is working fine now.
Thanks-
