### ISSUE TITLE
Harmony binding missing support for manual configuration

### ISSUE THREAD

**Issue by kokossoppa** [openhab/openhab2-addons#1217]
The logitech harmony binding would benefit from support for manual (ip) configuration which is needed if the device is on a different network from the controller. In case broadcast messages are not allowed to pass the network barrier.
##

**Comment by sid3windr** [comment]
Running into the same issue here, there is no way this can be autodetected on my network, so I simply cannot use it right now :(

**Comment by wborn** [comment]
This issue should also be fixed now that https://github.com/openhab/openhab2-addons/pull/1643 has been merged. This PR should be part of recent 2.1.0-SNAPSHOT builds.
