### ISSUE TITLE
With build 469 ios client does not work properly any more

### ISSUE THREAD

**Issue by dobe77** [openhab/openhab2-addons#1224]
With build 469 the IOS client does not work properly any more. Any chart containing more than one item is empty and the roller shutter controls are shown only as buttons. The basic web ui is working properly and the IOS client was working with build 447

**Comment by kaikreuzer** [comment]
Right, this is the equivalent of https://github.com/openhab/openhab.android/issues/219 for Android.
I hope that this can soon be fixed and a new release being pushed out to the AppStore.

**Comment by kaikreuzer** [comment]
I moved this issue to the right place at https://github.com/openhab/openhab.ios/issues/85.
