### ISSUE TITLE
Fibaro System FGS223 - unknown device

### ISSUE THREAD

**Issue by itrahk** [openhab/openhab2-addons#1226]
Hi I'm new to openhab so forgive me if I ask obvious questions. I've just connected Fibaro Double switch (FGS223) but it is discovered as Unknown Device - Z-Wave Node 2 (010F:0203:1000:3.2). I checked device database, and the device is there (http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/416). Should I do anything else to somehow refresh device database or can import product file manually (it is an export option on database website) to my OH2? 

I would be grateful for any help.

Regards
itrah

**Comment by cdjackson** [comment]
What version of the binding are you using?

Also, please note that this isn’t the right place to raise ZWave issues as there’s a separate zwave issue list …

https://github.com/openhab/org.openhab.binding.zwave/issues <https://github.com/openhab/org.openhab.binding.zwave/issues>

**Comment by itrahk** [comment]
Hi, I'm using "binding-zwave - 2.0.0.SNAPSHOT"

I didn't know there is special place for zwave issue (this one was in oh2 docs page), should I close it here and submit new one in proper place?

**Comment by cdjackson** [comment]
Yes - it would be better to move this to the correct issue list.

When you open the new request, can you state the actual version number (or the date or something). Every version ever made (well, nearly) has this number at the moment, so I need to know if you’re using the most recent version.

**Comment by itrahk** [comment]
How can I determine the actual version?

**Comment by cdjackson** [comment]
The easiest way is to log on to the console and use the list command.

**Comment by itrahk** [comment]
I've opened the issue in the proper place (https://github.com/openhab/org.openhab.binding.zwave/issues/88), thanks.
