### ISSUE TITLE
Home-Kit "Not Supported"

### ISSUE THREAD

**Issue by grouchal** [openhab/openhab2-addons#1253]
With the new iOS 10 Home app - I have decided to setup HomeKit and Openhab to work together properly - after trying it earlier in the year.

I have a raspberry Pi with Openhab 2 Beta 4, for testing this config

I have setup everything in a standard way and have only two accessories that are configured for HomeKit.

Am I doing something wrong here or is this a "known issue" with iOS 10?

When I have connect to openhab from iOS Home though I get the following messages:

![image 22-09-2016 at 11 28 copy](https://cloud.githubusercontent.com/assets/232846/18743146/fb2ac616-80b7-11e6-8e10-1e2192e59fdc.jpg)

![image 22-09-2016 at 11 24](https://cloud.githubusercontent.com/assets/232846/18742994/438a7826-80b7-11e6-9867-efa0d1314b94.jpg)

**Comment by neohusky** [comment]
No problem here, however, from time to time I get the status as updating and the accessory is unresponsive through HomeKit despite working trough openHAB. 

![img_1905](https://cloud.githubusercontent.com/assets/1212618/18744096/c0578252-80ff-11e6-9573-45bb7b84ba9f.PNG)
![img_1906](https://cloud.githubusercontent.com/assets/1212618/18744097/c0598962-80ff-11e6-84df-2a0fa0d656fe.PNG)

**Comment by grouchal** [comment]
I have used the non native iOS App "Home" to install the bridge and all is working now!

**Comment by ogillin** [comment]
@grouchal what did you mean by the non native iOS App "Home"?

**Comment by grouchal** [comment]
There is an app in the App Store called ‘Home’
