### ISSUE TITLE
Tags breaks *.items file

### ISSUE THREAD

**Issue by regnets** [openhab/openhab2-addons#1259]
If i add tags for homekit the item definition is unable to be parsed by homekit. 

In my example alle items to "S_BR_Bed1_D" are getting parsed correctly, after that all items are missing.

This is reproducible with a complete new installation and this item file. If i remove the Tags, the item file is imported correctly.

Here is the corresponding thread in the forum
https://community.openhab.org/t/whats-wrong-with-this-items-file/14426/11

Here is the *.items file:
```
/* Prefixes:
 * H = House
 * R = Room
 * C = Cluster
 * S = Single
 *
 * Room Abbreviations:
 * LR = Living Room
 * BR = Bedroom
 * HW = Hallway
 * GR = Guestroom
 *
 * Postfixes:
 * S = Switch
 * D = Dimmer
 * T = Temperature
 * C = Color
 *   = no Extension -> this groups are only intended to create a hierarchical structure for the gui so that the debugging of problems gets easier.
 *
 * itemtype itemname ["labeltext"] [<iconname>] [(group1, group2, ...)] [{bindingconfig}]
 */

/*
 * House Groups
 */
Group H_Lamps "All Lamps" <light>
String H_Scene "Scene" <video>
Group:Switch:OR(ON, OFF) H_Lamps_S "All Lamps" <light>
Group:Dimmer:AVG H_Lamps_D "All Lamps Dimmer" <dimmablelight>
Group:Dimmer:AVG H_Lamps_T "All Lamps Color Temperature" <colorlight>
Group:Color:AVG H_Lamps_C "All Lamps Color" <colorlight>

/*
 * Room Groups
 * Every Room needs a Group to Turn Off all Lamps at Once - Even ih there is only one Light!
 */
Group R_LR "Livingroom Lamps" <light> (H_Lamps)
String R_LR_Scene "Scene" <video>
Group:Switch:OR(ON, OFF) R_LR_S "Livingroom Lamps" <light> (H_Lamps_S)
Group:Dimmer:AVG R_LR_D "Livingroom Dimmer" <dimmablelight> (H_Lamps_D)
Group:Dimmer:AVG R_LR_T "Livingroom Temperature" <colorlight> (H_Lamps_T)
Group:Color:AVG R_LR_C "Livingroom Color" <colorlight> (H_Lamps_C)

Group R_BR "Bedroom Lamps" <light> (H_Lamps)
String R_BR_Scene "Scene" <video>
Group:Switch:OR(ON, OFF) R_BR_S "Bedroom Lamps" <light> (H_Lamps_S)
Group:Dimmer:AVG R_BR_D "Bedroom Dimmer" <dimmablelight> (H_Lamps_D)
Group:Dimmer:AVG R_BR_T "Bedroom Temperature" <colorlight> (H_Lamps_T)
Group:Color:AVG R_BR_C "Bedroom Color" <colorlight> (H_Lamps_C)

Group R_HW "Hallway Lamps" <light> (H_Lamps)
String R_HW_Scene "Scene" <video>
Group:Switch:OR(ON, OFF) R_HW_S "Hallway Lamps" <light> (H_Lamps_S)
Group:Dimmer:AVG R_HW_D "Hallway Dimmer" <dimmablelight> (H_Lamps_D)
Group:Dimmer:AVG R_HW_T "Hallway Temperature" <colorlight> (H_Lamps_T)
Group:Color:AVG R_HW_C "Hallway Color" <colorlight> (H_Lamps_C)

Group R_GR "Guestroom Lamps" <light> (H_Lamps)
String R_GR_Scene "Scene" <video>
Group:Switch:OR(ON, OFF) R_GR_S "Guestroom Lamps" <light> (H_Lamps_S)
Group:Dimmer:AVG R_GR_D "Guestroom Dimmer" <dimmablelight> (H_Lamps_D)
Group:Dimmer:AVG R_GR_T "Guestroom Temperature" <colorlight> (H_Lamps_T)
Group:Color:AVG R_GR_C "Guestroom Color" <colorlight> (H_Lamps_C)


/*
 * Cluster Groups
 * We only need Cluster Groups, where we got two or more Lights which should work as one Light!
 * Single Lamps can be directly added to the Room!
 */

/*
 * The Signal Cluster Group is special, the Signal Lamps are in different Rooms, so they are not assigned
 * to a room, however they are directly subordinated to the house. Also they are not intended to be switched by
 * homekit so they don't get exposed by the homekit bridge (no tagging)
 */
Group C_Signal "All Signal Lamps" <light> (H_Lamps)
Group:Switch:OR(ON, OFF) C_Signal_S "All Signal" <light>
Group:Dimmer:AVG C_Signal_D "All Signal Dimmer" <dimmablelight>
Group:Color:AVG C_Signal_C "All Signal Color" <colorlight>

Group C_LR_DiningTable "Dining Table" <light> (R_LR)
Group:Switch:AND(ON, OFF) C_LR_DiningTable_S "Dining Table" <light> (R_LR_S)
Group:Dimmer:AVG C_LR_DiningTable_D "Dining Table Dimmer" <dimmablelight> (R_LR_D) ["Lighting"]

Group C_LR_Couch "Couch" <light> (R_LR)
Group:Switch:AND(ON, OFF) C_LR_Couch_S "Couch" <light> (R_LR_S)
Group:Dimmer:AVG C_LR_Couch_D "Couch Dimmer" <dimmablelight> (R_LR_D) ["Lighting"]
Group:Dimmer:AVG C_LR_Couch_T "Couch Temperature" <colorlight> (R_LR_T)
Group:Color:AVG C_LR_Couch_C "Couch Color" <colorlight> (R_LR_C)

Group C_LR_Books "Books" <light> (R_LR)
Group:Switch:AND(ON, OFF) C_LR_Books_S "Books" <light> (R_LR_S)
Group:Dimmer:AVG C_LR_Books_D "Books Dimmer" <dimmablelight> (R_LR_D) ["Lighting"]
Group:Dimmer:AVG C_LR_Books_T "Books Temperature" <colorlight> (R_LR_T)
Group:Color:AVG C_LR_Books_C "Books Color" <colorlight> (R_LR_C)

Group C_BR_Bed "Bed" <light> (R_BR)
Group:Switch:AND(ON, OFF) C_BR_Bed_S "Bed" <light> (R_BR_S)
Group:Dimmer:AVG C_BR_Bed_D "Bed Dimmer" <dimmablelight> (R_BR_D) ["Lighting"]
Group:Color:AVG C_BR_Bed_C "Bed Color" <colorlight> (R_BR_C)

Group C_GR_Bed "Bed" <light> (R_GR)
Group:Switch:AND(ON, OFF) C_GR_Bed_S "Bed" <light> (R_GR_S)
Group:Dimmer:AVG C_GR_Bed_D "Bed Dimmer" <dimmablelight> (R_GR_D) ["Lighting"]
Group:Dimmer:AVG C_GR_Bed_T "Bed Temperature" <colorlight> (R_GR_T)


/*
 * Single Lamps! Finally!
 */
Switch S_Signal1_S "Signal Livingroom" (C_Signal_S, C_Signal) { channel="hue:0200:00178827902c:6:brightness" }
Switch S_Signal2_S "Signal Hallway"  (C_Signal_S, C_Signal) { channel="hue:0200:00178827902c:7:brightness" }
Dimmer S_Signal1_D "Signal Livingroom Dimmer"  (C_Signal_D, C_Signal) { channel="hue:0200:00178827902c:6:brightness" }
Dimmer S_Signal2_D "Signal Hallway Dimmer" (C_Signal_D, C_Signal) { channel="hue:0200:00178827902c:7:brightness" }
Color S_Signal1_C "Signal Livingroom Color" (C_Signal_C, C_Signal) { channel="hue:0200:00178827902c:6:color" }
Color S_Signal2_C "Signal Hallway Color" (C_Signal_C, C_Signal) { channel="hue:0200:00178827902c:7:color" }

Switch S_LR_DiningTable1_S "Dining Table 1" (C_LR_DiningTable_S, C_LR_DiningTable) { channel="hue:0100:00178827902c:11:brightness" }
Switch S_LR_DiningTable2_S "Dining Table 2" (C_LR_DiningTable_S, C_LR_DiningTable) { channel="hue:0100:00178827902c:12:brightness" }
Dimmer S_LR_DiningTable1_D "Dining Table 1 Dimmer" (C_LR_DiningTable_D, C_LR_DiningTable) { channel="hue:0100:00178827902c:11:brightness" }
Dimmer S_LR_DiningTable2_D "Dining Table 2 Dimmer" (C_LR_DiningTable_D, C_LR_DiningTable) { channel="hue:0100:00178827902c:12:brightness" }

Switch S_LR_Couch1_S "Couch 1" (C_LR_Couch_S, C_LR_Couch) { channel="hue:0210:00178827902c:1:brightness" }
Switch S_LR_Couch2_S "Couch 2" (C_LR_Couch_S, C_LR_Couch) { channel="hue:0210:00178827902c:2:brightness" }
Switch S_LR_Couch3_S "Couch 3" (C_LR_Couch_S, C_LR_Couch) { channel="hue:0210:00178827902c:3:brightness" }
Dimmer S_LR_Couch1_D "Couch 1 Dimmer" (C_LR_Couch_D, C_LR_Couch) { channel="hue:0210:00178827902c:1:brightness" }
Dimmer S_LR_Couch2_D "Couch 2 Dimmer" (C_LR_Couch_D, C_LR_Couch) { channel="hue:0210:00178827902c:2:brightness" }
Dimmer S_LR_Couch3_D "Couch 3 Dimmer" (C_LR_Couch_D, C_LR_Couch) { channel="hue:0210:00178827902c:3:brightness" }
Dimmer S_LR_Couch1_T "Couch 1 Temperature" (C_LR_Couch_T, C_LR_Couch) { channel="hue:0210:00178827902c:1:color_temperature" }
Dimmer S_LR_Couch2_T "Couch 2 Temperature" (C_LR_Couch_T, C_LR_Couch) { channel="hue:0210:00178827902c:2:color_temperature" }
Dimmer S_LR_Couch3_T "Couch 3 Temperature" (C_LR_Couch_T, C_LR_Couch) { channel="hue:0210:00178827902c:3:color_temperature" }
Color S_LR_Couch1_C "Couch 1 Color" (C_LR_Couch_C, C_LR_Couch) { channel="hue:0210:00178827902c:1:color" }
Color S_LR_Couch2_C "Couch 2 Color" (C_LR_Couch_C, C_LR_Couch) { channel="hue:0210:00178827902c:2:color" }
Color S_LR_Couch3_C "Couch 3 Color" (C_LR_Couch_C, C_LR_Couch) { channel="hue:0210:00178827902c:3:color" }

Switch S_LR_Books1_S "Books 1" (C_LR_Books_S, C_LR_Books) { channel="hue:0210:00178827902c:15:brightness" }
Switch S_LR_Books2_S "Books 2" (C_LR_Books_S, C_LR_Books) { channel="hue:0210:00178827902c:16:brightness" }
Dimmer S_LR_Books1_D "Books 1 Dimmer" (C_LR_Books_D, C_LR_Books) { channel="hue:0210:00178827902c:15:brightness" }
Dimmer S_LR_Books2_D "Books 2 Dimmer" (C_LR_Books_D, C_LR_Books) { channel="hue:0210:00178827902c:16:brightness" }
Dimmer S_LR_Books1_T "Books 1 Temperature" (C_LR_Books_T, C_LR_Books) { channel="hue:0210:00178827902c:15:color_temperature" }
Dimmer S_LR_Books2_T "Books 2 Temperature" (C_LR_Books_T, C_LR_Books) { channel="hue:0210:00178827902c:16:color_temperature" }
Color S_LR_Books1_C "Books 1 Color" (C_LR_Books_C, C_LR_Books) { channel="hue:0210:00178827902c:15:color" }
Color S_LR_Books2_C "Books 2 Color" (C_LR_Books_C, C_LR_Books) { channel="hue:0210:00178827902c:16:color" }


Switch S_BR_Bed1_S "Bed 1" (C_BR_Bed_S, C_BR_Bed) { channel="hue:0200:00178827902c:8:brightness" }
Switch S_BR_Bed2_S "Bed 2" (C_BR_Bed_S, C_BR_Bed) { channel="hue:0200:00178827902c:9:brightness" }
Dimmer S_BR_Bed1_D "Bed 1 Dimmer" (C_BR_Bed_D, C_BR_Bed) { channel="hue:0200:00178827902c:8:brightness" } ["Lighting"]
Dimmer S_BR_Bed2_D "Bed 2 Dimmer" (C_BR_Bed_D, C_BR_Bed) { channel="hue:0200:00178827902c:9:brightness" } ["Lighting"]
Color S_BR_Bed1_C "Bed 1 Color" (C_BR_Bed_C, C_BR_Bed) { channel="hue:0200:00178827902c:8:color" }
Color S_BR_Bed2_C "Bed 2 Color" (C_BR_Bed_C, C_BR_Bed) { channel="hue:0200:00178827902c:9:color" }


Switch S_GR_Bed1_S "Bed 1" (C_GR_Bed_S, C_GR_Bed) { channel="hue:0220:00178827902c:13:brightness" }
Switch S_GR_Bed2_S "Bed 2" (C_GR_Bed_S, C_GR_Bed) { channel="hue:0220:00178827902c:14:brightness" }
Dimmer S_GR_Bed1_D "Bed 1 Dimmer" (C_GR_Bed_D, C_GR_Bed) { channel="hue:0220:00178827902c:13:brightness" } ["Lighting"]
Dimmer S_GR_Bed2_D "Bed 2 Dimmer" (C_GR_Bed_D, C_GR_Bed) { channel="hue:0220:00178827902c:14:brightness" } ["Lighting"]
Dimmer S_GR_Bed1_T "Bed 1 Temperature" (C_GR_Bed_T, C_GR_Bed) { channel="hue:0220:00178827902c:13:color_temperature" }
Dimmer S_GR_Bed2_T "Bed 2 Temperature" (C_GR_Bed_T, C_GR_Bed) { channel="hue:0220:00178827902c:14:color_temperature" }

Switch S_GR_Ceiling_S "Ceiling" (R_GR_S, R_GR) { channel="hue:0100:00178827902c:17:brightness" }
Dimmer S_GR_Ceiling_D "Ceiling Dimmer" (R_GR_D, R_GR) { channel="hue:0100:00178827902c:17:brightness" } ["Lighting"]

Switch S_HW_Shelf_S "Shelf" (R_HW_S, R_HW) { channel="hue:0220:00178827902c:10:brightness" }
Dimmer S_HW_Shelf_D "Shelf Dimmer" (R_HW_D, R_HW) { channel="hue:0220:00178827902c:10:brightness" } ["Lighting"]
Dimmer S_HW_Shelf_T "Shelf Temperature" (R_HW_D, R_HW) { channel="hue:0220:00178827902c:10:color_temperature" }

Switch S_HW_Ceiling_S "Ceiling" (R_HW_S, R_HW) { channel="hue:0100:00178827902c:18:brightness" }
Dimmer S_HW_Ceiling_D "Ceiling Dimmer" (R_HW_D, R_HW) { channel="hue:0100:00178827902c:18:brightness" } ["Lighting"]

Switch S_BR_Ceiling_S "Ceiling" (R_BR_S, R_BR) { channel="hue:0210:00178827902c:19:brightness" }
Dimmer S_BR_Ceiling_D "Ceiling Dimmer" (R_BR_D, R_BR) { channel="hue:0210:00178827902c:19:brightness" } ["Lighting"]
Dimmer S_BR_Ceiling_T "Ceiling Temperature" (R_BR_T, R_BR) { channel="hue:0210:00178827902c:19:color_temperature" }
Color S_BR_Ceiling_C "Ceiling Color" (R_BR_C, R_BR) { channel="hue:0210:00178827902c:19:color" }

```

Here is what i get from the homekit emulation (http://<openhab>:9124/accessories)
``{"accessories":[{"aid":1415068200,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","events":false,"bonjour":false,"description":"Name of the accessory","value":"Bed Dimmer","maxLen":255},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","events":false,"bonjour":false,"description":"The name of the manufacturer","value":"none","maxLen":255},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","events":false,"bonjour":false,"description":"The name of the model","value":"none","maxLen":255},{"iid":5,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","events":false,"bonjour":false,"description":"The serial number of the accessory","value":"none","maxLen":255},{"iid":6,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","events":false,"bonjour":false,"description":"Identifies the accessory via a physical action on the accessory"}]},{"iid":7,"type":"00000043-0000-1000-8000-0026BB765291","characteristics":[{"iid":8,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","events":false,"bonjour":false,"description":"Name of the accessory","value":"Bed Dimmer","maxLen":255},{"iid":9,"type":"00000025-0000-1000-8000-0026BB765291","perms":["pw","pr","ev"],"format":"bool","events":false,"bonjour":false,"description":"Turn on and off","value":true}]}]},{"aid":1,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","events":false,"bonjour":false,"description":"Name of the accessory","value":"openHAB","maxLen":255},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","events":false,"bonjour":false,"description":"The name of the manufacturer","value":"openHAB","maxLen":255},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","events":false,"bonjour":false,"description":"The name of the model","value":"2.0.0.201609240823","maxLen":255},{"iid":5,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","events":false,"bonjour":false,"description":"The serial number of the accessory","value":"none","maxLen":255},{"iid":6,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","events":false,"bonjour":false,"description":"Identifies the accessory via a physical action on the accessory"}]}]},{"aid":684978930,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","events":false,"bonjour":false,"description":"Name of the accessory","value":"Dining Table Dimmer","maxLen":255},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","events":false,"bonjour":false,"description":"The name of the manufacturer","value":"none","maxLen":255},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","events":false,"bonjour":false,"description":"The name of the model","value":"none","maxLen":255},{"iid":5,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","events":false,"bonjour":false,"description":"The serial number of the accessory","value":"none","maxLen":255},{"iid":6,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","events":false,"bonjour":false,"description":"Identifies the accessory via a physical action on the accessory"}]},{"iid":7,"type":"00000043-0000-1000-8000-0026BB765291","characteristics":[{"iid":8,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","events":false,"bonjour":false,"description":"Name of the accessory","value":"Dining Table Dimmer","maxLen":255},{"iid":9,"type":"00000025-0000-1000-8000-0026BB765291","perms":["pw","pr","ev"],"format":"bool","events":false,"bonjour":false,"description":"Turn on and off","value":true}]}]},{"aid":1894787595,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","events":false,"bonjour":false,"description":"Name of the accessory","value":"Couch Dimmer","maxLen":255},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","events":false,"bonjour":false,"description":"The name of the manufacturer","value":"none","maxLen":255},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","events":false,"bonjour":false,"description":"The name of the model","value":"none","maxLen":255},{"iid":5,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","events":false,"bonjour":false,"description":"The serial number of the accessory","value":"none","maxLen":255},{"iid":6,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","events":false,"bonjour":false,"description":"Identifies the accessory via a physical action on the accessory"}]},{"iid":7,"type":"00000043-0000-1000-8000-0026BB765291","characteristics":[{"iid":8,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","events":false,"bonjour":false,"description":"Name of the accessory","value":"Couch Dimmer","maxLen":255},{"iid":9,"type":"00000025-0000-1000-8000-0026BB765291","perms":["pw","pr","ev"],"format":"bool","events":false,"bonjour":false,"description":"Turn on and off","value":true}]}]},{"aid":1539185283,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","events":false,"bonjour":false,"description":"Name of the accessory","value":"Bed Dimmer","maxLen":255},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","events":false,"bonjour":false,"description":"The name of the manufacturer","value":"none","maxLen":255},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","events":false,"bonjour":false,"description":"The name of the model","value":"none","maxLen":255},{"iid":5,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","events":false,"bonjour":false,"description":"The serial number of the accessory","value":"none","maxLen":255},{"iid":6,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","events":false,"bonjour":false,"description":"Identifies the accessory via a physical action on the accessory"}]},{"iid":7,"type":"00000043-0000-1000-8000-0026BB765291","characteristics":[{"iid":8,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","events":false,"bonjour":false,"description":"Name of the accessory","value":"Bed Dimmer","maxLen":255},{"iid":9,"type":"00000025-0000-1000-8000-0026BB765291","perms":["pw","pr","ev"],"format":"bool","events":false,"bonjour":false,"description":"Turn on and off","value":true}]}]},{"aid":1001991687,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","events":false,"bonjour":false,"description":"Name of the accessory","value":"Books Dimmer","maxLen":255},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","events":false,"bonjour":false,"description":"The name of the manufacturer","value":"none","maxLen":255},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","events":false,"bonjour":false,"description":"The name of the model","value":"none","maxLen":255},{"iid":5,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","events":false,"bonjour":false,"description":"The serial number of the accessory","value":"none","maxLen":255},{"iid":6,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","events":false,"bonjour":false,"description":"Identifies the accessory via a physical action on the accessory"}]},{"iid":7,"type":"00000043-0000-1000-8000-0026BB765291","characteristics":[{"iid":8,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","events":false,"bonjour":false,"description":"Name of the accessory","value":"Books Dimmer","maxLen":255},{"iid":9,"type":"00000025-0000-1000-8000-0026BB765291","perms":["pw","pr","ev"],"format":"bool","events":false,"bonjour":false,"description":"Turn on and off","value":true}]}]}]}`
`

I don't get any errors in the openhab.log besides this error, which is expected as the item couldn't be parsed:
```
2016-09-24 10:41:57.796 [WARN ] [assic.internal.render.SwitchRenderer] - Cannot determine item type of 'S_GR_Ceiling_S'
org.eclipse.smarthome.core.items.ItemNotFoundException: Item 'S_GR_Ceiling_S' could not be found in the item registry
        at org.eclipse.smarthome.core.internal.items.ItemRegistryImpl.getItem(ItemRegistryImpl.java:148)[96:org.eclipse.smarthome.core:0.9.0.201609151119]
        at org.eclipse.smarthome.ui.internal.items.ItemUIRegistryImpl.getItem(ItemUIRegistryImpl.java:609)[130:org.eclipse.smarthome.ui:0.9.0.201609151119]
        at org.eclipse.smarthome.ui.classic.internal.render.SwitchRenderer.renderWidget(SwitchRenderer.java:57)[179:org.eclipse.smarthome.ui.classic:0.9.0.201609151119]
        at org.eclipse.smarthome.ui.classic.internal.render.PageRenderer.renderWidget(PageRenderer.java:166)[179:org.eclipse.smarthome.ui.classic:0.9.0.201609151119]
        at org.eclipse.smarthome.ui.classic.internal.render.PageRenderer.processChildren(PageRenderer.java:123)[179:org.eclipse.smarthome.ui.classic:0.9.0.201609151119]
        at org.eclipse.smarthome.ui.classic.internal.render.PageRenderer.processChildren(PageRenderer.java:144)[179:org.eclipse.smarthome.ui.classic:0.9.0.201609151119]
        at org.eclipse.smarthome.ui.classic.internal.render.PageRenderer.processPage(PageRenderer.java:86)[179:org.eclipse.smarthome.ui.classic:0.9.0.201609151119]
        at org.eclipse.smarthome.ui.classic.internal.servlet.WebAppServlet.service(WebAppServlet.java:160)[179:org.eclipse.smarthome.ui.classic:0.9.0.201609151119]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)[79:org.eclipse.jetty.servlet:9.2.14.v20151106]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)[79:org.eclipse.jetty.servlet:9.2.14.v20151106]
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:70)[165:org.ops4j.pax.web.pax-web-jetty:4.2.4]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)[78:org.eclipse.jetty.server:9.2.14.v20151106]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)[77:org.eclipse.jetty.security:9.2.14.v20151106]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)[78:org.eclipse.jetty.server:9.2.14.v20151106]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)[78:org.eclipse.jetty.server:9.2.14.v20151106]
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:271)[165:org.ops4j.pax.web.pax-web-jetty:4.2.4]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)[79:org.eclipse.jetty.servlet:9.2.14.v20151106]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)[78:org.eclipse.jetty.server:9.2.14.v20151106]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)[78:org.eclipse.jetty.server:9.2.14.v20151106]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)[78:org.eclipse.jetty.server:9.2.14.v20151106]
        at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)[165:org.ops4j.pax.web.pax-web-jetty:4.2.4]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)[78:org.eclipse.jetty.server:9.2.14.v20151106]
        at org.eclipse.jetty.server.Server.handle(Server.java:499)[78:org.eclipse.jetty.server:9.2.14.v20151106]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)[78:org.eclipse.jetty.server:9.2.14.v20151106]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)[78:org.eclipse.jetty.server:9.2.14.v20151106]
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)[70:org.eclipse.jetty.io:9.2.14.v20151106]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)[81:org.eclipse.jetty.util:9.2.14.v20151106]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)[81:org.eclipse.jetty.util:9.2.14.v20151106]
        at java.lang.Thread.run(Unknown Source)[:1.8.0_74]
2016-09-24 10:41:57.799 [ERROR] [ui.internal.items.ItemUIRegistryImpl] - Cannot retrieve item 'S_GR_Ceiling_S' for widget org.eclipse.smarthome.model.sitemap.Switch
```

If you need any other information feel free to ask, i wasn't sure which debugging needs to be enabled.

Whats really bugging me is that the first five tags get imported/parsed correctly and if i add an additional tag to a group file, this also gets parsed and presented to the homekit interface. 

So the tags are not working for simple Dimmer items?

**Comment by kaikreuzer** [comment]
This sounds weird and from your description, this is a general problem in the item file parser.
I'd therefore like to ask you to open an issue at https://github.com/eclipse/smarthome/issues instead.
In order to make it easily reproducible and help on the analysis, it would be great if you could come up with a minimal item file on which this error occurs (I guess you won't need to define more than 3 items to reproduce it?). Doing a `smarthome:items` on the console should then show that not all defined items are available in the system, which would clearly show that there is a bug. Thanks!

**Comment by regnets** [comment]
Hi Kai, that was my mistake. the Tag hast du before the channel definition, sorry for that.
