### ISSUE TITLE
forceUpdate=true for Homematic binding not possible via .items file

### ISSUE THREAD

**Issue by mhaack** [openhab/openhab2-addons#1264]
Hello,

how can I set forceUpdate=true for Homematic items in OH2 in my .items file? Could not find any working sample or hint on https://github.com/openhab/openhab2-addons/tree/master/addons/binding/org.openhab.binding.homematic.
The only way I can set forceUpdate to true is via Paper UI, but I would like to config this via the .items file.

Thx
Markus
##

**Comment by kaikreuzer** [comment]
You cannot configure anything in an items file. Do you refer to a things file?

**Comment by mhaack** [comment]
I tried 
`String Switch_GF_Floor_1_Display        "Alarmschalter Flur EG Display"           <wallswitch>  (gHouse)                                {channel="homematic:HG-HM-Dis-EP-WM55:ccu:NEQXXXXXX:3#SUBMIT",forceUpdate=true}`

in the .items file.
I'm fine with defining forceUpdate=true in the .things file as well, but also here i could not find anything doc.

**Comment by kaikreuzer** [comment]
As I said, it is not possible to do anything like this in an item file.

I checked the documentation at https://github.com/openhab/openhab2-addons/tree/master/addons/binding/org.openhab.binding.homematic and no "forceUpdate" configuration value is mentioned there at all. It seems that only existed for the 1.x binding.

**Comment by mhaack** [comment]
But it is there: https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/model/HmDatapointConfig.java#L20 and I can configure it via the Paper UI and it works.

I know it is not mentioned thats why I asked how to configure it via file.

**Comment by kaikreuzer** [comment]
Ok, sorry, let's ask @gerrieg: Could you please add some documentation to the README.md about this configuration value?

**Comment by gerrieg** [comment]
It's not documented because i also don't know how to configure it outside PaperUI. I was hoping that Kai can tell us, it's a channel configuration.

**Comment by kaikreuzer** [comment]
@gerrieg The DSL is documented [here](https://www.eclipse.org/smarthome/documentation/features/dsl.html#defining-channels) and there is an example for a channel configuration in it.

**Comment by manuelm** [comment]
@kaikreuzer Tried that. Doesn't work. All custom channel configurations are created for channel group id `0`.


e.g. this example configurations:
```
Bridge homematic:bridge:mybridge [ gatewayAddress="localhost" ]

Thing homematic:HG-HM-TC-IT-WM-W-EU:mybridge:LEQ1070123 (homematic:bridge:mybridge) {
        Channels:
                State Number : 2#SET_TEMPERATURE [
                        delay="3.5"
                ]
}
```
Results in: `Datapoint 'LEQ1070123:0#2' not found on gateway 'homegear' to UNINITIALIZED (HANDLER_MISSING_ERROR)`


Looking at the code I don't think its actually possible to specify a channel group. see [GenericThingProvider.xtend#L353](https://github.com/eclipse/smarthome/blob/master/bundles/model/org.eclipse.smarthome.model.thing/src/org/eclipse/smarthome/model/thing/internal/GenericThingProvider.xtend#L353) and [ChannelUID.java#L42](https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/ChannelUID.java#L42)

**Comment by kaikreuzer** [comment]
Hm, interesting. It is correct that you cannot define channel groups for Things (see also https://github.com/eclipse/smarthome/issues/1118), but for the use case here, it should be possible to "overwrite" an existing channel of the Thing type through the DSL (because that would be the only chance to provide the configuration). For this, we probably need to support the "#" notation of channel IDs.
@sjka Do you think it would work to make the parser correctly handle "2#SET_TEMPERATURE" as a channel ID or are we missing something more crucial?

**Comment by sjka** [comment]
> Do you think it would work to make the parser correctly handle "2#SET_TEMPERATURE" as a channel ID

Yes, that should work: eclipse/smarthome#2762
