### ISSUE TITLE
Hue Emulation with color lights?

### ISSUE THREAD

**Issue by ertanden** [openhab/openhab2-addons#1266]
I'm pairing Hue Emulation addon with my Logitech Harmony, instead of directly pairing with the Philips Hue bridge, because Logitech Harmony doesn't allow more than one Hue bridge pairings.

This gives me the advantage to be able to control other devices (Z-wave etc.) in addition to Philips Hue lights, through openhab.

However I noticed that I can't control the color of my lights with this setup. Is it possible to implement this behaviour in the Hue Emulation addon? I guess this will also be beneficial for people with Z-Wave color lights.

**Comment by digitaldan** [comment]
I don't think is should be hard, I'm actually in that code this week, I'll make a note to see what I can do, thanks for the suggestion.
