### ISSUE TITLE
[sony] Sony Bravia JSON/XML RPC support

### ISSUE THREAD

**Issue by smyrman** [openhab/openhab2-addons#1268]
Wanted to comment on the Openhab Forum first, but it appears to be down. @tmrobert8, I saw  #1249, and was hoping someone have time for adding support for older Bravia TVs as well through the JSON/XML RPC API. As for how to control this TV, it's pretty straightforward, but I have very little Java experience.

I have a SONY BRAVIA KDL-55W807A -- Unfortunately it does not support the Simple IP (Low level protocol), which is used for #1249. It does however have a higher level JSON/XML RPC protocol that is rather straightforward to use.
# Howto

I did write a bash script previously to send XML to my Sony from Domoticz, and that was pretty easy... I got the information I needed from:  https://www.domoticz.com/forum/viewtopic.php?t=8301#p56880.

Really one just need a static string for the XML except for the control code to send (Pseudo code):

``` go
body := `<?xml version="1.0"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
  <s:Body>
    <u:X_SendIRCC xmlns:u="urn:schemas-sony-com:service:IRCC:1">
      <IRCCCode>` + code + `</IRCCCode>
    </u:X_SendIRCC>
  </s:Body>
</s:Envelope>`
```

The JSON RPC also has an endpoint to list all the control codes that could be used for discovery purposes. See previously linked forum post.
##

**Comment by kaikreuzer** [comment]
> but it appears to be down.

It is up again now!

**Comment by tmrobert8** [comment]
I'm writing support for sony IRCC service implementations right now (about 60% done).  While I'm writing it for my bluray player - it supports any sony IRCC service device (including bravia tvs, home avs, etc).  Won't say it will work out of the box for you since I only have my 2015 bravia tv & bluray to test with but if you don't mind testing when it's completed - should be able to make it work.

**Comment by smyrman** [comment]
I would love to test it when it's ready for that:-) Just give me a ping either on this issue, or another one which I can subscribe to.

**Comment by tmrobert8** [comment]
Just keep an eye out on the sony binding thread over at the openhab community forum - I'll announce it there.  Probably another two weeks or so before I feel comfortable with it.
