### ISSUE TITLE
hue emulator - multiple network interfaces on openhab

### ISSUE THREAD

**Issue by aaronbailey8** [openhab/openhab2-addons#1280]
Hi all - not sure if this the right place to ask for help - let me know if theres somewhere better I could try... 

I've been running openhab/openhab2 for around a year now - and have just purchased an amazon echo. I've installed the hue emulator binding and I can see in the logs that it is activated at /api - however the echo never detects it. 

When i check /api/discovery.xml the < URLBase > IP is a different IP to the main ip used on the server openhab is installed on.  That server has 2 interfaces, 10.20.1.1 and 192.168.1.2
the 10.20.1.x range is what the rest of my home is connected to, and where the echo is connected. 

Is it possible the echo is not finding the hue emulator because its being advertised on the 192.168.1.x interface and not the 10.20.1.x interface? 

I'm also running the homekit bridge (beowulfe) and this runs fine but I did have to configure it to use the correct interface with this setting org.openhab.homekit:networkInterface=10.20.1.1

Any help or advice would be much appreciated. 

Thanks Aaron

**Comment by digitaldan** [comment]
Yes that is very likely the issue, we try to attach to the first non loopback address.  Let me take a look and see if I can make this configurable.

**Comment by aaronbailey8** [comment]
This has worked perfectly!
Thank you. and for getting it fixed so quickly! 👍
