### ISSUE TITLE
Harmony Hub Channel for 'Current Activity' is duplicated

### ISSUE THREAD

**Issue by realroywalker** [openhab/openhab2-addons#1287]
As per the title, I noticed that both of my harmony hubs display the same channel multiple times.
They all seem to be 'linked' as disabling one channel by clicking the blue icon changes the state on all of them.

I did have 3 instances of each channel but at some point another has appeared! :-s

![image](https://cloud.githubusercontent.com/assets/486860/19056748/10638126-89c3-11e6-820a-c53487a186c0.png)

**Comment by digitaldan** [comment]
Hi, how recent is your openhab2 build?

**Comment by hfanieng** [comment]
Got the same problem up to snapshot 507, so i disabled the binding in my test-environment.

**Comment by tavalin** [comment]
I also have the same issue with the binding.  I did plan to debug and investigate but I've not yet found the time.

**Comment by digitaldan** [comment]
@tavalin can you confirm what build of OH2 you are running?  There was a problem with ESH some time ago which caused similar behavior, just want to make sure this is a new issue.

**Comment by tavalin** [comment]
507 or whatever latest snapshot is (I keep up-to-date with snapshots). It's been happening for a while though.

**Comment by digitaldan** [comment]
Yep, I see it too, I'll take a look this week.

**Comment by digitaldan** [comment]
So there are two issues here, the first is an assumption I had made about adding channels, I have a issue open at  https://github.com/eclipse/smarthome/issues/2256 .  This is what's causing the duplicate channels (or at least my assumption of how it worked).  But this also uncovered another issue where I'm trying to add dynamic options to the current activity channel, which is fine if you have one hub, but not if you have multiple as they all reference the same channel id (current activity).  Timing is good as I'm working through other issues with this binding so I hope to have a fix sooner then later.
