### ISSUE TITLE
Add Analysis Tool for New Bindings

### ISSUE THREAD

**Issue by svilenvul** [openhab/openhab2-addons#1289]
I would like to start a discussion about the integration of an analysis tool for PRs in the openhab2-addons repo. This should speed up the review process for new bindings. 

There are several questions that should be discussed in detail, so I will start with a few start points:
- What kind of problems should be able to detect this tool?
  - missing files in the bindings (e.g. about.html, files in ESH-INF folder, build.properties) or not needed files in the PR (files that have to be ignored, but are not);
  - code style in .java files. Most of the [ESH Code Style guidelines](http://www.eclipse.org/smarthome/documentation/development/guidelines.html#a-code-style) can be applicable here:
    - missing license headers; 
    - missing JavaDoc;
    - inappropriate code formatting.
  - correct version and artifact name in the pom.xml file;
  - MANIFEST.MF requirements like:
    - Require-Bundle is not used;
    - no internal packages are exported;
    - all exported packages are imported;
    - all services are contained in the Service-Component entry.
- Which tool will be most appropriate for these tasks?

I have made a research about this question and I listed some of the most popular tools for such tasks. They can be divided in two groups:
- in the first group are tools like [Codacy](https://support.codacy.com/hc/en-us) and [SonarQube](http://docs.sonarqube.org/display/HOME/SonarQube+Platform). They can integrate tools from the group below and offer additional features like admin dashboard interface, storage of data in databases, generation of graphics, etc.;
- the tools in the second group are mainly targeting a certain type of coding rules:
  - [Checkstyle](http://checkstyle.sourceforge.net/)  - conventions;
  - [FindBugs](http://findbugs.sourceforge.net/) - potential bugs;
  - [PMD](https://github.com/pmd/pmd) - bad practices.

All of the tools come with predefined set of rules, but for our tasks it is very important how extensible they are. This is why I think SonarQube may be the most appropriate for the tasks above. It has the following advantages:
- it is an open source project distributed under [GNU LESSER GENERAL PUBLIC LICENSE](http://www.sonarqube.org/downloads/license/);
- it is easily extendable - it comes with a set of [plugins](http://docs.sonarqube.org/display/PLUG/Plugin+Library);
- can be integrated at different point of the process ([GitHub](http://docs.sonarqube.org/display/PLUG/GitHub+Plugin), [Jenkins](http://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner+for+Jenkins), [Maven](http://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner+for+Maven), [Eclipse IDE](http://docs.sonarqube.org/display/SONARQUBE53/Installing+SonarQube+in+Eclipse)) ;
- comes with a rich set of predefined [rules](https://sonarqube.com/coding_rules#languages=java|repositories=squid);
- has integration plugins for [PMD](https://github.com/SonarQubeCommunity/sonar-pmd), [FindBugs](https://github.com/SonarQubeCommunity/sonar-findbugs) and [Checkstyle](https://github.com/SonarQubeCommunity/sonar-checkstyle);
- supports .java, .pom and .xml files with different plugins;
- uses Java and XPath API for [new rules definition](http://docs.sonarqube.org/display/DEV/Adding+Coding+Rules).

Can you share your opinion, comments, recommendations and share your experience with the mentioned tools? I will appreciate recommendations for new tools as well.
##

**Comment by maggu2810** [comment]
IIRC The time I used SonarQube you always need a running server instance. The Maven and Eclipse plugins used the server instance.
Also it seems not so easy to integrate a merge request builder with Solar as it mixes the results of all builds for the same project.
But perhaps I invested not enough time for configuration.

For my projects I use maven plugins for Checkstyle, FindBugs, PMD (you stated them above) etc.
The Jenkins instance checks the Quality Gates (execute all the plugins and continues on error - generate the report only) and Jenkins will fail if the report breaks the limits.

I also use a pre commit Maven profile that fails if an error occurred and use it before doing a commit (myself).

**Comment by MHerbst** [comment]
First of all I like the idea of automatically checking as much as possible. I also would prefer to use only  Checkstyle, Findbugs and PMD. We are using them in our company very similar to @maggu2810. And especially the Findbugs checks are really helpful.

If these tools are installed as Eclipse plugins (or executed from Maven) and allows everybody to check the sources before committing them. It would only be necessary to store the necessary rule sets in git and make them available together with the source projects.

Also Sonar is more focused on code quality (and respective metrics) and not so on checks checks for completeness and code style.

The only problem I see are the non-Java files. AFAIK Checkstyle and Findbugs only support Java files (Finbugs checks the compiled class files). With PMD it should be possible to check the POM and XML files.

**Comment by kaikreuzer** [comment]
I agree with @maggu2810 and @MHerbst. It would be ideal if all tools could be used by the developers locally before even creating a PR. A Maven profile should enable those checks and new PRs would be build on Jenkins with this profile.

What should be tried is to make such a mechanism easily extensible and configurable; we e.g. might e.g. have a different set of checks for bindings than for UIs. And the guidelines might evolve over time. Also note that almost everything is applicable to ESH as well, so openHAB2 might not be the right place for such a feature (at least not for most of it).

There was a discussion for ESH a long time ago about such automatic checks and I have seen Maven plugins that used Groovy to do more advanced checks - this might be a good solution for all non-Java files.

Last but not least, it would be nice if a kind of summary/report could be created; I expect that we might have warnings (besides errors), which would NOT stop the build, but which we should nonetheless get to the attention of the developer - if those warnings only appear somewhere in the Maven build log, I doubt that anyone will ever see them.

**Comment by svilenvul** [comment]
Thanks for the feedback !

I will try to summarize the tool requirements, that we have so far:

- integration the with the Maven build;
- easily extensible and configurable: 
- define custom rule sets with different set of checks (bindings, UIs);
- multiple levels of logging (error, warning, ...);
- generate summary/report. 

@MHerbst, you are right, PMD has [plugin for XML files](https://pmd.github.io/pmd-5.5.1/pmd-xml/rules/index.html). I like that it has a [Java and XPath API](https://pmd.github.io/pmd-5.5.1/customizing/howtowritearule.html) for defining rules and it supports rule sets.

@kaikreuzer, about the summary report, it seems that the maven site plugin is able to generate and run a local site that contains the reports of all of the above mentioned plugins - [more info](https://dzone.com/articles/maven-3-code-analysis-and) .

@cdjackson, yes SonarQube needs a running server instance. I like the Github plugin that generates comments in the PR, but anyway this is optional and not so important.

**Comment by svilenvul** [comment]
I am ready to try to build a prototype, but another question occurred to me.

Should this tool be custom standalone or it is better to add just the plugins for pmd, checkstyle, findbugs to the maven build?

A standalone tool (that includes the libraries above and maybe others and executes them via script) will be more portable, can be executed separately from the Maven build and can check only a specific bundle. I think it will be more customizable as well. The cons in this case is that will be more difficult to be created.

If we are using the another approach, almost everything that we need comes out of the box (through the maven plugins for pmd, checkstyle, findbugs), but it will require configuration in the master .pom file and will not be so easily ported between smarthome, opnehab2-addons and maybe other repositories.

**Comment by maggu2810** [comment]
For Maven builds only it seems to be portable. I am using a Maven artifact that contains all PMD, Checkstyle, FindBugs, ... rule resources and it is used in different projects of mine.
For a nice IDE integration it depends on how to consume that rules.

**Comment by kaikreuzer** [comment]
I'd also say that it should be run within the Maven build itself (as a profile) as discussed above.
There should be ways to still keep it pretty independent of the specific Maven build on which it is integrated as @maggu2810 describes.

**Comment by martinvw** [comment]
@svilenvul since we already made major steps in this and it has its own project I think this issue can be closed, do you agree on that?

**Comment by svilenvul** [comment]
Yes, definitely.
