### ISSUE TITLE
[Zwave] Fibaro keypad / tag reader user_code not recognized

### ISSUE THREAD

**Issue by bricolo100** [openhab/openhab2-addons#1290]
The Fibaro WT-RFID is recognized and initialized a a thing with model recognition, but in habmin the user_code interface doesn't appear, as well as in PAPER UI.
Environment

Openhab2 online version beta snapshot
zwave version 2.0.0-20161001.042047-244
Raspberry Pi

**Comment by cdjackson** [comment]
This is not currently available as the security classes are not available in OH2 at this time.   I will close this for now - hopefully the security classes will be available in the near future and we can look at it again once this is implemented.

**Comment by bricolo100** [comment]
Do you have an estimation of the "near future" ?

**Comment by cdjackson** [comment]
I would guess a month or two. I'm working on some refactoring that is needed first.
