### ISSUE TITLE
Hue Emulation: Ignoring Packets from Amazon Echo..?

### ISSUE THREAD

**Issue by crystollic** [openhab/openhab2-addons#1294]
Hi, I am hueemulation (beta4) and it seems to be missing/ignoring packets from an Amazon Echo (device s/w 4008).   The Echo finds a Hue Bridge on the same network but not openhab/hueemulation.  

Log level trace for hue emulation and jupnp doesn't show anything.  

Bit confused, so nay help appreciated.

**Comment by digitaldan** [comment]
This should be fixed in the nightly builds with this PR https://github.com/openhab/openhab2-addons/commit/f08ae880fc6499468059412615d42fbea1afc237 ,  can you confirm if this works for you?

**Comment by crystollic** [comment]
Honestly what's the world coming to, 11 minutes to fix a problem 😄  I will check and confirm.

**Comment by digitaldan** [comment]
Well to be fair, I fixed it 6 days ago ;-)

**Comment by crystollic** [comment]
I'm embarrassed now, but I think I also had an issue with IGMP snooping 😳 However, I am grateful for fixing a problem before I found it 😄  Brilliant work and hopefully I can help more in the future!
