### ISSUE TITLE
Netatmo thermostat binding "400 Bad Request"

### ISSUE THREAD

**Issue by planbnet** [openhab/openhab2-addons#1295]
As soon as the channel SetpointMode is linked (to a String item), the "Thermostat module" Thing goes OFFLINE with a "400 Bad Request" error.
It doesn't matter whether the link is established in the item definition file or via PaperUI. All other channels on the thermostat thing work.
##

**Comment by hmerk** [comment]
I can not reproduce this issue with latest build and actial firmware of the netatmo thermostat. Is there anything in your logs about this error ??

**Comment by planbnet** [comment]
No, nothing. But i don't get much logging output from the netatmo binding at all. The only debug log messages I seem to get are "Refreshing <channel-name>" and "Updating device channels".

All I have is the thing status:
`netatmo:NATherm1:netatmoapi:040000xxxxxx (Type=Thing, Status=OFFLINE: 400 Bad Request, Label=null, Bridge=netatmo:netatmoapi:netatmoapi)`

**Comment by planbnet** [comment]
One more thing: The other channels (for example SetpointTemperature) only seem to work once on startup and do not refresh.

**Comment by clinique** [comment]
@planbnet  : can you test with last evolution of the binding ? You shall no more face this issue.

**Comment by bboser** [comment]
I observe the same error, but just with temperature modules (I do not have a thermostat). From the log:

`11:47:47.961 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'netatmo:netatmoapi:home' changed from INITIALIZING to ONLINE
11:47:48.000 [WARN ] [.handler.AbstractNetatmoThingHandler] - Unable to load property signalLevels
11:47:48.000 [WARN ] [.handler.AbstractNetatmoThingHandler] - Unable to load property signalLevels
11:47:48.005 [WARN ] [.handler.AbstractNetatmoThingHandler] - Unable to load property batteryMax
11:47:48.005 [DEBUG] [netatmo.handler.NetatmoDeviceHandler] - Initializing Netatmo Devoce '70ee500134ea'
11:47:48.006 [WARN ] [netatmo.handler.NetatmoModuleHandler] - Battery levels were not correctly initialised - reported values will be inconsistent
11:47:48.012 [WARN ] [.handler.AbstractNetatmoThingHandler] - Unable to load property signalLevels
11:47:48.014 [WARN ] [.handler.AbstractNetatmoThingHandler] - Unable to load property batteryMax
11:47:48.015 [WARN ] [netatmo.handler.NetatmoModuleHandler] - Battery levels were not correctly initialised - reported values will be inconsistent
11:47:48.016 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'netatmo:NAMain:home:inside' changed from UNINITIALIZED (HANDLER_MISSING_ERROR) to INITIALIZING
11:47:48.018 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'netatmo:NAModule1:home:outside' changed from UNINITIALIZED (HANDLER_MISSING_ERROR) to INITIALIZING
11:47:48.020 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'netatmo:NAMain:home:inside' changed from INITIALIZING to ONLINE
11:47:48.033 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'netatmo:NAModule1:home:outside' changed from INITIALIZING to ONLINE
11:47:48.035 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'netatmo:NAModule4:home:inside' changed from UNINITIALIZED (HANDLER_MISSING_ERROR) to INITIALIZING
11:47:48.037 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'netatmo:NAModule4:home:inside' changed from INITIALIZING to ONLINE
11:47:48.442 [DEBUG] [netatmo.handler.NetatmoDeviceHandler] - Initializing Netatmo Devoce '70ee500134ea'
11:47:48.456 [INFO ] [smarthome.event.ThingUpdatedEvent   ] - Thing 'netatmo:NAMain:home:inside' has been updated.
11:47:48.463 [INFO ] [smarthome.event.ThingUpdatedEvent   ] - Thing 'netatmo:NAModule1:home:outside' has been updated.
11:47:48.472 [INFO ] [smarthome.event.ThingUpdatedEvent   ] - Thing 'netatmo:NAModule4:home:inside' has been updated.
11:47:49.179 [WARN ] [netatmo.handler.NetatmoBridgeHandler] - An error occured while calling station API : org.apache.oltu.oauth2.common.exception.OAuthSystemException: java.io.InterruptedIOException
11:48:42.211 [INFO ] [marthome.event.ItemStateChangedEvent] - sceneHall changed from NULL to ON
11:48:51.403 [WARN ] [netatmo.handler.NetatmoBridgeHandler] - An error occured while calling station API : 400 Bad Request
11:49:51.656 [WARN ] [netatmo.handler.NetatmoBridgeHandler] - An error occured while calling station API : 400 Bad Request
`

**Comment by clinique** [comment]
I suspect that you still have outdated versions of OH2 and/or the binding. This error : 
11:47:48.000 [WARN ] [.handler.AbstractNetatmoThingHandler] - Unable to load property signalLevels 
should have disappeared now.

Can you control ?

**Comment by bboser** [comment]
How do I check the version? 

I've installed a fresh copy (via openhabian) of OpenHAB2 yesterday. If I understand correctly, openhabian downloads the latest version of OpenHAB. Hence I would not expect it to be outdated.

Also, configuring from the Paper UI, I got the binding to update items (except the CO2 of an auxiliary module which always returns null), but the textual configuration does not work (i.e. no data is downloaded from Netatmo).

**Comment by bboser** [comment]
Just ran apt-get update and upgrade (downloaded fresh openhab). Errors still in log:

`00:33:14.259 [INFO ] [home.event.ItemChannelLinkAddedEvent] - Link 'Netatmo_Outdoor_BatteryLevel-netatmo:NAModule1:home:outside:BatteryVP' has been added.
00:33:14.260 [INFO ] [home.event.ItemChannelLinkAddedEvent] - Link 'Netatmo_Outdoor_Humidity-netatmo:NAModule1:home:0200000126b8:Humidity' has been added.
00:33:14.262 [INFO ] [home.event.ItemChannelLinkAddedEvent] - Link 'Netatmo_Outdoor_Temperature-netatmo:NAModule1:home:0200000126b8:Temperature' has been added.
00:33:19.001 [DEBUG] [org.openhab.binding.netatmo         ] - BundleEvent STARTING - org.openhab.binding.netatmo
00:33:19.003 [DEBUG] [org.openhab.binding.netatmo         ] - BundleEvent STARTED - org.openhab.binding.netatmo
00:33:19.039 [DEBUG] [org.openhab.binding.netatmo         ] - ServiceEvent REGISTERED - {org.eclipse.smarthome.core.thing.binding.ThingHandlerFactory}={component.name=org.openhab.binding.netatmo.internal.NetatmoHandlerFactory, component.id=176, service.id=300, service.bundleid=198, service.scope=bundle} - org.openhab.binding.netatmo
00:33:19.087 [INFO ] [smarthome.event.ThingAddedEvent     ] - Thing 'netatmo:netatmoapi:home' has been added.
00:33:19.119 [INFO ] [smarthome.event.ThingAddedEvent     ] - Thing 'netatmo:NAMain:home:inside' has been added.
00:33:19.123 [INFO ] [smarthome.event.ThingAddedEvent     ] - Thing 'netatmo:NAModule1:home:outside' has been added.
00:33:19.125 [INFO ] [smarthome.event.ThingAddedEvent     ] - Thing 'netatmo:NAModule4:home:inside' has been added.
00:33:19.144 [DEBUG] [org.openhab.binding.netatmo         ] - ServiceEvent REGISTERED - {org.eclipse.smarthome.config.discovery.DiscoveryService}={service.id=301, service.bundleid=198, service.scope=singleton} - org.openhab.binding.netatmo
00:33:19.168 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'netatmo:NAMain:home:inside' changed from UNINITIALIZED to UNINITIALIZED (HANDLER_MISSING_ERROR)
00:33:19.173 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'netatmo:NAModule1:home:outside' changed from UNINITIALIZED to UNINITIALIZED (HANDLER_MISSING_ERROR)
00:33:19.179 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'netatmo:NAModule4:home:inside' changed from UNINITIALIZED to UNINITIALIZED (HANDLER_MISSING_ERROR)
00:33:19.397 [DEBUG] [netatmo.handler.NetatmoBridgeHandler] - Initializing Netatmo API bridge handler.
00:33:19.396 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'netatmo:netatmoapi:home' changed from UNINITIALIZED to INITIALIZING
00:33:19.989 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'netatmo:netatmoapi:home' changed from INITIALIZING to ONLINE
00:33:20.078 [DEBUG] [netatmo.handler.NetatmoDeviceHandler] - Initializing Netatmo Devoce '70ee500134ea'
00:33:20.079 [WARN ] [netatmo.handler.NetatmoModuleHandler] - Battery levels were not correctly initialised - reported values will be inconsistent
00:33:20.088 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'netatmo:NAMain:home:inside' changed from INITIALIZING to ONLINE
00:33:20.089 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'netatmo:NAModule4:home:inside' changed from INITIALIZING to ONLINE
00:33:20.096 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'netatmo:NAModule4:home:inside' changed from UNINITIALIZED (HANDLER_MISSING_ERROR) to INITIALIZING
00:33:20.098 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'netatmo:NAMain:home:inside' changed from UNINITIALIZED (HANDLER_MISSING_ERROR) to INITIALIZING
00:33:20.104 [WARN ] [netatmo.handler.NetatmoModuleHandler] - Battery levels were not correctly initialised - reported values will be inconsistent
00:33:20.105 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'netatmo:NAModule1:home:outside' changed from UNINITIALIZED (HANDLER_MISSING_ERROR) to INITIALIZING
00:33:20.105 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'netatmo:NAModule1:home:outside' changed from INITIALIZING to ONLINE
00:33:21.678 [DEBUG] [netatmo.handler.NetatmoDeviceHandler] - Initializing Netatmo Devoce '70ee500134ea'
00:33:21.696 [INFO ] [smarthome.event.ThingUpdatedEvent   ] - Thing 'netatmo:NAMain:home:inside' has been updated.
00:33:21.703 [INFO ] [smarthome.event.ThingUpdatedEvent   ] - Thing 'netatmo:NAModule1:home:outside' has been updated.
00:33:21.712 [INFO ] [smarthome.event.ThingUpdatedEvent   ] - Thing 'netatmo:NAModule4:home:inside' has been updated.
00:33:25.016 [WARN ] [netatmo.handler.NetatmoBridgeHandler] - An error occured while calling station API : org.apache.oltu.oauth2.common.exception.OAuthSystemException: java.io.InterruptedIOException
00:33:27.145 [WARN ] [netatmo.handler.NetatmoBridgeHandler] - An error occured while calling station API : 400 Bad Request
`

**Comment by bboser** [comment]
I'm again attaching the log, this time with TRACE turned on (although there do not appear to be any trace messages) and as a file (perhaps the formatting is better). In addition to
`19:37:03.003 [WARN ] [.handler.AbstractNetatmoThingHandler] - Unable to load property signalLevels`
the authorization error
`An error occured while calling station API : org.apache.oltu.oauth2.common.exception.OAuthSystemException: java.io.InterruptedIOException`
(near the end of the file) might be of concern.

[netatmo_log.txt](https://github.com/openhab/openhab2-addons/files/605378/netatmo_log.txt)

I am also attaching my configuration (password etc obfuscated). As I mentioned, I get updates when I configure with the Paper UI, but not from the textual binding, which seems to point to an error in my configuration.

[netatmo_things.txt](https://github.com/openhab/openhab2-addons/files/605396/netatmo_things.txt)
[netatmo_items.txt](https://github.com/openhab/openhab2-addons/files/605397/netatmo_items.txt)

Many thanks for your help!

**Comment by clinique** [comment]
My IDs in things.txt does not look like yours : 
    Thing NAPlug    plug        [ equipmentId="70:EE:50:09:cc:98"]
    Thing NATherm1  thermostat  [ equipmentId="04:00:00:0a:17:b4", parentId="70:ee:50:09:CC:98" ]
    Thing NAMain    station     [ equipmentId="70:EE:50:00:c1:72" ]
    Thing NAModule1 exterieur   [ equipmentId="02:00:00:00:BC:dc", parentId="70:ee:50:00:C1:72" ]

**Comment by bboser** [comment]
Adding the colons fixed this issue!

Now the only remaining problem is that the CO2 level of the auxiliary indoor module is not updated. Per log the value is NULL. All the other parameters (temperature, humidity, ...) of the auxiliary module are correctly reported.

**Comment by lolodomo** [comment]
As the Co2 issue for external indoor module was fixed yesterday, this issue has to be closed now.

**Comment by bboser** [comment]
Thanks, the Co2 channel is working now, as you indicate!

**Comment by lolodomo** [comment]
@planbnet : could you please give us a new status ? Is this issue still relevant for you with last snapshots ? If not, please close it.

**Comment by hmerk** [comment]
I just have a Thermostat and face the following errors with SNAPSHOT 611:

2016-11-25 15:31:44.704 [WARN ] [.handler.AbstractNetatmoThingHandler] - Unable to load property signalLevels
2016-11-25 15:31:44.705 [WARN ] [.handler.AbstractNetatmoThingHandler] - Unable to load property batteryMax
2016-11-25 15:31:44.705 [WARN ] [netatmo.handler.NetatmoModuleHandler] - Battery levels were not correctly initialised - reported values will be inconsistent
2016-11-25 15:31:44.708 [WARN ] [.handler.AbstractNetatmoThingHandler] - Unable to load property signalLevels
2016-11-25 15:31:45.065 [WARN ] [netatmo.handler.NetatmoBridgeHandler] - An error occured while calling thermostat API : org.apache.oltu.oauth2.common.exception.OAuthSystemException: java.io.InterruptedIOException

My things are defined as : 
Bridge netatmo:netatmoapi:home "Netatmo API" @ "System" [ clientId="580b995867e4827f818b45ed", clientSecret="z4UqSHURAfDHRmpQReH0jOSbnGZYNOWiAC", username="hans-joerg.merk@t-online.de", password="secret", readStation=false, readThermostat=true] {
NAPlug    plugtherm  "Netatmo Relais" @ "Wohnzimmer" [ equipmentId="70:ee:50:0a:80:9c" ]
NATherm1  thermostat "Raumthermostat" @ "Wohnzimmer" [ equipmentId="04:00:00:0a:6c:74", parentId="70:ee:50:0a:80:9c" ]
}

**Comment by lolodomo** [comment]
@hmerk  your credentials are probably wrong (OAuthSystemException).
I would advice that you update your last message to replace clientId, clientSecret, username and password by anonymous values.

**Comment by hmerk** [comment]
Thanks @lolodomo , I updated my comment. But it is no issue with my credentials, as the temp values are read correct.

**Comment by bboser** [comment]
I get the same warnings in in my log (common.exception.OAuthSystemException and Unable to load property signalLevels).

But despite these warnings the binding works flawlessly reporting environmental parameters from the main, outdoor, and an indoor auxiliary module.

What problems are you experiencing?

**Comment by hmerk** [comment]
It seems that there is no problem and we simply could ignore this warning, but on the other hand, ther should be no warnings, so it would be worth to investigate on this.

**Comment by lolodomo** [comment]
It could make sense to close this issue and open another one.

**Comment by planbnet** [comment]
It seems that this issue is resolved in the current version. I'm still getting error messages for the thermostat, but that's most likely not related to this problem.

**Comment by JoeRu** [comment]
Hi all, i know it's closed; But i receive this log from the actual Snapshot-Branch:
--
 [ERROR] [.netatmo.handler.NetatmoBridgeHandler] - An error occurred while calling station API : 400 Bad Request
--
I checked with 2.1 addon - in 2.2 snapshot-release - but the errors stays.
