### ISSUE TITLE
[RFXCom] Error setting up Thermostat1

### ISSUE THREAD

**Issue by FutureCow** [openhab/openhab2-addons#1305]
I'm trying to add a thermostat to my openhab setup. When sending a setpoint to my receiver, i see the new thing in my PaperUI.

I've add the Thing with all the items (setpoint, contact, temperature, battery, batterylow, signallevel)

But when i'm sending a new setpoint i get a error, and the items doesn't get updated.

Log:
`13:45:33.163 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Message received: Raw data = 0940001270941C1B3250, Packet type = THERMOSTAT1, Seq number = 18, Sub type = DIGIMAX, Device Id = 28820, Temperature = 28, Set = 27, Mode = HEATING, Status = NO_DEMAND, Signal level = 5
`
`13:45:33.163 [DEBUG] [binding.rfxcom.handler.RFXComHandler] - Received message from bridge: rfxcom:bridge:usb0 message: Raw data = 0940001270941C1B3250, Packet type = THERMOSTAT1, Seq number = 18, Sub type = DIGIMAX, Device Id = 28820, Temperature = 28, Set = 27, Mode = HEATING, Status = NO_DEMAND, Signal level = 5`
`13:45:33.163 
[ERROR] [binding.rfxcom.handler.RFXComHandler] - Error occured during message receiving:`

`
13:48:40.540 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Message received: Raw data = 0940002370941B181652, Packet type = THERMOSTAT1, Seq number = 35, Sub type = DIGIMAX, Device Id = 28820, Temperature = 27, Set = 24, Mode = HEATING, Status = NO_DEMAND, Signal level = 5
``13:48:40.540 [DEBUG] [binding.rfxcom.handler.RFXComHandler] - Received message from bridge: rfxcom:bridge:usb0 message: Raw data = 0940002370941B181652, Packet type = THERMOSTAT1, Seq number = 35, Sub type = DIGIMAX, Device Id = 28820, Temperature = 27, Set = 24, Mode = HEATING, Status = NO_DEMAND, Signal level = 5
``13:48:40.541 [ERROR] [binding.rfxcom.handler.RFXComHandler] - Error occured during message receiving:
`

`13:49:33.439 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Message received: Raw data = 0940002770941A1D1552, Packet type = THERMOSTAT1, Seq number = 39, Sub type = DIGIMAX, Device Id = 28820, Temperature = 26, Set = 29, Mode = HEATING, Status = DEMAND, Signal level = 5
``13:49:33.440 [DEBUG] [binding.rfxcom.handler.RFXComHandler] - Received message from bridge: rfxcom:bridge:usb0 message: Raw data = 0940002770941A1D1552, Packet type = THERMOSTAT1, Seq number = 39, Sub type = DIGIMAX, Device Id = 28820, Temperature = 26, Set = 29, Mode = HEATING, Status = DEMAND, Signal level = 5
``13:49:33.440 [ERROR] [binding.rfxcom.handler.RFXComHandler] - Error occured during message receiving:`
##

**Comment by paulianttila** [comment]
THERMOSTAT1  messages doesn't support battery level, so there is a bug in the rfxcom binding. Just created PR which should fix the issue.

**Comment by FutureCow** [comment]
Thanks for your PR. I'm also getting errors trying to change setpoint:
22:08:15.016 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'rfxcom_thermostat1_usb0_28820_setpoint' received command 19
22:08:15.017 [DEBUG] [binding.rfxcom.handler.RFXComHandler] - Received channel: rfxcom:thermostat1:usb0:28820:setpoint, command: 19
22:08:15.017 [WARN ] [binding.rfxcom.handler.RFXComHandler] - RFXCOM doesn't support transmitting for channel 'setpoint'

And is "contact" the switch to change the status from NO_DEMAND to DEMAND?

This is the full message from the thermostat:
Packettype    = Thermostat1
subtype       = Digimax/TLX7506
Sequence nbr  = 1
ID            = 28820 ID1=70 ID2=94
Temperature   = 17 °C
Set           = 20 °C
Mode          = heating
Status        = demand
Signal level  = 5  -80dBm
