### ISSUE TITLE
Squeezebox binding crashes on mute

### ISSUE THREAD

**Issue by PaulKC** [openhab/openhab2-addons#1306]
When I mute my squeezebox radio the squeezebox binding crashes with the following exception. After this no connection to the squeezebox server is possible until openhab is restarted. I do not understand the whole architecture at the moment so I can not provide a pull request but I would be happy to help.

`Oct 08 18:14:06 raspberrypi start.sh[22529]: Exception in thread "Squeeze Server Listener" java.lang.IllegalArgumentException: Value must be between 0 and 100
Oct 08 18:14:06 raspberrypi start.sh[22529]: at org.eclipse.smarthome.core.library.types.PercentType.validateValue(PercentType.java:46)
Oct 08 18:14:06 raspberrypi start.sh[22529]: at org.eclipse.smarthome.core.library.types.PercentType.<init>(PercentType.java:31)
Oct 08 18:14:06 raspberrypi start.sh[22529]: at org.openhab.binding.squeezebox.handler.SqueezeBoxPlayerHandler.volumeChangeEvent(SqueezeBoxPlayerHandler.java:313)
Oct 08 18:14:06 raspberrypi start.sh[22529]: at org.openhab.binding.squeezebox.handler.SqueezeBoxServerHandler$SqueezeServerListener$20.updateListener(SqueezeBoxServerHandler.java:737)
Oct 08 18:14:06 raspberrypi start.sh[22529]: at org.openhab.binding.squeezebox.handler.SqueezeBoxServerHandler.updatePlayer(SqueezeBoxServerHandler.java:779)
Oct 08 18:14:06 raspberrypi start.sh[22529]: at org.openhab.binding.squeezebox.handler.SqueezeBoxServerHandler.access$7(SqueezeBoxServerHandler.java:762)
Oct 08 18:14:06 raspberrypi start.sh[22529]: at org.openhab.binding.squeezebox.handler.SqueezeBoxServerHandler$SqueezeServerListener.handlePrefsetMessage(SqueezeBoxServerH...r.java:734)
Oct 08 18:14:06 raspberrypi start.sh[22529]: at org.openhab.binding.squeezebox.handler.SqueezeBoxServerHandler$SqueezeServerListener.handlePlayerUpdate(SqueezeBoxServerHandler.java:500)
Oct 08 18:14:06 raspberrypi start.sh[22529]: at org.openhab.binding.squeezebox.handler.SqueezeBoxServerHandler$SqueezeServerListener.run(SqueezeBoxServerHandler.java:382)`

**Comment by digitaldan** [comment]
Easy enough ;-)
