### ISSUE TITLE
[Netatmo] Netatmo Welcome Camera

### ISSUE THREAD

**Issue by wep4you** [openhab/openhab2-addons#1309]
I'll try to implement the features for the netatmo welcome camera in the netatmo binding. I get stuck earlier this year by the outdated swagger api for the welcome cam, so hopefully its now up to date, or somebody can help to get this api working for the new netatmo-api.

@clinique 
##

**Comment by clinique** [comment]
I unfortunately have no Welcome at the time. But swagger api is not so hard to extend and the original developper very willing to accept commits, so...up to you :)
