### ISSUE TITLE
Harmony Hub 2.0 binding can only be configured via Paper UI

### ISSUE THREAD

**Issue by Marty56** [openhab/openhab2-addons#1313]
I did not see a way how to create a "device" without using the paper ui.
e.g.
String Samsung  "Samsung TV" { channel="harmonyhub:device:Wohnzimmer:27701008:buttonPress" } 

The item Samsung requires a number (in the example 27701008) that must be derived from the discovery in the paper ui and inserted by cut and paste into the items file.

It should be best practice to always describe a purely textual configuration of related items.String

**Comment by kaikreuzer** [comment]
> I did not see a way how to create a "device" without using the paper ui.

I do see it: http://docs.openhab.org/addons/bindings/harmonyhub/readme.html
