### ISSUE TITLE
KNX & PaperUI

### ISSUE THREAD

**Issue by redbear-ger** [openhab/openhab2-addons#1327]
Hi,
I'm using Build #520 atm and facing 2 major problems...

1. 
Shouldnt be a "configure" option for PaperUI @ Configuration->Services? There are only options für Basic & Classic but PaperUI is obviously working (tried to switch default port and default items)

2. 
KNX binding is installed but it is not listed in Configuration->Bindings. Therefore I cant add any KNX Items. Do I have a general misunderstanding in how 2.0 works?

**Comment by hmerk** [comment]
Don't really understand your first issue. What is missing exactly.
Your second one is simple. KNX Binding is a openHAB 1.x Binding and can not be configured through PaperUI.

**Comment by redbear-ger** [comment]
1st issue:
Missunderstanding on my site... you can define sitemaps in "Classic" and "Basic" UI IN Paper UI but not FOR Paper UI ;)
