### ISSUE TITLE
Homematic HG-HM-CC-TC shows no channels

### ISSUE THREAD

**Issue by gbirke** [openhab/openhab2-addons#1331]
I'm using the homematic 2.0.0.b4 binding with the homegear gateway software. I've recently updated from OH1 to OH2.

I have two devices - a HG-CC-RT-DN that shows all the channels and a HG-HM-CC-TC that shows no channels. I've tried to convert the channel names in my items file, ignoring the missing channels in the Paper UI, but it seems to be an addon problem. The funny thing is - the trace log shows it's receiving values.

[openhab.log.gz](https://github.com/openhab/openhab2-addons/files/531421/openhab.log.gz)

The log is my full OpenHAB log. I've enabled tracing and removed/added the HG-HM-CC-TC to show what's happening in the communication.
##

**Comment by MHerbst** [comment]
@gbirke Is this issue still open? If yes please test it again with the latest snapshot.

**Comment by MHerbst** [comment]
No answer to my question for more than 3 weeks. @martinvw I think we can close this issue.

**Comment by martinvw** [comment]
If needed you can reopen it.

**Comment by gbirke** [comment]
I've set it up from scratch with OpenHABian 1.3 Pine64 and a fresh install of Homegear and the channels are shown. 
When I filed the error I had migrated Homegear from Version 5 a RaspPi to Version 6 on Pine64, maybe that was one of the error sources.

**Comment by martinvw** [comment]
@gbirke thanks for reporting back, glad it was solved.
