### ISSUE TITLE
SONOS command "notificationsound" does not add sound file to the playqueue

### ISSUE THREAD

**Issue by Marty56** [openhab/openhab2-addons#1332]
The new SONOS command "notificationsound" is not added a respective sound file in the SONOS playqueue. If used it only plays the sound file which is already exisiting in the queue.

The desire behavior would be to act like the "playuri" command in this respect. Meaning to clear the queue and add the respective sound file.

**Comment by kgoderis** [comment]
@lolodomo any thoughts on this as you (I think) introduced this command some time ago

**Comment by kgoderis** [comment]
@Marty56 This issue should be added to eclipse/smarthome instead, as the binding has been moved to that repo

**Comment by Marty56** [comment]
OK. I move it there. Is there a doc where to find the related bug tracker other than "look at the code!" ?

**Comment by kaikreuzer** [comment]
See http://docs.openhab.org/developers/contributing/contributing#the-repositories.

But you are right, from the user docs, it is difficult to find the right repo. It might make sense to add a link to the correct issue tracker in http://docs.openhab.org/addons/bindings.html or where would you expect it?

**Comment by Marty56** [comment]
Thanks for the link. This is a good start and provides some orientation.
To add the first link at the addons doc site (the second link) is a good place to teach the user where to find the right issue tracker.

Although it is still not quite clear for me how I could have determined from that information that the SONOS binding is not tracked in openHAB2 addons but in the Eclipse SmartHome Extensions.
Before posting I did a search for SONOS issues in openhab2 addons and there were SONOS issues here. So I thought it would be the right place. 
So I guess one would have to look into the code which is hard for a user.

**Comment by lolodomo** [comment]
@kgoderis : no sorry I have not introduced this command and that is even one of the rare features of the Sonos binding I have not yet tested.

**Comment by kgoderis** [comment]
@lolodomo No prob. Just wondering. @digitaldan did you implement that method?

**Comment by kaikreuzer** [comment]
No, it was a contribution from DT.
