### ISSUE TITLE
DSCAlarm Binding: Things stuck on Status: INITIALIZING

### ISSUE THREAD

**Issue by gtg864m** [openhab/openhab2-addons#1342]
I am having an issue with DSC Alarm Things initializing after a restart of OH2.   This started when I upgraded from Beta 3 to Beta 4.  My setup is RPI2 using the Envisalink. After a restart I have to go in and restart the bundle in the console (or uninstall/reinstall the binding) to get Things to go online. 

10:21:02.679 [DEBUG] [rm.handler.DSCAlarmBaseBridgeHandler] - DSC Alarm Polling Task - 'dscalarm:envisalink:mybridge' is ONLINE
10:21:02.686 [DEBUG] [rm.handler.DSCAlarmBaseBridgeHandler] - Checking Things!
10:21:02.687 [DEBUG] [rm.handler.DSCAlarmBaseBridgeHandler] - _**Checking 'dscalarm:panel:mybridge:panel' - Status: INITIALIZING, Refreshed: true
10:21:02.689 [DEBUG] [rm.handler.DSCAlarmBaseBridgeHandler] - *__Checking 'dscalarm:partition:mybridge:partition1' - Status: INITIALIZING, Refreshed: true
10:21:02.691 [DEBUG] [rm.handler.DSCAlarmBaseBridgeHandler] - *__Checking 'dscalarm:zone:mybridge:zone1' - Status: INITIALIZING, Refreshed: true
10:21:02.693 [DEBUG] [rm.handler.DSCAlarmBaseBridgeHandler] - *__Checking 'dscalarm:zone:mybridge:zone2' - Status: INITIALIZING, Refreshed: true
10:21:02.694 [DEBUG] [rm.handler.DSCAlarmBaseBridgeHandler] - *__Checking 'dscalarm:zone:mybridge:zone3' - Status: INITIALIZING, Refreshed: true
10:21:02.696 [DEBUG] [rm.handler.DSCAlarmBaseBridgeHandler] - *__Checking 'dscalarm:zone:mybridge:zone4' - Status: INITIALIZING, Refreshed: true
10:21:02.697 [DEBUG] [rm.handler.DSCAlarmBaseBridgeHandler] - *__Checking 'dscalarm:zone:mybridge:zone5' - Status: INITIALIZING, Refreshed: true
10:21:02.699 [DEBUG] [rm.handler.DSCAlarmBaseBridgeHandler] - *_*Checking 'dscalarm:keypad:mybridge:keypad' - Status: INITIALIZING, Refreshed: true 
##

**Comment by RSStephens** [comment]
Hello @gtg864m,

I have seen the same results when defining things through a .thing DSL file, but not when defined using the PaperUI.  This appears to have started happening with beta 4 as you have said.  I don't see the same issue with previous versions of OH2.  I plan to look at the code as soon as I can.  Thanks for the feedback.
