### ISSUE TITLE
[rfxcom] Temperature and Humidity icon not displayed and formmating exception in log

### ISSUE THREAD

**Issue by harryzz** [openhab/openhab2-addons#1343]
OpenHAB 2.0 SPAPSHOT

in channels.xml
for channel-type id="temperature"
add:  `<category>Temperature</category>`
change: `<state pattern="%.1f °C" readOnly="true"></state>`
for channel-type id="humidity"
add: `<category>Humidity</category>`

br
harry
##

**Comment by paulianttila** [comment]
@harryzz: you could easily create PR directly from GitHub for this kind of small changes. 

![screen shot 2016-10-26 at 18 09 25](https://cloud.githubusercontent.com/assets/5506533/19731893/9cdfac4c-9ba7-11e6-9e22-afc19c5a9ce1.png)

Just start editing of the file. All changes will be saved on your fork, where you can directly create PR.

**Comment by phil2fer** [comment]
since buid 559 i have a problem with RFXCOM binding, and the changes in channels.xml
see my log file

If i go back build 558 every things is ok.
[Log.txt](https://github.com/openhab/openhab2-addons/files/570197/Log.txt)

**Comment by lolodomo** [comment]
@paulianttila : I tried snapshot 582 and I got the formmating exception.
Additionally, my bridge thing were there and ONLINE but my child things (Oregon sensors) were not there (not displayed in Paper UI nor by a "smarthoime:things list" command).
It looks like something is still broken.
The same setup in snapshot 554 is working well.

**Comment by paulianttila** [comment]
@lolodomo just tested latest snapshot and for me temperature humidity sensors are working fine (I also have some Oregon sensors). Try to remove one sensor and see if rediscovery helps.

**Comment by lolodomo** [comment]
@paulianttila : as discussed in another issue, my problem is fixed. And the formatting exception was probably not relative to a channel of the RFXCOM binding.

So maybe this issue can be closed ?

**Comment by paulianttila** [comment]
@lolodomo I agree, this can be closed. Formatting problem was fixed by the commit #1385 which actually is a problem on smarthome side (https://github.com/eclipse/smarthome/issues/2408)
