### ISSUE TITLE
[homekit] MAX! Thermostat Mode issue

### ISSUE THREAD

**Issue by ghost** [openhab/openhab2-addons#1345]
There are some problems with the mode settings. If I change the mode via Browser, my iOS device(iOS10) is showing the right information (Cooling to XX°C...). But it isnt possible to change the mode on the iOS device. It is just saying No Answer. Just setting the Temperatur works fine. The MAX modes are AUTOMATIC, MANUAL and BOOST and I set them also up in the homekit.cfg file.

Is there a fix?
##

**Comment by Jaghova** [comment]
Is not just with MAX Thermostat, I have seen this behaviour also with classic UI.
When the mode is changed in the UI Homekit is updated correctly. 
When the mode is changed in Homekit, the item keeps loading and it says "no answer"

**Comment by Arsur** [comment]
how do i have have to set up my Item File to get Max with homekit running. my problem is also this [ "homekit:HeatingCoolingMode" ] how did you get this running with Max!?

**Comment by niki1898** [comment]
This is my Items File for each Thermostat/Room
```Group tBadezimmer "Badezimmer" <temperature> [ "Thermostat" ]
String modeBadezimmer    "Modus: " (tBadezimmer) [ "homekit:HeatingCoolingMode" ] {channel="max:thermostat:KEQ0523594:KEQ0411965:mode"}
Number akBadezimmer  "Gemessene Temperatur: [%.1f °C]" (tBadezimmer) [ "CurrentTemperature" ] {channel="max:thermostat:KEQ0523594:KEQ0411965:actual_temp"}
Number setBadezimmer "Soll Temperatur: [%.1f°C]"  (tBadezimmer) [ "TargetTemperature" ] {channel="max:thermostat:KEQ0523594:KEQ0411965:set_temp"}```

Changing the mode via homekit stil isn't working
But you can see the current temperatur, the target temperatur and the current mode
For this you have to adjust the org.openhab.homekit:thermostat* settings in the homekit.cfg file or via Paper UI

**Comment by jtweaver22** [comment]
Has anyone figured out how to set the Mode via Homekit? I also get the "No answer". All I need it to do is return the string { "Heat", "Off", "Cool", "Auto" } to the String item I have for the thermostat mode, then rules can handle the rest. Is there a way to do this?

**Comment by polarvogel** [comment]
I did a TCPdump and watched the packets from my iPhone to openHAB2 device. On temperature changes, you can see 2-3 packets beeing sent. But no packets at all are sent when I try to change the HeatingCooling mode.
I guess the thermostats are not correctly registered to the iOS Home App.

**Comment by kaikreuzer** [comment]
Fixed by https://github.com/openhab/openhab2-addons/pull/4535
