### ISSUE TITLE
HomeKit Status synchronisation

### ISSUE THREAD

**Issue by philippk80** [openhab/openhab2-addons#1347]
Hey, 

in my case homekit isn't informed about changes when an item is controlled by for example the web interface. Is this not implemented, a bug or do I have a incorrect configuration?

Best regards,

Phil

**Comment by kaikreuzer** [comment]
I assume the question is specific about HomeKit (because status updates work in general), so I adapted the title.
@beowulfe could you comment?

**Comment by beowulfe** [comment]
It should update. HomeKit has a subscription mechanism for change notification, which the OH add-on supports.

Try turning up the logging and see if the changes are getting published.

**Comment by kaikreuzer** [comment]
So there is no bug or missing feature, I hence close this issue. For support, I would suggest to rather use the forum at https://community.openhab.org/
