### ISSUE TITLE
Netatmo - Switch to Getthermostatsdata, Gethomedata and Getstationsdata by November 30th

### ISSUE THREAD

**Issue by wep4you** [openhab/openhab2-addons#1352]
I got this info today:

Friendly reminder: Getthermstate, Getuser and Devicelist will move from deprecated to shut down. On November 30th, we are proceeding to a structural change to make our APIs faster and more powerful. Unfortunately, old and deprecated API methods won’t be supported anymore. Make sure you amend your code and start using newer methods as soon as possible for a smooth transition:

Replace Getthermstate with Getthermostatdata
Replace Getuser with Getthermostatdata, Gethomedata or Getstationsdata
Replace Devicelist with Getthermostatdata or Getstationsdata

So it looks like, there are some updates required.

I already implemented the netatmo welcome api on cbornet/netatmo-swagger-decl to implement it into the openhab2 netatmo addon 
@cbornet @clinique 
##

**Comment by lolodomo** [comment]
I just take a quick look and these 3 API are used by the OH 2 netatmo binding.
@clinique: I have not checked the OH 1.x binding, does it mean that the 1.x and 2.0 netatmo bindings will no more work well in 30 days ?

**Comment by clinique** [comment]
@lolodomo, they are used in current one version of the binding - no more in the under review rewrited version of v2 binding.

**Comment by lolodomo** [comment]
Ok so we have to keep in mind PR #1099 has to be finally merged during the next 30 days.
And we will have to switch to 2.0 binding at this time.

**Comment by lolodomo** [comment]
Enhancement implementated.
To be closed.
