### ISSUE TITLE
New Pentair pool controller binding

### ISSUE THREAD

**Issue by jsjames** [openhab/openhab2-addons#1353]
New binding to interface with Pentair EasyTouch controllers, IntelliFlo pool pumps and Intellichlor chlorinators.
##

**Comment by digitaldan** [comment]
have you seen http://docs.openhab.org/addons/bindings/autelis/readme.html ?  This was written to specifically support Pentair pools. It does require an Autelis device which acts as an ip gateway to the pool equipment, but well worth the cost if you are looking at IP control .

**Comment by digitaldan** [comment]
Apologies, I did not realize you already had a direct connection in mind and built (just saw your OH2 repo), nice work!
