### ISSUE TITLE
Plugin execution not covered by lifecycle configuration

### ISSUE THREAD

**Issue by magx2** [openhab/openhab2-addons#1363]
I followed steps in http://docs.openhab.org/developers/development/ide.html#installation to get OpenHab2 working. My problem right now is that in OH2-addons working set plugin ```org.openhab.binding.systeminfo``` is not compiling. The problem appers in pom.xml:

Description | Resource | Path	Location | Type
---------------|--------------|-------------------|---
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (execution: default, phase: compile) | pom.xml | /org.openhab.binding.systeminfo	line 7 | Maven Project Build Lifecycle Mapping Problem

JFY I'm getting the same problem when I create my own binding (http://docs.openhab.org/developers/development/bindings.html#creating-a-skeleton).

**Comment by kaikreuzer** [comment]
The solution is to remove the Maven nature from the project, which I have done with https://github.com/openhab/openhab2-addons/pull/1365.

When creating a skeleton, this should be no problem as the Maven nature is not added in it, see [here](https://github.com/eclipse/smarthome/blob/master/tools/archetype/binding/src/main/resources/archetype-resources/.project) - so you might have added that yourself accidentially?
