### ISSUE TITLE
Chromecast Binding - doesn't work with Shield TV (Android TV)

### ISSUE THREAD

**Issue by tavalin** [openhab/openhab2-addons#1381]
My excitement at discovering the newly merged Chromecast binding quickly disappeared when I realised it didn't discover my Shield TV box as a Chromecast device (when other Chromecast libs do) and having put in some temporary bandaids fixes, I still could not get the binding to control it.

Having done some initial debugging there's two specific lines of code in ChromecastDiscoveryParticipant which stop the DiscoveryResult being created.

The [first](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastDiscoveryParticipant.java#L62) issue is that the manufacturer is returned as "NVIDIA" instead of "Google Inc." so some thought needs to be done as to whether we check the the manufacturer at all, and if so, how we can flexibly extend this check to include other manufacturers of Android TV devices.

The [second](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastDiscoveryParticipant.java#L81) is that the model is returned as "SHIELD Android TV" so again, we need to look at how we can extend this check (and if necessary add a new thing-type).

Having made these fixes my Android TV was discovered as a Chromecast device but the controls on the Paper UI were unable to control it.  I believe there are further issues within @maggu2810's library (from looking at the log I'd guess the library isn't correctly parsing the playing state or hasn't communicated with the device to work out the playing state).

Here's some debug lines from when I pressed pause whilst a video was being cast to my Shield TV.

```
2016-11-02 22:57:29.462 [DEBUG] [io.rest.core.item.ItemResource:281  ] - Received HTTP POST request at 'items/chromecast_chromecast_d168cbf1_2fb4_375b_07cd_11d494836e03_control' with value 'PAUSE'.
2016-11-02 22:57:29.464 [INFO ] [arthome.event.ItemCommandEvent:43   ] - Item 'chromecast_chromecast_d168cbf1_2fb4_375b_07cd_11d494836e03_control' received command PAUSE
2016-11-02 22:57:29.464 [DEBUG] [.c.thing.internal.ThingManager:414  ] - Delegating command 'PAUSE' for item 'chromecast_chromecast_d168cbf1_2fb4_375b_07cd_11d494836e03_control' to handler for channel 'chromecast:chromecast:d168cbf1-2fb4-375b-07cd-11d494836e03:control'
2016-11-02 22:57:34.465 [DEBUG] [s.core.common.SafeMethodCaller:191  ] - Timeout of 5000ms exceeded, thread safeCall-3 (192) in state RUNNABLE is at java.lang.Thread.dumpThreads(Thread.java:-2).
2016-11-02 22:57:34.465 [DEBUG] [s.core.common.SafeMethodCaller:191  ] - Timeout of 5000ms exceeded, thread safeCall-1 (73) in state TIMED_WAITING is at java.lang.Object.wait(Object.java:-2).
2016-11-02 22:57:34.465 [WARN ] [.s.c.i.events.OSGiEventManager:198  ] - Dispatching event to subscriber 'org.eclipse.smarthome.core.thing.internal.ThingManager@1171eb6f' takes more than 5000ms.
2016-11-02 22:57:34.465 [WARN ] [.c.thing.internal.ThingManager:425  ] - Handler for thing 'chromecast:chromecast:d168cbf1-2fb4-375b-07cd-11d494836e03' takes more than 5000ms for processing event
2016-11-02 22:57:34.466 [INFO ] [smarthome.event.ItemStateEvent:43   ] - chromecast_chromecast_d168cbf1_2fb4_375b_07cd_11d494836e03_control updated to PAUSE
2016-11-02 22:57:34.466 [DEBUG] [.c.thing.internal.ThingManager:464  ] - Delegating update 'PAUSE' for item 'chromecast_chromecast_d168cbf1_2fb4_375b_07cd_11d494836e03_control' to handler for channel 'chromecast:chromecast:d168cbf1-2fb4-375b-07cd-11d494836e03:control'
2016-11-02 22:57:34.467 [INFO ] [s.event.ItemStateChangedEvent :43   ] - chromecast_chromecast_d168cbf1_2fb4_375b_07cd_11d494836e03_control changed from PLAY to PAUSE
2016-11-02 22:57:59.469 [INFO ] [ome.event.ThingStatusInfoEvent:43   ] - 'chromecast:chromecast:d168cbf1-2fb4-375b-07cd-11d494836e03' updated: OFFLINE (COMMUNICATION_ERROR): ChromeCast has invalid state to pause media playback
2016-11-02 22:57:59.470 [INFO ] [nt.ThingStatusInfoChangedEvent:43   ] - 'chromecast:chromecast:d168cbf1-2fb4-375b-07cd-11d494836e03' changed from OFFLINE (COMMUNICATION_ERROR): ChromeCast has invalid state to resume media playback to OFFLINE (COMMUNICATION_ERROR): ChromeCast has invalid state to pause media playback
```

Don't have any more time tonight to investigate but let me know if I can be of any more help.

**Comment by kaikreuzer** [comment]
Well, the binding says it supports Google Chromecast devices - it so far is not meant to support any "chromecast compatible receiver". But you can certainly create a PR to extend the binding in this regards.

I also experienced connection problems (closed connections after sending commands) and had the impression that the issues are within the underlying library. It would be great to have @maggu2810  joining the efforts here, if his time allows.

**Comment by tavalin** [comment]
>Well, the binding says it supports Google Chromecast devices - it so far is not meant to support any "chromecast compatible receiver". But you can certainly create a PR to extend the binding in this regards.

My expectations were set due to the fact that every other Chromecast enabled app discovers it as a Chromecast device but I take your point ;) 

My intentions were to create a PR with the modifications I mentioned but it didn't seem right to fix discovery only to have the device communiction not working correctly so I raised the issue for visibility and discussion.  Hopefully @maggu2810 can join the conversation but if not I'll try and take a look at the library src over the weekend and see if improvements can be made there.

**Comment by kaikreuzer** [comment]
> My intentions were to create a PR with the modifications I mentioned

Great. I'd actually suggest to introduce a third thing type that is a "Generic Chromecast Receiver" (but which uses the same handler implementation as well).

**Comment by BClark09** [comment]
I'd be happy to test and confirm any changes to the binding.

My initial thoughts are that the library being used is too strict on the information that it expects to come back from the device. Is the library src included in the binding? I had trouble finding it.

**Comment by kaikreuzer** [comment]
The library is maintained at https://github.com/maggu2810/shk/tree/master/bundles/shk-library-chromecast-api.
I was also wondering whether we should move its sources directly to the binding, but this would mean to fork it (again) and it also results in a license mix. I therefore hoped that @maggu2810 further maintains his version and we only include it as a jar. @maggu2810 What is your personal preference and plan regarding Chromecast?

**Comment by tavalin** [comment]
@kaikreuzer So I've started to look at this having done some more research on Chromecast discovery, I have to ask is there a reason discovery was implemented with upnp instead of mdns?

**Comment by maggu2810** [comment]
The real upstream library is this one: https://github.com/vitalidze/chromecast-java-api-v2
I only maintain my fork because I need some changes that cannot be merged upstream (breaks backward compatibility etc.).
I added some PRs the last week to the upstream lib that are also part of my fork.
I also added the mDNS discovery about five days ago to my ChromeCast binding.

**Comment by kaikreuzer** [comment]
So is your advice that we should use the upstream lib, because yours does not provide any additional features/fixes that would be important for openHAB?

@tavalin I do not care whether we use UPnP or mDNS - is any better supported by Chromecast than the other?

**Comment by maggu2810** [comment]
The necessary patch I need to add to the upstream library is to be able to register a listener for connection events (e.g. closed). I used this to set the offline status.
You need to decide if this is important for you.
If you don't care, perhaps the best thing is to use the upstream one.

Information about discovery: https://github.com/jloutsenhizer/CR-Cast/wiki/Chromecast-Implementation-Documentation-WIP#discovery

**Comment by BClark09** [comment]
@kaikreuzer's implenation for openHAB looks like it uses this listener also to determine offline status, so my guess is that we should keep using your library.

**Comment by kaikreuzer** [comment]
Well, in general I would say it is better to use the official project, as @maggu2810 contributes back his fixes to it anyhow (and so do others using this lib). So unless we say we really need the "offline" listener, I am fine with removing that feature and simply set the Thing to offline, if communication fails.

**Comment by tavalin** [comment]
@kaikreuzer I guess the benefit I'm seeing with mDNS is that we can register the service type we're interested in ("_googlecast._tcp.") so that we know any result is Chromecast-compatible, and if necessary we can determine exactly which model if* necessary. With the implementation of UPnP I can't see anyway to generically identify Chromecast-compatible devices without comparing the manufacturer and device model to a list of known candidates. Indeed at the moment we're getting all UPnP responses and have to filter out a lot of junk purely based on manufacturer and model.

*On a separate note, I'm not convinced that conceptually we need to separate Android TV from a regular Chromecast.  However having played around with the official library, there are definitely bugs when using Android TV that aren't in the [python implementation](https://github.com/balloob/pychromecast) which works very smoothly with my Android TV.

**Comment by maggu2810** [comment]
> However having played around with the official library, there are definitely bugs when using Android TV that aren't in the python implementation which works very smoothly with my Android TV.

@tavalin I don't know "how" the Java library has been created (which documentation or reverse engineering is used). And how the ChromeCast APIs (v1, v2, v3) differs. But I recently fixed a bug for the title that could be sent to the ChromeCast - I realized it does not work in the Java library but in pychromecast. So I checked that implementation and changed the Java to git to them (https://github.com/vitalidze/chromecast-java-api-v2/pull/50).
I think there are other places to, that needs a fix.

**Comment by tavalin** [comment]
As a workaround to the initial issue I realised that you can define your Android TV (or any Chromecast-capable device) as a normal Chromecast via the .things file as follows:

`chromecast:chromecast:androidtv [ipAddress="192.168.X.X"]`

I'll continue to investigate the merits of mDNS over UPnP over the next week and send through a PR if necessary.

**Comment by rogro82** [comment]
If you want to support the Google Cast-protocol instead of just Chromecast-devices the correct way is to use mDNS discovery. In my opinion it would also be better to rename the binding itself to a Google Cast-binding once it uses mDNS and can be used with other supported devices ( https://www.google.com/intl/en_us/cast/ ).

**Comment by kaikreuzer** [comment]
@rogro82 I agree with both your suggestions. @tavalin Would you take care of the renaming in the scope of your upcoming PR as well?

**Comment by tavalin** [comment]
@kaikreuzer will do.  I assume I should rename ALL occurrences of Chromecast to Google Cast:

- Binding name
- Thing type
- Class names
- Class constants

**Comment by kaikreuzer** [comment]
@tavalin Thanks! And yes, all those occurences - a good search&replace tool will be your best friend ;-)

**Comment by tavalin** [comment]
Well, having spent last night doing the almighty search and replace, I woke up this morning to see news that Google is rebranding "Google Cast" to "Chromecast built-in" (see [here](https://www.google.com/cast/) for first hint)

I think for now I will split the changes and submit just the mDNS part, as Chromecast may yet again be the correct name,

**Comment by kaikreuzer** [comment]
Indeed: https://twitter.com/Chromecast/status/801111758748483584

What a bad timing :-)

**Comment by lolodomo** [comment]
I have a Freebox Player mini 4k relying on Android TV. I could tell you what mDNS data are provided.
And i will test the compatibility of the binding with this player device.
