### ISSUE TITLE
Chromecast does not play/pause videos from all sources

### ISSUE THREAD

**Issue by BClark09** [openhab/openhab2-addons#1382]
I've installed the new chromecast binding, and the play/pause and volume buttons work very well when it is playing videos streamed from services like YouTube. When trying to pause or play a video from Airflow (A PC application which allows you to stream any video file to your chromecast) I receive the following errors (and the video does not play or pause):

```
21:02:32.954 [WARN ] [maggu2810.shk.chromecast_api.Channel] - Error while reading: Unrecognized field "videoInfo" (Class de.maggu2810.shk.chromecast_api.MediaStatus), not marked as ignorable
 at [Source: java.io.StringReader@538d7f; line: 1, column: 1023] (through reference chain: de.maggu2810.shk.chromecast_api.MediaStatus["videoInfo"])
21:02:32.957 [WARN ] [maggu2810.shk.chromecast_api.Channel] -  <-- {"type":"MEDIA_STATUS","status":[{"mediaSessionId":2,"playbackRate":1,"playerState":"PAUSED","currentTime":0,"supportedMediaCommands":15,"volume":{"level":1,"muted":false},"videoInfo":{"width":320,"height":240,"hdrType":"sdr"},"media":{"contentId":"http://192.168.0.3:46634/live-transcoding/segment/session1-e93aad4c-a207-11e6-b71a-d8cb8a772ec6/simple-mx0-pl0/segment0.mkv","contentType":"video/x-matroska","duration":30.121666,"metadata":{"metadataType":0,"title":"Sample Video"},"streamType":"BUFFERED"},"currentItemId":2,"items":[{"itemId":2,"media":{"contentId":"http://192.168.0.3:46634/live-transcoding/segment/session1-e93aad4c-a207-11e6-b71a-d8cb8a772ec6/simple-mx0-pl0/segment0.mkv","contentType":"video/x-matroska","duration":30.121666,"metadata":{"metadataType":0,"title":"Sample Video"},"streamType":"BUFFERED"},"autoplay":false,"customData":{"logoURL":"https://s3.amazonaws.com/Airflow/GoogleCast/v1/AirflowIconGoogleCast.png","placeholderText":"Airflow is ready to cast"}}],"repeatMode":"REPEAT_OFF"}],"requestId":7}
21:02:37.676 [WARN ] [ore.internal.events.OSGiEventManager] - Dispatching event to subscriber 'org.eclipse.smarthome.core.thing.internal.ThingManager@140e0d6' takes more than 5000ms.
21:02:37.676 [WARN ] [ome.core.thing.internal.ThingManager] - Handler for thing 'chromecast:chromecast:9e4179b4-7c59-aa7b-d1d6-d1f60324ed94' takes more than 5000ms for processing event
```

Volume control still works well though.

**Comment by kaikreuzer** [comment]
This again looks like some issue in the underlying library (see also https://github.com/openhab/openhab2-addons/issues/1381).

Please note that although I did the initial contribution of this binding (using @maggu2810's library), I very likely won't have a chance to maintain it on the long run - so it would be great if someone that is actively using Chromecast would volunteer to take care of it!

**Comment by BClark09** [comment]
I see the point of fault now with the library and will make a PR upstream.

**Comment by BClark09** [comment]
@kaikreuzer Looking deeper into this, this was actually already fixed in the original library and also in @maggu2810's version.

Could we use the latest build or build from source again to see if this issue is fixed?

**Comment by kaikreuzer** [comment]
Hm, then I must have grabbed an old jar of it... Feel free to build a new version and create a PR with it!

**Comment by BClark09** [comment]
Can do, shall we continue to use the library source from Maggu's branch, or should we look at using the original source?

**Comment by kaikreuzer** [comment]
Let's see what the answer on https://github.com/openhab/openhab2-addons/issues/1381#issuecomment-259141971 is.
