### ISSUE TITLE
Z-Wave: add device Popp outdoor switch

### ISSUE THREAD

**Issue by mkotsbak** [openhab/openhab2-addons#1383]
Please add this Popp device: http://www.popp.eu/products/actuators/wall-plug-switch-outdoor/

The XML file for it is as attached.

[node11.xml.txt](https://github.com/openhab/openhab2-addons/files/570185/node11.xml.txt)

**Comment by cdjackson** [comment]
This is in the database - it’s a ZWave.me product - ZME_06437

**Comment by cdjackson** [comment]
Sorry - I thought this was OH1. Please open an issue in the OH2 zwave issue list.

**Comment by mkotsbak** [comment]
@cdjackson I'm a bit unsure where the OH2 source code/issue list is located? Could you please add a link to the repository?
