### ISSUE TITLE
Colorpicker SVG missing

### ISSUE THREAD

**Issue by derchrisuk** [openhab/openhab2-addons#1389]
Hi,

while testing OpenHAB2, we discovered that the colorpicker.svg is missing.
Checked the org.eclipse.smarthome.ui.iconset.classic-0.9.0-SNAPSHOT.jar and could not find it in there either.

**Comment by kaikreuzer** [comment]
If you expect this to be added to the classic iconset, please enter an issue at https://github.com/eclipse/smarthome/issues, because this is where this iconset is maintained. Thanks!
