### ISSUE TITLE
http binding for dimmer gets no update 

### ISSUE THREAD

**Issue by kohlsalem** [openhab/openhab2-addons#1401]
Dear OH enthusiasts,

i'm right now in the process of moving my automations on OH2 (latest snapshot), and I'm really impressed. Homematic, Wemo and some other work fine, but i have to integrate some other devices (blinds and some esp8266 stuff) via http as well.

Easiest Project is a candle.

http://candle/?b=50  would bring it to 50% works great!! But since it can recieve changes even outside of OH, i want to poll the value as well. I try with

Dimmer Candle "Candle [%d]" <fire> {http="<[http://candle/:1000:JSONPATH($.b)] >[*:GET:http://candle/?b=%2$s] >[ON:GET:http://candle/?b=100] >[OFF:GET: http://candle/?b=0]"}

Switching works fine. JSONPATH works fine.

Number Candle_Value "Candle [%d]" {http="<[http://candle/:1000:JSONPATH($.b)]"} 

updates the number perfectly, if i put it on the sitemap.

However: The slider i have defined in the sitemap for this item never ever ever indicates any update based on the recieved value. The url gets called ( i have proved that). 

Is this a bug or an embarrassing misunderstanding of some concept? 

Thanks for any hint,

Michael

**Comment by kaikreuzer** [comment]
Hi Michael,

Please use this issue tracker only for bugs related to the code in this repository.

I'd suggest to discuss your problem in the community at https://community.openhab.org/c/openhab-2. It is probably also helpful if you could provide there some event log of what exactly is sent in your setup.

**Comment by watou** [comment]
@kohlsalem This is a current deficiency of the HTTP binding, which does not permit updating the state of Dimmer items.  (The binding has an incomplete hard-coded mapping of item types when it ought to be dealing only in items' accepted state types.) 

Since the cause is known, please open an issue [here](https://github.com/openhab/openhab/issues) and I will see about a pull request.

**Comment by kohlsalem** [comment]
@watou i did as you adviced here: https://github.com/openhab/openhab/issues/4759
