### ISSUE TITLE
Proposal for tests for the Astro Binding

### ISSUE THREAD

**Issue by petarnv** [openhab/openhab2-addons#1402]
I have started implementing tests for the Astro Binding.

@gerrieg, as an initial contributor, do you think it is a good idea to implement tests for this binding?

**Comment by gerrieg** [comment]
sure, tests are always good

**Comment by petarnv** [comment]
I have made a PR with implemented tests: https://github.com/openhab/openhab2-addons/pull/1434

**Comment by martinvw** [comment]
I believe the binding is now moved to Eclipse Smarthome, if needed please reopen an issue there.
