### ISSUE TITLE
RFXCOM: missing things when running snapshot 583

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab2-addons#1416]
Running snapshot 583, the RFXCOM binding is no more working (the binding is OK in snapshot 554).
After startup, I have my bridge thing ONLINE:
```
rfxcom:bridge:rfx (Type=Bridge, Status=ONLINE, Label=RFXtrx433E, Bridge=null)
```
But my child things are missing. Here is how my things file is defined:
```
Bridge rfxcom:bridge:rfx "RFXtrx433E" [ serialPort="/dev/ttyUSB0", ignoreConfig=true ] {
    Thing temperaturehumidity Bureau "Sonde Bureau" [ deviceId="32002", subType="TH1" ]
    Thing temperaturehumidity Chambre "Sonde Chambre" [ deviceId="62977", subType="TH1" ]
    Thing temperaturehumidity Veranda "Sonde Veranda" [ deviceId="8196", subType="TH1" ]
}
```
Was there a syntax change in the DSL ?

**Comment by paulianttila** [comment]
Thing-type for humidity temperature has been changed by @harryzz PR https://github.com/openhab/openhab2-addons/pull/1387. Don't know why?

**Comment by harryzz** [comment]
Hello
things types changed because of https://github.com/openhab/openhab2-addons/pull/1387

br
Zahari

**Comment by lolodomo** [comment]
@paulianttila : thanks a lot for this finding, my things are back. I have to update all my links now !
This change was not very clever as it breaks existing setups. And the readme was even not updated.

**Comment by paulianttila** [comment]
I will change thing temperature_humidity back to temperaturehumidity as it's inline other thing types.

**Comment by harryzz** [comment]
Hello
I think you are wrong. If you don't like underscores you need to change in RFXComBaseMessage.java and in all other java files where Packet type TEMPERATURE_HUMIDITY is used. There are also other mismatched packet types in rfxcom bindings with underscore.

br
Zahari

**Comment by paulianttila** [comment]
@harryzz: I have changed RFXComMessageFactory packet type converter to remove underscores before compares packet types. This change is already committed to master. In fact I did this change long time ago, but forgotten to do PR for it.

**Comment by harryzz** [comment]
Hello
it seems this is the best solution in this case.

br
Zahari
