### ISSUE TITLE
VoiceRSS TTS; file voicerss.cfg should be added automatically in conf/services

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab2-addons#1417]
When installing VoiceRSS TTS, no voicerss.cfg file is created in conf/services directory.

**Comment by kaikreuzer** [comment]
The documentation does not claim that there is one. 
But yes, feel free to create a PR to add this similar as it is done [for other addons](https://github.com/openhab/openhab2-addons/blob/master/features/openhab-addons/src/main/feature/feature.xml#L309).

**Comment by ThomDietrich** [comment]
there should be.

It's counterintuitive to have none and users will be rattled by that.
