### ISSUE TITLE
Adapt Binding tests to the new Bridge/Thing lifecycle

### ISSUE THREAD

**Issue by svilenvul** [openhab/openhab2-addons#1425]
The [PR merged in smarthome repo](https://github.com/eclipse/smarthome/pull/2087)  will break the existing tests is openhab2-addons, as they are relying on the fact that ThingHandler is registered as a Service, when a new stable version of ESH is released.

I will prepare a PR for the required adaptations.

**Comment by kaikreuzer** [comment]
It already exists since a week! https://github.com/openhab/openhab2-addons/pull/1394

**Comment by svilenvul** [comment]
@kaikreuzer 
I just wanted to add a few lines to the binding tests.
