### ISSUE TITLE
FGS-213 doesn't update the status if you switch it directly on device

### ISSUE THREAD

**Issue by normen1** [openhab/openhab2-addons#1428]
The device FGS-213 by fibaro doesn't update the status if you switch it manually directly on the device. If you look in Habmin in the zwave network viewer there is no connection displayed. If I turn on the device via openhab item the device switch on. So the connection was established and is working. If I refresh the item manually in Habmin the data will be displayed.

I still use FGS-223 by fibaro. That device update the status.

**Comment by cdjackson** [comment]
Normally this is associated with not setting the configuration correctly. Please check the association configuration. If the problem persists please discuss it on the forum.

**Comment by normen1** [comment]
There is no association configuration in habmin like in other device configurations.
