### ISSUE TITLE
Chromecast Binding doesn't discover ChromeCast Audio Groups

### ISSUE THREAD

**Issue by chriscolden** [openhab/openhab2-addons#1432]
Hi,

I was excited to find a chromecast binding in oh2. Unfortunately it's not finding my ChromeCast Audio Groups.

I've played with pychromecast and this found the groups as soon as one was enabled, so I assumed they were the same technology, possibly just passing a parameter back which the binding isn't expecting. Would be great to get these added in as well. Think of them as virtual chromecasts.

Many thanks
Chris

**Comment by chriscolden** [comment]
Could it be this...
 if (modelDetails.getModelName().equals("Chromecast Audio")) {
                    return ChromecastBindingConstants.THING_TYPE_AUDIO;

It possibly return Chromecast Audio Group and the binding currently is only looking for audio or video.

**Comment by kaikreuzer** [comment]
There are discussions to support "any" chromecast-capable device, this would then also include virtual groups. I think this will require to move from UPnP to mDNS discovery as it is discussed here: https://github.com/openhab/openhab2-addons/issues/1381#issuecomment-259277238

**Comment by tavalin** [comment]
I still intend to create the PR to move discovery to mDNS in order to support any chromecast-capable device but my concern here (as I don't have a Chromecast Audio) is whether the library we're using supports control of Audio Groups.

**Comment by chriscolden** [comment]
Groups are just virtual Chromecasts, so my guess is it would, however it would need testing.

pychromecast pushed this exact change to support groups.

https://github.com/balloob/pychromecast/commit/e250c80b82cdc2c66bbfadb5044248dfdb2d9334

**Comment by tavalin** [comment]
```
11/17/2016 04:50:52 AM - monitor-ccs - INFO - Discovered device: CAG-Upstairs (192.168.1.104) - Google Cast Group
11/17/2016 04:50:52 AM - monitor-ccs - INFO - Discovered device: CAG-House (192.168.1.104) - Google Cast Group
```

What's interesting here is that these devices share the same IP - could you possibly try the java chromecast library and confirm if it works for properly?

**Comment by chriscolden** [comment]
They share the same ip as one of the chromecasts in the group. As you can see the downstairs group and kitchen both share the same ip. My guess is that the first chromecast to connect to the network which is appart of the group gets a master status, and therefore shares the group out.

It's been a long time since i've coded in java but I can give it a shot.

**Comment by chriscolden** [comment]
turns out my java skills really aren't that good, im having trouble using the v2 api it's throwing dependencies all over the shop. sorry guys.
