### ISSUE TITLE
Add Amazon Polly TTS Voice (previously Ivona Speech Cloud)

### ISSUE THREAD

**Issue by kubawolanin** [openhab/openhab2-addons#1439]
As a big enthusiast of openHAB I'd like to suggest implementing yet another Text-to-Speech service, based on [Ivona Speech Cloud](http://developer.ivona.com/en/speechcloud/introduction.html).
It's a polish service (the company was acquired by Amazon some time ago) that produces really accurate and natural sounding voices. And - what's important for me, particularly - has great Polish language support, unlike e.g. VoiceRSS. They have a lot of choice for [other languages as well](https://www.ivona.com/us/).

I've already did some research in that field and even started coding my own add-on (which is cool, because I'm a front-end dev and didn't touch Java for years!)

So in order to use Ivona API, you'll need API credentials (API Key and API Secret)

They developed a SDK to get you started:
https://github.com/IvonaSoftware/ivona-speechcloud-sdk-java

So the Ivona openHAB voice addon will require additional lib.

Let me know what you think on the idea. 
I hope I'll submit some pull request soon.

**Comment by lolodomo** [comment]
I just tested the 2 french voices and that looks to me less good than VoiceRSS.
Can you confirm that the service is not free ?
But that is a good thing to add more and more TTS engine.

**Comment by kubawolanin** [comment]
Well, I'm sure there are better services for French, but for polish it's one of the best :) They support 51 voices for 23 languages so far, so I think it's a good to have it inside openHAB.

[For development account](http://b2b.support.ivona.com/articles/en_US/FAQ/Speech-Cloud-cost/?l=en_US&fs=Search&pn=1) it's free for 50000 units/month. 
[Here's a brief explanation of what's the definition of unit](https://www.ivona.com/us/for-business/speech-cloud/#faq1).

Best!

**Comment by lolodomo** [comment]
Each user will have to create a developer account ?

**Comment by kubawolanin** [comment]
Yes. The same way you do it for [Nest binding](https://github.com/openhab/openhab/wiki/Nest-Binding#binding-configuration) or VoiceRSS in that matter.

**Comment by kaikreuzer** [comment]
> Each user will have to create a developer account ?

For VoiceRSS you need to sign up for an account as well, but Ivona seems to be a bit more strict regarding having accounts only for developers:

___"Speech generated with this service can be used only for development purposes. To start using this service we ask you to fill this form, it should take about 2-5 minutes."___

They ask a lot of questions, so I am not sure if they will approve "regular" openHAB users to get access.

In general, the quality of this service seems pretty good and it would be nice to see it supported by openHAB. Maybe you could reach out to their team and check what is their position about that? Maybe they would be interested themselves in supporting openHAB and would allow us some special accounts for our users?

> So the Ivona openHAB voice addon will require additional lib.

As they publish it under Apache license, there is no problem at all to include this lib in the add-on.

**Comment by kubawolanin** [comment]
@kaikreuzer thank you for comment.

I've already contacted them but didn't get any response yet.
In the meantime I'm going to continue my work on the add-on.

Cheers!

**Comment by tameion** [comment]
@kaikreuzer I am also interested in your project.

I have been using one of the Ivona voice files for my self built home automation system but am now moving on to OpenHab.

Has there been any further progress?

**Comment by kaikreuzer** [comment]
@tameion Welcome!
I don't have any more recent information on that topic - probably best to ask for @kubawolanin's update on it.

**Comment by kubawolanin** [comment]
Hey @tameion!
My progress on this has stopped pretty much on Jan 21st.
Here's [my branch with the code](https://github.com/kubawolanin/openhab2-addons/tree/ivona). 
Note it were my first steps in binding development and a lot of it would need to be reconsidered or even rewritten. Feel free to grab my code and continue working on that :)

Also, Ivona SDK has become [Amazon Polly](http://docs.aws.amazon.com/polly/latest/dg/examples-java.html), so it would make sense to create an add-on for Polly directly. Both require AWS SDK to work.
On the flip side, Polly is a commercial product...

Personally, I'm leaning towards open source solutions like [CMU Sphinx](https://cmusphinx.github.io/) which [openHAB integration](https://github.com/openhab/openhab2-addons/pull/2220) is being taken care of by @ghys currently :)

**Comment by kubawolanin** [comment]
For those interested in the subject - @hillmanr created fully functional voice add-on for Amazon Polly. 🏆 

Community discussion:
https://community.openhab.org/t/amazon-polly-tts-voice-service/29699/8
