### ISSUE TITLE
[Homematic] Smoke Detector HM-Sec-SD-2 missing in description.properties

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab2-addons#1440]
description.properties already contains a smoke detector of type HM-Sec-SD. My smoke detector identifies with type HM-Sec-SD-2.
@gerrieg  I have executed the CcuMetadataExtractor but it did not create an entry for HM-Sec-SD-2.

**Comment by gerrieg** [comment]
The Extractor can not extract all descriptions, so we have to add them manually, see https://github.com/openhab/openhab2-addons/pull/1460

**Comment by MHerbst** [comment]
OK, I understand. Next time I will add them to the extras descriptions file.
