### ISSUE TITLE
SMA Energy Meter configuration

### ISSUE THREAD

**Issue by ebazan** [openhab/openhab2-addons#1441]
As a newby I'm trying to configure my SMA Energy Meter Thing in Open HAB without succeding.
What should I write in the .config / .items / .site files.
I tried following the examples wit no success.

Many thanks for the support.

             enrico

**Comment by kaikreuzer** [comment]
Hi Enrico,

please use our forum at https://community.openhab.org/ for support. Thanks!

**Comment by ebazan** [comment]
Ok, sorry.
