### ISSUE TITLE
Netatmo "Air Quality" not working anymore for additional modules

### ISSUE THREAD

**Issue by michaeljoos72** [openhab/openhab2-addons#1444]
Hi

With latest update to fix the humidity a new issue popped up for me:
CO2 (Air Quality) doesn't work anymore. But only for my **additional indoor modules**. Main module does work as expected!

Thanks
Michael

**Comment by rene54321** [comment]
Is the outdoor module working correctly? As my one shows still not correct values and does not update.

**Comment by michaeljoos72** [comment]
Yes outdoor looks good in my system:

![image](https://cloud.githubusercontent.com/assets/20517474/20473455/22a06f7e-afc1-11e6-94f6-6262420e0517.png)

**Comment by rene54321** [comment]
Could you share your things configuration with me (without secret and so on). I dont find any failure in my setup.

**Comment by michaeljoos72** [comment]
@clinique @lolodomo Not sure if it's OK to ask you. But I hope you can help here with my CO2-Issue?

**Comment by lolodomo** [comment]
At my knowledge, Co2 is only available for the main module ?

**Comment by lolodomo** [comment]
Looking at the readme, Co2 should be available for additional indoor module.
In fact I was not aware that it exists two different additional modules, one for indoor, one for outdoor. Mine is certainly an outdoor module.

**Comment by michaeljoos72** [comment]
My setup is main indoor module, 2 additional indoor modules, outdoor module, rain and wind modules.

For both additional indoor modules CO2 was working until last week with the humidity fix. Temperature, Humidity, Battery Level...everything is OK except CO2.

**Comment by lolodomo** [comment]
@clinique: it look like your forgot CO2 case in class NAModule4Handler.hancleCommand.

**Comment by clinique** [comment]
Yes, Co2 is present in thing definition XML file but seems to be missing below. I'll correct this (along with some comments of @lolodomo after the last PR). @michaeljoos72 , can you please open an issue ?

**Comment by lolodomo** [comment]
@clinique the issue is opened, you.just answered inside lol

**Comment by clinique** [comment]
@lolodomo :+1:

**Comment by lolodomo** [comment]
@michaeljoos72 : please confirm your issue is fixed in the last snapshot and then close this issue.

**Comment by michaeljoos72** [comment]
Yeap, will test this tomorrow as I'm not able to update my system today. Thanks!

**Comment by michaeljoos72** [comment]
👍 Thanks!
