### ISSUE TITLE
[Paper UI] Astro Control 12 hour format

### ISSUE THREAD

**Issue by NorbertHD** [openhab/openhab2-addons#1446]
In Paper UI in Control view the Astro binding shows times in 12 hour format without am/pm abbreviation.
Can somebody please change it to 24 hour format? It's in org.eclipse.smarthome.ui.paper-0.9.0-SNAPSHOT.jar file controllers.min.js line 2452.

Change
            return $filter('date')(date, "dd.MM.yyyy hh:mm:ss");
To
            return $filter('date')(date, "dd.MM.yyyy HH:mm:ss");

Capital letter HH is 24 hour format.

**Comment by kaikreuzer** [comment]
Could you please add this as a bug for the Paper UI at https://github.com/eclipse/smarthome/issues? Many thanks!
