### ISSUE TITLE
[Paper UI] Yahoo Weather Control wrong air pressure

### ISSUE THREAD

**Issue by NorbertHD** [openhab/openhab2-addons#1447]
In Paper UI Control view the Yahoo Weather binding shows the wrong air pressure. Actually it shows 33491 hPa which is about 33 times to high. Normal air pressure is around 1013 hPa.

**Comment by kaikreuzer** [comment]
Please report that as a bug for the Yahoo weather binding at https://github.com/eclipse/smarthome/issues.
