### ISSUE TITLE
[amazondashbutton] Binding does not work with new Dash Buttons

### ISSUE THREAD

**Issue by monnimeter** [openhab/openhab2-addons#1449]
The amazondashbutton binding works only with those buttons which send ARP requests. Unfortunatelly most of the new buttons sold in Germany have a new hardware version which uses the UDP Bootstrap Protocol (bootp).

The model number of these "new" buttons is JK29LP (old model nr. is JK76PL). I've found a German page explaining the difference - there's also a working example script (python):
https://blog.thesen.eu/aktuellen-dash-button-oder-ariel-etc-von-amazon-jk29lp-mit-dem-raspberry-pi-nutzen-hacken/

@OLibutzki could you please check if and how the binding could be extended to also support the new model?!

Thank you and regards.
Osman

**Comment by OLibutzki** [comment]
Thanks for the issue. I wil take a look at it asap.

**Comment by monnimeter** [comment]
👍, thank you.

IMHO this could be a good starting point:
https://github.com/openhab/openhab2-addons/tree/master/addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/service/dhcp

**Comment by OLibutzki** [comment]
This one fits pretty well as it uses the Pcap4J which I use for the binding as well: http://www.stefreitag.de/wp/2016/10/29/dashbutton-detektieren-per-java/

**Comment by monnimeter** [comment]
👍 
Yes, you're right. Please let me know if you need my support (i.e. for testing).

**Comment by OLibutzki** [comment]
I have two JK29LP Dash buttons and both work with this binding without any problems. I do not have a JK76PL model.

Did you start openHAB as root or did you grant the capabilities to the java Process as described here? http://docs.openhab.org/addons/bindings/amazondashbutton/readme.html

**Comment by OLibutzki** [comment]
I just compared the performance between bootp and arp and bootp is about 50 ms faster than arp, but I think this difference is not that important.

**Comment by monnimeter** [comment]
openHAB is run with its own user. Caps are granted as per documentation.
BTW: the binding discovers automagically the other Amazon devices, i.e. a Kindle.
I've also tested an ARP based Python Script; it also did not recognoze the button. But, another Python Script based on BOOTP works well.

**Comment by monnimeter** [comment]
Did you implement a BOOTP packet listener? I could give it a try...

**Comment by OLibutzki** [comment]
That's interesting. Obviously the model number is not the criteria for the ARP request being sent.

I will update the binding. It will handle bootp packets as well. You can help me a lot, if you test my implementation.

**Comment by monnimeter** [comment]
Yes, I'll do it for sure. In #1236 I saw @kaikreuzer had also issues with his dash button... maybe he will also give it a new try.

Which FCC-ID do your buttons have? Mine has 2AETK-1013

**Comment by OLibutzki** [comment]
> Mine has 2AETK-1013
Same here

I added BOOTP support. You can download the binding [here](https://ufile.io/88725).

Thanks for testing!

**Comment by monnimeter** [comment]
It works great!

2016-11-23 17:52:57.506 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'amazondashbutton:dashbutton:ac-63-be-xx-xx-xx' to inbox.

Thank you. 👍

**Comment by monnimeter** [comment]
If you create a PR for this commit, then the issue can be closed :)
