### ISSUE TITLE
Migrate UPB Binding

### ISSUE THREAD

**Issue by DaAwesomeP** [openhab/openhab2-addons#1461]
Hi,
I've been using the UPB binding from OH1 in OH2, and it would appear to work perfectly. I requires the serial binding, and it has two configuration options:
```
upb:port=/dev/ttyUSB0
upb:network=55
```

**Comment by kaikreuzer** [comment]
If you want to say that the 1.x binding should be added to the distro please see http://docs.openhab.org/developers/development/compatibilitylayer.html#how-to-add-a-successfully-tested-1x-add-on-to-the-distribution and create an according PR at the OH1 repository.

**Comment by watou** [comment]
@DaAwesomeP I will add the UPB binding to OH2 unless you would prefer.

**Comment by DaAwesomeP** [comment]
@watou I was going to do it myself, but it sounds like you would do a better job at it. Thanks!

**Comment by watou** [comment]
Sorry, I jumped the gun.  https://github.com/openhab/openhab/pull/4814

**Comment by DaAwesomeP** [comment]
@watou you're good!
