### ISSUE TITLE
Rules: Cron Trigger not reliable

### ISSUE THREAD

**Issue by SebZim** [openhab/openhab2-addons#1464]
Hi,
in addition to my posting I will set this point to the issue list:

[Link openHAB community](https://community.openhab.org/t/cron-trigger-not-reliable/17106/6)

The trigger is working well after changing something in the cron expression. After few hours of running fine, the trigger suddenly does strange things. Running 2-4 times at the same time, for example.
Details can be seen very good in the logfile. I put a example in the forum, as shown in the link.

Thanks in advance.

**Comment by kaikreuzer** [comment]
This would have to be reported at https://github.com/eclipse/smarthome/issues as it is not related to any openHAB 2 add-on (what this repo here is about).
