### ISSUE TITLE
Squeezebox control from UI

### ISSUE THREAD

**Issue by lumachan** [openhab/openhab2-addons#1466]
Hi,

Since recent snapshot (don't know exactly which one), when I control my players through the UI I have the following error in my log : 

`2016-11-23 17:20:52.398 [INFO ] [ebox.handler.SqueezeBoxPlayerHandler] - player thing squeezebox:squeezeboxplayer:E582ACF3-915E-40B9-9098-8EFE1D8BE026:b827eb6906b3 has no server configured, ignoring command: PLAY`

When I changed from LMS, I can see items updated on OpenHAB. But it seems any command from OpenHAB is refused when the same error like above.

Maybe related to that ? https://github.com/openhab/openhab2-addons/pull/1394

Thanks

**Comment by jmccoy555** [comment]
Also see https://github.com/openhab/openhab2-addons/issues/1455

**Comment by mhilbush** [comment]
> Maybe related to that ? #1394

Yes, definitely.  The variable squeezeBoxServerHandler, which is used in numerous places in the binding, was set in method bridgeHandlerInitialized.  bridgeHandlerInitialized was removed with that PR.

@digitaldan Do you know how to fix this?

**Comment by kaikreuzer** [comment]
Seems I wasn't cautious enough when removing that code.
I would assume that simply setting the bridge field in https://github.com/openhab/openhab2-addons/pull/1394/files#diff-fa27c95c88010a6d98082106f43bed43L112 instead of introducing a local variable should already do the trick. @digitaldan, would you agree?

**Comment by lumachan** [comment]
Thanks @kay and @digitaldan ! Will try on tomorrow snapshot !

Regards

**Comment by jmccoy555** [comment]
Now working in snapshot build 615 (running in docker). Thanks @digitaldan and everyone.
