### ISSUE TITLE
[Netatmo] Bridge ONLINE although wrong credentials entered

### ISSUE THREAD

**Issue by sjka** [openhab/openhab2-addons#1472]
I created a new "Netatmo API" Bridge via the PaperUI, entering "asdf" for all credentials that I was asked for. The bridge was created (which is okay) and went ONLINE (which surprised me):

```
openhab> smarthome:things
netatmo:netatmoapi:ba4a941b (Type=Bridge, Status=ONLINE, Label=Netatmo API, Bridge=null)
```

My expectation was that it would end up in "OFFLINE (Configuration Error)" when entering wrong credentials.

**Comment by lolodomo** [comment]
You're right.
@clinique: checks are missing in NetatmoBridgeHandler.initialize()

**Comment by clinique** [comment]
Will take this one in a batch of corrections

**Comment by clinique** [comment]
...and kill once for a while this problem with loadProperties :cry:

**Comment by lolodomo** [comment]
@clinique : for your information I tried the snapshot 624 and got a lot of exceptions with the netatmo binding. I restored the stable snapshot 607.

**Comment by clinique** [comment]
I think this can be closed ?

**Comment by martinvw** [comment]
@clinique thanks for mentioning
