### ISSUE TITLE
[Chromecast] Binding doesn't discover Chromecast Ultra

### ISSUE THREAD

**Issue by NorbertHD** [openhab/openhab2-addons#1476]
Chromecast Binding doesn't discover Chromecast Ultra. The Chromecast Ultra has model name "Chromecast Ultra" but the Chromecast binding only discovers model names "Eureka Dongle" and "Chromecast Audio".

Please add

```
                } else if (modelDetails.getModelName().equals("Chromecast Ultra")) {
                    return ChromecastBindingConstants.THING_TYPE_CHROMECAST;
```
to ChromecastDiscoveryParticipant.java getThingType.

**Comment by tavalin** [comment]
Please see https://github.com/openhab/openhab2-addons/issues/1381

I have also stated a workaround on that issue to manually define it in the meantime.

**Comment by NorbertHD** [comment]
Thanks, I will wait for the discovery with mDNS.
