### ISSUE TITLE
Onkyo bundle cant add discovered thing (AVR)

### ISSUE THREAD

**Issue by kungfoolfighting** [openhab/openhab2-addons#1483]
I recently got an onkyo TX-NR656 which is listed as supported in the OnkyoBindingConstants.java

I installed the latest openhab2 online and offline snapshot today and both are able to discover the AVR, but when trying to add the Thing from the inbox the paperUI gets a popup that says:  ERROR: 409 - Conflict

And the logs say: 
`[WARN ] [g.discovery.internal.PersistentInbox] - Cannot create thing. No binding found that supports creating a thing of type onkyo:onkyoAVR.`

The Onkyo 1.9 plugin works though.

edit: 
I just reinstalled everything and checked the log while installing the Onkyo plugin and this is the (very long) log excerpt with the error messages:
[log message](http://pastebin.com/UVskH0N3)

**Comment by swamiller** [comment]
Same bug here with the latest snapshot (TX-NR646).  Binding was working well before I updated to the current OH2 snapshot. I did a completely new install, no help.

**Comment by kungfoolfighting** [comment]
I reverted to the revision before the last onkyo-related commit:

https://github.com/openhab/openhab2-addons/pull/1475
and compiled and used that version of the onkyo plugin and it works!
So the last commit definitely broke the plugin.

**Comment by kaikreuzer** [comment]
Definitely not due to #1475, but rather due to #1431.

I just briefly tested it and noticed that an NPE is thrown, which causes the handler factory to crash.
https://github.com/openhab/openhab2-addons/pull/1485 should fix that.

**Comment by kungfoolfighting** [comment]
Yes not due to 1475, I just linked the last commit before the breaking commit which contains a working version of the plugin. The following commit is the breaking one
