### ISSUE TITLE
Locale changes lead to problems in the basic ui

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab2-addons#1487]
I tested with Build 616 on Windows 10 (German) with Chrome browser.

After a fresh installation of openHAB I have added the Yahoo Weather Binding and configured a location. Locale was the default locale. In Basic UI it looks like this:

![image](https://cloud.githubusercontent.com/assets/616792/20642398/22c8397c-b40e-11e6-9aef-0d0baae22db2.png)

As you can see the the locale is ignored for the formatting of decimals. No matter how I set the locale (I also tried en_US), in Basic UI always a decimal comma is used. 

Now I changed the locale to de_DE and in Basic UI it looks like this:
![image](https://cloud.githubusercontent.com/assets/616792/20642421/b04c4982-b40e-11e6-9038-c566eb20e300.png)

Interestingly the behaviour is not always the same. Sometimes only the text remains english and no Icons are shown. For other bindings like the Homematic binding it looks quite similar:
![image](https://cloud.githubusercontent.com/assets/616792/20642432/db9acb18-b40e-11e6-8fc5-2477eaa5862d.png)

The only way to solve the problem is to remove the things and add them again.

**Comment by kaikreuzer** [comment]
I would assume this has the same underlying cause as https://github.com/openhab/openhab2-addons/issues/1487.
As Yahoo weather binding as well as the Basic UI are both within the ESH repo as well, I close this issue here.

**Comment by MHerbst** [comment]
@kaikreuzer  I think you are referring the wrong issue. 1487 is this issue :-)

**Comment by kaikreuzer** [comment]
I hope you didn't get in a loop following the links ;-)
The correct one should be https://github.com/eclipse/smarthome/issues/2589.
