### ISSUE TITLE
NullPointer in astro binding discovery?

### ISSUE THREAD

**Issue by micw** [openhab/openhab2-addons#1488]
Hi,

while reading the astro binding code I found the following:
https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/discovery/AstroDiscoveryService.java#L52

```
        try {
            result = HttpUtil.executeUrl("GET", "http://ip-api.com/json/?fields=lat,lon", 5000);
        } catch (IOException e) {
            logger.warn("Can't get latitude and longitude for the current location: {}", e);
        }
```

I think the code should exit here because otherwise it continues with resul==null which leads to a nullpointer within the next try...catch (which is ignored in the catch).

**Comment by ThomDietrich** [comment]
@svilenvul

**Comment by svilenvul** [comment]
@ThomDietrich 
Thanks, PR is created.
