### ISSUE TITLE
Kodi (Xbmc) Addon does not display special characters

### ISSUE THREAD

**Issue by Dom1n1c** [openhab/openhab2-addons#1496]
The XBMC addon can not handle special characters such as tv / movie titles:
"Der Hobbit - Smaugs EinÃ¶de"
is displayed instead of
"Der Hobbit - Smaugs Ein**ö**de"

Maybe this can be changed in the current xbmc addon or in the new kodi addon for OH2.

Thanks 👍

**Comment by MHerbst** [comment]
The new Kodi Addon has the same problem. There seems to be a problem with international characters. Either an encoding is missing somewhere or UTF-8 strings are not correctly handled.
@pail23

**Comment by MHerbst** [comment]
Works now correct.

**Comment by MHerbst** [comment]
@pail23 This issue is solved an can be closed.
