### ISSUE TITLE
RFXCOM rainsensor

### ISSUE THREAD

**Issue by fremel75** [openhab/openhab2-addons#1498]
Rainrate and raintotal does not get updated 

I have tested this change in RFXComBindingConstants.java and it solves this for me
`-    public final static String CHANNEL_RAIN_RATE = "rainrate";`
` -    public final static String CHANNEL_RAIN_TOTAL = "raintotal";`
` +    public final static String CHANNEL_RAIN_RATE = "rainRate";`
` +    public final static String CHANNEL_RAIN_TOTAL = "rainTotal";`

**Comment by martinvw** [comment]
@fremel75 I think this can be closed now, can you do so?
