### ISSUE TITLE
[exec] README improvement

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab2-addons#1500]
Related to the latest change at https://github.com/openhab/openhab2-addons/pull/468 by @kgoderis 

A few remarks regarding the exec 2.0 binding [README](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.exec/README.md):

* The `transform` property of a thing is mentioned but not shown in the example.
* Defaults for `interval` and `timeout` are missing
* You might wish to execute a command periodically (interval) or manually (run). I don't think these two quite important options become clear looking at the README. This should be discussed in a subsection.
* The are two spaces in the apc example.
* `channel="exec:command:apc:execute"` is not defined as a valid channel.
* How about a better/comprehensible example command like uptime?
* For newcomers it might be unclear that you need to define multiple Things for multiple commands. I would suggest two-three things in the Full Example
* Related to that, the sentence "the binding supports a single Thing, being the 'command' thing" may be misleading.
* Also related: "All devices support the following channels" - the term device was not used before
* One of the recurring problems with the Exec binding is the fact, that commands are executed in the context and with the privileges of the openhab process. A subsection should address that issue.
* Another recurring problem was the correct usage of `@@` in the command. I'm unsure if the fact that this is not needed here should be mentioned...
* Further functionality was revealed [here](https://github.com/openhab/openhab2-addons/pull/468#issuecomment-263072784) and should be mentioned

**Comment by kgoderis** [comment]
@ThomDietrich  All very valid ;-) It stems from me copy/pasting from my outdated config files, as well as the fact that i am incorporating changes/suggestions. 

Will correct for all yr comments

> Another recurring problem was the correct usage of @@ in the command. I'm unsure if the fact that this is not needed here should be mentioned...

Ah.. That is an interesting one. In v1 of the binding it was a hack for Mac OS X, but myself (also on Mac OS X) never came across the issue. I hope someone can confirm, or not, whether that is still relevant in the new binding. If so, then it needs to be added back in.

**Comment by kgoderis** [comment]
@ThomDietrich Can we close this issue?

**Comment by ThomDietrich** [comment]
Hey @kgoderis, I just read through your enhancements to the binding and the README. While you addressed most o the things above, there are still some points unattended, e.g. `transform` is now shown in a second example but still not in the definition in the top part of the file. Defaults for timeout etc are not named. I think an itemization instead of the text in line 17 would be better. [Example](http://docs.openhab.org/addons/bindings/network/readme.html)
The README technically contains all needed information but there are too many uncertainties users will have to figure out. I believe you invested quite a few hours to get the binding to the fantastic point where it is now. The README does not honor that...

**Comment by wborn** [comment]
Do you think the current Exec binding [README](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.exec/README.md) is still missing information @ThomDietrich? Perhaps you can also review the pending Exec binding changes in PR https://github.com/openhab/openhab2-addons/pull/2012?

**Comment by J-N-K** [comment]
No response from reporter for >18 month.
