### ISSUE TITLE
Snapshot 623 not installing UIs and bindings - ignoring addons.cfg

### ISSUE THREAD

**Issue by skywayne** [openhab/openhab2-addons#1507]
![image](https://cloud.githubusercontent.com/assets/1105616/20696721/eecddb60-b659-11e6-9e8e-ebd5b8714b39.png)

Have tried editing addons.cfg, (which contained UIs) but no luck - system is effectively dead.  Have also installed UIs using console, but still not working correctly - e.g. paper UI doesn't have extensions tab

**Comment by kaikreuzer** [comment]
This is definitely not the right issue tracker - and I would suggest to first figure out if there is a bug or not in the community. Please provide startup log files as well then.

**Comment by kaikreuzer** [comment]
FTR: https://community.openhab.org/t/empty-index-page-start-index-after-startup/17465
