### ISSUE TITLE
[org.openhab.binding.harmonyhub] doku how to get available button press values

### ISSUE THREAD

**Issue by kohlsalem** [openhab/openhab2-addons#1515]
Hi,

i have to say, the binding works quite nice and strainght forward to switch scenes on the harmony hub. However, pressing buttons turned to be hard.

It took me quite some hours of google and reading, reading trace logs of the binding (one hint somewhere) , compiling and trying the harmony command line tool (mentioned in OH1 version, did not authenticate) to finally find the thread with the hint to check the rest service for channel-types in order to see possible buttonPress values.

I would find it very valuable and time saving to get this documented in the readme :-).

Thanks
Michael

**Comment by kaikreuzer** [comment]
Do you plan to create a PR to add what is missing for you in the docs?

**Comment by kohlsalem** [comment]
would be my very first one - i try :-)

**Comment by wborn** [comment]
Since #1516 got merged I think this issue can be closed?
