### ISSUE TITLE
[Astro] Paper UI shows lots of channel groups with same name and description

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab2-addons#1520]
The Astro binding has lots of channels and groups. But unfortunately the groups are all shown with the same name and description, e.g. for the Moon thing:
![image](https://cloud.githubusercontent.com/assets/616792/20861524/a225d254-b992-11e6-87f8-6b82360f77a2.png)

For the thing Sun it is even worse. There are 13 groups named "Range" with the sam description of "Range for a sun event".

**Comment by lolodomo** [comment]
Now that https://github.com/eclipse/smarthome/pull/2970 is merged, it is now possible to add a label and a description to each channel group.
I will propose a PR enhancing that for the astro binding.

**Comment by kaikreuzer** [comment]
Sounds good! I'll propably do a new ESH stable build tomorrow, so that this change is available in the openHAB distro then.

**Comment by lolodomo** [comment]
Perfect, then you will be able to merge my PR tomorrow ;)

**Comment by lolodomo** [comment]
I am sorry, finally I will let a specialist define the right label and description to all these groups because theu are not all really "talking" to me !

**Comment by kaikreuzer** [comment]
The specialist would be @gerrieg, I would say!

**Comment by wborn** [comment]
Closing this issue because nowadays the channel groups have a proper label and description. The Astro binding also moved to Eclipse SmartHome.

**Comment by lolodomo** [comment]
Please reopen this issue, there is clearly something to change in the Astro binding to provide different labels and descriptions. I don't understand the reason leading to its closure.

**Comment by lolodomo** [comment]
It looks like now the labels are different but all descriptions are the same "Range for a sun event" so the change was done only partially.

**Comment by wborn** [comment]
Shall we open an issue for this in the ESH issue tracker instead @lolodomo?

**Comment by lolodomo** [comment]
If you close here, yes an issue has to be recreated in ESH.
Looking at the code, there is now a label for most of groups but not all.  Descriptions are not defined.
