### ISSUE TITLE
Homematic: Signal strength is always 0 for devices that are only sending

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab2-addons#1521]
The Homematic devices are having two datapoints containing information about the signal strength: RSSI and RSSI_PEER. The binding uses RSSI as value for the signal strength. But for devices that only send data (like window contact HM-Sec-SCo and outdoor thermometer HM-WDS10-TH-O) RSSI is always 0. RSSI_PEER contains a valid value for all devices.
I would suggest to use the value of RSSI_PEER in case RSSI is zero.

What do you think, @gerrieg?

**Comment by gerrieg** [comment]
And why don't you just link RSSI_PEER to a item for these devices to show the signal strength? I don't like to have any logic on the original datapoints. 
If you really want to have only one RSSI datapoint, we should add a virtual datapoint that maps RSSI_DEVICE and RSSI_PEER with the logic you mentioned.

**Comment by MHerbst** [comment]
For users like you and me it would be of course a solution to just use RSSI_PEER.
But if somebody just wants to use the Homatic device he will run a discovery and select the channels he wants to use. In Paper UI you have the channel "Signal Strength" that is mapped to the RSSI datapoint. This channel will always have a value of 0 for several devices (at least for window contacts, thermometers and smoke detectors) and this will be confusing for most users (I also had to do some research work to understand whats happening and what the problem is). Also RSSI_PEER is only visible if you select "Show more".

But I agree with you that it is better to not add this kind of logic to original datapoints. I like the idea of a virtual datapoint and I would configure it as the source for the signal strength by default.

**Comment by gerrieg** [comment]
From this point of view you are right
I will simplify the creation of virtual datapoints, so that we can easily add such functionality.

**Comment by MHerbst** [comment]
Sounds good. Maybe it can be realized together with #1445

**Comment by gerrieg** [comment]
sure, that's the same

**Comment by MHerbst** [comment]
Retested after #1622. The new datapoint works.  There is a smaller issue (see #1842), but this one can be closed.
