### ISSUE TITLE
[amazondashbutton] Amazon Kindle is detected as dash-button

### ISSUE THREAD

**Issue by SuperOok** [openhab/openhab2-addons#1530]
Hi @OLibutzki ,

I have 4 dash buttons, however, the binding claimed that I have 5. I got an additional entry in the inbox, which is no dash button.

Checking the Mac address, I learned that the superflous dash button in fact is a kindle e-book-reader, which I have in my WLAN network.

So I guess the kindle has some similar ARP-request which gets wrongly identified as dash button.

**Comment by OLibutzki** [comment]
Which vendor prefix does your Kindle have?

**Comment by emericklaw** [comment]
It also picks up my Echos and Dots.

In case it helps these are the prefixes for Amazon devices I have.

**Echo**
50:f5:da
ac:63:be

**Dot**
ac:63:be
88:71:e5

**Dash Buttons**
34:d2:70  Qty: 1 (most recent was out of stock for a while)
50:f5:da   Qty: 4
ac:63:be   Qty: 12

**Comment by OLibutzki** [comment]
As the ac:63:be is used by multiple Amazon Devices I just don't know how to determine if the device is a Dash button. Any ideas?

**Comment by emericklaw** [comment]
Depending on how much info pcap collects about the packet contents. If you can filter by content/requested host name/ip then I could run a pcap session for a few hour and see if there is anything different between the dash buttons and the other Amazon devices.

**Comment by OLibutzki** [comment]
I use Pcap4J which wraps the native pcap commands. If there is a criteria to identify a Dash button I'm pretty sure, Pcap4J can provide this information.

I highly appreciate any help.

**Comment by emericklaw** [comment]
I have tested for a while with Wireshark and I am pretty sure there is nothing that can be done.

Since there is no guarantee how the network is setup you cannot intercept any other packets. In my setup my wifi is not connected to the same switch as the PC I was collecting data on, this mean all I saw broadcast traffic from the Amazon Dash buttons. This PC is on the same part of my network as openHAB and without an overly complicated setup (and potentially bandwidth hogging) to forward more of the general traffic to the openHAB device.

You may want to add a note mentioning it may pick up any Amazon device somewhere in the docs and maybe even on the Add Thing from Inbox screen.

**Comment by OLibutzki** [comment]
Thanks for your help. 

First of all it's a good idea to document this behaviour.

Moreover I wonder if it's better to disable background discovery and fall back to a explicit discovery mode. Using this it's less likely that a non Dash button device sends an arp / bootp request. But you can not eliminate this problem at all.

@kaikreuzer what do you think is better? Decreasing the false positives to a lower level or providing the background discovery possibility?

**Comment by kaikreuzer** [comment]
I think it depends on the amount of false positives. If we end up noticing that we cannot identify Dashs at all from the MAC, we would have to remove the auto-discovery.
If there is a good chance to find Dashs and can use the feedback of users to improve the identification, we should stick to the auto-discovery - after all, users can simply click "ignore" on a discovery result to hide it, in case it is a false positive.

**Comment by OLibutzki** [comment]
@kaikreuzer hmm, there will be false positives for every Amazon device. So for the moment disabling background discovery seems to be the best solution.

If anyone has an idea how to distinguish the devices let me know!

**Comment by SuperOok** [comment]
Sorry for being late: I liked the auto-discovery since it detects a new device at the time I press the dash-button. So there is a time-correlation of a newly discovered device to the first time the button is pressed after configured for the WLAN.
If there would simply be some informative text that I can safely ignore or disable any other detected amazon devices; it would be ok.
Background discovery would ease integration of a button since I do not have to look for the MAC Adress in my router. Or can this be avoided also without auto-discovery?

**Comment by emericklaw** [comment]
Auto discovery is useful. I have ignored some of my other Amazon devices and added some by mistake but named them something obvious.

If the ignore feature on the inbox is not enough could there be a list of ignore mac addresses that the user could add their non Dash devices to.

Or an option to enable/disable auto discovery in the addon config.

**Comment by OLibutzki** [comment]
Just to clrify this. The idea is not to disable auto discovery entirely, but to disable the background scan. So you have to scan for Dash buttons explicitly. That means you have to trigger the discovery in the Paper UI and press the Dash button. The Dash button is added to the inbox like in background discovery mode.

Using the mode we can reduce the likelihood of detecting a false positive massively as those devices only pop up in the inbox if they send an ard / bootp request in the short scanning period.

**Comment by SuperOok** [comment]
Ok, that sounds feasible.

**Comment by OLibutzki** [comment]
I think we can close this issue
