### ISSUE TITLE
Support VSX-529

### ISSUE THREAD

**Issue by Sschhsd** [openhab/openhab2-addons#1531]
Is it possible to support the pioneer VSX-529?

It is possible to control power, mute and input-source, but the control of the volume doesnt work.

For the VSX-529 the following commands (OpenHab 1) are working fine:
pioneeravr="*:livingroom:#VD"
pioneeravr="*:livingroom:#VU"

Could you please provide me the syntax for openhab2?
Could you please provide me the syntax for rule-commands for openhab2?

**Comment by Stratehm** [comment]
Please see the same issue #1344: Pioneer Binding Volume set for VSX 528 like AVRs

**Comment by Sschhsd** [comment]
Oh, sorry for opening a second issue.

Thank you!

**Comment by Stratehm** [comment]
This issue is a duplicate of #1344. Should be closed.

**Comment by martinvw** [comment]
@Stratehm thanks for mentioning
