### ISSUE TITLE
[Exec 2.0] Not possible to only execute once

### ISSUE THREAD

**Issue by chiefymuc** [openhab/openhab2-addons#1533]
Currently it is not possible to execute a command only once.

Default: interval = 15s
When putting interval=0, the handler throws an error.

It would be a good feature if it is possible to only execute a command once!

I hope @kgoderis can help?

Thanks!

**Comment by kgoderis** [comment]
Ok will fix that

**Comment by chiefymuc** [comment]
I confirm it works! Thank you!

One additional comment. I see many confused questions on the OH forums, so maybe the readme should include more information. Also I guess setting the default to 0 would probably avoid a lot of questions.

Cheers!

**Comment by steve-bate** [comment]
I suggest that not specifying an interval should result in a one-shot execution when triggered by an input command or similar event. Using zero as a magic number for disabling the periodic execution is surprising for the user, especially since it's currently undocumented (AFAICT). An interval=0 _should_ be an error since the user surely doesn't want the execution to run in a tight loop, which the value implies. It's also surprising that the execution runs periodically when no interval is requested or specified.

**Comment by steve-bate** [comment]
Unless I'm mistaken, I was seeing this behavior on the master branch. When I didn't specify an interval I saw a callback once per minute which appeared to correspond to a recent change to make the default value for the interval be 60 seconds.  I agree that any positive interval value is difficult to validate in a general way.

**Comment by steve-bate** [comment]
This is the configuration I saw that matched the behavior I was seeing (callback every 60 seconds without an interval specification).

**thing-types.xml**

```xml            
           <parameter name="interval" type="integer"  required="false">
                <label>Interval</label>
                <description>Interval, in seconds, the command will be repeatedly executed</description>
                <default>60</default>
            </parameter>
```

**Comment by kgoderis** [comment]
That is (to me) not normal as it has required=false

There is a check in the code on absence of this parameter, and if not present, nothing should be scheduled but I suspect the runtime to fill in the parameter automatically for us

@kaikreuzer what is the supposed behaviour when both required and default are defined on the Thing Type?

**Comment by kgoderis** [comment]
@kaikreuzer Can you enlighten us, and/or merge https://github.com/openhab/openhab2-addons/pull/1637/files?

**Comment by kaikreuzer** [comment]
A default value will be used, if nothing else is specified by the user. So as it is not required, the value will be 60 - apparently not what you intended, right?

**Comment by mavris** [comment]
Having this code `Thing exec:command:switchTV [command="python /opt/BroadLink/BlackBeanControl/BlackBeanControl.py -c SwitchTV" interval=0, timeout=10, autorun=false]` the command is executed each 60 secs. Any recommendations how to disable the loop?

**Comment by tavalin** [comment]
@mavris aren't you missing a comma before interval=0?
