### ISSUE TITLE
[onkyo] Command LISTEN_MODE_QUERY (LMDQSTN) causes sound interruption Onkyo TX8050 

### ISSUE THREAD

**Issue by dvolochnik** [openhab/openhab2-addons#1534]
I've tested onkyo binding with my TX8050 receiver and as soon as Onkyo Thing was online, the receiver started to have short sounds interruptions approximately every second. Further investigation showed, that the interruptions happened every time right after the binding send status query to the receiver.

After few experiments, it was clear, that problem is caused by 
`sendCommand(EiscpCommandRef.LISTEN_MODE_QUERY)`
command in the checkStatus() function.

So easy and dirty solution was to comment out problematic row as following:
`private void checkStatus() {

        sendCommand(EiscpCommandRef.POWER_QUERY);
        sendCommand(EiscpCommandRef.VOLUME_QUERY);
        sendCommand(EiscpCommandRef.SOURCE_QUERY);
        sendCommand(EiscpCommandRef.MUTE_QUERY);
        sendCommand(EiscpCommandRef.ZONE2_POWER_QUERY);
        sendCommand(EiscpCommandRef.ZONE2_VOLUME_QUERY);
        sendCommand(EiscpCommandRef.ZONE2_SOURCE_QUERY);
        sendCommand(EiscpCommandRef.ZONE2_MUTE_QUERY);

        // sendCommand(EiscpCommandRef.LISTEN_MODE_QUERY);

        if (connection != null && connection.isConnected()) {
            updateStatus(ThingStatus.ONLINE);
        } else {
            updateStatus(ThingStatus.OFFLINE);
        }
    }`
After that the problem was gone.

Most likely, it is a model specific problem which exists only for TX8050 receiver, but, anyway, is there any workaround, or, probably, somebody can create one?

**Comment by marcelrv** [comment]
I think currently there is no workaround.
we need to ask @pail23 what is the purpose of the frequent polling of status, as while being connected seems all updates are already send, hence the polling may not be needed at all (or very limited)

Alternatively, we could make the polling frequency a configuration option, so in your case you can set it to very slow/disable

**Comment by Cossey** [comment]
It doesn't look like @dvolochnik is active on GitHub anymore.

The polling is now defaulted to 0 in current versions and looking at the code this problem should only appear for a brief moment when openHab connects to the device.

As noted by @marcelrv the protocol does send unsolicited updates when values change so polling is probably there for those receivers that have unstable EISCP/networking implementations.

@cweitkamp can you get someone to close this issue please?

**Comment by cweitkamp** [comment]
@Cossey Yes, I can. Thanks for cleaning up the Onkyo issues.
