### ISSUE TITLE
[pulseaudio] No sinks discovered

### ISSUE THREAD

**Issue by bepat** [openhab/openhab2-addons#1538]
I tried the pulseaudio binding 2.0 but it discovers no items. 
I found out, that the pulseaudio client ist waiting for ">>> " to determine the end of the answer from the server.
I am using the pulseaudio module "module-cli-protocol-tcp" like described in the readme file.
This modules does not send ">>> " at the end of the answer. I have tested this with telnet. 
So the pulseaudio client runs into a SocketTimeoutException and returns an empty string from the function "_sendRawRequest".
I changed this to 'return result;' instead of 'return "";'. This seems to work fine for me.
Is this a general behavior? Or is something wrong with my pulseaduio configuration?

**Comment by kaikreuzer** [comment]
@peuter Could you comment?

**Comment by peuter** [comment]
I have to take closer look into that when I find the time. It almost 2 years ago since I wrote that, so I have to read and test a little bit to understand whats going on there. Maybe pulseaudio changed something in the protocol behaviour. @bepat Which pulseaudio version do you use?

**Comment by bepat** [comment]
I am using PulseAudio 5.0 on a raspberry Pi 3.
I also traced the communication with WireShark, to see if there is another char or something else to determine the end. I found nothing.
The last char is a new line.

**Comment by peuter** [comment]
Ok just checked my pulseaudio production system is in 4.0 and that has the '>>>', my desktop system has pulseaudio 8.0 without '>>>'. So as you found the problem with 5.0 they must have changed the behaviour there. @bepat As you already hav found a solution which to fix the problem I would suggest that you create a pull request with that change and as @kaikreuzer to merge that PR.

**Comment by peuter** [comment]
There seem to be more syntax changes here. The volume parsing does not work either with PA 8.0. It seems that I have to change some regular expressions there. @bepat I you want to I can fix everything in one pull request.

**Comment by peuter** [comment]
@bepat Could you please check if my fix is working with pulseaudio 5.0 as I only tested it with 4.0 and 8.0?

**Comment by bepat** [comment]
@peuter Sorry for that late response! It works well with pulseaudio 5.0.
Thank you!
