### ISSUE TITLE
[amazondashbutton] Config item for polling period and even instant response?

### ISSUE THREAD

**Issue by emericklaw** [openhab/openhab2-addons#1544]
Would it be possible to allow configuration of the polling duration from within the UI?

With the current delay of 2 seconds I can either get lucky and press the button milisends before the poll or get unlucky and press just after a poll has completed.

I am not familiar with pcap so this next part may not be possible. Can it be setup to listen constantly and immediately trigger when a request is made?

**Comment by emericklaw** [comment]
I meant to include you @OLibutzki

**Comment by OLibutzki** [comment]
I'm not sure I got you right. The binding listens constantly for arp and bootp udp packets. 

The delay is caused by the device and the network as it takes some time until the requests are submitted after pressing the button.

**Comment by emericklaw** [comment]
I will close this, you are correct and I saw this when looking at Wireshark relating to #1530 

Thanks
