### ISSUE TITLE
EXEC not working

### ISSUE THREAD

**Issue by htrampe** [openhab/openhab2-addons#1545]
Hi! I'am using the latest openhab2-beta4-release and installed the EXEC-Binding 2.0 Snapshot by HABmin. I insert the code for a switch-Item. The item is visibly in the basic ui. But when iam clicking on it its not working. I can fired it up with openhab-user by using the terminal. So what's wrong? Biggest Problem: in the openhab2.log-file is nothing saved for the exec-binding. Also when iam writing a wrong path the log-file does not give any information. Can someone help? THX!

**Comment by kaikreuzer** [comment]
You will actually have to use a snapshot, it is a mistake that the exec 2 binding appears in the beta4 online version.
Using https://openhab.ci.cloudbees.com/job/openHAB-Distribution/ should work nicely!

**Comment by htrampe** [comment]
No, sorry - nothing happened. I installed latest version (snapshot), installed the EXEC-Binding with HAbmin, make shure that i can execute the script as openhab-user (su openhab) but nothing happens. Here is my item-content:
`Group funksteckdosen

Switch FS_SZ_lampe { exec=">[ON:/etc/openhab2/scripts/brennstuhl_switch.sh 1 4 10000] >[OFF:/etc/openhab2/scripts/brennstuhl_switch.sh 0 4 10000]" }
`
Here is my Script:
`
#!/bin/bash
gpio -1 mode 0 out

if [ "$1" == 1 ]; then
        #gpio -1 write 11 1
        ssh root@192.168.178.150 "/usr/local/bin/send $3 $2 1"
else
        #gpio -1 write 11 0
        ssh root@192.168.178.150 "/usr/local/bin/send $3 $2 0"
fi

`

**Comment by kaikreuzer** [comment]
Your config is for Exec1 binding, not for Exec2.
Please check http://docs.openhab.org/addons/bindings/exec/readme.html and use our community for further questions: https://community.openhab.org/

**Comment by kgoderis** [comment]
@kaikreuzer FYI, read on openhab.org is not in sync with GitHub repo.
