### ISSUE TITLE
Replace freeboxos-java lib with EPL version

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab2-addons#1546]
@clinique I just by chance came across [this line](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.freebox/about.html#L36).
First of all, the link to the license there is broken. Then it claims it is GPL (which caught my attention as this is a no-go), while in reality the lib is under LGPL.

Looking at this lib, I noticed that it has been dual-licensed under the EPL now as well since two months.
I think it would make a lot of sense to update the lib to the EPL version as this would be a much better fit for us. Could you take a look into that?

**Comment by clinique** [comment]
Yes sir, I'll do.

**Comment by lolodomo** [comment]
Good news, it was our request since a long time. I was not aware that the change has been done.
For info, I was given the write rights to this project few weeks ago.
