### ISSUE TITLE
[OH2] NetAtmo - Binding -  No continuous values

### ISSUE THREAD

**Issue by LukaNoah** [openhab/openhab2-addons#1550]
After few hours the values are not up to date. Only 1 refresh in 1 to 2 hours. Whats wrong? 
Latest OH2 snapshot. 

> 2016-12-09 12:35:41.966 [ERROR] [netatmo.handler.NetatmoBridgeHandler] - An error occured while calling station API : 403 Forbidden
![image](https://cloud.githubusercontent.com/assets/16850444/21056514/38fe6f2c-be36-11e6-9a76-288e0738800c.png)

**Comment by lolodomo** [comment]
Default update interval is 10 minutes (600000 ms). What value did you set ?
I can see sometimes a 403 error.

**Comment by LukaNoah** [comment]
I have also an update intervall froh 10 minutes. This value is not changeable. After save , oh says bad request .

**Comment by LukaNoah** [comment]
here are the timestamps from the last days.
first coloumn - timestamp from oh by received a change from netatmo
2nd coloumn - last message by netatmo
[netatmo.zip](https://github.com/openhab/openhab2-addons/files/650392/netatmo.zip)

**Comment by LukaNoah** [comment]
no ideas?

**Comment by lolodomo** [comment]
I am a little lost. What is the problem exactly ?
You are showing to us that OH discovers netatmo value changes with a certain delay ? Yes, that is normal, OH scans for updated values every 10 minutes, so you could discover a value has changed with a delay of 10 minutes compared to what is shown by the netatmo appmlication.
I am not sure what is the value in your second column and how you retrieved it. Netatmo is not sending messages but the binding is requesting the netatmo for values.
@clinique: can you please enter in this discussion ?
The only point I can confirm is that sometimes a request of data by the binding is rejected by the netatmo with a 403 error (only few times during a day).

**Comment by LukaNoah** [comment]
Please show at the datatable. At the left coloumn should be an update every 10 minutes. I know about the delay between NetAtmo an oh.
When new values received, is the difference ok. But NetAtmo read not values every 10 minutes. 6 o'clock, 8 o'clock, 11 o'clock and so on...
The left Column is the timestamp from oh, when a NetAtmo-update received. It should be in a 10 minutes cycle. It isn't.
The cycle is now definied in the main-indoor-module? 600000ms and save will be show bad request.

**Comment by LukaNoah** [comment]
I made a new clean installion on my pi.
It's running at time....
