### ISSUE TITLE
openhab.target could not resolve

### ISSUE THREAD

**Issue by SuperOok** [openhab/openhab2-addons#1551]
Hi @kaikreuzer 

I just followed the [Installation guide for IDE setup for OH2-addons|http://docs.openhab.org/developers/development/bindings.html].
Ultimately the target platform did not resolve properly in my Windows 10 with Neon.1 with the error message below

![grafik](https://cloud.githubusercontent.com/assets/10581272/21050750/de1d21c0-be1c-11e6-9180-176c6abeef8d.png)

Even cleaning does not help that there seems to be nothing in the target afterwards; no dependencies are found

![grafik](https://cloud.githubusercontent.com/assets/10581272/21050826/4758eb4c-be1d-11e6-8962-a4347248fd9a.png)

Any ideas?

Cheers,
Hauke

**Comment by kaikreuzer** [comment]
You have a bad timing. This just broke around lunch time due to a new ESH stable release.
And I was just fixing it through https://github.com/openhab/openhab-distro/pull/346.
So please pull this change and refresh your target platform - all should be fine again then :-)

**Comment by SuperOok** [comment]
ok, thanks, works fine now
