### ISSUE TITLE
org.openhab.io.transport.serial

### ISSUE THREAD

**Issue by stormwalkerec** [openhab/openhab2-addons#1562]
latest openhab2 - and your download

2016-12-10 23:46:37.580 [INFO ] [org.openhab.io.transport.serial     ] - FrameworkEvent INFO - org.openhab.io.transport.serial
org.osgi.framework.BundleException: The bundle class path entry "lib/nrjavaserial-3.9.3.jar" could not be found for the bundle "osgi.identity; osgi.identity="org.openhab.io.transport.serial"; type="osgi.bundle"; version:Version="2.0.0.201612091415""

I downloaded and compiled nrjavaserial-3.12.0.jar, it is specifically looking still for 3.9.3

**Comment by kaikreuzer** [comment]
You mean you tried to patch the existing bundle? I see that it correctly contains lib/nrjavaserial-3.9.3.jar and I have never seen your message before in a log. How to reproduce?

**Comment by stormwalkerec** [comment]
I have a odroid c1+ with  Ubuntu 16.04.1 LTS

Fresh install - updated

Then I followed these commands:

//Install Java and Openhab2-offline
add-apt-repository ppa:webupd8team/java
apt-get update
apt-get install oracle-java8-installer
apt install oracle-java8-set-default

echo 'deb https://openhab.ci.cloudbees.com/job/openHAB-Distribution/ws/distributions/openhab-offline/target/apt-repo/ /' | sudo tee /etc/apt/sources.list.d/openhab2.list
echo 'deb https://openhab.ci.cloudbees.com/job/openHAB-Distribution/ws/distributions/openhab-online/target/apt-repo/ /' | sudo tee --append /etc/apt/sources.list.d/openhab2.list
wget -qO - 'http://www.openhab.org/keys/public-key-snapshots.asc' | sudo apt-key add -

apt-get install apt-transport-https vim-nox input-utils git
apt-get update
apt-get install openhab2-offline

sudo systemctl daemon-reload
sudo systemctl enable openhab2.service
sudo systemctl start openhab2.service

//Install your serial binding
sudo usermod -a -G dialout openhab

wget https://github.com/tobof/openhab2-addons/blob/MySensors/addons/binding/org.openhab.binding.mysensors/target/org.openhab.binding.mysensors-2.0.0-SNAPSHOT.jar?raw=true

mv org.openhab.binding.mysensors-2.0.0-SNAPSHOT.jar?raw=true org.openhab.binding.mysensors-2.0.0-SNAPSHOT.jar
sudo cp /tmp/org.openhab.binding.mysensors-2.0.0-SNAPSHOT.jar /usr/share/openhab2/addons/
chmod openhab.openhab /usr/share/openhab2/addons/org.openhab.binding.mysensors-2.0.0-SNAPSHOT.jar

/usr/share/openhab2
./start.sh

feature:install openhab-transport-serial

logout

//Check Log, see that error - then tried:
git clone https://github.com/NeuronRobotics/nrjavaserial.git

https://github.com/NeuronRobotics/nrjavaserial.git

sudo add-apt-repository ppa:cwchien/gradle
sudo apt-get update
sudo apt-get install gradle

cd nrjavaserial
gradle build

//It then installed a different version in the system, but your one still looks for that specific version.

//Maybe it is a permission issue ? I did change it all as per the documentation to the openhab user ...

**Comment by kaikreuzer** [comment]
nrjavaserial does not support 64bit ARM Linux, you should use a 32-bit JVM instead, see https://github.com/NeuronRobotics/nrjavaserial/issues/72.
