### ISSUE TITLE
Harmony Initializing Items/Things twice when OpenHab-2 ver 637 restarts

### ISSUE THREAD

**Issue by Royw51** [openhab/openhab2-addons#1563]
and things go to a status of "initializing"  When I remove the items/things using Paper Gui, do a search with the Harmony binding. It finds the items/things and brings them online.  If I stop/start openhab, I must go through that same process to again get them come back on line.  Just a side note, I noticed this same behavior in version 636.

```
07:41:47.643 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'harmonyhub:hub:Mediaroom' changed from UNKNOWN to ONLINE
07:41:47.644 [WARN ] [ome.core.thing.internal.ThingManager] - Attempt to initialize a handler twice for thing 'harmonyhub:device:Mediaroom:30397210' at the same time will be ignored.
07:41:47.645 [INFO ] [smarthome.event.ThingUpdatedEvent   ] - Thing 'harmonyhub:device:Mediaroom:30397210' has been updated.
07:41:47.673 [WARN ] [ome.core.thing.internal.ThingManager] - Attempt to initialize a handler twice for thing 'harmonyhub:device:Mediaroom:30397246' at the same time will be ignored.
07:41:47.673 [INFO ] [smarthome.event.ThingUpdatedEvent   ] - Thing 'harmonyhub:device:Mediaroom:30397246' has been updated.
07:41:47.687 [WARN ] [ome.core.thing.internal.ThingManager] - Attempt to initialize a handler twice for thing 'harmonyhub:device:Mediaroom:30396771' at the same time will be ignored.
07:41:47.687 [INFO ] [smarthome.event.ThingUpdatedEvent   ] - Thing 'harmonyhub:device:Mediaroom:30396771' has been updated.
07:41:47.696 [WARN ] [ome.core.thing.internal.ThingManager] - Attempt to initialize a handler twice for thing 'harmonyhub:device:Mediaroom:30396823' at the same time will be ignored.
07:41:47.696 [INFO ] [smarthome.event.ThingUpdatedEvent   ] - Thing 'harmonyhub:device:Mediaroom:30396823' has been updated.
07:41:47.710 [WARN ] [ome.core.thing.internal.ThingManager] - Attempt to initialize a handler twice for thing 'harmonyhub:device:Mediaroom:30397319' at the same time will be ignored.
07:41:47.710 [INFO ] [smarthome.event.ThingUpdatedEvent   ] - Thing 'harmonyhub:device:Mediaroom:30397319' has been updated.
```

**Comment by tratho** [comment]
Same here

**Comment by kaikreuzer** [comment]
I doubt that it is related to #1480.

It rather looks like a bug in the ESH ThingManager - @sbussweiler & @sjka, could you have a look?

@Royw51 Could you provide a log with enabled debugging for the ThingManager? On the console, simply set
```
log:set DEBUG org.eclipse.smarthome.core.thing
```
Thanks!

**Comment by Royw51** [comment]
I have the logs but not sure how/where to upload.

**Comment by tratho** [comment]
HarmonyHubHandler.java

private synchronized void connect() {
        updateStatus(ThingStatus.INITIALIZING);

        disconnectFromHub();

        HarmonyHubConfig config = getConfig().as(HarmonyHubConfig.class);
        discoTime = config.discoveryTimeout > 0 ? config.discoveryTimeout : DISCO_TIME;
        heartBeatInterval = config.heartBeatInterval > 0 ? config.heartBeatInterval : HEARTBEAT_INTERVAL;

        discovery = new HarmonyHubDiscovery(discoTime);
        discovery.addListener(this);
        discovery.startDiscovery();
    }

updateStatus(ThingStatus.INITIALIZING); is not allowed any more afaik.

@kaikreuzer yes you are right i think. I only wanted to show, that there are still some problems with the binding

**Comment by Royw51** [comment]
Never mind... Read Roy Read... 
here are the log files.

[events_201612111222.txt](https://github.com/openhab/openhab2-addons/files/644669/events_201612111222.txt)
[openhab_201612111222.txt](https://github.com/openhab/openhab2-addons/files/644670/openhab_201612111222.txt)

**Comment by kaikreuzer** [comment]
@tratho The code you have posted does not exist anymore, I had fixed that [here](https://github.com/openhab/openhab2-addons/pull/1552/files) already (and this fix is part of distro 637).

@Royw51 Thanks for the logs, this will definitely help for the analysis.
@sbussweiler: From a first glance I would say that the ThingManager tries to register the handler twice: Once as a child of a bridge and once for the thing itself. Might this be the problem?

**Comment by kaikreuzer** [comment]
FTR: [Here](https://community.openhab.org/t/harmony-hub-binding-unreliable/18146) are also logs, where Things stay in INITIALIZING status, although the Harmony handler does a 
```
    public void initialize() {
        updateStatus(ThingStatus.UNKNOWN);
        connect();
    }
```
so this clearly hints that there is a bug in the framework.

**Comment by sjka** [comment]
Let's ignore the double-attempt to initialize the thing. The log entry is ugly, but it's a normal anticipated case.

The things are in `INITIALIZING` state, therefore the framework is fine. However, we noticed that the Hamrony thing handler does the following

```java
    private void updateBridgeStatus() {
        ThingStatus bridgeStatus = getBridge().getStatus();
        if (bridgeStatus == ThingStatus.ONLINE && getThing().getStatus() != ThingStatus.ONLINE) {
            bridge = (HarmonyHubHandler) getBridge().getHandler();
            updateStatus(ThingStatus.ONLINE);
            updateChannel();
        } else if (bridgeStatus == ThingStatus.OFFLINE) {
            updateStatus(ThingStatus.OFFLINE, ThingStatusDetail.BRIDGE_OFFLINE);
        }
    }
```

This leaves a case where no status is set. Fix this, and all is going to be good :-D

**Comment by kaikreuzer** [comment]
> This leaves a case where no status is set.

Not sure I understand. How can this be if the status is always set to UNKNOWN in initialize as mentioned in https://github.com/openhab/openhab2-addons/issues/1563#issuecomment-266997568?

**Comment by kaikreuzer** [comment]
> Let's ignore the double-attempt to initialize the thing. The log entry is ugly, but it's a normal anticipated case.

Can you elaborate on this, why it is normal? Is there anything that can be done to make the logging less ugly in anticipated situations?

**Comment by sbussweiler** [comment]
> Can you elaborate on this, why it is normal?

If the bridge handler has been initialized, the framework tries to initialize all child handlers. At the same time a child thing is added and the framework also tries to initialize the child handler (because the bridge handler is already initialized). The _first one_ is the winner, the _second one_ causes the log entry.

**Comment by kaikreuzer** [comment]
Right, this was my analysis in https://github.com/openhab/openhab2-addons/issues/1563#issuecomment-266302611. But do you really consider this "normal", i.e. does that make sense? Why do you at all TRY to initialize a thinghandler for which there is a bridge configured, if you already know that it will also be initialized once the its bridge handler is initialized?

**Comment by sjka** [comment]
> do you really consider this "normal", i.e. does that make sense

No, as I said: it's ugly! But that's how it is implemented right now. 

My original point was: this is not related to the things staying in INITIALIZING state. However, I just realize that we still didn't spot the root-cause for this.

**Comment by tratho** [comment]
I still think, it is related to #1480, because, my dirty hack, mentioned in this thread, works "fine" for me! I have no " Attempt to initialize a handler twice for thing" in my logs!

**Comment by Homey-GER** [comment]
I have this problem too.

Very annoying as I have about 10 "Things" that need to get deleted and added again everytime I restart openHab.

Hope it will get fixed soon 👍 If I can help somehow ... just let me know ;)

**Comment by ianj001** [comment]
I have this issue too, when I restart openHAB2 I have to go into the paper UI delete all my harmony things and re-add them then they work.
