### ISSUE TITLE
HmIP Door Window Contact paired as String, not as Contact

### ISSUE THREAD

**Issue by FrankZimmer** [openhab/openhab2-addons#1564]
The new HmIP SWDO (Door Window Contact) will be paired with Paperui as

```
homematic_HMIP_SWDO_1cffcc63_0000D3C98C9A98_0_RSSI_DEVICE (Type=NumberItem, State=-58, Label=Signal Strength, Category=QualityOfService)
homematic_HMIP_SWDO_1cffcc63_0000D3C98C9A98_1_STATE (Type=StringItem, State=OPEN, Label=State, Category=null)
openhab>
```

State as String Item. But it must be a ContactItem
To compare with the HM Classic , see here

```
homematic_HM_Sec_SC_2_1cffcc63_LEQ0140613_0_LOWBAT (Type=SwitchItem, State=OFF, Label=Low Battery, Category=Battery)
homematic_HM_Sec_SC_2_1cffcc63_LEQ0140613_0_RSSI_DEVICE (Type=NumberItem, State=0, Label=Signal Strength, Category=QualityOfService)
homematic_HM_Sec_SC_2_1cffcc63_LEQ0140613_1_LOWBAT (Type=SwitchItem, State=OFF, Label=Low Battery, Category=Battery)
homematic_HM_Sec_SC_2_1cffcc63_LEQ0140613_1_STATE (Type=ContactItem, State=CLOSED, Label=null, Category=null)
```
Anybody else has this issue?

I'm using OH2 with a CCU2 (latest build from Homematic Binding), no issues in the log...

**Comment by MHerbst** [comment]
Hmm, strange. I have got the HM-Sec-ScO (similar to to HmIP-SWDO but not using IP). This is also OK. 
I think that is something for @gerrieg

**Comment by gerrieg** [comment]
I have to see the metadata, so please switch the binding into TRACE mode and send me a full startup log.
```
log:set TRACE org.openhab.binding.homematic
```

**Comment by FrankZimmer** [comment]
[log.txt](https://github.com/openhab/openhab2-addons/files/649861/log.txt)

I pared the device with log det to trace

New Device has the ID 0000D3C98C9A98

**Comment by gerrieg** [comment]
The type of the datapoint is not BOOL but ENUM with two options. And enum is a String in openHab. The mapping is correct, but i agree that this is not optimal. Maybe the datapoint gets more options in the future.
```
name=STATE,type=ENUM,options=CLOSED;OPEN
```

I will soon start a refactoring of the virtual datapoints in the binding and i will add a CONTACT_STATE datapoint that maps to a Contact.

**Comment by MHerbst** [comment]
@FrankZimmer @gerrieg Is this issue still open? To me it seems that it can be closed

**Comment by itheiss** [comment]
Don't know if this is related to this issue but HmIP SWDO (Door Window Contact) still fails to work with Type=ContactItem. I am facing exact the same problem as described [here](https://community.openhab.org/t/homematic-window-state-is-null-for-contact-but-closed-for-strings/27868). 

My thing definition:
`Thing HMIP-SWDO 0000D7098E3B90 "Fensterkontakt Wohnzimmer - Süd" @ "LIVINGROOM"`

My item definition:
`Contact SHUTTER_CONTACT_STATE_LIVINGROOM_SOUTH       "Fensterkontakt - Süd [%s]"    <contact>   { channel="homematic:HMIP-SWDO:ccu2:0000D7098E3B90:1#STATE_CONTACT" }
`

openHAB console:
`openhab> smarthome:items list SHUTTER_CONTACT_STATE_LIVINGROOM_SOUTH
SHUTTER_CONTACT_STATE_LIVINGROOM_SOUTH (Type=ContactItem, State=NULL, Label=Fensterkontakt - Süd, Category=contact)`

This shows in the trace when I open the window:
`2017-06-05 16:59:02.854 [DEBUG] [ommunicator.AbstractHomematicGateway] - Received new (Integer) value '-69' for '0000D7098E3B90:0#RSSI_DEVICE' from gateway with id 'ccu2'
2017-06-05 16:59:02.855 [DEBUG] [ommunicator.AbstractHomematicGateway] - Received new (Boolean) value 'false' for '0000D7098E3B90:0#SABOTAGE' from gateway with id 'ccu2'
2017-06-05 16:59:02.855 [DEBUG] [ommunicator.AbstractHomematicGateway] - Received new (Boolean) value 'false' for '0000D7098E3B90:0#DUTY_CYCLE' from gateway with id 'ccu2'
2017-06-05 16:59:02.855 [DEBUG] [ommunicator.AbstractHomematicGateway] - Received new (Boolean) value 'false' for '0000D7098E3B90:0#LOW_BAT' from gateway with id 'ccu2'
2017-06-05 16:59:02.856 [DEBUG] [ommunicator.AbstractHomematicGateway] - Received new (Integer) value '0' for '0000D7098E3B90:0#ERROR_CODE' from gateway with id 'ccu2'
2017-06-05 16:59:02.856 [DEBUG] [ommunicator.AbstractHomematicGateway] - Received new (Boolean) value 'false' for '0000D7098E3B90:0#UNREACH' from gateway with id 'ccu2'
2017-06-05 16:59:02.856 [DEBUG] [ommunicator.AbstractHomematicGateway] - Received new (Double) value '1.5' for '0000D7098E3B90:0#OPERATING_VOLTAGE' from gateway with id 'ccu2'
0000D7098E3B90:1
2017-06-05 16:59:02.868 [DEBUG] [ommunicator.AbstractHomematicGateway] - Received new (Integer) value '1' for '0000D7098E3B90:1#STATE' from gateway with id 'ccu2'
2017-06-05 16:59:02.869 [TRACE] [converter.type.AbstractTypeConverter] - Converting ENUM value '1' with StringTypeConverter for '0000D7098E3B90:1#STATE'
2017-06-05 16:59:02.870 [TRACE] [converter.type.AbstractTypeConverter] - Converting BOOL value 'null' with OpenClosedTypeConverter for '0000D7098E3B90:1#STATE_CONTACT'
`

The STATE_CONTACT is always 'null'

**Comment by MHerbst** [comment]
Which version of the Homematic binding are you using? I have checked the commit history and about 4 months ago @gerrieg  made a change regarding this device.

**Comment by itheiss** [comment]
Hi,

I am using openHAB 2.1.0 Build #929 with the corresponding native openHAB2 Homematic binding.

Regards
Ingo

**Comment by MHerbst** [comment]
Hi Ingo,

the modification was definitely contained in the is build but I am not sure wether the implementation is correct. It seems that the CCU sends a value "1" but the virtual datapoint vor STATE_CONTACT only expectss "OPEN" and "CLOSED" as valid values (these values are sent by the older window contact device).

Can you check it @gerrieg ? I won't find time for it before next weekend.

**Comment by gerrieg** [comment]
The implementation of the virtual datapoint is wrong, i expect open/closed but the value is a integer 0/1. I fixed this now, but i'm not sure if i should return true or false for closed/open
I have no time to test it, so please try this PR. There is a 50:50 chance that it is correct 😃 

https://github.com/openhab/openhab2-addons/pull/2346

**Comment by itheiss** [comment]
Thanks for taking care of this. I am not yet able to build this myself. Could you please add a WIP to the title, so I can grap the jar and test it.

Regards
Ingo

**Comment by martinvw** [comment]
https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/org.openhab.binding.homematic/2.1.0-SNAPSHOT/org.openhab.binding.homematic-2.1.0-SNAPSHOT.jar

**Comment by martinvw** [comment]
@gerrieg @itheiss note that that is not needed, any PR will allow you to grab the jar. However if you create a PR just to allow others to grab the PR it is clear to everyone that it is not ready if you add WIP. But it only influences humans not the build-software :-)

**Comment by itheiss** [comment]
Thanks for the explanation @martinvw . Somehow I thought WIP was a kind of trigger :-)
I will test and and give feedback ...

**Comment by itheiss** [comment]
Mmmh either I am doing something wrong or nothing has changed with the new implementation.

I installed the `org.openhab.binding.homematic-2.1.0-SNAPSHOT.jar` and it's active Bundle-Id 229:

_218 | Active    |  80 | 2.1.0.201705282306     | openHAB 1.x Compatibility Layer
219 | Active    |  80 | 2.1.0.201705282306     | openHAB Cloud Connector Bundle
220 | Active    |  80 | 2.1.0.201705282306     | openHAB REST Documentation
221 | Active    |  80 | 1.10.0.201705220110    | openHAB InfluxDB Persistence bundle
222 | Resolved  |  80 | 2.1.0.201705282306     | openHAB Basic UI Fragment, Hosts: 213
223 | Resolved  |  80 | 2.1.0.201705282306     | openHAB Paper UI Theme Fragment, Hosts: 214
224 | Active    |  80 | 2.1.0.201705282306     | MaryTTS Voice Service
225 | Active    |  80 | 0.9.10.v20160429-1435  | reflections (wrap)
226 | Active    |  80 | 1.5.8.v20160511-1038   | swagger-jersey2-jaxrs (wrap)
228 | Active    |  80 | 2.1.0.201705282035     | Robonect Binding
229 | Active    |  80 | 2.1.0.201706082024     | Homematic Binding
230 | Installed |  80 | 2.1.0.201705282306     | Homematic Binding_

Here is a trace I captured from one of the sensors:

`2017-06-09 14:22:46.000 [DEBUG] [ommunicator.AbstractHomematicGateway] - Received new (Integer) value '-62' for '0000D7098E3B90:0#RSSI_DEVICE' from gateway with id 'ccu2'
2017-06-09 14:22:46.000 [DEBUG] [ommunicator.AbstractHomematicGateway] - Received new (Boolean) value 'false' for '0000D7098E3B90:0#SABOTAGE' from gateway with id 'ccu2'
2017-06-09 14:22:46.001 [DEBUG] [ommunicator.AbstractHomematicGateway] - Received new (Boolean) value 'false' for '0000D7098E3B90:0#DUTY_CYCLE' from gateway with id 'ccu2'
2017-06-09 14:22:46.001 [DEBUG] [ommunicator.AbstractHomematicGateway] - Received new (Boolean) value 'false' for '0000D7098E3B90:0#LOW_BAT' from gateway with id 'ccu2'
2017-06-09 14:22:46.001 [DEBUG] [ommunicator.AbstractHomematicGateway] - Received new (Integer) value '0' for '0000D7098E3B90:0#ERROR_CODE' from gateway with id 'ccu2'
2017-06-09 14:22:46.002 [DEBUG] [ommunicator.AbstractHomematicGateway] - Received new (Boolean) value 'false' for '0000D7098E3B90:0#UNREACH' from gateway with id 'ccu2'
2017-06-09 14:22:46.002 [DEBUG] [ommunicator.AbstractHomematicGateway] - Received new (Double) value '1.4' for '0000D7098E3B90:0#OPERATING_VOLTAGE' from gateway with id 'ccu2'
0000D7098E3B90:1
2017-06-09 14:22:46.015 [DEBUG] [ommunicator.AbstractHomematicGateway] - Received new (Integer) value '0' for '0000D7098E3B90:1#STATE' from gateway with id 'ccu2'
2017-06-09 14:22:46.016 [TRACE] [converter.type.AbstractTypeConverter] - Converting BOOL value 'null' with OpenClosedTypeConverter for '0000D7098E3B90:1#STATE_CONTACT'`

What is the difference between 0000D7098E3B90:1#STATE and 0000D7098E3B90:1#STATE_CONTACT? 

My item is bound to 0000D7098E3B90:1#STATE_CONTACT as this channel is declared as Contact. The channel 0000D7098E3B90:1#STATE is from type String. 

`My item definition:
Contact SHUTTER_CONTACT_STATE_LIVINGROOM_SOUTH "Fensterkontakt - Süd [%s]" <contact> { channel="homematic:HMIP-SWDO:ccu2:0000D7098E3B90:1#STATE_CONTACT" }`

With this item definition nothing is displayed. I am confused ...

**Comment by gerrieg** [comment]
The difference is, that STATE is the original datapoint in the CCU. It's a enum with two values so i have to map it to a String. The STATE_CONTACT is a virtual datapoint that exists only in the binding and simulates a datapoint/channel that can be mapped to a Contact.

It's strange that the virtual datapoint is not executed. I have now implemented some debug messages, please try this jar file: [Download](https://drive.google.com/file/d/0Bw7zjCgsXYnHM1BCeXVCQUN1TVk/view?usp=sharing)

Thanks!

**Comment by itheiss** [comment]
Hi Gerhard,

with the "debug jar" everything is working now, so I think it must be my fault in the first try :-(
Nevertheless I have attached the trace:
[openhab.log.txt](https://github.com/openhab/openhab2-addons/files/1065752/openhab.log.txt)

From my point of view it's working and ready to merge.

Thanks for your time and efforts!

Regards
Ingo

**Comment by itheiss** [comment]
@martinvw I think we can close this issue as  #2346 was merged - right?

**Comment by martinvw** [comment]
thanks for reminding me!

**Comment by jensrossbach** [comment]
Hi, I have a Homematic IP invisible door/window contact (HmIP-SWDO-I) with the same problem as described here. But I see only the STATE channel and no CONTACT_STATE channel. Has this fix maybe only been done for the HmIP-SWDO?
