### ISSUE TITLE
Working on cm11a binding for legacy X-10 devices

### ISSUE THREAD

**Issue by BobRak** [openhab/openhab2-addons#1566]
I have picked up the work started by "engineergreen" and committed at: [Orignal cm11a code]((https://github.com/engineergreen/openhab/tree/cm11a-binding/bundles/binding/org.openhab.binding.cm11a)

I have converted his implementation to OpenHAB 2.  Engineergreen's work allows switches and dimmers to be controlled by sending X10 commands over the serial interface. In addition he started implementing code to listen to date coming from the cm11a to the PC. I have extended that and am able to now successfully decode the serial data into an address and function.  The goal of that is to be able to update the UI if a switch or dimmer is changed by a different controller.

Here is what is left to do:
1. Update the UI with data received on the serial port. I'm still trying to figure out how to do that. And, at the same time update the state in the appropriate "thing" classes to reflect what has happened external to OpenHAB.
2. Persist the state of each switch / dimmer and restore it on start up.
3. Cleanup the code, ad good JavaDoc, create the readme.MD file.

**Comment by brucejackson** [comment]
Hi @BobRak 

I experimented earlier this year with this binding to enable it to receive an X10 command and then cause OpenHab to open a URL (causing some function to happen).  Primarily it was to work with HomeLink Cars.

The code is here:  https://github.com/brucejackson/openhab-cm11a

As I recall, I added [some configuration items](https://github.com/brucejackson/openhab-cm11a/blob/develop/README.md) detailing the command code to listen for and URL to execute an x10 is received.  

Most of the processing is in the receivedData function in [X10Interface.java](https://github.com/brucejackson/openhab-cm11a/blob/master/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/internal/X10Interface.java)

I don't know it this will be of any use to you.  I have not attempted to update this to OpenHab2.

Bruce.

**Comment by brucejackson** [comment]
If it helps you,  I would be more than happy to help test the 2.0 version of the binding.  I just installed 2.0b4 this weekend.

**Comment by robertjackson17** [comment]
Hi @BobRak 

I'm also interested in your efforts to bring the cm11a into OpenHAB2. I'm happy to help test things as you go along. Like my brother (above), I've just installed 2.0b4 this weekend.

Rob

**Comment by BobRak** [comment]
Hi Bruce and Robert:

I will be happy to upload my code to git as soon as a get the code a little more stable and a readme.md created (so you know how to configure it).  I have figured out how to get the UI to update when an external  controller is used to change a device. I still have to figure out how to restore the previous state on startup but I'll make code available to both of you before that. Also, I am developing on windows and I am using a real serial port. I want to make sure it continues to work with my usb to serial adapter. Hopefully I'll be ready to send something by mid next week.
Thanks for your interest in my work. It is nice to know someone else in the world is still using cm11a controllers.

Bob

**Comment by brucejackson** [comment]
Excellent - Thanks. 

About restoring state, have you have any luck using OpenHab's persistence.   I use mySQL for persistence so my mysql.persist file looks like:

```
Strategies` {
	every05min	: "0 0/5 * * * ?"
	every10min	: "0 0/10 * * * ?"
	every15min	: "0 0/15 * * * ?"
	every20min	: "0 0/20 * * * ?"
	every30min	: "0 0/30 * * * ?"
	everyHour	: "0 0 * * * ?"
	everyDay	: "0 0 0 * * ?"
        // If no strategy is specified for an item entry below, the default list will be used.
	default = everyChange, restoreOnStartup
  }

  Items {
     gX10* : restoreOnStartup, everyChange  // added just as an example
      gAlarm* : strategy = restoreOnStartup, everyUpdate, everyChange  //gAlarm  is a reference to a group    in the items file
    gServices_Sonos* : strategy = everyDay
 
     ndefined : strategy = restoreOnStartup, everyChange
  }`

```

So with this persistance file I would expect a item such as this to work:

``` // x10 LED lights
 Switch	Light_X10_LED_Back   "Backyard Light"	<light>	(gX10,gServices_Lights,gOutdoors)	 { cm11a="C8" }
 Switch	Light_X10_LED_Front   "Frontyard Light"	<light>	(gX10,gServices_Lights,gOutdoors)	 { cm11a="C7" }
```

**Comment by robertjackson17** [comment]
Thanks Bob,

We'll look forward to trying it out. Bruce and I both have OpenHAB2 running on Raspberry Pi boxes.

The set-up at my end has the car's HomeLink button (that usually opens garage doors) programmed using a X10 HR12A to connect with an X10 transceiver RR501. As I recall, the CM11A detects that output of the transceiver across the electrical wires. Bruce's code sees triggers a rule to turn on the house lights (Plum switches/dimmers). It seems I have to go through this because HomeLink doesn't play nicely with the rest of the world.

I'm not sure how Bruce is using X10.

Rob

**Comment by BobRak** [comment]
Hi Bruce and Robert:

I want to give up a status update on the cm11a binding.

On the plus side:
* I got a lot of the cleanup done including adding JavaDoc on all of the
classes
* I created a readme.md file so you know how to configure it.
* I was just ready to push it to git when I realized I should first build a
jar file and that is where the trouble started.

On the minus side:
* The maven build failed. with a bunch of compile errors concerning the
serial port and I couldn't figure out why.  I thought I had everything
configured correctly. Eventually I figured it out and have been able to
successfully build a jar.
* Then I thought I better test it and for the most part it seems like it is
working correctly but it never actually writes to the serial port.  I'm
still trying to figure out what the problem is. I'll keep working on it but
I think this might take a few days to figure out. The magical thing is if I
step away for a few hours or a day I have a bunch of new ideas to try.
Hoping this will happen with this problem.

I'll keep you posted.  Are either of you Java developers and have you done
any OpenHAB binding development? If so, I could push it to gitHub and you
could try an figure out what is going on, if you are interested.

Bob

**Comment by brucejackson** [comment]
If you push the code I'm happy provide another set of eyes to see if I can help. 

I am not strong in Java and my only experience with openhab bindings was modifying EngineerGreen's work for Rob.

**Comment by BobRak** [comment]
Hi Bruce and Robert:

I've pushed my work to: https://github.com/BobRak/OpenHAB-cm11a

I figured out why it wouldn't build and got that taken care of so there in
now a jar file in the target directory you can deploy.

I've also made some progress in figuring out where and why it stops reading
from the serial port. One thing I've noticed is if I start OpenHAB and
change switches through the web interface things seem to work pretty well.
Also, if you say turn a switch off in the web interface and then turn it on
using a keypad or other X10 controller you will see the web is updated.
That's the good news and is pretty cool. But, after that making changes
through the web is ineffective. I'm working at figuring out why. One thing
that seems to happen is on the next write to the interface
X10Interface.java seems to get stuck where it reads the checksum from the
interface (line 405). My next task is to figure out why that is. Also, the
code doesn't ever timeout on serial reads and therefore if it get stuck it
is just hung there. So my next tasks are: 1) figure out why it has trouble
after receiving data. 2) add some serial read timeout so it can't just hang
and never free up.  Please feel free to look into either of these. My time
will be somewhat limited the next couple of weeks because of the holidays
but I will no doubt have some time to try and make progress.

Bob

**Comment by brucejackson** [comment]
Thanks Bob.  I have it installed and running.  Enjoy the holidays.

**Comment by BobRak** [comment]
Please let me know if you have problems with it stopping working.
Especially after using a keypad or other device to change modules. I
haven;t done any testing on linux or RPi.

Thanks,

Bob

**Comment by brucejackson** [comment]
Everything looks great with the latest version of the binding.  From my perspective, I think it is ready to be submitted for inclusion in the project.

Bruce.

**Comment by big-col** [comment]
im not able to increase the logging level for this binding. can someone else try and replicate please.

**Comment by wborn** [comment]
The binding got merged with https://github.com/openhab/openhab2-addons/pull/2669.
