### ISSUE TITLE
[Milight] OH2 cannot change brightness for white bulbs

### ISSUE THREAD

**Issue by MikeJMajor** [openhab/openhab2-addons#1572]
Setting the brightness for white bulbs doesn't seem to be working.

Decreasing the brightness from 100℅ results in the bulb turning off. Increasing the brightness from 0% doesn't result in the bulb turning on (unless it's to 100%).

Looking at the code for MilightCommunication the calls to increaseBrightness/decreaseBrightness are passing -1 for the oldPercent parameter which seems to be the cause of the problem.

**Comment by davidgraeff** [comment]
@MikeJMajor: Thank you for your contribution. Could you have a look at my review notes?
Thanks.
