### ISSUE TITLE
Zwave Fibaro FGS-223

### ISSUE THREAD

**Issue by temuccio** [openhab/openhab2-addons#1574]
Hello, 
I use a fibaro FGS-223 with Openhab2 and AEON Stick Gen5.
It works fine but second channel doesn't send information about power and energy meter.
Do you know this problem?
I can help you to find a solution?
Best regards

**Comment by cdjackson** [comment]
Please can you raise this on the forum where there are more people to help you. I believe people are using this so I suspect it's a config issue. 

Http://community.openhab.org
