### ISSUE TITLE
[openhabcloud] Issue with Configuration Popup » Itemlist

### ISSUE THREAD

**Issue by Homey-GER** [openhab/openhab2-addons#1575]
Hey,
congratulations to your new cloud service! Looks great so far.

Just noticed an issue with the configuration popup:
PaperUI » Configuration » Services » openHAB Cloud

In this DropDown Menu to select your Items it shows messed up stuff at the top of the list after I selected some Items and saved them.

In plain text my config looks like this:
expose=Netatmo,Temperature,Lights,Heating

But in the dropdown menu it shows that I have selected 34 Items and in every line I see one letter.

It's somehow showing every single Character in a single line as an item.
So instead just showing 1 item "Netatmo", I see 7 items: N | e | t | a | t | m | o

![ohcloudconfig](https://cloud.githubusercontent.com/assets/1194515/21247650/73ebad34-c331-11e6-97a8-a894d3d4edee.png)

Not sure yet if this affecting the service and items in the cloud, I just signed up a few minutes ago, but I only see 1 item pushed to the myopenhab cloud for now ... Will wait a bit to see if it works anyway and it's maybe only a display issue in the popup.

Anyway, GREAT JOB!
Membership-Application-Form already prepared to support openHAB Foundation a bit :)

**Comment by kaikreuzer** [comment]
Thanks @Homey-GER!

I can confirm this issue, there is still some bug between the ESH REST API and the Paper UI - I'll make sure that gets fixed by the weekend!

**Comment by kaikreuzer** [comment]
This now works correctly in the latest snapshot distro!
It does not show "x options selected" anymore, but only "search", but this is nothing severe, I would say (@aounhaider1, do you know why this is?).
