### ISSUE TITLE
[Network] Special routine for iPhone detection

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab2-addons#1579]
Presence detection for the iPhone/iPad is quite special and a few hacky solutions have been discussed over the time.

* https://www.reddit.com/r/homeautomation/comments/3zhl2z/i_think_i_finally_figured_out_iphone_wifi
* https://community.openhab.org/t/use-networkhealth-binding-for-iphone-detection/3825/1
* https://community.openhab.org/t/working-iphone-wifi-presence-locator/5985/1
* https://community.openhab.org/t/iphone-presence-detection-with-hping3-and-arp/18171/1
* ...

The solution best working seems to be the one described [here](https://community.openhab.org/t/iphone-presence-detection-with-hping3-and-arp/18171/1), combining a special ping and an arp lookup. As iPhone detection is highly demanded and the iPhone/iPad/iWhatever will not go away any time soon, it would be nice to integrate the process in the Network Binding. What do you think?

Pinging the previous authors @mettke @davidgraeff

Could be related to: https://github.com/openhab/openhab2-addons/issues/1156

**Comment by Marty56** [comment]
Would love it!

**Comment by ThomDietrich** [comment]
@Marty56 This task is currently unassigned. If you want to give it a try...?

**Comment by hakan42** [comment]
Thinking about this and ARP scanning, I am thinking whether a dedicated ARP scanning binding would be a good idea. Care to add your ideas / opinions to the community thread?

https://community.openhab.org/t/arp-scanning-should-i-create-a-new-binding-or-add-to-the-network-binding/18514

**Comment by Marty56** [comment]
@ThomDietrich. This would clear exceed my capabilities.

**Comment by ThomDietrich** [comment]
@Marty56 maybe you could assist @hakan42 or look into #1156. Everyone starts small at some point ;)

**Comment by davidgraeff** [comment]
In my opinion this extension belongs to this addon. I'm not owning an Apple device though, and couldn't test such an extension. And I'm not sure if all Openhab supported operating systems support sending low level ARP packets. At least on linux you need special permissions and a custom implementation as the java framework does not help with this task.
