### ISSUE TITLE
Max Shuttercontact Display State

### ISSUE THREAD

**Issue by Hilzerak** [openhab/openhab2-addons#1590]
Hey guys,
i struggle for long time with the max shuttercontacts. I've a Maxcube as Gateway and Openhab2.
In Paperui they work fine.

But in other UIs i ran in errors with my config.

**Items:**

Contact OG_Bath_Window "Window is [MAP(max.map):%d]" (Window_Sensor, OG_Bed, Contact) {channel="max:shuttercontact:NEQ1207124:NEQ0846206:contact_state"}
**Sitemap**

Text item=OG_Bath_Window

**Transform**
1=offen
0=geschlossen
2=gekippt
NULL=undefiniert
CLOSED=geschlossen
OPEN=offen
-=UNKOWN

Didnt get the state shown properly, always shown "UNKOWN".

The Log indicates correct stateswitches.
> [ItemStateChangedEvent ] - max_shuttercontact_NEQ1207124_NEQ0846206_contact_state changed from CLOSED to OPEN 

What am I doing wrong? Or is it a Bug in the Binding?
Please Help!

**Comment by Homey-GER** [comment]
Here is the mistake:
[MAP(max.map):%d]

Replace %d by %s

It should look like this then:
[MAP(max.map):%s]

**Comment by Hilzerak** [comment]
Thx for reply an explanation.
Unfortunately i've tested this with both and no difference at all.
"Unknown every time".

**Comment by Homey-GER** [comment]
hmm, then I am not sure, sorry.
I can only confirm that it's working fine for me.
I've used the latest OH2-Beta4 for some weeks and now I am on the latest snapshot from some days ago.

I have installed:
binding-max - 2.0.0.SNAPSHOT
transformation-map - 0.9.0.SNAPSHOT

/items/max.items
`Contact Contact_WZ   "Balkontür [%s]"   { channel="max:shuttercontact:LEQ0039819:LEQ0167545:contact_state" }`

/sitemaps/max.sitemap
`Text item=Contact_WZ label="Wohnzimmer [MAP(max.map):%s]"`

/transform/max.map
`CLOSED=zu
OPEN=offen`

**Comment by Hilzerak** [comment]
@Homey-GER 
U ARE THE MAN!
Finally... after over 8h invest I've found the error...
Wow!

But, can anyone explain me why the hell this is the fault?!
I've removed the Item from Group Contact, restarted the Server and then it works.
The Group definition is:

> Group Contact

Is it because the Name "Contact" is defined as Itemtype?
