### ISSUE TITLE
[marytts] Why is there a separate log directory?

### ISSUE THREAD

**Issue by itn3rd77** [openhab/openhab2-addons#1597]
I don't know if this is considered a bug but I want to bring this to discussion.

In my humble opinion we should have a single log directory (sub directories when necessary) to store all log files  in one place. With installed marryTTS addon there is an extra log directory inside the userdata folder named 'log'  beside the default log directory named 'logs'. Is this intentional? I would suggest to store this log files in 'userdata/logs' or 'userdata/logs/marrytts' if possible.

Regards
Ingo

**Comment by kaikreuzer** [comment]
> I would suggest to store this log files in 'userdata/logs' or 'userdata/logs/marrytts' if possible.

I once tried to do this, but the folder is written directly from the Mary server without using the slf4j logging infrastructure, hence I failed moving the folder.

If you find a way to make it work, it would be awesome :-)

**Comment by itheiss** [comment]
As far as my research is correct the the logging is configured from 'marrytts/util/log4j.properties' inside the 'marytts-runtime-5.1-SNAPSHOT.jar'. I found a post at stackoverflow where some guy said the properties file can be overridden by putting a directory containing the properties files, with the same package structure, in the classpath, before the jar file.

But my knowledge is to limited to state this true and I am far away from having a development environment for openhab.
