### ISSUE TITLE
occured or occurred

### ISSUE THREAD

**Issue by martinvw** [openhab/openhab2-addons#1600]
In at least 11 openhab bindings and multiple parts of the org.eclipse smarthome the word occurred has been misspelled. A search in the code gives 97 occurrences of which 82 occurred in either comments or strings and should thus be easily replaced. 

If anyone likes to replace them please do so, otherwise I will most likely do it somewhere in the upcoming weeks.

Any other spelling errors which should be included in such a refactoring please add them here.

**Comment by kaikreuzer** [comment]
Feel free to create PRs where ever you find such typos! Many thanks :-)

**Comment by martinvw** [comment]
Resolved for openhab, we could also scan through eclipse smarthome but another issue should be created then
