### ISSUE TITLE
[netatmo] [OH2] Results of HTTP calls are shown on the console

### ISSUE THREAD

**Issue by hakan42** [openhab/openhab2-addons#1601]
## Expected Behavior
Debug traces should go to either to the designated log or be suppressed

## Current Behavior
The HTTP requests and responses are dumped on the system console:

    Dec 21 15:58:42 pitaya start-service.sh[12940]: Access-Control-Allow-Origin: *
    Dec 21 15:58:42 pitaya start-service.sh[12940]: OkHttp-Selected-Protocol: http/1.1
    Dec 21 15:58:42 pitaya start-service.sh[12940]: OkHttp-Sent-Millis: 1482335922633
    Dec 21 15:58:42 pitaya start-service.sh[12940]: OkHttp-Received-Millis: 1482335922834
    Dec 21 15:58:42 pitaya start-service.sh[12940]: {"body":{"devices":[{"_id":"70:ee:50:17:e0:9c","cipher_id":...

    Dec 22 12:20:11 pitaya start-service.sh[729]: {"body":{"devices":[{"_id":"XX:XX:XX:XX:XX:XX","cipher_id":"enc:16:XXXXX
    Dec 22 12:20:11 pitaya start-service.sh[729]: ,"battery_vp":5210,"battery_percent":61,"rf_status":55,"firmware":17},{"_id":"XX:XX:XX:XX:XX:XX","type":"NAModul
    Dec 22 12:20:11 pitaya start-service.sh[729]: 797132,"wifi_status":42}],"user":{"mail":"hakan@tandogan.com","administrative":{"country":"DE","reg_locale":"en-
    Dec 22 12:20:11 pitaya start-service.sh[729]: <--- END HTTP (4357-byte body)
    Dec 22 12:20:11 pitaya start-service.sh[729]: ---> HTTP GET https://api.netatmo.net/api/getstationsdata?device_id=XXXXXXXXXXX
    Dec 22 12:20:11 pitaya start-service.sh[729]: ---> END HTTP (no body)
    Dec 22 12:20:12 pitaya start-service.sh[729]: <--- HTTP 200 https://api.netatmo.net/api/getstationsdata?device_id=XXXXXXX (154ms)

You can see from the requested URLs as well from the content (which I modified slightly to suppress my own credentials) that the request go to api.netatmo.net.

If an exception is thrown, the stack trace starts with

    Dec 13 13:12:51 pitaya start-service.sh[4347]: at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:175)
    ....
    Dec 13 13:12:52 pitaya start-service.sh[4347]: at org.openhab.binding.netatmo.handler.NetatmoBridgeHandler.getStationsDataBody(NetatmoBridgeHandler.java:138)
    Dec 13 13:12:52 pitaya start-service.sh[4347]: at org.openhab.binding.netatmo.handler.station.NAMainHandler.updateReadings(NAMainHandler.java:41)
    Dec 13 13:12:52 pitaya start-service.sh[4347]: at org.openhab.binding.netatmo.handler.NetatmoDeviceHandler.updateChannels(NetatmoDeviceHandler.java:92)
    Dec 13 13:12:52 pitaya start-service.sh[4347]: at org.openhab.binding.netatmo.handler.NetatmoDeviceHandler$1.run(NetatmoDeviceHandler.java:64)
Dec 13 13:12:52 pitaya start-service.sh[4347]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

and goes straight through okhttp to make the HTTP calls.

## Possible Solution
Suppress the aforementioned if not explicitly enabled 😈 

## Steps to Reproduce (for bugs)
1. Set up a clean OH2 installation
2. Add a netatmo bridge
3. See HTTP dumps on console

## Your Environment

* Version used: OH2, Jenkins build 657, and with 660 (Karaf 4.0.8) too
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...): Oracle JDK 1.8.0_111
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...): Raspberry Pi 3 with Hypriot OS

This ticket was previously mistakenly opened in the OH1 repo ( https://github.com/openhab/openhab/issues/4919 )

**Comment by hakan42** [comment]
@watou  identified that the core issue is with okhttp library using System.println() everywhere. 

https://github.com/openhab/openhab/issues/4919#issuecomment-268793510

I would not expect them to change, though, as they are targeting Android applications as well, where they cannot rely on slf4j / log4j being available.

Perhaps we should look into some other library to do the OAUTH dance and the following HTTP requests?

**Comment by clinique** [comment]
This can be changed quite easily, just by removing line 91  in NetatmoBridgeHandler. I'll do it when I'll have the opportunity to make another PR.

**Comment by hmerk** [comment]
@clinique Did you fix this in the meantime, if so, this issue could be closed.

**Comment by clinique** [comment]
@hmerk : I'd like @hakan42 to confirm that it does not exist anymore. I do not have this behaviour on my side. It may depend upon his loglevel.

**Comment by clinique** [comment]
@lolodomo , @cweitkamp : do you face this on your systems ?

**Comment by cweitkamp** [comment]
@clinique No, I cannot see anything like that in my log files if I activate `DEBUG` or `TRACE` logging for the Netatmo binding itself. I am not familiar with logging methods for the underlying swagger API. Not sure if it is located over there.

**Comment by martinvw** [comment]
Yes sounds good
