### ISSUE TITLE
[yamahareceiver] Add additional info for Net Radio

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab2-addons#1602]
For input channel Net Radio additional information like station name and currently played song are available and e.g. shown on the receiver's display. 
It would be nice to show these information also in openHAB.

**Comment by davidgraeff** [comment]
@MHerbst: Could u have a look at the refactored plugin? https://community.openhab.org/t/yamahareceiver-binding-has-issue-with-zone-2/19731/8?u=david_graeff
Thanks,
David

**Comment by MHerbst** [comment]
@davidgraeff Unfortunately on my system ist does not work at all. See my comments in the Community.

**Comment by davidgraeff** [comment]
Should be solved with #3264

**Comment by wborn** [comment]
Closing this since #3264 got merged.
