### ISSUE TITLE
Rule problem: The name 'C3' cannot be resolved to an item or type

### ISSUE THREAD

**Issue by johane73** [openhab/openhab2-addons#1610]
Hi,

I've got an interesting Rules error.

I've got two nexa switches, C1 & C3 (yes there is a C2 as well) and a remote that came with the pack.

I have rules set up so that when I press 1 - OFF on the remote  the C3 Switch is turned OFF.

The rule is:
`rule "Received Remote Switch 1 OFF"
when
        Item Remote1.1 received update OFF
then
        logInfo("Remote 1.1", "OFF")
        sendCommand(C3, OFF)
end`

This works fine.

But when I set up the rule to turn C1 & C3 off it fails:
`
rule "Remote 1.0 Update"
when
        Item Remote1_0 received update
then
        logInfo("Remote 1", "All Off")
        sendCommand(C3, OFF)
        sendCommand(C1, OFF)
end
`

The error log says:
Rule 'Remote 1.0 Update': An error occured during the script execution: The name 'C3' cannot be resolved to an item or type.

Any ideas?
(For some reason the linefeeds in my code sample doesnt show)

I've got Openhab2 snapshot installed from the other day.

**Comment by watou** [comment]
Please open a new topic at https://community.openhab.org where this can be discussed, thanks!
