### ISSUE TITLE
[exec] Pipe symbol in command line unsupported

### ISSUE THREAD

**Issue by metbril** [openhab/openhab2-addons#1614]
I try to create a thing that monitors my Internet connection by pinging Google. Eventually it should populate a Switch item.

This thing provides output
```
Thing exec:command:ping_google [command="ping -c 1 8.8.8.8", interval=30, timeout=5, autorun=false]
```

This thing raises an error on the ping command:

```
Thing exec:command:ping_google [command="ping -c 1 8.8.8.8 | grep 'packets transmitted'", interval=30, timeout=5, autorun=false]
```
It looks like the pipe symbol is not supported properly.

This is the item:
```
String Test_Ping "Ping [%s]" <text> (Network)  { channel="exec:command:ping_google:output" }
```

**Comment by kgoderis** [comment]
@rtvb | is something internally to the shell (ex. bash) you are using, the exec binding is about executing a process. More in depth info can be found on:

http://alvinalexander.com/java/java-exec-system-command-pipeline-pipe
http://stackoverflow.com/questions/5928225/how-to-make-pipes-work-with-runtime-exec or http://stackoverflow.com/questions/7226538/how-to-use-pipe-symbol-through-exec-in-java

**Comment by rtvb** [comment]
So I assume something like 

```
Thing exec:command:ping_google [command="/bin/sh ping -c 1 8.8.8.8 | grep 'packets transmitted'", interval=30, timeout=5, autorun=false]
```

should work?
