### ISSUE TITLE
[RFXCOM] TEMPERATURE_HUMIDITY_BAROMETRIC missing

### ISSUE THREAD

**Issue by egila** [openhab/openhab2-addons#1623]
The TEMPERATURE_HUMIDITY_BAROMETRIC message has not yet been implemented in the rfxcom 2.0 binding. It was present in the 1.x version of the binding.

**Comment by martinvw** [comment]
I'm busy with it now, so I suppose I can provide you with a test-jar tonight.

Do you know how to install that?

**Comment by martinvw** [comment]
Hereby a version including support for TEMPERATURE_HUMIDITY_BAROMETRIC messages, please test and report any findings!

[org.openhab.binding.rfxcom-2.1.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab2-addons/files/758739/org.openhab.binding.rfxcom-2.1.0-SNAPSHOT.jar.zip)
