### ISSUE TITLE
ASTRO Offset error build 681

### ISSUE THREAD

**Issue by Royw51** [openhab/openhab2-addons#1624]
When attempting to set an event off set for Range event "astro:sun:local:set#event"  this is posted in the log:
[INFO ] [ome.io.rest.core.thing.ThingResource] - Received HTTP PUT request for update at 'things/astro:sun:local' for an unmanaged thing 'astro:sun:local'.

and a "pop up" box stating "ERROR: 409 - Conflict" appears.  This occurs on all Range events, sun and moon, that I tried.

**Comment by kaikreuzer** [comment]
You cannot change a Thing that is defined in a file. Create it through the Paper UI instead and it will work.
