### ISSUE TITLE
[RFXCOM] Improve README docs 

### ISSUE THREAD

**Issue by metbril** [openhab/openhab2-addons#1626]
The [documentation](https://raw.githubusercontent.com/openhab/openhab2-addons/master/addons/binding/org.openhab.binding.rfxcom/README.md) desperately needs improvement:

- [ ] working example(s) for different types of devices
- [ ] better documentation of available subtypes

Feel free to add other improvements.

**Comment by martinvw** [comment]
Can't we just migrate the wiki of the rfxcom 1.x binding that one looked (more) complete.

**Comment by martinvw** [comment]
@metbril I spent some time on README, can you take a look at it :-)

Any suggestions, please let me know, I plan to create a PR for it in this weekend:

https://github.com/martinvw/openhab2-addons/blob/feature/rfxcom-readme/addons/binding/org.openhab.binding.rfxcom/README.md

**Comment by martinvw** [comment]
I already created a WIP PR

**Comment by metbril** [comment]
Great work. This is a big improvement.

BTW @martinvw, I noticed a change to the code, not README in your PR. Is that on purpose or by accident?

**Comment by martinvw** [comment]
It was an incorrect reference to a non-existing class, its also documentation ;-)

**Comment by martinvw** [comment]
@metbril any specific things you still miss?
