### ISSUE TITLE
ZWAVE:  false  / good usercode not reported

### ISSUE THREAD

**Issue by bricolo100** [openhab/openhab2-addons#1636]
When using a device that utilizes USER_CODE, this user_code is not:
- associated to Channel in case of success
- reported into the log in case this one is not registered as valid.

In the first case, it is impossible to associate/store the action with a person (that owns the code), this does not help for tracability.
In the second case, RFID tags cannot be set as valid input because their stored ID is not known (can be only retrieved by the RFID tag reader).
- So the request is to associate to the Alarm notification a channel/thing that stores the user_code (or its index in the list). A lot better would be to associate a name to each user_code and that this name is copied into the relevant channel/thing upon status modification.
- Then second request is to  log the user_code (false a minima) into the INFO log level, so that they can be latter acknoledged in the list a valid codes.

 Happy new year

**Comment by cdjackson** [comment]
I don't really understand what you're asking for.

Please discuss on the forum first (also, this issues list is not for zwave, so if we do open an issue for this, please open on the zwave list).

Thans
