### ISSUE TITLE
[pioneeravr] Add setting and querying listening modes functionality

### ISSUE THREAD

**Issue by Spilota** [openhab/openhab2-addons#1653]
<a alt="bounty" href="https://www.bountysource.com/issues/40590803"><img src="https://api.bountysource.com/badge/issue?issue_id=40590803"></a>

It would be useful (to me) to add a bit of functionality for setting / querying listening modes:

Set Listening Mode:  [****SR<CR>]
Request Listening Mode: [?L<CR>]
Request Resolution Status: [?VTC<CR>]

Being able to send custom commands and be given the ACSII response would probably add this functionality for all use cases.

**Comment by scurb** [comment]
Would be really good!

**Comment by Celaeno1** [comment]
OK for me, too. 
Please implement "Request Listening Mode, Setting" = [?S], too. Thanks!

**Comment by Celaeno1** [comment]
@Stratehm Maybe something for you?

**Comment by joeduck** [comment]
Listening Mode would be great!
Could we donate for the Feature and your great work?

Greetings

**Comment by martinvw** [comment]
I saw bountysource being used:

https://www.bountysource.com/issues/40590803-pioneeravr-feature-request-pioneeravr

**Comment by kaikreuzer** [comment]
@martinvw With a bounty of $0...? A bit weird...

**Comment by martinvw** [comment]
I responded to:

> Could we donate for the Feature and your great work?

I meant I saw bountysource being used on a few other issues

**Comment by kaikreuzer** [comment]
Ah :-)

**Comment by joeduck** [comment]
Donated :)

**Comment by martinvw** [comment]
@Stratehm you should be able claim this if you start it and retrieve it once finalised.

**Comment by gersilex** [comment]
I'm starting with the implementation of the Listening Mode (Setting) and Playing Listening Mode (Query) right now.

**Comment by gersilex** [comment]
@Spilota @Celaeno1  `****SR`, `?S` and `?L` are implemented in #5515 

I have not implemented `?VTC` as this is not a part of the listening mode feature set. If this is still relevant to you, I might give it a shot, too, if you could create a separate issue for this.

**Comment by Celaeno1** [comment]
@gersilex I don't need "Request Resolution Status: [?VTC]".
