### ISSUE TITLE
Openhab2 KNX Binding

### ISSUE THREAD

**Issue by B0rner** [openhab/openhab2-addons#1658]
Hi,

sorry, I'm not sure, if this is the right place to place my question, but I didn't find an alternative.
I'm looking for an KNX Binding for openhab2 and found the following tree:
https://github.com/kgoderis/openhab2/tree/knx-refactor

So my question is: is there a way to get the current state of the knx addon without pulling the branch from @kgoderis ?  I would like to implement the current KNX2 addon state into an existing openhab2 environment.

Thank you, B0rner

**Comment by kaikreuzer** [comment]
Hi @B0rner, the right place for questions is https://community.openhab.org/.
KNX 2 binding is still under development, but you can safely use the KNX 1 binding, which is included in the openHAB distro.
