### ISSUE TITLE
CometVisu PHP support add-on: configuration saving error caused by fix coded transfer limit inside jetty server

### ISSUE THREAD

**Issue by cybergreen2** [openhab/openhab2-addons#1666]
**Issue:**
During the creation of my CometVisu visualisation I was running in an saving error of my CometVisu configuration by using the php-editor of CometVisu. The error "configuration could not be saved, serve responded with 'error' / 'ServerError' will occur, if the fix implemented transmiting size value `maxFormContentSize = 200000` in Request.java of the jetty-server is overrun.

**Environment:**
openhab 2.0.0.b4 und openhab 2.0.0.b5 (in both the error occurs)
ui-cometvisu - 2.0.0.b5
ui-cometvisu-php - 2.0.0.b5

**running workaround:**
`        <Call name="setAttribute">
                <Arg>org.eclipse.jetty.server.Request.maxFormContentSize</Arg>
                <Arg>300000</Arg>
        </Call>` in jetty.xml and restart of openhab2

**Comment by peuter** [comment]
@kaikreuzer Is there a general setting that can be used in a .cfg file to modify this settings? I guess I can add one for the cometvisu-binding, but maybe there could be a need for a generic one for all servlets.

**Comment by kaikreuzer** [comment]
You could consider doing a PR against https://github.com/openhab/openhab-distro/blob/master/distributions/openhab/src/main/resources/runtime/etc/jetty.xml

**Comment by peuter** [comment]
@cybergreen2 As you have a working solution: Would you mind to create a pull request from it?

**Comment by cybergreen2** [comment]
A PR was created by me.

**Comment by peuter** [comment]
As your PR has been merged, I guess we can close thise issue now,
