### ISSUE TITLE
[Homematic] Wrong language used for texts on page Control in Paper UI

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab2-addons#1668]
I know that the Homematic add-on uses its own technique to support different languages. While this works perfect for texts in *Inbox*, *Things* and *Items* it does not work correctly on the *Control* page. Here always the english texts are used, e.g.
![image](https://cloud.githubusercontent.com/assets/616792/21744398/f5187500-d514-11e6-8cf6-b656394a95c3.png)

For add-ons using the standard technique for language support the correct german texts are displayed (example taken from the Kodi add-on):
![image](https://cloud.githubusercontent.com/assets/616792/21744405/2a08f320-d515-11e6-9263-561536eed128.png)

BTW: the language currently is taken from the browser's language and transferred in the REST request as accept language and then used in class `org.eclipse.smarthome.io.rest.LocaleUtil` (see also https://github.com/eclipse/smarthome/issues/2589)

Tested on Windows 10 (German, Chrome Browser German, locale set to "de") and build 699.

**Comment by MHerbst** [comment]
The language definitions are loaded when class MetadataUtils is initialized. This happens when the binding is loaded. The method loadBundle only loads the properties file for the default locale. In the classes that are implementing e.g. the ConfigDescriptionProvider interface the locales are ignored (as an example see method: HomematicConfigDescriptionProviderImpl#getConfigDescription).

To solve this problem I see two possible options:
1. In class MetadataUtils load all available language definitions and store them per locale. When asked for a description you could return the correct text.
2. In MetadataUtils load the text of the default locale. If a method is asked for texts of a different locale replace the loaded definitions by the texts of the requested locale.

I would prefer the second options because in most situation the locale set in Paper UI will be the same as the default locale. 
What do you think, @gerrieg ?

**Comment by gerrieg** [comment]
Signal Strength and Low Battery are OH default system channels. Currently it's not possible to do a translation for them.

**Comment by kaikreuzer** [comment]
It is possible to add translations, but not in the binding, but in the core framework - I have created https://github.com/eclipse/smarthome/issues/3623 for that! @gerrieg Feel free to create an according PR yourself (hint: I guess the translations would have to go into the `org.eclipse.smarthome.core.thing` bundle).

**Comment by MHerbst** [comment]
Maybe Signal Strength and Low Battery were a bad example :-). But the problem exists with nearly all texts that are provided by the binding. I have seen several places where the binding uses `Locale.getDefault()`. This is the default locale set by the Java VM. If the locale set in Paper UI is different from the default locale you can see that this current locale is ignored by the Homematic binding.

**Comment by MHerbst** [comment]
Retestes it with OH 2.2. The system channel names are now displayed correctly.

But the Homematic-specific channel names are always displayed in english (tested on Windows 10 German = Java VM default locale; no locale settings in Paper UI).
This leads to a "language mixture":
Thing desdriptions are displayed on German:
![image](https://user-images.githubusercontent.com/616792/34358904-fcd9811c-ea53-11e7-8285-4d1987ca3951.png)

Channel names always appear in English:
![image](https://user-images.githubusercontent.com/616792/34358934-3b6e4bc4-ea54-11e7-8218-1fd072cd5147.png)

But [file](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.homematic/src/main/resources/homematic/generated-descriptions_de.properties) `generated-descriptions_de.properties`  seems to contain all necessary translations.

**Comment by mdicke2s** [comment]
This issue was moved to eclipse/smarthome#5778
