### ISSUE TITLE
[Homematic] No “CONTROL_MODE” data from HM-TC-IT-WM-W-EU

### ISSUE THREAD

**Issue by codefalk** [openhab/openhab2-addons#1669]
I do run OH2 beta5 Online version and do not get any data from 
homematic:HM-TC-IT-WM-W-EU:76bxxxxx:MExxxxx:2#CONTROL_MODE (Raumthermostat).
Log does not show any status changes.

I do get CONTROL_MODE changes for HM-CC-RT-DN (Heizkörperthermostat) though. Right now my workaround is to link HM-CC-RT-DN and HM-TC-IT-WM-W-EU directly and get the CONTROL_MODE change from HM-CC-RT-DN.

**Comment by qrioniclabs** [comment]
I can confirm this issue. Occasionally I get the correct value (like 'MANU_MODE'), but most of the time it is just '-'. Device is a HM-CC-RT-DN, Bridge is run via RaspberryMatic on a PI.

Item is configured like this:
`Number i_Heating_ControlMode  "Akt. Modus: [%s]" <heating> (g_Schlafzimmer) {channel="homematic:HM-CC-RT-DN:*****************:4#CONTROL_MODE"}`

openhab2 v0.9.0.201701091847

**Comment by KlausMu** [comment]
You have to define the Item as "String". The mapping changed in OH2, so you can't map any longer an enum to Number.
See https://github.com/openhab/openhab2-addons/issues/1558
Also change your rules, if you use Numbers for the CONTROL_MODE state there.

**Comment by codefalk** [comment]
KlausMu, thanks!
This solved the issue for me.

**Comment by gorzan14** [comment]
For me  “CONTROL_MODE” from HM-TC-IT-WM-W-EU does not work even after changing Item from Number to String. For HM-CC-RT-DN it works.
