### ISSUE TITLE
[avmfritz] Support for AVMDECT210

### ISSUE THREAD

**Issue by jrubbel** [openhab/openhab2-addons#1676]
Gents,

I recently bought the new FritzDECT 210 device (https://avm.de/produkte/fritzdect/fritzdect-210/1) which is basically a DECT200 device, but outdoor-ready.

As this device is not discovered by PaperUI I tried to add it manually as a DECT200 thing in PaperUI by providing the appropriate AIN. Unfortunatly the thing remains in the state INITIALIZING.

My other device is a DECT200 which works like a charm.

Any help on this?

Many thanks
Jesko

**Comment by jrubbel** [comment]
After increasing the loglevel for the avmfritz binding to DEBUG I can find the following entry in the log file:

2017-01-10 18:37:54.762 [DEBUG] [ternal.discovery.AvmDiscoveryService] - discovered unsupported device with id 116570019138

Besides waiting for an updated avmbinding - is there a workaround e.g. by adding the DECT210 device to some kind of config file?

Many thanks
Jesko

**Comment by jrubbel** [comment]
Awesome - when when this me merged back? I am using openhabian with openHAB 2.0.0~20170103034422 (Build #692) and want to intergrate the new addon asap....
Many thanks
Jesko

**Comment by kaikreuzer** [comment]
Just merged it - should be contained in tomorrows snapshot.

**Comment by jrubbel** [comment]
Cool - I just upgraded my openhabian with sudo openhabian-config - I am now on the latest build: .openHAB 2.0.0~20170103034422 (Build #717). Unfortunatly the DECT210 is still not discoverd - it looks like Build #717 does not include this change yet - i just checked https://openhab.ci.cloudbees.com/job/openHAB-Distribution/lastBuild/ which states: 

Modul-Builds
AVM FRITZ! Binding (übersprungen)

**Comment by kaikreuzer** [comment]
>  it looks like Build #717 does not include this change yet

Correct, because it is from January 12. Next (successful) one will contain it.
