### ISSUE TITLE
[chromecast] Expose Online / Offline as well as whats currently playing

### ISSUE THREAD

**Issue by chriscolden** [openhab/openhab2-addons#1677]
Would it be possible to add functionality to grab the status of the chromecast which can then be used to dynamically update a sitemap, ie, if its offline it's hidden.

Also there are no methods to get any information about whats playing.

**Comment by holmes** [comment]
I'll take this on. Looking at exposing the metadata in https://developers.google.com/cast/docs/reference/chrome/chrome.cast.media.GenericMediaMetadata

**Comment by holmes** [comment]
PR: https://github.com/openhab/openhab2-addons/pull/2097
