### ISSUE TITLE
[voice-mactts] Crackling sound before each say command output on Mac OS TTS

### ISSUE THREAD

**Issue by andreashil** [openhab/openhab2-addons#1680]
In Build 703 for each say command a noticeable crackling sound is played on a Mac Mini before saying the text over the speakers. This was not the case in previously installed version 426. This is reproducible each time it is used.

**Comment by andreashil** [comment]
Not reproducible in Build 806 any more.

**Comment by wborn** [comment]
Please open an issue in the Eclipse Smarthome [issue tracker](https://github.com/eclipse/smarthome/issues) when this is still an issue.
