### ISSUE TITLE
[avmfritz] add support for Comet DECT

### ISSUE THREAD

**Issue by LukaNoah** [openhab/openhab2-addons#1687]
Can you please add the support for the Comet DECT in the binding?

[https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/AHA-HTTP-Interface.pdf](url)

**Comment by LukaNoah** [comment]
<devicelist version="1">
	<device identifier="xxxxxx yyyyyy" id="16" functionbitmask="2944" fwversion="03.83" manufacturer="AVM" productname="FRITZ!DECT 200">
		<present>1</present>
		<name>myDECT200</name>
		<switch>
			<state>1</state>
			<mode>manuell</mode>
			<lock>0</lock>
			<devicelock>0</devicelock>
		</switch>
		<powermeter>
			<power>155920</power>
			<energy>158158</energy>
		</powermeter>
		<temperature>
			<celsius>210</celsius>
			<offset>-10</offset>
		</temperature>
	</device>
	<device identifier="aaaaaa bbbbbb" id="17" functionbitmask="320" fwversion="03.50" manufacturer="AVM" productname="Comet DECT">
		<present>1</present>
		<name>myComet</name>
		<temperature>
			<celsius>220</celsius>
			<offset>-10</offset>
		</temperature>
		<hkr>
			<tist>44</tist>
			<tsoll>42</tsoll>
			<absenk>28</absenk>
			<komfort>42</komfort>
			<lock>0</lock>
			<devicelock>0</devicelock>
			<errorcode>0</errorcode>
			<batterylow>0</batterylow>
			<nextchange>
				<endperiod>1484341200</endperiod>
				<tchange>28</tchange>
			</nextchange>
		</hkr>
	</device>
</devicelist>

**Comment by cweitkamp** [comment]
Hey there, I ready to look into this. Problem is, I have no Comet Dect device for testing. Maybe I can build a virtual AHA HTTP interface which will deliver exactly your devicelist-xml. But be patient. I think I need two weeks or more.

**Comment by LukaNoah** [comment]
Thank you very much. Great to hear this. I would help, so I can ;)
Please don't forget the set <sethkrtsoll>command.

**Comment by cweitkamp** [comment]
Oh, no. I don't forget that command. That is the interesting part and follows in step 2. At the moment I'm planning to implement four read-only channels for "tist", "komfort", "absenk" and "battery_low" and one r/w channel for "tsoll".

If you like you are welcome to checkout my branch, build it and exchange the .jar file of the binding in your environment to test the current work.

**Comment by LukaNoah** [comment]
Thank you very much.
Where can I find a howto, to make this?
Where can I find the jar-file in my openhab-installation?

**Comment by cweitkamp** [comment]
You can find a tutorial [here](http://docs.openhab.org/developers/development/ide.html).

For the second question I need to know which setup you are using. Linux? Raspberry Pi? Windows? In general you can place your own addon files in the /usr/share/openhab2/addon/ folder (on linux based setups). I suggest to uninstall the old avmfritz binding first.

I attached a build of my current branch ([.jar file](https://github.com/openhab/openhab2-addons/files/713401/org.openhab.binding.avmfritz-2.0.0_20170118-SNAPSHOT.zip)). It only supports automatically discovering your Comet DECT device and read the "temperature" channel.

demo.items
```
Number COMETDECTTemperature "Actual measured temperature [%.1f °C]" { channel="avmfritz:Comet_DECT:1:aaaaaabbbbbb:temperature" }
```

demo.sitemap:
```
sitemap demo label="Main Menu"
{
	Frame "Comet DECT heating thermostat" {
		Text item=COMETDECTTemperature icon="temperature"
	}
}
```

I am eager to hear feedback.

**Comment by LukaNoah** [comment]
I'm using openHAB on an raspberry. Installed with apt-get.

It works :D
![image](https://cloud.githubusercontent.com/assets/16850444/22077820/106172a4-ddb6-11e6-9257-e183e0936315.png)

**Comment by LukaNoah** [comment]
I hade eclipse ;(
Can you please post your actual builds ?

**Comment by cweitkamp** [comment]
My github fork is [Link](https://github.com/cweitkamp/openhab2-addons/tree/AVMFritzComet) up-to-date. Feel free to clone or download it.

**Comment by cweitkamp** [comment]
@LukaNoah any results with your testings?

If not, I like to provide you my newest build ([.jar file](https://github.com/openhab/openhab2-addons/files/721873/org.openhab.binding.avmfritz-2.0.0_20170122-SNAPSHOT.zip)). This version supports reading temperature, reading battery level and setting temperature. Would you like to test it?

demo.items:

```
Number COMETDECTActualTemp "Actual measured temperature [%.1f °C]" { channel="avmfritz:Comet_DECT:1:aaaaaabbbbbb:actual_temp" }
Number COMETDECTSetTemp "Thermostat temperature setpoint [%.1f °C]" { channel="avmfritz:Comet_DECT:1:aaaaaabbbbbb:set_temp" }
Switch COMETDECTBattery "Battery low" { channel="avmfritz:Comet_DECT:1:aaaaaabbbbbb:battery_low" }
```

demo.sitemap:

```
sitemap demo label="Main Menu"
{
	Frame "Comet DECT heating thermostat" {
		Text item=COMETDECTActualTemp icon="temperature"
		Setpoint item=COMETDECTSetTemp minValue=8.0 maxValue=28.0 step=0.5 icon="temperature"
		Switch item=COMETDECTBattery icon="battery"
	}
}
```
I am eager to hear feedback.

**Comment by LukaNoah** [comment]
It does'nt work.
In paperUI the new values are not present. I maked a avm.items-file with these two values and added these to my sitemap. The setpoint-value are not changing to the value from the fb. Changed values of setpoint was not send to fb.

**Comment by cweitkamp** [comment]
Thanks for testing.

Some questions:
Did you remove your Comet DECT thing in Paper UI and add it again after replacing the binding? If not, give it a try. If that doesn't help and the channels are not visible in Paper UI then remove all Comet DECT things and items in Paper UI and your *.things and *.items files, restart openhab2.service and try it again.

Do you know how the fb is reacting, after sending an "ON" or "OFF" over the interface? Does ist set the mentioned temperatures (7.5 for OFF, 28.5 for ON)?
Currently I suggest not to expand the range of allowed temperatures from 7.5 to 28.5 because in the documentation of the interface the range is given from 8.0 to 28.0. I suggest to implement sending an ON or OFF to the set_temp channel. This will send either 253 or 254 to the fb. What do you mean?

I think I found the problem why the values are not present and will not update after change. I work out a solution for that.

**Comment by LukaNoah** [comment]
I has removed all. And add again. Nothing. 
On / Off where ok.

**Comment by cweitkamp** [comment]
New build [.jar file](https://github.com/openhab/openhab2-addons/files/727064/org.openhab.binding.avmfritz-2.0.0_20170124-SNAPSHOT.zip) (untested). Should fix the "not present value" bug.

Could you try to implement an additional Switch item for "avmfritz:Comet_DECT:1:aaaaaabbbbbb:set_temp" channel to send ON/OFF commands?

Restart openhab2.service after replacing the binding like suggested.

**Comment by LukaNoah** [comment]
I Do,  but I'm not @home. Friday I Can Do this, sorry ;)

**Comment by cweitkamp** [comment]
New build ([.jar file](https://github.com/openhab/openhab2-addons/files/731915/org.openhab.binding.avmfritz-2.0.0_20170126-SNAPSHOT.zip)).

**Comment by LukaNoah** [comment]
Hi,
with the latest jar:
- I have 4 values at paperUI (setpoint, battery, 2x actual_temperature)
- send on to setpoint the fb receive on ("AUS" send off)
- send off to setpoint the fb receive off ("BOOST" send on)
- send setpoints between 8 and 28, the fb receive it
- any changes at the setpoint in fb don't transmit to oh2

great job ;)
thank you very much
![image](https://cloud.githubusercontent.com/assets/16850444/22346455/6ea498b0-e404-11e6-8f6d-dcdfe974c796.png)

**Comment by cweitkamp** [comment]
Hi,
you're welcome. Sounds good so far.

Currently I'm working on the last problem and do some refactoring of the code. Maybe I upload an new version later this evening.

The eco and comfort temperatures are defined as readonly values in the AHA interface. So the only option I can offer is to create readonly channels for them in the avmfritz binding.

**Comment by LukaNoah** [comment]
Hi, 
the readonly for oh2. I would see the actual setpoints for the 2 Modus to Set to them and Set the mode in oh2.
thx

**Comment by cweitkamp** [comment]
Hi,
check this out ([.jar file](https://github.com/openhab/openhab2-addons/files/740212/org.openhab.binding.avmfritz-2.0.0_20170130-SNAPSHOT.zip))

Problem solved changing the values in fb should change them in oh2, too. Added channels "eco_temp" and "comfort_temp".

**Comment by LukaNoah** [comment]
on first start with new binding I got this

`2017-01-30 21:52:17.862 [ERROR] [.binding.avmfritz.handler.BoxHandler] - 
java.lang.NullPointerException
	at org.openhab.binding.avmfritz.handler.BoxHandler.updateThingFromDevice(BoxHandler.java:189)[10:org.openhab.binding.avmfritz:2.0.0.201701302032]
	at org.openhab.binding.avmfritz.handler.BoxHandler.addDeviceList(BoxHandler.java:132)[10:org.openhab.binding.avmfritz:2.0.0.201701302032]
	at org.openhab.binding.avmfritz.internal.hardware.callbacks.FritzAhaUpdateXmlCallback.execute(FritzAhaUpdateXmlCallback.java:70)[10:org.openhab.binding.avmfritz:2.0.0.201701302032]
	at org.openhab.binding.avmfritz.internal.hardware.FritzahaContentExchange.onComplete(FritzahaContentExchange.java:71)[10:org.openhab.binding.avmfritz:2.0.0.201701302032]
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193)[71:org.eclipse.jetty.client:9.2.19.v20160908]
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185)[71:org.eclipse.jetty.client:9.2.19.v20160908]
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:453)[71:org.eclipse.jetty.client:9.2.19.v20160908]
	at org.eclipse.jetty.client.HttpReceiver.responseSuccess(HttpReceiver.java:400)[71:org.eclipse.jetty.client:9.2.19.v20160908]
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.messageComplete(HttpReceiverOverHTTP.java:266)[71:org.eclipse.jetty.client:9.2.19.v20160908]
	at org.eclipse.jetty.http.HttpParser.parseContent(HttpParser.java:1487)[73:org.eclipse.jetty.http:9.2.19.v20160908]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1245)[73:org.eclipse.jetty.http:9.2.19.v20160908]
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:156)[71:org.eclipse.jetty.client:9.2.19.v20160908]
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:117)[71:org.eclipse.jetty.client:9.2.19.v20160908]
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:69)[71:org.eclipse.jetty.client:9.2.19.v20160908]
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:89)[71:org.eclipse.jetty.client:9.2.19.v20160908]
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:123)[71:org.eclipse.jetty.client:9.2.19.v20160908]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)[74:org.eclipse.jetty.io:9.2.19.v20160908]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)[85:org.eclipse.jetty.util:9.2.19.v20160908]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)[85:org.eclipse.jetty.util:9.2.19.v20160908]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
`
After remove thing and add new, the message where gone.

Changes in fb ui of setpoint where transmitt to oh2 *hurra*
great job, thanks a lot :D

![image](https://cloud.githubusercontent.com/assets/16850444/22441475/d2d633e4-e737-11e6-9733-0d86f81fc88f.png)

**Comment by cweitkamp** [comment]
You got that NPE because your existing thing didn't have the new "eco_temp" channel. After replacing the thing everything works fine. I think it will not happen again in the future.

Which temperature values do you expect for the "set_temp" channel after sending an "ON" or "OFF" over the interface (7.5 for OFF, 28.5 for ON)? That will be easy.

The screenshot shows two channels for the Actual Temperature which are connected to different parameters of the interface. Let's have a look at your xml-response in the second post. There is one tag <temperature> for the Comet DECT device. This tag is connected to the first channel "temperature" (similar to the Fritz!DECT 200 device). The other tag <tist> within the <hkr> tag is connected to the second channel "actual_temp" (only provided by heating thermostats). I assume that both channels show the same value, but they are handled different in the binding.

**Comment by LukaNoah** [comment]
Thanks for the explanations.
8 and 28 are in the range of the control. I think 5 and 30 would be better because they are not in the normal range. If I change with the buttons the setpoint of 30 down, then comes as the first 28 and that would be correct. With 5 the same.

**Comment by cweitkamp** [comment]
Last build before creating pull request ([.jar file](https://github.com/openhab/openhab2-addons/files/744653/org.openhab.binding.avmfritz-2.0.0_20170201-SNAPSHOT.zip)). 

Temperature of "set_temp" channel will be set to (6.0 for OFF, 30.0 for ON) after sending an "ON" or "OFF" over the fb interface.

Thanks for testing. Great job, too.

**Comment by LukaNoah** [comment]
can you please add this 2 readonly values (endperid and tchange)?
<nextchange> <endperiod>1484341200</endperiod> <tchange>28</tchange> </nextchange>

**Comment by LukaNoah** [comment]
I have tested the new jar.

Set Setpoint at fb to "an" - oh receive "ON", setpoint 30°C, after next refresh (?) setpoint in oh2 goes to 127. The same by "aus", setpoint going to 6, after next refresh(?) setpoint in oh2 goes to 126.5.

**Comment by cweitkamp** [comment]
Hi,

can you please explain which purpose the two new values "endperiod" and "tchange" fulfill? I don't find anything in the documentation of AVM. I need those information for understanding and of course for the binding documentation. Should "endperiod" represent a DateTime type and "tchange" a Number type? Both readonly?

I cannot explain the observed behavior. Maybe it is the behavior of the fb itself. But what I can tell you is that - stupid as I am - I implemented the ON/OFF specification mentioned in my last post for the actual_temp channel NOT like described for the set_temp channel. Now I switched it and it should handle the values correct ([.jar file](https://github.com/openhab/openhab2-addons/files/748906/org.openhab.binding.avmfritz-2.1.0_20170202-SNAPSHOT.zip)).

**Comment by LukaNoah** [comment]
Thanks ;) 
endperiod will be the next switch from eco to comfort,  or comfort to eco. It will be DateTime. tchange will be the next setpoint, which where to set at endperiod. 
endperiod = end of the actual heating-cycle (eco or comfort) 
tchange = next setpoint, after the actual heating-cycle

The new jar I try tomorrow.

**Comment by LukaNoah** [comment]
with the new jar

The same as with the previous version.
`
2017-02-03 18:31:41.072 [INFO ] [.eclipse.smarthome.model.script.AVMT] - SetPoint change; ON, received 127
2017-02-03 18:31:41.094 [INFO ] [.eclipse.smarthome.model.script.AVMT] - SetPoint change; ON, received 30
2017-02-03 18:31:41.125 [INFO ] [.eclipse.smarthome.model.script.AVMT] - SetPoint change; ON, received 30
2017-02-03 18:31:55.995 [INFO ] [.eclipse.smarthome.model.script.AVMT] - SetPoint change; ON, received 127
2017-02-03 18:31:56.006 [INFO ] [.eclipse.smarthome.model.script.AVMT] - SetPoint change; ON, received 30
2017-02-03 18:31:56.025 [INFO ] [.eclipse.smarthome.model.script.AVMT] - SetPoint change; ON, received 30
`
setpoint off, the same
`2017-02-03 18:33:26.701 [INFO ] [g.eclipse.smarthome.model.script.AVM] - Noah - Heizung aus
2017-02-03 18:33:26.723 [INFO ] [.eclipse.smarthome.model.script.AVMT] - SetPoint change; OFF, received 6
2017-02-03 18:33:26.750 [INFO ] [.eclipse.smarthome.model.script.AVMT] - SetPoint change; OFF, received 6
2017-02-03 18:33:28.099 [INFO ] [g.eclipse.smarthome.model.script.PIL] - Garage-Temperatur-Update :4.0
2017-02-03 18:33:41.644 [INFO ] [.eclipse.smarthome.model.script.AVMT] - SetPoint change; OFF, received 126.5
2017-02-03 18:33:41.656 [INFO ] [.eclipse.smarthome.model.script.AVMT] - SetPoint change; OFF, received 6
2017-02-03 18:33:41.712 [INFO ] [.eclipse.smarthome.model.script.AVMT] - SetPoint change; OFF, received 6
2017-02-03 18:33:56.660 [INFO ] [.eclipse.smarthome.model.script.AVMT] - SetPoint change; OFF, received 126.5
2017-02-03 18:33:56.668 [INFO ] [.eclipse.smarthome.model.script.AVMT] - SetPoint change; OFF, received 6
2017-02-03 18:33:56.706 [INFO ] [.eclipse.smarthome.model.script.AVMT] - SetPoint change; OFF, received 6
`

In the above xml are 3 other parameters hidden:
- lock : binary :  online?
- devicelock : binary : keylock
- errorcode : Number : Errorcode of heating thermostat

Do you see a chance to implement this too?

**Comment by cweitkamp** [comment]
Nice to hear.

I think it is no problem to implement one channel for every information provided by the AHA interface. The Fritz!DECT 200 and 210 devices both provide more parameters, too (e.g. mode lock, devicelock). I think about implementing them in the near future. I am also interested in implementing the group features of the fb for this binding.

Maybe we should move our conversation and testing to the community forum. This feature (issue) is probaly ready to deploy. What do you think?

**Comment by LukaNoah** [comment]
Yes , it is. 
Let's do it.
Thx :) 
Should I close?

**Comment by cweitkamp** [comment]
Why not.

**Comment by LukaNoah** [comment]
Ok,  closed
