### ISSUE TITLE
[Yamaha Binding] Zone2 controls have effect on Main zone

### ISSUE THREAD

**Issue by HolgerL25** [openhab/openhab2-addons#1701]
Hi,

I am running OH2 with the Yamahareceiver Binding 2.0.0.b5. with a Yamaha RX-V1071
Everything works for the Main Zone.
If I select any control on the Zone2, it controls the Main zone and not Zone2.
This seems to be a bug in the binding.
David_Graeff asked me to open an issue here.

**Comment by davidgraeff** [comment]
@kaikreuzer Can be closed if the merge request is accepted :)

**Comment by kaikreuzer** [comment]
@davidgraeff I have updated your https://github.com/openhab/openhab2-addons/pull/1781#issue-203791047, so that this will happen automatically!
