### ISSUE TITLE
[RFXCOM Binding] PT2262, multi-bit on/off code

### ISSUE THREAD

**Issue by daniel-hermann** [openhab/openhab2-addons#1702]
Hello,

I use Openhab 2.0.0-Snapshot Build#720 (apt-get shows verison 2.0.0~20170114120524-1).

I have a problem with PT2262 switches.

Switches where only the last bit is on/off, the rest is the device-id work perfectly.
Switches where the last two bits are on/off code do not work at all.

Can anyone confirm that?
any log information I can provide with this specific problem?

thank you
Daniel

**Comment by gersilex** [comment]
Forum discussion: https://community.openhab.org/t/rfxcom-pt2262-how-does-it-work/19660

**Comment by martinvw** [comment]
Hello could you test with this new version of the binding, the support should have improved.

[org.openhab.binding.rfxcom-2.1.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab2-addons/files/845907/org.openhab.binding.rfxcom-2.1.0-SNAPSHOT.jar.zip)

**Comment by daniel-hermann** [comment]
I am very sorry for replying so late, but i put the openhab project on hold for a while.

I am now trying it and it is not completely working.

The Items are auto-discovered, and then I add them in the Paper UI.
When using the remote the status of the thing changes. But when trying to use openhab (paperui) to change the state it does not work, and the debugging log shows this error:

`21:34:12.698 [ERROR] [binding.rfxcom.handler.RFXComHandler] - Transmitting error
org.openhab.binding.rfxcom.internal.exceptions.RFXComException: Invalid device id '4265217'
        at org.openhab.binding.rfxcom.internal.messages.RFXComLighting4Message.setDeviceId(RFXComLighting4Message.java:218)[201:org.openhab.binding.rfxcom:2.1.0.201702192000]
        at org.openhab.binding.rfxcom.handler.RFXComHandler.handleCommand(RFXComHandler.java:86)[201:org.openhab.binding.rfxcom:2.1.0.201702192000]
        at org.eclipse.smarthome.core.thing.internal.ThingManager$4.call(ThingManager.java:361)[106:org.eclipse.smarthome.core.thing:0.9.0.201702100936]
        at org.eclipse.smarthome.core.thing.internal.ThingManager$4.call(ThingManager.java:1)[106:org.eclipse.smarthome.core.thing:0.9.0.201702100936]
        at org.eclipse.smarthome.core.common.SafeMethodCaller.executeDirectly(SafeMethodCaller.java:218)[99:org.eclipse.smarthome.core:0.9.0.201702100936]
        at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:189)[99:org.eclipse.smarthome.core:0.9.0.201702100936]
        at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:83)[99:org.eclipse.smarthome.core:0.9.0.201702100936]
        at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:67)[99:org.eclipse.smarthome.core:0.9.0.201702100936]
        at org.eclipse.smarthome.core.thing.internal.ThingManager.receiveCommand(ThingManager.java:358)[106:org.eclipse.smarthome.core.thing:0.9.0.201702100936]
        at org.eclipse.smarthome.core.items.events.AbstractItemEventSubscriber.receive(AbstractItemEventSubscriber.java:46)[99:org.eclipse.smarthome.core:0.9.0.201702100936]
        at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:192)[99:org.eclipse.smarthome.core:0.9.0.201702100936]
        at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:1)[99:org.eclipse.smarthome.core:0.9.0.201702100936]
        at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:181)[99:org.eclipse.smarthome.core:0.9.0.201702100936]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748)[:1.8.0_131]
`

**Comment by martinvw** [comment]
Can you test with the latest version of the binding, so not the version which I offered as download but just the current stable or snapshot version. It has been merged for months already and the code which throws this error does not exists anymore (luckily enough in this case)

**Comment by daniel-hermann** [comment]
I am using binding-rfxcom - 2.1.0.SNAPSHOT, which should be the current version, right?

**Comment by martinvw** [comment]
Your logging suggests you are using a binding of 19 February, so that is not the newest. Also the newest snapshot is a 2.2.0 snapshot

**Comment by daniel-hermann** [comment]
you are absolutely right, I am sorry. Somehow I had to change repo, and dit not realize it.

Now it says "binding-rfxcom - 2.1.0" can that be right for the stable release?

Is the right way to add in the PaperUI? Now it seems I can turn it on but not off.

**Comment by martinvw** [comment]
The ON/OFF commands should be configurable, so if the defaults are not good you should be able to change it. When running in debug mode you should be able to capture the desired on off commands.

**Comment by daniel-hermann** [comment]
Thank you for your patience with me ;)

`16:48:14.062 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Message received: Raw data = 09130042411511014570, Packet type = LIGHTING4, Seq number = 66, Sub type = PT2262, Device Id = 266577, Command = ON_1(1), Pulse = 325
16:48:14.068 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'rfxcom:lighting4:rfxtrx433E:266577' to inbox.
16:48:14.070 [INFO ] [smarthome.event.InboxAddedEvent     ] - Discovery Result with UID 'rfxcom:lighting4:rfxtrx433E:266577' has been added.
16:48:15.038 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Message received: Raw data = 09130043411514014270, Packet type = LIGHTING4, Seq number = 67, Sub type = PT2262, Device Id = 266577, Command = OFF_4(4), Pulse = 322
16:48:15.455 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Checking RFXCOM transceiver connection, thing status = ONLINE
`

**Comment by martinvw** [comment]
You are welcome!

ON_1 / OFF_4 sounds good can you also post debug logging of sending?

If you add a triple back-tick before and after it will display properly

**Comment by daniel-hermann** [comment]
```16:41:29.988 [DEBUG] [binding.rfxcom.handler.RFXComHandler] - Received channel: rfxcom:lighting4:rfxtrx433E:266577:command, command: ON
16:41:29.989 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Transmitting message 'Raw data = unknown, Packet type = LIGHTING4, Seq number = 0, Sub type = PT2262, Device Id = 266577, Command = ON_1(1), Pulse = 322'
16:41:29.992 [INFO ] [marthome.event.ItemStateChangedEvent] - Audio_schlafzimmer_sw_Command changed from OFF to ON
16:41:29.995 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'Audio_schlafzimmer_sw_Command' received command ON
16:41:30.349 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Message received: Raw data = 0402010000, Packet type = TRANSMITTER_MESSAGE, Seq number = 0, Sub type = RESPONSE, Response = ACK
16:41:30.350 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Transmitter response received: Raw data = 0402010000, Packet type = TRANSMITTER_MESSAGE, Seq number = 0, Sub type = RESPONSE, Response = ACK
16:41:32.141 [DEBUG] [binding.rfxcom.handler.RFXComHandler] - Received channel: rfxcom:lighting4:rfxtrx433E:266577:command, command: OFF
16:41:32.142 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Transmitting message 'Raw data = unknown, Packet type = LIGHTING4, Seq number = 0, Sub type = PT2262, Device Id = 266577, Command = OFF_4(4), Pulse = 322'
16:41:32.146 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'Audio_schlafzimmer_sw_Command' received command OFF
16:41:32.147 [INFO ] [marthome.event.ItemStateChangedEvent] - Audio_schlafzimmer_sw_Command changed from ON to OFF
16:41:32.500 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Message received: Raw data = 0402010000, Packet type = TRANSMITTER_MESSAGE, Seq number = 0, Sub type = RESPONSE, Response = ACK
16:41:32.500 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Transmitter response received: Raw data = 0402010000, Packet type = TRANSMITTER_MESSAGE, Seq number = 0, Sub type = RESPONSE, Response = ACK
```

**Comment by martinvw** [comment]
It seems all proper, pity that it does not work 

This is the OFF we send
```Transmitting message 'Raw data = unknown, Packet type = LIGHTING4, Seq number = 0, Sub type = PT2262, Device Id = 266577, Command = OFF_4(4), Pulse = 322'```

And this is the OFF we receive:

```Message received: Raw data = 09130043411514014270, Packet type = LIGHTING4, Seq number = 67, Sub type = PT2262, Device Id = 266577, Command = OFF_4(4), Pulse = 322```


The subtype, device id, command and pulse all seem to match.

**Comment by daniel-hermann** [comment]
Can I somehow check the raw data that is really sent?

**Comment by martinvw** [comment]
Setting the logging to TRACE might give the raw data we send

**Comment by daniel-hermann** [comment]
Ok, so I checked, the raw message is different.

raw OFF recieved from the handheld: 
```Raw data = 09130043411514014270
OFF sent by rfxcom 
```Send data (len=10): 09130000411514014200

**Comment by martinvw** [comment]
```
09130043411514014270
09130000411514014200
```

The hex 43 is the sequence number which translates to 67
The 70 in the end is the signal strength which also does not have to be set when sending.

So there should be no real difference, maybe the RFXCOM just fails to send the proper signal, did it work with the old openHAB 1 binding? Can you maybe share some more details about the device you are using.
