### ISSUE TITLE
[RFXCOM] discovered things reappear in inbox after deletion

### ISSUE THREAD

**Issue by rtvb** [openhab/openhab2-addons#1712]
Any automatically discovered thing that I manually delete from the Inbox in Paper UI eventually is being re-discovered again and returns to the Inbox. This has flooded (and will continue to do so) my Inbox with over 150 items from RF devices that are not mine, but my neighbors'.

**Comment by sjka** [comment]
Did you _delete_ or _ignore_ them?

**Comment by lolodomo** [comment]
If they were deleted, it us expected that they reappear later.

**Comment by rtvb** [comment]
I deleted them. In the past I have had similar issues with the Hue binding (reappearing things for bridge and bulbs that I have already manually configured). Since yesterday I started to ignore them. I have restarted once or twice and will monitor in the future if they re-appear. Hopefully not. I have had over 200 RFXCOM items in the Inbox.

**Comment by lolodomo** [comment]
Issue to be closed ?

**Comment by rtvb** [comment]
Ignored things stay hidden until explicitly asked for. Even after restarts and apt-get updates.

Why do they reappear after deletion by design?

**Comment by lolodomo** [comment]
Because if you delete a discovered thing, it is deleted and openHAB keeps no trace of it and so of course it will reappear the next time a discovery is triggered. If you don't want this behaviour, just ignore the discovered thing and don't delete it.

**Comment by mrwee** [comment]
Can I just add that this seems to be an RFXCOM binding issue? It seems that the binding thinks these are new devices but they're not. I had 200+ Lightning4 devices in my list, but RFXmgr does not show more than 20.

**Comment by martinvw** [comment]
What do you mean that RFXmgr shows 20? It could partially be related to what part we assume to be the device id and what part we assume to be part of the payload, But please elaborate.
