### ISSUE TITLE
[maryTTS] use wrong sampling rate for German voices

### ISSUE THREAD

**Issue by curlyel** [openhab/openhab2-addons#1715]
When setting maryTTS to use one of the two German voices  _bits3-hsmm/bits1-hsmm_, the speech is rendered way too fast ("donald duck's voice"). It's impossible to unterstand any spoken output which probably makes the two German voices useless in the distribution.

btw.: The English voice _cmu-slt-hsmm_ is working well while rendered at the right speed.

**Comment by dirtyharryiv** [comment]
I have exactly the same problem.

**Comment by marcelloceschia** [comment]
I have checked the sample rate with the german voices, and these are in 16000 Hz where the en_US uses 48000 Hz.
Sadly, the marryTTS package for openhab uses a hard coded value of 48000  in MaryTTSAudioStream.java, so it is not usable for "any" languages.

**Comment by curlyel** [comment]
Sounds like you identified the lines in the code dealing with the sample rate. Some idea how to adjust/make it manually selectable if not automatically?

Since I'm not a Java programmer, I can't fix that myself. But probably we can point somebody in the right direction to get this sorted out ...

**Comment by marcelloceschia** [comment]
@curlyel it should be an easy fix in https://github.com/openhab/openhab2-addons/blob/50f7f662b4e5cf9f99b0c9a3e64f7097357d17e4/addons/voice/org.openhab.voice.marytts/src/main/java/org/openhab/voice/marytts/internal/MaryTTSAudioStream.java#L92

changing 
`int srate = 48000;`
to
`long srate = this.audioFormat.getFrequency();`

the sampling rate is already defined for Voice, see: https://github.com/marytts/marytts/blob/497548b263b4ec15095ae1ad1209b55dbaa5755c/marytts-runtime/src/main/java/marytts/modules/synthesis/Voice.java#L171

Unfortunately I was unable to build the bundle to test it

**Comment by curlyel** [comment]
Wow, that seems simple - indeed. 
Since I'm not capable of compiling some jar out of the sources myself, I've asked on the comunity forum for help on it ...

Anyhow - many thanks for looking into it!

**Comment by marcelloceschia** [comment]
@curlyel I've got it working. But it needs a null pointer check, because there is an initial request without an audio format. But the real audio has set the correct audioformat.
So it has to be: `long srate = (this.audioFormat != null) ? this.audioFormat.getFrequency() : 16000l;`

For testing you can try: https://www.dropbox.com/s/uksw9s0t2fk52qr/org.openhab.voice.marytts-2.0.0-SNAPSHOT.jar?dl=1
You have to update the bundle and restart openHAB
