### ISSUE TITLE
[CometVisu] Unable to install on OpenHAB 2 on Win10

### ISSUE THREAD

**Issue by MageGH** [openhab/openhab2-addons#1717]
The structure of the OH2 has been changed and the documents to install CometVisu on OH2 are outdated. I need a guide how to install it. Simply pushing the install button in Paper UI adds the Cometvisu UI to the OH2 welcome screen but getting the following error:
HTTP ERROR 404
Problem accessing /cometvisu/. Reason:
Not Found

I am running Win10

**Comment by peuter** [comment]
As described here: https://github.com/openhab/openhab2-addons/tree/master/addons/ui/org.openhab.ui.cometvisu

You have to download and extract the CometVisu to a folder on your computer and tell the cometvisu-binding where this folder is in the cometvisu.cfg file.

Whats parts of the documentation are outdated?

**Comment by MageGH** [comment]
Hello, 
The folder below doesnt exist on the latest OpenHAB2 releases.

"Relative path to the folder the CometVisu client can be found:
cometvisu:webFolder=runtime/web/src/"

e/web/src/

**Comment by peuter** [comment]
That is just an example, you have to replace it with the absolute path to your local cometvisu installation

**Comment by peuter** [comment]
I just create a PR with an update for the documentation, that hopefully make these things more clear.

**Comment by MageGH** [comment]
In the meanwhile can you help me because it doesnt want to work for me?
This is what I did:

1. Installed the CometVisu addon which is part of the OH2 addon pack
2. Extracted the "release" folder (including the release folder) of the downloaded CometVisu archive in the runtime folder off my openHAB2 server.
3. Tried to modify the 'cometvisu.cfg' 'cometvisu:webFolder=' setting without any success

Anything else I need to do? What webfolder should be set exactly? The release folder? Or what?

**Comment by peuter** [comment]
The webfolder must point to the folder where the cometvisu's index.html is in. What path did you configure as webFolder?

**Comment by MageGH** [comment]
It works!! :) Thanks a lot Tobias.
Btw, the installation instructions never says that this should point to the index.html. I think the description should look something like this:

1. Extracted the "release" folder of the downloaded CometVisu archive into the runtime folder of the openHAB2 server
2. Install the CometVisu addon which is part of the OH2 addon pack
3. Modify the 'cometvisu:webFolder=' setting in the 'cometvisu.cfg' file to point to the index.html file which was originally in the release folder of the downloaded CometVisu archive

cometvisu:webFolder=c:\OpenHAB\runtime\release\
This setting was working for me.

**Comment by peuter** [comment]
I guess this issue can be closed.
