### ISSUE TITLE
Paper UI not working properly during configuration setup

### ISSUE THREAD

**Issue by Tepsiya** [openhab/openhab2-addons#1726]
Hello -- as you can see I am new in the world of Openhab..  I have now finally installed openhab on raspberry PI3.. it was working properly however the knx binding wouldnt install .. so I updated the knx.cfg file and started to (try and error) using items and sitemaps..  since that paperui is not working anymore and other formatting is very odd.. Habpanel however seems to work fine .. 

opening paperui I get this .. 

≡ 
{{title}} chevron_right {{subtitle}}  

tx for support! ..

**Comment by kaikreuzer** [comment]
Welcome at openHAB! Please let me guide you a bit - for support, you should best visit our forum at https://community.openhab.org/. Issue trackers are mainly used for concrete bugs and code discussions. Thanks!

**Comment by Tepsiya** [comment]
tx
