### ISSUE TITLE
z-wave Fibaro FGMS0001 Unknown Sensor Type = 54

### ISSUE THREAD

**Issue by rwijngaa** [openhab/openhab2-addons#1727]
Hi,

I'm using openhab2 on a rpi, and added my Fibaro FGMS 001 sensor. The temperature and luminance work fine, but i cannot get the burglaralarm, batterylevel, etc to work.
In the logs i see two error's concerning the fibaro node (node9)

```
2017-01-18 10:38:07.845 [ERROR] [ss.ZWaveMultiLevelSensorCommandClass] - NODE 9: Unknown Sensor Type = 53, ignoring report.
2017-01-18 10:38:07.864 [ERROR] [ss.ZWaveMultiLevelSensorCommandClass] - NODE 9: Unknown Sensor Type = 54, ignoring report.
```
How do i get rid of these unknowns? I'm using the latest openhab snapshot and
Z-Wave binding 2.0.0.SNAPSHOT (zwave_version: 3.2)

Regards
Rino

**Comment by rwijngaa** [comment]
Maybe @cdjackson can help?

**Comment by IOOOTAlan** [comment]
@rwijngaa this is the wrong repository, as it doesn't contain the zwave binding anymore.
You should probably move your question to the [relevant zwave subsection on the OpenHab community forum](https://community.openhab.org/tags/c/add-ons/bindings/zwave), before opening an issue on the [zwave binding repository](https://github.com/openhab/org.openhab.binding.zwave)

**Comment by cdjackson** [comment]
As above - I'd suggest to discsuss on the forum, and if there's a bug found, then we open an issue on the zwave issue tracker...
