### ISSUE TITLE
{Homematic] HM-ES-TX-WM and HM-ES-PMSw1-Pl do not work (OFFLINE)

### ISSUE THREAD

**Issue by belmondo2001** [openhab/openhab2-addons#1728]
Hello,
after update oh2 the homematic binding for 'HM-ES-TX-WM and HM-ES-PMSw1-Pl ' 
 doesn't work.
i got following errors .

OFFLINE - COMMUNICATION_ERROR -1 Failure (sending <?xml version="1.0" encoding="ISO-8859-1"?> <methodCall><methodName>getValue</methodName> <params><param><value>LEQ0272118:2</value></param><param><value>ENERGY_COUNTER</value></param></params></methodCall>)

-----------

OFFLINE - COMMUNICATION_ERROR -1 Failure (sending <?xml version="1.0" encoding="ISO-8859-1"?> <methodCall><methodName>getValue</methodName> <params><param><value>MEQ0381392:1</value></param><param><value>IEC_ENERGY_COUNTER</value></param></params></methodCall>)

mfg.
Jürgen

**Comment by MHerbst** [comment]
Can you activate the trace with 

`log:set TRACE org.openhab.binding.homematic`

and attach the log file?

Are you using a CCU or Homegear?

**Comment by MHerbst** [comment]
@belmondo2001 Is this issue still open? If yes please test it again with the latest snapshot build and provide the requested information if the problem still occurs.

**Comment by BOFH90** [comment]
Same here with Raspberrymatic (2.27.8.20170501).
You can also see the following error in the CCU2-Logs multiple times, nearly every minute.:

> err	rfd	 HSSParameter::GetValue() id=GAS_ENERGY_COUNTER failed getting physical value.


In OpenHab2, the device is shown as "Offline" with Error "-1" but Data is avaliable in the CCU2-Webinterface execpt in OpenHab2.

**Comment by MHerbst** [comment]
Which version of the binding are you using? There have been quite a lot changes in the last month.

**Comment by BOFH90** [comment]
Iḿ using the latest version in the repos (2.0.0) which hasn´t changed since the last few month. But i don´t want to change to a non-rc or unstable release. I hope a new version gets pushed to the repos very soon.

**Comment by MHerbst** [comment]
> I hope a new version gets pushed to the repos very soon.
This would require a new openHAB release. Currently there is no release date for the next version. It is possible to only replace the Homematic binding by a new version for a test (see https://community.openhab.org/t/frequently-asked-questions-faqs/17727#addons-1).

**Comment by BOFH90** [comment]
It works with the newer 2.1.0 Binding 👍 Openhab2 is now able to receive data.

**Comment by martinvw** [comment]
@BOFH90 thanks for testing!
