### ISSUE TITLE
[zwave-binding] Add new device: Popp Z-Weather

### ISSUE THREAD

**Issue by moonwhaler** [openhab/openhab2-addons#1731]
Hello,

please add support for the Device Popp Z-Weather to the database, It's already there, but it seems (even while using the latest (apt) nightly of openhab 2 + Zwave binding), mine isn't recognised:

0154:0100:0400:1.0 (Unknown device)

http://products.z-wavealliance.org/products/2102

Manufacturer: 0154 (Popp & Co.)
Type: 0100
ID: 0400

This was tested again with a brand new setup including the new apt-repository, but although other devices are being added sucessfully, this one is not.

If you need something else, please tell me.
Thank you!

**Comment by cdjackson** [comment]
Please can you close this and create an issue in the zwave issue list - it will simply get lost here.

Thanks.
