### ISSUE TITLE
NPE in Astro binding

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab2-addons#1732]
`12:43:00.002 [ERROR] [org.quartz.core.JobRunShell ] - Job astro:sun:local.job-event-start-noon#event threw an unhandled Exception: java.lang.NullPointerException at org.openhab.binding.astro.handler.AstroThingHandler.triggerEvent(AstroThingHandler.java:304)[185:org.openhab.binding.astro:2.0.0.201701121723] at org.openhab.binding.astro.internal.job.EventJob.executeJob(EventJob.java:32)[185:org.openhab.binding.astro:2.0.0.201701121723] at org.openhab.binding.astro.internal.job.AbstractBaseJob.execute(AbstractBaseJob.java:39)[185:org.openhab.binding.astro:2.0.0.201701121723] at org.quartz.core.JobRunShell.run(JobRunShell.java:202)[105:org.eclipse.smarthome.core.scheduler:0.9.0.201701091847] at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)[105:org.eclipse.smarthome.core.scheduler:0.9.0.201701091847] 12:43:00.006 [ERROR] [org.quartz.core.ErrorLogger ] - Job (astro:sun:local.job-event-start-noon#event threw an exception. org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.NullPointerException] at org.quartz.core.JobRunShell.run(JobRunShell.java:213)[105:org.eclipse.smarthome.core.scheduler:0.9.0.201701091847] at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)[105:org.eclipse.smarthome.core.scheduler:0.9.0.201701091847] Caused by: java.lang.NullPointerException at org.openhab.binding.astro.handler.AstroThingHandler.triggerEvent(AstroThingHandler.java:304)[185:org.openhab.binding.astro:2.0.0.201701121723] at org.openhab.binding.astro.internal.job.EventJob.executeJob(EventJob.java:32)[185:org.openhab.binding.astro:2.0.0.201701121723] at org.openhab.binding.astro.internal.job.AbstractBaseJob.execute(AbstractBaseJob.java:39)[185:org.openhab.binding.astro:2.0.0.201701121723] at org.quartz.core.JobRunShell.run(JobRunShell.java:202)[105:org.eclipse.smarthome.core.scheduler:0.9.0.201701091847] ... 1 more 12:44:00.001 [ERROR] [org.quartz.core.JobRunShell ] - Job astro:sun:local.job-event-end-noon#event threw an unhandled Exception: java.lang.NullPointerException at org.openhab.binding.astro.handler.AstroThingHandler.triggerEvent(AstroThingHandler.java:304)[185:org.openhab.binding.astro:2.0.0.201701121723] at org.openhab.binding.astro.internal.job.EventJob.executeJob(EventJob.java:32)[185:org.openhab.binding.astro:2.0.0.201701121723] at org.openhab.binding.astro.internal.job.AbstractBaseJob.execute(AbstractBaseJob.java:39)[185:org.openhab.binding.astro:2.0.0.201701121723] at org.quartz.core.JobRunShell.run(JobRunShell.java:202)[105:org.eclipse.smarthome.core.scheduler:0.9.0.201701091847] at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)[105:org.eclipse.smarthome.core.scheduler:0.9.0.201701091847] 12:44:00.003 [ERROR] [org.quartz.core.ErrorLogger ] - Job (astro:sun:local.job-event-end-noon#event threw an exception. org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.NullPointerException] at org.quartz.core.JobRunShell.run(JobRunShell.java:213)[105:org.eclipse.smarthome.core.scheduler:0.9.0.201701091847] at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)[105:org.eclipse.smarthome.core.scheduler:0.9.0.201701091847] Caused by: java.lang.NullPointerException at org.openhab.binding.astro.handler.AstroThingHandler.triggerEvent(AstroThingHandler.java:304)[185:org.openhab.binding.astro:2.0.0.201701121723] at org.openhab.binding.astro.internal.job.EventJob.executeJob(EventJob.java:32)[185:org.openhab.binding.astro:2.0.0.201701121723] at org.openhab.binding.astro.internal.job.AbstractBaseJob.execute(AbstractBaseJob.java:39)[185:org.openhab.binding.astro:2.0.0.201701121723] at org.quartz.core.JobRunShell.run(JobRunShell.java:202)[105:org.eclipse.smarthome.core.scheduler:0.9.0.201701091847] ... 1 more`

I don't use noon. This happens in intervals of around 40 min, with varying jobs. sometimes it's sun:noon, sometimes sun:rise, sun:set or moon:set. There is no clear pattern. But if it happens, it always happens to start and end.

Expected: at least catch NPE.

**Comment by mhilbush** [comment]
@J-N-K  Could it be related to this?

https://community.openhab.org/t/npes-in-astro-binding/18657

Does it still occur if you delete and readd the astro things?

**Comment by J-N-K** [comment]
Didn't see that thread and didn't try. However, I think that is not a solution because reconfiguring everytime something in the binding changes is not acceptable. The binding should check if a channel exists before using it.

**Comment by mhilbush** [comment]
I would agree if this was a released product.  Keep in mind that openHAB is under very active development, and that breaking changes are not uncommon.

**Comment by kaikreuzer** [comment]
Nonetheless, I agree with @J-N-K that NPEs can be considered a bug and it always makes sense to harden the code accordingly.

@gerrieg Could you have a look, please?

**Comment by mhilbush** [comment]
I think this fix might actually make the problem worse.  Now, instead of throwing an exception in the log file, if the event channel is missing (most likely because the astro thing was added prior to the event functionality being added), the events will not work, and it will be completely silent about why they are not working.  I'm still not sure how someone will know to delete and readd the astro thing in order to pick up the new event channels.  Would it make sense to log an info or warning message indicating that the channel doesn't exist?

**Comment by gerrieg** [comment]
I've implemented a warning now

**Comment by martinvw** [comment]
I believe the binding is now moved to Eclipse Smarthome, if needed please reopen an issue there.
