### ISSUE TITLE
[exec] Format string from Item to Exec Thing (e.g. to customize parameters)

### ISSUE THREAD

**Issue by stiansoevik** [openhab/openhab2-addons#1735]
Please consider making it possible to format the string sent from Items to Exec Thing.

Use case: Use same Thing for many Items. Send some ID of the Item to the ting.
```
String Livingroom_TvLight "28 [%s] " { channel="exec:command:cmdtest:input" }
Thing exec:command:cmdtest [command="/home/pi/cmdtest %2$s", autorun=true]
```

**Comment by davidgraeff** [comment]
Can be done by openHAB profiles nowadays.
