### ISSUE TITLE
myopenhab: no access to Paper UI ?

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab2-addons#1736]
Using https://myopenhab.org/basicui/app or https://myopenhab.org/classicui/app, we can get a remote access to Basic UI and Classic UI.
Using https://myopenhab.org/paperui or https://myopenhab.org/paperui/app does not work. Is it expected ?

**Comment by kaikreuzer** [comment]
Try https://home.myopenhab.org/ui/index.html resp. https://home.myopenhab.org/paperui/index.html (depending on the OH2 version you are using)

**Comment by lolodomo** [comment]
Ok https://home.myopenhab.org/paperui/index.html is working for me.
Any reason why https://myopenhab.org/paperui/index.html is not working too ?
https://myopenhab.org/basicui/app is working.
https://myopenhab.org/classicui/app is working.
Documentation is mentioning https://myopenhab.org but not https://home.myopenhab.org. Any user will have difficulty to find the right URL for Paper UI !

**Comment by lolodomo** [comment]
@kaikreuzer : I think there is something wrong.
You can access your dashboard with https://myopenhab.org/start/index but then when you click on Paper UI, you got "Cannot GET /paperui/index.html ".

**Comment by kaikreuzer** [comment]
You should simply use the link that is offered on https://myopenhab.org/, which points to https://home.myopenhab.org/start/index and all is well.

**Comment by lolodomo** [comment]
Ok, well I did not see that link on the home page.
