### ISSUE TITLE
[homekit] Add-on missing enumerated type for DimmableSwitchable

### ISSUE THREAD

**Issue by shadowmite** [openhab/openhab2-addons#1740]
I am just starting to get into this openhab stuff, but perhaps I've already found an issue. I have a Smart Fan Control switch that I'd like to control over Siri and noticed if I use the "Lighting" tag it works. But if I use the "Switchable" tag it does nothing. Never shows up. Looking at the code it appears if a "Dimmer" is found as the item it gets changed to "DimmableSwitchable" which does not exist as a enumerated type. Can this be fixed please?

**Comment by shadowmite** [comment]
Actually on second look its also not declared as a valid possibility in: 
HomekitAccessoryFactory.java

Perhaps the proper fix is to change the docs and remove "Dimmer" as a valid type for this tag, but I hope you'll implement it instead. If I could learn to compile this beast I'd try to fix this myself.

**Comment by J-N-K** [comment]
Fixed
