### ISSUE TITLE
Wrong Zodiac Astro Binding

### ISSUE THREAD

**Issue by michaeljoos72** [openhab/openhab2-addons#1742]
Hi

I'm using astro:sun:local:zodiac#sign

Yesterday 20. January should be CAPRICORN=Steinbock (last day).
But Astro-Binding 2.00 (OH2) already showed AQUARIUS=Wassermann

It seems that we have a shift of one day

Michael

**Comment by kaikreuzer** [comment]
@gerrieg Could you have a look, please?

**Comment by gerrieg** [comment]
20. January is Aquarius, see http://www.astrology-zodiac-signs.com

**Comment by kaikreuzer** [comment]
Both of you are right, see [wikipedia](https://en.wikipedia.org/wiki/January_20):

"In the ancient astronomy, it is the cusp day between Capricorn and Aquarius. In some years it is Aquarius, but others Capricorn."

**Comment by gerrieg** [comment]
OK, never heard before... The calculation in the Astro binding is only date base. I need to find a calculator that does it right, there are many inaccurate calculators on the net

**Comment by martinvw** [comment]
I believe the binding is now moved to Eclipse Smarthome, if needed please reopen an issue there.
