### ISSUE TITLE
Z-wave - Battery indicator is not shown correctly - Z-wave binding

### ISSUE THREAD

**Issue by espentj** [openhab/openhab2-addons#1743]
I have a POPP smoke sensor:
Device discovery resolved to thingType zwave:popp_004001_00_000 
that is not able to correctly display it´s battery status. Note I have 10 of this device and all are exhibiting the same behaviour. 

I am wondering if the definition for the battery sensors values are being erronously translated somehow, but I don´t quite know how to investigate further.
One of the devices is NODE 8, and I have included the debug log here. The complete log is also included. 

[POPP-Battery-error-logfiles.zip](https://github.com/openhab/openhab2-addons/files/721057/POPP-Battery-error-logfiles.zip)

The problem has been there for as long as I have run Openhab2 (august 2016), and I am currently running the latest SNAPSHOT as of January 21 - 2017.

The XML file for node 8 is also included: [node8.xml.zip](https://github.com/openhab/openhab2-addons/files/721058/node8.xml.zip)

**Comment by cdjackson** [comment]
Please can you open this issue in the Zwave issue list. 

Thanks
