### ISSUE TITLE
[homematic] INSTALL_TEST not working

### ISSUE THREAD

**Issue by stundzig** [openhab/openhab2-addons#1744]
Hi team,

i've update my homegear to version 7 to get support for the INSTALL_TEST channel in openhab2. I've found in https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/misc/HomematicConstants.java#L43 the constant INSTALL_TEST. 

I've deleted my homematic smoke detectors in openhab2 and readded them as things. But unfortunatly, i can see the INSTALL_TEST channel in the paperui. 

@gerrieg Is this INSTALL_TEST channel supported with the current code base?

My homegear config of my smoke detectors `2F3A15 │LEQ0734461 │ 0042 │HM-Sec-SD` is:
```
(Peer)> config print
MASTER
{
	Channel: 0
	{
		[ROAMING]: 00 
		[POLLING_INTERVAL]: 01 68 
		[POLLING]: 00 
	}
}

VALUES
{
	Channel: 1
	{
		[STATE]: 00 
		[INSTALL_TEST]: 00 
	}
	Channel: 0
	{
		[CENTRAL_ADDRESS_SPOOFED]: 00 
		[DEVICE_IN_BOOTLOADER]: 00 
		[RSSI_PEER]: 00 
		[DUTYCYCLE]: 00 
		[CONFIG_PENDING]: 00 
		[LAST_PACKET_RECEIVED]: 58 82 ce 42 
		[UPDATE_PENDING]: 00 
		[RSSI_DEVICE]: 00 
		[STICKY_UNREACH]: 00 
		[LOWBAT]: 00 
		[UNREACH]: 00 
	}
}

LINK
{
}
```

**Comment by gerrieg** [comment]
It's a generic binding, so all channels are supported.

Did you try to delete and rescan the thing?
Did you see the 'Show More' button to show all channels?

If it doesn't work, please send me a full startup TRACE log, see [Debug and Tracing](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.homematic/README.md)

**Comment by stundzig** [comment]
Hi,

thanks for your help. _Show More_ shows me the new channels. ;)

But unfortunatly, i found also, that **INSTALL_TEST** is a readonly channel. So i can't use the smoke detectors to trigger an alarm from openhab2.
