### ISSUE TITLE
Homekit debug logging?

### ISSUE THREAD

**Issue by johnofcamas** [openhab/openhab2-addons#1746]
I have an issue with HomeKit where it stops working sometime in the middle of the night, but I don't see anything in the openhab logs indicating what the issue might be, is there a way to enable HomeKit debug logs?

**Comment by shadowmite** [comment]
Per the readme under homekit add-on:

openhab> log:set TRACE com.beowulfe.hap

**Comment by martinvw** [comment]
@shadowmite thanks!
@johnofcamas if it doesn't help you please open a new issue
