### ISSUE TITLE
[astro Binding] sunrise event

### ISSUE THREAD

**Issue by MrPatHome** [openhab/openhab2-addons#1747]
Hi,

got a problem with a rule triggerin with sunset or -rise. Can´t figure out what´s wrong.

rule "Außenbeleuchtung an (Sonne)"
when
    Channel astro:sun:home:set#event triggered START 
then
	logInfo("Außenbeleuchtung nach Sonne", "an")
    sendCommand(Aussenlicht_hinten_rechts_1_State, ON)
end

**Comment by benderl** [comment]
I am quite new to Channels in OH2, but I think you have to put the channel name in single quotes '...'
At least this is how it works for me in a similar rule.

**Comment by Celaeno1** [comment]
Yes, you need the single quotes '...' as channel name in the rules-file:

    Channel 'astro:sun:home:set#event' triggered START

**Comment by MrPatHome** [comment]
Thanks for the hints, but still doesn´t work:

rule "Wohnzimmerlicht bei Sonnenuntergang an 1"
when
        Channel 'astro:sun:local:set#event' triggered START
then
    logInfo("Innenbeleuchtung nach Sonne", "an")
    sendCommand(LampeWZ_1_State, ON)
    sendCommand(VitrineTV_1_State, ON)
    sendCommand(VitrineRechts_1_State, ON)

Any Idea?

**Comment by Celaeno1** [comment]
Did you try only 1 sendCommand?

My rule is working fine:

    rule "Osram_Light2_Toggle zeitgesteuert an"
	    when 
		  Channel 'astro:sun:a7f71b41:set#event' triggered START
	    then
		  sendCommand(Osram_Light2_Toggle, ON)
    end

Do you have command "end" at the end of the rule?
 
Be sure that you use the correct item! e.g. "LampeWZ_1_State" is well configured in your item file?

"LampeWZ_1_State" does not seem to be a 'switch' !!??

**Comment by kaikreuzer** [comment]
Sounds more like a support discussion than a bug - I'd suggest to move over to the forum at https://community.openhab.org/.
