### ISSUE TITLE
[homematic] Systemvariables are not imported correctly

### ISSUE THREAD

**Issue by gowi** [openhab/openhab2-addons#1749]
Hi,
it looks like the import of homematic systemvariables does not work properly. The export of systemvariables is OK. See: [https://community.openhab.org/t/receiving-homegear-systemvariables/20847](https://community.openhab.org/t/receiving-homegear-systemvariables/20847)

**Comment by MHerbst** [comment]
The state of system variables can't be updated automatically in OH because Homematic does not send an event for changes of these variables. But you can request a manual update of all with the GATEWAY-EXTRAS channel "Reload All From Gateway".

**Comment by gowi** [comment]
Hmm, in OH1 the update of system variables work properly. And as you can see in the log, OH2 also receives system variable updates: `2017-01-22 00:32:15.593 [DEBUG] [ternal.communicator.HomematicGateway] - Received new (String) value 'OFF' for 'null:0#AlarmanlageStatus' from gateway with id 'd229e0dc'`

But something goes wrong after OH2 received the update.

**Comment by gowi** [comment]
Is there any update in the meanwhile? Here a log from the newest experimental version:

> 2017-02-14 20:54:13.287 [DEBUG] [ternal.communicator.HomematicGateway] - Received new (String) value 'ON' for 'null:0#AlarmanlageStatus' from gateway with id 'd229e0dc'
> 2017-02-14 20:54:13.303 [TRACE] [nicator.server.BinRpcCallbackHandler] - Event BinRpcMessage: system.multicall()
> [
>         {
>                 methodName=event
>                 params=
>                 [
>                         RF-d229e0dc
> 
>                         AlarmanlageStatus
>                         ON
>                 ]
>         }
> ]
> 
> 2017-02-14 20:54:13.309 [DEBUG] [ternal.communicator.HomematicGateway] - Received new (String) value 'ON' for 'null:0#AlarmanlageStatus' from gateway with id 'd229e0dc'

**Comment by MHerbst** [comment]
I assume that the values are not updated automatically in the Basic UI. What happens if you refresh the manually?

**Comment by MHerbst** [comment]
@gowi Is the issue still open? If yes please try the latest snapshot. In the meantime there have some changes regarding the gateway.

**Comment by MHerbst** [comment]
No answer to my question for more than 3 weeks. @martinvw I think we can close this issue.
