### ISSUE TITLE
gnu.io.RXTXPort.eventLoop high CPU load

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab2-addons#1755]
All,

Is anyone using a binding using the gnu.io lib also having issues with a high CPU load, caused by Threads running the gnu.io.RXTXPort.eventLoop loop?

@kaikreuzer Can't remember if you/we/someone decided to go through this library or an alternative one with better native implementations?

**Comment by kaikreuzer** [comment]
No better alternative has been found so far, see https://github.com/openhab/openhab-core/issues/101.

I'd suggest to discuss such issues at https://github.com/NeuronRobotics/nrjavaserial
