### ISSUE TITLE
[MAX!] Feature Request Max! ecoswitch, channel 'mode'

### ISSUE THREAD

**Issue by Celaeno1** [openhab/openhab2-addons#1757]
At the moment Thing 'ecoswitch' is supporting only one channel "battery_low". It would be very usefull, if channel "mode" is supported, too. Modes: AUTO, ECO, OFF, and so on would be great!

**Comment by Celaeno1** [comment]
@marcelrv 
maybe this is something for you?

**Comment by RalphPungaKronbergs** [comment]
+1  
I am missing this feature badly too...

**Comment by marcelrv** [comment]
Unfortunately eco switch position does not seem to be available with this detail in the data the cube is sending.

E.g in the normal eq3 software you also can't see the position of this switch.

If you see somewhere a good implementation that does show this, and we can find out how, I'm very willing to implement this. Until than suggest to close this request

**Comment by Celaeno1** [comment]
Thanks for this information. This is a pity! I read in FHEM forum, that MaxCube provides no state query via LAN, but via 868 MHz (RF, e.g. MAX-CUL)). Maybe there is an other solution to realize this. Normally you can configure ecoswitch with two "actions", e.g. "AUTOMATIC" and "ECO".  If you press at ecoswitch e.g. "AUTOMATIC", then ALL thermostates go to mode "AUTOMATIC" immediately. Now we only need a query for Max! Cube: "when ALL thermostates changed to "AUTOMATIC" within e.g. 10 seconds, then ecoswitch "must have been pressed", then change state of ecoswitch to "AUTOMATIC". And so on...

**Comment by marcelrv** [comment]
This is more something to implement as a rule rather than in the binding. 

E.g 
Add all thermostats to a group, cycle through the thermostats and query thermostat mode. If they are all on manual and with the eco temperature, than consider the switch on eco mode, in all other cases, it is in auto.

**Comment by Celaeno1** [comment]
Ok, I will try a rule... Thank you very much!
