### ISSUE TITLE
[openhabcloud] Unable to save new rule or item in Paper UI when accessing through myopenhab.org

### ISSUE THREAD

**Issue by tavalin** [openhab/openhab2-addons#1758]
I tried to create a new rule using Paper UI but was not able to save (tick icon).  Nothing happens immediately after clicking the button and later I get the following toast message:

`Error: 504 - Gateway Time-out`

The same also happened when I tried to create a new item using Paper UI through myopenhab.org.

If I connected to Paper UI through LAN or dynamic IP then it works as expected.

**Comment by digitaldan** [comment]
Can you please open an issue on https://github.com/openhab/openhab-cloud/issues and close this one?  Thanks!

**Comment by tavalin** [comment]
FTR it seems it has already been raised. https://github.com/openhab/openhab-cloud/issues/31
