### ISSUE TITLE
[OH2 Netatmo Binding] Missing values rain 1h / 24h

### ISSUE THREAD

**Issue by RalphPungaKronbergs** [openhab/openhab2-addons#1762]
The Netatmo Binding is working fine so far, the only two values I'm missing are rain for 1h and 24h. Both are readable via Netatmo API. It would be great if these values would be integrated into the Binding.

Edit: It seems like the sync timestamp for Wind and Rain is also missing, although both exist via Netatmo API.

@clinique - maybe you could have a look? Thx

Thanks,
Punga

**Comment by Homey-GER** [comment]
`                case CHANNEL_SUM_RAIN1:
                    return ChannelTypeUtils.toDecimalType(dashboardData.getSumRain24());
                case CHANNEL_SUM_RAIN24:
return ChannelTypeUtils.toDecimalType(dashboardData.getSumRain24());`

Is it right that both case's return .getSumRain**24**() ?
I dont think so ...

**Comment by clinique** [comment]
Yes, indeed, nice copy paste bug !

**Comment by clinique** [comment]
Thise could be closed
