### ISSUE TITLE
[sonos] Clear player queue

### ISSUE THREAD

**Issue by torstesu** [openhab/openhab2-addons#1765]
The current sonos addon does not provide a channel to clear the current queue of a player. The playlist channel only allows to add tracks from a playlist to a player's queue. Thus, when using the playlist channel multiple times on the same player with different playlists, the queue will represent a mix of the playlists added.

In many use cases, a user would prefer to clear the queue so to only play tracks from the selected playlist.

My proposal is to implement a new channel to enable the user to clear the queue of a player. Keeping the playlist and clearqueu channel separated, will allow the user to choose the behaviour when adding tracks to the queue.

**Comment by kaikreuzer** [comment]
Please note that the Sonos binding is part of ESH: https://github.com/eclipse/smarthome/labels/Sonos
