### ISSUE TITLE
References to items in the Frame declaration, within a sitemap, block updates on icons!

### ISSUE THREAD

**Issue by sailorsail** [openhab/openhab2-addons#1768]
In a clean install of openHAB 2.0 Release Build, I've used the following configuration:
file.items
```csv
Switch Light_WCSmall_Ceiling 	"Light Ceiling WC Small" 				
Switch Light_WCBig_Ceiling 	"Light Ceiling WC Big" 				
Number Temp_WCBig 		"Temperature WC Big [%.2f °C]" 	
```
file.sitemap
```php
sitemap demo label="demo" {
	Text label="WC1" {
		Frame label="test" {
			Switch item=Light_WCBig_Ceiling
			}
		}
	Text label="WC2" {
		Frame item=Temp_WCBig {
			Switch item=Light_WCSmall_Ceiling
			}
		}
	}
```
When I toggle 'Light_WCBig_Ceiling', within “WC1” page, the update of the icon is performed; no refresh is necessary on the user interface (either iOS or Web Basic UI).
However if I toggle 'Light_WCBig_Ceiling', within “WC2” page, the update of the icon is not performed.
Nevertheless, if I refresh the page, navigate back, and in again, the change is then shown.
The only diference here is the use of item=Temp_WCBig in the Frame declaration.
Allegedly, the use of items in frame declarations is possible, but I wasn’t expecting the different behaviour. Shouldn’t the reaction to the toggle be consistent, or is this the expected behaviour?
Do you have any ideias about what's going on?

**Comment by kaikreuzer** [comment]
This does not seem to be about any specific openHAB 2 add-on, so this issue tracker is most likely the wrong place. Did you already ask for support in the forum at https://community.openhab.org/?

**Comment by sailorsail** [comment]
I did asked in the forum at:
https://community.openhab.org/t/do-references-to-items-on-frame-declaration-in-the-sitemap-block-updates-on-icons/21083/4
In the forum it has been suggested that an issue needs to be filed, possibly the BasicUI in the openhab2-addons repo.
We could be wrong, but if the above mentioned behaviour is not expected, could you advice where this issue could be filled?

**Comment by MHerbst** [comment]
> We could be wrong, but if the above mentioned behaviour is not expected, could you advice where this issue could be filled?

The correct place for issues regarding Basic UI is in the SmartHome repo: https://github.com/eclipse/smarthome/issues
