### ISSUE TITLE
Support for Rfxcom Kangtai

### ISSUE THREAD

**Issue by thibhen** [openhab/openhab2-addons#1772]
Hello, 
Is it possible to add support for Rfxcom / Lighting5 / Kangtai type of devices ?

Change is about adding in the File 

>org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting5Message.java

in the enum  SubType, a new Entry "Kangtai (17)"

This device was added recently by Rfxcom (Firmware 1013) : http://blog.rfxcom.com/?p=106

Thanks

Thibaut

**Comment by martinvw** [comment]
I have added support in a local branch, but it would be great if you could be provide with some example output of the RFXCom device, either from the RFXMngr or from rfxcom debug statements. In that way a test can be added as well.

[org.openhab.binding.rfxcom-2.1.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab2-addons/files/758778/org.openhab.binding.rfxcom-2.1.0-SNAPSHOT.jar.zip)

Can you please test and supply me with some test data including action you requested to validate it to be correct.

**Comment by martinvw** [comment]
And it might not be stated explicitly but the jar should provide the proper support for the Lighting5 / Kangtai type.
