### ISSUE TITLE
Error in Onkyo readme

### ISSUE THREAD

**Issue by TheNetStriker** [openhab/openhab2-addons#1774]
I just found a typo in the onkyo readme: https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.onkyo/README.md

The typo is under the "Thing Configuration". The thing should be declared as onkyo:onkyoAV**R**:myOnkyo. (onkyoAVR instead of onkyoAV)

**Comment by paulianttila** [comment]
This will be fixed with PR #1708

**Comment by cweitkamp** [comment]
#1708 is merged long time ago. Is this ready for closing?
