### ISSUE TITLE
Offline Hue lights

### ISSUE THREAD

**Issue by obartelt** [openhab/openhab2-addons#1776]
When I switch a Hue light off manually (cutting power by using a wall switch), I get an event in the Karaf console:

[me.event.ThingStatusInfoChangedEvent] - 'hue:0100:001788253ecd:8' changed from ONLINE to OFFLINE: Bridge reports light as not reachable

But the light is still shown as "on" in OpenHAB (brightness as it was set (e.g. 100%), and the :switch channel set to ON).

Is that a bug? How can I get the real state of the light in OpenHAB (i.e. "off"/0%)?

**Comment by kaikreuzer** [comment]
Note that the hue binding is located at https://github.com/eclipse/smarthome, so it should be reported there.
I have seen the same effect in my log, but didn't further analyze it.
As the binding claims that "Bridge reports light as not reachable", did you already check with the Philips Hue app whether the lights are shown to have a problem there?

**Comment by obartelt** [comment]
Yes, they are correctly shown as having a problem there (since they're actually non powered, and thus non reachable).

**Comment by kaikreuzer** [comment]
Ah, sorry, I didn't read your initial description carefully enough.
No, it is not a bug that openHAB still shows it ON. It simply shows you the last " real state of the bulb". If the connection to the bulb breaks (for whatever reason!), how would you possibly know any updated "real" state?

**Comment by obartelt** [comment]
Hmm, while I can understand that, how do you handle such a situation? I have some lights in my home that I really switch off physically, and I want it to show as such in my sitemap (and not thinking I have left the lights on). Any idea?

**Comment by kaikreuzer** [comment]
Not that easy. You would probably best do a rule, but you would need https://github.com/eclipse/smarthome/issues/1654 for it.

**Comment by obartelt** [comment]
Yeah, I've seen that, too. Too bad it's not implemented yet :-(

**Comment by obartelt** [comment]
Would it perhaps be possible to implement another channel "online" or something along that lines, which would represent the actual connection state (online, offline, unknown)?

**Comment by jn-se** [comment]
@obartelt It is now working in the snapshots build since the merge in April. See #3001.

But the status change ONLINE/OFFLINE is very slow and delayed. Does anybody else can confirm this behaviour? It seems to be a problem in the bridge.
