### ISSUE TITLE
Z-Wave & Powermax bindings will not run together

### ISSUE THREAD

**Issue by big-col** [openhab/openhab2-addons#1777]
I have a strange issue...

I can install the zwave binding, configure and run OH2 without any issues.
If i add the Powermax 1.0 binding alongside zwave, it works OK until the next time i restart OH2, then neither zwave nor powermax will work.

Sometimes after a restart i get the following error in the console, i cannot find this in the logs though
_openhab> Error 0x6 at src/windows/termios.c(2265): The handle is invalid._

If i remove both addons/bindings and add them again, both will work, until i next restart OH2
I am currently running OH2 release build, this has been happening since beta 3 or 4, which is when i started looking at upgrading from OH1.

This is easily repeatable.  I have increased logging in a number of areas, probably too much now though.

Please let me know what logs would help in understanding the problem.

As always, thanks in advance :)
Colin

**Comment by scurb** [comment]
I have both ZWave and Powermax binding in OH2 running in parallell. I use IP connection to my Powermax from OH2.

**Comment by big-col** [comment]
Intresting, how are you doing that?

And what OS are you using?

**Comment by big-col** [comment]
I downloaded a serial-tcp tool from https://www.commfront.com/pages/downloads and now OH2 talks to my Powermax via IP.  i can now run Powermax and zwave in parallel.  

Thanks Patrik @scurb :)
