### ISSUE TITLE
[Network Binding] native ping on linux - wrong flag render ping unusable

### ISSUE THREAD

**Issue by guyyakobovitch** [openhab/openhab2-addons#1778]
In "org.openhab.binding.network/src/main/java/org/openhab/binding/network/service/NetworkUtils.java",
"nativePing" function:

`if (SystemUtils.IS_OS_UNIX) {
            proc = new ProcessBuilder("ping", "-t", String.valueOf(timeout / 1000), "-c", "1", hostname).start();
        } else if (SystemUtils.IS_OS_WINDOWS) {
            proc = new ProcessBuilder("ping", "-w", String.valueOf(timeout), "-n", "1", hostname).start();
        } else {
            throw new InvalidConfigurationException("System Ping not supported");
        }`

The result on linux is: "ping -t {Timeout in seconds} -c 1"
but according to man ping  -t is TTL flag and not timeout flag (which is -w).

I found that after seeing on wireshark expired time to live response messages when setting 1000ms timeout on network binding thing.

That causes the System Ping function to misbehave.

**Comment by kaikreuzer** [comment]
Fixed by https://github.com/openhab/openhab2-addons/pull/1780
