### ISSUE TITLE
Chromecast: the play and say console commands not working

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab2-addons#1784]
With my Freebox Player Mini 4k (Android TV), the following console commands are not working (the palyer is switching to a notification screen but the audio file is never played):
```
openhab> smarthome:audio play chromecast:chromecast:68531fbf51cfff589ca6043630b411bb doorbell.mp3
openhab> smarthome:audio play chromecast:chromecast:68531fbf51cfff589ca6043630b411bb barking.mp3
openhab>
openhab> smarthome:voice say voici un essai de texte
```

**Comment by lolodomo** [comment]
Here is a warning I get:
```
13:19:30.240 [WARN ] [su.litvak.chromecast.api.v2.Channel ] - Unable to process request ID = 62, data: {"responseType":"MEDIA_STATUS","status":[{"mediaSessionId":1,"playbackRate":1,"playerState":"BUFFERING","currentTime":0,"supportedMediaCommands":15,"volume":{"level":1,"muted":false},"media":{"contentId":"http://192.168.1.xx:8080/audio/0f501ff6-50a2-4a5d-b06e-fdccd6ab8881","contentType":"audio/mpeg","metadata":{"title":"Notification","thumb":null},"duration":0},"currentItemId":1,"items":[{"itemId":1,"media":{"contentId":"http://192.168.1.xx:8080/audio/0f501ff6-50a2-4a5d-b06e-fdccd6ab8881","contentType":"audio/mpeg","metadata":{"title":"Notification","thumb":null},"duration":0},"autoplay":true,"customData":null}],"repeatMode":"REPEAT_OFF"}],"requestId":62}
```

**Comment by lolodomo** [comment]
@watou : could it be a problem with the proxy?

Are these commands working well with the official Chromecast products?

**Comment by watou** [comment]
> could it be a problem with the proxy?

The proxy servlet in ESH is only for Image and Video sitemap widgets (presently) and cannot serve any other purpose.  I have proposed [here](https://github.com/eclipse/smarthome/pull/2753#issue-198873443) to securely generalize its function so non-sitemap-based UIs can traverse it.

**Comment by lolodomo** [comment]
Sorry I certainly made a confusion, this URL is an URL for an audio file delivered by openHAB, no link with the UI proxy.

**Comment by lolodomo** [comment]
Ok, maybe chromecast needs to establish several connections to the audio stream ?
The binding uses the audio servlet in such a way that only one access is possible: https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/handler/ChromecastHandler.java#L282
I will check what happens if a duration is defined by the binding.

**Comment by lolodomo** [comment]
Thebinding included in the 2.0 kar was working.
I recompiled the code (with a minor change) and put the jar file in my addons directory.
Here is the error I get:
```
205 | Installed |  80 | 2.1.0.201701291733    | Chromecast Binding
openhab> bundle:start 205
Error executing command: Error executing command on bundles:
        Error starting bundle 205: Could not resolve module: org.openhab.binding.chromecast [205]
  Unresolved requirement: Import-Package: com.fasterxml.jackson.annotation
```
Any idea what I missed ?

**Comment by lolodomo** [comment]
Ok I can confirm that defining a duration (and so allowing multiple connections) solves theis issue.

Another "problem" is that at the end of the notification, google cast player is not closed.

**Comment by lolodomo** [comment]
The problem is now fixed by the proposed PR.

In addition, I tried to close the application using chromecast.stopApp() when IDLE media_status is received but it leads to either NPE or problems.
