### ISSUE TITLE
OH2 don't start cron rules after a while (2.0.0-1, 2.1.0-Snapshot)

### ISSUE THREAD

**Issue by netzlaff** [openhab/openhab2-addons#1785]
After upgrading my RPi3 (Java 1.8.0_121, etc.) and upgrade OH2 from 2.0.0-SNAPSHOT to 2.0.0-1 --> OH2 don't start cron rules after a few minutes. No Errors or something on the log. I've tested 2.1.0-Snapshot, but the problem is the same.

Here my addons.cfg:
```
package = standard

# A comma-separated list of bindings to install (e.g. "sonos,knx,zwave")
binding = astro,exec,knx1,novelanheatpump1,ntp

# A comma-separated list of UIs to install (e.g. "basic,paper")
ui = basic,paper

# A comma-separated list of persistence services to install (e.g. "rrd4j,jpa")
persistence = rrd4j

# A comma-separated list of actions to install (e.g. "mail,pushover")
action =

# A comma-separated list of transformation services to install (e.g. "map,jsonpath")
transformation = map,regex

# A comma-separated list of text-to-speech engines to install (e.g. "marytts,freetts")
tts =

# A comma-separated list of miscellaneous services to install (e.g. "myopenhab")
misc = homekit,openhabcloud
```

I have two cron rules, that starts every minute and on rules that starts every 5 minutes. This rules starts for a few minutes (10 or 30 or ...) and stops executing. After restart OH2, the rules still working - after a few minutes -> stop working!

Befor this update all my rules works perfectly.

What is the the problem, what can i debug ...

Thank you!

**Comment by kaikreuzer** [comment]
Note that this issue tracker is for bugs in openHAB 2 add-ons - your issue does not seem to be about any of those.
As it is not at all clear, what your problem might be, I suggest to first discuss in the forum at https://community.openhab.org/.
