### ISSUE TITLE
[netatmo] netatmo.cfg not created and documentation missing

### ISSUE THREAD

**Issue by CWempe** [openhab/openhab2-addons#1786]
When installing the netatmo binding (e.g. via addons.cfg or karaf console) does not create a netatmo.cfg in /etc/openhab2/.

And I cannot find documentation how the netatmo.cfg should look like to manually create one.

see: https://community.openhab.org/t/will-binding-cfg-files-be-automatically-created/21040/8

**Comment by watou** [comment]
The Netatmo 2.0 binding does not have any configuration itself, as explained in the documentation:

https://github.com/openhab/openhab2-addons/tree/master/addons/binding/org.openhab.binding.netatmo#binding-configuration

The Netatmo 1.9 binding from the openhab1-addons repo does have, and does install, the .cfg file that it needs.

I think this issue should be closed.  WDYT?

**Comment by CWempe** [comment]
I think there is still much to learn for me about openhab2. :(

I still do not know if it is possible to configure openhab2 just via config files.
