### ISSUE TITLE
Sound files produced by say and sendsound are 404

### ISSUE THREAD

**Issue by rapiertg** [openhab/openhab2-addons#1788]
openHAB 2.0 on Debian Jessie amd64 installed from official apt

Every time I try to execute playSound() or say() to kodi:
```
2017-01-28 22:03:52.245 [DEBUG] [i.internal.protocol.KodiClientSocket] - send message: {"jsonrpc":"2.0","id":130,"method":"Application.GetProperties","params":{"properties":["version","name"]}}
2017-01-28 22:03:52.248 [DEBUG] [i.internal.protocol.KodiClientSocket] - Message received from server: {"id":130,"jsonrpc":"2.0","result":{"name":"Kodi","version":{"major":16,"minor":1,"revision":"c327c53","tag":"stable"}}}
2017-01-28 22:03:52.248 [DEBUG] [i.internal.protocol.KodiClientSocket] - Response received from server:{"id":130,"jsonrpc":"2.0","result":{"name":"Kodi","version":{"major":16,"minor":1,"revision":"c327c53","tag":"stable"}}}
2017-01-28 22:03:52.248 [DEBUG] [i.internal.protocol.KodiClientSocket] - callMethod returns {"id":130,"jsonrpc":"2.0","result":{"name":"Kodi","version":{"major":16,"minor":1,"revision":"c327c53","tag":"stable"}}}
```

In Kodi side I am getting something like:
```
21:46:35 4562.937012 T:1963397120  NOTICE: DVDPlayer: Opening: http://192.168.1.5:8080/audio/48f250c6-b5a2-44e8-9946-49a0d96c6ccb
21:46:35 4562.937500 T:1963397120 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
21:46:35 4562.939453 T:1423963040  NOTICE: Creating InputStream
21:46:35 4562.955078 T:1423963040   ERROR: CCurlFile::Open failed with code 404 for http://192.168.1.5:8080/audio/48f250c6-b5a2-44e8-9946-49a0d96c6ccb
21:46:35 4562.955078 T:1423963040   ERROR: Open - failed to open source <http://192.168.1.5:8080/audio/48f250c6-b5a2-44e8-9946-49a0d96c6ccb>
21:46:35 4562.955566 T:1423963040   ERROR: CDVDPlayer::OpenInputStream - error opening [http://192.168.1.5:8080/audio/48f250c6-b5a2-44e8-9946-49a0d96c6ccb]
21:46:35 4562.955566 T:1423963040  NOTICE: CDVDPlayer::OnExit()
21:46:35 4562.959961 T:1963397120  NOTICE: CDVDPlayer::CloseFile()
21:46:35 4562.959961 T:1963397120  NOTICE: DVDPlayer: waiting for threads to exit
21:46:35 4562.960449 T:1963397120  NOTICE: DVDPlayer: finished waiting
21:46:35 4562.960449 T:1963397120  NOTICE: CDVDPlayer::CloseFile()
21:46:35 4562.960449 T:1963397120  NOTICE: DVDPlayer: waiting for threads to exit
21:46:35 4562.960449 T:1963397120  NOTICE: DVDPlayer: finished waiting

```

Under the link: http://192.168.1.5:8080/audio/48f250c6-b5a2-44e8-9946-49a0d96c6ccb I am getting 404 http code from jetty.

**Comment by lolodomo** [comment]
@rapiertg : it is a URL from the openHAB internal proxy.
@watou : that's probably for you ;)

**Comment by watou** [comment]
@lolodomo I don't recognize that URI, but all proxy URIs should start with `/proxy`.

**Comment by lolodomo** [comment]
Sorry for my mismatch, I think it is just an URL for audio delivered by openHAB.

**Comment by lolodomo** [comment]
@rapiertg : this URL is delivered by the openHAB audio servlet.
The kodi audio sink seems to not define a duration after which the servlet will stop to serve the file: https://github.com/openhab/openhab2-addons/blob/213f4d68103218612886242452168de3bdf63870/addons/binding/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/KodiAudioSink.java#L74

**Comment by kaikreuzer** [comment]
If no duration is specified, the AudioServlet will serve the stream exactly once, afterwards you will see a 404. Not sure if Kodi requests the same stream multiple times?

**Comment by lolodomo** [comment]
This could be checked by replacing in the Kodi binding for testing purpose:
`String relativeUrl = audioHTTPServer.serve(audioStream);`
by 
`String relativeUrl = audioHTTPServer.serve(audioStream, 300);`

**Comment by lolodomo** [comment]
@kaikreuzer : what not allowing systematically a multiple access to the file through the servlet and setting a duration of 1 hour (for example) when it is not set by the audio sink ?

**Comment by kaikreuzer** [comment]
Well, it is fully up to the sink to decide what it needs. Why keep 100 streams in memory for an hour, if not needed at all? And also serving it without authentication to who ever wants to access it (might be text-to-speech with private info).

**Comment by lolodomo** [comment]
I said 1 hour but it could be few minutes. The difficulty for any binding is to know the duration of a file and the problem is common to all bindings.
I am trying to verify that (with the Chromecast binding) but the current way it is implemented by the audio servlet could be a problem with the Kodi and the Chromecast bindings. The only binding defining a duration is the Sonos binding.

**Comment by lolodomo** [comment]
@rapiertg : a similar fix was just proposed for the Onlyo binding and the Chromecast binding. I will not be surprised that the same fix is required for the Kodi binding (fix of the audio sink to allow multiple access) to the audio file.

**Comment by kaikreuzer** [comment]
I actually doubt that Onkyo, Chromecast and Kodi all do multiple HTTP requests for the very same stream - I think it is rather an odd behavior that Sonos does that.

So instead of applying an ugly workaround to all of those bindings, I think we should have a closer look at the AudioServlet, if this needs a fix.

Does anyone actually SEE multiple requests being done?

**Comment by mhilbush** [comment]
> I think it is rather an odd behavior that Sonos does that

Perhaps so.   Are these two log entries an indication that the stream is being requested twice?  If so, I suspect the LMS (squeezebox server) and the player both are requesting the stream.
```
2017-01-30 07:02:39.335 [DEBUG] [ome.core.audio.internal.AudioServlet] - Stream to serve is e5004202-b33b-4753-a8db-373654f271ff
2017-01-30 07:02:39.398 [DEBUG] [ome.core.audio.internal.AudioServlet] - Stream to serve is e5004202-b33b-4753-a8db-373654f271ff
```

**Comment by okuehn** [comment]
> Does anyone actually SEE multiple requests being done?

i have actually the same issue while implementing some tts to my openhab using kodi as audio sink.
below the log from kodi:
```
23:30:48.187 T:139766112691968    INFO: easy_aquire - Created session to http://192.168.205.50
23:30:48.249 T:139769523907008   DEBUG: CCurlFile::GetMimeType - http://192.168.205.50:8081/audio/9f2177ee-fb5d-498f-833d-8c94aa2634ac -> failed
23:30:48.252 T:139769523907008   DEBUG: Loading settings for http://192.168.205.50:8081/audio/9f2177ee-fb5d-498f-833d-8c94aa2634ac
23:30:48.252 T:139769523907008   DEBUG: CPlayerCoreFactory::GetPlayers(http://192.168.205.50:8081/audio/9f2177ee-fb5d-498f-833d-8c94aa2634ac)
23:30:48.254 T:139769523907008  NOTICE: VideoPlayer: Opening: http://192.168.205.50:8081/audio/9f2177ee-fb5d-498f-833d-8c94aa2634ac
23:30:48.259 T:139769523907008   DEBUG: CCurlFile::GetMimeType - http://192.168.205.50:8081/audio/9f2177ee-fb5d-498f-833d-8c94aa2634ac -> failed
23:30:48.259 T:139768675923712   DEBUG: CurlFile::Open(0x7f1e6e4765f0) http://192.168.205.50:8081/audio/9f2177ee-fb5d-498f-833d-8c94aa2634ac
23:30:48.265 T:139768675923712   ERROR: CCurlFile::Open failed with code 404 for http://192.168.205.50:8081/audio/9f2177ee-fb5d-498f-833d-8c94aa2634ac
```
and from openhab
```
2017-02-07 23:30:48.193 [DEBUG] [ome.core.audio.internal.AudioServlet] - Stream to serve is 9f2177ee-fb5d-498f-833d-8c94aa2634ac
2017-02-07 23:30:48.247 [DEBUG] [ome.core.audio.internal.AudioServlet] - Received request for invalid stream id at /audio/9f2177ee-fb5d-498f-833d-8c94aa2634ac
2017-02-07 23:30:48.257 [DEBUG] [ome.core.audio.internal.AudioServlet] - Received request for invalid stream id at /audio/9f2177ee-fb5d-498f-833d-8c94aa2634ac
2017-02-07 23:30:48.262 [DEBUG] [ome.core.audio.internal.AudioServlet] - Received request for invalid stream id at /audio/9f2177ee-fb5d-498f-833d-8c94aa2634ac
2017-02-07 23:30:48.268 [DEBUG] [ome.core.audio.internal.AudioServlet] - Received request for invalid stream id at /audio/9f2177ee-fb5d-498f-833d-8c94aa2634ac
```

**Comment by lolodomo** [comment]
@kaikreuzer : do you still doubt about the need to apply the same fix to the kodi binding ?
If not, I can provide the fix.

**Comment by kaikreuzer** [comment]
No doubt, looking forward to a fix - thanks!
