### ISSUE TITLE
[homematic] State of variable only pushed to CCU2, when item is switched manually in OH2

### ISSUE THREAD

**Issue by thefox73** [openhab/openhab2-addons#1794]
I'm running OH2 RC1 and apparently the status of a variable is not published correctly to the CCU2 via Gateway Extras.
I use the network binding to detect, if a device is online or not. I assigned the switch item to the homematic variable sysvarpresence in the thing Gateway Extras in OH2.
If I now activate the OH item manually via PaperUI, the status is updated to the CCU2 correctly.
But if the status is set by the network binding, then this update is not pushed to the CCU2.
I can see the updates in the PaperUI, but these changes are not published to CCU2

**Comment by thefox73** [comment]
To specify the issue:
Via HABmin I can see, that the switch item is assigned correctly against the Gateway-Extra thing.
And within the Gateway-Extras I can see the switch item moving from on to off and vice versa, when the network binding changes the status of the switch item. But these changes are not published against the CCU2.
If I switch the item manually within the Gateway-Extras thing, then these change is published against the CCU2, So apparently it makes a difference for the Gateway-Extras if the switch is status is changed by the network binding or manually.

**Comment by MHerbst** [comment]
> I use the network binding to detect, if a device is online or not. I assigned the switch item to the homematic variable sysvarpresence in the thing Gateway Extras in OH2.

How did you implement this? If you used a rule, can you post the coding here. The communication between the binding and the CCU works correctly, so it probably this is a problem of the binding itself.

**Comment by thefox73** [comment]
I implemented this without any rules.
I created a switch item, which I assigned against the online channel of the network thing.
So, when the binding detects a device in the local network, this switch is set to ON. This works perfectly.
In the next step I assigned the same switch item against the sysvarpresence variable in the thing Gateway-Extras and I assumed that this item would set the HM variable to on as well, when the network binding detects the devices. But this does not work. 
When I open HABmin and navigate to the Gateway-Extras thing, I can see the switch item which is handled by the network binding. And when the network binding sets the switch to ON, I can see this in the Gateway-Extras, but it's not published to the CCU2.
But when I switch the item directly in the Gateway-Extras, this action is pushed to the CCU2 immediately.
Maybe I do not understand the function of the Gateway-Extras and this is not the way how I have to implement it. But if it works switching the item manually, it should work using a binding as trigger, too.
Or am I wrong?

**Comment by MHerbst** [comment]
The idea of linking items this way is actually obvious. Maybe too obvious :-). I have tested it in my environment and it seems that the state change of the item by the network add-on does not trigger a state change of the  Homematic channel that is also connected to this item.

@kaikreuzer what do you thing? Should this work?

**Comment by thefox73** [comment]
I tried it with non HM item and unfortunately it seems not to work.
Again it's only possible to trigger the item manually via HABmin. Then linked item is switched, too.
But if one item is trigerred from "outside", the linked item is not triggered.

**Comment by kaikreuzer** [comment]
> @kaikreuzer what do you thing? Should this work?

Yes, both commands and state update events are provided to all linked channels. Normally, channels only react on commands (which ask them to actively do something), while ignoring state events.
But for a feature like "sysvarpresence", which more or less should be an "external representation" of openHAB's presence state, I think it would make sense that the channel updates the state in Homematic, when it is noticed that the state in openHAB has changed.

So deciding whether state updates should be considered should be done by finding the right perspective: Is it a sensor, where the only the binding knows the truth about its state? Then the binding should send the state updates. Is it a piece of information that is primarily maintained in openHAB (like the presence state), then it should be openHAB which sends the state updates to the binding (which hence needs to consider them).

@gerrieg Is this something that could be applied in the binding? I know that it might be tricky as most channels are automatically derived from their XML descriptions?

**Comment by MHerbst** [comment]
@thefox73 As a bypass you could use the Rule editor in PaperUI and create two simple rules. 

Rule 1:
Is executed when the item state of the network device changes to "ON" and the executes a command to set the item connected with Homematic variable to "ON"

Rule 2:
same as the first rule but for "OFF".

**Comment by thefox73** [comment]
@MHerbst Thanks for the hint. This is exactly what I already did with a text based rule and it works.

But it would be very smart, if the binding could be enhanced in the way Kai suggested.
We will see ;-)

**Comment by gerrieg** [comment]
Sending variable updates to the Homematic gateway and not only commands makes sense, but for the devices it's hard to decide which channel should be send due the mass on devices and channels.

I will implement this for variables, but if it's really necessary to have this for devices too, i would let the user decide and would add a channel property like ```sendOnUpdate``` or something like that.

**Comment by thefox73** [comment]
That would be great.
What about sending variable updates from the CCU2 to OH?

I created a variable in HM, which pops up in the the Gateway-Extras. I linked this channel to a OH item.
In the next step I created a rule to switch a device on/off via this item.
On HM side the variable is set by a motion detector.
If motion is detected, the variable is switched, but in OH nothing happens.

Will this work as well, after you implemented the new functionality?

Btw: I would appreciate to have this property "sendOnUpdate" ;-)

**Comment by gerrieg** [comment]
No, there is no event in the CCU when a variable changes so it's impossible to detect this automatically. To refresh all variables, you have to send a REFRESH command to one variable.

But why don't you use the motion detector itself in OH? Events from devices are published so you don't need the detour via the variable to do something in OH.

**Comment by thefox73** [comment]
Okay, thank you.
Using the motion detector was just for testing.

**Comment by ptweety** [comment]
How can I send such a REFRESH to a specific var?

**Comment by gerrieg** [comment]
In the console for example:
```
smarthome send {VARIABLE_ITEM_NAME} REFRESH
```
this triggers a reload of all variables

**Comment by MHerbst** [comment]
In my opinion we can close this issue. What do you think @gerrieg ?

**Comment by gerrieg** [comment]
yes, you can close it
