### ISSUE TITLE
HomeMatic devices with CONFIG_PENDING

### ISSUE THREAD

**Issue by sagittarius0815** [openhab/openhab2-addons#1796]
I have some HomeMatic devices in state CONFIG_PENDING.

These devices are shown in CCU1 WebUI in same state for a few years :) and that never was a problem.
I was not able to solve the problem with configuration data in CCU1.
It never was a problem meens, that all devices and scripts are working in CCU1 as expected. And I have a running OpenHAB1.8 system with a working homematic 1.8 binding.

But with OH2 these devices are deteced as CONFIG_PENDING=true: 
`2017-01-29 17:44:44.599 [DEBUG] [ternal.communicator.HomematicGateway] - Received new (Boolean) value 'true' for 'HEQ0031687:0#CONFIG_PENDING' from gateway with id 'ccu'`
and the thing state in OH2 is "INITIALIZING".
In this state devices are not working:
`2017-01-29 17:44:58.760 [ERROR] [ematic.handler.HomematicThingHandler] - Illegal status INITIALIZING. Bindings only may set UNKNOWN, ONLINE, OFFLINE or REMOVED.`

Is there a way to ignore the CONFIG_PENDING=true and bring the devices to state "ONLINE"?

I have a lot of other HomeMatic devices with no CONFIG_PENDING, they are ONLINE and working in OH2 as expected.

**Comment by gowi** [comment]
Same problem here. When there is a device with pending config data, the exception `[ERROR] [ematic.handler.HomematicThingHandler] - Illegal status INITIALIZING. Bindings only may set UNKNOWN, ONLINE, OFFLINE or REMOVED.` is raised

**Comment by sagittarius0815** [comment]
I agree, that it is a good idea to set device state to "initializing" during device configuration is pending.

But at least for CCU1 it may be that devices are remaining in configuration pending state and user is not able to solve this situation without a complete CCU1 system reset. And a reset is not needed because devices are working,

**Comment by kaikreuzer** [comment]
> I agree, that it is a good idea to set device state to "initializing" during device configuration is pending.

No, that's not a good idea, because INITIALIZING is a status that describes the handler, not the handled device.

For config_pending, there is a specific status already defined: ONLINE.CONFIGURATION_PENDING, see [here](https://github.com/eclipse/smarthome/blob/7e6048adaa94790604045c76576d354a0ccc28ba/docs/documentation/concepts/things.md#status-details).

@gerrieg Please note that bindings MUST NEVER set the status to INITIALIZING.

**Comment by gerrieg** [comment]
fixed with https://github.com/openhab/openhab2-addons/pull/1622

**Comment by MHerbst** [comment]
@sagittarius0815 can you retest it with the latest OH snapshot and close this issue if it is solved?

**Comment by sagittarius0815** [comment]
Issue solved with snapshot 2.1
