### ISSUE TITLE
Map Transformation gives error 500 when configure Things

### ISSUE THREAD

**Issue by tnemrap** [openhab/openhab2-addons#1797]
When i install Harmonyhub i can configure Things but when i install Map Transformation i receive error 500 when i try to configure Harmonyhub Things.

/mike

**Comment by digitaldan** [comment]
Can you post the errors, maybe a log file?  Also are your Harmony items using the map transformation?

**Comment by tnemrap** [comment]
Now i see that it is not in the Harmonyhub binding. It must be in the Map Transformation.
When i install Map Transformation habpanel and Network binding does not work either.

**Comment by digitaldan** [comment]
Would you then close issue this or at least rename it please?

**Comment by tnemrap** [comment]
The problem was solved when i replaced all %d with %.0f in my items files.
