### ISSUE TITLE
ZWave Binding

### ISSUE THREAD

**Issue by cdjackson** [openhab/openhab2-addons#180]
As commented on the list, I've now got the zwave binding running under OH2/ESH but need some additional features in the core to support parameterising channels.

**Comment by GarethFox** [comment]
Hi,

Thanks a lot for your hard work !
I am currently testing a large panel of open source solutions for home automation compatible w/ rpi 2.
I have been running on openhab earlier this week, and getting a lot of interest on it.
I am using the zme uzb1 zwave controller and had some issues runing it properly under zwave binding 1.6.2 (sometimes the controller green w/ some manufacturer information at start, sometimes red but still inclusions possible or a fibaro door sensor in grey_some trouble to create the network compare to the ozw control panel)
I have been trying to mount on an empty rpi 2 openhab2 and habmin2 today w/ the latest releases. the server is running well, and the acces to the habmin page is ok.
I have put into /addons files org.openhab.binding.zwave-1.7.0-SNAPSHOT.jar and 
org.openhab.ui.habmin-2.0.0-SNAPSHOT-0.0.11.jar.
After a reboot, going to the zwave configuration page under habmin I have no device found, the command set the controller to default gives error sending action request to server, the command for adding device gives the same. I have done it w/ an other stick but no changes.
I am wondering now if there is a way to indicate the /dev/ttyACM0 path into a config.cfg file like it was asked to be done for operating it properly under openhab1 ?
Maybe I am missing something...I know it still under development, thank you in advance for your time.

In the meantime, I'll give an other try with openhab1 running the 1.7 zwave binding and see how it behaves with the zme stick.

sincerely yours,

**Comment by cdjackson** [comment]
Yes - you need a config file. If memory serves me correctly, it should be in the /config/services folder, and it should be called zwave.cfg and should contain the information that was previously in the openhab.cfg file in OH1.

**Comment by GarethFox** [comment]
Okay,

Thx for the quick reply !
I gave a try copying the config.cfg from oh1, uncommenting and adding the zwave:port=/dev/ttyACM0, then saved it as /opt/openhab2/conf/services/zwave.cfg.
No changes after a reboot and a a logged access to the habmin zwave config page.
For a ACM0 device, do we have to add 'openhab' user to 'dialout' group as asked for oh1 ? 
Actually, an -$ id openhab command tells no user existing. Should I create and add it to the group w/ a -$ sudo useradd -g dialout openhab or maybe in the case doing it for a openhab2 user ?

**Comment by cdjackson** [comment]
I guess this is specific to the configuration of the PI - I would suggest that you ask the question on the mailing list rather than here as more people will see it.

**Comment by kaikreuzer** [comment]
> I gave a try copying the config.cfg from oh1, uncommenting and adding the zwave:port=/dev/ttyACM0, then saved it as /opt/openhab2/conf/services/zwave.cfg.

You also need to remove the "zwave:" prefix of every entry, i.e. your zwave.cfg file should only have ```port=/dev/ttyACM0```.

**Comment by GarethFox** [comment]
Hi !

Thx for the tips !
I wanted to try it this morning, but unfortunately, without any explication...the habmin web page is down...
I have an open access on http://openhabserver:8080 with classic or paper ui etc,..but the http://openhabserver:8080/habmin/index.html does not work.
I have made a brand new installation, but no idea of what is goin on... so I can't tell if it works well with this modification on the cfg file.
I remember that it used to have a pop-up page at the opening of habmin2, and I am now wondering if there is not a kind of internet check step that is not working properly today and avoid the access to habmin2 ?
I would be glad to continue the topic on the mailing list if you would be kind enough to redirect me toward it.

Have a nice day guys !

**Comment by cdjackson** [comment]
The mailing list is here -:
https://groups.google.com/forum/#!forum/openhab2
I assume you already have the OH1 zwave binding in the addons folder? This is required for the HABmin JAR to load. I'm not sure how you're accessing your system (remotely?) but I don't think there should be anything that should block HABmin as it's on the same TCP address/port.

**Comment by xsnrg** [comment]
@cdjackson We can probably close this one as it is merged now, yes?
