### ISSUE TITLE
Chromecast: after the playback of a notification, the cast application should disappear

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab2-addons#1802]
If you trigger a notification using the chromecast audio sink, a cast application is loaded to play the notification. At the end of the playback, the application should disappear and you should return to your previous application.

**Comment by lolodomo** [comment]
I tried to fix that issue (using chromecast.`stopApp()`) with no success :(

**Comment by lolodomo** [comment]
@kaikreuzer @tavalin @maggu2810 : did you already try using stopApp() with success ?

When I cast an audio file with the binding, a new application is launched in Android TV, the audio file is played and at the end, the application is not closed (I only see a small Cast icon at the center of the image). Is it possible to request a return to the previous running application ? Is it what stopApp() should do ?
Or should I ask for the current application before I launch the new default application, and then start it again at the end of the notification ?

**Comment by lolodomo** [comment]
stopApp() is in fact working well. I just have to call it at the right place and right moment.

**Comment by lolodomo** [comment]
Closed by PR #1824

**Comment by maggu2810** [comment]
> @maggu2810 : did you already try using stopApp() with success ?

Do not remember, sorry.
After the code has been taken over, I stopped to work on.
