### ISSUE TITLE
avmfritz - incorrect readings with multiple 546E

### ISSUE THREAD

**Issue by ugar-ugar** [openhab/openhab2-addons#1806]
Hello,
i am using 2 Powerline 546E Adapters.  (IP : x.x.x.60, x.x.x.62).
The readings (Energy, Power, Switch-State) are not correct assigned to the device:
Device x.x.x.60 has readings of Device x.x.x.62
Device x.x.x.62 has readings of Device x.x.x.60

The assignement of the switch-action is OK:
Switching Device x.x.x.60 turns the socket of x.x.x.60 off, 
Switching Device x.x.x.62 turns the socket of x.x.x.62 off, 

Please contact me if further debigging or testing is needed.

**Comment by cweitkamp** [comment]
Hey there, I am going to look into this. Please post an abstract of your *.things and *.items files. Or a screenshot if configured over the UIs.

**Comment by cweitkamp** [comment]
Hey there, another question. Are you using the Powerline devices without a FRITZ!Box? Did you add them over PaperUI or not? Can you provide some log files?

**Comment by cweitkamp** [comment]
@ugar-ugar Do you like to test and confirm?
