### ISSUE TITLE
Optimization of units in Tesla binding

### ISSUE THREAD

**Issue by benderl** [openhab/openhab2-addons#1807]
I upgraded to OpenHAB2 just e few weeks ago and tried the new Tesla binding. I noticed that the range units (kilometers or miles) in the things properties are not used in any way. So in regions with metric units the numbers give a nice mixture of km (Odometer) and mil (Charge Rate in m/h).
Also some channels are displayed with the unit "km|miles" in PaperUI. This is quite irritating and should be changed, if the conversion is done in the binding code.

I would suggest to improve the binding by interpreting the parameters

- chargerateunits
- distanceunits

and calculate the affected values right in the binding. So the user sees all values in the expected units without the need for calculations.

Last but not least, the channel "Charge Rate" creates an item of type string as default. This should be a number item.

I had a look at the binding source code, but am not really familiar with Java.

**Comment by kaikreuzer** [comment]
@kgoderis Could you have a look?

**Comment by kgoderis** [comment]
@benderl I also noticed this and had it on my to-fix list

**Comment by kgoderis** [comment]
@benderl Changing the unit displayed in the UI can not be changed at the time being, and depends on the inclusion of https://github.com/eclipse/smarthome/pull/1857

**Comment by benderl** [comment]
@kgoderis I will have a detailed look at the weekend.
The different ranges ("ideal", "Rated") are quite irritating, but this is not related to the binding.

**Comment by benderl** [comment]
Sorry for my late reply, but I am quite busy these days.
The "Charge Rate" seems to be the only item with wrong units. So this has already been fixed by your commit.
Well done!
