### ISSUE TITLE
New install of addons2 source is not compling

### ISSUE THREAD

**Issue by pinkfish** [openhab/openhab2-addons#1811]
Gives this error.  Is there something wrong with the jupnp repository?

 mvn -o clean install[INFO] Scanning for projects...
[INFO] Computing target platform for MavenProject: org.openhab.binding:org.openhab.binding.astro:2.0.0-SNAPSHOT @ /usr/local/home/ddt/openhab/git/addons-2/openhab2/addons/binding/org.openhab.binding.astro/pom.xml
[INFO] Adding repository http://download.eclipse.org/modeling/tmf/xtext/updates/releases/maintenance/R201407030533
[INFO] Adding repository http://download.eclipse.org/modeling/emf/emf/updates/2.10/core/R201405190339
[INFO] Adding repository http://download.eclipse.org/jetty/updates/jetty-bundles-9.x/9.2.9.v20150224
[INFO] Adding repository http://download.eclipse.org/releases/luna/201406250900
[INFO] Adding repository http://download.eclipse.org/eclipse/updates/4.4/R-4.4.2-201502041700
[INFO] Adding repository http://download.eclipse.org/tools/orbit/downloads/drops/R20140525021250/repository
[INFO] Adding repository http://www.openhab.org/jupnp/update-site
[ERROR] Failed to resolve target definition /usr/local/home/ddt/openhab/git/addons-2/openhab2/targetplatform/openhab.target: Failed to load p2 metadata repository from location http://www.openhab.org/jupnp/update-site/: Repository system is offline and no local cache available for http://www.openhab.org/jupnp/update-site -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException

**Comment by kaikreuzer** [comment]
http://www.openhab.org/jupnp/update-site isn't referenced anywhere in the build since more than a year...
Is it possible that you still have something old in your local maven repo that might be used by Maven? Please try it with a clean local repo - I would expect the build to succeed then.

**Comment by pinkfish** [comment]
This is a completely clean install.  I didn't have openhab, or even maven, installed on this machine before I tried to compile this yesterday.  I did a mvn -o clean install and it still gives these errors.

**Comment by pinkfish** [comment]
Tried again to clone from scratch again, it still fails, although differently this time.  It says:
Failed tests: 
  SysteminfoOSGiTest.assert channel cpu#load is updated:292->this$3$testItemStateIsUpdated:-1->testItemStateIsUpdated:170->testItemState:178->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:199 Thing status detail is {HANDLER_INITIALIZING_ERROR} with description {Thing can not be initialized!}
Expected: is <ONLINE>
     but: was <OFFLINE>
  SysteminfoOSGiTest.assert channel cpu#threads is updated:328->this$3$testItemStateIsUpdated:-1->testItemStateIsUpdated:170->testItemState:178->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:199 Thing status detail is {HANDLER_INITIALIZING_ERROR} with description {Thing can not be initialized!}
Expected: is <ONLINE>
     but: was <OFFLINE>
  SysteminfoOSGiTest.assert channel memory#available is updated:364->this$3$testItemStateIsUpdated:-1->testItemStateIsUpdated:170->testItemState:178->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:199 Thing status detail is {HANDLER_INITIALIZING_ERROR} with description {Thing can not be initialized!}
Expected: is <ONLINE>
     but: was <OFFLINE>
  SysteminfoOSGiTest.test discovery with invalid hostname:710->testDiscoveryService:766->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:199 Thing is not initilized.
Expected: is <ONLINE>
     but: was <OFFLINE>
  SysteminfoOSGiTest.assert channel memory#availablePercent is updated:391->this$3$testItemStateIsUpdated:-1->testItemStateIsUpdated:170->testItemState:178->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:199 Thing status detail is {HANDLER_INITIALIZING_ERROR} with description {Thing can not be initialized!}
Expected: is <ONLINE>
     but: was <OFFLINE>
  SysteminfoOSGiTest.test thing handles channel priority change:846->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:199 
Expected: is <true>
     but: was <false>
  SysteminfoOSGiTest.assert channel sensors#cpuVoltage is updated:551->this$3$testItemStateIsUpdated:-1->testItemStateIsUpdated:170->testItemState:178->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:199 Thing status detail is {HANDLER_INITIALIZING_ERROR} with description {Thing can not be initialized!}
Expected: is <ONLINE>
     but: was <OFFLINE>
  SysteminfoOSGiTest.assert channel cpu#description is updated:346->this$3$testItemStateIsUpdated:-1->testItemStateIsUpdated:170->testItemState:178->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:199 Thing status detail is {HANDLER_INITIALIZING_ERROR} with description {Thing can not be initialized!}
Expected: is <ONLINE>
     but: was <OFFLINE>
  SysteminfoOSGiTest.test discovery with unresolved hostname:726->testDiscoveryService:766->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:199 Thing is not initilized.
Expected: is <ONLINE>
     but: was <OFFLINE>
  SysteminfoOSGiTest.assert medium priority channel is updated:261->this$3$testItemStateIsUpdated:-1->testItemStateIsUpdated:170->testItemState:178->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:199 Thing status detail is {HANDLER_INITIALIZING_ERROR} with description {Thing can not be initialized!}
Expected: is <ONLINE>
     but: was <OFFLINE>
  SysteminfoOSGiTest.assert channel cpu#load15 is updated:319->this$3$testItemStateIsUpdated:-1->testItemStateIsUpdated:170->testItemState:178->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:199 Thing status detail is {HANDLER_INITIALIZING_ERROR} with description {Thing can not be initialized!}
Expected: is <ONLINE>
     but: was <OFFLINE>
  SysteminfoOSGiTest.assert channel cpu#name is updated:355->this$3$testItemStateIsUpdated:-1->testItemStateIsUpdated:170->testItemState:178->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:199 Thing status detail is {HANDLER_INITIALIZING_ERROR} with description {Thing can not be initialized!}
Expected: is <ONLINE>
     but: was <OFFLINE>
  SysteminfoOSGiTest.assert channel cpu#uptime is updated:337->this$3$testItemStateIsUpdated:-1->testItemStateIsUpdated:170->testItemState:178->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:199 Thing status detail is {HANDLER_INITIALIZING_ERROR} with description {Thing can not be initialized!}
Expected: is <ONLINE>
     but: was <OFFLINE>
  SysteminfoOSGiTest.assert state of not existing device is not updated:271->this$3$testItemStateIsNull:-1->testItemStateIsNull:174->testItemState:178->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:199 Thing status detail is {HANDLER_INITIALIZING_ERROR} with description {Thing can not be initialized!}
Expected: is <ONLINE>
     but: was <OFFLINE>
  SysteminfoOSGiTest.test discovery with empty hostname string:734->testDiscoveryService:766->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:199 Thing is not initilized.
Expected: is <ONLINE>
     but: was <OFFLINE>
  SysteminfoOSGiTest.assert channel memory#used is updated:373->this$3$testItemStateIsUpdated:-1->testItemStateIsUpdated:170->testItemState:178->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:199 Thing status detail is {HANDLER_INITIALIZING_ERROR} with description {Thing can not be initialized!}
Expected: is <ONLINE>
     but: was <OFFLINE>
  SysteminfoOSGiTest.assert channel memory#total is updated:382->this$3$testItemStateIsUpdated:-1->testItemStateIsUpdated:170->testItemState:178->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:199 Thing status detail is {HANDLER_INITIALIZING_ERROR} with description {Thing can not be initialized!}
Expected: is <ONLINE>
     but: was <OFFLINE>
  SysteminfoOSGiTest.test discovery with valid hostname:718->testDiscoveryService:766->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:199 Thing is not initilized.
Expected: is <ONLINE>
     but: was <OFFLINE>
  SysteminfoOSGiTest.assert channel cpu#load1 is updated:301->this$3$testItemStateIsUpdated:-1->testItemStateIsUpdated:170->testItemState:178->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:199 Thing status detail is {HANDLER_INITIALIZING_ERROR} with description {Thing can not be initialized!}
Expected: is <ONLINE>
     but: was <OFFLINE>
  SysteminfoOSGiTest.assert channel cpu#load5 is updated:310->this$3$testItemStateIsUpdated:-1->testItemStateIsUpdated:170->testItemState:178->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:199 Thing status detail is {HANDLER_INITIALIZING_ERROR} with description {Thing can not be initialized!}
Expected: is <ONLINE>
     but: was <OFFLINE>

Tests run: 22, Failures: 20, Errors: 0, Skipped: 1
****

**Comment by kaikreuzer** [comment]
These tests sometimes fail (might also be due to the OS they are executed on).
Run the build with the `-DskipTest=true` option.
For further support, I'd recommend our forum at https://community.openhab.org/
