### ISSUE TITLE
Please add state to Kodi Binding

### ISSUE THREAD

**Issue by chrissfoot** [openhab/openhab2-addons#1816]
I currently use the xbmc binding to dim lights when my player changes from stop/pause to play (and back again). This does not appear to be possible with the new addon as it does not have the state channel that the xbmc addon provides

**Comment by tavalin** [comment]
Can't you use the `control` channel for this?

The channel documentation is [here](https://github.com/openhab/openhab2-addons/tree/master/addons/binding/org.openhab.binding.kodi#channels).

You would have an item such as:

`Player kodiState {channel="kodi:kodi:myKodi:control"}`

Then a rule like:

```
rule "Kodi change state"
when 
  Item kodiState changed to PLAY
then 
 // dim lights
end
```

**Comment by chrissfoot** [comment]
Yes, you can.... i'm an idiot!
