### ISSUE TITLE
How to Configured Habpanel  in Eclipse Smart Home

### ISSUE THREAD

**Issue by amarpulli544** [openhab/openhab2-addons#1821]
Hello,
I would like to know, how to  habpanel configured in eclipse smart home. What are things required for habpanel configured in ESH. As for my knowledge cloning the habpanel package from git repository and then extract here smarthome-master/extension/ui/ in smart home project, then compiled by using "mvn clean install" then loaded into project. It doesn't work for me. 
Thanks 
Amar

**Comment by kaikreuzer** [comment]
Please use our forum at https://community.openhab.org/ for such questions, the issue tracker should be used for bug/feature tracking.
