### ISSUE TITLE
PaperUI - Purpose of Item Type Dropdown

### ISSUE THREAD

**Issue by lsafelix75** [openhab/openhab2-addons#1827]
Hi,

From the Paper UI --> Configuration --> Items --> (edit) item, it allows me to choose an item type for an item. What is the real intention of being a dropdown? As far as I know its type (and the only one) has already been fixed or defined in ESH-INF's thing .xml within <item-type> </item-type>, and we can only define 1 type instead of multiple types?

In my situation, i like the dropdown list for the item-type BUT it should not tie to ESH-INF's xml. Just like xxx.item, it allows me to redefine item-type of an item that links to a specific thing's channel through mapping transformation (e.g. Contact device1 "Status [MAP(status.map):%s]"

**Comment by kaikreuzer** [comment]
This is not a bug report for any openHAB 2 add-on in this repo, is it?
If you have questions about general binding development, best go to https://www.eclipse.org/forums/index.php/f/271/.
