### ISSUE TITLE
[systeminfo] Available storage gets only updated on start of openHAB 2

### ISSUE THREAD

**Issue by adb76** [openhab/openhab2-addons#1830]
I recognized, that after a restart of openHAB 2 on my Debian Jessie server the channels "...storage#available" or "storage#availablePercent" were only update once on startup. Later even when creating 1 GB files on my server the values remained the same. After looking into the source code I think I've found the problem:

In the file OshiSysteminfo.java the variable "fileStores" saves an object "OSFileStore" which is in the constructor initialized via "operatingSystem.getFileSystem().getFileStores();"
```
public class OshiSysteminfo implements SysteminfoInterface {

    private OperatingSystem operatingSystem;
    private NetworkIF[] networks;
    private Display[] displays;
    private OSFileStore[] fileStores;
    private GlobalMemory memory;
    private PowerSource[] powerSources;
    private CentralProcessor cpu;
    private HWDiskStore[] drives;
    private Sensors sensors;

    public final static int PRECISION_AFTER_DECIMAl_SIGN = 1;

    /**
     * Some of the methods used in this constructor execute native code and require execute permissions
     *
     */
    public OshiSysteminfo() {
        SystemInfo systemInfo = new SystemInfo();
        HardwareAbstractionLayer hal = systemInfo.getHardware();
        operatingSystem = systemInfo.getOperatingSystem();
        displays = hal.getDisplays();
        fileStores = operatingSystem.getFileSystem().getFileStores();
        memory = hal.getMemory();
        powerSources = hal.getPowerSources();
        cpu = hal.getProcessor();
        sensors = hal.getSensors();
        networks = hal.getNetworkIFs();
        drives = hal.getDiskStores();
}
```
In my understanding "fileStores" is only created once at startup of openHAB.

In the method
```
public DecimalType getStorageUsed(int index) throws DeviceNotFoundException {
        OSFileStore fileStore = (OSFileStore) getDevice(fileStores, index);
        long totalSpace = fileStore.getTotalSpace();
        long freeSpace = fileStore.getUsableSpace();
        long usedSpace = totalSpace - freeSpace;
        usedSpace = getSizeInMB(usedSpace);
        return new DecimalType(usedSpace);
}
```

"getDevice(fileStores, index)" is use to get one concret volume "fileStore". With "fileStore.getUsableSpace();" the assumption is, that the **current** used space of that device is returned.

But when looking into "https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/software/os/OSFileStore.java "getUsableSpace()" only returns the value of the OSFileStore object:

```
  public long getUsableSpace() {
        return this.usableSpace;
}

```

But the OSFileStore object "filestore" we are working on was only created once on startup and therefor will always show the initial value! 

So, from my point of view of refresh of the object OSFilestore is necessary to update the current storage usage.

**Comment by svilenvul** [comment]
Very good observation, it seems that other channels are affected as well - https://github.com/oshi/oshi/issues/310.

I will update the binding with the required changes.
