### ISSUE TITLE
[Kodi] Add additional channels to stop the player and close Kodi

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab2-addons#1833]
See discussions

- https://github.com/eclipse/smarthome/issues/2741
- https://community.openhab.org/t/openhab-2-kodi/21941/3

There was also request/discussion about adding an option to close Kodi

**Comment by lolodomo** [comment]
What about merged PR #1698 ?

**Comment by MHerbst** [comment]
I only searched in the open issues ....
