### ISSUE TITLE
Plugwise binding

### ISSUE THREAD

**Issue by wborn** [openhab/openhab2-addons#1835]
It would be nice to have a native openHAB 2.0 Plugwise binding. As I've seen no one else work on this so far, I'll be putting some effort in creating a native binding myself.

Here's my list of ideas for the openHAB 2.0 version of the Plugwise binding:
* reuse openHAB 1.x Plugwise protocol messages
* stop using Quartz, Joda-Time in the binding
* use a Bridge for the Stick and Things for Circles, Scans, Senses etc.
* add support for retrieving historic data from Circles, Scans, Senses

I'm still undecided on using:
* channels for the various timestamps that are also in the OH1 binding version, it might be better to keep track of these timestamps using rules/persistence
* channel groups, initially they might be overkill, but when retrieving historic data is done via channels I think it is better to create channel groups. This subject touches the discussion in this [community thread](https://community.openhab.org/t/howto-integrate-a-device-returning-a-history-of-measurements/21127/2).
* trigger channels for Scan motion events and Switch button state changes

Good ideas are always welcome. :-)

It would also be nice if someone has insights on reusing OH1 code. Is it okay to copy/paste and refactor away? Should original OH1 @author tags be removed or retained?

**Comment by watou** [comment]
> add support for retrieving historic data from Circles, Scans, Senses

Is this what a binding should do, or could it be a queryable persistence service?

> channels for the various timestamps that are also in the OH1 binding version, it might be better to keep track of these timestamps using rules/persistence

If the `*-stamp` queries are coming back from the remote device, then they might be needed if your binding will obsolete the 1.x binding.  If the binding is generating them or there is no use case for them, maybe they could be dropped.

> Should original OH1 @author tags be removed or retained?

Retained always even when refactoring, copying, etc.  Otherwise one could have the wrong impression about who all the authors are.

**Comment by wborn** [comment]
> Is this what a binding should do, or could it be a queryable persistence service?

Yes it would be more natural when such data can be retrieved using a persistence service. Using channels for this feels like a hacky solution. I'll be starting to implement this when the OH2 binding equals OH1 functionality. Hopefully APIs and examples for this have caught up by then. :-)

> Retained always even when refactoring, copying, etc. Otherwise one could have the wrong impression about who all the authors are.

Retaining @author tags for the protocol files will be easy. It might become fuzzy when bits and pieces of the other files are reused. For those I could do something like `@author <author name> - openHAB 1.x <classname> some additional details`.

**Comment by kaikreuzer** [comment]
> Retaining @author tags for the protocol files will be easy. It might become fuzzy when bits and pieces of the other files are reused.

Whereever you copy a substantial block of code, you should add the author tag as well. No need to reference where you have taken the code from.

BUT, you need to add any additional author as "Also-by" in your commit message. And by doing so, you certify that they are ok with the DCO as well, so you should reach out to all of them to ensure this.

**Comment by wborn** [comment]
> BUT, you need to add any additional author as "Also-by" in your commit message. And by doing so, you certify that they are ok with the DCO as well, so you should reach out to all of them to ensure this.

Is it OK to first create the code (with proper @author tags), ask original authors if they are OK with it and agree to the DCO, and then squash the commit with additional "Also-by" lines? It is a bit of a chicken egg problem.

Before proceeding, I think it is best if @kgoderis can tell us if he approves his original Plugwise Binding code being reused for the openHAB 2 Plugwise Binding.

**Comment by kaikreuzer** [comment]
> Is it OK to first create the code (with proper @author tags), ask original authors if they are OK with it

Yes, as there is usually a very high likelyhood that they are ok (as they already contributed to OH1, but we did not really have a proper contribution management there, so we should enforce it on OH2).

**Comment by kgoderis** [comment]
@wborn Yes, definitely ok to re-use. I do not use the plugwise devices since a long time, so I can not comment to what extend the binding is still compatible with the latest plugwise firmware. If you are an active user, it is best that you take the lead on this binding going forward. With OH2 in mind, the code might look completely different anyways, so do not be/feel bothered by @author tags with my name behind it ;-)

**Comment by wborn** [comment]
> Yes, definitely ok to re-use.

Thanks @kgoderis !

The OH1 Plugwise Binding already works very well for me nowadays after pushing several [improvements](http://docs.openhab.org/addons/bindings/oh1/plugwise/readme.html#openhab-190). :-) The firmware has not been updated for years.

**Comment by wborn** [comment]
By now the new OH2 Plugwise binding has succeeded its OH1 counterpart regarding functionality. OH2 specific functionality such as Thing discovery, i18n support, online/offline states and some properties also play out very nicely. 

This also means that I'm done with reusing parts of the OH1 code. I've added Karel as co-@author in the respective files. In the OH1 code only @kgoderis and myself are listed as @author's. So it would be great if  you can formally approve the way your code is being reused in the OH2 binding version Karel. As well as if you are OK with the DCO. Then I'll add you in an 'Also-by' line.

All work has been squashed into this commit: https://github.com/wborn/openhab2-addons/commit/39d77c5788ccf44f5911463ddaa84c901e3abe3e

These are the files that contain (parts of) your code from OH1 and where you have been added as co-@author:

```
handler/PlugwiseRelayDeviceHandler.java
handler/PlugwiseStickHandler.java
internal/PlugwiseCommunicationHandler.java
internal/PlugwiseDiscoveryService.java
internal/PlugwiseInitializationException.java
internal/protocol/AcknowledgeMessage.java
internal/protocol/CalibrationRequestMessage.java
internal/protocol/CalibrationResponseMessage.java
internal/protocol/ClockGetRequestMessage.java
internal/protocol/ClockGetResponseMessage.java
internal/protocol/ClockSetRequestMessage.java
internal/protocol/field/Energy.java
internal/protocol/field/MessageType.java
internal/protocol/InformationRequestMessage.java
internal/protocol/InformationResponseMessage.java
internal/protocol/MessageFactory.java
internal/protocol/Message.java
internal/protocol/ModuleJoinedNetworkRequestMessage.java
internal/protocol/NetworkResetRequestMessage.java
internal/protocol/NetworkStatusRequestMessage.java
internal/protocol/NetworkStatusResponseMessage.java
internal/protocol/NodeAvailableMessage.java
internal/protocol/NodeAvailableResponseMessage.java
internal/protocol/PowerBufferRequestMessage.java
internal/protocol/PowerBufferResponseMessage.java
internal/protocol/PowerChangeRequestMessage.java
internal/protocol/PowerInformationRequestMessage.java
internal/protocol/PowerInformationResponseMessage.java
internal/protocol/RealTimeClockGetRequestMessage.java
internal/protocol/RealTimeClockGetResponseMessage.java
internal/protocol/RoleCallRequestMessage.java
internal/protocol/RoleCallResponseMessage.java
```

**Comment by kgoderis** [comment]
@wborn I am ok with your proposal

**Comment by wborn** [comment]
> I am ok with your proposal

Great! I'll put in a PR after doing some more testing and documentation writing.
