### ISSUE TITLE
[Wifilight] Binding not working with my ld382 v3

### ISSUE THREAD

**Issue by m3tatai** [openhab/openhab2-addons#1840]
Hello guys, 

i bought this Wifi RGB(W) LED Controller ( https://www.amazon.de/gp/product/B00Q7STR4E/ref=ask_ql_qh_dp_hza ) and added the controller to my wifi network. Afterwards i added the wifilights binding and conncted the binding with my controller. Everything seems to be fine and online, but after switching my Controller to on, nothing happend. 

I'm Using debian + Openhab 2.0.1 and Wifilights 2.0.0 . I'm new to openhab and linux. 

Best regards ! 

m3ta

**Comment by davidgraeff** [comment]
This led is controlled by the milight addon, not the wifilights binding :) Could you please test again.

**Comment by davidgraeff** [comment]
@kaikreuzer: Could you close this one?

**Comment by m3tatai** [comment]
@davidgraeff The Topic was a mistake by myself. I used several versions of the milight binding(not wifilight), but without success.
But i got a temporary solution for my problem. Using the **Wifilight** Binding from the latest snapshot release, ist working without any problems. 

In summary:
Milight: not working (beta 13)
Wifilight: working (latest Snapshort release)
