### ISSUE TITLE
[Homematic] Small issues with new Signal Strength / RSSI implementation

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab2-addons#1842]
Just tested the new channel Signal Strength. The received value is OK (but displayed without unit).
![image](https://cloud.githubusercontent.com/assets/616792/22628096/38be3df6-ebce-11e6-9d1a-5baad89ce999.png)

When an item is created for this channel, the item has a default category of "QualityOfService", but according to the definition of QoS (https://www.eclipse.org/smarthome/documentation/development/bindings/thing-definition.html) only values 0, 1, 2, 3 or 4 are interpreted correctly.

I think there are two possible solutions (I must confess that I am not sure about the best solution):
- use an empty default category (like RSSI Peer and RSSI Device) and display the unit "dbM" by default. 
- use category "QualityOfService" as category and return suitable values for this category to enable a correct display of the bitmap.

Now that groups are working fine, I am not sure whether a signal strength makes sense. It seems to be always "NaN"
![image](https://cloud.githubusercontent.com/assets/616792/22628178/bc492ce8-ebcf-11e6-84d4-4f971c16d8de.png)

**Comment by gerrieg** [comment]
Thanks for the hint, i added a new channel RSSI and fixed the signal strength values, see https://github.com/openhab/openhab2-addons/pull/1858

**Comment by MHerbst** [comment]
:-) Will try it after it has been merged.

**Comment by MHerbst** [comment]
@gerrieg I now had the time to test it and the signal strength seems to work correct now for single devices. However the displayed values differ from the values that the CCU shows when I use devconfig.cgi. This maybe a problem of the CCU. If necessary I will create a new issue. 

So this one can be closed now.
