### ISSUE TITLE
Several links to docs are broken

### ISSUE THREAD

**Issue by sihui62** [openhab/openhab2-addons#1843]
http://docs.openhab.org/addons/io/openhabcloud/readme.html
http://docs.openhab.org/addons/io/homekit/readme.html
http://docs.openhab.org/addons/io/hueemulation/readme.html

All show: Error 404

**Comment by MHerbst** [comment]
This is the wrong repo. Can you create an issue in this repo https://github.com/openhab/openhab-docs/issues and close this one.

**Comment by MHerbst** [comment]
I have created an issue in the openhab-docs repos because all links seem to be broken because of a geneeral reorg without redirects.

**Comment by sihui62** [comment]
> This is the wrong repo.

Sorry, silly me, closed.
