### ISSUE TITLE
[HomeKit] Duplicate subscription

### ISSUE THREAD

**Issue by mlowijs** [openhab/openhab2-addons#1848]
When accessing a Thermostat in the Home app on iOS, these log messages appear in the openHAB log:

    18:13:56.366 [ERROR] [kit.internal.HomekitAccessoryUpdater] - Received duplicate subscription on wk_th_mode
    18:13:56.369 [ERROR] [kit.internal.HomekitAccessoryUpdater] - Received duplicate subscription on wk_th_mode

Also, possibly related, setting the thermostat mode inside the Home app doesn't change the value of the mode in openHAB.

**Comment by 1activegeek** [comment]
chiming in here as I've got the same issue occurring. I've seen it randomly, but just now restarted due to HomeKit saying the OpenHAB accessory wasn't responding. When I checked the messages, there was a flood of these.

**Comment by johnofcamas** [comment]
Same issue still occurring. any update to this?  Is it harmless?

**Comment by Stefan136** [comment]
I see the same issue sometimes for all devices connection to Homekit :(

**Comment by grzegorz914** [comment]
I see also the same issue for all devices binding with HomeKit

**Comment by rkneipp** [comment]
Same issue here.

**Comment by smiesko99** [comment]
Hi 

have you resolve this issue ?

**Comment by wborn** [comment]
Closing this issue because it is a duplicate #1258.
