### ISSUE TITLE
[org.openhab.binding.chromecast] Chromecast Audio: Stream and Control of Multiroom Groups not working correctly

### ISSUE THREAD

**Issue by TS-Tec** [openhab/openhab2-addons#1853]
Hi,

just recognized that the behavior of Multiform Groups, which are handled like separate "virtual" Chromecast Audio devices and are discovered as separate things in OpenHAB2, is not as it should be.
The control channel and the playURI channel do only have an influence of one group device and not to all. If streaming to the Multiroom Group is started from another device, the control does not work at all...
I guess that the virtual Multiroom Device has to be handled different like a normal "real" Chromecast Audio...

**Comment by lolodomo** [comment]
One similar issue with less details already exists: #1766
