### ISSUE TITLE
[MAX! Binding] Support CUL stick

### ISSUE THREAD

**Issue by deflomu** [openhab/openhab2-addons#1856]
I would like to control my Max! thermostats without using a Max! Cube. I have a busware CUL 868 MHZ  USB stick wo it would be nice if I could use it directly with openhab2.

**Comment by hmerk** [comment]
You could try to use the openHAB 1.x maxcul binding within openHAB2.

**Comment by deflomu** [comment]
Thank you I'll try that. Even if this works I think it could still be useful to have this functionality in the new addon.

**Comment by hmerk** [comment]
No, as it is completely different approach. Even with openHAB 1.x, there had been two different bindings, CUL and CUBE.

**Comment by deflomu** [comment]
Oh ok. So the right approach would be to create a new addon that does not support the Cube but uses the CUL stick to communicate with the thermostats and so on? Or would it be useless work because there already is the openhab 1 addon? Anyway: I think this issue can be closed then.

**Comment by hmerk** [comment]
Do you see any benefit from having a openHAB 2 binding for communicationg with the CUL ?
If not, there is no need for one.
You can close this issue yourself if you want. :-)

**Comment by deflomu** [comment]
Hmm I just assumed every addon should be migrated to openhab 2. Thanks for your help :)
