### ISSUE TITLE
[Zoneminder] Unessesary log infos in openhab.log

### ISSUE THREAD

**Issue by whopperg** [openhab/openhab2-addons#1859]
Hi @Mr-Eskildsen ,
just installed your now merged Addon (congrats on that ;-)) and my log is flooded again with:

`2017-02-07 20:08:04.176 [INFO ] [andler.ZoneMinderServerBridgeHandler] - [BRIDGE (914be859)]: Bridge status changed from 'ONLINE' to 'ONLINE'
2017-02-07 20:08:19.571 [INFO ] [andler.ZoneMinderServerBridgeHandler] - [BRIDGE (914be859)]: Bridge status changed from 'ONLINE' to 'ONLINE'
2017-02-07 20:08:34.930 [INFO ] [andler.ZoneMinderServerBridgeHandler] - [BRIDGE (914be859)]: Bridge status changed from 'ONLINE' to 'ONLINE'
2017-02-07 20:08:50.401 [INFO ] [andler.ZoneMinderServerBridgeHandler] - [BRIDGE (914be859)]: Bridge status changed from 'ONLINE' to 'ONLINE'
2017-02-07 20:09:05.719 [INFO ] [andler.ZoneMinderServerBridgeHandler] - [BRIDGE (914be859)]: Bridge status changed from 'ONLINE' to 'ONLINE'
` and so on.

**Comment by Mr-Eskildsen** [comment]
Oh Crap.....
Obviously a error. Is it only the "change" from ONLINE -> ONLINE that is flooding?

**Comment by whopperg** [comment]
Yep, seems only the change notice

**Comment by whopperg** [comment]
Hey mate, any update on this? Do you need more Infos? Or can i help otherwise? 

Cheers,

**Comment by Mr-Eskildsen** [comment]
I have just changed a couple of things and created a new build. That should decrease the spamming of the log, to a more usefull level.

**Comment by Andre1Becker** [comment]
Sound good! Happy to give it a try :)

**Comment by whopperg** [comment]
Sounds good! Happy to give it a try! :-) Cheers

**Comment by Mr-Eskildsen** [comment]
I have been using the binding below for a couple of days, in my environment it seems to run smooth, and the log entries seems to be at a more reasonable level
[org.openhab.binding.zoneminder-2.1.0-SNAPSHOT.zip](https://github.com/openhab/openhab2-addons/files/792726/org.openhab.binding.zoneminder-2.1.0-SNAPSHOT.zip)

**Comment by whopperg** [comment]
Hey, looks much better now - only when a alarm is raised, i got entries in the log. Thank you very much! I close this for now.

**Comment by Mr-Eskildsen** [comment]
All done, your review gave much more sense when looking at the code :-)
