### ISSUE TITLE
HABPanel Problem with MAP Binding

### ISSUE THREAD

**Issue by micropet** [openhab/openhab2-addons#1872]
I use HABPanel to display only one temperature:
Number D25_Temp_aussen "Outside temperature [%. 1f ° C]"

That works great. If I now install the MAP binding I get the following error message:

Connection lost. Trying to reconnect.

If I remove the MAP binding, the display works again.

**Comment by kubawolanin** [comment]
I think https://github.com/openhab/org.openhab.ui.habpanel/issues would be the best place to submit this issue :)

**Comment by micropet** [comment]
Thank you. I ask there.
