### ISSUE TITLE
Homematic IP Things Offline

### ISSUE THREAD

**Issue by michaeljoos72** [openhab/openhab2-addons#1873]
Hi

With latest 2.1 snapshots (approx 1 week ago) my Homematic-IP-Things disconnect from openHAB after about 30 minutes and go offline. It happens only to IP-Devices (window and door sensors). Could it be that this is related to the new RSSI handling?

2.0 is working like a charme :)

Thanks
Michael

**Comment by MHerbst** [comment]
I don't think that it is caused by the RSSI handling. Maybe it is caused by one of the other changes that were merged together with the RSSI handling. 
Can you activate the trace output and attach the log file here?

The trace can be activated on the Karaf console with the following command:
```
log:set TRACE org.openhab.binding.homematic
````
Then restart openHAB. You can disable the trace output with:
```
log:set INFO org.openhab.binding.homematic
````

**Comment by michaeljoos72** [comment]
Ok, thanks. Will do this next Monday as I'm not at home right now.

**Comment by michaeljoos72** [comment]
Updated right now to latest snapshot with same result. The IP-Things go offline one by one after about 30 minutes. Very strange....

![image](https://cloud.githubusercontent.com/assets/20517474/22890681/685b11f2-f20d-11e6-99fc-e6eac0c0fd31.png)

This belongs to all Things that start with 0000D3...:

  <entry name='NEQ0166447' value='Dimmer Bar' />
  <entry name='0000D3C9905BF8' value='Fenster Bad' />
  <entry name='0000D3C9905FE8' value='Fenster Bad UG' />
  <entry name='0000D3C9905D30' value='Fenster Büro' />
  <entry name='0000D3C9905E50' value='Fenster Entrée' />
  <entry name='0000D3C9905CFC' value='Fenster Esstisch' />
  <entry name='0000D3C9905E5A' value='Fenster Gästezimmer' />
  <entry name='0000D3C9905D39' value='Fenster Kino' />
  <entry name='0000D3C9905E36' value='Fenster Küche' />
  <entry name='0000D3C9905E0A' value='Fenster Lukarne Ost' />
  <entry name='0000D3C9905FD0' value='Fenster Lukarne West' />
  <entry name='0000D3C9905D36' value='Fenster Schlafzimmer' />
  <entry name='0000D3C9905B71' value='Fenster Sofa' />
  <entry name='BidCoS-RF' value='HM-RCV-50 BidCoS-RF' />
  <entry name='000915698D5F95' value='Motion Rotini' />
  <entry name='MEQ0738529' value='Schalter Aufgang' />
  <entry name='NEQ0950149' value='Schalter Bad' />
  <entry name='MEQ0738907' value='Schalter Büro' />
  <entry name='MEQ0738683' value='Schalter Entrée' />
  <entry name='MEQ0738686' value='Schalter Gästezimmer' />
  <entry name='MEQ0737879' value='Schalter Kamin' />
  <entry name='MEQ0738620' value='Schalter Küche' />
  <entry name='MEQ0738031' value='Schalter Schlafzimmer' />
  <entry name='NEQ0950182' value='Schalter WC' />
  <entry name='0000D3C993475B' value='Türe Eingang' />
  <entry name='0000D3C98C9205' value='Türe Esstisch' />
  <entry name='0000D3C98C91F1' value='Türe Kellerabgang' />
  <entry name='0000D5698E3D90' value='Türe Terrasse' />

Additionally Trace-Log to analyze in more detail. Hope this helps:

[Trace_Homematic.txt](https://github.com/openhab/openhab2-addons/files/771570/Trace_Homematic.txt)

**Comment by michaeljoos72** [comment]
One more Error-Log with latest snapshot:

[Error_Log.txt](https://github.com/openhab/openhab2-addons/files/785126/Error_Log.txt)

Homematic-Devices Online
Homematic-IP-Devices Offline

**Comment by MHerbst** [comment]
There are a lot of timeout exceptions in the error log but I have no idea how this could be related to HMIP components. I don't whether it may help to increas the timeout value in the bridge configuration. Any idea @gerrieg?

**Comment by gerrieg** [comment]
There are so many TimeoutExceptions, please make sure all ports are open ([see readme](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.homematic/README.md)). Port 9292 is new in the snapshot build.

**Comment by michaeljoos72** [comment]
I try to analyse more. But if a port is the issue it should not work at system start? In my case everything is online about 30 minutes and then each Homematic-IP Thing goes offline one by one (not all at the same time)

**Comment by gerrieg** [comment]
I've downloaded the current snapshot and started it, it runs now for about two hours and my HmIP device is still online

**Comment by michaeljoos72** [comment]
It looks that this was an issue with reconnecting/restarting of RPC-Server. It helped to increase aliveInterval to 3600 (1h). For now everything is online :) Issue closed.
