### ISSUE TITLE
Change Channel

### ISSUE THREAD

**Issue by Blackei** [openhab/openhab2-addons#1875]
Hi,

i have a Problem to change to another channel. I have a Item and can send a break over Alexa.
I made a rule for the send command

rule "umschalten"
when
    Item prosieben received update
then
    var String HarmonyState = Harmony_Hub.state.toString()
if (HarmonyState == "Fernseher")
    sendCommand(Receiver, "1142")
end

But how can i change to Channel 1142? Thanks for Help

**Comment by kaikreuzer** [comment]
Please use our forum for support: https://community.openhab.org/
Thanks!
