### ISSUE TITLE
myopenhab change uuid and secret after saving old value are shown

### ISSUE THREAD

**Issue by kobelka** [openhab/openhab2-addons#1876]
I purged my old openhab version and installed a new one.
So I also have to change the uuid and secret in myopenhab.org.
After I have clicked Update the old values are shown again, also if you browse z.b. to events and back to account the old values are shown. Only if you logout and login again the new value wher shown.

**Comment by kaikreuzer** [comment]
This seems to be an issue report about the cloud service, so please rather enter it at https://github.com/openhab/openhab-cloud. Thanks!
