### ISSUE TITLE
Colorpicker in BASIC UI

### ISSUE THREAD

**Issue by rockster2410** [openhab/openhab2-addons#1890]
Hi,
there is an issue in openhab2 (incl. latest snapshot) with the colorpicker in the BasicUI.
The colorpicker is working perfectly but not the two buttons next to it (left and right to turn on and off).

The problem is discussed here: 
https://community.openhab.org/t/openhab2-problem-with-colorpicker-in-basic-ui/19421

Does anyone know a solution?

Thanks!

**Comment by kaikreuzer** [comment]
Could you please report this at https://github.com/eclipse/smarthome/issues, because this is where the Basic UI lives? Thanks!
