### ISSUE TITLE
[Homematic] delay in processing remote control commands

### ISSUE THREAD

**Issue by jipp** [openhab/openhab2-addons#1892]
Hi

I observed the following.

when a remote Switch (HM-RC-8 or HM-PB-2-WM55) is pressed it takes several seconds till the command is processed. the next command is processed faster. this stays like this for some time, but latest the next morning I observe the same again

below some logs for the HM-RC-8 - MEQ0708559
The TH16Switch is controlled via mqtt.
I observe the same when using a homematic switch. just to exclude this as source of problems I used the mutt device.

delayed processing:

homegear.log
02/14/17 07:32:17.813 Module HomeMatic BidCoS: Info: INSTALL_TEST on channel 4 of HomeMatic BidCoS peer 6 with serial number MEQ0708559 was set to 0x09.
02/14/17 07:32:17.813 Module HomeMatic BidCoS: Info: PRESS_SHORT on channel 4 of HomeMatic BidCoS peer 6 with serial number MEQ0708559 was set to 0x09.
02/14/17 07:32:17.813 Module HomeMatic BidCoS: Info: TEST_COUNTER on channel 4 of HomeMatic BidCoS peer 6 with serial number MEQ0708559 was set to 0x09.
02/14/17 07:32:17.814 Module HomeMatic BidCoS: Info: SIM_COUNTER on channel 4 of HomeMatic BidCoS peer 6 with serial number MEQ0708559 was set to 0x09.

openhab.log
2017-02-14 07:32:17.927 [ItemStateChangedEvent     ] - RC_4short changed from OFF to ON
2017-02-14 07:32:19.940 [ItemStateChangedEvent     ] - RC_4short changed from ON to OFF
2017-02-14 07:32:23.221 [ItemCommandEvent          ] - Item 'TH16Switch' received command ON
2017-02-14 07:32:23.233 [ItemStateChangedEvent     ] - TH16Switch changed from OFF to ON

events.log
2017-02-14 07:32:23.185 [INFO ] [smarthome.model.script.remoteControl] - RemoteControl-4-short
2017-02-14 07:32:23.206 [INFO ] [eclipse.smarthome.model.script.Light] - ON

fast processing:

homegear.log
02/14/17 07:33:10.819 Module HomeMatic BidCoS: Info: INSTALL_TEST on channel 4 of HomeMatic BidCoS peer 6 with serial number MEQ0708559 was set to 0x0A.
02/14/17 07:33:10.819 Module HomeMatic BidCoS: Info: PRESS_SHORT on channel 4 of HomeMatic BidCoS peer 6 with serial number MEQ0708559 was set to 0x0A.
02/14/17 07:33:10.819 Module HomeMatic BidCoS: Info: TEST_COUNTER on channel 4 of HomeMatic BidCoS peer 6 with serial number MEQ0708559 was set to 0x0A.
02/14/17 07:33:10.820 Module HomeMatic BidCoS: Info: SIM_COUNTER on channel 4 of HomeMatic BidCoS peer 6 with serial number MEQ0708559 was set to 0x0A.

openhab.log
2017-02-14 07:33:10.939 [ItemStateChangedEvent     ] - RC_4short changed from OFF to ON
2017-02-14 07:33:10.975 [ItemCommandEvent          ] - Item 'TH16Switch' received command OFF
2017-02-14 07:33:10.983 [ItemStateChangedEvent     ] - TH16Switch changed from ON to OFF
2017-02-14 07:33:12.932 [ItemStateChangedEvent     ] - RC_4short changed from ON to OFF

events.log
2017-02-14 07:33:10.952 [INFO ] [smarthome.model.script.remoteControl] - RemoteControl-4-short
2017-02-14 07:33:10.961 [INFO ] [eclipse.smarthome.model.script.Light] - OFF

rule:
rule "RemoteControl-4-short"
when
	Item RC_4short received update ON
then
	logInfo("remoteControl", "RemoteControl-4-short")
	if (TH16Switch.state == ON) {
		logInfo("Light", "OFF")
		sendCommand(TH16Switch, OFF)
	} else if (TH16Switch.state == OFF) {
		logInfo("Light", "ON")
		sendCommand(TH16Switch, ON)
	}
end

thing:
Bridge	homematic:bridge:scc	[ gatewayAddress="lemonpi" ]
{
	Thing	HG-HM-RC-8			MEQ0708559
	Thing	GATEWAY-EXTRAS-SCC	GWE00000000
}

item:
Switch	RC_1short	"Fernbedienung Taste 1 short"	<none>	{ channel="homematic:HG-HM-RC-8:scc:MEQ0708559:1#PRESS_SHORT" }

**Comment by MHerbst** [comment]
Can you check the log file whether there is a message that the binding lost the connection the the CCU. Maybe the binding has first to reconnect with the CCU.

**Comment by jipp** [comment]
could you give me a hint for which message type I have to look for?

**Comment by MHerbst** [comment]
You could search for messages containing "Connection lost".

**Comment by jipp** [comment]
Hi

I monitored the system now since some days.
looking through the logs I have not found any "connection lost" messages.
Also for the time I reported the problem there was no such message.

The news is: For whatever reason I did now not observe the reported behavior anymore - looks like that monitoring the system solved the problem.
I will continue looking around and checking. But so far it works quite well.

thanks
Wolfgang

**Comment by Brain0verflow** [comment]
Hi,

i have exactly the same error. I'm using a HM-RC-8 - MEQ0708559 and a few HM-LC-Bl1PBU-FM with a CCU2. In my openhab.log are no connection lost entries.

**Comment by MHerbst** [comment]
@Brain0verflow Do you still have this problem? If yes can you try it with the latest snapshot version of the add-in?

**Comment by Brain0verflow** [comment]
@MHerbst I updated OH2 and the bindings to the latest snapshots few days ago. It looks like the error is gone.
Thanks for this fix!

**Comment by martinvw** [comment]
Thanks for reporting back
