### ISSUE TITLE
documentation for kostal binding wrong

### ISSUE THREAD

**Issue by CWempe** [openhab/openhab2-addons#1893]
It looks like the documentation of the kostal binding is wrong.

The doc says:
```
Thing kostalpico:kostalpico:inverter [ url="http://192.168.0.128" ]
```

But it should be ```kostalinverter:kostalinverter:```

see discussion: https://community.openhab.org/t/kostal-not-working-via-config-file/22918

**Comment by kaikreuzer** [comment]
Could you submit a PR to fix it?

**Comment by CWempe** [comment]
Never done this before.
But it's quiet easy via Github web frontend. :)

https://github.com/openhab/openhab2-addons/pull/1899
