### ISSUE TITLE
High CPU usage with serial libs

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab2-addons#1897]
[Sorry for posting this here, as I can not enter a new Issue on openhab/nrjavaserial repo]

For one of my bindings I continue to experience irrational high CPU usage when using the nrjavaserial binding, even when using the work-around using a separate Thread to read out data on the serial port. It is that worse that in my operational environment (on macOS X) - with all the other bindings in full swing - this causes issues with other bindings. For example, whereas the KNX binding normally is able to process a response telegram with a few 100 of ms, this now goes up to 10 seconds and more. The binding in question (RME) communicates with a remote device that is pushing out a constant flow of data over the serial port (e.g. it is no message based or similar, like in other bindings). 

Is there a way to more dramatically alter the nrjavaserial port in such a way that timings, intervals, .... (at least, the parameterisation of these) are pushed upwards to the client using the library? And make the library "less blocking"? I am not an expert in native code and so forth, I do not know if this this possible after all, but somehow somewhere something is frantically consuming cpu cycles without being able to modify any behaviour

I have come across:

https://blogs.oracle.com/jtc/entry/java_serial_communications_revisited
https://github.com/ChristianSchwarz/xidobi2/wiki/Other-Serial-Libraries

**Comment by kaikreuzer** [comment]
>  I can not enter a new Issue on openhab/nrjavaserial repo

That's because the official repo is https://github.com/NeuronRobotics/nrjavaserial.
I'd highly recommend to post your issue there, because this is where all users of that library are able to see and answer on it. I personally cannot really comment on it and I am lacking the time to investigate it in depth myself.
