### ISSUE TITLE
Write only channels ?

### ISSUE THREAD

**Issue by darkrift** [openhab/openhab2-addons#1898]
I'm still new to the openhab2 dev infrastructure, but I'll explain the use case I am trying to solve.

I am currently trying to make a binding to communicate with my LG TV through the RS232 (DB9) port (the OH1 plugin doesn't even support this at the moment) and there are commands I can send to the TV with an IR code and the TV understands it as if it was pressed on the tv remote.

Now, in OH2 I need to create a channel to support that and be able to cummunicate with the handler, however this channel doesn't really have a state in itself.

As such, I don't see any "write-only" channel so I think we should have such feature where we can have a one-way communication only, unless I didn't find that feature ?

**Comment by lolodomo** [comment]
You should discuss about that on the forum.
You can simply use a channel of type String that will be used only to send commands.

**Comment by tavalin** [comment]
I'd have thought a trigger channel would be better to send a button press, no?

**Comment by lolodomo** [comment]
Trigger channel is something relatively new and I have not yet played with bindings using it.
I found only this page talking about that notion: https://eclipse.org/smarthome/documentation/development/bindings/thing-definition.html It is not clear for me what it is for exactly and how to use them.

**Comment by darkrift** [comment]
The way I see the trigger channel is for handlers to send events to that channel and update the tied items, not the other way around.

Richard Lavoie

**Comment by kaikreuzer** [comment]
>  trying to make a binding to communicate with my LG TV through the RS232

I hope you are aware of http://docs.openhab.org/addons/bindings/lgtvserial/readme.html?

**Comment by kaikreuzer** [comment]
As a general remark: Please discuss binding API/development issues at https://www.eclipse.org/forums/index.php/f/271/ - thanks!

**Comment by darkrift** [comment]
Is this new or in another project ? I just checked openhab2-addons, openhab-addons and the esh folder for that binding on my computer (I downloaded the code 2 weeks ago) and I couldn't find it, it's also not available in my OH2 install (which I installed at about the same time I downloaded the code) to configure the things. The only one I found was the old oh1 lg binding which doesn't go through the serial port.

**Comment by kaikreuzer** [comment]
Came with https://github.com/openhab/openhab2-addons/pull/1242, which was created in 09/2016 and merged 10 days ago.
