### ISSUE TITLE
[MAX! Binding] Incorrect "Full Example" in README?

### ISSUE THREAD

**Issue by adam-dej** [openhab/openhab2-addons#1906]
Hi,

I'm using text based config and max binding. README of the MAX! binding shows the following example of `max.things`:

```
Bridge max:bridge:KEQ0565026 [ ipAddress="192.168.3.9", serialNumber="KEQ0565026" ]
max:thermostat:KEQ0565026 [ serialNumber="KEQ0565123" ]
```

However, this did not work for me. After adding the first line the debug log shows that the binding is communicating with the cube, thermostats are learned in and it's reading actual temperature from all of them. However, this error appears when I add the second line defining the thermostat:

```
[DEBUG] [x.internal.handler.MaxDevicesHandler] - Initialized MAX! device handler for KEQ0453817.
[DEBUG] [x.internal.handler.MaxDevicesHandler] - Required bridge not defined for device KEQ0453817.
```

This config format finally worked for me (IDs are from the example)

```
Bridge max:bridge:KEQ0565026 [ ipAddress="192.168.3.9", serialNumber="KEQ0565026" ] {
    Thing max:thermostat:KEQ0565026:KEQ0565123 [ serialNumber="KEQ0565123" ]
}
```

Since I'm relatively new to configuring openhab using config files I don't know whether this is a misunderstanding on my part or error in the README, but I'm letting you know just to be sure.

I'm currently on OpenHAB 2.1.0-snapshot (using docker image), but the problem (and solution) is the same on OpenHAB 2.0.0 (again, from docker image).

**Comment by marcelrv** [comment]
I think it is an error in the documentation....
