### ISSUE TITLE
[Homematic] HM-CC-RT-DN Automode/Manumode

### ISSUE THREAD

**Issue by Andirs55** [openhab/openhab2-addons#1909]
Hello i suppose i found a bug in the switch between auto- and manumode. My thermostats should switch to 5°C manumode on window open and back to automode when windows are closed again.

Here are my rules:

> rule "SZ_window_opened"
> 	when
> 		Item SZFK1_State changed to OPEN
> 	then
> 		if(timer_SZ_window == null) {
> 			timer_SZ_window = createTimer(now.plusSeconds(15), [|
> 				sendCommand(SZHT1_Manumode, 5.0)
> 			])
> 		}
> end
> 
> rule "SZ_window_closed"
> 	when
> 		Item SZFK1_State changed to CLOSED
> 	then
> 		if(timer_SZ_window.hasTerminated) {
> 			timer_SZ_window = null
> 			sendCommand(SZHT1_Automode, ON)
> 		}
> 		else {
> 			timer_SZ_window.cancel()
> 			timer_SZ_window = null
> 		}
> end

Now my problem: The cycle manumode (window open) and automode (window closed) works exactly one time. On the second window open it does not switch to manumode anymore and throws no error in the logs (standard debug level). But if I change the manumode temperature to a different value e.g. 6°C it works again for one cycle and then i have to change the temp again.

**Comment by MHerbst** [comment]
Which OH version are you using? Especially with #1622 there have been some updates that may also solve this problem.

**Comment by Andirs55** [comment]
I am on 2.0.0 Release build

**Comment by MHerbst** [comment]
Can you try it with latest OH 2.1.0 snapshot. There has been a change in the Homematic binding that may correct this problem. 
I can'tr try to reproduce it right now because I have directly coupled the window contact and the radiator. Therefore I don't need a rule :-).

**Comment by Andirs55** [comment]
Yes that seems to help thanks :)
