### ISSUE TITLE
[Homematic] Don't make all datapoints available as channels for device groups

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab2-addons#1915]
While testing the new signal strength I got a strange result when creating items for the RSSI channels of a device group:
![image](https://cloud.githubusercontent.com/assets/616792/23095179/e4d23fc0-f605-11e6-82a9-147a690669f6.png)

Generally these channels don't make sense for device groups because the datapoints are device-specific and dont't contain real values for groups.

You can see it when you check the datapoint values returned from the CCU:
```
<device name="Gruppe Arbeitszimmer" ise_id="2227" unreach="20.0" sticky_unreach="20.0" config_pending="20.0">
  <channel name="Gruppe Arbeitszimmer:0" ise_id="2228" visible="" operate="">
      <datapoint name="VirtualDevices.INT0000007:0.UPDATE_PENDING" type="UPDATE_PENDING" ise_id="2238" value="20.0" valuetype="2" valueunit="" timestamp="1487437437" operations="5"/>
      <datapoint name="VirtualDevices.INT0000007:0.RSSI_DEVICE" type="RSSI_DEVICE" ise_id="2234" value="20.0" valuetype="8" valueunit="" timestamp="1487437437" operations="5"/>
      <datapoint name="VirtualDevices.INT0000007:0.AES_KEY" type="AES_KEY" ise_id="2229" value="20.0" valuetype="8" valueunit="" timestamp="1487437437" operations="1"/>
      <datapoint name="VirtualDevices.INT0000007:0.DEVICE_IN_BOOTLOADER" type="DEVICE_IN_BOOTLOADER" ise_id="2231" value="20.0" valuetype="2" valueunit="" timestamp="1487437437" operations="5"/>
      <datapoint name="VirtualDevices.INT0000007:0.CONFIG_PENDING" type="CONFIG_PENDING" ise_id="2230" value="20.0" valuetype="2" valueunit="" timestamp="1487437436" operations="5"/>
      <datapoint name="VirtualDevices.INT0000007:0.UNREACH" type="UNREACH" ise_id="2237" value="20.0" valuetype="2" valueunit="" timestamp="1487437436" operations="5"/>
      <datapoint name="VirtualDevices.INT0000007:0.LOWBAT" type="LOWBAT" ise_id="2233" value="20.0" valuetype="2" valueunit="" timestamp="1487437437" operations="5"/>
      <datapoint name="VirtualDevices.INT0000007:0.STICKY_UNREACH" type="STICKY_UNREACH" ise_id="2236" value="20.0" valuetype="2" valueunit="" timestamp="1487437436" operations="7"/>
      <datapoint name="VirtualDevices.INT0000007:0.RSSI_PEER" type="RSSI_PEER" ise_id="2235" value="20.0" valuetype="8" valueunit="" timestamp="1487437437" operations="5"/>
  </channel>
  <channel name="Gruppe Arbeitszimmer" ise_id="2239" visible="true" operate="true">
      <datapoint name="VirtualDevices.INT0000007:1.CONTROL_MODE" type="CONTROL_MODE" ise_id="2245" value="1" valuetype="16" valueunit="" timestamp="1487437300" operations="5"/>
...
```
It seems that the values of all datapoints that do not make sense for groups are "20.0". 
@gerrieg  As far as I can see you can ignore datapoints of channel 0 for groups completely because these datapoints will never contain real values.

**Comment by gorzan14** [comment]
Some Channels are not updated correctly. For example: CONTROL_MODE. Which is important. It is the same for other Things that have this Channel like Heater-thermostat and wallthermostat.
I wrote an detailed Issue with logs. #1923 The value is correctly send from CCU2 to the Binding but not updated to openHAB2.

**Comment by gerrieg** [comment]
@MHerbst 
It's not so easy to remove only one channel from one 'device'. Apart from this i think it's better to always show all channels the gateway exposes to the user, independently if they make sense or not. That's what the gateway sends. Maybe another gateway (Homegear, OCCU) sends values that make sense to some users.

**Comment by MHerbst** [comment]
@gerrieg OK. Accepted. What do you think of adding some information to the documentation that explain how the channels are derived from the datapoints.
