### ISSUE TITLE
MAX!Cube Binding doesnt respond anymore to Alexa-Voice command via Hue-Emulation

### ISSUE THREAD

**Issue by rrutk** [openhab/openhab2-addons#1920]
MAX!Cube Binding doesnt respond anymore to Alexa-Voice command via Hue-Emulation

MAX!Cube Binding doesnt respond anymore to Alexa-Voice command via Hue-Emulation.

No change at all, but the voice command "Heating to xy degrees" is not answered all the time with "This command doesnt work for this device".

It has worked for weeks ("Heating to xy degrees")...

Any ideas?

----------------

Wochenlang hat die Kombination Alexa + openHAB mit Hue-Emulation und Max!-Binding wunderbar funktioniert: "Heizung auf xy Grad" -> Voila.

Seit heute: "Heizung auf xy Grad" -> "Dieser Befehl funktioniert nicht für das Gerät Heizung".

Wurde an der Alexa-Software irgendwas verändert, so dass sie die "Lux Light" (emulierten Hue-Geräte) nicht mehr mir "Grad"-Befehlen ansprechen kann?

Geht noch jemandem das so?

Irgendwelche Ideen? Danke!

**Comment by kaikreuzer** [comment]
Please do not cross post - the forum is the better place for support, so check https://community.openhab.org/t/new-binding-hue-emulator-amazon-echo-integration/7944/165.
