### ISSUE TITLE
[wunderground?] Use any item in layout of weather binding 

### ISSUE THREAD

**Issue by staehler** [openhab/openhab2-addons#1924]
In openhab 1 it was possible to include individual item states in the weather binding layout. So I could use my own values of my weatherstation and enriched the layout just with not known weather data from the weather provider.

I would like to have this feature in OH2 as well. The temperature of my weatherstation differs slightly from the temperature of wondergroud. On the other hand, I have no UV index sensor, which I would take from the weather privider. So the layout should give the possibility to mix values.

**Comment by wborn** [comment]
If this is about the Weather Underground Binding it should be reported in the Eclipse SmartHome [issue tracker](https://github.com/eclipse/smarthome/issues) @staehler . Although that binding may also be EOL soon because of the WU API going EOL. :disappointed:
