### ISSUE TITLE
[holidays] Add iCal (Holidays) Binding

### ISSUE THREAD

**Issue by cniweb** [openhab/openhab2-addons#1925]
I would have an idea for a new feature:
Public holidays / school holidays binding
Realized with iCal import.

iCal data files for Germany are accessible via:
http://www.schulferien.org/deutschland/ical/

The idea would be to control the heating system, for example...

**Comment by sebastienvermeille** [comment]
@cniweb I like that idea and would be happy to develop it myself if @wborn is okay with that ?

(Would like to become openhab contributor and it seems a nice project to start with)
Can I start working on it ?

**Comment by kaikreuzer** [comment]
> Do we agree on that ?

I think this is still much too fuzzy. "we want to be able" - who is "we"? We have to differentiate different use cases, where "we" can be the developers of add-ons, the system admin, the regular user, etc. All of them might have different requirements as I tried to highlight with the two examples above.

Also note my reference to the LocaleProvider - holidays depend on your location (and other infos). You might want to have multiple holiday calendars within your system as you might deal with different locations & users.

If we are NOT talking here about an "iCal-Binding", but a "holiday info provider" feature, it'd probably make sense to create an issue at https://github.com/eclipse/smarthome/issues and get further people involved that have ideas/requirements for such a feature (like @JueBag, who uses holidays for Tankerkoenig).

**Comment by wborn** [comment]
Regarding the holiday part, there's already [ESH PR 6227](https://github.com/eclipse/smarthome/pull/6227) which will provide holiday information using [jollyday](http://jollyday.sourceforge.net/). So perhaps an iCal calendar can be another holiday information source for the Ephemeris service of that PR?

**Comment by kaikreuzer** [comment]
Right, thanks for the reminder @wborn, I somehow completely forgot about the existence of this PR!

**Comment by sebastienvermeille** [comment]
good I let someone else develop it it start to be to huge for my openhab skills.
