### ISSUE TITLE
[network] Items page reloads over 2 minutes when using network binding

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab2-addons#1926]
Items page reloads over 2 minutes when using network binding on oh2.

Does it wait util all things are pinged when reloading items?

**Comment by davidgraeff** [comment]
Yes it does and this is a bug, thanks for pointing this out. I'll make a fix soon.

**Comment by davidgraeff** [comment]
@openhab/maintainers This can be closed

**Comment by martinvw** [comment]
@davidgraeff thanks for the update!
