### ISSUE TITLE
Sonos Group: "Slave" with wrong state

### ISSUE THREAD

**Issue by michaeljoos72** [openhab/openhab2-addons#1931]
The state of a Sonos that has been added to another Sonos shows "PLAYING" after a few seconds even if the player is stopped:

Sonos 1: Stopped
Sonos 2: Stopped

Add Sonos 2 to Sonos 1 (Group)

After a few seconds:

Sonos 1: Stopped
Sonos2: Playing

Don't know if this is a bug in the Binding or Sonos itself?

**Comment by lolodomo** [comment]
For Sonos, sonos2 is playing in this case but the idea in the binding was to set the state of the group master. So it would be a bug in the binding because I would expect sonos2 in state stopped.
I will check.

How do you group your Sonos. With the Sonos application ?

PS: you declare the bug in the wrong repo as the Sonos binding is an Eclipse smarthome binding.

**Comment by lolodomo** [comment]
Just tried and I can't reproduce. For me, it is working as expected.
I am grouping the zones with the Sonos application.

**Comment by michaeljoos72** [comment]
I've tried it now with the sonos application as well. But for me it did not change anything.

1. Select Sonos_A --> Group
2. Add Sonos B to Group

Aproximately 30s later openHAB-Status changes to:

Sonos_A:
![sonos_a](https://cloud.githubusercontent.com/assets/20517474/23150820/d692144c-f7f6-11e6-82f3-0a41c4ae11c2.jpg)

Sonos_B:
![sonos_b](https://cloud.githubusercontent.com/assets/20517474/23150822/dbe32012-f7f6-11e6-91f2-cf9ef2881801.jpg)

Sonos_B_Status
![sonos_b_status](https://cloud.githubusercontent.com/assets/20517474/23150825/e109656a-f7f6-11e6-9c4b-7d32db3f5e28.jpg)

Hmmmm....I will do some more tests this evening to further delimit this behaviour.

**Comment by lolodomo** [comment]
Try with another UI too in case it is a problem relative to basic UI.
Yesterday I tried with HABdroid.

**Comment by michaeljoos72** [comment]
It was also visible in PaperUI...so not only relatet to BasicUI.

Was... :)

Yesterday I started from Scratch with Sonos-Configuration and removed "add" and "standalone" channels. And in addition I did some changes in my items file.
For now it looks good but don't ask me what was really the reason here for this behaviour.

Thanks
Michael

**Comment by joepadmiraal** [comment]
I know this ticket is closed but since it's the first Google hit I think it still might be useful to add a comment.
I have exactly the same with a stereo pair.
Both the REST calls and the UI's show the playing state after a number of seconds.
I eventually changed my rules and UI's to use the second Sonos speaker which does give the correct values.

**Comment by lolodomo** [comment]
Pairs are very probably not well managed. Reverse engineering should be done to understand how it is managed by Sonos in comparison to standard groups.

**Comment by jaywiseman1971** [comment]
I have 3 pairs of Sonos 1's and what I have found over the last year working with them and OH is one of the pairs is the Master over the pair.  Once you identify the master; you basically only interface with it vs. the pair.  I have noticed they do get out of sync once and while in OH; so you just do a postUpdate on the slave when the master changes.  It's not perfect though . . .

**Comment by joepadmiraal** [comment]
> so you just do a postUpdate on the slave 

Do you mean you'll change your rules so they do the postUpdates on the slave instead of the master?
Or do you do some kind of postUpdate to let the slave become the master again?

**Comment by jaywiseman1971** [comment]
The master unit never changes from being the master; it will always be the master.  I just looked at my code, looks like I'm doing sendCommands & postUpdate to both units on the rules.

Basement2 is my "master" of the pair.

Here's a few examples:

`		Sonos_Basement_StandAlone.postUpdate(OFF)				// Basement
		Sonos_Basement_ClearQueue.postUpdate(OFF)
		Sonos_Basement_Remove.postUpdate("OFF")
			Thread::sleep(1000)  // 1 second wait

		Sonos_Basement2_StandAlone.postUpdate(OFF) 				// Basement 2 - MASTER
		Sonos_Basement2_ClearQueue.postUpdate(OFF)
		Sonos_Basement2_Remove.postUpdate("OFF")
			Thread::sleep(1000)  // 1 second wait`

`			// Turning StandAlone Flags ON

			Sonos_Basement_StandAlone.sendCommand(ON)
			Sonos_Basement2_StandAlone.sendCommand(ON)
				Thread::sleep(1000)  // 1 second wait

			Sonos_Basement_Stop.sendCommand(ON)						// Stop Player Completely
			Sonos_Basement2_Stop.sendCommand(ON)					// Stop Player Completely
				Thread::sleep(1000)  // 1 second wait

			Sonos_Basement_Stop.sendCommand(OFF)					// Reset Flag
			Sonos_Basement2_Stop.sendCommand(OFF)					// Reset Flag
				Thread::sleep(1000)  // 1 second wait

			Sonos_Basement_ClearQueue.sendCommand(ON)				// Clear Queue ON
			Sonos_Basement2_ClearQueue.sendCommand(ON)				// Clear Queue ON
				Thread::sleep(1000)  // 1 second wait

			Sonos_Basement_ClearQueue.sendCommand(OFF)				// Clear Queue OFF
			Sonos_Basement2_ClearQueue.sendCommand(OFF)				// Clear Queue OFF
				Thread::sleep(3000)  // 3 second wait

			Sonos_Basement_Controller.postUpdate('STOPPED')		
			Sonos_Basement2_Controller.postUpdate('STOPPED')

			Sonos_Basement_CurrentAlbumCoverArtURL.postUpdate(DummyImageURL)		
			Sonos_Basement_CurrentTrack.postUpdate(DummyTrack)

			Sonos_Basement2_CurrentAlbumCoverArtURL.postUpdate(DummyImageURL)
			Sonos_Basement2_CurrentTrack.postUpdate(DummyTrack)`

`rule "Sonos Basement Controller Check URL and Track"
    when
		Item Sonos_Basement_Controller received update or
		Item Sonos_Basement_CurrentAlbumCoverArtURL received update or
		Item Sonos_Basement2_Controller received update or
		Item Sonos_Basement2_CurrentAlbumCoverArtURL received update
    then
	
        if (systemStarted.state != ON && Sonos_Basement_Controller.state != 'PLAYING' && Sonos_Basement_Controller.state != 'TRANSITIONING' && Sonos_Basement_CurrentTrack.state === null) {

			Sonos_Basement_CurrentAlbumCoverArtURL.postUpdate(DummyImageURL)
			Sonos_Basement_CurrentTrack.postUpdate(DummyTrack)

			Sonos_Basement2_CurrentAlbumCoverArtURL.postUpdate(DummyImageURL)
			Sonos_Basement2_CurrentTrack.postUpdate(DummyTrack)
		}

        if (systemStarted.state != ON && Sonos_Basement2_Controller.state != 'PLAYING' && Sonos_Basement2_Controller.state != 'TRANSITIONING' && Sonos_Basement2_CurrentTrack.state === null) {

			Sonos_Basement_CurrentAlbumCoverArtURL.postUpdate(DummyImageURL)
			Sonos_Basement_CurrentTrack.postUpdate(DummyTrack)

			Sonos_Basement2_CurrentAlbumCoverArtURL.postUpdate(DummyImageURL)
			Sonos_Basement2_CurrentTrack.postUpdate(DummyTrack)
		}
end`

Best, Jay

**Comment by bummzulu** [comment]
I have the same recurring issue. I can fix it for a while by deleting the cache/temp files of openhab:
![image](https://user-images.githubusercontent.com/46400859/73125138-bc530d00-3fa3-11ea-8c9e-c647be2a9511.png)
