### ISSUE TITLE
Feature Request one-wire binding: filter humidity > 100%

### ISSUE THREAD

**Issue by staehler** [openhab/openhab2-addons#1937]
Hi,
unfortunately sometimes (but often enough) my 1wire humidity sensors report values > 100%, which is of course nonsense. I hoped the tukeyfilter would filter this values out, but it doesn't. Because of this false positives my air condition raises more often than necessary.
Could you please enhance the [onwire binding](http://docs.openhab.org/addons/bindings/onewire1/readme.html) to filter out this values.
I could do this in a rule, but I think this values shouldn't be considered at all. 

Thanks and regards,
Michael

**Comment by wborn** [comment]
The onewire1 addon code is part of the openhab1-addons project.
If this is still an issue, please use the openhab1-addons [issue tracker](https://github.com/openhab/openhab1-addons/issues) for creating issues for this addon.

There's also an updated OH2 [OneWire Binding](https://www.openhab.org/addons/bindings/onewire) you might want to give a try. That addon is maintained at Eclipse SmartHome which also has its own [issue tracker](https://github.com/eclipse/smarthome/issues?q=is%3Aopen+is%3Aissue+label%3ABinding-OneWire).
