### ISSUE TITLE
[Homematic] NPE in HomematicDeviceDiscoveryService

### ISSUE THREAD

**Issue by gowi** [openhab/openhab2-addons#1938]
Hi, I removed a SystemVariable in Homegear. Since this is not recognized automatically by the Homematic-Binding, I removed the GATEWAY-EXTRAS thing. But now, I can't re-add the thing. The inbox is empty and no things are discovered. There is an execption in the log:

> 2017-02-22 10:48:49.072 [DEBUG] [ternal.communicator.HomematicGateway] - Loaded 27 gateway script(s)
> 2017-02-22 10:48:49.090 [DEBUG] [ternal.communicator.HomematicGateway] - Loaded device 'GWE00000000' (GATEWAY-EXTRAS-D229E0DC) with 33 datapoints
> 2017-02-22 10:48:49.092 [DEBUG] [atic.type.HomematicTypeGeneratorImpl] - Generating ThingType for device 'GATEWAY-EXTRAS-D229E0DC' with 33 datapoints
> 2017-02-22 10:48:49.170 [DEBUG] [binding.homematic.type.MetadataUtils] - Description not found for: GATEWAY-EXTRAS|RELOAD_RSSI, RELOAD_RSSI
> 2017-02-22 10:48:49.312 [ERROR] [very.HomematicDeviceDiscoveryService] -
> java.lang.NullPointerException
>         at org.openhab.binding.homematic.type.MetadataUtils.createBigDecimal(MetadataUtils.java:253)[184:org.openhab.binding.homematic:2.1.0.201702121957]
>         at org.openhab.binding.homematic.type.HomematicTypeGeneratorImpl.createChannelType(HomematicTypeGeneratorImpl.java:254)[184:org.openhab.binding.homematic:2.1.0.201702121957]
>         at org.openhab.binding.homematic.type.HomematicTypeGeneratorImpl.generate(HomematicTypeGeneratorImpl.java:137)[184:org.openhab.binding.homematic:2.1.0.201702121957]
>         at org.openhab.binding.homematic.handler.HomematicBridgeHandler.onDeviceLoaded(HomematicBridgeHandler.java:293)[184:org.openhab.binding.homematic:2.1.0.201702121957]
>         at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.loadAllDeviceMetadata(AbstractHomematicGateway.java:414)[184:org.openhab.binding.homematic:2.1.0.201702121957]
>         at org.openhab.binding.homematic.discovery.HomematicDeviceDiscoveryService$1.run(HomematicDeviceDiscoveryService.java:108)[184:org.openhab.binding.homematic:2.1.0.201702121957]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_77]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_77]
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_77]
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_77]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_77]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_77]
>         at java.lang.Thread.run(Thread.java:745)[:1.8.0_77]
>

**Comment by MHerbst** [comment]
Can you please try it with the current binding version? Does it solve the problem?

**Comment by MHerbst** [comment]
@martinvw  No answer to my question after 26 days. I think we can close this issue.
