### ISSUE TITLE
[kodi] thing stays offline despite correct settings

### ISSUE THREAD

**Issue by piejanssens** [openhab/openhab2-addons#1941]
Windows, openHAB2 and Kodi running on same machine.
Tried with both localhost and the IP address.
Autodiscovery doesn't show any result, despite zeroconf being enabled in Kodi.
Kodi settings:
- Enable remote 
- Port 9090
- Username/password blank

Final version of Kodi 17

/cc @pail23

**Comment by pail23** [comment]
kodi discovery is done by UPnP. Can you enable UPnP and try again?

**Comment by piejanssens** [comment]
Oh OK. Yes with UPnP it worked. Thanks.

**Comment by piejanssens** [comment]
After adding it as a new 'thing', however it stays offline.

**Comment by piejanssens** [comment]
Important - Kodi has a problem when the webserver is set to port 9090, because this port is also used by the websockets server...
https://github.com/PaulAvery/kodi-ws/issues/15
