### ISSUE TITLE
Paper UI's Add-ons > Misc Tab is blank when window maximized, populated when not

### ISSUE THREAD

**Issue by scurrier03** [openhab/openhab2-addons#1945]
![image](https://cloud.githubusercontent.com/assets/13679288/23247575/9af1db96-f960-11e6-9936-62acb575f453.png)
![image](https://cloud.githubusercontent.com/assets/13679288/23247596/b67ec568-f960-11e6-9b44-f58c3b4d3c2b.png)

Pretty much just as you can see in the pics.  When maximized, the tab is blank.  When half-screen, the tab is populated.  I have seen this before, so it's not a one time thing.  Chrome's scaling is set to 100%.

One possible cause is that I have a Dell 9550 Laptop with a 15" 4K display, which may be unusual at this point.

**Comment by scurrier03** [comment]
I should probably also note that my DPI setting is at 200% on my laptop.

**Comment by kaikreuzer** [comment]
Could you please report this at https://github.com/eclipse/smarthome/issues as this is where the Paper UI is maintained? Thanks!
