### ISSUE TITLE
[homekit] Can homekit integration provide an attribute to change the bridge name?

### ISSUE THREAD

**Issue by zenz** [openhab/openhab2-addons#1946]
as title, as I read the source code, it should be simple. but I'm not quite well with java language and it's developing environment.

**Comment by lutwik** [comment]
I don't know how to change it via an attribute.
If you are using Home app by Apple, you can change the display name of the Openhab Bridge by long pressing (or force touch pressing) on its icon and clicking on "details". Maybe that helps.

**Comment by zenz** [comment]
I know how to modify it on Home App.
But what about modify it for recognition? in case there are several openHAB device in my test environment.

**Comment by cubistico** [comment]
I have the same requirement (for the same reason). I've changed the HomeKit code locally to allow for this, and it works well. Now I'm looking to contribute my change, but please bear with me, this would be my first openHAB contribution. Can I assign this issue to me?

**Comment by cubistico** [comment]
See https://github.com/openhab/openhab2-addons/pull/3332

**Comment by J-N-K** [comment]
PR merged.
