### ISSUE TITLE
Enhancement: Enrich silvercrestwifisocket binding to support Aldi EasyHome

### ISSUE THREAD

**Issue by Ronson1909** [openhab/openhab2-addons#1952]
I plan to enhance the SilverCrest Wifi Socket Binding to support the similar system sold by Aldi (in fall 2016) under the brand EasyHome. The handling is extremely similar, only a company code byte and two authentication code bytes are different in the request and response packets. The Aldi system also includes a 433 MHz device to control remote plugs via web. However, I will split this in a separate enhancement.

The approach would be to add a new property "vendor" with two options (I already read that there's also a similar system sold with the brand CSL, which could become the next option). The request and response classes would be enhanced with that additional property and main changes are then in the WifiSocketPacketConverter class that composes and decomposes packets.

Actually the main work is already done and it's working. However, I'm not sure how existing SilverCrest binding users would see and deal with this change (new property). Since it's my first github activity (forking, pull request) this will be the main challenge for me.

**Comment by martinvw** [comment]
@Ronson1909 can we close this one now?

**Comment by Ronson1909** [comment]
Yes, we can close it.
