### ISSUE TITLE
[cometvisu] Change the add-on name in paper ui

### ISSUE THREAD

**Issue by peuter** [openhab/openhab2-addons#1958]
Currently the package is called "CometVisu" but as is only installs a backend for the CometVisu and not the CometVisu ifself, this name is misleading. Can someone change the name to "CometVisu backend" or tell me where I can do it?

**Comment by kaikreuzer** [comment]
The name is defined here (as "description"): https://github.com/openhab/openhab2-addons/blob/master/features/openhab-addons/src/main/feature/feature.xml#L382

**Comment by peuter** [comment]
Thanks PR #1959 created
