### ISSUE TITLE
Add discovery to Russound 

### ISSUE THREAD

**Issue by tmrobert8** [openhab/openhab2-addons#1974]
Add discovery to russound to discover Russound RIO devices.  Likewise, add the ability to scan the RIO device to discover all the zones/sources/banks/presets for automatic setup

Also includes media management channels and a new HABPanel widget that emulates the My Russound application

**Comment by tmrobert8** [comment]
Attached is the testing jar + habpanel for this...
[Russound.zip](https://github.com/openhab/openhab2-addons/files/844716/Russound.zip)

**Comment by tmrobert8** [comment]
Instructions for the testing jar:
1) Remove all existing Russound things/channels/etc (they have changed alot in this version)
2) Uninstall the Russound binding
3) Unzip above - put the binding in "addons", put the "Russound" folder into "conf/html" (so it's conf/html/Russound).

For autodiscovery:
1) Restart openHAB
2) Open the PAPERUI - inbox and hit the "+" to start the scan.
3) **Hopefully** a RIO system will appear over the next 30 seconds or so.
4) Click to add it
5) Wait a few more seconds and the controllers/zones/etc will be discovered and placed in the inbox
6) Add the controllers/zones you want from the inbox.

Note: there is a new config option on the RIO System thing that will enable the auto scan on startup (so if you restart openHAB - it will rescan your MCA system for any new things [if you enabled new zones, new sources, etc] and will place the new stuff in your inbox.

HABPANEL widget
1) The channels must be named a specific way - if you autodiscovered AND enabled "Simple Mode" in the Paperui (configuration->system) - you should be fine.  If not, don't even try this until I've documented it.
2) You need to link a BUNCH of new channels (many are under the "Show More" button for the various things).  The following list the channels that must be linked
2a) Rio System:  allon, sources
2b) Controller (nothing)
2c) Zone: name, source, bass, treble, balance, loudness, turnonvolume, donotdisturb, partymode, status, volume, mute, repeat, shuffle, rating, keyrelease, keycode, event, systemfavorites, zonefavorites, presets, mminit, mmcontextmenu
2d) Source (tuner): name, type, channel, channelname, artistname, albumname, songname, mode, programservicename, radiotext, radiotext2, radiotext3, radiotext4, banks
2c) Source (non-tuner): name, type, channel, channelname, artistname, albumname, coverarturl, playlistname, songname, rating, mode, shufflemode,repeatmode, mmscreen, mmtitle, mmmenu, mmattr, mmmenubuttonoktext,mmmenubuttonbacktest, mminfotext,mmhelptext, mmtextfield
3) Open HAPPANEL and go into edit on whichever dashboard
4) Add the russound widget (Add Widget->Custom Widget cog->Import) - choose the "Russound.widget.json" in "conf/html/Russound"
5) Hit the settings (the vertical bar->Edit) and under "Zone Name Channel" - choose the zone name channel (that specifies the zone the widget is for). Should be similar to "russound_zone_(widgetid)_(controllerid)_(zoneid)_name".
6) Get out of edit - and play with the widget

**Comment by Tomtibo** [comment]
Hi Tim! I'v just try the discovery feature but it's do not work for me. The logs show the scan but it's only scan ip from 192.168.1.1 to 192.168.1.30, and the device is not on this range. I thing it should scan from 192.168.1.1 to 192.168.1.255. Here is the log:

`01:25:01.915 [DEBUG] [nternal.discovery.RioSystemDiscovery] - >> starting scan
01:25:01.921 [DEBUG] [nternal.discovery.RioSystemDiscovery] - Starting scan of 192.168.11.
01:25:01.927 [DEBUG] [nternal.discovery.RioSystemDiscovery] - Scanning 192.168.11.1, 192.168.11.2, 192.168.11.3, 192.168.11.4, 192.168.11.5, 192.168.11.6, 192.168.11.7, 192.168.11.8, 192.168.11.9, 192.168.11.10
01:25:01.929 [DEBUG] [nd.internal.net.SocketChannelSession] - Connecting to 192.168.11.1:9621
01:25:01.930 [DEBUG] [nternal.discovery.RioSystemDiscovery] - Scanning 192.168.11.21, 192.168.11.22, 192.168.11.23, 192.168.11.24, 192.168.11.25, 192.168.11.26, 192.168.11.27, 192.168.11.28, 192.168.11.29, 192.168.11.30
01:25:01.930 [DEBUG] [nternal.discovery.RioSystemDiscovery] - Scanning 192.168.11.11, 192.168.11.12, 192.168.11.13, 192.168.11.14, 192.168.11.15, 192.168.11.16, 192.168.11.17, 192.168.11.18, 192.168.11.19, 192.168.11.20
01:25:01.936 [DEBUG] [nd.internal.net.SocketChannelSession] - Connecting to 192.168.11.21:9621
01:25:01.937 [DEBUG] [nd.internal.net.SocketChannelSession] - Connecting to 192.168.11.11:9621
01:25:02.185 [DEBUG] [nternal.discovery.RioSystemDiscovery] - Connection couldn't be established to port 192.168.11.1:9621
01:25:02.188 [DEBUG] [nd.internal.net.SocketChannelSession] - Connecting to 192.168.11.2:9621
01:25:02.190 [DEBUG] [nternal.discovery.RioSystemDiscovery] - Connection couldn't be established to port 192.168.11.21:9621
01:25:02.191 [DEBUG] [nternal.discovery.RioSystemDiscovery] - Connection couldn't be established to port 192.168.11.11:9621
01:25:02.197 [DEBUG] [nd.internal.net.SocketChannelSession] - Connecting to 192.168.11.12:9621
01:25:02.193 [DEBUG] [nd.internal.net.SocketChannelSession] - Connecting to 192.168.11.22:9621
01:25:02.443 [DEBUG] [nternal.discovery.RioSystemDiscovery] - Connection couldn't be established to port 192.168.11.2:9621
01:25:02.445 [DEBUG] [nd.internal.net.SocketChannelSession] - Connecting to 192.168.11.3:9621
01:25:02.451 [DEBUG] [nternal.discovery.RioSystemDiscovery] - Connection couldn't be established to port 192.168.11.12:9621
01:25:02.455 [DEBUG] [nternal.discovery.RioSystemDiscovery] - Connection couldn't be established to port 192.168.11.22:9621
01:25:02.458 [DEBUG] [nd.internal.net.SocketChannelSession] - Connecting to 192.168.11.23:9621
01:25:02.464 [DEBUG] [nd.internal.net.SocketChannelSession] - Connecting to 192.168.11.13:9621
01:25:02.701 [DEBUG] [nternal.discovery.RioSystemDiscovery] - Connection couldn't be established to port 192.168.11.3:9621
01:25:02.703 [DEBUG] [nd.internal.net.SocketChannelSession] - Connecting to 192.168.11.4:9621
01:25:02.711 [DEBUG] [nternal.discovery.RioSystemDiscovery] - Connection couldn't be established to port 192.168.11.23:9621
01:25:02.714 [DEBUG] [nd.internal.net.SocketChannelSession] - Connecting to 192.168.11.24:9621
01:25:02.721 [DEBUG] [nternal.discovery.RioSystemDiscovery] - Connection couldn't be established to port 192.168.11.13:9621
01:25:02.724 [DEBUG] [nd.internal.net.SocketChannelSession] - Connecting to 192.168.11.14:9621
01:25:02.956 [DEBUG] [nternal.discovery.RioSystemDiscovery] - Connection couldn't be established to port 192.168.11.4:9621
01:25:02.959 [DEBUG] [nd.internal.net.SocketChannelSession] - Connecting to 192.168.11.5:9621
01:25:02.968 [DEBUG] [nternal.discovery.RioSystemDiscovery] - Connection couldn't be established to port 192.168.11.24:9621
01:25:02.971 [DEBUG] [nd.internal.net.SocketChannelSession] - Connecting to 192.168.11.25:9621
01:25:02.977 [DEBUG] [nternal.discovery.RioSystemDiscovery] - Connection couldn't be established to port 192.168.11.14:9621
01:25:02.980 [DEBUG] [nd.internal.net.SocketChannelSession] - Connecting to 192.168.11.15:9621
01:25:03.212 [DEBUG] [nternal.discovery.RioSystemDiscovery] - Connection couldn't be established to port 192.168.11.5:9621
01:25:03.215 [DEBUG] [nd.internal.net.SocketChannelSession] - Connecting to 192.168.11.6:9621
01:25:03.225 [DEBUG] [nternal.discovery.RioSystemDiscovery] - Connection couldn't be established to port 192.168.11.25:9621
01:25:03.228 [DEBUG] [nd.internal.net.SocketChannelSession] - Connecting to 192.168.11.26:9621
01:25:03.233 [DEBUG] [nternal.discovery.RioSystemDiscovery] - Connection couldn't be established to port 192.168.11.15:9621
01:25:03.236 [DEBUG] [nd.internal.net.SocketChannelSession] - Connecting to 192.168.11.16:9621
01:25:03.468 [DEBUG] [nternal.discovery.RioSystemDiscovery] - Connection couldn't be established to port 192.168.11.6:9621
01:25:03.470 [DEBUG] [nd.internal.net.SocketChannelSession] - Connecting to 192.168.11.7:9621
01:25:03.483 [DEBUG] [nternal.discovery.RioSystemDiscovery] - Connection couldn't be established to port 192.168.11.26:9621
01:25:03.485 [DEBUG] [nd.internal.net.SocketChannelSession] - Connecting to 192.168.11.27:9621
01:25:03.489 [DEBUG] [nternal.discovery.RioSystemDiscovery] - Connection couldn't be established to port 192.168.11.16:9621
01:25:03.492 [DEBUG] [nd.internal.net.SocketChannelSession] - Connecting to 192.168.11.17:9621
01:25:03.723 [DEBUG] [nternal.discovery.RioSystemDiscovery] - Connection couldn't be established to port 192.168.11.7:9621
01:25:03.726 [DEBUG] [nd.internal.net.SocketChannelSession] - Connecting to 192.168.11.8:9621
01:25:03.739 [DEBUG] [nternal.discovery.RioSystemDiscovery] - Connection couldn't be established to port 192.168.11.27:9621
01:25:03.742 [DEBUG] [nd.internal.net.SocketChannelSession] - Connecting to 192.168.11.28:9621
01:25:03.744 [DEBUG] [nternal.discovery.RioSystemDiscovery] - Connection couldn't be established to port 192.168.11.17:9621
01:25:03.747 [DEBUG] [nd.internal.net.SocketChannelSession] - Connecting to 192.168.11.18:9621
01:25:03.979 [DEBUG] [nternal.discovery.RioSystemDiscovery] - Connection couldn't be established to port 192.168.11.8:9621
01:25:03.981 [DEBUG] [nd.internal.net.SocketChannelSession] - Connecting to 192.168.11.9:9621
01:25:03.997 [DEBUG] [nternal.discovery.RioSystemDiscovery] - Connection couldn't be established to port 192.168.11.28:9621
01:25:03.999 [DEBUG] [nternal.discovery.RioSystemDiscovery] - Connection couldn't be established to port 192.168.11.18:9621
01:25:03.999 [DEBUG] [nd.internal.net.SocketChannelSession] - Connecting to 192.168.11.29:9621
01:25:04.002 [DEBUG] [nd.internal.net.SocketChannelSession] - Connecting to 192.168.11.19:9621
01:25:04.234 [DEBUG] [nternal.discovery.RioSystemDiscovery] - Connection couldn't be established to port 192.168.11.9:9621
01:25:04.237 [DEBUG] [nd.internal.net.SocketChannelSession] - Connecting to 192.168.11.10:9621
01:25:04.253 [DEBUG] [nternal.discovery.RioSystemDiscovery] - Connection couldn't be established to port 192.168.11.29:9621
01:25:04.255 [DEBUG] [nternal.discovery.RioSystemDiscovery] - Connection couldn't be established to port 192.168.11.19:9621
01:25:04.256 [DEBUG] [nd.internal.net.SocketChannelSession] - Connecting to 192.168.11.30:9621
01:25:04.257 [DEBUG] [nd.internal.net.SocketChannelSession] - Connecting to 192.168.11.20:9621
01:25:04.490 [DEBUG] [nternal.discovery.RioSystemDiscovery] - Connection couldn't be established to port 192.168.11.10:9621
01:25:04.510 [DEBUG] [nternal.discovery.RioSystemDiscovery] - Connection couldn't be established to port 192.168.11.20:9621
01:25:04.510 [DEBUG] [nternal.discovery.RioSystemDiscovery] - Connection couldn't be established to port 192.168.11.30:9621

`

**Comment by Tomtibo** [comment]
If I try to manually create RussoundRio thing, then all things are discovered! Also, when restarting the russound binding, I get a warm message. And reviewed the doc... because zone volume does not work anymore..
 Can we still use Dimmer item (PoucentType), for a zone volume channel?(scaling 0-100 to 0-50)

> 03:03:06.644 [WARN ] [core.internal.items.ItemRegistryImpl] - Could not add item: Value must be between 0 and 100
java.lang.IllegalArgumentException: Value must be between 0 and 100
	at org.eclipse.smarthome.core.library.types.PercentType.validateValue(PercentType.java:51)[98:org.eclipse.smarthome.core:0.9.0.b4]
	at org.eclipse.smarthome.core.library.types.PercentType.<init>(PercentType.java:46)[98:org.eclipse.smarthome.core:0.9.0.b4]
	at org.eclipse.smarthome.core.library.types.DecimalType.as(DecimalType.java:151)[98:org.eclipse.smarthome.core:0.9.0.b4]
	at org.eclipse.smarthome.core.library.items.DimmerItem.setState(DimmerItem.java:76)[98:org.eclipse.smarthome.core:0.9.0.b4]
	at org.eclipse.smarthome.core.persistence.internal.PersistenceManagerImpl.initialize(PersistenceManagerImpl.java:256)[103:org.eclipse.smarthome.core.persistence:0.9.0.b4]
	at org.eclipse.smarthome.core.persistence.internal.PersistenceManagerImpl.added(PersistenceManagerImpl.java:394)[103:org.eclipse.smarthome.core.persistence:0.9.0.b4]
	at org.eclipse.smarthome.core.persistence.internal.PersistenceManagerImpl.added(PersistenceManagerImpl.java:1)[103:org.eclipse.smarthome.core.persistence:0.9.0.b4]
	at org.eclipse.smarthome.core.internal.items.ItemRegistryImpl.allItemsChanged(ItemRegistryImpl.java:105)[98:org.eclipse.smarthome.core:0.9.0.b4]
	at org.eclipse.smarthome.model.item.internal.GenericItemProvider.modelChanged(GenericItemProvider.java:341)[123:org.eclipse.smarthome.model.item:0.9.0.b4]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:207)[122:org.eclipse.smarthome.model.core:0.9.0.b4]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:99)[122:org.eclipse.smarthome.model.core:0.9.0.b4]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:272)[122:org.eclipse.smarthome.model.core:0.9.0.b4]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.access$1(FolderObserver.java:265)[122:org.eclipse.smarthome.model.core:0.9.0.b4]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver$WatchQueueReader.processWatchEvent(FolderObserver.java:146)[122:org.eclipse.smarthome.model.core:0.9.0.b4]
	at org.eclipse.smarthome.core.service.AbstractWatchQueueReader.run(AbstractWatchQueueReader.java:122)[98:org.eclipse.smarthome.core:0.9.0.b4]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]


> 02:54:39.554 [INFO ] [marthome.event.ItemStateChangedEvent] - RussVolZ4 changed from 0 to 1
02:54:39.555 [WARN ] [pse.smarthome.core.items.GenericItem] - failed notifying listener '[org.eclipse.smarthome.core.persistence.internal.PersistenceManagerImpl@8881d8, RussVolZ4, Value must be between 0 and 100]' about state update of item java.lang.IllegalArgumentException: Value must be between 0 and 100: {}

**Comment by tmrobert8** [comment]
[org.openhab.binding.russound-2.1.0-SNAPSHOT.zip](https://github.com/openhab/openhab2-addons/files/854638/org.openhab.binding.russound-2.1.0-SNAPSHOT.zip)

That was a really stupid mistake on my part (a bug prevented the over .30+ scan).  Attached is the one that should work - give it a try if you will.  The doc is REALLY obsolete right now - don't follow it.  Many channels have been added/dropped/changed and I haven't caught the doc up with it yet.  Volume changed to be a simple decimal type (not a percentage) - was having issues with scaling believe it or not.  

Do you use happanel at all?  I've almost got my russound widget fully working and will hopefully be posting that again soon...

**Comment by tmrobert8** [comment]
[RussoundHabPanel.zip](https://github.com/openhab/openhab2-addons/files/858050/RussoundHabPanel.zip)

This is the latest habpanel zip - still testing and it still has a few bugs but is looking pretty good.  Unzip into "conf/html" - then import "Russound.widget.json" into your habpanel dashboard.  This version also needs the Controller->Zones channel linked to switch to different zones (note: you need to unlock that in settings - otherwise it's locked to the one zone).

**Comment by tmrobert8** [comment]
New version of Russound HabPanel - supports vertical and horizontal layouts
[RussoundHabPanel.zip](https://github.com/openhab/openhab2-addons/files/868950/RussoundHabPanel.zip)

**Comment by tmrobert8** [comment]
New Version of both the binding and the hap panel - give them a try!
[RussoundHapPanel.zip](https://github.com/openhab/openhab2-addons/files/896479/RussoundHapPanel.zip)
[org.openhab.binding.russound-2.1.0-SNAPSHOT.zip](https://github.com/openhab/openhab2-addons/files/896480/org.openhab.binding.russound-2.1.0-SNAPSHOT.zip)

**Comment by martinvw** [comment]
@tmrobert8 has this been implemented in https://github.com/openhab/openhab2-addons/pull/2135?

If yes can you agree that this is then completed and that this issue can be closed?

**Comment by martinvw** [comment]
@tmrobert8 any update about this? Is it done or not?

**Comment by tmrobert8** [comment]
@martinvw 
Didn't notice you responded to this and didn't get an email notification - weird.  This one was merged in #2135 and I'll close this.
