### ISSUE TITLE
Feature request influxdb: use different retention policies

### ISSUE THREAD

**Issue by staehler** [openhab/openhab2-addons#1975]
The influxdb writes all collected data to the default retention policy at the moment. I have data which need to be stored for just a few days and others I want to store for some year (e.g. energy consumption). At the moment all data are stored for the maximum timespan (default policy) and fills my hdd. Is there a way to enhance the binding to accept more than one retention policy.
Just an idea: would it be possible to define the retention policy within the influxdb.persist like
```
        gInfluxDB*			: strategy = everyChange, everyDay, restoreOnStartup, rp_one_year
        gInfluxDB1*			: strategy = everyChange, everyDay, rp_one_day
        gZeitsteuerung*		: strategy = everyChange, everyDay, restoreOnStartup
```
rp_one_year (the retention policy name has to be defined in influxdb) would hold the data for one year, rp_one_day would hold them for one day and if no retention policy is given, then use the default retention policy.
Would be nice to see such a feature, as the persisted data waste my hdd.

Thanks and regards
Michael

**Comment by wborn** [comment]
The InfluxDB persistence addon code is part of the openhab1-addons project.
Please use the openhab1-addons [issue tracker](https://github.com/openhab/openhab1-addons/issues) for feature requests for this addon.
