### ISSUE TITLE
[homematic] Transmitters do not link to Contact items (HM-PB- , HM-HM-RC- )

### ISSUE THREAD

**Issue by robbyb67** [openhab/openhab2-addons#1978]
In homematic 1.x extensions the HM wireless wall switches and remote controls could be bound to Contact items. As these devices are only transmitting this behaviour was completely logical to me.

In homematic 2.x binding linking a SHORT_PRESS or LONG_PRESS channel to a contact item does not work. The item will never change its state. When linked to a switch item an ON event is followed by an OFF event, which is understandable too.

Is it possible to enable linking to a Contact too ? If not - please add a hint to the bindigs page and the 1.x migration guide.

**Comment by MHerbst** [comment]
Generally it is possible to link two different channels to the same item. This will of course only work if they are compatible, i.e. are using the same value types. As far as I know there is an open problem with channels that are connected this way #1794.

As a bypass you could write a rule where you react on changes.

**Comment by robbyb67** [comment]
To be clear - this is not about linking the same Item to different channels!

In your words it seems to be the case that HM wall transmitters are no longer compatible to Contact items (OpenCloseType respectively).

**Comment by MHerbst** [comment]
There probably was a misunderstanding and I must say that I don't know the Homematic 1.x binding. 

When I read "contact item" I thought of a window contact device. If I understand it correct you want to use an item of type "contact" and link it to a SHORT_PRESS resp. LONG_PRESS channel. This will probably not work because the Contact type only knows the values "OPEN" and "CLOSEE". To solve it you would have create a virtual contact item and use a rule to set it.

**Comment by robbyb67** [comment]
Understood and ok - but there should be a hint for migration in the documentation because thats an significant change in operation.

From the technical point of view the HM transmitters are nothing other than "manually operated" door or window contacts. They only sense an open or closed state. 
Switches on the other side normally can "do" something like HM actors ... but thats of cause some kind of philosophy. ;-)

**Comment by mdicke2s** [comment]
@robbyb67 What is the outcome of this issue? Is there any change necessary in the binding or do we need to adapt the documentation? If not, I would suggest to close this issue

**Comment by robbyb67** [comment]
From my point of view the binding should be changed. 
HM transmitter (Wall and Hand) channels should be of OpenCloseType rather that OnOffType.

**Comment by mdicke2s** [comment]
This issue was moved to eclipse/smarthome#5780
