### ISSUE TITLE
[chromecast] Be more specific about callbackUrl

### ISSUE THREAD

**Issue by ShaunCurrier** [openhab/openhab2-addons#1984]
In the Chromecast binding [README.md](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.chromecast/README.md), it is not super clear what the `callbackUrl` is used for or what it should typically be set to.  It just says:

`the binding needs to know the url to access`

and

`optional Callback URL - url to use for playing notification sounds, e.g. http://192.168.0.2:8080`

I used a random port on my main openHAB web gui IP and it worked.  After experimenting with the binding, it seems pretty clear that this is not a Chromecast device URL and is perhaps supposed to be the interface address and port that the Chromecast activity will bind to, but I'm not sure.

**Comment by maggu2810** [comment]
Let's assume the machine your Chromecast binding is running has multiple network interfaces and every network interface uses at least one network address.
Let's further assume the networks are different and your Chromecast is only available in one network and so could be accessed only by one interface and address of your binding.
If the binding access the Chromecast it does not matter, but if the Chromecast access the binding the correct address needs to be used.
For simple setup the default should works fine.
If you e.g. use the notification featuer, so an audio file present on the machine the binding is running should be played by the Chromecast, the audio file is made available on an internal web server, the URL to that file is send to the Chromecast and the Chromecast tries to access that file.
This is the place the callbackUrl is used.

**Comment by ShaunCurrier** [comment]
I understand the root concepts there, but it's still not clear to me what the callback URL is in plain terms.

Is the callback URL telling the binding what interface, address and port to bind to for outgoing communication that carries out the Chromecast api?

Is the callback URL used to bind a web server that is auto configured by the binding and hosting sound files to be played via incoming connections from the Chromecast (removing the need to set up an independent web server)?

The callback URL is _____. (Fill in the blank)

**Comment by maggu2810** [comment]
It is the part in front of the relative URL:
https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/handler/ChromecastHandler.java#L378

**Comment by martinvw** [comment]
@ShaunCurrier @maggu2810 is this all clear now? Should/could we update the README or can this issue be closed? Thanks!

**Comment by ShaunCurrier** [comment]
It's still not clear to me what this is, but it seems I'm the only one, and I can live without understanding it. Feel free to close.

**Comment by CWempe** [comment]
This is absolutely not clear!

Why would anybody assume that you need to configure your openHAB ip there?

I will update the README, when I have enough information to update other parts of this documentation.

This issue can be reopend if you like.

**Comment by richaardvark** [comment]
Years later, this is **_still not clear_** and the documentation is still limited.
