### ISSUE TITLE
[Chromecast] Add a "Limitations" section to README.md, incl. groups limitation

### ISSUE THREAD

**Issue by ShaunCurrier** [openhab/openhab2-addons#1985]
The Chromecast binding's [README.md](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.chromecast/README.md) could use a section with known limitations of the binding.

At least one item that should be included is that Chromecast groups are not supported. A Chromecast group is, for example, something that allows multiple Chromecast audio devices can be synced and treated as one device.  The binding will detect the group and allows adding it as a Thing, but it will not play content like the individual devices can with the binding.

**Comment by mcguiresean** [comment]
Hi @ShaunCurrier. Just FYI, my PR #1882 added support for audio groups.

**Comment by ShaunCurrier** [comment]
Awesome. Maybe I should close this issue then since I know of no other limitations.
