### ISSUE TITLE
Add labels for github issues/PRs

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab2-addons#1986]
It would be great if every binding has its own label here. Sonos and z-wave have one, so why no labels for other bindings/uis.
For clarity a pattern like "binding/kodi" or "oi/homekit" might be good.

**Comment by MHerbst** [comment]
Generelly I like this idea because it would make it much easier to filter issues. But it would only work if all creators of issue would be allowed to assign a label. I don't know whether it is possible to allow this to everybody.

**Comment by mueller-ma** [comment]
@MHerbst From Github Help https://help.github.com/articles/applying-labels-to-issues-and-pull-requests/

> Assign labels to issues and pull requests to help organize your projects. You can do this in repositories to which you have write access.

**Comment by kaikreuzer** [comment]
And this is exactly the problem. It does not allow issue reporters to use these labels and for the maintainers it is simply too much overhead to keep up with this.

**Comment by mueller-ma** [comment]
It's possible to create issue templates (one for each binding) and add a label to this template. If a user creates an issue with a template, the label is auto assigned. It's also possible to add assignees.
