### ISSUE TITLE
[Sonos] SaveAll gives error when parsing metadata.

### ISSUE THREAD

**Issue by tnemrap** [openhab/openhab2-addons#1988]
I receive this when i try to do SaveAll

>2017-03-03 22:45:02.131 [ERROR] [inding.sonos.internal.SonosXMLParser] - Could not parse MetaData from string '{"service":{"name":"spotify-connect"}}'

**Comment by hmerk** [comment]
@tnemrap Does this issue still exist ? If so, please close it here and open a new one at https://github.com/eclipse/smarthome, as the SONOS Binding has moved to ESH quite a while ago.
Otherwise just close this issue.
