### ISSUE TITLE
[Astro] Season name does not match dates for seasons

### ISSUE THREAD

**Issue by aness-github** [openhab/openhab2-addons#1996]
Using Astro Binding for OpenHAB2 the date of Spring is set to "2017-02-20", however Season name is set to "Winter".

Correct date of Spring seems to be "2017-03-20", https://www.calendardate.com/year2017.php

See also Issue #1995, these both seems to be an off by one error on dates.

**Comment by martinvw** [comment]
The astro binding is now moved to Eclipse Smarthome, if needed please (re)open an issue there.
