### ISSUE TITLE
[Z-Way] ON / OFF command not working for dimmers

### ISSUE THREAD

**Issue by TS-Tec** [openhab/openhab2-addons#1998]
While playing with the HomeKit OH integration, I recognized, that the on and off command do not work for dimmers. I then checked with the Karaf console and it is same behavior:

`smarthome:send ZWay_Dimmer_Item percent_value` works fine (also 0 and 100!)

`smarthome:send ZWay_Dimmer_Item ON` or `smarthome:send ZWay_Dimmer_Item OFF` don't work. 
No change of the Z-Wave-Device.

In the log, I can see, that the item changes but it looks like it is not recognized by the Z-Way-Server (nothing happens):

`[INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'ZWay_Dimmer_Item' received command ON
[INFO ] [marthome.event.ItemStateChangedEvent] - ZWay_Dimmer_Item changed from 0 to 100`

This means, the show value of the item is not the real value as of the Z-Way device!

**Comment by TS-Tec** [comment]
Hi @pathec,

can you tell me how to do this?
In the PaperUI it shows only 2.0.0 version.
How can I update a single binding?

Thanks for your support!!

**Comment by pathec** [comment]
Hi,

I think you have to update your openHAB, because PaperUI should display `binding-zway - 2.1.0.SNAPSHOT`.

Do you use Beta- or Snapshot Release?

**Comment by TS-Tec** [comment]
Snapshot. I run OpenHABian.

I tried apt-get update and upgrade but nothing changes... What is the best way to do this?
Sorry I am not a Linux or OH2 expert...

**Comment by pathec** [comment]
Ok, I found this: http://docs.openhab.org/installation/linux.html#changing-versions and http://docs.openhab.org/installation/openhabian.html#switch-openhab-branch, but I've never used openHABian. I would try: `sudo apt-get install openhab2=2.1.0`

**Comment by TS-Tec** [comment]
Isn't there a way to update only this single binding?
My System runs very well at the moment and I don't wanna get into trouble...

@ThomDietrich I thought the OpenHABian-Config tool update function does all this. How do I get OpenHABian to the latest version?

**Comment by TS-Tec** [comment]
BTW:  There is no OpenHab version 2.1.0 available.
Only the binding has an updated version. Reinstalling OH2 did not updated the binding.
Is it possible to install ist separately? Maybe with the Karaf Console (bundle or feature function)?

**Comment by pathec** [comment]
Ok, I'm not sure what to do. But I think @ThomDietrich can help you.

**Comment by pathec** [comment]
A quick fix might be to download the binding (https://openhab.ci.cloudbees.com/job/openHAB2-Bundles/lastSuccessfulBuild/org.openhab.binding$org.openhab.binding.zway/) manually and copy it into the addons folder. But I think you have to uninstall the Z-Way binding first via PaperUI.

**Comment by ThomDietrich** [comment]
Hey guys,
openHABian doesn't do anything special in this area. The solution by @pathec is the one to go 👍  Good luck! @TS-Tec you might have write permission problems on the addons folder via samba. Ping me if you need help with that.

**Comment by TS-Tec** [comment]
Thanks for your support!

@ThomDietrich Indeed I would appreciate your support!
I am confused because I can't find the original installation folder of the binding. And I am not sure what of the new files have to be copied.
Is it possible to clarify this directly with you? This would be great!! Thanks in advance!!

**Comment by TS-Tec** [comment]
I found this in the community:

[https://community.openhab.org/t/how-to-install-a-snapshot-version-of-a-binding-in-a-oh2b4-installation/14254](url)

Do you think this will work also with the ZWay-Binding?

Will all things be kept? I am afraid of losing my whole configuration...

**Comment by pathec** [comment]
The configuration of the Z-Way Binding? Or other bindings? The Z-Way Binding configuration is probably deleted. But the description should work.

One possibility would be to save the configuration. I guess the complete configuration is stored in the JSON DB. So if you back up the files from the folder `/openhab2/userdata/jsondb/` and copy back after the update, everything should be as before.

Maybe someone can confirm this?

**Comment by ThomDietrich** [comment]
I'm also not certain but yes, that should do the trick. You should do a backup before such changes. If anything goes wrong, you can restore from the backup. In case your devices are lost with the change of the binding version (which I'd believe will not happen) you should be able to restore them with the jsondb.
So what you need to do: 1. backup 2. uninstall binding 3. copy the snapshot binding to the addons folder 4. restore configuration if needed.

**Comment by TS-Tec** [comment]
OK, I will try this.

What is confusing for me:
The addons folder is empty (I think because I installed all addons via PaperUI and they are stored in a different place). But is the handling the same if they are located in a different location? Will the configuration via PaperUI still be possible?
I could imagine that the way via Karaf console (bundle:install) is better but I only found very poor documetation about the handling...

**Comment by pathec** [comment]
Yes, Bindings installed via PaperUI are stored in a different place. That's why you have to uninstall the Z-Way Binding first via PaperUI. The handling in PaperUI is the same!

**Comment by ThomDietrich** [comment]
The addons folder is intended specifically for sideloaded addons. All fine ;)

**Comment by TS-Tec** [comment]
Guys I did something very stupid, but had the luck that it seems to work:
I added the nightly and beta repos to my apt-sources and performed a apt-get update and upgrade. I thought it would only use stable versions but it updated to the latest SNAPSHOT!

I was very afraid to destroy everything but after I started OH again, all seems to work well and also my Z-Way Problem ist solved! (So this issue can be closed I think).

What do you propose? Should I stay at this SNAPSHOT and do some updates from time to time or should I restore backup and try to do it like we discussed before?

Do you know when OH 2.1 will become a stable release?

Never the less, thanks for your support!!

**Comment by TS-Tec** [comment]
> Closing this issue is something you'll have to do yourself.

👍 :)
