### ISSUE TITLE
[yahoo] Enter a city name rather than the woeid

### ISSUE THREAD

**Issue by volkmarnissen** [openhab/openhab2-addons#2001]
Currently, the location in the weather binding is a number, the woeid. 
Isn't it better to be able to use the city name?
This is possible with the following query:

select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="\<cityname\>")

If both (woeid and cityname) can be entered in the location field, it should be possible to change the binding without disrupting the existing functionality.

**Comment by wborn** [comment]
If you are still using the [Weather Binding](https://docs.openhab.org/addons/bindings/weather1/readme.html) with Yahoo weather, you can enter your request in the openhab1-addons [issue tracker](https://github.com/openhab/openhab1-addons/issues).

There is also a [YahooWeather Binding](https://docs.openhab.org/addons/bindings/yahooweather/readme.html) nowadays. Please enter issues /requests for that binding in the Eclipse SmartHome [issue tracker](https://github.com/eclipse/smarthome/issues).
