### ISSUE TITLE
Eclipse IDE setup  Issuse for Openhab Development

### ISSUE THREAD

**Issue by amarpulli544** [openhab/openhab2-addons#2007]
Hi,

I am unable to launch openhab runtime in Eclipse neon2  IDE. Don't know what happend? but getting some issues while launch the Openhab run time. I could not see any plug-ins in launching wizard. I didn't get any updates from Eclipse IDE. I also check for updates, but no were updates.  see below screen shot

![openhab](https://cloud.githubusercontent.com/assets/16384828/23643555/8f59107a-0328-11e7-901b-2aa15cbea4ab.png)

While launch the openhab runtime getting below issue

```
!SESSION Tue Mar 07 11:25:32 IST 2017 ------------------------------------------
!ENTRY org.eclipse.equinox.launcher 4 0 2017-03-07 11:25:32.172
!MESSAGE Exception launching the Eclipse Platform:
!STACK
java.lang.ClassNotFoundException: org.eclipse.core.runtime.adaptor.EclipseStarter
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:670)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)

```
My System Configuration:

Java version: 1.8
Eclipse IDE: Neon2
OS: Windows 7 Ultimate(64 bit)

Please let me know the any one facing same issue. how to resolve ?

Thanks,
Amar.

**Comment by mherwege** [comment]
I have the same issue. I tought it was me making a mistake somewhere, so tried many different things and could not get it to work. I did notice the eclipse smarthome repository was not accessible. That may have something to do with it. I also was not able to locally build anymore as the dependencies could not be resolved.

**Comment by kaikreuzer** [comment]
There was an issue with the ESH p2 repo, which should be fixed now.
Could you please check again?

**Comment by mherwege** [comment]
It works for me now. Thanks Kai.

**Comment by amarpulli544** [comment]
Now, it is been working for me. Thanks Kai.
