### ISSUE TITLE
MAX! binding properties support

### ISSUE THREAD

**Issue by marcelrv** [openhab/openhab2-addons#201]
Improvement of the binding to support the configured properties for the thermostats

* ValveOffset:            
* Temp Offset
* Decalcification:       
* ValveMaximum:           
* Temp Eco:               
* Duration Open Windoww:  
* Temp Open Window:       
* Temp Comfort:           
* Temp Setpoint Min:      
* Temp Setpoint Max:      
* Duration Boost:         
* ProgramData:

**Comment by kaikreuzer** [comment]
@marcelrv, Can this be closed?

**Comment by marcelrv** [comment]
@kaikreuzer ,

No, further developments on this are in progress, This enhancement is more or less a placeholder for a larger set of PR's to finally fully support configuration of the MAX! devices.

#217 was the first one, showing the generic properties/configuration.
The next one, currently in progress, will show the remaining properties/configurations specific to the thermostats.

With that, the display functions will be done, and I can start the actual configuring of the thermostats through the OH/habmin interface (to no longer need to rely on the vendor configuration program anymore)
.

**Comment by kaikreuzer** [comment]
ok, I see you are keeping track yourself, thanks :-)

**Comment by kaikreuzer** [comment]
Is this still in the making?

**Comment by marcelrv** [comment]
yes indeed, is going slow due to a new family member in the making as well. That project is finished now :)
latest work related to this here
https://github.com/marcelrv/openhab2/tree/device-config

**Comment by kaikreuzer** [comment]
@marcelrv Can we close this now?

**Comment by marcelrv** [comment]
close... but not fully there.
The last piece I want to provide as part of this enhancement is in testing.
There is an issue I need to investigate before I can make the PR for it. (one of the properties is not getting updated well)

**Comment by kaikreuzer** [comment]
Well, just create new PRs with improvements whenever you are ready with them - I think there is no need to track this anymore through additional issues.
