### ISSUE TITLE
[avmfritz] User "openhab" has no access to smart home functions

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab2-addons#2014]
Thing stays offline and says something similar to "User "openhab" has no access to smart home functions". After restarting oh2 the items goes online

**Comment by cweitkamp** [comment]
Hi, I read a lot posts with similar situation, so I uploaded a version with advanced debug logging for the authentication algorithm for screwing the FRITZ!Box in the binding. There is only one line of code which sets the bridge item to offline with the given messages. Can you please download my version, install it manually, activate debug logging and post the corresponding debug lines in this issue. That would help a lot. Thanks.

**Comment by mueller-ma** [comment]
How do I install it manually?

**Comment by cweitkamp** [comment]
To answer that question I need to know which setup you are using. Linux ([see here](http://docs.openhab.org/installation/linux.html#installing-add-ons))? Windows ([see here](http://docs.openhab.org/installation/windows.html#file-locations))? Other? In general you can place your own addon files in the /usr/share/openhab2/addon/ folder (on linux based setups). I suggest to uninstall the old avmfritz binding first.

**Comment by mueller-ma** [comment]
@cweitkamp I think its better to setup a snapshot oh on a similar vm than my stable oh. When I install snapshot from apt repos, does it include your changes?

**Comment by cweitkamp** [comment]
Of course, why not. But my changes are not in the snapshot. You can only benefit from them if you install the binding manually.

**Comment by cweitkamp** [comment]
@mueller-ma All my changes are merged into latest snapshots. Could you be so kind and verify, if your problems are still there?

**Comment by mueller-ma** [comment]
Sry, but I dont have enough time and resources to set up a second openhab for testing

**Comment by lovwyr** [comment]
One short remark, on newer Fritz!Box Models the Userauth via Username/Password is not enabeld by Default. It can be enabled under System -> FRITZ!Box-Users -> 2nd Tab.

**Comment by mueller-ma** [comment]
I cannot really remember that I ever saw a Fritzbox with user authentication enabled by default
