### ISSUE TITLE
Cannot get service reference for transformation service of type JSONPath

### ISSUE THREAD

**Issue by decologne** [openhab/openhab2-addons#2022]
I'm running OH2 Snapshot 2.1.0 build latest , manual installed.
I installed JSONPath by Paper UI.
11:40:24.773 [INFO ] [smarthome.event.ExtensionEvent      ] - Extension 'transformation-jsonpath' has been installed.
The next item rule:
number lamp2power "Sonoff Pow switch [%d ]" {mqtt="<[broker:tele/sonoff_A03597/ENERGY:state:JSONPath($.Current)]"}
generate the warning:
11:40:47.156 [WARN ] [.core.transform.TransformationHelper] - Cannot get service reference for transformation service of type JSONPath
What do I wrong ?

**Comment by kaikreuzer** [comment]
Please use our forum at https://community.openhab.org/ for support - thanks!
