### ISSUE TITLE
[Homematic] HM-CC-RT-DN Thermostat 'SIGNAL_STRENGTH' & 'RSSI'

### ISSUE THREAD

**Issue by Andirs55** [openhab/openhab2-addons#2029]
Hello my logs are flodded with the following entries from my thermostats:

```
2017-03-12 22:13:57.778 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'NEQ0871188:0#RSSI'
2017-03-12 22:13:57.778 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'NEQ0871188:0#SIGNAL_STRENGTH'
```

which is correct because only these two channels regarding rssi and signal strength exist:

homematic:HG-HM-CC-RT-DN:xxx:NEQ0871188:0#RSSI_DEVICE
homematic:HG-HM-CC-RT-DN:xxx:NEQ0871188:0#RSSI_PEER

Using the latest OH2 snapshot and homegear.

**Comment by MHerbst** [comment]
RSSI and SIGNAL_STRENGHT are "virtual datapoints" that are calculated based on real homematic datapoints. AFAIK they exist for all devices and there should always be a channel. I did not check it with the latest snapshot but I can remember that these channels worked correct (at least with a CCU and not Homegear). 
I think this is something for @gerrieg

**Comment by gerrieg** [comment]
Did you add the Things via PaperUI or via config file? If you are using PaperUI, remove the Thing an add it again.

**Comment by Andirs55** [comment]
Things were added via PaperUI. I removed and readded them and now it seems to work, thanks
