### ISSUE TITLE
Add Rademacher DuoFern Binding

### ISSUE THREAD

**Issue by CWempe** [openhab/openhab2-addons#2047]
It would be great if anybody could develop a binding for [Rademacher DuoFern](https://www.rademacher.de/hausautomation-homepilotr/rolllaeden-per-funk-steuern/).

For starters there is already an implementation in FHEM.
I guess the source code might help creating the binding.

https://github.com/mhop/fhem-mirror/blob/f3bb0be1177d61f5e8a45f74666938233ad13cbe/fhem/FHEM/10_DUOFERNSTICK.pm
https://github.com/mhop/fhem-mirror/blob/f3bb0be1177d61f5e8a45f74666938233ad13cbe/fhem/FHEM/30_DUOFERN.pm

**Comment by CWempe** [comment]
As a work around, I created a tutorial who to connect DuoFern devices via Fhem and Mqtt.

https://community.openhab.org/t/rademacher-duofern-via-fhem-and-mqtt/26322

**Comment by trokohl** [comment]
Rademacher offers also a JSON API 
http://www.imakeyouintelligent.com/rademacher-homepilot-json-api-via-webbrowser-ansteuern/ (GERMAN)

I could imagine to develop an add-on, but I only have roller shutter actuators.
Maybe someone is interested in developing a bridge together and/or have other devices.

**Comment by CWempe** [comment]
You need the expensive Homepilot to use the JSON-API.

**Comment by trokohl** [comment]
Ah okay. You don’t want to use the Homepilot.

I have a Homepilot but i try to bundle up all my different device to one (openHAB).

**Comment by woanne67** [comment]
@wborn Where can I find the Rademacher DuoFern Binding and does it work without Homepilot?
Thanks.

**Comment by wborn** [comment]
There is no binding for this yet @woanne67. This issue is a feature request for such a binding. 

You could follow the [Rademacher DuoFern via Fhem and MQTT](https://community.openhab.org/t/rademacher-duofern-via-fhem-and-mqtt/26322?u=wborn) tutorial by @CWempe as a workaround for this.

**Comment by davidgraeff** [comment]
The Github issue list is not a wish list though. If someone has the intention to develop a binding that can be stated here. Closing for now.
