### ISSUE TITLE
Binding creation script generates with the wrong version of `org.openhab.binding`

### ISSUE THREAD

**Issue by sdwilsh** [openhab/openhab2-addons#2059]
Both `create_openhab_binding_skeleton.cmd` and `create_openhab_binding_skeleton.sh` set the version of `org.openhab.binding` to `2.0.0-SNAPSHOT`, which fails the build.  I believe it should be set to `2.1.0-SNAPSHOT` (that at least got my build working for a binding I'm working on).

**Comment by kaikreuzer** [comment]
Yes, that one was missed indeed after the 2.0.0 release. Would you want to create a PR with the fix?

**Comment by cweitkamp** [comment]
I created PR [#2074](https://github.com/openhab/openhab2-addons/pull/2074) to solve this one.

**Comment by sdwilsh** [comment]
Thanks @cweitkamp!  I haven't had time to circle back to this yet, so that was much appreciated :D

**Comment by cweitkamp** [comment]
Hey @sdwilsh, you are welcome. I stumbled over this problem today and took some minutes to solve it.
