### ISSUE TITLE
[Milight] Discovery detects Orvibo S20 as V6 Bridge

### ISSUE THREAD

**Issue by tavalin** [openhab/openhab2-addons#2090]
I've just updated my runtime to build 856 which seems to contain the recently merged Milight changes.  I opened PaperUI and noticed there was a new discovery in my inbox, to my surprise the Milight binding has discovered my Orvibo S20 as a V6 bridge 😆 I was quite amused that it even managed to extract the MAC address from the UDP packet.

**Comment by davidgraeff** [comment]
OMG. I can imagine this. I detect MilightV6 bridges by just the default ethernet chip response string, which is the recommended way at the moment.
