### ISSUE TITLE
Item labels deleted after reboot (Raspberry pi 3)

### ISSUE THREAD

**Issue by ajuveneton** [openhab/openhab2-addons#2092]
Hello,
I'm running OH2 on a Raspberry pi 3 (installed with apt-get)
In Paper UI, I've created Things/Items with "Network" and "Freebox" bindings.
It works pretty well except that when I reboot my RPI, the items labels are deleted.
Known issue? Am I doing something wrong?
Best regards.

Arnaud

**Comment by kaikreuzer** [comment]
This is a known issue and related to the (unfortunately not yet fixed) issue https://github.com/eclipse/smarthome/issues/1550.
