### ISSUE TITLE
Freebox binding: no more working with firmware 3.4

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab2-addons#2108]
Free has introduced a new version of the FreeboxOS API with the firmware 3.4 (API v4.0).
The library the binding relies on is no more fully compatible with the new API version. I opened an issue and will try to fix it: https://github.com/MatMaul/freeboxos-java/issues/6

**Comment by lolodomo** [comment]
I have a hotfix ready.
I am just waiting for a potential quck merge today of the PR relative to static logger that impacts the freebox binding.

**Comment by kaikreuzer** [comment]
Merged!

**Comment by lolodomo** [comment]
PR submitted..

**Comment by lolodomo** [comment]
Closed by merged PR #2112
