### ISSUE TITLE
Rule Engine (Experimental) NullPointerException

### ISSUE THREAD

**Issue by mackelito** [openhab/openhab2-addons#2123]
The rule get´s triggered at the correct time but throws this error
2017-03-31 22:13:03.088 [ERROR] [.automation.core.internal.RuleEngine] - Fail to execute rule '[rule_2, null]': java.lang.NullPointerException

Running the rule manually by clicking the play icon works fine.

**Comment by sjka** [comment]
Thanks for reporting this bug. However, may I ask you to open this bug in another project? I know it's confusing, but the rule engine is maintained in the [eclipse/smarthome](https://github.com/eclipse/smarthome) project. So could you please the same issue there? 

If you see in your logs anything in addition which would give us a clue where to start with the analysis (e.g. a stacktrace) it would be very helpful to directly include it there.

**Comment by mackelito** [comment]
Done!
For reference: https://github.com/eclipse/smarthome/issues/3212

**Comment by mackelito** [comment]
This has been resolved in https://github.com/eclipse/smarthome/issues/3029

But how do I update to use latest master?

**Comment by kaikreuzer** [comment]
Use openHAB 2.1.0-SNAPSHOT, which includes this fix since 2 months :-)

**Comment by mackelito** [comment]
Sorry for the delay in responding...
hmmm so It should be updated when running "Update System" in the configuration tool right?

**Comment by mackelito** [comment]
Ah I see that I see run "openHAB 2.0.0-1 (Release Build)"... how to run "openHAB 2.1.0-SNAPSHOT"?
