### ISSUE TITLE
[Squeezebox] Track duration

### ISSUE THREAD

**Issue by mikaelgu80** [openhab/openhab2-addons#2124]
I'd like to request that the duration of the currently playing track be added as a thing, it's available in the CLI documentation.

**Comment by mhilbush** [comment]
@mikaelgu80 I can take a look at this.  I assume you mean to add the track duration as a channel on the player thing.  One thing I'm not sure about is how duration is handled for streaming sources, such as Pandora, Spotify, Internet radio, etc.

I have a couple other things going on right now, so I may not get to this right away...

**Comment by mikaelgu80** [comment]
Yes, definitely a channel on the thing, that's what you get for writing something a 6:30 in the morning... But thank you! I think that for streams it just reports 0 for the duration, at least that's what's showing on the web app for squeezebox.

**Comment by mhilbush** [comment]
Looks like some remote streaming services give duration (e.g. Pandora) and some don't (e.g. Internet radio).

**Comment by mikaelgu80** [comment]
I actually only use My Music (mp3 and flac), airplay and a few internet radio stations. In my oppinion it would be prefectly acceptable to show whatever value the server is spitting out, whether it be 0 or the real duration.

**Comment by mhilbush** [comment]
@mikaelgu80 I added the duration channel.  If you want to try it out before the change is merged, you can find it [here](https://github.com/mhilbush/squeezebox).

**Comment by mikaelgu80** [comment]
Awesome! Thank you very much, I'll have a look when I have some spare time.

**Comment by mhilbush** [comment]
@mikaelgu80 As you see above, the change was merged.
