### ISSUE TITLE
Air Quality: daylight savings not respected for observation time

### ISSUE THREAD

**Issue by metbril** [openhab/openhab2-addons#2141]
Since a few weeks we live in summertime in the Netherlands. The observation time is 1 hour off. The current time is 20:50 and the last observation time is 21:00. That's not ok. My guess is that the time calculation in the binding does not take DST into account.

Cc @kubawolanin 
![img_0309](https://cloud.githubusercontent.com/assets/559346/24840101/2129660a-1d67-11e7-94ba-2bc132496025.PNG)

**Comment by consolacion** [comment]
Noticed that too
