### ISSUE TITLE
Add Synaccess Netbooter Binding

### ISSUE THREAD

**Issue by CABrouwers** [openhab/openhab2-addons#2143]
Synaccess netbooters [http://www.synaccess-net.com](url) are remote power source management devices with multiple independent outlets. They also include RMS AC current reading and environment temperature monitoring. They can be controlled byTelnet. 
I have developed a binding for this family of devices, which I would like submit.

**Comment by martinvw** [comment]
@CABrouwers please create a PR when you are ready, note that we have a rather large queue so it could take some time before its merged.

In the meanwhile you could publish your binding to the marketplace, see: https://community.openhab.org/t/distributing-bindings-through-the-iot-marketplace/24491

**Comment by davidgraeff** [comment]
No progress. Closing.
