### ISSUE TITLE
[SystemInfo] missing channel 'memory#usedPercent'

### ISSUE THREAD

**Issue by rtvb** [openhab/openhab2-addons#2146]
I use memory used percentage next to CPU used percentage for server monitoring.
I currently need a simple rule to create the item, but hope the value will be added as a dedicated channel.

Current channels:

- memory#available
- memory#availablePercent
- memory#used

current items:
```xtend
Number System_Memory_Total            "Geheugen (totaal)      [%.0f MB]" (System)        { channel="systeminfo:computer:local:memory#total" }
Number System_Memory_Available        "Geheugen (beschikbaar) [%.0f MB]" (System)        { channel="systeminfo:computer:local:memory#available" }
Number System_Memory_AvailablePercent "Geheugen (beschikbaar) [%.2f %%]" (System, Chart) { channel="systeminfo:computer:local:memory#availablePercent" }
Number System_Memory_Used             "Geheugen (gebruikt)    [%.0f MB]" (System)        { channel="systeminfo:computer:local:memory#used" }
Number System_Memory_UsedPercent      "Geheugen (gebruikt)    [%.2f %%]"  (System, Chart)
```

current rule:
```xtend
rule "MemUsedPercent"
when
	Item System_Memory_AvailablePercent changed
then
	System_Memory_UsedPercent.postUpdate(100-(System_Memory_AvailablePercent.state as DecimalType))
end
```

**Comment by cweitkamp** [comment]
The same is true for channel groups swap and storage (no swap#usedPercent or storage#usedPercent).

The values returned by all availablePercent channels is calculated in the binding, so I assume we can do the same for the usedPercent values.

I am looking into that.

**Comment by cweitkamp** [comment]
Find PR here: [#2207](https://github.com/openhab/openhab2-addons/pull/2207)
