### ISSUE TITLE
Homekit does not pair

### ISSUE THREAD

**Issue by justeagler** [openhab/openhab2-addons#2177]
Hello,
I'm using Openhab2 (openhabian installation) for some months, everything works great except homekit.
I have some items created in PaperUI and another ones created manually (OH1.x way).

At moment, homekit installed successfully, it recognises openhab items but does not pair with any iOS device (tried with my iPhone 6S, iPad Air 2, iPhone 5S, another iPhone 6S, all of them with iOS 10).

The situation point is:
- Homekit is installed successfully;
- Homekit is configured as described in the documentation (https://github.com/openhab/openhab2-addons/tree/master/addons/io/org.openhab.io.homekit);
- In the logs everything looks great at this point, home kit starts and recognise openhanded items (tagged ones)
<img width="1440" alt="screen shot 2017-04-19 at 01 35 40" src="https://cloud.githubusercontent.com/assets/5799170/25159551/61fc76d4-24a8-11e7-892a-7752e8e4f8d5.png">
- I see the accessories json in browser and logs if set smarthome:homekit allowUnauthenticated true
- but home app and even eve app doesn't find any home kit device..

Anyone can help me please?

Note: I don't know if theres any cache/legacy issues with old houses but in my old installation of openhab I had the homebridge addon running with the homekit, before Apple release the home app in iOS10.

**Comment by justeagler** [comment]
Solved!

I discovered that was a problem in my router that blocks bonjour protocol that Apple uses to expose homekit devices.

With some telnet commands I had unlocked the multicast filter on my router interfaces and solved the problem.

Good luck!

**Comment by martinvw** [comment]
@justeagler thanks for reporting back!

**Comment by oliverrahner** [comment]
Thanks @justeagler, this brought me on the right track! I use an "FRITZ!WLAN Repeater 300E" by AVM as a secondary Access Point and had connected OpenHAB via Wifi.
Turns out, the 300E doesn't support Multicast via Wifi, only on the wire.

**Comment by kevinhab** [comment]
I think it's my problem too. But I can't find Multicast function on my Access Point Device ( vigor AP 910C )

**Comment by justeagler** [comment]
I had fixed it by telnet.

**Comment by skatehouse** [comment]
how?

**Comment by justeagler** [comment]
Each router has their own Operating System so you must search specific commands to disable the multicast filter on your router.

Cheers

No dia 03/01/2018, às 23:09, skatehouse <notifications@github.com> escreveu:
