### ISSUE TITLE
About.html files not included in the build.properties file

### ISSUE THREAD

**Issue by svilenvul** [openhab/openhab2-addons#2178]
While working on a check for the static-analysis-tool that verifies the content of the build.properties file, I have noticed that in the most of the bundles the about.html file is not included in the build.properties file.

I assume that we would like to include the about.html file in the binary build.

I will extend the AboutHtmlCheck to verify that the about.html file is included in the build.properties file and create a PR that will fix the current code base in the OH2 addons repo.

@kaikreuzer, please let me know if it is not expected always to include the about.html file in the build.properties file.

**Comment by kaikreuzer** [comment]
Fully agree - good catch!
