### ISSUE TITLE
[PioneerAVR] Support for Pioneer SC-2023

### ISSUE THREAD

**Issue by dyankodyankov** [openhab/openhab2-addons#2180]
Hello,

I am using OpenHab2 with OpenHabian. My avr receiver and the bluray player both come from Pioneer.
The reciever is a SC-2023. Through the existing Pioneer binding I can control Zone 1 but Zone 2 doesn't work. As I know this binding officially supports only models older than 2012 and as such lacks support for the newer ones. Are there any plans to update it so the newer models are supported as well?

My other issue is that there is no support at all for the bluray players. I have a BDP-450 and it is discovered as an AV device but cannot be controlled. It would be wonderful if support could be added to the binding.

Thank you.

Best regards,
Dyanko

**Comment by Celaeno1** [comment]
Try this for your AVR:

https://github.com/Stratehm/openhab2-addons/releases/tag/2016-12-22

**Comment by dyankodyankov** [comment]
Hi Alex,

thank you a lot and sorry for answering with such a delay.

I managed to uninstall the most recent binding through the Karaf console and to install the proposed snapshot (genericAVR). Now I have following problem: the AVR is discovered and gets the right name (model name) but it stays "Offline" regardless of what I do. Do you have a solution for this?

Thank you in advance.

**Comment by Celaeno1** [comment]
Are you sure that correct binding is installed? Please check with karaf console:
`bundle:list`
`235 | Active   |  80 | 2.0.0.201612222234     | PioneerAvr Binding`

Be sure that 'TCP port' is configured correct . You can try 'TCP port' 8102 or 23. Both are possible.

Then you should do the following: 

- shutdown openhab
- power off SC-2023
- power on SC-2023
- start openhab

Once the SC-2023 is detected correctly it should work.

**Comment by wborn** [comment]
Can you already properly control your SC-2023 receiver and BDP-450 bluray player using the PioneerAVR binding @dyankodyankov?

**Comment by dyankodyankov** [comment]
Hi,

I haven't played with openHab for a while but think that it worked the last time I tested. I will try it out when I am back home on Thursday and let you know. 

@Celaeno1 : Here I'd like to thank you Alex for your help. It is almost an year gone since your last comment but you helped me back then :-)

**Comment by dyankodyankov** [comment]
Hello again,

as I promised I checked the functionality of PioneerAVR binding at home. It works perfectly for the SC-2023, even Zone 2. Everything works as expected. 

What I cannot do is control the bluray player BD-450. This is not part of the functionality of the bindig. But it would be nice if someone could create a binding for controlling the players as well :-)

Regards,
Dyanko
