### ISSUE TITLE
[homekit] Thermostat Tags

### ISSUE THREAD

**Issue by mavris** [openhab/openhab2-addons#2184]
Hi,
I have successfully integrated home kit to my open hab and it works great so far!
But I tried to setup the thermostat using your example and I get  "No Response" on HomeKit app.
Any ideas why?
```
Group gLivingRoomThermostat "Living Room Air Condition" [ "Thermostat" ]
Number livingRoomCurrentTemp "Living Room Air Condition Current Temperature" (gLivingRoomThermostat) [ "CurrentTemperature" ]
Number livingRoomTargetTemperature "Living Room Air Condition Target Temperature" (gLivingRoomThermostat) [ "TargetTemperature" ]
String livingRoomHeatingCoolingMode "Living Room Air Condition Heating/Cooling Mode" (gLivingRoomThermostat) [ "homekit:HeatingCoolingMode" ]
```

**Comment by trailblazer2006** [comment]
Take a look at this https://github.com/beowulfe/HAP-Java/issues/37. Seems to be your problem discussed there.

**Comment by kaikreuzer** [comment]
Fixed by https://github.com/openhab/openhab2-addons/pull/4535
