### ISSUE TITLE
rfxcom: way to toggle discovery 

### ISSUE THREAD

**Issue by rotulet** [openhab/openhab2-addons#2186]
Hi, 
I am using openHab 2.1.0 with a RFXCom transceiver and I receiving all the 433 Mhz frames from the neighboring. So my openhab InBox is constantly filled with items not coming from my house. I would like to know if there is a way to stop the auto discovery from rfxcom binding? 
If not, it should a very nice feature !

Thanks.

**Comment by martinvw** [comment]
If you click the ignore button (an eye with line across) they should be gone and not come back.

Do you use that option or do you remove them, because then they are supposed to return.

**Comment by rotulet** [comment]
Yes I can ignore some items by the light bulbs they use (LIGHT4 and LIGHT5) often change their id (may be they are not installed the way they should) and the inbox keep filling. They also have a SECURITY1 sensor showing sometime.

**Comment by martinvw** [comment]
LIGHTING4 is a bug and will be fixed in a future release, I was not aware about problems of LIGHTING5. SECURITY1 I also saw in my own setup although the amount of different items seemed limited (and this appeared after a quite recent upgrade of the firmware)

**Comment by rotulet** [comment]
I have just ignored all of them. So, I will be able to tell you how long it takes for them to re-appear. 
Besides, is there a way to stop the discovery process?

**Comment by martinvw** [comment]
No it's not a process in this case just unrecognized/unmatched messages

**Comment by rotulet** [comment]
So there is not way to add a parameter to handle or ignore the new unrecognized/unmatched messages?

**Comment by martinvw** [comment]
Correct

**Comment by rotulet** [comment]
Is there a workaround you can suggest?

**Comment by mjagdis** [comment]
For me it's CHIMEs that pile up. These RF protocols are inherently unreliable and generally just spew the same message several times for "redundancy" (yeah, no checksums or parity :-( ). I suspect rfxcom tries to remove duplicates and sanitise obvious noise but CHIMES in particular are just about all ID so distinguishing signal from noise is... tricky.

Try this:
[org.openhab.binding.rfxcom-2.1.0-SNAPSHOT.zip](https://github.com/openhab/openhab2-addons/files/1019581/org.openhab.binding.rfxcom-2.1.0-SNAPSHOT.zip)

Look on the config page for your bridge and turn the "Disable discovery" switch on.

**Comment by mjagdis** [comment]
And again, with the right default (i.e. discovery enabled)
[org.openhab.binding.rfxcom-2.1.0-SNAPSHOT.zip](https://github.com/openhab/openhab2-addons/files/1019629/org.openhab.binding.rfxcom-2.1.0-SNAPSHOT.zip)

**Comment by rotulet** [comment]
Sorry I was away for a long time! Great modifications! I will check this new snapshot asap. Thanks!
