### ISSUE TITLE
Globalcache Discovery Multicast Listener discovering non-Globalcache devices

### ISSUE THREAD

**Issue by swamiller** [openhab/openhab2-addons#2188]
Globalcache binding discovery service is finding my Onkyo amp and listing as an "unknown" globalcache device.  A new globalcache Thing is also being created. The "unknown" globalcache thing cannot be deleted.  Attempting to delete/remove the thing creates an "Error 500: Internal Server Error" message.  

The following INFO item populates the openhab.log about every 30ish seconds:
`2017-04-21 11:33:30.520 [INFO ] [balcache.discovery.MulticastListener] - Multicast listener doesn't know how to parse beacon: AMXB<-SDKClass=Receiver><-Make=ONKYO><-Model=TX-NR646><-Revision=1.0.0><-UUID=00:09:b0:d9:b2:a2><Port=60128>`

This anomaly seems related to the recently closed issue #2172.

**Comment by mhilbush** [comment]
@swamiller Thanks for reporting this.  I wasn't aware that other types of devices, such as receivers, used the same multicast port and beacon format.  I'll push a change that simply ignores unknown beacons, and reduces the logging level to debug.

As for the inability to delete, I'm not sure I see why #2172 would be related to the inability to delete the thing.

**Comment by swamiller** [comment]
@mhilbush I think the inability to delete issue is because OH doesn't handle unknown devices, not directly related to #2172 but became evident because of the change.


![image](https://cloud.githubusercontent.com/assets/17254439/25318477/1f965be2-2855-11e7-9502-fef8422b4544.png)

**Comment by mhilbush** [comment]
@swamiller Is the issue deleting the inbox entry, or deleting the thing?  From the image above, it looks like it's in the inbox.

By any chance, do you use HABmin?  If so, do you get the same error when you try to delete using HABmin?

**Comment by swamiller** [comment]
@mhilbush For closure...yes, the error was in the inbox and does occur with Habmin as well.  I disabled the globalcache discovery service.  I'd love some direction on getting this thing out of my inbox, if you don't mind?

**Comment by mhilbush** [comment]
@swamiller The easiest way to get rid of it would be to do the following:
- stop openhab
- edit the file `userdata/jsondb/org.eclipse.smarthome.config.discovery.DiscoveryResult.json`, and remove everything except for `{}`
- save the file
- start openhab

The inbox entry should be gone.

Sorry that this caused you a problem.  In a day or two I'll push a new version of globalcache that prevents this from occurring.
