### ISSUE TITLE
CalDAV Configuration and Refresh Problems

### ISSUE THREAD

**Issue by Auto-Mark** [openhab/openhab2-addons#2195]
Migrating to openHAB2 I've managed to overcome some hurdles of the CalDAV binding. However, the following problems remain:

* Starting up there are often warnings and errors that may differ every time without any changes in the configuration, such as "Unable to parse configuration parameter" even if it definetely is OK.
The configuration has been done by editing the files caldavio.cfg and caldavPersonal.cfg in the /services folder. It appears that the configuration made in these files also is stored somewhere else: When adding an error to the configuration file it gets flagged. After removing this error it still gets flagged .

* When starting openHAB2 the calendar entries are loaded. After that the CalDAV binding doesn't update its items. That means when anything is added or changed in the calender this is not reflected in openHAB. Only simple calendar entries are used so far, no repeating events, no jobs. Different settings for reloadInterval and preloadTime didn't have any effect on that.

Issues:
* shadow copy of configuration isn't kept in sync with configuration files (is there a workaround?)
* CalDAV doesn't refresh its data

**Comment by kaikreuzer** [comment]
As far as I am aware, there is no CalDAV binding in this repo... If you are talking about the openHAB 1 version of the binding, please report the issue at https://github.com/openhab/openhab1-addons or first discuss it at https://community.openhab.org/ - thanks!
