### ISSUE TITLE
Homematic Gateways-Extras missing and not linkable

### ISSUE THREAD

**Issue by Xento** [openhab/openhab2-addons#2202]
Hello
I have a problem with the Gateways-Extras.
I had a thing Gateway-Extras but it was offline (Device GWE000000... not found on ...) and I couldn't link items.
So I deleted this thing but now it's not discovered anymore.
The gateway is fixed to ccu-type.
Where can I send you the startup log?

**Comment by MHerbst** [comment]
Which version of the binding are you using? I think there have been some corrections since the 2.0 release.

You can attach the log to the issue.

**Comment by Xento** [comment]
I was on the snapshot from 22.04.
Now I downgraded to 2.0.0~RC1-1 and it is working again.

**Comment by MHerbst** [comment]
@Xento Can you try it again with the latest snapshot version?

**Comment by Xento** [comment]
It's not working with the latest snapshot.
Downgrade to 2.0.0~RC1-1 and it is working again.

**Comment by MHerbst** [comment]
Hmmm strange, works in my environment without problems. Which firmware version has your CCU?

**Comment by Xento** [comment]
2.27.8 is my firmware version.
How can I help you?

**Comment by MHerbst** [comment]
@Xento  I would need a trace log. You can attach it here to your message.

Two more questions: 
- Firmware 2.27.8 introduced a firewall to the CCU this firewall needs to be opened for openHAB. I assume that you did it but please check it again.
- do  you have an Osram Lightify system connected to your CCU?

**Comment by Xento** [comment]
I will add a trace, when I have time to capture one.
The firewall is configured to be open for my local network.
Yes I use Osram Lightify on my CCU. Could this cause the issue?

**Comment by MHerbst** [comment]
Yes it is probably caused by Osram Lightify, please look at issue #2373. You can download a corrected binding from here: https://openhab.jfrog.io/openhab/online-repo-snapshot/2.1/org/openhab/binding/org.openhab.binding.homematic/2.1.0-SNAPSHOT/org.openhab.binding.homematic-2.1.0-SNAPSHOT.jar
