### ISSUE TITLE
Add support for KNX DPT 20.102

### ISSUE THREAD

**Issue by TinusK** [openhab/openhab2-addons#2203]
OpenHAB version 2.0.0 (Release Build)

Item:
```
String Heating_MF_Living_HVAC
	"HVAC"
	(gMF_Living, gHVAC)
	["HVAC"]
	{ knx="20.102:3/3/81" }

```
OpenHAB Log:
```
[ERROR] [el.item.internal.GenericItemProvider] - Binding configuration of type 'knx' of item 'Heating_MF_Living_HVAC' could not be parsed correctly.
org.eclipse.smarthome.model.item.BindingConfigParseException: DPT 20.102 is not supported by the KNX binding.
```

ETS (data on the knx bus):
```
#	Time	Service	Flags 	Prio	Source Address	Source Name	Destination Address	Destination Name	Rout	Type	DPT	Info
6057	4/25/2017 08:03:21.555	to bus		Low	1.2.253	-	3/3/81	MF - Dining + Living	6	Read		$00
6058	4/25/2017 08:03:21.606	from bus		Low	1.2.41	AKH-0400.02 Heating actuator 4-fold, 2TE,24/230VAC	3/3/81	MF - Dining + Living	6	Response	  20.102 HVAC mode	$02 | Standby
```

If I remove the '20.102:' from the binding
```
String Heating_MF_Living_HVAC
	"HVAC"
	(gMF_Living, gHVAC)
	["HVAC"]
	{ knx="3/3/81" }
```
then I get the following error from OpenHAB:
`10:07:03.367 [INFO ] [g.knx.internal.dpt.KNXCoreTypeMapper] - Translator couldn't parse data for datapoint type '16.001' (KNXIllegalArgumentException).`

The above error message remains the same for Item type String or Number.

KNX Datapoint Type 20.102 can have the following data:
$00 Auto
$01 Comfort
$02 Standby
$03 Economy
$04 Building Protection

Maybe the KNX DPT 20.102 could be added?

Thank you,
Tinus

**Comment by kaikreuzer** [comment]
Assuming you are talking about the KNX 1.x binding, please report this at https://github.com/openhab/openhab1-addons or first discuss it at https://community.openhab.org/. Thanks!

**Comment by TinusK** [comment]
Sorry, my mistake.

Thanks.
Tinus

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by lewie** [comment]
@kgoderis, same Todo in KNX2. Since java 1.8 can be used, we should do 
simpler DTP import in KNXCoreTypeMapper. 

Reflection would simplify: https://github.com/openhab/openhab2-addons/pull/1438#issuecomment-286389026

**Comment by saperlot** [comment]
HI @lewie, do you know the state of the 20.102 integration? i would love to use it. btw: any workaround to use it without having support of this dpt?

**Comment by lewie** [comment]
This is the PR for for your question: https://github.com/openhab/openhab1-addons/pull/5277

This is a Testfile for you, with the PR #5277 included: https://github.com/lewie/openhab/raw/66ba140713eecee5fd16541da6b1cb3564d27306/org.openhab.binding.knx-1.11.0-genericKNXCoreTypeMapper%235277.jar

20.102 should work, if not, please tell me here your results: https://github.com/openhab/openhab1-addons/pull/5277

**Comment by lewie** [comment]
@saperlot, 20.102 is mapped to StringType in openHAB at the moment.
But:

> KNX Datapoint Type 20.102 can have the following data:
> $00 Auto
> $01 Comfort
> $02 Standby
> $03 Economy
> $04 Building Protection

would tend to be a DecimalType.

**Comment by walmins** [comment]
hello!
do you have any issue for DPT 20.102? 
i use actuly insted of 20.102 =>  DPT 5.010 and this work fine.

Thanks

**Comment by walmins** [comment]
Hi TinusK!
