### ISSUE TITLE
Z-Wave database update: ECOLINK Garage Door Tilt Sensor

### ISSUE THREAD

**Issue by whit98c** [openhab/openhab2-addons#2224]
Hello, this item is not creating a nodeX.xml file (node 9 below). It seems to work with sensor_binary 255/0.

https://www.amazon.com/gp/product/B00HGVJRX2/ref=oh_aui_detailpage_o02_s00?ie=UTF8&psc=1

20:23:21.734 [DEBUG] [ssage.ApplicationCommandMessageClass] - NODE 9: Application Command Request (FAILED:PING)
20:23:21.736 [DEBUG] [ng.zwave.internal.protocol.ZWaveNode] - NODE 9: Node is ALIVE. Init stage is PING.
20:23:21.737 [DEBUG] [ve.internal.protocol.ZWaveController] - Notifying event listeners: ZWaveNodeStatusEvent
20:23:21.739 [DEBUG] [alization.ZWaveNodeInitStageAdvancer] - NODE 9: Node Status event during initialisation - Node is ALIVE
20:23:21.741 [DEBUG] [alization.ZWaveNodeInitStageAdvancer] - NODE 9: Node advancer - PING: queue length(0), free to send(true)
20:23:21.743 [DEBUG] [alization.ZWaveNodeInitStageAdvancer] - NODE 9: Node advancer: loop - PING try 1: stageAdvanced(false)
20:23:21.744 [DEBUG] [alization.ZWaveNodeInitStageAdvancer] - NODE 9: Node advancer: PING - send NoOperation
20:23:21.746 [DEBUG] [ndclass.ZWaveNoOperationCommandClass] - NODE 9: Creating new message for command No Operation
20:23:21.748 [DEBUG] [alization.ZWaveNodeInitStageAdvancer] - NODE 9: Node advancer - queued packet. Queue length is 1
20:23:21.750 [DEBUG] [ve.internal.protocol.ZWaveController] - Message queued. Queue length = 1. Queue={}
20:23:21.750 [DEBUG] [ocol.ZWaveController$ZWaveSendThread] - Took message from queue for sending. Queue length = 0
20:23:21.751 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 9: Got an event from Z-Wave network: ZWaveNodeStatusEvent
20:23:21.753 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 9: Setting ONLINE
20:23:21.754 [DEBUG] [wave.internal.protocol.SerialMessage] - Assembled message buffer = 01 08 00 13 09 01 00 25 1F D6
20:23:21.758 [DEBUG] [ing.zwave.handler.ZWaveSerialHandler] - NODE 9: Sending REQUEST Message = 01 08 00 13 09 01 00 25 1F D6
20:23:21.757 [DEBUG] [ve.internal.protocol.ZWaveController] - NODE 9: Node Status event - Node is ALIVE
20:23:21.761 [DEBUG] [ssage.ApplicationCommandMessageClass] - NODE 9: Incoming command class SENSOR_BINARY
20:23:21.763 [DEBUG] [dclass.ZWaveBinarySensorCommandClass] - NODE 9: Received SENSOR_BINARY command V0
20:23:21.765 [DEBUG] [dclass.ZWaveBinarySensorCommandClass] - NODE 9: Sensor Binary report, type=Unknown, value=255
20:23:21.767 [DEBUG] [ve.internal.protocol.ZWaveController] - Notifying event listeners: ZWaveBinarySensorValueEvent
20:23:21.769 [DEBUG] [alization.ZWaveNodeInitStageAdvancer] - NODE 9: CC event during initialisation stage IDLE
20:23:21.770 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 9: Got an event from Z-Wave network: ZWaveBinarySensorValueEvent
20:23:21.772 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 9: Got a value event from Z-Wave network, endpoint = 0, command class = SENSOR_BINARY, value = 255
20:23:21.776 [DEBUG] [WaveSerialHandler$ZWaveReceiveThread] - Receive Message = 01 04 01 13 01 E8
20:23:21.777 [DEBUG] [ssage.ApplicationCommandMessageClass] - NODE 11: Transaction not completed: node address inconsistent.  lastSent=11, incoming=255
20:23:21.780 [DEBUG] [ve.internal.protocol.ZWaveController] - Receive queue TAKE: Length=0
20:23:21.783 [DEBUG] [wave.internal.protocol.SerialMessage] - Assembled message buffer = 01 04 01 13 01 E8
20:23:21.785 [DEBUG] [ve.internal.protocol.ZWaveController] - Process Message = 01 04 01 13 01 E8
20:23:21.787 [DEBUG] [ve.internal.protocol.ZWaveController] - Message: class=SendData[0x13], type=Response[0x01], priority=High, dest=255, callback=0, payload=01
20:23:21.789 [DEBUG] [l.serialmessage.SendDataMessageClass] - NODE 9: Sent Data successfully placed on stack.
20:23:23.890 [DEBUG] [WaveSerialHandler$ZWaveReceiveThread] - Receive Message = 01 09 00 04 04 09 03 30 03 00 CF
20:23:23.898 [DEBUG] [ve.internal.protocol.ZWaveController] - Receive queue TAKE: Length=0
20:23:23.903 [DEBUG] [wave.internal.protocol.SerialMessage] - Assembled message buffer = 01 09 00 04 04 09 03 30 03 00 CF
20:23:23.907 [DEBUG] [ve.internal.protocol.ZWaveController] - Process Message = 01 09 00 04 04 09 03 30 03 00 CF
20:23:23.912 [DEBUG] [ve.internal.protocol.ZWaveController] - Message: class=ApplicationCommandHandler[0x04], type=Request[0x00], priority=High, dest=255, callback=0, payload=04 09 03 30 03 00
20:23:23.915 [DEBUG] [ssage.ApplicationCommandMessageClass] - NODE 9: Application Command Request (ALIVE:DETAILS)
20:23:23.919 [DEBUG] [ssage.ApplicationCommandMessageClass] - NODE 9: Incoming command class SENSOR_BINARY
20:23:23.922 [DEBUG] [dclass.ZWaveBinarySensorCommandClass] - NODE 9: Received SENSOR_BINARY command V0
20:23:23.925 [DEBUG] [dclass.ZWaveBinarySensorCommandClass] - NODE 9: Sensor Binary report, type=Unknown, value=0
20:23:23.928 [DEBUG] [ve.internal.protocol.ZWaveController] - Notifying event listeners: ZWaveBinarySensorValueEvent
20:23:23.931 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 9: Got an event from Z-Wave network: ZWaveBinarySensorValueEvent
20:23:23.933 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 9: Got a value event from Z-Wave network, endpoint = 0, command class = SENSOR_BINARY, value = 0

**Comment by martinvw** [comment]
You might have more luck at https://github.com/openhab/org.openhab.binding.zwave/issues
