### ISSUE TITLE
habmin:  add zwave node number to thing attributes

### ISSUE THREAD

**Issue by TheKorn2** [openhab/openhab2-addons#2226]
Please add what zwave node number a device is to the habmin thing attribute window.  Right now if a device fails initialization it's more or less impossible to figure out what node number a problem thing is to correlate with in the debug log.

![habmin_request](https://cloud.githubusercontent.com/assets/6579539/25667765/2476a846-2fea-11e7-8b46-768a7ff6f8e2.png)

(This is node 4, but I only know that because I set this test up under oh1 and upgraded!)

**Comment by cdjackson** [comment]
Isn’t it provided in the device configuration?

**Comment by TheKorn2** [comment]
Nope.  :(

(It's not in properties nor description, either.)

![habmin_device_configuration](https://cloud.githubusercontent.com/assets/6579539/25669485/488324bc-2fef-11e7-820d-061fdac05225.png)

**Comment by cdjackson** [comment]
It's in device configuration -:

![image](https://cloud.githubusercontent.com/assets/1041475/25671881/6e28360a-3029-11e7-9de2-77707c506299.png)


This is only true though if you're using the latest branch.

I've also just realised you raised this in the OH2 issue list so in any case this should be closed.

**Comment by TheKorn2** [comment]
Ahh, ok.  I'll figure out how to jump that one up.  Thanks.

Where should I have raised this instead?

**Comment by cdjackson** [comment]
You should raise habmin issues in the habmin issue list, and for zwave issues in the zwave issue list...

**Comment by TheKorn2** [comment]
Here???  https://github.com/openhab/org.openhab.binding.zwave

Can't find anything similar for habmin.  Link would help.

**Comment by cdjackson** [comment]
Yes - habmin should be the same format using the project name /openhab/org.openhab.ui.habmin I think.

**Comment by TheKorn2** [comment]
Nuked install, and re-installed OH2 with the nightly snapshots from 2017-05-01.  Still no node IDs in habmin.

![habmin_no_node_id](https://cloud.githubusercontent.com/assets/6579539/25683211/b33102f8-3020-11e7-9290-598538d99528.png)

**Comment by martinvw** [comment]
Please continue this at https://github.com/openhab/org.openhab.ui.habmin/issues
