### ISSUE TITLE
[CoolMasterNet] Controller state remains UNINITIALIZED

### ISSUE THREAD

**Issue by kusanghi** [openhab/openhab2-addons#2228]
Hi !

we installed the coolmasternet binding into OH2, then add CoolMasterNet Controller, however status of device is "UNINITIALIZED".
See the picture : http://i.imgur.com/04ifebf.jpg and http://i.imgur.com/oIdUomu.jpg
Can you support to resolve this problem? or show me which step i miss?
Thank you,

**Comment by martinvw** [comment]
Are you sure you added the correct host/ip? Can you check the log for any errors? See http://docs.openhab.org/administration/logging.html

Van: kusanghi
Verzonden: donderdag 4 mei 2017 05:11
Aan: openhab/openhab2-addons
CC: Subscribed
Onderwerp: [openhab/openhab2-addons] CoolMasterNet Controller ( UNINITIALIZED )(#2228)

Hi !
we installed the coolmasternet binding into OH2, then add CoolMasterNet Controller, however status of device is "UNINITIALIZED".
See the picture : http://i.imgur.com/04ifebf.jpg and http://i.imgur.com/oIdUomu.jpg
Can you support to resolve this problem? or show me which step i miss?
Thank you,

**Comment by kusanghi** [comment]
My logs 
`2017-05-04 13:24:25.307 [WARN ] [ore.thing.internal.ThingRegistryImpl] - Cannot create thing. No binding found that supports creating a thing of type coolmasternet:controller.
`
I'm sure the correct IP.
I used IP to connect via telnet and sent the command successfully.

**Comment by martinvw** [comment]
How does your config look, see also https://github.com/openhab/openhab2-addons/tree/master/addons/binding/org.openhab.binding.coolmasternet

**Comment by wborn** [comment]
Can you already properly use your CoolMasterNet Controller using the binding @kusanghi?

**Comment by wborn** [comment]
If it still doesn't work you might have more luck with openHAB 2.4.0 which contains a couple of fixes.
See also the openHAB 2.4.0 [release notes](https://github.com/openhab/openhab2-addons/releases/tag/2.4.0).
