### ISSUE TITLE
Rule is not executed when no event name is passed

### ISSUE THREAD

**Issue by kubawolanin** [openhab/openhab2-addons#2229]
Environment / device: openHAB 2.0 Build #905 / RaspberryPI 3B with openHABian

Steps to reproduce:
1. Create a new rule responding to the event channel, e.g.
```
rule "Tide Dash button pressed"
when
    Channel "amazondashbutton:dashbutton:Tide:press" triggered
then
    sendNotification("some@email.com", "Amazon button pressed!")
    sendCommand(Vacuum_Dock, ON)
end
```
or
```
 rule "Xiaomi Switch"
 when
     Channel "mihome:sensor_switch:<ID>:button" triggered
 then
     var actionName = receivedEvent.getEvent()
     switch(actionName) {
         case "CLICK": {
             <ACTION>
         }
         case "DOUBLE_CLICK": {
             <ACTION>
         }
         case "LONG_CLICK_PRESS": {
             <ACTION>
         }
         case "LONG_CLICK_RELEASE": {
             <ACTION>
         }
     }
 end
```
2. Try to trigger the events and see the results

Expected result: The rule is triggered and performed actions should be logged in the console.

Actual result: The rule doesn't trigger, nothing is being logged.

Note that both rules worked for me before I updated the distro to the latest one.

When I pass event name to the `when` section, e.g.
```
Channel "mihome:sensor_switch:<ID>:button" triggered CLICK
```
everything works properly as expected.

**Comment by kubawolanin** [comment]
@kaikreuzer should it be moved to the [eclipse/smarthome](https://github.com/eclipse/smarthome/issues) github or [openhab-core](https://github.com/openhab/openhab-core/issues)? Seems like a general issue.

**Comment by kaikreuzer** [comment]
Yes, please open it at ESH - thanks!

**Comment by kubawolanin** [comment]
Moved here:
https://github.com/eclipse/smarthome/issues/3362
