### ISSUE TITLE
Keba P20 wallbox addon presenting wrong current unit

### ISSUE THREAD

**Issue by GernotHot** [openhab/openhab2-addons#2234]
Hi all,

I am currently integrating one (and later more) Keba P20 (and P30) wallbox into our smart home and I noticed, that the presented current is by factor 1000 to low:
The Webinterface of the wallbox shows a current of 8,15A
![firmware](https://cloud.githubusercontent.com/assets/28429864/25736652/94167700-3173-11e7-9709-ac734d6943c0.jpg)
The addon shows in parallel a value of 8mA (`Number Keba1I1  "Strom Phase 1" {channel="keba:kecontactp20:1:I1"} `)
![kebap20](https://cloud.githubusercontent.com/assets/28429864/25736819/8d42fe84-3174-11e7-8086-03b3447eb326.jpg)
The software release (2.4a1) is quite old indeed, but a new P30c shows the same beaviour.

The most current UDP programmer's guide of KEBA (page 10) states, that the value is sent as [mA], which is confirmed by a wireshark-trace (I1):
![wireshark](https://cloud.githubusercontent.com/assets/28429864/25736921/28a99ec8-3175-11e7-818f-4f216218bf51.jpg)

Thank You!

**Comment by kgoderis** [comment]
This can be assigned to me

**Comment by kgoderis** [comment]
Fixed by https://github.com/openhab/openhab2-addons/pull/2270
