### ISSUE TITLE
Keba P20/P30 feature request: Present serial number and firmware version

### ISSUE THREAD

**Issue by GernotHot** [openhab/openhab2-addons#2236]
Hi all,

as I am planing to integrate some P20 and P30 into my smart home, it would be nice to add an item to present the serial number and the installed firmware into the UI, e.g. 
`Number Serial  {channel="keba:kecontactp20:1:serial", autoupdate="false"}` and
`String Firmware  {channel="keba:kecontactp20:1:firmware", autoupdate="false"}`

First is for easier mapping of the wallbox to the UI by using the unique identifier "serial" (when installing more than two boxes and the latter is for getting an overview over the firmware-states, as KEBA is currently deploying their firmware updates in a quite short interval.

**Comment by kgoderis** [comment]
This can be assigned to me

**Comment by kgoderis** [comment]
@GernotHot Since I only have a P20 at mu disposal right now, could you provide me with the Firmware string that your P30 is returning when requesting a report of type 1?

**Comment by kgoderis** [comment]
@GernotHot to be completely transparent, information like serial numbers of firmware versions are to be considered properties of the Thing, and per se information that is provided through a channel. You would be uniquely identifying the Keba's anyways through their Thing definition and the linked Items.

**Comment by GernotHot** [comment]
@kgoderis I agree on this. Recently, I had to change boxes due to hardware failures and as the new boxes get the same IP (due to DHCP), the thing-definition does not change. In future, when installing a huge number of boxes, the information, which serial number is installed on e.g. "Box 2" might then be helpful ... Well, that's quite a stretch, but I think a possible use case.

At fw-version: the Keba X-model deploys firmware-updates automatically to the c-boxes, but this update-process sometimes failed. This properties might be useful to cross-check, whether the update suceeded or not.

Here the results of the `report 1` request
Box 1 (x-type):
_Please note: the source-IP of a x-box seems to be always "192.168.25.11", no matter, which IP-address is assigned to the public interface of the wallbox_ 
`{
"ID": "1",
"Product": "KC-P30-ES2400C2-E0R",
"Serial": "17191234",
"Firmware":"P30 v 3.08.1 (170213-143648)",
"COM-module": 1,
"Sec": 227
}`

Box 2 (c-type):
`{
"ID": "1",
"Product": "KC-P30-ES240022-E0R",
"Serial": "16881234",
"Firmware":"P30 v 3.07.1a1 (170111-112920)",
"COM-module": 0,
"Sec": 348907
}`

Box 3 (c-type):
`{
"ID": "1",
"Product": "KC-P30-ES240022-E0R",
"Serial": "17231234",
"Firmware":"KEBA P30 v 3.02.4 (160226-065816)",
"Sec": 350005
}`

Box 4 (c-type):
`{
"ID": "1",
"Product": "KC-P30-ES240022-E0R",
"Serial": "17291235",
"Firmware":"P30 v 3.06.2a5 (161209-083000)",
"COM-module": 0,
"Sec": 350106
}`

BR 
GernotHot

**Comment by kgoderis** [comment]
Fixed by https://github.com/openhab/openhab2-addons/pull/2270
