### ISSUE TITLE
Keba P30c feature request:  Using the display of the Wallbox

### ISSUE THREAD

**Issue by GernotHot** [openhab/openhab2-addons#2237]
The new generation of Keba Wallboxes in the connected versions "c" and "x" use an embedded display to present some data on booting (IP-address, firmware and meter values) and after charging (meter values of current session).
Using the UDP protocol, it is possible to present some "server"-generated content:
`display [a] [min] [max] [tk] [text]`
(example: `display 0 0 0 0 12346,6`)

> [a]
= Activates the usage of none default values for the time [text] is displayed.
0 = default (min-time = 2 sec, max-time = 10 sec, fixed token)
1 = min and max time can be defined
[min]      =  Defines  the  duration  in  seconds  how  long  the  text  will  displayed  before
   another display command will be processed (internal MID metering
   relevant information may overrule this).
[max]    = Defines the duration in seconds how long the text will displayed if no
   additional display command follows.
[tk]
= Token – for internal use only.
[text]      =  Text  shown  on  the  display.  Maximum  23  ASCII  characters  can  be  used.
0 .. 23 characters
~ == 
Σ
$ == blank
, == comma

http://www.keba.com/web/downloads/e-mobility/KeContact_P20_P30_UDP_ProgrGuide_en.pdf (Page 16)
It would be great to use this feature to present some additional, OpenHAB generated information!

Thanks
Thanks

**Comment by kgoderis** [comment]
This can be assigned to me
