### ISSUE TITLE
new Robonect binding (Husqvarna Automower, Gardena mowers)

### ISSUE THREAD

**Issue by reyem** [openhab/openhab2-addons#2240]
Robonect is a wlan module which can be put into Husqvarna and Gardena Automowers. This allows to monitor and control the mower via HTTP. As the current way of integration in openhab via http binding is rather cumbersome it makes sense to create a binding.

More info about robonect can be found here
www.robonect.de 

There seems to be no effort on a binding for this in the OH community so far:
https://community.openhab.org/t/robonect-binding-automover-wlan-module/27609
 
However, in the robonect community there would be definitely some demand:
http://www.robonect.de/viewtopic.php?f=21&t=254&p=7813&hilit=openhab#p7813

Therefore I already created a binding which can
* Retrieve all information from the mower ( current status, battery, wlan signal ... etc. )
* retrieve or set a name
* set the mower mode ( AUTO, MANUAL, HOME, EOD, JOB )
* start Jobs

The binding is not final yet and does not follow all OH2 guidelines. However, finally it should become a PR for the official addons.

**Comment by kaikreuzer** [comment]
Sounds great @reyem! As you mention in the title also "Gardena mowers" - are you aware of the [Gardena binding](http://docs.openhab.org/addons/bindings/gardena/readme.html)? Is Husqvarna using the same technology (gateway/cloud), so that this might actually be (almost?) compatible already?

**Comment by reyem** [comment]
No, this is not the same. Robonect is a project not officially from the manufaturers, enabling mowers remote control and monitoring via wifi, which do not have that feature out of the box. That guy behind robonect reverse engineered the protocol of the service interface and created a wifi module, which people can plug into their mowers. The software running on it provides next to a web interface also a simple http based api. Thats were the binding comes into the play

The official gardena binding seems to be a cloud solution rather, wheras with robonect you can stay in the local network.

Although gardena and husqvarna indeed share the same robot under the chassis... so who knows what the future brings 🙂

**Comment by kaikreuzer** [comment]
Ah, very cool, thanks for the explanation!

**Comment by reyem** [comment]
This is the related branch in my repo.
https://github.com/reyem/openhab2-addons/tree/2240-robonect-binding

**Comment by reyem** [comment]
Here a first pre version for people interested in early testing.

[org.openhab.binding.robonect-2.1.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab2-addons/files/981947/org.openhab.binding.robonect-2.1.0-SNAPSHOT.jar.zip)

**Comment by kaikreuzer** [comment]
@reyem Best if you directly create a [WIP] pull request from your branch - then the code will automatically built and deployed to https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/

**Comment by reyem** [comment]
@kaikreuzer Thank you for the hint. I created a PR with [WIP] in the subject. Hope that is the right way...

https://github.com/openhab/openhab2-addons/pull/2249

**Comment by kaikreuzer** [comment]
Perfect, thanks 👍 
I'd suggest to continue all further discussion on #2249 then and close this issue here.
