### ISSUE TITLE
Homematic Channel LOW_BAT --> Contact?

### ISSUE THREAD

**Issue by michaeljoos72** [openhab/openhab2-addons#2241]
Hi

I'm using this channel for all my HM-IP-Devices. For me it would make much more sense to define this channel as contact not as switch? Is there a reason for that?

![image](https://cloud.githubusercontent.com/assets/20517474/25770720/70415d7a-323d-11e7-9abb-fc970c2cc846.png)

**Comment by kaikreuzer** [comment]
Well, "Switch" is used for any general boolean value. Contact would mean the state is OPEN/CLOSED, which doesn't make much sense for "Low Bat", does it?

In general, I would suggest to ask questions at https://community.openhab.org/ instead of opening issues here - thanks!
