### ISSUE TITLE
[MiLight Binding] Orvibo Smart Plugs discovered as bridges.

### ISSUE THREAD

**Issue by DomQuixote** [openhab/openhab2-addons#2244]
Orvibo Smart Plugs (that have the same Hostname as the bridge, namely HF-LPB100) get discovered as MiLight bridges. This is very confusing of course.

**Comment by tavalin** [comment]
Sounds like a duplicate of #2090 that I raised.

**Comment by DomQuixote** [comment]
You are absolutely right. I'll close this one.
