### ISSUE TITLE
[Homematic] Unable to correct a wrong gateway address 

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab2-addons#2248]
With a fresh installation of build 20170506 (on Windows 10) it is not possible to change a wrong gateway address.

I have performed the following steps in Paper UI:

- Search for Things / add manually
- Then I entered a wrong "Gateway address"
- Edited the bridge definition again,  changed the gateway address and saved the configuration.

This results in the following error message on the console:
```
2017-05-07 19:43:00.716 [ERROR] [ome.io.rest.core.thing.ThingResource] - Exception during HTTP PUT request for update config at 'things/homematic:bridge:2e878e32/config' for thing 'homematic:bridge:2e878e32': null
```
This is the only information. There is no stack trace.

**Comment by orificer** [comment]
I can confirm the same issue. I've had to change the ip address of the Pi which is running Homegear and wasn't able to change the gateway address at the thing definition within Paper UI. I've even tried to change it through the REST API, but I've reived an error 500 both ways.

**Comment by MHerbst** [comment]
Here is a bypass: you can edit the file `org.eclipse.smarthome.core.thing.Thing.json` (located in `userdata/jsondb`) and search for "homematic.bridge" and then for "gatewayAddress". You can then change the address and after a restart of openHAB it should work again.

**Comment by MHerbst** [comment]
Retest with OH 2.2. The problem does no longer occur.
