### ISSUE TITLE
PaperUI installing Binding UI does not Update

### ISSUE THREAD

**Issue by Josar** [openhab/openhab2-addons#2252]
When installing a binding from the PaperUI "/paperui/index.html#/extensions" the installation start and the UI shows rotating process ongoing.

In the Log I can follow the installation. After it finisches the UI does not get Updated. It remains at  process in ongoing.

**Comment by kaikreuzer** [comment]
The Paper UI is not in this repo, but at https://github.com/eclipse/smarthome.

Nonetheless, I cannot confirm the issue - I just tested the very latest build and all works as expected.
I thus expect that you have some local network issues (wrongly configured reverse proxy?). You might want to check https://community.openhab.org/ for help.
