### ISSUE TITLE
zwave update time not pulling in

### ISSUE THREAD

**Issue by knockreff** [openhab/openhab2-addons#2257]
In the transfer to opnehab2 it doesn't appear that the information channels are pulling in
what used to be 

dateTime LastUpdated_Humidor "Last update [%1$tH:%1$tM]" (GF_Humidor) {zwave="8:command=info,item=LAST_UPDATE" }

Should now be
DateTime LastUpdated_Humidor "Last update [%1$tH:%1$tM]" (GF_Humidor) { channel="zwave:device:ba7ae0b2:node13:info_last_update" }

however this does not appear to pull in properly not do similar info based channels.  Has the wording for this changed significantly as it doesn't appear to be documents and needed for high quality mobile site maps.

Cheers,
Tony

**Comment by martinvw** [comment]
@knockreff if this issue is still relevant could you then ask it in the [zwave-issues](https://github.com/openhab/org.openhab.binding.zwave/issues)

Of course you are also welcome to suggest a documentation update if you already found how to do it.
