### ISSUE TITLE
Wemo Insight: delayed update for state and power

### ISSUE THREAD

**Issue by IOOOTARobby** [openhab/openhab2-addons#2269]
OH2 Version: 2.0.0
Binding Version: installed from the addons section
Device: Wemo Insight, firmware version WeMo_WW_2.00.10966.PVT-OWRT.Insight

I was using the WeMo mobile app (on Android) and the PaperUI (on may laptop) at the same time.

These are the behaviors I was testing:

- clicking on the physical button on the WeMo while looking the two UIs
- using the button in the WeMo App while looking PaperUI
- using the button in the PaperUI while looking the WeMo App

I have observed two awkward behaviours:

1. switching off the WeMo through its physical button: the WeMo App gets updated in a second, the PaperUI takes one minute or more to allign (it stays ON till then)
2. switching off the WeMo through the button in the WeMo App: the PaperUI takes one minute or more to align

So, in the end, if I switch off the WeMo Insight from **outside** of the PaperUI the latter stays misaligned  for more than a minute.

Am I the only affected by this behavior?

Thanks in advance.

**Comment by kaikreuzer** [comment]
The WeMo binding is part of Eclipse SmartHome, so please be so kind and report your issue at github.com/eclipse/smarthome/issues - thanks!

**Comment by IOOOTARobby** [comment]
Sorry, error due to hurry...

I have replicated the issue on the right repo, thanks @kaikreuzer
