### ISSUE TITLE
RFXCOM Oregon UVN800

### ISSUE THREAD

**Issue by TorpedoBE** [openhab/openhab2-addons#2272]
Hi,

I would like to use the Oregon UVN800 with my RFXCom to control my blinds.

Can this be added to the addon?

------------------------------------------------
Packettype    = UV
Subtype       = UV2 - UVN800
Sequence nbr  = 14
ID            = 7900 decimal:30976
UV Level      = 0
Description = Low
Signal level  = 8  -56dBm
Battery       = OK
------------------------------------------------
Regards,

Bart

**Comment by mjagdis** [comment]
Try this:
[org.openhab.binding.rfxcom-2.1.0-SNAPSHOT.zip](https://github.com/openhab/openhab2-addons/files/1049126/org.openhab.binding.rfxcom-2.1.0-SNAPSHOT.zip)
