### ISSUE TITLE
WeatherBinding not working with Meteoblue free account

### ISSUE THREAD

**Issue by pgruetter** [openhab/openhab2-addons#2274]
Hi all

I signed up for basic-day API key by meteoblue because they provide very accurate forecasts for my location. Unfortunately, the free basic-day subscription doesn't seem to be supported. 

This is the error I get:
`2017-05-17 16:17:13.657 [ERROR] [nal.provider.AbstractWeatherProvider] - METEOBLUE[home-mb]: Can't retreive weather data: HTTP/1.1 400 Bad Request`

A quick search in the forum confirms the problem:
https://community.openhab.org/t/openhab-binding-weather-meteoblue-api/23500
https://community.openhab.org/t/oh2-weather-binding-meteoblue-not-working/27098

Would be great if this got fixed.

**Comment by lolodomo** [comment]
The binding is a OH 1.x binding so you open the issue in the wrong git. The current is for OH 2 bindings.

**Comment by pgruetter** [comment]
Sorry, didn't realize that's not a OH2 binding. Will open a new issue

**Comment by martinvw** [comment]
No problem :-)

**Comment by pgruetter** [comment]
And looking at the right git repo, you can even find an open issue already ;-) 
https://github.com/openhab/openhab1-addons/issues/5185
