### ISSUE TITLE
group http request for multiply item

### ISSUE THREAD

**Issue by off14** [openhab/openhab2-addons#2277]
Hi,

i have a rainmachine controller, with REST api. 1 REST request gives me JSON string with information about all zones.
each zone is represented as an item in openhab2 basicUI. all items are grouped under the folder.
every time i open the folder i see my items. how to avoid sending separate http requests for each zone and just fire one request when the group (folder) is opened, and then feed each item from that result?

**Comment by kaikreuzer** [comment]
This does not sound like an issue report for any openHAB 2 add-on, right?
So please better address your question in our community at https://community.openhab.org/ - thanks!
