### ISSUE TITLE
onewire: tukey filter doesn't work as expected

### ISSUE THREAD

**Issue by staehler** [openhab/openhab2-addons#2292]
Hi,
regarding to the explanation of the tukey-filter of the [onewire binding](https://github.com/openhab/openhab1-addons/wiki/one-wire-binding) I would expect, that unreasonable values would be filtered. E.g. my onewire humidity sensors send data [in percent] in a row like this:
43; 45; 47; 46; 133; 45; ...
The value of 133% is obviously not correct and should be filtered because of two reasons:
- it is more than 100% (this I meanwhile filter by a rule)
- this value must be a faulty measurement (humidity doesn't behave this way)
Even a row with values like above but an faulty measurement below 100%, (maybe like 85%), should be filtered, as it is obviously a high peak out of the row.
If you find I'm right, I would highly appreciate, if this behavior could be fixed. Unfortunately because of this wrong humidity values, my air condition is controlled the wrong way :-(  

Thanks for looking at this.

Kind regards,
Michael

**Comment by wborn** [comment]
The onewire binding you are referring to is part of the openhab1-addons @staehler. When this is still an issue, please create an issue for it in the openhab1-addons [issue tracker](https://github.com/openhab/openhab1-addons/issues).
