### ISSUE TITLE
New Binding LG webOS

### ISSUE THREAD

**Issue by sprehn** [openhab/openhab2-addons#2305]
Since Dec 2015 we are testing this new binding in the community. Initially for OH 1.8 - since March 2016 this OH2 version. https://community.openhab.org/t/connect-sdk-binding-for-lg-webos-tvs/

I would like to contribute this binding to the main project now, and will shortly create a corresponding pull request for review.

**Comment by RealKanashii** [comment]
WebOS 2.0 here, waiting for the commit (or the jar if you want I test it before) :)

**Comment by sprehn** [comment]
You can test the latest release here if you want:
https://github.com/sprehn/openhab2-addons/releases

I am currently challenged to perpare the pull request: 
https://github.com/openhab/openhab2-addons/pull/2306

The issue is, that 8 commits don't carry the "Signed-off-by" line, and I am facing problem rebasing.

**Comment by davidgraeff** [comment]
@sprehn 
`git rebase -i HEAD~10` (or more if need to go back further in the commit history)
and then for each commit do:
```
git commit --amend -sS
git rebase --continue
```
or just sqash all commits to one, which is preferred anyway (use 's' for all related commits expect the very first one) in the `git rebase -i` command prompt.

**Comment by sprehn** [comment]
Hi @davidgraeff 
It is already failing on the first command...

```
sprehn ~/Code/sprehn-openhab2-addons $ git rebase -i HEAD~10 
error: could not apply 62801628... Initial commit of Z-Wave binding

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
Could not apply 62801628f1c7722470275fa02217c9f8d1b45a32... Initial commit of Z-Wave binding
sprehn ~/Code/sprehn-openhab2-addons $ git rebase --abort

```

**Comment by sprehn** [comment]
Could not fix those old commit messages, so I reset my fork to upstream master and reintegrated my binding. This close the original PR. Created new PR #2768.
