### ISSUE TITLE
Add Wavin AHC9000 / Jablotron AC-116 Binding

### ISSUE THREAD

**Issue by spiff42** [openhab/openhab2-addons#2315]
I am looking into making an OH2 binding for Wavin AHC9000 floor heating controller, as discussed here: https://community.openhab.org/t/new-binding-suggestion-wavin-ahc-9000-jablotron-ac-116/28422

**Comment by EsbenSkovPedersen** [comment]
Sounds good - how is the project going?

**Comment by DanNielsen** [comment]
News?

**Comment by spiff42** [comment]
There is a little discussion taking place in the openhab forums:
https://community.openhab.org/t/new-binding-suggestion-wavin-ahc-9000-jablotron-ac-116/28422/10

Other than that, not much progress. I guess the interest has been somewhat limited during the summer, when the floor heating has been turned off :-)
Maybe there will be some more interest now that it is getting colder.

If anyone wants to help out, let me know.

**Comment by jkiddo** [comment]
Would the AHC 8000/AHC 8014 also be supported by this binding?
