### ISSUE TITLE
[astro] solar midnight trigger channel

### ISSUE THREAD

**Issue by emme-g** [openhab/openhab2-addons#2337]
Hello everybody,
I write here in Github after starting a post in the Openhab Community about my idea/need to have a new trigger group for the "solar midnight" of the Sun thing [https://community.openhab.org/t/astro-binding-solar-midnight-trigger-channel/28442].
Basically I would like to have a trigger channel for the solar midnight (when the solar azimut is 0) because I want to configure some rules triggered through this event, but it seems to me the binding doesn't include now that possibility. With the help of Rich Koshak I managed to reach a first solution for my need, but I think it would be a cleaner solution (and maybe useful for other people too) to add a new trigger channel for the Sun thing that runs when the solar azimut is 0.
What do you think? Is it possible and feasible? Bye.

**Comment by kaikreuzer** [comment]
Please note that the Astro binding has meanwhile been moved to ESH. Could you please be so kind and copy your issue to https://github.com/eclipse/smarthome/issues? Thanks!
