### ISSUE TITLE
New Binding & Transport - NEEO

### ISSUE THREAD

**Issue by tmrobert8** [openhab/openhab2-addons#2343]
Implementing a new binding and transport for NEEO

**Comment by mherwege** [comment]
Thank you for the effort implementing this. I will be happy to test as soon as I get my NEEO.

**Comment by tmrobert8** [comment]
Just contact me when you do

**Comment by wborn** [comment]
See also:
* PR https://github.com/openhab/openhab2-addons/pull/3191
* [Community thread](https://community.openhab.org/t/neeo-remote-binding-transport/33408)
