### ISSUE TITLE
[HomeKit] limiting temperature range of thermostats

### ISSUE THREAD

**Issue by CooperCGN** [openhab/openhab2-addons#2367]
Is there a way to limit the range the thermostats? Now it's from -100 to 100 degrees which makes it hard to adjust manually.

**Comment by patrickse** [comment]
Have a look at this...

https://community.openhab.org/t/homekit-and-homematic-thermostat/15221/3?u=patrickse

**Comment by CooperCGN** [comment]
Thanks, but to be honest I have no idea where and what to do. I am one of those users who got their setup running but have no idea about coding :)

**Comment by CooperCGN** [comment]
OK, I got it, it goes into the config file... I will see if I get it working
