### ISSUE TITLE
[kodi] Channel for online/offline state

### ISSUE THREAD

**Issue by Newan** [openhab/openhab2-addons#2375]
Right now the Kodi binding does not provide a channel for the online state.
It is possible to provide a online/offline state to check this channel in rules.

**Comment by kaikreuzer** [comment]
Online/Offline status is a feature of a Thing, it must not be modelled as a Channel.

See https://github.com/eclipse/smarthome/issues/1654.

**Comment by Newan** [comment]
thanks for answer, but the issue is open? Is it implemented?
Is there any documentation or example.

I search for 2 state request:

```
rule "Kodi event on"
when
  Thing kodiUID changed from ONLINE to OFFLINE
then
  // do something
end
```
How get the kodiUID? 

```
rule "Kodi event on"
when
  Item seonorXYZ changed 
then
   If (kodiUID.getStatus() == ThingStatus.Online)
end
```

But i don´t know how to get the "thing" object. Muss i run over all things an compare the ui?

**Comment by sjka** [comment]
see https://github.com/eclipse/smarthome/pull/3001#issuecomment-309250577, i.e. `getThingStatusInfo("kodi:your:thing")` should do the trick.

**Comment by Newan** [comment]
Thanks!
