### ISSUE TITLE
[volumio] Add Volumio Binding

### ISSUE THREAD

**Issue by kubawolanin** [openhab/openhab2-addons#2397]
Submitting this issue for awareness. @patrickse is working on an add-on that allows you to control Volumio instance in your local network.
Binding in its current state can be found here: https://github.com/patrickse/org.openhab.binding.volumio2

## Context

See [this thread on openHAB Community](https://community.openhab.org/t/is-here-anyone-using-volumio/16678)

**Comment by sjka** [comment]
Thanks for creating this  issue here for staking the claim. 
@patrickse do you have any plans creating a PR for it?

**Comment by davidgraeff** [comment]
We can't force an author to publish his binding on this repository. Closing now.
@patrickse Please reopen if you have interest in submitting a PR.

**Comment by patrickse** [comment]
@davidgraeff I will pick up development as soon as the platform is stable again and the re-integration of ESH is completed. We can the merge the binding into openhab2-addons... if there´s still an interest

**Comment by davidgraeff** [comment]
There always is. The reintegration and buildsystem migration has been finished. It's about documentation at the moment and to find the most easy way to setup a developer environment.
