### ISSUE TITLE
[Serial] No longer works with Base64 data.

### ISSUE THREAD

**Issue by sipvoip** [openhab/openhab2-addons#2409]
## Expected Behavior
When running older serial-1.10.0-SNAPSHOT.jar binding from Feb 16th the binding works as expected with my rule: 

val to64 = DatatypeConverter::parseBase64Binary(Outside_Air_Sensor.state.toString)

## Current Behavior
With latest serial binding from openHAB 2.1 release I get:

Exception in rule 'Outside_Air_Sensor': java.lang.ArrayIndexOutOfBoundsException: 219

https://community.openhab.org/t/error-script-engine-scriptexecutionthread/30704/3

## Context
Breaks all my rules serial sensors with Base64 data, had to manually downgrade binding.

## Your Environment
openHAB 2.1 on Centos7

**Comment by kaikreuzer** [comment]
Please report on https://github.com/openhab/openhab1-addons/issues as this is where the serial binding is maintained. You might also check what PRs had been merged on it since February to figure out a potential culprit.
