### ISSUE TITLE
Add Sky Sat Receivers Binding

### ISSUE THREAD

**Issue by cniweb** [openhab/openhab2-addons#2410]
Implementing a new binding for Sky Sat Receivers e.G. Humax S HD 4

A Node.js implementation already exists:
https://github.com/dalhundal/sky-remote-cli

**Comment by RickyTR** [comment]
I'm really interested in this one. Is there something to try?

**Comment by cniweb** [comment]
Yes, the sky-remote-cli work with Humax S HD 4!

**Comment by RickyTR** [comment]
Too bad I have a BSKYB DRX892i...

**Comment by cniweb** [comment]
@RickyTR Try this:
https://github.com/lgladdy/SkyRemote
