### ISSUE TITLE
[onkyo] Port is not recognized in OH 2.1

### ISSUE THREAD

**Issue by CWempe** [openhab/openhab2-addons#2412]
This is my onkyo.things that wos working with openhab 2.0 and is exactly like the documentation.

```
onkyo:onkyoAVR:avr1 [ipAddress="192.168.1.31", port="60128", volumeLimit=50]
```

After the update to openhab 2.1 I got this errors:
> 2017-07-01 00:54:17.291 [DEBUG] [nding.onkyo.internal.OnkyoConnection] - Test connection to 192.168.1.31:0
> 2017-07-01 00:54:17.293 [DEBUG] [nding.onkyo.internal.OnkyoConnection] - Send command: [command=PWR, value=QSTN] to 192.168.1.31:0 (Socket[unconnected])
> 2017-07-01 00:54:17.304 [ERROR] [nding.onkyo.internal.OnkyoConnection] - Can't connect: Verbindungsaufbau abgelehnt (Connection refused)

So the "port=" was not recognized.

I deleted the quotation marks because this is supposed to be a int not a string and now it is working again.

```
onkyo:onkyoAVR:avr1 [ipAddress="192.168.1.31", port=60128, volumeLimit=50]
```

I am not sure why this changed.  
Should this be fixed in the code to support the "old" syntax?  
Or should the documentation be eedited?

**Comment by martinvw** [comment]
Somehow we must have missed this incompatible change while reviewing, it would be great if you could create a PR to update the documentation. Thanks for reporting it!
