### ISSUE TITLE
Openhab eats my cpu (org.jupnp.transport.impl.MulticastReceiverImpl)

### ISSUE THREAD

**Issue by faljse** [openhab/openhab2-addons#2427]
Hi,  my openhab process uses unusual much cpu.

I noticed this behavior before and after OH2.1 upgrade:
`
  68.58% (    83.53s) org.jupnp.transport.impl.MulticastReceiverImpl.run()
`
So most of the time it completely consumes one of the cores.

This is on a "standard" install plus mqtt binding and jrds graphs, no additional upnp related config.

Tcpdump shows some upnp traffic in my network ( <1 pkt/s), which shouldnt cause that high cpu usage.

Is there a way to disable upnp to make sure it is the issue here?
If a dump of the actual upnp traffic is helpful i can provide that.

Running oh2 on a odroid/xu4 with oracle Java HotSpot(TM) Client VM (build 25.131-b11, mixed mode)

**Comment by martinvw** [comment]
And how long did openHAB run while spending 83sec in that single method?

**Comment by faljse** [comment]
> And how long did openHAB run while spending 83sec in that single method?

About 2 minutes.

Im pretty sure now the method displayed by the profiler is not responsible, maybe he is confusing blocking/execution time

However, the openhab process is indeed using a huge amount of cpu and i can trigger it by installing/uninstalling the lifx binding.

Where can i find the sourcecode of lifx 2.1 module?

**Comment by martinvw** [comment]
https://github.com/eclipse/smarthome/tree/master/extensions/binding/org.eclipse.smarthome.binding.lifx And please create a ticket in smarthome to track this problem.

**Comment by hmerk** [comment]
Shouldn't the issue be placed at https://github.com/jupnp/jupnp ?
I don't think that the lifx binding actively triggers the multicast receiver....

**Comment by kaikreuzer** [comment]
I'd second @hmerk's comment - I doubt that this is related to the LIFX binding itself. Would be good if you could e.g. also check with other UPnP enabled bindings like Philips hue, Wemo and others.
