### ISSUE TITLE
[homekit] Update com.beowulfe.hap.hap needed

### ISSUE THREAD

**Issue by trailblazer2006** [openhab/openhab2-addons#2441]
Hi. I have installed an openhab 2.1 with HomeKit 2.1.0 addon on Raspberry. During the adjustment of the thermostat, I encountered a problem described in the topic  https://github.com/beowulfe/HAP-Java/commit/9ba46a5b0363a1f954b039e678b1b911cac74650. This problem has a solution for a long time, but the latest available version contains this error. I consulted with the author of the opener attribute and he told me that the add-on is using the version of HAP-Java library version 1.1.3.
Here is openhab2-addons / addons / io / org.openhab.io.homekit / build.properties file content:
```
...
lib/com.beowulfe.hap.hap-1.1.3.jar,\
...

```
Please update the HomeKit Integration (misc-homekit - 2.1.0) add-on so that when installing via the Paper UI from openhab, it downloads the corrected version of the HAP-Java library

**Comment by martinvw** [comment]
@beowulfe is this something you can do or already have done?

**Comment by trailblazer2006** [comment]
Hi Martin. Problem still persists with latest version of the homekit addon.

**Comment by beowulfe** [comment]
@trailblazer2006 - I’ve been looking for community feedback on a beta version I posted here https://github.com/openhab/openhab2-addons/issues/929

That just so happens to contain the latest version of the library. Can you try it out and see how it works for you?

**Comment by trailblazer2006** [comment]
@beowulfe Hi Andy. I tested the beta 1.1.4. The thermostat on Homekit works fine, the mode is switched, the target temperature is set. Just in case, tested the operation of the switch and the dimmer. Everything is OK.

**Comment by trailblazer2006** [comment]
Hi @martinvw. @beowulfe just released new version of hap-java. Can you update build properties to target to new release 1.1.4. Thank you.

**Comment by kaikreuzer** [comment]
Fixed by https://github.com/openhab/openhab2-addons/pull/4535
