### ISSUE TITLE
[kodi] Sending ShowCodec to channel input returns "Method not found." message from Kodi

### ISSUE THREAD

**Issue by hr77** [openhab/openhab2-addons#2442]
demo.items

`String kodi_input { channel="kodi:kodi:05094b7d:input" }`

Sending `ShowCodec`

```
2017-07-04 21:37:19.617 [DEBUG] [i.internal.protocol.KodiClientSocket] - send message: {"jsonrpc":"2.0","id":49,"method":"Input.ShowCodec"}
2017-07-04 21:37:19.632 [DEBUG] [i.internal.protocol.KodiClientSocket] - Message received from server: {"error":{"code":-32601,"message":"Method not found."},"id":49,"jsonrpc":"2.0"}
2017-07-04 21:37:19.632 [DEBUG] [i.internal.protocol.KodiClientSocket] - Response received from server:{"error":{"code":-32601,"message":"Method not found."},"id":49,"jsonrpc":"2.0"}
2017-07-04 21:37:19.632 [DEBUG] [i.internal.protocol.KodiClientSocket] - callMethod returns {"error":{"code":-32601,"message":"Method not found."},"id":49,"jsonrpc":"2.0"}
```
The JSON request seems to be correct comparing the documentation: http://kodi.wiki/view/JSON-RPC_API/v8#Input.ShowCodec.

When sending this request, the running Kodi instance should actually display information about the codec of the current movie on screen, but instead does nothing.

Related thread: https://community.openhab.org/t/kodi-rewind-fastforward-not-working/30592/5

**Comment by marcelerkel** [comment]
This is not an openHAB or Kodi Binding issue. The Input.ShowCodec method no longer seems to exist in Kodi. When using curl I get the exact same "Method not found." error:

`# curl -s --data-binary '{"jsonrpc": "2.0", "method": "Input.ShowCodec", "id": 1}' -H 'content-type: application/json;' http://localhost:8080/jsonrpc`
`{"error":{"code":-32601,"message":"Method not found."},"id":1,"jsonrpc":"2.0"}`

According to http://kodi.wiki/view/CodecInfo most of the ShowCodec info has been moved to the PlayerProcessInfo window.

`curl -s --data-binary '{"jsonrpc": "2.0", "method": "Input.ShowPlayerProcessInfo", "id": 1}' -H 'content-type: application/json;' http://localhost:8080/jsonrpc`
`{"id":1,"jsonrpc":"2.0","result":"OK"}`

**Comment by cweitkamp** [comment]
Thanks for the information. So this issue could be closed?

**Comment by martinvw** [comment]
Or the binding has to be updated for the changes in the api?

**Comment by cweitkamp** [comment]
No, that is not necessary. The channel which is used to access all "Input.*" methods of the Kodi JSON-RPC interface accepts an String with the method name to replace the asterisks (see https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.kodi/README.md#channels). So the solution is to use "Input.ShowPlayerProcessInfo" instead of "Input.ShowCodec". I posted in the linked community thread too.

**Comment by martinvw** [comment]
I did not realise that it was so generic 🙂

**Comment by hr77** [comment]
I can confirm that "Input.ShowPlayerProcessInfo" is working great, thank you!
