### ISSUE TITLE
Astro 2.1 binding date issue

### ISSUE THREAD

**Issue by pompel82** [openhab/openhab2-addons#2447]
After upgrading to 2.1 the timestamps of sunrise and sunset #start and #end dates are that of yesterdays date. Prior to 2.1 this used to be todays date.

**Comment by kaikreuzer** [comment]
Please note that the Astro binding does not exist here anymore, but is part of ESH, so issues should be reported at https://github.com/eclipse/smarthome/issues (and note that quite some bugs have already been fixed during the last days).
