### ISSUE TITLE
[Yamaha] Binding not getting status update of Receiver -> shows offline

### ISSUE THREAD

**Issue by Terr4** [openhab/openhab2-addons#2452]
Hi there

I have the issue that the Yamaha Biding is not receiving any status updates from my Receiver and in Paper UI it shows it as OFFLINE.
However I can send commands to it with no issues in Basic UI & Classic UI
This has worked in the past.

If I can provide any logs please just let me know. I do not see anything relevant in the logs for the binding.

## Expected Behavior
Receive status updates of Yamaha Receiver and thing should be ONLINE and not OFFLINE

## Current Behavior
Thing shows OFFLINE and does not gather the current status. Controlling it works although in Basic UI & Classic UI.

## Possible Solution
?

## Steps to Reproduce (for Bugs)
1. Turn Receiver off with the remote
2. OpenHAB2 status does not change to OFF

## Your Environment
* Version used: OpenHab 2.0
* Environment name and version: Raspberry Pi 3, Raspbian Jessie. OpenHab2 not installed with APT-GET but manually

**Comment by davidgraeff** [comment]
Hopefully resolved with #1781

**Comment by davidgraeff** [comment]
@martinvw can be closed
