### ISSUE TITLE
[insteonplm] Feature Request: OH2 Insteon PLM/Hub Support

### ISSUE THREAD

**Issue by augustf** [openhab/openhab2-addons#2464]
The Insteon PLM/Hub add-on is currently available as an OpenHab 1 plugin. Per a discussion with other users on https://community.openhab.org/t/insteon-plm-recognized-but-not-available-as-a-binding/13576 , we'd like to see the Insteon add-on available as a proper OpenHab 2 plugin, with Insteon devices detectable via the Paper UI (see the excellent Philips Hue add-on).

The OH2 Insteon add-on should follow the development guidelines (http://docs.openhab.org/developers/development/bindings.html) and function with both the PLM and Hub.

We've posted a bounty: https://www.bountysource.com/issues/47277806-insteonplm-feature-request-oh2-insteon-plm-hub-support

**Comment by kubawolanin** [comment]
Note that there's one pull request with OH2 Insteon Binding that @pinkfish started a while ago, but it's closed for some reason:
https://github.com/openhab/openhab2-addons/pull/1965

**Comment by augustf** [comment]
Closed for lack of feasibility and interest (https://community.openhab.org/t/oh2-insteon-plm-bounty-posted/31687/4)

**Comment by robnielsen** [comment]
@augustf I don't know if you are aware, but I ported over the Insteon PLM binding earlier this year: https://www.openhab.org/addons/bindings/insteon/
