### ISSUE TITLE
Binding Request: Worx Landroid S (Modell 2017)

### ISSUE THREAD

**Issue by Silencer80** [openhab/openhab2-addons#2468]
Deleted on request from the manufacturer.

**Comment by tj2000bch** [comment]
Hi,
I also interested on a binding for Landroid S Model 2017 and can test and debug.

**Comment by Silencer80** [comment]
Hi,

i´ve just found an workaround to integrate Landrois S with OpenHAB.

1. Get an SSL client certificate as described here: https://github.com/mjiderhamn/worx-landroid-nodejs/blob/master/landroid-mqtt.md
2. Convert to pem-Files.
3. Install local Mosquitto-Server as Bridge (in commanOut, out CommandIn).

#Bridge to Landroid
connection landroid
bridge_cafile /etc/mosquitto/ca_certificates/vs.pem
bridge_keyfile /etc/mosquitto/ca_certificates/private.pem
bridge_certfile /etc/mosquitto/ca_certificates/cert.pem
bridge_insecure false
address a1optpg91s0ydf.iot.eu-west-1.amazonaws.com:8883
local_clientid <ANDROID_ID>
cleansession true
start_type automatic
notifications false
try_private false
topic commandOut in 0 DB510/<MAC>/ DB510/MAC/
topic commandIn out 0 DB510/<MAC>/ DB510/MAC/


4. Connect with MQTT-Binding to local Mosquitto.

5. Filter JSON with JSONPATH & Transforms.

/* Landroid Items with transforms */

Number Landroid_Akkutemperatur "Akku-Temperatur: [%.1f °C]" <temperature> (Garden) {mqtt="<[landroid:DB510/<MAC>/commandOut:state:JS(LD_Akku_Temp.js)]"}
Number Landroid_Akkuspannung "Akku-Spannung: [%.1f Volt]" <battery> (Garden) {mqtt="<[landroid:DB510/<MAC>/commandOut:state:JS(LD_Akku_Vol.js)]"}
Number Landroid_Akkuladung "Akku-Ladestand: [%s %%]" <akku> (Garden) {mqtt="<[landroid:DB510/<MAC>/commandOut:state:JS(LD_Akku_Perc.js)]"}
Number Landroid_Ladestatus "Akku wird [MAP(charging.map):%s]" <akku> (Garden) {mqtt="<[landroid:DB510/<MAC>/commandOut:state:JS(LD_Charging.js)]"}
Number Landroid_Wifi       "WiFi-Signal: [%s %%]" <signal> (Garden) {mqtt="<[landroid:DB510/<MAC>/commandOut:state:JS(LD_RSI.js)]"}
Number Landroid_Betriebszeit "Betriebszeit: [%.1f h]" (Garden) {mqtt="<[landroid:DB510/<MAC>/commandOut:state:JS(LD_Time.js)]"}
Number Landroid_BetriebszeitMesser "Betriebszeit Messer: [%.1f h]" (Garden) {mqtt="<[landroid:DB510/<MAC>/commandOut:state:JS(LD_BladeTime.js)]"}
Number Landroid_Distanz "Zurückgelegte Distanz: [%.1f km]" (Garden) {mqtt="<[landroid:DB510/<MAC>/commandOut:state:JS(LD_Distance.js)]"}

/* Landroid Items  JSONPATH */

Number Landroid_Ladezyklen "Akku-Ladezyklen: [%s]"  (Garden) {mqtt="<[landroid:DB510/<MAC>/commandOut:state:JSONPATH($.dat.bt.nr)]"}
Number Landroid_Fehler "Fehlerstatus: [MAP(landroid_error.map):%s]"  (Garden) {mqtt="<[landroid:DB510/<MAC>/commandOut:state:JSONPATH($.dat.le)]"}
Number Landroid_Status "Status: [MAP(landroid_status.map):%s]"  (Garden) {mqtt="<[landroid:DB510/<MAC>/commandOut:state:JSONPATH($.dat.ls)]"}
`

5. Send MQTT-Commands with Rules.

Best regards!
-Boris

**Comment by Ontrackx** [comment]
Hi,
I also interested on a binding for Landroid S Model 2017 and can test.

**Comment by Ontrackx** [comment]
@Silencer80 , would you pleeease help me with your soulution via teamwiever?
I always have troubles reciving certificates

**Comment by tj2000bch** [comment]
Is it possible to install a Mosquitto-Server as Bridge and as Broker on the same System?
Can I have more than one config File on Mosquitto?

**Comment by tj2000bch** [comment]
Hi,
I have the «pkcs12» Certifikate from my Landroid.
{
"pkcs12":"MIIRTERAzCCCV8G ………….B\/uxcECNtYBiY+Jv4V"
}
How can I convert this to a “.pem” file?

**Comment by Silencer80** [comment]
Hi,

first follow the instructions from:
https://github.com/mjiderhamn/worx-landroid-nodejs/blob/master/landroid-mqtt.md

To get the binary PKCS12 certificate, this string needs to be Base64 decoded. (On Windows, this can be done using certutil -decode input.file output.file).

Then use openssl to convert pkcs12 to pem and export private key without password.

**Comment by tj2000bch** [comment]
@Silencer80 
Hi Boris
My only problem is, which part of the PKCS12 do i need to save in which file. In p12, pxf or cer?
I tried it with Windows and a Base64 online decoder.
Tobi

**Comment by Ontrackx** [comment]
Finally got this working to domotics (testing purposes) but battery is missing from 2017 model?

Certificate retrieved
Fetching root CA
Connecting to MQTT broker
Connected to MQTT broker - subscribing to DB510/F0FE6B207FB4/commandOut
Landroid status: {"state":"Home","errorMessage":null,"batteryPercentage":null,"totalMowingHours":35.8,"totalDistance":28249,"noOfAlarms":0}
Landroid status: {"state":"Home","errorMessage":null,"batteryPercentage":null,"totalMowingHours":35.8,"totalDistance":28249,"noOfAlarms":0}
Landroid status: {"state":"Home","errorMessage":null,"batteryPercentage":null,"totalMowingHours":35.8,"totalDistance":28249,"noOfAlarms":0}
Landroid status: {"state":"Home","errorMessage":null,"batteryPercentage":null,"totalMowingHours":35.8,"totalDistance":28249,"noOfAlarms":0}
Landroid status: {"state":"Home","errorMessage":null,"batteryPercentage":null,"totalMowingHours":35.8,"totalDistance":28249,"noOfAlarms":0}
Landroid status: {"state":"Home","errorMessage":null,"batteryPercentage":null,"totalMowingHours":35.8,"totalDistance":28249,"noOfAlarms":0}
Landroid status: {"state":"Home","errorMessage":null,"batteryPercentage":null,"totalMowingHours":35.8,"totalDistance":28249,"noOfAlarms":0}
Landroid status: {"state":"Home","errorMessage":null,"batteryPercentage":null,"totalMowingHours":35.8,"totalDistance":28249,"noOfAlarms":0}
Landroid status: {"state":"Home","errorMessage":null,"batteryPercentage":null,"totalMowingHours":35.8,"totalDistance":28249,"noOfAlarms":0}

**Comment by whopperg** [comment]
some notes to complete the how to:
- only copy string without the "" form the certificate to a empty file
- convert the certificate with openssl in to a cert and key file (hint: import password is empty so just hit enter)
openssl pkcs12 -in cert.pkcs12 -out newfile.crt.pem -clcerts -nokeys
openssl pkcs12 -in cert.pkcs12 -out newfile.key.pem -nocerts -nodes
(where cert.pkcs12 is your converted file you downloaded via POSTMAN as above)

- download the ROOT CA file for Verisign ([here](https://www.symantec.com/content/en/us/enterprise/verisign/roots/VeriSign-Class%203-Public-Primary-Certification-Authority-G5.pem))

- install mosquitto server (Linux apt-get: install mosquitto)
- copy all certificate files to /etc/mosquitto/ca-certificates
- create a new config file in /etc/mosquitto/conf.d/ named landroid.conf
then paste this content;
connection landroid
bridge_cafile /etc/mosquitto/ca_certificates/vs-ca.pem
bridge_keyfile /etc/mosquitto/certs/key.pem
bridge_certfile /etc/mosquitto/certs/cert.pem
bridge_insecure false
address a1optpg91s0ydf.iot.eu-west-1.amazonaws.com:8883
local_clientid Your Android ID here
cleansession true
start_type automatic
notifications false
try_private false
topic commandOut in 0 DB510// DB510/YOUR_MAC_GOES_HERE/
topic commandIn out 0 DB510// DB510/YOUR_MAC_GOES_HERE/

**Comment by whopperg** [comment]
Hey @Silencer80 ,
is it possible that you could upload or post your map and js files? This would be nice as i dont have any Clou what i should put in there ;-)

Thanks!

**Comment by Silencer80** [comment]
Hey @All,

the manufacturer has informed me that this solution is bothering its systems. Above all, the polling function mentioned here by others causes considerable problems and costs.

So please do not use that anymore and refrain from polling.

Thank you!
-Boris
