### ISSUE TITLE
[Telegram] photoURL does not represent a known image type

### ISSUE THREAD

**Issue by MrMontesa** [openhab/openhab2-addons#2469]
## Expected Behavior
I'm running Motioneye software on a Pi Zero W with the NoIR cam. The software has the option to curl images and use them right away. The link looks like this:
http://192.168.23.17:8765/picture/1/current/?_username=admin&_signature=$my_security_token

I want to use this URL in rules using the sendTelegramPhoto function. My rule code looks like this:

```
val String url = "http://192.168.23.17:8765/picture/1/current/?_username=admin&_signature=$my_security_token"
logInfo("SecCam", "URL: " + url)
 sendTelegramPhoto("bot1", url,"Groundfloor Cam")
```
This should send the photo via Telegram.

## Current Behavior
Unfortunately the above rule spits an error:

```
2017-07-17 10:33:19.366 [INFO ] [clipse.smarthome.model.script.SecCam] - URL: http://192.168.23.17:8765/picture/1/current/?_username=admin&_signature=$my_security_token
2017-07-17 10:33:19.406 [ERROR] [ab.action.telegram.internal.Telegram] - photoURL does not represent a known image type
```

Since I can properly curl the image using the url I'm quite sure motioneye works ok. Is it possible that Openhab has issues finding the image? I'm not 100% sure, but I think I was running this functionlatiy before on OH2.0. Since my PiZero setup broke I never activated it for production use. Now on OH 2.1 and fixed PiZero I'd like to start again.
Also opened a dicussion at [community.openhab.org](https://community.openhab.org/t/photourl-does-not-represent-a-known-image-type/31589)

## Possible Solution
Since this is very much hardware (PiZero) & software (motioneye) related, I know its difficult to reproduce. Possibly we can focus on the what leads to this error message and understand why OH behaves the way it does. The [motioneye software](https://github.com/ccrisan/motioneye) is also hosted on github and we might have a chat with the developer as well.

## Steps to Reproduce (for Bugs)
1. get Pi with Cam
2. Install & configure motioneye
3. Install Telegram Binding
4. write rule using motioneye link

## Context
I have several webcams around the house acting as a security system. In case motion is detetected by some PIRs, I'd like to send telegram messages containing the webcam image. This nicely works with all IP cams I have querying the CGI interface of the webcams, but doesnt work with motioneye and PiZero cam.

## Your Environment
OH 2.1 release build with Telegram binding
PiZero W with NoIR cam running debian 7 and motionEye 0.35.2

**Comment by sjka** [comment]
Thanks for your bug report. 

If I get it right, the image is produced by motion(eye) and will be forwarded from there using the Telegram action. At least I don't see any involvement of the Eclipse SmartHome framework in between. The Telegram action is maintained in this repository: https://github.com/openhab/openhab1-addons. Therefore may I ask you to open an issue there?  

I'm well aware that it is complicated sometimes with that many projects to figure out which is the right one... - just copy'n'paste your very good description from above there.  Thanks for your patience!

**Comment by MrMontesa** [comment]
Thanks for your swift reply. I [opened an issue](https://github.com/openhab/openhab1-addons/issues/5254) for openhab1-addons as requested.
Motioneye iteself is a Webgui written in python  for the well known [motion](http://www.lavrsen.dk/foswiki/bin/view/Motion/WebHome) tool.
