### ISSUE TITLE
Tradfri binding potential bug

### ISSUE THREAD

**Issue by tam481** [openhab/openhab2-addons#2472]
## Expected Behavior
I expect the switch item to always reflect the status of the light.

## Current Behavior
A while after configuring the binding and linking the dimmer item with the bulb the status of the light is no longer reflected. The light can be controlled through the dimmer item but its status is no longer update if the light is switched on/off or the brightness changes using the Tradfri Android app or the physical remote/dimmer.

## Steps to Reproduce (for Bugs)
1. Configure binding
2. Assign dimmer item to "tradfri channel"
3. Use as normal. Check using the physical remote and app and the status updates correctly on OpenHAB.
4. A while later....
5. Binding works to control the light but is no longer receiving status update. 

## Context
I cannot get the status of the light as it stops changing to reflect the actual status if turned on using the IKEA Tradfri remote.

## Your Environment
Using OpenHAB 2.1 from the official repo on a Raspberry Pi 2

* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
Using Google Chrome, Firefox and Opera

* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):
Raspbian lite (latest release as of 15/07/2017

**Comment by martinvw** [comment]
Can you create this bug at https://github.com/eclipse/smarthome/issues, Thanks!
