### ISSUE TITLE
[ZWAVE] Cooper RFWC5 status LED control 

### ISSUE THREAD

**Issue by phinnay** [openhab/openhab2-addons#2473]
## Expected Behavior
Some method needs to be developed to control the LED scene selector lights on the RFWC5 

Under OH1 this could be done as follows:
Switch DR_Scene1i "Scene 1 LED" {zwave="16:command=INDICATOR,bit=0"}

## Current Behavior
Unable to control LED's via OH2

## Possible Solution
Whatever will allow for control of the LED's!

## Steps to Reproduce (for Bugs)
Attempt to set LED's they dont work under OH2. 

## Context
setting the LED's allows for custom rules to reflect their current state visually, making automation friendlier and easier to use. Manually setting the LED's is also essential to keep multiple scene controllers in sync regardless of brand. This is a feature available on all commercial automation systems. 

## Your Environment
OpenHAB2 on Raspi. Cooper RFWC5

**Comment by martinvw** [comment]
Can you check in https://github.com/openhab/org.openhab.binding.zwave/issues whether such an issue already exists and if not open it there, thanks!
