### ISSUE TITLE
[Feature Request] - Realtime trigger to IFTTT

### ISSUE THREAD

**Issue by dk8pn** [openhab/openhab2-addons#2488]
openHAB2 should serve item states through myopenhab.org to the realtime API of IFTTT.
A basic feature is already in place but IFTTT reacts after a large delay between 15 minutes up to 1 hour.

Desired application is as following: Alexa Triggers item state change "air conditioner ON/OFF". openHAB2 tells IFTTT to use an "intersishome applet" to switch the airconditioner ON. Execution should be realtime. There is a description in IFTTT for realtime API requirements.

**Comment by kaikreuzer** [comment]
I assume that this is rather a feature request for https://github.com/openhab/openhab-cloud as in this repo there is no such thing as an "IFTTT add-on".
