### ISSUE TITLE
[onkyo] 'sec' instead of 'msec' in debug output

### ISSUE THREAD

**Issue by CWempe** [openhab/openhab2-addons#2502]
This should be milli seconds I think.

```
2017-07-29 22:30:04.398 [ERROR] [nding.onkyo.internal.OnkyoConnection] - No data received during supervision interval (70000 sec)!
```

https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/OnkyoConnection.java#L306

**Comment by cweitkamp** [comment]
PR #2763
