### ISSUE TITLE
[netatmo] TempTrend and PressTrend not working

### ISSUE THREAD

**Issue by CWempe** [openhab/openhab2-addons#2505]
According to the wiki and the [stations.xml](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.netatmo/ESH-INF/thing/station.xml) TempTrend and PressTrend are supposed to work for the main indoor module.

But it looks like this is not working.
https://community.openhab.org/t/what-channel-types-are-supported-by-wich-netatmo-device/24394/6?u=christoph_wempe

My config:

```
String Netatmo_Indoor_TempTrend           "TempTrend [%s]"                 <line>             (gNetatmo)                        { channel = "netatmo:NAMain:home:inside:TempTrend" }
String Netatmo_Indoor_PressureTrend       "PressureTrend [%s]"             <pressure>         (gNetatmo)                        { channel = "netatmo:NAMain:home:inside:PressTrend" }
```

But TempTrend is working for the outdoor module.

```
String Netatmo_Outdoor_TempTrend          "TempTrend [%s]"                 <line>             (gNetatmo)                        { channel = "netatmo:NAModule1:home:outside:TempTrend" }
```

I see no error when setting log to TRACE.

```
2017-07-30 17:24:51.107 [DEBUG] [netatmo.handler.NetatmoDeviceHandler] - Trying to update channels on device 70:ee:50:06:a9:30
2017-07-30 17:24:51.605 [DEBUG] [netatmo.handler.NetatmoDeviceHandler] - Successfully updated device readings! Now updating channels
2017-07-30 17:24:51.614 [DEBUG] [.handler.AbstractNetatmoThingHandler] - Updating device channels
2017-07-30 17:24:51.817 [DEBUG] [netatmo.handler.NetatmoDeviceHandler] - Updating child modules of 70:ee:50:06:a9:30
2017-07-30 17:24:51.819 [DEBUG] [netatmo.handler.NetatmoDeviceHandler] - Updating child module 02:00:00:05:db:ac
2017-07-30 17:24:51.821 [DEBUG] [.handler.AbstractNetatmoThingHandler] - Updating device channels
```

**Comment by cweitkamp** [comment]
@clinique Can you help?

**Comment by lolodomo** [comment]
If I correvtly remember, the pressure is only delivered by the outside module  ?  In this case it would make sense that pressureTrend is not delivered by the indoor module too.

**Comment by CWempe** [comment]
No.
Pressure only works for the indoor module.

![image](https://user-images.githubusercontent.com/1270359/28767788-5e0844b2-75d5-11e7-9404-51b238acdbb1.png)


![image](https://user-images.githubusercontent.com/1270359/28767613-a447a112-75d4-11e7-94ce-4a8615f5636c.png)

```
Number Netatmo_Indoor_Pressure            "Pressure [%.1f mbar]"           <pressure>         (gNetatmo)                        { channel = "netatmo:NAMain:home:inside:Pressure" }
```

**Comment by clinique** [comment]
Sure, there seem to be a problem here. Temperature trend works fine on the outside module but not for the inside one. Pressure Trend does not fill neither. Will look closer at this issue.
