### ISSUE TITLE
[Tankerkoenig] Feature Request: Swicth or Contact to show if station is open/closed

### ISSUE THREAD

**Issue by tbail** [openhab/openhab2-addons#2513]
The binding is missing a switch or contact that indicates if the desired gas station is open or closed. In addition to the open8closed information prices should have a defined value i.e. 0,00€.

Based on the open/closed information fuel prices cloud be displayed or it is possible to give a closed information to the user.

## Expected Behavior
For each station a new channel (Switch or contact) should indicated if the station is closed or open.

## Current Behavior
The information desired is currently not there.

## Possible Solution
Just implement the switc/contact

## Your Environment
Latest nightly on raspberry pi 3

**Comment by JueBag** [comment]
Will start working on as soon as I'mentioned back home.

**Comment by JueBag** [comment]
Dammit.  This mobile phone is driving me n***. 
..as soon as I'm back home.

**Comment by JueBag** [comment]
I incooperated a channel "station_open" which shows the information using a Contact.
Lets wait until the "hosting" PR gets approved and merged.

**Comment by martinvw** [comment]
Maybe it would even be better if @tbail could already test it before it gets merged?

**Comment by JueBag** [comment]
Stupid question:
Is that possible without me posting the .jar?

**Comment by martinvw** [comment]
It should be this one I think:

https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/org.openhab.binding.tankerkoenig/2.2.0-SNAPSHOT/org.openhab.binding.tankerkoenig-2.2.0-SNAPSHOT.jar
