### ISSUE TITLE
Netatmo binding: missing translations in French 

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab2-addons#2517]
Using the new Paper UI page for bindings, I got this for the Netatmo binding:
* the binding description has no sense: "Le binding Netatmo gre station Netatmo Personal Weather et les modules additionels."
* some things types are displayed in French like for example NAMain or NAModule1, but others in English like for example netatmoapi or NATherm1
* the French description of the thing type NAModule3 has apparently an encoding problem

**Comment by martinvw** [comment]
Is this maybe caused by missing translations? Did you configure your language to be French?

I suppose the first text is stored some where in the repo, can you check?

**Comment by lolodomo** [comment]
The language of my RPI is setup to use French; OH is certainly using the system language by default and so French is used in my case.
There are certainly missing translations, that is the object of my isuue ;)

**Comment by martinvw** [comment]
😀

**Comment by lolodomo** [comment]
https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.netatmo/ESH-INF/i18n/netatmo_fr.properties#L3

I confirm that the binding description has to be made understandable :) in the french translation and missing strings have to be added in this file.

@clinique : can you enhance that ?

**Comment by cweitkamp** [comment]
I can offer to add some german translations, too.

**Comment by lolodomo** [comment]
Maybe first a full French file would help you to forget nothing in your German translation ?

I took a look to all ESH/OH2 bindings and internationalization is very rare. When provided, most of the time only a German translation is provided. We have few bindings with a Dutch translation and only one with a French translation, the netatmo binding.
I will try to add French translation for few bindings I am using.

**Comment by lolodomo** [comment]
@clinique : do you need my help to fix the French translation ?

**Comment by clinique** [comment]
You're very welcome to do so !

Envoyé de mon iPhone

**Comment by lolodomo** [comment]
I am working on it.
