### ISSUE TITLE
[hueemulation] Emulation fails if one device not active

### ISSUE THREAD

**Issue by glennpierce** [openhab/openhab2-addons#2522]
I have two sonoffs. Both are connected to power extension leads. These will be used for temporary things like Christmas lights. When both are plugged in, my Openhab2 setup works with hue emulation. Ie my Amazon echo can discover both devices. However, if one sonoff is unplugged then the amazon echo fails to discover any devices including the existing one still plugged in.

I can still control the existing device through openhab2 web interface so I assume the problem is with the hue emulation.

## Expected Behaviour
If one device is unplugged only that device should fail to be controlled, not all of them.

## Current Behaviour
All devices currently become unrecoverable if one device fails. 

## Steps to Reproduce (for Bugs)

My sitemap is

```
sitemap home label="Pierce-House"
{
    Frame label="Garden"
    {
        Switch item=Switch1
        Text item=Switch1_wifi
    }

    Frame label="Christmas"
    {
        Switch item=Switch2
        Text item=Switch2_wifi
    }
}
```

items are

```
Switch Switch1 "Garden Light" <Garden> ["Switchable"] { mqtt=">[mosquitto:tasmota/sonoff/garden/cmnd/power:command:*:default], <[mosquitto:tasmota/sonoff/garden/cmnd/power:state:default]" }

Switch Switch1_Reachable "Garden Light: reachable" { mqtt="<[broker:tasmota/sonoff/garden/tele/LWT:state:MAP(reachable.map)]" }

// Wifi Signal Strength in Percent
Number Switch1_wifi "Garden Light WIFI [%d %%]" (gRSSI) { mqtt="<[mosquitto:tasmota/sonoff/garden/tele/STATE:state:JSONPATH($.Wifi.RSSI)]" }


Switch Switch2 "Christmas Light" <Christmas> ["Switchable"] { mqtt=">[mosquitto:tasmota/sonoff/livingroom/cmnd/power:command:*:default], <[mosquitto:tasmota/sonoff/livingroom/cmnd/power:state:default]" }

Switch Switch2_Reachable "Christmas Light: reachable" { mqtt="<[broker:tasmota/sonoff/livingroom/tele/LWT:state:MAP(reachable.map)]" }

// Wifi Signal Strength in Percent
Number Switch2_wifi "Christmas Light WIFI [%d %%]" (gRSSI) { mqtt="<[mosquitto:tasmota/sonoff/livingroom/tele/STATE:state:JSONPATH($.Wifi.RSSI)]" }
```

## Context

I wish to use wifi controlled extension leads. I don't need them constantly connected all year round. I would like for my alazon ech to work with the ones plugged in.
openhab2                               2.1.0-1
addon                                     2.1.0-1

* Version used: (e.g., openhab and addon versions)
Java 8
Raspbian Linux

**Comment by davidgraeff** [comment]
Fixed with the refactor in OH 2.4
