### ISSUE TITLE
[yamaha] Tuner band selection and preset feature for dual band models (RX-S601D)

### ISSUE THREAD

**Issue by zarusz** [openhab/openhab2-addons#2524]
Hi,

I have a Yamaha Receiver RX-S601D which comes with a Tuner input that supports two band modes FM and DAB+. With the latest Yamaha binding #1781 (and the old one too) there is no way to:

- Change the band (FM vs. DAB+)
- Change the preset (station A or B)

Furthermore, I am experiencing an error and the playback/navigation functionality does not seem to work when TUNER is selected as input (see error below).

## Expected Behavior
- Be able to select my favorite radio station whether on FM or DAB+

## Current Behavior
- Not able to select my favorite radio station on Yamaha RX-S601D

## Possible Solution
I have investigated the latest Yamaha Binding PR #1781 by @davidgraeff and these need to be done:
- Add a 'tuner_band' thing channel (R/W) of type String - accepting 'FM' or 'DAB'
- The existing 'preset' channel has to take into account currently selected band. The internal Yamaha commands to set preset need to address the band (presets are tracked separately for each band).

## Steps to Reproduce (for Bugs)
1. Build the latest Yamaha Binding and deploy to OH2.1
2. When selecting input to TUNER the following error shows up in openhab.log:

`2017-08-05 22:05:04.239 [WARN ] [eiver.handler.YamahaZoneThingHandler] - post failed on: <?xml version="1.0" encoding="utf-8"?><YAMAHA_AV cmd="GET"><TUNER><Play_Info>GetParam</Play_Info></TUNER></YAMAHA_AV>`

## Context
I have reached out to @davidgraeff and discussed the problem. The fix and change would be easy to introduce. I will be creating a PR soon with the proposed fix and enhancement (see above).

We have 2 issues and 1 feature here:
1. The `<TUNER>` xml element should be replaced with `<DAB>` in all commands.
2. The preset channel should issue commands to Yamaha including the band name.
3. A new 'tuner_band' channel should be added to the binding.

## Your Environment
* OH2.1, Bindings 2.1 (installed from apt-get)
* Latest Yamaha binding from #1781 - packaged & installed manually.
* Java 8, Raspberry Pi 2
* Operating System and version: Raspbian Jessie

**Comment by davidgraeff** [comment]
@zarusz : I haven't seen your PR yet but please consider that older AVRs don't have DAB at all. So you cannot replace **all** TUNER XML references with DAB, but you need to extend or add instead.

**Comment by davidgraeff** [comment]
I'm preparing the code base for MusicCast support (Yamaha extended protocol) in #2533. If you haven't started yet, I suggest to base it on that commit. If you have started, just continue and we'll try to merge your code first and I'll rebase later.

**Comment by zarusz** [comment]
I already started, but will reapply my changes on top of your #2533 PR. 

In the meantime, please wait with any major changes ;)

**Comment by zarusz** [comment]
The PR #2558 awaiting review & approval.
