### ISSUE TITLE
[Lutron] - Add support for RadioRA (Classic)

### ISSUE THREAD

**Issue by jjlauterbach** [openhab/openhab2-addons#2537]
I'm implementing a binding for the legacy Lutron RadioRA lighting solution often called RadioRA (Classic).

The existing Lutron binding only works with more modern Lutron products (RadioRA 2) and the protocols and communication methods are different for each system.  RadioRA (Classic) requires a piece of hardware such as the Chronos time module to expose a RS232 port for sending commands to the system. 

I have the code mostly working now as a new binding as I didn't feel it would be easy to live along side the code within in the existing Lutron binding.  

Still working on code cleanup and documentation.  Would like to add automated tests as well.
https://github.com/jjlauterbach/openhab2-addons/tree/2537-radiora

**Comment by tmrobert8** [comment]
Just a comment - really up to you and @kaikreuzer but I did add an even earlier Lutron protocol (the Grafix eye protocol) into the existing binding without any issues and wouldn't see any issues to do it here either (note: I'm not the owner of the existing binding but just a contributor - really need to have the 'owner' input here instead).  

I, personally, would like to see it added to the existing rather than keep segmenting the binding space by different product models because it makes management, from an end user, easier.  However, that's a bigger question that @kaikreuzer needs to answer (should the binding space be segmented by manufacturer, by model, or 'depends' on the product).

Sorry for jumping in on this - but just adding my 2 cents worth..

**Comment by kaikreuzer** [comment]
If there is no technical reason to split it into a separate binding (e.g. because it has huge new dependencies that one would not want for the existing Lutron support), I would agree with @tmrobert8 - it makes it much easier for the users if we only have one Lutron binding and the users can simply choose the "bridge" they are using.
@jjlauterbach Could you check what it would mean to your work to make it a part of the existing binding?

**Comment by jjlauterbach** [comment]
Thanks for the feedback.  I took a look at what was done to add the Grafix eye protocol and I can easily do something similar and just namespace my code into a smaller compartment within the binding.  Shouldn't be too hard and will just require some minor refactoring.

I do have one question.  Both RadioRA and RadioRA 2 have some similar thing types such as dimmers and switches.  The concept and config parameters are largely compatible (terminology is a little different, i.e. integrationId vs zoneNumber) so I think I could reuse those things types and then figure out which handlers to instantiate in the ```LutronHandlerFactory``` based on the bridge used.  

Do you think that's a good approach or should we keep these things separate and just create thing types such as radioradimmer and radioraswitch.  This might make it easier to document and easier for users to understand what's applicable to them based on the system they have.  

I'll probably have some time this weekend to start integrating my code into the lutron binding this weekend.  Any additional feedback you have would be much appreciated.

**Comment by martinvw** [comment]
Great that you are willing to take another look! @kaikreuzer @actong and maybe @tmrobert8  could you give him some hints. Thanks!

**Comment by tmrobert8** [comment]
I, personally, would just move everything over to a sub-namespace within the project and merge the handler factory.  Something I wish I did but am recommending is to rename/move your readme.md and then modify the existing one to provide a link (with verbage of course) to your readme.md (I merged my readme into theirs - which probably should have been separated).

**Comment by kaikreuzer** [comment]
> Both RadioRA and RadioRA 2 have some similar thing types such as dimmers and switches.

Usually, a thing type should correspond to a specific product that it in the market - so as these are clearly different products, it should be ok to also keep separate thing-types for them.
If there is a too huge variety of products and they all indeed have exactly the same features and configuration possibilities, using a single thing-type for them makes sense.
I leave it up to you, what you consider to be the case here - I have too little insight in the Lutron world :-)

**Comment by jjlauterbach** [comment]
Thanks.  I found some time this weekend and pushed my implementation into the Lutron binding and everything is working as well as it did before.  

Working on some final code cleanup and then I want to learn how to best write some unit tests for bindings.  Then I'll submit a pull request.  

Updating the title of this issue to reflect the current approach of adding to the existing Lutron binding

I've pushed my current changes to a branch on my fork 
https://github.com/jjlauterbach/openhab2-addons/tree/lutron-radiora

**Comment by ramillaw2** [comment]
I am setting up open HAB and I have Lutron RA system with some of the older Graphik Eyes. 

I wanted to know if this Binding has been included in the one that is available in the open HAB set-up?

If not - how can I get this binding for my set-up?

**Comment by jjlauterbach** [comment]
@ramillaw2  The code to use RadioRA Classic hasn't been integrated with the openhab lutron binding yet.

I've been meaning to finish up the code cleanup and documentation so I can create a pull request to share this with others.  

Hopefully within the next couple of weeks I will find the time to do that.

**Comment by nostromo20** [comment]
Hi I want to connect openhab to an older Grafikeye 3x with an RS232 connection through a GRX-PRG (Its the older version without ethernet). As a test I connected to the RadioRA RS232 and it shows "online" so basic communication works ok, but would need it to bridge to the Grafikeye (which it cannot). Any thoughts on how easy this would be to implement?

**Comment by jjlauterbach** [comment]
The RS232 bridge is specifically for Radio RA Classic and it won't be able to work with GRX-PRG.  I suggest you log a new issue or post of the community forum and hopefully someone with more knowledge of Grafik Eye will be able to chime in.
