### ISSUE TITLE
netatmo binding

### ISSUE THREAD

**Issue by raisude** [openhab/openhab2-addons#2541]
During the last days my Netatmo components fail sometimes.

following message is in PaperUI

Netatmo API
Netatmo API

This bridge represents the gateway to Netatmo API.

Status: OFFLINE - CONFIGURATION_ERROR Unable to connect Netatmo API : OAuthProblemException{error='unsupported_response_type', description='Invalid response! Response body is not application/json encoded', uri='null', state='null', scope='null', redirectUri='null', responseStatus=0, parameters={}}

What can I do?

Regards Rainer

**Comment by octa22** [comment]
Same here :-(

**Comment by michaeljoos72** [comment]
Yes, I see the same :( 
Did Netatmo change something in the API or is it only in the latest snapshots?

**Comment by raisude** [comment]
For me it seems that netatmo has changier something. I use myatmo on the iphone and this App has made also trouble during the Last days

**Comment by octa22** [comment]
It seems to be something with the API, Netatmo OH1 binding has problems too

**Comment by raisude** [comment]
https://api.netatmo.com

**Comment by IOOOTAlan** [comment]
There has been some API changes recently (see the changes "brewing" in PR #2510, which addresses issues #2505 and #2379), however your issue seems to concern the authentication on the API portal.
Maybe @clinique has a better view on this.

**Comment by cweitkamp** [comment]
The Netatmo API is available again. Not very stable, but it works most of the time. So this one can be closed.

**Comment by raisude** [comment]
Not really. The Api is available. But i habe the following Problem. The values of the items are not actual. After starting openhab they are. But they stop getting new values after some time. Restarting the services gives them actual values.

**Comment by clinique** [comment]
@martinvw : this issue could be closed, @raisude opened a new one (#2586) with the update problem he faces.

**Comment by martinvw** [comment]
Thanks for mentioning!
