### ISSUE TITLE
Kaipule IM20 Z-Wave

### ISSUE THREAD

**Issue by Uruwashii** [openhab/openhab2-addons#2550]
The EU version of the Kaipule IM20_ZWAVE door contact sensor is not showing in the device database.

IM20_ZWAVE is being discovered as Z-Wave Node 4 (0214:0002:0001:5.38) 

Purchased Thing: IM20_ZWAVE_EU

****THING PROPERTIES****

zwave_class_basic | ROUTING_SLAVE
-- | --
zwave_class_generic | SENSOR_NOTIFICATION
zwave_frequent | false
zwave_neighbours | 1,3
zwave_version | 5.38
zwave_listening | false
zwave_plus_devicetype | ACCESS_CONTROL_SENSOR
zwave_deviceid | 1
zwave_nodeid | 4
zwave_routing | true
zwave_beaming | true
zwave_class_specific | NOTIFICATION_SENSOR
zwave_manufacturer | 532
zwave_devicetype | 2

**Comment by kaikreuzer** [comment]
You probably rather want to report this at https://github.com/openhab/org.openhab.binding.zwave/issues.
