### ISSUE TITLE
Skeleton readme outdated?

### ISSUE THREAD

**Issue by 9037568** [openhab/openhab2-addons#2552]
It appears the [doc/readme](http://docs.openhab.org/developers/development/bindings.html) on generating an OH2 skeleton is outdated.

It currently states claims only a single parameter is needed, when 2 are actually required:

For this, go into your git repository under git/openhab2-addons/addons/binding and call the script create_openhab_binding_skeleton.sh **with a single parameter**, which is your binding name in camel case (e.g. ‘ACMEProduct’ or ‘SomeSystem’)

Usage: create_openhab_binding_skeleton BindingIdInCamelCase BindingIdInLowerCase

**Comment by kaikreuzer** [comment]
Note that the documentation is maintained at https://github.com/openhab/openhab-docs.

@cweitkamp As you recently worked on the archetypes, would you volunteer to update [the page](https://github.com/openhab/openhab-docs/blob/gh-pages/developers/development/bindings.md) accordingly? Thanks!

**Comment by cweitkamp** [comment]
Yes of course, I will look into this. Give me some days.
