### ISSUE TITLE
[netatmo] Binding does not support Healthy Home Coach device

### ISSUE THREAD

**Issue by msvinth** [openhab/openhab2-addons#2566]
The Netatmo binding does not support the NETATMO [Healthy Home Coach](https://www.netatmo.com/en-US/product/aircare/homecoach)

[Developer reference](https://dev.netatmo.com/resources/technical/reference/healthyhomecoach/gethomecoachsdata) 

The data returned by the device is very similar to the weather station but the type ("NHC") is different. It only adds the health_idx enum in the returned values compared to the weather station.

This is the data i get on my device
```_id: "70:xx:xx:xx:xx:xx"
last_status_store: 1502991330
type: "NHC"
dashboard_data:
   AbsolutePressure: 1013.7
   time_utc: 1502991330
   health_idx: 0
   Noise: 51
   Temperature: 25.5
   temp_trend: "down"
   Humidity: 58
   Pressure: 1013.7
   pressure_trend: "down"
   CO2: 548
   date_max_temp: 1502978089
   date_min_temp: 1502943538
   min_temp: 24.5
   max_temp: 26.7
data_type:
   "Temperature"
   "CO2"
   "Humidity"
   "Noise"
   "Pressure"
   "health_idx"
co2_calibrating: false
date_setup: 1502804496
last_setup: 1502804496
firmware: 36
last_upgrade: 1502804498
wifi_status: 63
name: "xxx"```

**Comment by cweitkamp** [comment]
@martinvw I think this one is solved for now.

**Comment by martinvw** [comment]
Thanks for mentioning!
