### ISSUE TITLE
[Homematic] Binding for dimmer HmIP-PDT contains more than 900 configuration settings

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab2-addons#2568]
I have added a Homematic dimmer (HmIP-PDT) to my configuration. And then I tried to edit the thing's configuration in Paper UI.

## Expected Behavior
Configuration edit page should appear within seconds.

## Current Behavior
It takes several minutes to render the page in Paper UI (see also https://github.com/eclipse/smarthome/issues/4093). This happens because the thing definition contains more than 900 configuration settings.

This is an excerpt from `org.eclipse.smarthome.core.thing.Thing.json` containing all available settings:
```
      "configuration": {
        "properties": {
          "HMP_6_63_WP_CONDITION": "0",
          "HMP_6_74_WP_DURATION_FACTOR": 31,
          "HMP_6_06_WP_LEVEL": 0.0,
          "HMP_6_57_WP_FIXED_MINUTE": 0,
          "HMP_2_OVERTEMP_LEVEL": 70,
          "HMP_6_03_WP_RAMP_TIME_FACTOR": 0,
          "HMP_6_54_WP_FIXED_MINUTE": 0,
          "HMP_6_09_WP_DURATION_BASE": "7",
          "HMP_6_22_WP_ASTRO_TYPE": "0",
          "HMP_6_39_WP_LEVEL": 0.0,
          "HMP_6_69_WP_RAMP_TIME_BASE": "0",
          "HMP_6_12_WP_TARGET_CHANNELS": 0,
... >900 lines removed
          "HMP_6_32_WP_DURATION_BASE": "7",
          "HMP_6_19_WP_DURATION_BASE": "7"
        }
```

## Possible Solution
Check and (maybe) try to reduce the number of configuration settings for this device.

## Steps to Reproduce (for Bugs)
1. Add the HmIP-PDT to openHAB
2. Open the thing's configuration page

## Your Environment
* Version used: openHAB 2.1 with Homematic binding 2.1.0 (release version) on Raspberry 3
* Version used: openHAB 2.2 Build 1017 with latest Homematic binding on Windows 10
* Browser: Chrome 60 and Edge on Windows 10

**Comment by mdicke2s** [comment]
This issue was moved to eclipse/smarthome#5784
