### ISSUE TITLE
[yamahareceiver] Don't get netradio working

### ISSUE THREAD

**Issue by krafel** [openhab/openhab2-addons#2569]
As sort of newbie to openhab I'd like to apologize upfront, because probably the questions points to me being a typical layer 8 problem ;-) however, I do not get sort of a 'netradio station selection' working at all. I have some stations under Bookmarks/My__Favorites, like Deutschlandfunk and some respective navigation channel items (up/down, select) and some sitemap testing statements in a fresh 2.2.0-snapshot environment from yesterday. No stream change possible...

Is there a good example how netradio (or menu browsing, respectively) is working including some item, sitemap and rules definitions? I just don't get how it's ought be used, sorry...

**Comment by davidgraeff** [comment]
@openhab/maintainers Can be closed.
@krafel : There was a big feature update of the yamaha binding which adds proper navigation support. Please update or wait for an updated OH2.3 release

**Comment by martinvw** [comment]
@davidgraeff thanks for the update!
