### ISSUE TITLE
[network] Old configuration does not work

### ISSUE THREAD

**Issue by claell** [openhab/openhab2-addons#2579]
After switching to the snapshot build of OH2 the network binding failed to work for me using the old configuration. In #2380 It is stated that this should be working: "The old thing "device" is now "pingdevice". This is not a real breaking change though, as all old configurations should still work because I map "device" to "pingdevice" in the handler factory."

Unfortunately it didn't work for me. I had to change the channel "time" to "latency" in the item configuration and use "pingdevice" instead of "device" for the things.

Maybe you can take a look at it @davidgraeff

**Comment by martinvw** [comment]
@davidgraeff it would be great if this could be fixed before going live with 2.2

**Comment by davidgraeff** [comment]
Ups, I renamed the time channel to latency, that's true. I will add an internal not xml exported time channel again and update it together with latency.

I have no idea why the "device" thing does not work though. The factory should create a thing handler and that thing handler does not care if its thing has the ThingUID of "device" or "pingdevice".

**Comment by claell** [comment]
It did not work for me, the thing did not show any channels in PaperUI.

Also: Does old configurations with no longer supported parameters work? Example: `network:device:devicename [ hostname="192.168.0.42", port=0, retry=1, timeout=5000, refresh_interval=60000, use_system_ping="false", dhcplisten="true" ]`

**Comment by davidgraeff** [comment]
Yes should work with not-used configuration parameters.

**Comment by davidgraeff** [comment]
@martinvw Can we rename the binding to "presencedetection"? That reflects more what the binding does and we are not breaking any compatibility with people that still use the network binding of the last release.

**Comment by claell** [comment]
> The only way I can think of to NOT make a "device" thing visible to new users but at the same time modifiable by PaperUI for current users is to implement a ThingTypeProvider and enable it only if the user still has a Thing with UID "device". That's complicated.

So it worked in the background, but PaperUI just didn't show it? That might be possible.

**Comment by davidgraeff** [comment]
@claell Yes exactly

**Comment by claell** [comment]
Alright

**Comment by martinvw** [comment]
> @martinvw Can we rename the binding to "presencedetection"? That reflects more what the binding does and we are not breaking any compatibility with people that still use the network binding of the last release.

to me this does sound even more breaking if an existing binding is removed from the repository, @kaikreuzer wdyt?

**Comment by kaikreuzer** [comment]
I do not understand the suggestion. @davidgraeff, please note that the "network" binding is not from 1.x, but exists in 2.x, so removing or renaming it won't solve anything.

**Comment by davidgraeff** [comment]
An update process would not remove bindings. So the network binding would stay for users how have installed it and are using it. And new users would see presencedetection instead.

_Sent from my Lge LG-F700K using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by martinvw** [comment]
@kaikreuzer wdyt given the explanation?

**Comment by kaikreuzer** [comment]
Well, simple: Breaking changes should be avoided and if this is not possible, they must be documented at https://github.com/openhab/openhab-distro/wiki/Draft-for-openHAB-2.2-Release-Notes#manual-installations, so that people now that they will have to change their configuration when updating from 2.1 to 2.2.

**Comment by davidgraeff** [comment]
I will add an entry to the breaking change section of the draft, and we can close this issue then?

**Comment by kaikreuzer** [comment]
Sure.
