### ISSUE TITLE
[network] Wrong "uses_dhcp_listen" property value shown in PaperUI

### ISSUE THREAD

**Issue by claell** [openhab/openhab2-addons#2591]
## Expected Behavior
For me the property "uses_dhcp_listen" in the PaperUI configuration of a pingdevice shows:
"uses_dhcp_listen | off"

I just tried and it looks like the this is wrong. The device is immediately discovered after connecting to Wifi.

Also I have no config file set and I think the default behaviour is to use dhcp listen.

So probably the displayed value is wrong.

## Environment
* Version used: openHAB 2.2.0 Build 1023
* Operating System and version: Raspbian Jessie

**Comment by davidgraeff** [comment]
Please check if the Openhab java process listens to port 67 or 6767. You Chan checked with 'netstat -tulpen'.

DHCP listen requires special permissions or a port forwarding, if you did not set this up it is unlikely that it works. Maybe your ping refresh timeout is very low?

**Comment by claell** [comment]
I have a refresh rate of once per minute.
There are also messages in the log:
`2017-08-23 17:52:52.532 [INFO ] [work.internal.dhcp.DHCPListenService] - DHCP request for registered address: 192.168.1.200`

I did not use the steps in the Readme to setup dhcp listen (https://github.com/openhab/openhab2-addons/tree/master/addons/binding/org.openhab.binding.network#dhcp-listen).

However I used
`setcap 'cap_net_raw,cap_net_admin=+eip cap_net_bind_service=+ep' $(realpath /usr/bin/java)`
as described here: http://docs.openhab.org/installation/linux.html#java-network-permissions

Result for the command:
```
pi@raspberrypi:~ $ sudo netstat -tulpen
Aktive Internetverbindungen (Nur Server)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      0          10166       711/sshd        
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      0          10674       1174/exim4      
tcp6       0      0 :::8080                 :::*                    LISTEN      109        1731690     27986/java      
tcp6       0      0 127.0.0.1:43377         :::*                    LISTEN      109        1731203     27986/java      
tcp6       0      0 :::22                   :::*                    LISTEN      0          10168       711/sshd        
tcp6       0      0 ::1:25                  :::*                    LISTEN      0          10675       1174/exim4      
tcp6       0      0 :::8443                 :::*                    LISTEN      109        1731372     27986/java      
tcp6       0      0 127.0.0.1:8101          :::*                    LISTEN      109        1729926     27986/java      
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           105        9861        422/avahi-daemon: r
udp        0      0 0.0.0.0:49914           0.0.0.0:*                           105        9863        422/avahi-daemon: r
udp        0      0 0.0.0.0:68              0.0.0.0:*                           0          10354       710/dhcpcd      
udp        0      0 192.168.1.105:123       0.0.0.0:*                           0          10124       781/ntpd        
udp        0      0 127.0.0.1:123           0.0.0.0:*                           0          10123       781/ntpd        
udp        0      0 0.0.0.0:123             0.0.0.0:*                           0          10117       781/ntpd        
udp6       0      0 :::43211                :::*                                109        1733402     27986/java      
udp6       0      0 :::5353                 :::*                                109        1731709     27986/java      
udp6       0      0 :::5353                 :::*                                109        1731706     27986/java      
udp6       0      0 :::5353                 :::*                                109        1731703     27986/java      
udp6       0      0 :::5353                 :::*                                105        9862        422/avahi-daemon: r
udp6       0      0 :::53575                :::*                                109        1731360     27986/java      
udp6       0      0 192.168.1.105:42342     :::*                                109        1733382     27986/java      
udp6       0      0 :::1900                 :::*                                109        1733399     27986/java      
udp6       0      0 :::1900                 :::*                                109        1733381     27986/java      
udp6       0      0 :::51674                :::*                                105        9864        422/avahi-daemon: r
udp6       0      0 :::546                  :::*                                0          10052       710/dhcpcd      
udp6       0      0 :::67                   :::*                                109        1731733     27986/java      
udp6       0      0 fdd5:24c4:abb4::105:123 :::*                                106        10681       781/ntpd        
udp6       0      0 fdd5:24c4:abb4:0:d3:123 :::*                                106        10680       781/ntpd        
udp6       0      0 fe80::84a4:6770:204:123 :::*                                0          10126       781/ntpd        
udp6       0      0 ::1:123                 :::*                                0          10125       781/ntpd        
udp6       0      0 :::123                  :::*                                0          10118       781/ntpd        
udp6       0      0 :::42666                :::*                                109        1954613     27986/java
```

Also this only works for discovering connecting, not for disconnecting.

**Comment by davidgraeff** [comment]
Yes netstat confirms that java is listening on port 67. The readme recommend setcap before too but it caused issues in some special cases. So I removed that section. I'll have a look at some point, thanks for reporting.

**Comment by claell** [comment]
Thanks!

**Comment by claell** [comment]
I just checked again with the updated addon and unfortunately the value is still "no" for me.

**Comment by davidgraeff** [comment]
It is enabled though:
https://github.com/openhab/openhab2-addons/pull/2580/files#diff-97c941c5818b3809fb23425c6e062154R178

But the property is apparently only updated once at the beginning. If it wasn't ready by then, it will be shown as "no".

**Comment by davidgraeff** [comment]
I prepared a new fix. It is basically: move some lines around

**Comment by claell** [comment]
Just tested it.

It shows:
```
uses_dhcp_listen | no
dhcp_state | Running normally
```
also:
```
presence_detection_type | ARP_PING
arp_state | IPUTILS_ARPING
uses_arp_pings | no
```

Are the "uses_" properties different and not "on" when the detection method is used?

**Comment by davidgraeff** [comment]
@claell This is not generated by the binding. Apparently the framework caches the values of properties, and because I never assign a new value to them, they are still visible to you. Might be an OSGi cache entry or an old jsondb entry, whatever service is responsible for properties.

**Comment by martinvw** [comment]
Do you mean that they are not generated by this version of the binding?

**Comment by davidgraeff** [comment]
@martinvw Yes, they are not assigned anymore in the current version

**Comment by claell** [comment]
Alright. To me it still looks a bit confusing right now. Is this behaviour (displaying of cached values of properties) wanted / is there a different place where to "fix" this?

**Comment by martinvw** [comment]
Most likely re-adding the item should solve it

2017-09-09 17:50 GMT+02:00 Claudius Ellsel <notifications@github.com>:

**Comment by claell** [comment]
Ah, now I understand. This is only happening for me because my usage of the old addon version before. Deleting my items and things file and readding it did not help, but I guess waiting will work as well and this property does not hurt.

So thanks for fixing and your help!
