### ISSUE TITLE
1.9 Sonance binding tested under OH 2.0

### ISSUE THREAD

**Issue by LaurensVanAcker** [openhab/openhab2-addons#2596]
I tested the 1.9 Sonance binding under OH2 and it works.
Could you include this in the openhab2-addons?
https://github.com/openhab/openhab1-addons/tree/master/bundles/binding/org.openhab.binding.sonance

**Comment by tavalin** [comment]
I think issue should go in openhab-distro repo.

**Comment by kaikreuzer** [comment]
No, please directly open a PR against openhab1-addons as described here: http://docs.openhab.org/developers/development/compatibilitylayer.html#how-to-add-a-successfully-tested-1x-add-on-to-the-distribution. Thanks!

**Comment by LaurensVanAcker** [comment]
https://github.com/openhab/openhab1-addons/pull/5293
