### ISSUE TITLE
[network] Two small typos

### ISSUE THREAD

**Issue by claell** [openhab/openhab2-addons#2600]
This is an issue to note two small typos in /ESH-INF/i18n/network_de.properties.

- "binding.config.network.allow_dhcp_listen.description = Lauscht auf DHCP Packete, welche beim Eintritt von Geräten in das Network gesendet werden, um die Verfügbarkeit eines Gerätes in beinahe Echtzeit mitzuteilen." Small typo: "Packete", also: "Network"
- "thing-type.config.network.servicedevice.refresh_interval.description = Spezifiziert den Aktualisierungsintervall (in ms)" Should be "das Aktualisierungsintervall"

**Comment by Trickx** [comment]
When German language is selected in UI, some German umlaut are not shown properly at least with Firefox.
In PaperUI -> Configuration -> Bindings, see screenshot.
![binding-network - 2 2 0 snapshot_german](https://user-images.githubusercontent.com/8447808/29708351-a110900e-8988-11e7-88f1-ab091fe124b8.PNG)

**Comment by claell** [comment]
Yes that was an issue introduced by me when fixing a typo. See https://github.com/openhab/openhab-distro/issues/525
