### ISSUE TITLE
openHAB target platform not resolving

### ISSUE THREAD

**Issue by doandzhi** [openhab/openhab2-addons#2630]
Hello, I faced some errors trying to resolve my openHAB target platform.

![targetplatform](https://user-images.githubusercontent.com/17512690/29828353-22db4642-8ce5-11e7-9934-ee8e53357dff.PNG)

 Using the SmartHome target platform I see that there are californium dependencies added. Could they have been missed in the openHAB platform?

**Comment by kaikreuzer** [comment]
https://github.com/openhab/openhab-distro would be the better repo to report it :-)

It seems to me that you have a terribly old version of openhab.target (which is part of openhab-distro). Your screenshot shows that references openhab-deps-repo version 1.0.6, while 1.0.16 is the current one. Could you pull the latest changes from openhab-distro into your workspace?

**Comment by doandzhi** [comment]
And what is the actual purpose of the openhab-core target platform, because I actually tried to use it instead of the one in openhab-distro? Also thanks for the quick reply :)

**Comment by kaikreuzer** [comment]
That's a very good question, I completely forgot about the fact that it exists :-)
The openHAB IDE does not import that project into the workspace, so you shouldn't do it either. The openhab.target file in there is used by the Maven build - I am actually surprised that this build still works despite the old target definition...
It probably would make sense to get rid off it; will have to think about it how to best get there...

**Comment by wborn** [comment]
Is this still an issue @doandzhi ?

**Comment by doandzhi** [comment]
It was not an issue at all. I was just mislead by the second target platform (openhab-core) that is existent. Also as Kai mentioned this issue is related more to the openhab-distro so feel free to close this one here.

**Comment by wborn** [comment]
Thanks for the update! :-)
