### ISSUE TITLE
org.openhab.binding.jeelink specifies JRE 1.7, but contains Java 8 code

### ISSUE THREAD

**Issue by rickardp** [openhab/openhab2-addons#2636]
I don't know if the tie to JRE 1.7 is by design, but the code appears to use classes that only exist in JRE 1.8.

## Expected Behavior
When I open the workspace in Eclipse, the code compiles.

## Current Behavior
When I open the workspace in Eclipse, I get compilation errors due to classes not found in JRE 1.7 that are used in org.openhab.binding.jeelink.

## Possible Solution
Using the workspace JDK solves the problem, e.g.

```
diff --git a/addons/binding/org.openhab.binding.jeelink/.classpath b/addons/binding/org.openhab.binding.jeelink/.classpath
index a95e0906c..3daf88219 100644
--- a/addons/binding/org.openhab.binding.jeelink/.classpath
+++ b/addons/binding/org.openhab.binding.jeelink/.classpath
@@ -1,6 +1,6 @@
 <?xml version="1.0" encoding="UTF-8"?>
 <classpath>
-       <classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.7"/>
+       <classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>
        <classpathentry kind="con" path="org.eclipse.pde.core.requiredPlugins"/>
        <classpathentry kind="src" path="src/main/java"/>
        <classpathentry kind="output" path="target/classes"/>

```

## Steps to Reproduce (for Bugs)
Open the workspace

## Context
Minor issue, just changing the Java Build path for this one project solves the problem.

## Your Environment
* Version used: master branch
* Mac OS X, followed instructions in the developer guide here: http://docs.openhab.org/developers/development/ide.html

**Comment by martinvw** [comment]
Thanks for reporting! Could you create a PR which resolves it?

For some contributing guidelines see http://docs.openhab.org/developers/contributing/contributing.html

**Comment by kaikreuzer** [comment]
I already did: https://github.com/openhab/openhab2-addons/pull/2639

**Comment by martinvw** [comment]
😄
