### ISSUE TITLE
[homematic] TCL script / XML parse error

### ISSUE THREAD

**Issue by 3yc** [openhab/openhab2-addons#2662]
Sometimes Homematic binding is failing to parse the TCL script XML output. It fails with this error message:

`Status: OFFLINE - COMMUNICATION_ERROR : ParseError at [row,col]:[3,22] Message: Wert des Attributs "name", das mit Elementtyp "entry" verknüpft ist, darf nicht das Zeichen "<" enthalten. : : ParseError at [row,col]:[3,22] Message: Wert des Attributs "name", das mit Elementtyp "entry" verknüpft ist, darf nicht das Zeichen "<" enthalten. ---- Debugging information ---- message : : ParseError at [row,col]:[3,22] Message: Wert des Attributs "name", das mit Elementtyp "entry" verknüpft ist, darf nicht das Zeichen "<" enthalten. cause-exception : com.thoughtworks.xstream.io.StreamException cause-message : : ParseError at [row,col]:[3,22] Message: Wert des Attributs "name", das mit Elementtyp "entry" verknüpft ist, darf nicht das Zeichen "<" enthalten. class : org.openhab.binding.homematic.internal.model.TclScriptDataList required-type : org.openhab.binding.homematic.internal.model.TclScriptDataList converter-type : com.thoughtworks.xstream.converters.reflection.ReflectionConverter path : /list line number : 3 version : 1.4.7 -------------------------------`

This behavior shows only for one item:
 _"Wired RS485 I/O-Modul 12 Eingänge, 14 Ausgänge, Hutschienenmontage (HMW-IO-12-Sw14-DR)"_

Its not easy to reproduce since its sporadic nature. Few tries to edit and save the item in paper ui brings the item back online.

**Comment by MHerbst** [comment]
On a first view it looks like the TCL script returns not well-formed XML. output. Or does the device name contain a "<"?

 Can you give us some more information about your environment (CCU version, openHAB version etc.).

**Comment by 3yc** [comment]
Sure,
Openhab Snapshot from 1.9.17 and ccu2 v2.29.22
I turned the debug log level on for this binding while trying to restore it. The funny thing is, there are no messages in openhab.log just the one in the paper ui only.

**Comment by MHerbst** [comment]
@gerrieg Any idea? To me it looks like a bug in XML output.

**Comment by gerrieg** [comment]
For me too. I just checked the TCL scripts if i forgot a WriteXML, but they are all there. WriteXML should escape the XML output correctly.

@3yc 
Can you please enable TRACE logging for the Homematic binding and try to reproduce the problem? Then i see what's wrong in the logfile

**Comment by 3yc** [comment]
Sure, as soon as the error triggers again. At DEBUG level i saw not much, maybe TRACE provides more information.

**Comment by 3yc** [comment]
Ok, i think i know whats going on here. See the Log:
```
2017-09-06 09:42:56.374 [DEBUG] [tic.internal.communicator.CcuGateway] - RpcMessage unknown RPC failure (-1 Failure), fetching values with TclRega script for device LEQ0251834, channel: 25, paramset: VALUES
2017-09-06 09:42:56.374 [TRACE] [tic.internal.communicator.CcuGateway] - TclRegaScript: string channel = "BidCos-Wired.LEQ0251834:25.";
string datapointNames = "VALUE\tSTATE";
string datapointName;
Write('<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>\n');
Write("<list>\n");
foreach (datapointName, datapointNames) {
    object dp = dom.GetObject(channel #  datapointName);
    Write("  <entry");
    Write(" name='"); WriteXML(dp.Name().StrValueByIndex(".",2));
    Write("' value='"); WriteXML(dp.Value());
    Write("' />\n");
}
Write("</list>");
2017-09-06 09:42:56.425 [TRACE] [tic.internal.communicator.CcuGateway] - Result TclRegaScript: <?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<list>
  <entry name='null  <entry name='STATE' value='false' />
</list>
```

HMW-IO-12-Sw14-DR is switchable for some channels between analog and digital input. Depending on this setting the VALUE xor STATE are existing. Running the same script for this channel that is switched to analog input returns:
```
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<list>
  <entry name='VALUE' value='0.000000' />
  <entry name='null</list>
```

The simpliest fix would be to check for NULL in the Tcl script. An other option is to ask for the VALUE/STATE according to its channel conmfiguration.

Greetings
 Adam

**Comment by gerrieg** [comment]
Thanks for finding the problem! I will fix it soon.
But ... any chance to upgrade to openHab 2? There is a completely different metadata fetching in the 2.x binding and i'm pretty sure it will work. Use the latest 2.2 snapshot to have all the fixes since 2.1 release.

**Comment by 3yc** [comment]
It's openhab2, snapshot from 1.9.2017. According to this [file in master branch](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.homematic/src/main/resources/homematic/tclrega-scripts.xml) it's script named getAllChannelValues:

```
<script name="getAllChannelValues">
        <data>
        <![CDATA[
string channel = "{channel_name}";
string datapointNames = "{datapoint_names}";
string datapointName;
Write('<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>\n');
Write("<list>\n");
foreach (datapointName, datapointNames) {
    object dp = dom.GetObject(channel #  datapointName);
    Write("  <entry");
    Write(" name='"); WriteXML(dp.Name().StrValueByIndex(".",2));
    Write("' value='"); WriteXML(dp.Value());
    Write("' />\n");
}
Write("</list>");
        ]]>
        </data>
</script>
```
Do im mixing things up here?

**Comment by gerrieg** [comment]
Sorry, **I** mixed up the scripts 😕  This is a 2.x workaround script if fetching the metadata with the Homematic API fails. On some devices the CCU returns a failure at the API call.

**Comment by 3yc** [comment]
So the trap is the switchable STATE/VALUE attribute in homematic, good :) How about a change in the TCL script like that until the API problem is solved:
```
string channel = "{channel_name}";
string datapointNames = "{datapoint_names}";
string datapointName;
Write('<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>\n');
Write("<list>\n");
foreach (datapointName, datapointNames) {
    object dp = dom.GetObject(channel #  datapointName);
    if(dp) {
       Write("  <entry");
       Write(" name='"); WriteXML(dp.Name().StrValueByIndex(".",2));
       Write("' value='"); WriteXML(dp.Value());
       Write("' />\n");
   }
}
Write("</list>");
```

**Comment by gerrieg** [comment]
exactly, this should fix the problem. I'm currently on vacation, i will do the change on monday.

**Comment by 3yc** [comment]
Created a pull request #2680
