### ISSUE TITLE
[Amazon Dash Button] not detecting my button - Configuration file?

### ISSUE THREAD

**Issue by SciLor** [openhab/openhab2-addons#2663]
Following mac prefix is missing:
FC:A6:67

What about a configuration in the papergui for additional macs?

See: https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.amazondashbutton/src/main/java/org/openhab/binding/amazondashbutton/internal/discovery/AmazonDashButtonDiscoveryService.java

**Comment by kubawolanin** [comment]
cc: @OLibutzki

**Comment by Celaeno1** [comment]
This has been solved long time ago: on the 21th of October.
see here:
https://github.com/openhab/openhab2-addons/commit/5175844771e337f3ba475e83b47848c2b0f660cd#diff-e0e2a96129cca02cc8990983a1d87b65R73

**Comment by martinvw** [comment]
Thanks for mentioning
