### ISSUE TITLE
[homekit] "This accessory is not currently supported by the Home App" when tagging items with "Switchable"

### ISSUE THREAD

**Issue by robbrown92** [openhab/openhab2-addons#2679]
So i am having some difficulty connecting my oh2 with homekit. items are [ "SWITCHABLE" ] however when i add the accessory in homekit i get the error

Not supported
This accessory is not currently supported by the Home App..

An ideas?

**Comment by ogillin** [comment]
same issue here.
any update?

**Comment by fss** [comment]
Having the same issue. Just updated to OH2.2, but this didn't solve the problem.

**Comment by J-N-K** [comment]
Please check if this is still the case

**Comment by J-N-K** [comment]
Closing as current master shares only very little code parts with 2.1.0
