### ISSUE TITLE
[homematic] Missing configuration dialog in paper UI and HABADMIN UI

### ISSUE THREAD

**Issue by sagittarius0815** [openhab/openhab2-addons#2697]
Since openHAB 2.2.0 Build #1036 snapshot (2017-09-10) the configuration dialog for homematic binding is missing in paper UI and HABADMIN UI

**Comment by kaikreuzer** [comment]
I just tested build 1037 and all looks ok.
Can you please explain what exactly you mean by "configuration dialog" and post a screenshot of your problem?

**Comment by sagittarius0815** [comment]
I looked for the place where to enter homematic configuration parameters such like "gatewayAddress".
But now I found it. First I have to add a thing called "homematic bridge". There I can enter the configuration parameter.
Sorry, my fault, issue closed.
