### ISSUE TITLE
[Xiaomi / MiHome] java.lang.NullPointerException

### ISSUE THREAD

**Issue by beshkenadze** [openhab/openhab2-addons#2699]
## Expected Behavior
Switch On/Off
## Current Behavior
Crash

## Steps to Reproduce (for Bugs)
1. Setup MiHome by http://docs.openhab.org/addons/bindings/mihome/readme.html
2. Add items Xiaomi Plug by http://docs.openhab.org/addons/bindings/mihome/readme.html#xiaomiitems
3. Make a call from the control page (Paper UI)
4. Crash
Link to the stack: https://gist.github.com/beshkenadze/4afd694fd568fb66178c64b7c99a9004

## Context
Switching On/Off via hardware does not cause the crash, the element changes state on the control page.

## Your Environment
* Version used: Docker: openhab/openhab:2.1.0-amd64

**Comment by beshkenadze** [comment]
Maybe duplicate #2405

**Comment by tavalin** [comment]
Could you try a 2.2.0 snapshot? It may have been fixed since the 2.1.0 release.

**Comment by beshkenadze** [comment]
@tavalin Unfortunately, the snapshot crashes with the error: Error in initialization script: /openhab/userdata/etc/shell.init.script: String index out of range: 0.

**Comment by martinvw** [comment]
Are you running docker(-compose)? If so see: https://github.com/openhab/openhab-docker/pull/103 and the related community thread

**Comment by beshkenadze** [comment]
@martinvw 
I use direct command
```Bash
sudo docker run \
        --name openhab-snapshot \
        --net=host \
        -v /etc/localtime:/etc/localtime:ro \
        -v /etc/TZ:/etc/timezone:ro \
        -v /volume1/docker/openhab/addons:/openhab/addons \
        -v /volume1/docker/openhab/conf:/openhab/conf \
        -v /volume1/docker/openhab/userdata:/openhab/userdata \
        -p 8080:8080 \
        -p 8443:8443 \
        -p 8101:8101 \
        -p 9898:9898 \
        -p 9898:9898/udp \
        -d \
        --restart=always \
        openhab/openhab:2.2.0-snapshot-amd64
```
My host is Synology.

**Comment by martinvw** [comment]
You should pass a -t it needs to have a tty available otherwise it terminates, we should add this to the 2.2 release notes, could you do that?

https://github.com/openhab/openhab-distro/wiki/Draft-for-openHAB-2.2-Release-Notes

Thanks!

**Comment by beshkenadze** [comment]
@martinvw Sorry, but I don't really understand for what?

**Comment by martinvw** [comment]
For example add the -t just after the -d or was that not your question? 

```Bash
sudo docker run \
        --name openhab-snapshot \
        --net=host \
        -v /etc/localtime:/etc/localtime:ro \
        -v /etc/TZ:/etc/timezone:ro \
        -v /volume1/docker/openhab/addons:/openhab/addons \
        -v /volume1/docker/openhab/conf:/openhab/conf \
        -v /volume1/docker/openhab/userdata:/openhab/userdata \
        -p 8080:8080 \
        -p 8443:8443 \
        -p 8101:8101 \
        -p 9898:9898 \
        -p 9898:9898/udp \
        -d \
        -t \
        --restart=always \
        openhab/openhab:2.2.0-snapshot-amd64
```

**Comment by beshkenadze** [comment]
@martinvw yep, it's not my question :) 
The problem in the MiHome Binding. I was advised to try the snapshot, but it crashes with internal errors.

**Comment by martinvw** [comment]
If you experience that the new 2.2 openhab quits after starting (with or without error) you should make sure you call docker with `-t` 

Because the error you posted above has nothing to do with the mihome binding.

**Comment by beshkenadze** [comment]
@martinvw I can export the logs from the Docker at any time, there is no need in the parameter.
I am interested in the error in binding :)
In any case, thanks for the advice!

**Comment by beshkenadze** [comment]
Okay.

**Comment by beshkenadze** [comment]
Okay, I was able to run the snapshot version and there this bug is fixed.
