### ISSUE TITLE
Jar files are touched and fill up ramdisk although they are not modified

### ISSUE THREAD

**Issue by lauhub** [openhab/openhab2-addons#2721]
## Context

I run OpenHab on a development box under Debian 8 (Armbian Jessie) and I set an [`overlayfs`](https://www.datalight.com/blog/2016/01/27/explaining-overlayfs-%E2%80%93-what-it-does-and-how-it-works/). This makes the mass storage device to be safe (mounted as read-only), even with power breakage.

This overlay FS is schematically a RamDisk that receives all write operations and store them while the permanent storage is read as an underlayer. Writing on the overlay FS effectively writes in the ramdisk, not in the permanent storage device.

If electric power is lost, all changes in RamDisk are lost, but the permanent storage is not altered.

Any file that is [`touch`ed](https://en.wikipedia.org/wiki/Touch_(Unix)) is copied (duplicated) from the underlying permanent storage to the RamDisk. So it occupies some RAM even if its content did not change

## Expected Behavior

When running `openhab2` only some files should be modified and the footprint in RamDisk should be kept low. Installed addons JAR files should not be modified since they are not updated or re-installed.

## Current Behavior

At startup or after startup, `openhab2` `touch`es (in the UNIX way of the term) several jar files [(see link with list of addons' touched files)](https://gist.github.com/lauhub/09db500a12543d6c7f7dd49eb9d2751c) and fills up the RamDisk with about 141MB of unuseful data

By unuseful I mean that these files are not modified: md5 sum of both RamDisk and permanent storage are identical

Current ramdisk is 512MB, which leads to some crash if it is filled up. I am limited to this size (total amount of RAM : 1GB) and this *cannot* be changed since the box cannot have more RAM 

## Possible Solution

 - Remove the `touch` of the file if it already exists
 - Setup the `/var/lib/openhab2/kar/openhab-addons-2.1.0` as read-only (but this may lead to bug when installing or updating addons)

## Steps to Reproduce (for Bugs)

1. Create a read-only system with an overlayroot (under Ubuntu using the overlayroot package).
2. Install openhab2
3. use `df -h` to show ramdisk usage

## Your Environment

* Version used: 2.1.0
* Addons list: see [this gist](https://gist.github.com/lauhub/09db500a12543d6c7f7dd49eb9d2751c)
* Environment name and version : java version "1.8.0_131"
* Operating System and version: Armbian Jessie

**Comment by kaikreuzer** [comment]
Hi @lauhub, thanks for reporting this.
Please note that this issue is not about an individual addon, so this is actually the wrong issue tracker to report it - the better choice would be https://github.com/openhab/openhab-distro/issues.

Nonetheless, I doubt that there is anything we can do about it ourselves, because the openHAB distro merely uses Apache Karaf to do the [KAR handling](http://karaf.apache.org/manual/latest/kar) - so what you observe clearly seems to be the normal behavior of Karaf. I would hence assume that you might get the best help at http://karaf.922171.n3.nabble.com/Karaf-User-f930749.html.

**Comment by maggu2810** [comment]
Just FYI: Instead of using nabble this list web frontend looks much better: [Pony Mail -
 user@karaf.apache.org]

[Pony Mail -
 user@karaf.apache.org]: https://lists.apache.org/list.html?user@karaf.apache.org
