### ISSUE TITLE
[homekit] Thermostat mode does not accept string value?

### ISSUE THREAD

**Issue by ccaramel** [openhab/openhab2-addons#2723]
I'm trying to create a rule to convert thermostat mode (KNX behaviour) to homekit.

KNX behaviour is "1" for heating and "0" for cooling

The simple rule is described here:
```
rule "Thermostat bureau homekit"
when
        Item BureauThermostatMODE received command
then
        var String mode
        if (BureauThermostatMODE.state==ON)
                {
                mode = ("heat")
                sendCommand (BureauThermostatHeatingCoolingMode, mode)
                }
                else
                {
                mode = ("cool")
                BureauThermostatHeatingCoolingMode.postUpdate(mode)
                }

end
```

In response, I have a rare issue:

```
[INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'BureauThermostatMODE' received command ON
[ERROR] [al.accessories.HomekitThermostatImpl] - Unrecognized heating cooling target mode: heat. Expected cool, heat, auto, or off strings in value.
[ERROR] [al.accessories.HomekitThermostatImpl] - Unrecognized heating cooling target mode: heat. Expected cool, heat, auto, or off strings in value.
[INFO ] [smarthome.event.ItemStateEvent      ] - BureauThermostatHeatingCoolingMode updated to heat
[INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'BureauThermostatHeatingCoolingMode' received command heat
```

Is someone have any idea?
Regards.

**Comment by Wolph69** [comment]
No idea, but I have the issue. 
Since My danfoss raditator thermostats don’t have a mode option iOS shows the thermostats as OFF while being able to set the temperature. 
My idea was to initialize the mode in the thermostat’s group with the same result as described here. 
Any solution or idea so far?

**Comment by grzegorz914** [comment]
@ccaramel 
Please post your HomeKit settings, all mode need to be same as in HomeKit settings.
Default is Auto, Heat, Cool, Off.

**Comment by Wolph69** [comment]
Hi @grzegorz914,

here are my settings. Perhaps you have an idea what's wrong here.

.items:
`Group GThermostat_WZ        "Thermostat WZ"     <radiator>  [ "Thermostat" ]
    String HomeKitHCMode_WZ "Wohnzimmer Heizung Heating/Cooling Mode" (GThermostat_WZ) [ "homekit:HeatingCoolingMode" ]
    Number Radiator_WZ          "Heizung WZ"        <radiator> (GThermostat_WZ) [ "TargetTemperature" ] { channel="zwave:device:ed822cda:node6:thermostat_setpoint_heating" } 
    Number Temp_WZ              "Temperatur WZ"        <temperature> (GThermostat_WZ) [ "CurrentTemperature" ] { channel="zwave:device:ed822cda:node14:sensor_temperature" }
`

and in .rules:
`rule "heat_init"
when
	System started
then
    HomeKitHCMode_WZ.sendCommand('auto')
end`

I tried .sendCommand(auto), .sendCommand(Auto) and .sendCommand('Auto') as well with the same result as soon as i open Home in iOS: 
`2018-01-21 23:17:40.446 [ERROR] [al.accessories.HomekitThermostatImpl] - Unrecognized heating cooling target mode: auto. Expected cool, h
eat, auto, or off strings in value.`

Any help would be much appreciated ;)

**Comment by grzegorz914** [comment]
@Wolph69 

please post your settings from HomeKit service?

**Comment by Wolph69** [comment]
Thanks a lot, @grzegorz914!
That helped a lot.
The default setting in homekit.cfg have been:
`org.openhab.homekit:thermostatCoolMode=CoolOn`
`org.openhab.homekit:thermostatHeatMode=HeatOn`
`org.openhab.homekit:thermostatAutoMode=Auto`
`org.openhab.homekit:thermostatOffMode=Off`

That caused the error messages in the log.

Now I am able to set a dummy mode like this:
`    HomeKitHCMode_WZ.sendCommand('auto')
`

The Button in iOS is now active and the mode is set to auto, but iOS is still showing the error message 'no response'

Any hints? :)

**Comment by grzegorz914** [comment]
@Wolph69 

U need to use ("Auto"),(“HeatOn”),(“CoolOn”),(“Off”) as a mode. It work for me ohne any problem.

**Comment by Wolph69** [comment]
Thanks for your help! 
I still get the "no response" error in iOS, but so far everything else is working fine.
I guess,  I get the error because I don't have any physical item linked to "homekit:HeatingCoolingMode".

**Comment by grzegorz914** [comment]
I alao do not have physical Item binded to HeatingCoolingMode and all working OK. I have no “response only” if TargetTemperature can not write or read from source.

Regards

**Comment by Wolph69** [comment]
Thanks @grzegorz914!

after restart of my iPhone the error message had been gone.
I get the error message as soon as i try to change the modus.
Something like this doesn't work:

```
rule "HomeKitStatusSetTemp_WZ"
when 
    Item HomeKitHCMode_WZ received command
then
    if (receivedCommand == 'HeatOn') {
        Radiator_WZ.sendCommand(23)
    }
    if (receivedCommand == 'Auto') {
        Radiator_WZ.sendCommand(21)
    }
    if (receivedCommand == 'CoolOn') {
        Radiator_WZ.sendCommand(16)
    }
    if (receivedCommand == 'Off') {
        Radiator_WZ.sendCommand(10)
    }
end
```

But I at least I can set the mode like that:
`    HomeKitHCMode_WZ.sendCommand('Auto')`

It seems like a sync from iOS to Openhab doesn't work for modus, but works well from Openhab to iOS.

**Comment by kaikreuzer** [comment]
Might hopefully be fixed by https://github.com/openhab/openhab2-addons/pull/4535 - if not, please re-open.
