### ISSUE TITLE
JSR223 Groovy rule throws exception on startup only (MissingPropertyException: No such property: itemRegistry)

### ISSUE THREAD

**Issue by vbier** [openhab/openhab2-addons#2727]
I have a groovy rule that works fine once the system has started, but on startup I
always get:

> 2017-09-22 11:56:02.935 [ERROR] [ipt.internal.ScriptEngineManagerImpl] - Error during evaluation of script 'file:/etc/openhab2/automation/jsr223/shading.groovy': javax.script.ScriptException: groovy.lang.MissingPropertyException: No such property: itemRegistry for class: Script1

I have to touch the rule once the system is up and then it works. The rule can be stripped down to one line and still triggers the error:

`itemRegistry.get("gShutterLocks")`

I have openhabian running and just updated to openHAB 2.2.0 Build #1044 in hope that 
the problem will go away, but is still there.

## Expected Behavior
The rule should parse without errors on system startup.

## Current Behavior
I do get the above mentioned MissingPropertyException.

## Steps to Reproduce (for Bugs)
Install openHAB with JSR223 groovy support, add a rule with the above mentioned content and restart openHAB.

## Environment
openhabian [master]v1.3-303(0e2437c)
openHAB 2.2.0 Build # 1044

**Comment by kaikreuzer** [comment]
This seems to be an issue report about the new rule engine and not about any addon that is in this repository here. So please rather report it at https://github.com/eclipse/smarthome/issues. Thanks!

**Comment by vbier** [comment]
Will do, sorry.
