### ISSUE TITLE
[Xiaomi / MiHome] Get no data from sensors

### ISSUE THREAD

**Issue by mpuff** [openhab/openhab2-addons#2733]
Hello community,

I have run openhab2 in docker on synology.
Port 9898 is forwarded to 9898 in the docker container!
I can add the Xiaomi Mi Smart Home Binding and it is displayed to me online.
I can also find all sensors and integrate them with the status online, but I get no data on the control dashboard.
Only the batteriestatus shows me a value, this is equal with each sensor, which is also funny
Does someone has the same probem?

Thank you

Kind regrads,
mpuff

**Comment by kubawolanin** [comment]
I have no experience with dockerized openHAB, so can't really help.
Maybe @dimalo @tavalin @pboos have more experience?

**Comment by dimalo** [comment]
Hi @mpuff,

the binding works like this:
Discovery: OH sends active requests to the gateway and it responds.
Normal Operation: Gateway sends sensor values via multicast to port 9898 of OH machine

there were already users having problems with routers not forwarding multicast, even between lan and wifi. so might be your problem too? the host machine does not forward multicast traffic to the container...
[have a look here](https://stackoverflow.com/questions/37214608/docker-receiving-multicast-traffic) for example

**Comment by mpuff** [comment]
Hello @dimalo,

thank you very much, with this example i found the error, i dont has set the network to host ( docker command: --net=host), now it is working  :)
