### ISSUE TITLE
[max] Add possibility to see communication errors for MAX! devices

### ISSUE THREAD

**Issue by dominicdesu** [openhab/openhab2-addons#2753]
Sometimes it can happen that a connection error occurs between the MAX cube and one of its devices. This connection error is currently not available in the max binding, it is only visible in the original vendor software:
![grafik](https://user-images.githubusercontent.com/3878009/30935125-fc5955a2-a3cf-11e7-925b-10d4128aebdb.png)

It would be really useful the have a channel for connection errors (or maybe setting the thing to a different state even?), because it usually takes a while until I realize that the thermostat doesn't react to commands anymore. Especially bad if it keep heating the whole night.

I had once implemented this [feature for the OH1 binding](https://github.com/openhab/openhab1-addons/pull/3640), maybe it helps for the 2.0 implementation.

**Comment by cweitkamp** [comment]
I have implemented the suggested feature (see #3795).
