### ISSUE TITLE
[yamahareceiver] Problem with HDMI input

### ISSUE THREAD

**Issue by RickyTR** [openhab/openhab2-addons#2758]
I have some problems in setting HDMI input. To change the input I set the HDMI’s to HDMI1, HDM2 etc. and with this the command goes well but it seems that current input is read as HDMI_1, HDMI_2 etc. . In event log I find this:

017-09-29 21:12:08.195 [ome.event.ItemCommandEvent] - Item ‘AMP_Input’ received command HDMI1
2017-09-29 21:12:08.205 [vent.ItemStateChangedEvent] - AMP_Input changed from HDMI_1 to HDMI1
2017-09-29 21:12:08.417 [vent.ItemStateChangedEvent] - AMP_Input changed from HDMI1 to HDMI_1

I don't know if it's related or not but the Main_zone thing seems to update every minute.

2017-09-30 00:36:13.128 [me.event.ThingUpdatedEvent] - Thing 'yamahareceiver:zone:5f9ec1b3_ed59_1900_4530_00a0dea1f5e0:Main_Zone' has been updated.
2017-09-30 00:37:13.274 [me.event.ThingUpdatedEvent] - Thing 'yamahareceiver:zone:5f9ec1b3_ed59_1900_4530_00a0dea1f5e0:Main_Zone' has been updated.
2017-09-30 00:38:13.350 [me.event.ThingUpdatedEvent] - Thing 'yamahareceiver:zone:5f9ec1b3_ed59_1900_4530_00a0dea1f5e0:Main_Zone' has been updated.

I'm using OH2.2 build 1051 and my receiver is RXV675.

**Comment by davidgraeff** [comment]
To keep your thing in sync with the receiver, we need to poll it periodically. You can change the frequency in the binding configuration. It is one minute per default.

Yamaha AVRs need HDMI1 to be send to it to change to for instance the hdmi 1 input. But it reports HDMI_1 back. Unfortunately this is not consistent. Some AVRs report back HDMI1 some HDMI 1. At the moment I do not intend to change the current behaviour. It took quite some time to make it work for all kind of devices.

I'm happy to receive pull requests to unify the naming. I will have a look at this situation again when I implement the newer Yamaha protocol.

**Comment by RickyTR** [comment]
Everything was working with the version in 2.1 but I understand that you change something to support other models. I think I can solve the problems using rules until the new version of the binding.
Thanks for your work!

**Comment by zarusz** [comment]
Please check out the closely related discussion [here](https://community.openhab.org/t/yamahareceiver-binding-problems/34628/18).

**Comment by zarusz** [comment]
@RickyTR can you please verify if the proposed fix (described in [here](https://community.openhab.org/t/yamahareceiver-binding-problems/34628/18)) solves the problem for you?

**Comment by RickyTR** [comment]
Sorry for my late reply. The problem seems to be there again in the version I downloaded today (org.openhab.binding.yamahareceiver-2.3.0-SNAPSHOT).

**Comment by zarusz** [comment]
@RickyTR where did you take this JAR from?

Here is my most [recent build](https://www.dropbox.com/sh/jm35oeqcmv6si87/AABynvOSOPYLTiiNOXuJKWKra?dl=0) with a bunch of other fixes.

**Comment by RickyTR** [comment]
I took the jar here:
https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/

**Comment by zarusz** [comment]
@RickyTR I have not submitted the PR yet, so the fix for this issue will not be available in the link you provided. At the moment only the link I provided has a version with this issue fixed. 

I plan to submit a PR once I am done with all the changes. If you can, give it a try and confirm if it works for you...

**Comment by RickyTR** [comment]
I’m testing the version you linked and so far so good.
Thanks a lot.

**Comment by zarusz** [comment]
PR has be submitted: https://github.com/openhab/openhab2-addons/pull/3264
