### ISSUE TITLE
JSONPATH returning NULL on item not found can lead to problems with REST API

### ISSUE THREAD

**Issue by sgofferj** [openhab/openhab2-addons#2767]
System: Ubuntu server 16.04 LTS on Xeon 1240L V3. Openhab stable from ppa

I recently included Sonoff B1 lightbulbs with Tasmota fw in my system. Here is an example item config:

```
Switch B1_1_Sw          "B1-1-Switch"           (gALL, gLIGHTS)         { mqtt="<[broker:b1-1/stat/RESULT:state:JSONPATH($.POWER)],  >[broker:b1-1/cmnd/POWER:command:*:${command}]" }
Number B1_1_Dim         "B1-1-Dimmer"                                   { mqtt="<[broker:b1-1/stat/RESULT:state:JSONPATH($.Dimmer)], >[broker:b1-1/cmnd/Dimmer:command:*:default]" }
Number B1_1_CT          "B1-1-ColorTemp"                                { mqtt="<[broker:b1-1/stat/RESULT:state:JSONPATH($.CT)],     >[broker:b1-1/cmnd/CT:command:*:default], >[broker:b1-1/cmnd/CT:command:*: ]" }
String B1_1_Col         "B1-1-Color"                                    { mqtt="<[broker:b1-1/stat/RESULT:state:JSONPATH($.Color)],  >[broker:b1-1/cmnd/Color:command:*:default]" }
```

The B1 with tasmota software answers to all commands with

> stat/RESULT {“POWER”:“ON”, “Dimmer”:100, “Color”:“FFFFFFFFFF”}

(of course with appropriate values). It also answers with this to the cmnd/CT command which sets the color temperature. If you want the color temperature in a reply, you have to send an empty cmnd/CT and you will get something like this.

> stat/RESULT {“CT”:500}

Now, JSONPATH returns NULL if it can’t find the path item you are asking for, and as both the standard as well as the CT reply use the RESULT path, there’s always something going to be NULL. If you send a regular command, CT will be NULL and if you ask for CT, POWER, Dimmer and Color will be NULL.

That lead to this messages in the log:

> 2017-10-03 20:12:50.277 [WARN ] [b.core.events.EventPublisherDelegate] - given new state is NULL, couldn’t post update for 'B1_1_CT’
> 2017-10-03 20:12:50.282 [WARN ] [b.core.events.EventPublisherDelegate] - given new state is NULL, couldn’t post update for 'B1_1_CT’
> 2017-10-03 20:12:50.325 [WARN ] [b.core.events.EventPublisherDelegate] - given new state is NULL, couldn’t post update for 'B1_1_Sw’
> 2017-10-03 20:12:50.325 [WARN ] [b.core.events.EventPublisherDelegate] - given new state is NULL, couldn’t post update for ‘B1_1_Dim’

And after a short while the REST API would reply to an items request with a 500 java.lang.NullPointerException.

See also https://community.openhab.org/t/connection-lost/34744/15

**Comment by kaikreuzer** [comment]
Transform services are part of ESH, so may I ask you to please report that issue at https://github.com/eclipse/smarthome/issues? Thanks!

**Comment by sgofferj** [comment]
Well, one could also see it as a bug that the REST API blows up if an item is NULL... ;) :D
