### ISSUE TITLE
Add HomeEasy Binding

### ISSUE THREAD

**Issue by cniweb** [openhab/openhab2-addons#2769]
It would be very nice if one would be program a binding for HomeEasy Smartwares (wireless sockets).
A cli for the HomeEasy Smartwares HE853 USB device can be found here:
https://github.com/hphde/he853-cli

**Comment by cniweb** [comment]
Software Download can be found here:
http://service.smartwares.eu/en-us/product/10.036.05/he853-he-comp-usb-netwerk-dongle.aspx?tab=downloads

**Comment by J-N-K** [comment]
No progress for 18 month, closing here. Please open a new issue if someone works on this.
