### ISSUE TITLE
[avmfritz] add support for FRITZ Dect 301

### ISSUE THREAD

**Issue by WannabeNerd** [openhab/openhab2-addons#2772]
Since AVM introduced the new [Fritz!Dect 301 on IFA 2017](https://en.avm.de/ifa-2017/) in Berlin a while ago, I wondered if you could add support for Fritz!Dect 301. I guess from an API perspective its nothing more than a FritzDect300 with new model name.

**Comment by cweitkamp** [comment]
Hi WannabeNerd,

yes of course. I already have a branch in my porsonal fork for supporting the new device https://github.com/cweitkamp/openhab2-addons/commits/AVMFritzDECT301. I am currently waiting for AVM to announce an official release date. ;-)

@martinvw Please assign me to this. Thx. Do you think I should already contribute? Even if the device could not be purchased, yet?

**Comment by martinvw** [comment]
@kaikreuzer can you add @cweitkamp as contributor so I can also assign him here?

> Do you think I should already contribute? Even if the device cannot not be purchased, yet?

If the API is defined already why not :-)

**Comment by kaikreuzer** [comment]
> can you add @cweitkamp as contributor so I can also assign him here?

He has got an invitation!

**Comment by cweitkamp** [comment]
@kaikreuzer @martinvw Invitation accepted. Thank you very much.

**Comment by martinvw** [comment]
:-)

**Comment by WannabeNerd** [comment]
Wow you guys are quick! Thanks for the immediate reaction. If you need somebody to test the functionality I volunteer because I happen to have a Fritz Dect 301 already installed, which of course is why I made this issue in the first place ;)

**Comment by cweitkamp** [comment]
That is a reason to open the PR right away. Here you are PR #2774.

**Comment by WannabeNerd** [comment]
Thank you for the PR. Assuming it will be merged soon - whats next? I installed my openhab2 via the package manager of my distribution (raspbian on my raspberry pi 2). How exactly do I upgrade my existing openhab2 installation to the new state of this repo? Is it possible to only upgrade the binding "avmfritz"?

**Comment by cweitkamp** [comment]
Well, both is possible. After this PR gets merged it will be available in the snapshot version of OH2. How you install the snapshot on linux based sytems is decribed here: http://docs.openhab.org/installation/linux.html#package-repository-installation.

On the other hand you can download the current binding version here: https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/org.openhab.binding.avmfritz/2.2.0-SNAPSHOT/. Uninstall the original binding first and then put the new .jar file into your addons folder. Read more about folders here: http://docs.openhab.org/installation/linux.html#file-locations.

Please keep in mind that the avmfritz binding currently depends on some changes in the underlying ESH framework which are not compatible with OH2 2.1.0. I recommend you to use the first solution unless you are knowing what you are doing. ;-)

**Comment by WannabeNerd** [comment]
Ok thank you very much. I guess I'm going to try the the installation of the snapshot verison of OH2 then :)

**Comment by WannabeNerd** [comment]
Hey guys, I just saw that the PR was merged. So I installed the snapshot version of OH2 as it is described in the [documentation](http://docs.openhab.org/installation/linux.html#package-repository-installation). 

Unfortunately my OH2 becomes stuck at  
`"Please stand by while UIs are being installed. This can take several minutes." `
In the log I found entries like: 
` ERROR org.openhab.core.karaf.internal.FeatureInstaller - Failed installing 'open...
Okt 11 23:00:49 raspberrypi2 karaf[4848]: Error downloading mvn:org.openhab.ui/org.openhab.ui.habmin/2.2.0-SNAPSHOT
`
Any ideas?

**Comment by cweitkamp** [comment]
Sry to say. The PR wasn't merged, yesterday.

For your update problem I have to point you to the [community forum](https://community.openhab.org/). I am afraid I cannot help you very much with that.
