### ISSUE TITLE
[network] TTL on discovery results 

### ISSUE THREAD

**Issue by martinvw** [openhab/openhab2-addons#2776]
Follow up of https://github.com/eclipse/smarthome/issues/4391

See also: https://community.openhab.org/t/network-snapshot-inbox-being-filled-and-emptied/34968

@kaikreuzer stated:
> The TTL is NOT meant to rush the user to accept a discovery result asap. This is not the summer clearance sale.
>
>So I guess the discussion comes up because the network binding simply misuses this feature. Using a TTL without background discovery imho does not really make sense.

The question originated from me not being able to accept results before their TTL was over, while @davidgraeff choose this solution because he felt there was no proper alternative:

> That’s intended. Because the network binding causes a mess in the inbox, politely spoken, all entries have a TTL.

**Comment by martinvw** [comment]
So the main point is should we accept that it becomes messy with so many discovered devices or should we remain using the TTL? 

Or maybe but I don't know how feasible it is limit / group items. For example something that offers both an apple-service and an http-service should maybe be just one Thing

**Comment by kaikreuzer** [comment]
The "normal" way is that the user should simply "ignore" results in which he is not interested.
I see that the network binding is quite some exception as it indeed can create a large set of discovery results. So maybe some "bulk ignore" / "bulk delete" feature could help here, but I am a bit hesitant to suggest adding such a feature to the Paper UI just because of a single binding...

**Comment by martinvw** [comment]
Okay, for now I created a [PR](https://github.com/openhab/openhab2-addons/pull/2773) to at least mention its 'hack' in the README and extended it to 10 minutes. 

So we don't have to decide today 😉 , however this is new in the SNAPSHOT so it did not hit the full public yet, so I think we want to act somehow before releasing it.

**Comment by davidgraeff** [comment]
in my opinion TTL makes sense. we don't know how long those network devices will stay but one think is certain: they will not stay forever (DHCP IP change, mobile out of WiFi range, IP TV off), so why should the inbox results.

**Comment by martinvw** [comment]
> in my opinion TTL makes sense. we don't know how long those network devices will stay but one think is certain: they will not stay forever (DHCP IP change, mobile out of WiFi range, IP TV off), so why should the inbox results.

Yes but the main difference with the case where there is background discovery running is that network devices disappear from inbox while they are still available. And I think that @kaikreuzer point is that that was not what the TTL was intended for.

**Comment by davidgraeff** [comment]
What I can imagine that we do is, we keep the list of results and use a background discovery to watch devices if they are still reachable, before the TTL value causes them to be removed.

**Comment by martinvw** [comment]
I think that is indeed the proper solution, I do not yet know how hard it is, is it something you expect to have time for?

**Comment by kaikreuzer** [comment]
I am not sure if this is a proper solution. The network binding does NOT have any background discovery on purpose as it can be a very heavy operation. And doing a background discovery that merely removes stuff instead of adding new results is also not an expected behavior (while it still can be expensive/undesired when you have a lot of devices on your network).

**Comment by martinvw** [comment]
So there is no proper solution...

**Comment by kaikreuzer** [comment]
Imho the proper solution is to discard all not-found-anymore results after every newly manually triggered scan (that should be the normal behavior anyhow) and leave it to the user to ignore anything he is not interested in.

**Comment by martinvw** [comment]
@davidgraeff reading the linked PR and this issue it does not seem completely fixed or where other changes made to this behavior?

**Comment by davidgraeff** [comment]
Hm. True. I think I have closed this because there was no progress or conclusion. Can be reopened of course. I guess the TTL can be removed or only be applied for ping devices and not TCP port things.
