### ISSUE TITLE
[rfxcom] "Cannot delegate update" warnings with CoCo switch

### ISSUE THREAD

**Issue by stefaanv** [openhab/openhab2-addons#2791]
Hi,
I added a coco switch to (otherwise perfectly) running openhab2 system with RFXcom bridge.  The system is currently cupturing a number of OrgonScientific thermometers and was doing fine.
Recently, I added a coco wireless switch and configured with the PaperUI.
Things are working fine - I can see the state of the coco switch in the PaperUI "Control" screen, but there is the below error message in the log every tie I press the swtich.  What's going wrong ?
```
09:25:03.117 [DEBUG] [binding.rfxcom.handler.RFXComHandler] - Received message from bridge: rfxcom:bridge:238adf67 message: Raw data = 0B11000000E24AA20A000070, Packet type = LIGHTING2, Seq number = 0, Sub type = AC, Device Id = 14830242.10, Command = OFF, Dim level = 0, Signal level = 7
09:25:03.131 [INFO ] [marthome.event.ItemStateChangedEvent] - cocoSchakelaarTv changed from ON to OFF
09:25:03.132 [WARN ] [ome.core.thing.internal.ThingManager] - Cannot delegate update 'OFF' for item 'cocoSchakelaarTv' to handler for channel 'rfxcom:lighting2:238adf67:coco_schakelaar:command', because no thing with the UID 'rfxcom:lighting2:238adf67:coco_schakelaar' could be found.
```
## Environment
Ubuntu 16.04 on Intel x64 architecture
OpenHAB2 version 4.0.8
RFX binding 2.1.0

**Comment by martinvw** [comment]
It seems like some inconsistency, can you retry and list the name / ids of things and items that are involved if possible including some context.
