### ISSUE TITLE
[systeminfo] cpu#load15 not formatted correctly

### ISSUE THREAD

**Issue by Andirs55** [openhab/openhab2-addons#2812]
cpu#load is automatically formatted to show up between 0-100 and automatically includes the % character on the sitemap. However cpu#load15 (maybe also cpu#load1, cpu#load5 as well) are formatted as 0.0-1.0 without the % character. 

In my opinion that is not intended (since a percent value is more intuitive) and should be fixed.

Thanks

**Comment by martinvw** [comment]
Those are not percentages afaik

**Comment by Andirs55** [comment]
Ok i see

**Comment by martinvw** [comment]
It was not the same as the other post the load1, load5 and load15 are:

> Returns the system load average for the number of elements specified, up to 3, representing 1, 5, and 15 minutes. The system load average is the sum of the number of runnable entities queued to the available processors and the number of runnable entities running on the available processors averaged over a period of time. The way in which the load average is calculated is operating system specific but is typically a damped time-dependent average. If the load average is not available, a negative value is returned. This method is designed to provide a hint about the system load and may be queried frequently. The load average may be unavailable on some platforms (e.g., Windows) where it is expensive to implement this method.

So not a percentage indeed
