### ISSUE TITLE
[Squeezebox] web radio doesn't update cover art

### ISSUE THREAD

**Issue by phil2fer** [openhab/openhab2-addons#2813]
hi all,

When i listen web radio the cover art image doesn't update.
I think is not a bug but an improvement

I will try to change code by myself but it will take some time..
The subscribe message need K tag

> K | artwork_url | A full URL to remote artwork.  Only available for certain online music services.

and we have to check message begining with : artwork_url%3A

best regards

## My Environment
OpenHAB2 (2.1) on RPi3

**Comment by phil2fer** [comment]
Hi,

I try to export the modified binding into a jar file. Everything seems to be ok but when i put the file into the addons folder and install the binding, i have a message in the log

> 2017-11-01 10:19:10.403 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-squeezebox': Error restarting bundles:
> Could not resolve module: org.openhab.binding.squeezebox [206]
> Another singleton bundle selected: osgi.identity; osgi.identity="org.openhab.binding.squeezebox"; type="osgi.bundle"; version:Version="2.2.0.qualifier"; singleton:="true"

I don't know if it is important or not..

Before i make the PR, i'll really appreciate if someone could test this jar file 

[org.openhab.binding.squeezebox.jar.pdf](https://github.com/openhab/openhab2-addons/files/1433750/org.openhab.binding.squeezebox.jar.pdf)

**Comment by mhilbush** [comment]
I installed it, and it discovered my server and players just fine.

I've not seen the above error before.  Are you sure you completely uninstalled the version that came with your distribution?

What do you see in the karaf console when you check what's installed?  For example
```
bundle:list -s | grep squeezebox
```

**Comment by phil2fer** [comment]
you are right the version that came with my distribution is not completely uninstalled

```
openhab> bundle:list -s | grep squeezebox
204 │ Active    │  80 │ 2.2.0.qualifier        │ org.openhab.binding.squeezebox
206 │ Installed │  80 │ 2.2.0.201710280843     │ org.openhab.binding.squeezebox
```
However the jar file working correctly for me too.

I have detect another case when the cover art is not correctly refresh, i'll try to fix it
