### ISSUE TITLE
[Homematic] HmIP Door Window Contact paired as String, not as Contact - corrected for HMIP-SWDO but not HMIP-SWDO-I

### ISSUE THREAD

**Issue by mrehker** [openhab/openhab2-addons#2817]
This issue is related to #1564 where a virtual datapoint of type contact was added für HMIP-SWDO. Unfortunately, the StateContactVirtualDatapointHandler.java only recognises HMIP-SWDO and not the (newer) HMIP-SWDO-I, which currently only provides the status as a string. This again does not allow the contact to be used in openhab2, because updates are not recognised in the rules.

I would propose to modify 

private boolean isApplicable(HmDevice device) {
        return "HMIP-SWDO".equals(device.getType());
}

to 

private boolean isApplicable(HmDevice device) {
        return "HMIP-SWDO".equals(device.getType()) or "HMIP-SWDO-I".equals(device.getType()); 
}
so that it also returns true for HMIP-SWDO-I

**Comment by gerrieg** [comment]
I've overlooked this issue, sorry. This will be implemented in one of the next 2.4 snapshots.

**Comment by mdicke2s** [comment]
This issue was moved to eclipse/smarthome#5786
