### ISSUE TITLE
[Tradfri] Binding doens´t provide group events after Tradfri App/Gateway Update

### ISSUE THREAD

**Issue by haukman** [openhab/openhab2-addons#2823]
I´m using Tradfri Group events in my OpenHab-config to trigger some other devices in my livingroom. After the update from IKEA for the App/Gateway (which makes HomeKit/Alexa available) the events.log stopped receiving these events. I can still control all my tradfri devices from OpenHab, so this is not a generell connection issue.

Can someone confirm this behaviour?

## Expected Behavior
Pressing the Tradfri-Remote (that is part of a Tradfri group), should create event in my envents.log (worked fine until update)

## Current Behavior

No events displayed int the events.log anymore
## Steps to Reproduce (for Bugs)

1. Add a tradfri-Group to your config.things, config.items
2. Turn the lights on and off and watch the events.log

## Your Environment

* Version used: (e.g., openhab and addon versions)
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):

**Comment by kaikreuzer** [comment]
Please note that Tradfri is maintained at ESH, so check https://github.com/eclipse/smarthome/issues?q=is%3Aissue+is%3Aopen+label%3ABinding-Tr%C3%A5dfri. Thanks!
