### ISSUE TITLE
[homekit] No accessories found when using Synology NAS

### ISSUE THREAD

**Issue by peter9310** [openhab/openhab2-addons#2826]
I installed openhab2 on my Synology. This is working. I Installed the homekit binding.
I also configured the [homekit binding] with the following:

Port: 9124
PIN: 062-25-954
Network: 192.168.178.25 (This is my IP adress for the Synology)

## Expected Behavior
I am using IOS 11. If i start Homekit on the Iphone i first have to input the PIN 062-25-954 but 
Homekit searches and searches and there is nothing found.

## Current Behavior
Because i am not a Software Guru i do not know how to solve this issue

## Possible Solution
I have no idea

## Steps to Reproduce (for Bugs)
It is not complicated. Just start the phone with IOS11 and put in the PIN - nothing happens!

## Context

What i would like to get: an icon in homekit on the phone for openhub.

## Your Environment
Synology 
Added: HOMEKIT BINDING, 
OPENHAB 2
Iphone 7plus withe Homekit and IOS11.0.3 (15A432)

**Comment by rngtng** [comment]
same behaviour here. Is your synology connected via WIFI or Ethernet?

**Comment by peter9310** [comment]
I have plugged it on the ethernet.

My main topic is that i have not a exact configuration knowledge for this. I installed all on the synology openhub2 and the binding homekit but the phone under ios11 does not fing anything.

**Comment by rngtng** [comment]
hm ok same here... sorry can't help..

**Comment by peter9310** [comment]
Hello!

Is someone here who can help!

**Comment by wborn** [comment]
Is this still an issue and did you also add tags to your items as described in the [HomeKit add-on documentation](https://www.openhab.org/addons/integrations/homekit/#item-configuration)?

**Comment by J-N-K** [comment]
Probably either fixed or invalid (configuration issue on Synology). 6 month no response.
