### ISSUE TITLE
[amazondashbutton] Problem with setcap to java

### ISSUE THREAD

**Issue by sagittarius0815** [openhab/openhab2-addons#2827]
## Current Behavior
if I set capabilities to use Pcap4J with java for non root user, my openhab2 service will not start.
Error message is
/usr/bin/java: error while loading shared libraries: libjli.so: cannot open shared object file: No such file or directory

If I only remove capabilites (setcap -r) openhab2 service is working.
Java is not running for non root user if capabilities are set. In this case java is running only for root user.

Any ideas how to solve this?

## Steps to Reproduce 

```
pi@openhab2:~ $ java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) Client VM (build 25.111-b14, mixed mode)

pi@openhab2:~ $ sudo setcap cap_net_raw,cap_net_admin=eip $(realpath /usr/bin/java)
pi@openhab2:~ $ java -version
java: error while loading shared libraries: libjli.so: cannot open shared object file: No such file or directory
pi@openhab2:~ $ sudo java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) Client VM (build 25.111-b14, mixed mode)

pi@openhab2:~ $ sudo setcap -r $(realpath /usr/bin/java)
pi@openhab2:~ $ java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) Client VM (build 25.111-b14, mixed mode)
```

## Your Environment
Running OH2 (2.2.0 Build #1071) on raspberry pi 3 (raspian)
Installed Amazon Dash Button and Pcap4J according to the instructions.

**Comment by sagittarius0815** [comment]
Found a possible solution at [stackexchange](https://unix.stackexchange.com/questions/87978/how-to-get-oracle-java-7-to-work-with-setcap-cap-net-bind-serviceep)

1. find path to libjli.so
```
pi@openhab2:~ $ ldd  $(realpath /usr/bin/java)
	linux-vdso.so.1 (0x7ec03000)
	/usr/lib/arm-linux-gnueabihf/libarmmem.so (0x76fc2000)
	libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x76f87000)
	libjli.so => /opt/java/jdk1.8.0_111/bin/../lib/arm/jli/libjli.so (0x76f6a000)
	libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0x76f57000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x76e16000)
	/lib/ld-linux-armhf.so.3 (0x54b3a000)
	libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0x76de9000)
```
2. add path to java.conf
```
pi@openhab2:~ $ cat /etc/ld.so.conf.d/java.conf
/opt/java/jdk1.8.0_111/bin/./../lib/arm/jli
```
3. build runtime cache
```recognized
pi@openhab2:~ $ sudo ldconfig
(reboot may be necessary)
```
Now openhab2 starts with capabilities set and Amazon Dash Button are recognized.
May be it's helpfull to add this steps to installation instruction?

**Comment by martinvw** [comment]
@ThomDietrich what would be the most appropriate place for this? @sagittarius0815 could you (with some guidance of Thomas) create a PR to document this at the proper place?

**Comment by ThomDietrich** [comment]
Hello @sagittarius0815,
never ran into that issue. Could you please retry with the latest openHAB snapshot? There were some changes in that area recently...

**Comment by davidgraeff** [comment]
Assumed to be fixed. And dashbuttons are EOL.
