### ISSUE TITLE
[systeminfo] CPU Temperature is causing Error in Windows

### ISSUE THREAD

**Issue by negmos** [openhab/openhab2-addons#2842]
When using the CPU temperature channel on Windows installation of OH2, i keep getting this error in the log:

`2017-11-14 14:48:24.641 [ERROR] [oshi.util.platform.windows.WmiUtil  ] - Could not connect to namespace root\OpenHardwareMonitor. Error code = 0x8004100e`

Although the error exists, the temperature is still reported and updated.
I guess the binding is choosing another namespace to check if one fails.

**Comment by negmos** [comment]
Sorry, i forgot to add more details :)

I'm using the below system info:
- OS: Windows 10 (with latest updates)
- CPU: intel core i3 Skylake
- OH2: openHAB 2.2.0 Build #1056
Item configuration:

> Number	cpu_temp		"CPU Temperature [%.1f °C]"	{channel="systeminfo:computer:NeGm-NUC:sensors#cpuTemp"}

**Comment by 9037568** [comment]
This appears to be outside of OH control.
OSHI's logging is pretty awful and this really shouldn't be logged as an ERROR, imo.

But the bottom line is when OH calls OSHI to get the temperature, OSHI runs a number of queries in sequence, switching namespaces along the way, hoping one of them succeeds. See [the code here](https://github.com/dbwiddis/oshi/blob/5c9223bd24d8116c045266000734b218f94941fc/oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsSensors.java).

I believe this ticket should be closed and a new one filed against OSHI.
