### ISSUE TITLE
Add GigasetElements Binding

### ISSUE THREAD

**Issue by hkuhn42** [openhab/openhab2-addons#285]
I am currently working on a OpenHab2 Plugin for GigasetElements based on the inofficial REST API used by their web client (Yes i am aware that this can break in the future but there is no official API and i want to integrate the components i have). As suggested in the guidelines for contributing, i wanted to ask for feedback and clearify some points in advance.

I am planning to use Apache CXF as JAX-RS rest framework but as REST is such a common approach for home automation apis, i wondered wethere there are or will be an "official" api and guidelines for this. Checking the existing code i did not see any common rest libs used or "exposed" by the framework. Are there any plans for such a basic service?
##

**Comment by kaikreuzer** [comment]
Interesting approach! It is indeed pretty annoying that Gigaset does not offer any official APIs - maybe they will notice one day that this would actually be a selling point for them...

Hi have recently created the page https://github.com/eclipse/smarthome/blob/master/docs/sources/development/extensions/bindings/dependencies.md for giving some advice on libraries to use. So far, we only list the Apache HTTP components for general HTTP client use cases, but we do not have any specific library for REST. I agree that it would make sense to have a suggestions there (and possibly the lib directly available within openHAB 2, so the bindings don't have to bundle it).
@kgoderis used the JAX-RS client that is part of Jersey (see https://github.com/openhab/openhab2/blob/master/addons/binding/org.openhab.binding.tesla/META-INF/MANIFEST.MF), which is already contained within the REST API of openHAB. As both are implementing JAX-RS, I assume that this is compatible with Apache CXF? So is there any reason why CXF might be better suited? In general JAX-RS API seems to be a good choice as it then allows us to replace the implementation at any time, if required.

**Comment by hkuhn42** [comment]
I will definitly stick to JAX-RS. I am currently planning on using a generative approach with annotated interfaces and also exploring the possibility of using a swagger definition to generate the classes completely. As i do not use an official api, i want to keep the time and effort to adopt to api changes to a minimum. 
I have more experience with cxf as i am using it at work (imho it is more flexibel and also covers jax-ws) but i will have a second look on jersey for this. I like the idea of having a jax-rs framework as part of the openhab2 core. It helps to keep a smaller footprint for the bindings and also reduces the risk of multiple possibly outdated and or vulnerable versions of the same libs.

**Comment by kaikreuzer** [comment]
@hkuhn42 Did you make any progress on this?

**Comment by hkuhn42** [comment]
I did some research regarding swagger but the code generated by the java part is not that good (no annotations, not flexible). I started writing a new api but found a project which already implements the rest access. It is not perfect (no comments, no javadoc) but i decided to use it for now and see how far i will get with it. I am planning to check in a first version which allows to control the overall alarm mode after i solved a little problem i still have.

@kaikreuzer 
My current problem ist actually something you could maybe help me with. The first thing i implemented is the mode configuration of the the base (there are three "alarm" modes: home, away, custom ). I am not quite sure how configure that in the thing file. My prototype uses three switches to test it but that is kind of unusable :). Any suggestions?

**Comment by kaikreuzer** [comment]
> found a project which already implements the rest access

Do you have a reference?

> Any suggestions?

Yes! Use a number and provide some state description with it. See e.g. https://github.com/openhab/openhab2/blob/master/addons/binding/org.openhab.binding.max/ESH-INF/thing/thing-types.xml#L201

**Comment by hkuhn42** [comment]
Thanks for the hint. That is exactly what i am looking for. The project by the way is: https://github.com/CurrentContinuation/gigasetelements

**Comment by kaikreuzer** [comment]
> It is not perfect (no comments, no javadoc)

And especially: No license information! (at least I could not find any)
Before using this lib, you should definitely ask the author to add a license to his project, since otherwise you will infringe his copyright by using his code and I definitely won't be able to accept your binding as a contribution to openHAB.

**Comment by hkuhn42** [comment]
He stated that the software is open source (in terms of no copyright). However you are right in that this is not suffice so i asked him to clarify this and he did. Could you please check wether this is acceptable for openhab2? Also i pulled the repository and will add a new one with a better name soon (when i figured out whats broken with my workspace and get it to work ;)

**Comment by kaikreuzer** [comment]
> Could you please check wether this is acceptable for openhab2?

Looks like some kind of BSD-like license, should imho be ok.

**Comment by bercht-a** [comment]
Hi, I'am very interested in this binding. Is there a beta version for testing?

**Comment by hkuhn42** [comment]
Hi, i am afraid not.  Actually i am currently working on a alpha version. I had one but they made some changes to the api so i have to fix these. My next goal ist to get a version which is able to login and change the mode. @bercht-a  What kind of functionality would you like to use / need?

**Comment by bercht-a** [comment]
Changing the mode is the most important functionality for me. But it would be nice, to have an event in case of an alert (Probably need some kind of polling).

**Comment by hkuhn42** [comment]
I have a very early alpha version on https://github.com/hkuhn42/openhab2.elements
I is still extremly far from complete but it can set the mode and discovery all sensors of the base. During startup, the battery status of the sensors is updated. Everything else is still broken :)

As automatic discovery is not possible (i need a user and password to connect to the gigaset cloud) i looked into manual discovery. I could not find any examples so I used a channel of the base as a trigger. I would really appreciate feedback regarding this approach.  

Finally, there are two new components (Pug and Button) and the camera which i do not own. If someone happens to own them, a copy of the response dump of the base init (its dumped to system.out during discovery and startup) would be nice.

**Comment by kaikreuzer** [comment]
> I could not find any examples so I used a channel of the base as a trigger. I would really appreciate feedback regarding this approach.

You indeed cannot do a discovery of the bridge/gateway as this requires the credentials for the cloud. So this Bridge could be manually defined by the user. But once such a Bridge exists, you can register a DiscoveryService implementation for the end devices; this could potentially even support auto-discovery, can't it? See the documentation at https://www.eclipse.org/smarthome/documentation/development/bindings/discovery-services.html#discovery.

As an example see https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/HueThingHandlerFactory.java#L89, where once a Hue bridge handler is instantiated, it also registers a LightDiscoveryService that is capable of reading information about available lights from a Hue bridge.

**Comment by hkuhn42** [comment]
@kaikreuzer first of all, thank you for taking the time to help some clueless newbe like me, i really appreciate it.

I saw the Hue Bindings two differenc discovery services and tried to mimic its Light Discovery related behavier by implementing and registering a DiscoveryService but it just did not get triggered. So by example i actually meant that i could not find the code that actually triggers a newly registered DiscoveryService and thus misunderstood the part about active scans in that i had to actually implement a means to call the discovery service. After your post i took the time to review everything and found the problem.
In the end i just forgot to set the supported thing types. After fixing that, it workes like a charm. Thanks again!

**Comment by kaikreuzer** [comment]
Good to hear :-)

**Comment by hkuhn42** [comment]
I just checked in a new version of the binding (https://github.com/hkuhn42/openhab2.elements).
Changes are:
- I wrote a new api with jax-rs 2.0 proxy api using jersey
- After adding the base, Autodiscovery works for door, motion, window and siren sensors
- IntrusionSettings mode can be changed
- Firmware, battery and (window / door) open status channels are display and updated every 30 seconds

**Comment by kaikreuzer** [comment]
Sounds like a good progress!
I see that you have bundled a lot of Jersey/Jackson libraries in your bundle. Are you aware that Jersey is already available in other bundles and all you need to do is to import the packages you need?
Please also note that the recommended JSON parser is GSON (which is also available for use already) and not Jackson - so if it is easy to refactor, I would recommend to do so as it will heavily shrink the size of your binding.

**Comment by hkuhn42** [comment]
@kaikreuzer thanks for the fast feedback. I am acutally all for not bundeling the same jars over and over again so I really tried to use the eclipsesource jersey plugin first. However it does not export the proxy api and i wanted to use that because it is so much simpler and more flexible. I also tried to just add the jar for proxy api but i got some strange classNotFound Issues afterwards. If there are other plugins that export the complete jersey package, i will happily use one of them.
Regarding the JSON Parser i was actually not aware that there was a recommanded one (is there a page for these?  the dependencies page you created back in june seems to be gone and i could not find anything when i checked last). I saw that two other plugins (avmfritz and freebox) use it. Also I used Jackson in the past because it gives you a lot of flexibility with the models by its annotations. 
I will have a look at GSON when i find the time but i will definitly have to recreate the complete client model.
In general i am with you that openhab2 should try to avoid mulitple jars of the same lib and also multiple versions if possible. I actually started to look through the existing plugins to see what kind of dependencies regarding http, jax-rs and json they have (originally because i tried to find my "missing lib"). I stopped after i checked all the jars but i think that it could make sense to either find matching plugins and add them  or add one or two new library plugins to get rid of these direct dependencies. I also would like to suggest adding hints to these plugins to the getting started tutorial.  
P.S. if we need a new library plugin, i would volunteer to create it if nobody else wants to do so

**Comment by kaikreuzer** [comment]
> However it does not export the proxy api 

Which package is this exactly? We could also ask the eclipsesource jersey plugin to simply export it in the next version.

> Regarding the JSON Parser i was actually not aware that there was a recommanded one (is there a page for these?

Yes, here: https://www.eclipse.org/smarthome/documentation/development/bindings/dependencies.html

**Comment by hkuhn42** [comment]
I followed your request and refactored the plugin to use GSON and moved back to importing the eclipsesource classes yesterday and did some more cleanup today. 
It would be really helpfull if somebody with an elements installation would be willing to give the plugin a  try and  me some feedback.
>Which package is this exactly? We could also ask the eclipsesource jersey plugin to simply export it in the next version.

The package is org.glassfish.jersey.client.proxy. I checked and it is not even part of the plugin. It seems to be only one class and about 10 kbyte in size so it is probably not that much of a problem. It would be perfect if you could ask them to include and export it however. 

Thanks for the pointer, i am either blind or the page is newer than my interest in binding development. Teaches me to look there more often :)

**Comment by kaikreuzer** [comment]
> It would be perfect if you could ask them to include and export it however.

Hm, if it does not exist at all in this package, this is an issue. It is meant as a minimal set to run Jersey, so adding optional stuff upon request is a bit against the idea.
10kb does not sound like a lot of code - is it maybe possible to just implement what you need yourself?

**Comment by hkuhn42** [comment]
I actually referenced the com.eclipsesource.jaxrs.jersey-all plugin so i think it may very well be an option for them to add that package in a future version. After all the name somewhat implies that this package should be a part of it, too :).
However, i do not think that getting rid of a single small jar file is worth the effort of trying to copy and maintain the functionality especially regarding future releases of jersey and the jax-rs api. After all, the whole point of using proxy client was to minimize the effort needed in case of changes of the gigaset cloud api.
