### ISSUE TITLE
Inbox polluted with false modules (ZWave Binding)

### ISSUE THREAD

**Issue by Newtt** [openhab/openhab2-addons#2853]
When I hit search module in openhab2, there is something like 6-7 node that comes up. This is weird because the battery is not even in into the switch...

When I try to pair my Duwi wall switch (Z-Wave module), but there is something like 5-6 node that appear, Z-Wave Node 10, Z-Wave Node 9, Z-Wave Node 8, Z-Wave Node 7, etc... and when I try to add them, I keep getting errors (no communication error). How can I permanantly delete old nodes / old try to pair the item ?

**Comment by kubawolanin** [comment]
Hey @Newtt,
I'd advise you to close this issue and open it in https://github.com/openhab/org.openhab.binding.zwave

Cheers!
