### ISSUE TITLE
[harmonyhub] Binding no longer works

### ISSUE THREAD

**Issue by bigbasec** [openhab/openhab2-addons#2854]
This started as a random issue where I would need to restart OH several times for things to start working again.  Now it seems that doing anything w/ the Harmony fails.  

Logs report : 
14:15:00.859 [WARN ] [internal.profiles.ProfileCallbackImpl] - Cannot delegate command 'PowerToggle' for item 'TechnicsAVReceiver_SendButtonPress' to handler for channel 'harmonyhub:device:Backroom:35553137:buttonPress', because no handler is assigned. Maybe the binding is not installed or not propertly initialized.

Happens on all 3 Harmony devices I have, and with any sort of control(changing activities, or a simple button press).  The same type of control through a Vera that I have here works without issue, so I have implemented that as a workaround.  

* Version used: 2.2.0.201711152010     │ HarmonyHub Binding, latest OH2
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...): 
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...): Ubuntu 16.04.3 LTS

**Comment by sihui62** [comment]
Same here, related community forum thread:

https://community.openhab.org/t/harmonyhub-buttonpress-not-working/36248

**Comment by bigbasec** [comment]
Just installed a fresh 2.1 on a vm and confirmed that it works fine there.  So it appears as though something along the way broke this.  Doesn't seem to be getting much attention so I'll likely roll back my whole installation until I can find a point that it works again.

**Comment by bigbasec** [comment]
Updated to 1088, and the binding did work for about 2 hours, now things are back to : 
`22:06:32.872 [WARN ] [internal.profiles.ProfileCallbackImpl] - Cannot delegate command 'PowerToggle' for item 'TechnicsAVReceiver_SendButtonPress' to handler for channel 'harmonyhub:device:Backroom:35553137:buttonPress', because no handler is assigned. Maybe the binding is not installed or not propertly initialized.`

**Comment by bigbasec** [comment]
@digitaldan Any ideas?

**Comment by Xento** [comment]
I have the same issues after updating my snapshot.

When I try to reinit the binding I get this
`19:18:35.750 [WARN ] [home.core.thing.internal.ThingManager] - Initializing handler for thing 'harmonyhub:hub:Wohnzimmer' takes more than 5000ms.
19:18:38.110 [WARN ] [home.core.thing.internal.ThingManager] - Initializing handler for thing 'harmonyhub:device:Wohnzimmer:38150328' takes more than 5000ms.`

**Comment by Xento** [comment]
After 
`apt-get install openhab2=2.2.0~20171109102930-1 openhab2-addons=2.2.0~20171109102930-1`
everything is working again.

**Comment by wborn** [comment]
After some debugging I think it is caused by an issue in the new profiles code. So I've entered  https://github.com/eclipse/smarthome/issues/4622 for this.

**Comment by bigbasec** [comment]
Seems as though you found where the problem is, great first step on getting it fixed.  Currently bouncing all my harmony stuff through an old Vera, sort of annoying.

**Comment by wborn** [comment]
The fix that was made should be available in build #1096. Did anyone try it yet?

**Comment by michaeljoos72** [comment]
I recommend to wait here because of that:

https://community.openhab.org/t/oh2-startup-error-in-latest-build/9082/3?u=michaeljoos

**Comment by martinvw** [comment]
> I recommend to wait here because of that:

Thanks for warning, I believe that the build is currently broken, keep an eye out of the forum for updates.

**Comment by martinvw** [comment]
> I recommend to wait here because of that:
>
> https://community.openhab.org/t/oh2-startup-error-in-latest-build/9082/3?u=michaeljoos

I see reports of users where things are working again after updating to version 1098 https://community.openhab.org/t/oh2-startup-error-in-latest-build/9082/18

Bt if you are coming from a stable release it might wise to install the 1098 as vm or on an other machine to first test :-)

**Comment by bigbasec** [comment]
So I decided after seeing people without issues of updating, which brought me to 1099.  Now nothing, and I mean nothing works.  Zwave has activity, but I have no way of controlling it.  HarmonyHub doesn't work either.  Cleared tmp and cache made no difference.

**Comment by martinvw** [comment]
tmp and cache is not enough, the underlying karaf was upgraded so a lot more is needed. How did you do the upgrade, using the update script? Because that should handle the details. On what environment are you running, maybe it's wise to open a separate thread with this information at the forum and link from here to there.

**Comment by bigbasec** [comment]
apt-get, as I normally do.  Ubuntu 16.04

**Comment by digitaldan** [comment]
Hi, sorry for being late here.  I'm actually between houses and all my harmony hubs are in temporary storage so its going to be hard for me to test for the next 5 weeks until we move in!

**Comment by michaeljoos72** [comment]
@bigbasec did you see already this discussion? it sounds to me that you have the same issue:

https://community.openhab.org/t/oh2-startup-error-in-latest-build/9082/28?u=michaeljoos

**Comment by wborn** [comment]
Did you already resolve the issues with the Harmony binding @bigbasec? I've been running it without any issues since 2.2.0.

**Comment by wborn** [comment]
It was working fine ever since. But we'll have to retest the whole binding after adapting it to the Websocket API now that Logitech has closed the XMPP API that was used for local access. See also #4411.
