### ISSUE TITLE
[rrd4j] RRD4J isn't storing any values

### ISSUE THREAD

**Issue by MichaelFink** [openhab/openhab2-addons#2863]
## Expected Behavior
RRD4J is capable of storing numeric values. 

## Current Behavior
I'm using the latest version from the APT repositories. Unfortunately it seems like RRD4J doesn't store any values. Even the .rrd files aren't generated.
I've put together a minimal test setup: [openhab-minimal.tar.gz](https://github.com/openhab/openhab2-addons/files/1497187/openhab-minimal.tar.gz)
It contains only a single testItem which gets a random value assigned every minute via a rule.
I've only tested it on Linux (Ubuntu 17.10 and Raspbian).
I also tried mapdb which is working fine.
The issue was discussed [here](https://community.openhab.org/t/rrd4j-doesnt-store-any-data/35265).

## Possible Solution
N/A

## Steps to Reproduce (for Bugs)
1. Install openhab2 from scratch using the APT repository
2. Replace /etc/openhab2 with the repro-config --> [openhab-minimal.tar.gz](https://github.com/openhab/openhab2-addons/files/1497187/openhab-minimal.tar.gz) 

## Context
Trying to keep a history of numeric values.

## Your Environment
* Version used: 
  openhab 2.1.0-2 
  openhab-persistence-rrd4j 1.10.0 

* Environment name and version: OpenJDK Runtime Environment (Zulu Embedded 8.20.0.42-linux-aarch32hf) (build 1.8.0_121-b42)
  
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):
Raspbian / Linux raspberrypi 4.9.35-v7+

**Comment by martinvw** [comment]
I spotted an mismatch between the item in the persistence config and items file so maybe there is no issue, [see also my reply at the community forum](https://community.openhab.org/t/rrd4j-doesnt-store-any-data/35265/22)
