### ISSUE TITLE
[Hue Emulation] IMPORTANT dont work with nginx proxy (auth)

### ISSUE THREAD

**Issue by WiredLife** [openhab/openhab2-addons#2864]
Hi all!
I've installed a nginx proxy with this help
http://docs.openhab.org/installation/security.html#nginx-auth
to secure openhab, but after that my Alexa dont find any devices...
After a look @ http://ip/api/discovery.xml i see the URLBase is still @ port 8080 so alexa cant find anything.
Is there a way to change this to my needs?
Thanks!

**Comment by lsiepel** [comment]
You can change the port with the discoveryHttpPort setting that is available in PaperUI -> Configuration -> Services -> Hue emulator -> expert mode.

**Comment by WiredLife** [comment]
Nope doesnt work for me :(
Maybe because i tried some parameters which i cant remove now...
Is there any way to remove saved parameters?

By the way, i found a better solution to allow Amazon Echo access without authentication
iptables -A INPUT -p tcp --dport 8080 -m mac ! --mac-source 00:01:02:03:04:05 -j DROP
Replace 00:01:02:03:04:05 with the mac of Amazon Echo, now it can reach anything without auth (isnt supported by hue bridge i think)
and the rest goes over the proxy on port 80 with auth :)

**Comment by Flole998** [comment]
Of course auth isn't supported! Either turn off auth or make the Hue URLs not require it. Clearly not an issue but designed by philips to work like this. Absolutely nothing we can do about it.

**Comment by lsiepel** [comment]
@WiredLife not sure what your actual bug report / feature request is. Maybe you want to discuss it at the forums. There are workaround as suggested.

**Comment by Flole998** [comment]
This can be closed as it is clearly not an issue. A misconfigured nginx caused the problem.

**Comment by bademux** [comment]
@Flole998  it depends. [Documentation](https://www.openhab.org/docs/installation/security.html#nginx-setup) suggests configuration incompatible with default plugin.
here the fix:

$ cat  /etc/nginx/sites-enabled/openhab 
```nginx
server {
   listen                          80;
   listen                          443 ssl;
   server_name                     myservername;
   add_header                      Strict-Transport-Security "max-age=31536000; includeSubDomains";

    # Cross-Origin Resource Sharing.
#    add_header 'Access-Control-Allow-Origin' 'http://localhost:8080/rest';
    add_header 'Access-Control-Allow_Credentials' 'true';
    add_header 'Access-Control-Allow-Headers' 'Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
    add_header 'Access-Control-Allow-Methods' 'GET,POST,OPTIONS,PUT,DELETE,PATCH';
    
## Secure Certificate Locations
   ssl_certificate                 /etc/ssl/certs/openhab.crt;
   ssl_certificate_key             /etc/ssl/certs/openhab.key;

## Password Protection
   auth_basic                              "Username and Password Required";
   auth_basic_user_file                    /etc/nginx/.htpasswd;

   satisfy  all;
   allow    192.168.1.1/24; #change it if needed
   allow    127.0.0.1;
   deny     all;

   location ~* ^/(api|api/.*|description.xml)$ {
        auth_basic off;
        proxy_pass                              http://localhost:8080;
        proxy_set_header Host                   $http_host;
        proxy_set_header X-Real-IP              $remote_addr;
        proxy_set_header X-Forwarded-For        $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto      $scheme;
   }

   location / {
       proxy_pass                              http://localhost:8080/;
        proxy_set_header Host                   $http_host;
        proxy_set_header X-Real-IP              $remote_addr;
        proxy_set_header X-Forwarded-For        $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto      $scheme;
    }
}
```

**Comment by Flole998** [comment]
@bademux Open an issue at the docs repo and submit your PR there then
