### ISSUE TITLE
mvn clean install does not work anymore

### ISSUE THREAD

**Issue by ymymym** [openhab/openhab2-addons#2865]
Did anyone experience this error after trying to compile a specific binding? mvn clean install command works fine last week. 

[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.openhab.binding.mihome 2.2.0.qualifier
[ERROR]   Missing requirement: org.eclipse.osgi.services 3.6.0.v20170228-1906 requires 'package org.osgi.util.function [1.0.0,2.0.0)' but it could not be found
[ERROR]   Cannot satisfy dependency: org.eclipse.smarthome.config.core 0.9.0.201711202142 depends on: package org.osgi.service.component 0.0.0
[ERROR]   Cannot satisfy dependency: org.openhab.binding.mihome 2.2.0.qualifier depends on: package org.eclipse.smarthome.config.core 0.0.0
[ERROR]
[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: org.openhab.binding:org.openhab.binding.mihome:2.2.0-SNAPSHOT @ C:\Users\yongming.ng\openhab2-master\git\openhab2-addons\addons\binding\org.openhab.binding.mihome\pom.xml: See log for details -> [Help 1]

**Comment by ymymym** [comment]
Managed to resolve by adding org.osgi.util.function in manifest file

**Comment by kaikreuzer** [comment]
There should be no need to add it to your manifest (as your bundle does not depend on it itself). I'll look at what's wrong there.

**Comment by kaikreuzer** [comment]
I have fixed the target platform - you should be able to remove the import from your manifest again!
