### ISSUE TITLE
[yamahareceiver] Cannot delegate command/update

### ISSUE THREAD

**Issue by d3rh3ld** [openhab/openhab2-addons#2866]
After switching from OH stable 2.1.0 to the latest snapshot version (#1084) i had to change the items for the yamahareceiver. Now i am getting errors, when i try to send a command to my Yamaha RX-V775 receiver:
`20:23:29.564 [WARN ] [internal.profiles.ProfileCallbackImpl] - Cannot delegate command 'ON' for item 'Yamaha_Mute' to handler for channel 'yamahareceiver:zone:5f9ec1b3_ed59_1900_4530_00a0dea23248:Main_Zone:zone_channels#mute', because no handler is assigned. Maybe the binding is not installed or not propertly initialized.
20:23:29.571 [WARN ] [internal.profiles.ProfileCallbackImpl] - Cannot delegate update 'ON' for item 'Yamaha_Mute' to handler for channel 'yamahareceiver:zone:5f9ec1b3_ed59_1900_4530_00a0dea23248:Main_Zone:zone_channels#mute', because no handler is assigned. Maybe the binding is not installed or not propertly initialized.`

But otherwise all items receiving correct updates from the Yamaha device.
.item:
`Switch Yamaha_Mute "YamahaMute" <soundvolume_mute> (gYamaha, gAudio) {channel="yamahareceiver:zone:5f9ec1b3_ed59_1900_4530_00a0dea23248:Main_Zone:zone_channels#mute"}`
.sitemap:
`Switch item=Yamaha_Mute label="AV Mute"`

Furthermore i figured out that if i resave my yamaha.item file without changing the content, the model gets refreshed.
After this, commands are successfully transmitted, until the yamaha things (Main_Zone and Zone_2) getting updated by the 60s interval. This is the log:
`20:22:32.810 [INFO ] [del.core.internal.ModelRepositoryImpl] - Refreshing model 'yamaha.items'
20:22:40.482 [INFO ] [smarthome.event.ItemCommandEvent     ] - Item 'Yamaha_Mute' received command ON
20:22:40.494 [INFO ] [smarthome.event.ItemStateChangedEvent] - Yamaha_Mute changed from OFF to ON
20:23:26.576 [INFO ] [smarthome.event.ThingUpdatedEvent    ] - Thing 'yamahareceiver:zone:5f9ec1b3_ed59_1900_4530_00a0dea23248:Main_Zone' has been updated.
20:23:26.609 [INFO ] [smarthome.event.ThingUpdatedEvent    ] - Thing 'yamahareceiver:zone:5f9ec1b3_ed59_1900_4530_00a0dea23248:Zone_2' has been updated.
20:23:29.558 [INFO ] [smarthome.event.ItemCommandEvent     ] - Item 'Yamaha_Mute' received command ON
20:23:29.564 [WARN ] [internal.profiles.ProfileCallbackImpl] - Cannot delegate command 'ON' for item 'Yamaha_Mute' to handler for channel 'yamahareceiver:zone:5f9ec1b3_ed59_1900_4530_00a0dea23248:Main_Zone:zone_channels#mute', because no handler is assigned. Maybe the binding is not installed or not propertly initialized.
20:23:29.571 [WARN ] [internal.profiles.ProfileCallbackImpl] - Cannot delegate update 'ON' for item 'Yamaha_Mute' to handler for channel 'yamahareceiver:zone:5f9ec1b3_ed59_1900_4530_00a0dea23248:Main_Zone:zone_channels#mute', because no handler is assigned. Maybe the binding is not installed or not propertly initialized.
20:23:29.573 [INFO ] [smarthome.event.ItemStateChangedEvent] - Yamaha_Mute changed from OFF to ON`

**Comment by wborn** [comment]
The root cause of this issue could also be https://github.com/eclipse/smarthome/issues/4622.

**Comment by d3rh3ld** [comment]
Seems like this... 
Can you tell me how long it takes until the Commit 3dce300 is available in the snapshots?

**Comment by kaikreuzer** [comment]
Will do a new ESH stable release tonight.

**Comment by kaikreuzer** [comment]
Done - latest distro 1096 should have this fixed.
