### ISSUE TITLE
[homekit] Thermostat mode logging fix 

### ISSUE THREAD

**Issue by HentschelT** [openhab/openhab2-addons#2874]
Currently, the homekit addon shows hardcoded expected strings in the log entry if a mode request isn't parseable. This disagrees with what the 'mode' parser is actually looking for, which is somewhat confusing when debugging adapting a new thermostat.

The attached patch/diff fixes that (it's pretty much a one-liner)

OpenHAB 2.2- , build 1087 on openhabian

Cheers,
-Th

https://gist.github.com/HentschelT/38fc5536b7c19b75ca05e4f0af9d1754#file-openhab2-homekit-thermo-mode-logging-diff

**Comment by J-N-K** [comment]
Fixed in master
