### ISSUE TITLE
[Tradfri] Things going offline are not detected

### ISSUE THREAD

**Issue by StrikerTwo** [openhab/openhab2-addons#2885]
I have several Tradfri bulbs connected to a Tradfri gateway and OpenHAB. Problem is that if they are switched off with the wall switch, OpenHAB still thinks they are switched on.
The Tradfri app shows them as offline pretty much instantly, so obviously the gateway knows about it. 

## Expected Behavior
Offline things should fire offline triggers. I don't expect real time updates, somewhere around 1-5 minutes would be quite enough.

## Current Behavior
No offline events are shown in the log. Only when I try to send commands to the connected items the offline event is eventually fired.
Likewise when they are switched on again: no online events for the thing or command events for the items show in the log.

## Possible Solution
Maybe have the binding check periodically for the thing status instead of relying on receveiving events?

## Context
I want to change the bulb brightness depending on time of day. If the bulb is switched off at the wall switch, it won't get updates about the current target brightness. And if I don't get any event when the bulb is switched on again at the wall switch, I can't even set the correct brightness at that moment.

## Your Environment
OpenHAB 2.1 on Windows 2012
Latest(?) Tradfri binding
Latest Tradfri firmware according to app

**Comment by kaikreuzer** [comment]
Please note that the Tradfri binding is maintained at https://github.com/eclipse/smarthome and that a lot of fixes have been done since the version that is included in openHAB 2.1.

Please test on a recent 2.2 snapshot and if you still encounter issues there, report them at https://github.com/eclipse/smarthome/issues. Thanks!
