### ISSUE TITLE
[homekit] Automation limited over the HomeKit App

### ISSUE THREAD

**Issue by semaf** [openhab/openhab2-addons#2890]
I just recognized that I have only 1 option of automation over the Homekit App. I have an Apple TV 4 too at home. Is the HomeKit Binding or the Apple TV 4 the reason?

![img_0758](https://user-images.githubusercontent.com/8831145/33256924-7eac797c-d354-11e7-874a-9546ed5086a8.jpg)

**Comment by extric99** [comment]
Can you try using an ipad as hub for the automation if you have one available. For me this works fine.

**Comment by J-N-K** [comment]
Since other users report it's working and no further response was received. I'll close here. Please open a new issue if it still persists.
