### ISSUE TITLE
[milight] Milight floods the inbox

### ISSUE THREAD

**Issue by sjka** [openhab/openhab2-addons#2918]
Every milight bridge deliberately floods the inbox with things of all _possible_ thing types, not only those which _really_ exist (see [README.md](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.milight/README.md)). I understand that the protocol doesn't support any proper discovery for its things. Then, however, the binding should also not support it instead of doing this.

**Comment by sjka** [comment]
@davidgraeff as the author of this binding, could you please take care of this?

**Comment by davidgraeff** [comment]
@sjka I implemented this on purpose. I have to admit, that at that time there existed lesser types of bulbs. So yes, it might be time now to remove the things from discovery.
