### ISSUE TITLE
[onkyo] Add support for TX-NR545

### ISSUE THREAD

**Issue by KidSquid1** [openhab/openhab2-addons#2922]
Please add support for the Onkyo TX-NR545 AVR

The model is currently a step in between two currently supported models.

**Comment by paulianttila** [comment]
Meanwhile, you can setup your receiver manually to be TX-NR535 or TX-NR555. It should work fine as from binding point of view there is no difference between 535 and 555 either.

**Comment by KidSquid1** [comment]
Any idea on why the log is flooded with this ERROR message every minute?  I can ping the unit fine, in fact I have kept the ping going for 5 minutes and while the ping never drops, the connection still shows an error message every minute.  I am still using the unsupported version of the thing...could this be an issue as all of the channels work as they should.

`2017-12-07 00:36:09.735 [ERROR] [nding.onkyo.internal.OnkyoConnection] - Can't connect: connect timed out
2017-12-07 00:37:09.735 [ERROR] [nding.onkyo.internal.OnkyoConnection] - Can't connect: connect timed out`

**Comment by sirLeone** [comment]
It would be great to add officiall support for TX-NR545 - maybe autodiscovery would start to wrok

**Comment by Cossey** [comment]
@KidSquid1 and @sirLeone I can look into adding this for you two (I have recently just added support for my receiver) but I will need the following from you:

* confirmation from you that this receiver supports `Zone 2`
* test the `albumArt` channel with the currently available add-on and see if it correctly displays the album art on Paper UI (this is in regards to push request 4502, just wanting to get a consensus of other models that suffer from this issue) _you will need to play something over the NET input that displays album art (ie: AirPlay or Spotify Connect)_
* test the add on that I will build and link to, to make sure it works and detects the receiver correctly _(you will need to know how to do this but this is explained in the openHab docs)_

I don't believe adding support for the receiver using the typical method will affect how auto-discovery works, have you ruled out network issues? It also might be a receiver issue as I've read online at a few places that some of the older models were a bit unstable in their handing of some of the network functionality, if you can, try updating the firmware to see if that helps.

**Comment by KidSquid1** [comment]
@Cossey 

Thanks for looking in to this....

I can confirm that the receiver does support a 2nd Powered Zone

![image](https://user-images.githubusercontent.com/28264840/50678340-cfbfbe80-0fc3-11e9-8096-62001c822d68.png)

I am away from the receiver for the next week or so and regrettably can not test the AlbumArt feature as requested.

I will be happy to test the new version when available.

Currently I am using the unsupported receiver and have disabled logging as to suppress the errors which I mentioned above.  Network health is not an issue - the receiver has always been available via IP address and was pingable even when the binding claims it was unavailable.

Squid

**Comment by sirLeone** [comment]
I also confirm that zone 2 is supported by the receiver. AlbumArt i will test in hours and let you know.

**Comment by sirLeone** [comment]
@Cossey I have just checked your version, sorry for doing it so late but have A LOT of work :(
I can say that my TX-NR545 is properly discovered by paperUI and after changing channel definition in my .item file all is working OK as before. 
Thanks a lot !

**Comment by dabbith** [comment]
Is there any chance support for the HT-RC560 could be added as well?  It's the North American name for the TX-NR626.

**Comment by cweitkamp** [comment]
@Cossey Will you come up with a PR for the support of the TX-NR545 model?

**Comment by Cossey** [comment]
@cweitkamp Yes I will sort this out and submit a push request. Ill add another Thing for the HT-RC560 too.

**Comment by cweitkamp** [comment]
@Cossey :+1: Very much appreciated.

> Ill add another Thing for the HT-RC560 too.

Great if that will work too.

**Comment by Cossey** [comment]
No problem; I will sort this out this weekend when I have a spare moment.

**Comment by Cossey** [comment]
@dabbith Please try this Binding to see if you can auto-discover your Receiver: https://www.dropbox.com/s/dz5uvqp5k5w6m3m/org.openhab.binding.onkyo-2.5.0-SNAPSHOT-htrc560.jar?dl=0

You'll need to remove the existing Onkyo binding and Things if they already exist, then shift this Binding into the add-on folders. Refer to the documentation for more details if required.

**Comment by Cossey** [comment]
@cweitkamp added pull request for the TX-NR545, however the CI build failed for some reason - since I don't know how to force it to re-run so I'll leave it to you.

I've created a new Thing for the HT-RC560 that @dabbith requested here and once he confirms this works I'll open another Pull Request with this Issue as reference. Cheers Christoph.

**Comment by cweitkamp** [comment]
@Cossey Thanks. As long as the Travis build is green we are good to merge. :+1:

**Comment by dabbith** [comment]
@Cossey Got a chance to test.  First had to install the upnp package (feature:install esh-io-transport-upnp).  Now it looks like the binding is loading, but the receiver is not being discovered.  I can manually add the receiver and it works properly.  With the release binding, the receiver was discovered but unknown.

How can I enable logging for the upnp discovery?

**Comment by Cossey** [comment]
Hi @dabbith,

I may have to make a specific mod to the Binding for your case so that we can get the name of the device being sent through UPNP. I assume you've set the onkyo binding to `TRACE` level logging. If not, try setting to that and doing a scan and add to see if it logs out the UPNP packet. 

I don't have much free time at present but if setting the log level doesn't help when I get a moment Ill make tweak to the Binding so that it logs out the particular field it uses for the identifying the correct receiver.

**Comment by dabbith** [comment]
@Cossey I must have been doing something wrong.  I updated the logging and restarted and now I see my HT-RC560.  So everything looks good.  Thanks!

**Comment by Cossey** [comment]
Hey @dabbith,
Just to clarify, it did auto-detect your model successfully? If so Ill get this merged into openHAB.

Thanks!

**Comment by dabbith** [comment]
@Cossey, 
Yes, it was correctly auto-detected and when added works perfectly.  Looks like it should be good to merge. Thanks so much!

**Comment by sirLeone** [comment]
Hi
@Cossey 
After upgrade to OH2.5.1-2 i have removed your binding file (from 4 Jan 2019) and installed 2.5.1 version from PaperUI but unfortunately it says that TX-NR545 is not supported (it WAS discovered in PaperUI) 

TX-NR545 ONLINE
Unsupported Onkyo AV Receiver
onkyo:onkyoUnsupported:2db09476-af94-76b9-449d-7609afb9a61f
