### ISSUE TITLE
[onkyo] Readme - Improve callback url description

### ISSUE THREAD

**Issue by Confectrician** [openhab/openhab2-addons#2925]
Hi together,

I have updated the bindings readme recently in #2860.
This was intended from a docs-repo issue: openhab/openhab-docs#462

From the original discussion, there is one point still unaddressed:
> In the bindings configuration section there is a reference to a parameter for a CallBack URL. Generally I know what a callback URL in web development is, but the documentation is vague on what functionality the Callback URL provides and what URL should be plugged in here. Is it the URL of the Openhab install? Is it the URL of the Onkyo receiver? What the heck is it supposed to do?

I was not able to improve this in a useful way, because i just improved the readme and don't own an onkyo device to clarify what this configuration parameter does.

Maybe this issue can help to clarify the behaviour of the binding and what this parameter affects.
I can do a possible PR myself, when i know what has to be explained, but for me its also ok if someone else with the specific knowledge opens a PR. 😃

**Comment by martinvw** [comment]
Lets mention @marcelrv and @pail23 again :-)

**Comment by marcelrv** [comment]
I'm also not fully aware of what this is doing.
I've always been surprised that this is a configuration on the binding level (rather than on the thing level)

**Comment by martinvw** [comment]
Thanks, then it's all hope on @pail23 😉

**Comment by Cossey** [comment]
Looking at the source code, I can see the callbackUrl is used in `OnkyoHandlerFactory.java; lines 60-106`. It appears to be used for the UPnP Audio Sink service and gets set to the IP address and Port of the openHab web server when it is `null`. 

In `UpnpAudioSinkHandler.java; line 168` it looks like it is used to serve the audio stream to the receiver from openHAB:
```
    public void process(AudioStream audioStream)
            throws UnsupportedAudioFormatException, UnsupportedAudioStreamException {
        String url = null;
        if (audioStream instanceof URLAudioStream) {
            // it is an external URL, the speaker can access it itself and play it.
            URLAudioStream urlAudioStream = (URLAudioStream) audioStream;
            url = urlAudioStream.getURL();
        } else {
            if (callbackUrl != null) {
                String relativeUrl;
                if (audioStream instanceof FixedLengthAudioStream) {
                    // we serve it on our own HTTP server
                    relativeUrl = audioHTTPServer.serve((FixedLengthAudioStream) audioStream, 20);
                } else {
                    relativeUrl = audioHTTPServer.serve(audioStream);
                }
                url = callbackUrl + relativeUrl;
            } else {
                logger.warn("We do not have any callback url, so onkyo cannot play the audio stream!");
                return;
            }
        }
        playMedia(url);
    }
```
I don't really know anything about the audio sinks but I think that's what the code seems to be doing above.

**Comment by cweitkamp** [comment]
We have similar issues for e.g. the Chromecast binding. Have a look into #1984 or #3867 for more information why bindings implement the callback url.

**Comment by cweitkamp** [comment]
@Confectrician Should we think about porting the explanation used in #3867 for the Onkyo binding now to get rid of this issue? Does that make sense? Or do you think we should mention it in a more general way e.g. in the openHAB documentation itself?
