### ISSUE TITLE
 Paper UI: Items stacked in Control tabs 

### ISSUE THREAD

**Issue by jangrewe** [openhab/openhab2-addons#2970]
On the Control page, all Items in any location tab except the first one are stacked and can not really be used anymore.
There is also no sliding animation when switching tabs.

It looked fine with v2.1, but i thought going to 2.2 would be reasonably safe, considering the late stage of development

## Expected Behavior
I was expecting the Things/Items to be placed next to each other.

## Current Behavior
The tab for any location other than the very first stacks all Things on top of each other.

## Steps to Reproduce (for Bugs)
1. install openHABian
2. use `openhabian-config` to switch to the current snapshot
3. put separate things into separate locations with `@ "somewhere"`

## Your Environment
* Version used: 2.2.0~20171216031002-1 (openHABian)
* Environment name and version: current Firefox and Chrome
* Operating System and version: Windows 10

![Screenshot](https://screenshots.firefoxusercontent.com/images/011166be-2c2b-4465-8107-147839ca807a.png)

**Comment by kubawolanin** [comment]
I would advice to submit this issue on https://github.com/eclipse/smarthome/issues as the development of Paper UI is going on there.
This one should be closeed.

Cheers!

**Comment by jangrewe** [comment]
Thanks for the hint, i opened an issue there, and in the mean time also discovered the reason: my window size seems to be too big for the JS to handle (4K may not be the default, but it's definitely a standard).

https://github.com/eclipse/smarthome/issues/4759
