### ISSUE TITLE
[homekit] Can't change saturation of Color item

### ISSUE THREAD

**Issue by Pickowicko** [openhab/openhab2-addons#2974]
I added some hue lights to my openhab system today, however when I control them though the home app or Siri I can control brightness and hue but not saturation. This means I cannot set the Color white in the home app. When I am in paperUi though I can change all three settings successfully. 

When I am trying to change the color on the Color wheel in the home app I select a Color and then the Color indicator glitches to the radius that is the saturation I have set in paperUi.  

Tdlr: I cannot change saturation from homkit. Only hue and brightness

Config files:

//Items File

Switch Demo_Switch “Demo Switch” [“Switchable”]
Color Demo_Light “Demo Light” [“Lighting”]

//Sitemap File

sitemap home label=“Home”
{
Frame label=“Demo”
{
Switch item=Demo_Switch
Colorpicker item=Demo_Light
}
}

**Comment by fenderle** [comment]
This is issue is open forever and the problem still persists

**Comment by J-N-K** [comment]
Please check if this is still the case with 2.5 Snapshot>1601

**Comment by fenderle** [comment]
Sorry I don’t use OpenHAB anymore...
