### ISSUE TITLE
[tinkerforge] new humidity 2.0 bricklet use

### ISSUE THREAD

**Issue by KenPTex** [openhab/openhab2-addons#2977]
I have a tinkerforge master brick and a temperature, barometer, and ambient light 2.0 bricklet in my openhab2 installation.  They all work fine.   My openhab installation is on a RPi using the standard openhabian installation.  Tinkerforge apparently discontinued the humidity bricklet and now sells a humidity 2.0 bricklet, which I have.  

I hooked it up and tried to configure it as a humidity bricklet, but it didn't work.  no response and no entries in the log file pertaining to that bricklet (set on info).   I assume that the Tinkerforge binding needs to be updated to handle the new 2.0 humidity bricklet to access it.

I'd like to see that update happen, but if anyone knows of a workaround they can point me to I would appreciate it.  

It appears to me that the bricklets can be used with Modbus, but I have absolutely no experience with Modbus or with the openhab modbus binding.  I couldn't find any examples of how to do that when I searched but if someone can point me that way I'd appreciate that too.

**Comment by wborn** [comment]
The Tinkerforge binding is part of the openhab1-addons project. See also https://github.com/openhab/openhab1-addons/issues/5392 which is about adding support for the new 2.0 humidity bricklet in the Tinkerforge binding.
