### ISSUE TITLE
[Hue binding] Osram Lightify Plug detected but not controllable

### ISSUE THREAD

**Issue by cee-dee** [openhab/openhab2-addons#2985]
## Expected Behavior
According to http://docs.openhab.org/addons/bindings/hue/readme.html the "On/Off Plug-in Unit" should be supported. 

## Current Behavior
The plug is detected, I can add it as a thing, but it is not offered for controlling in the Control menu. When accessing it via Configuration -> Things a click on the blue button yields an "Internal Server Error (500)".

The log files in /var/log/openhab2 don't list anything on this action.

## Possible Solution
?

## Steps to Reproduce (for Bugs)
0. Pair Lightify Plug with Hue Brdige.
1. Add hue binding.
2. Add Hue as thing.
3. Pair bridge.
4. Look under Control panel -> no plug found
5. Go to Control -> Things -> Plug and try to activate it

## Context
I want to switch on/off some non-hue things like legagcy led lighting in furniture or air conditioning devices.

## Your Environment
* Hardware: Osram Lightify Plug, Current firmware version: V1.04.12
* binding-hue - 2.1.0
* current stable openhab2
* Ubuntu 14.04.01, 64 bit
* OpenJDK Runtime Environment (build 1.8.0_141-8u141-b15-3~14.04-b15)
* OpenJDK 64-Bit Server VM (build 25.141-b15, mixed mode)

**Comment by hmerk** [comment]
First issue I see is that you use OpenJDK, which is not recommended. Please install OracleJDK and try again.
If you still see problems, please open a new issue at https://github.com/eclipse/smarthome, as the HUE Binding is an ESH Binding, not an openHAB Binding.

I would suggest to close this issue here.

**Comment by cee-dee** [comment]
Ok, I will try the OracleJDK and perhaps open a new issue at Eclipse SmartHome. Thank you!

**Comment by cee-dee** [comment]
For the record: it did not help to use:
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

**Comment by dominicdesu** [comment]
@cee-dee what is the ticket number in the ESH tracker?
