### ISSUE TITLE
[Squeezebox] Cover Art Data Has Wrong Data Type.

### ISSUE THREAD

**Issue by kungfoolfighting** [openhab/openhab2-addons#2989]
## Expected Behavior
The cover art should be displayed in HabPanel.

## Current Behavior
When trying to display the squeezebox cover art in HabPanel the image is not displayed.

## Possible Solution
The reason is very likely that the media type of the cover art is not properly set.
It is set to 'application/octet-stream' rather than something like 'image/jpeg'.
This leads HabPanel to mark the data with 'unsafe:' since this media type is not whitelisted for images.
Setting the appropriate media type in the logitech squeezebox binding would solve this problem.

This problem was discussed here: https://community.openhab.org/t/displaying-raw-image-in-habpanel/37300/8

## Steps to Reproduce (for Bugs)
- Be on OH 2.2 Snapshot
- Bind cover art channel to OpenHAB image item.
- Try to display image item in HabPanel with standard image widget.
- Observe that image is not shown.

## Context
I am trying to get cover art from squeezebox to display in HabPanel.

## Your Environment
- OH 2.2 Snapshot on X86 Linux server.

**Comment by lolodomo** [comment]
The ESH framework is providing an util method to download images amd setting the media type as expected.

**Comment by cweitkamp** [comment]
PR #3035
