### ISSUE TITLE
[homematic] Lots of warning messages "Channel not found for datapoint 'BidCoS-RF:1#PRESS'" after OH 2.2 upgrade 

### ISSUE THREAD

**Issue by robbyb67** [openhab/openhab2-addons#3010]
After upgrade to OH 2.2 I find lots of the above warning messages in the log.

The curious thing is that a Channel reference

BidCoS-RF:1#PRESS

is nowhere to find in any item nor any jsondb file.

How can I get rid of this ?

**Comment by martinvw** [comment]
@gerrieg ?

**Comment by gerrieg** [comment]
BidCoS-RF:1#PRESS is a new trigger channel in the 2.2 binding. Try to delete and re-add the thing(s) again.

**Comment by robbyb67** [comment]
Which thing(s) are the cause? Is it only the bridge (CCU2) or each and every Homematic device ?
If it's the latter then we need a mechanism for migration if the future - at least such things have to be mentioned in the release notes.

**Comment by gerrieg** [comment]
each thing that has a PRESS_SHORT and/or PRESS_LONG channel has now a PRESS trigger channel to.

@martinvw 
When a thing gets more channels, e.g firmware update or in this case a virtual channel from the binding, can i do something from the binding that the things in OH are updated? Or is this something the framework must handle?

**Comment by kaikreuzer** [comment]
@gerrieg With the PRESS trigger channel in place now, would it be time to deprecate the PRESS_SHORT/PRESS_LONG (state) channels? It otherwise seems to be pretty confusing for users.

Regarding the warning that this issue is about: The binding should always expect things that do not have all channels available and must not log warnings in such a case.

**Comment by gerrieg** [comment]
> would it be time to deprecate the PRESS_SHORT/PRESS_LONG (state) channels?

yes, will deprecate them

> ... and must not log warnings in such a case

OK, thanks for the info, will reduce the log level to trace

**Comment by robbyb67** [comment]
Does that mean that it will be no longer possible to use different rules for the LONG/SHORT triggers ?

**Comment by gerrieg** [comment]
sure, see the example in the [docs](http://docs.openhab.org/addons/bindings/homematic/readme.html), search for trigger rule

**Comment by robbyb67** [comment]
Ahh - I see. So I have a hobby ...
For future releases: PLEASE mention such changes in the release notes.
