### ISSUE TITLE
[Milight] ledwhitemode doesn't work anymore

### ISSUE THREAD

**Issue by martin393** [openhab/openhab2-addons#3021]
After updating to version 2.2.0 it isn't possible to activate the whitemode of my milights and the ibox anymore.

When i call the command "milight_zone1_ledwhitemode.sendCommand(ON)" in my rules i can see this in the event log "Item 'milight_zone1_ledwhitemode' received command ON", but it doesn't take effect.

**Comment by it2semi** [comment]
Same problem here... with Milight RGBW and RGBWW LEDs and iBox2.

**Comment by martinvw** [comment]
@davidgraeff can you take a look / assist here?

**Comment by davidgraeff** [comment]
It's because the channels whitemode,nightmode are defined as trigger channels. That's just wrong. 

But until I have an answer on the issue on the eclipse smartphone issue tracker, I don't know how to implement this correctly. 

The problem: I need a pushbutton like channel type and that's not yet existing.

**Comment by kaikreuzer** [comment]
> But until I have an answer on the issue 

For traceability reasons, it would be nice if you could directly link to it.

> the eclipse smartphone issue tracker

🤣

**Comment by it2semi** [comment]
thanks for you answer. is there any workaround for this problem?

**Comment by MikeJMajor** [comment]
There's the same issue with disco mode which works in OH 2.1, but not in OH 2.2.

So there may well be a problem with how the channels are defined, but the behaviour of the trigger channel looks to have changed in OH 2.2 since the channel definition in the binding hasn't changed.

**Comment by MikeJMajor** [comment]
@davidgraeff Why can't we change the types to switch for nightmode and whitemode and dimmer for the animation modes? That should be enough to get it working again and will match the examples in the readme

**Comment by ducker2** [comment]
Alas, I missed this one and I've opened #3028. Sounds like both issues are related, if not the same. I really miss the power saving nightmode, so it would be really great to have it fixed again.

**Comment by MikeJMajor** [comment]
PR #3093

**Comment by markus7811** [comment]
Same issue here. LEDWhiteMode worked with 2.1.0.ref-rc11.jar (last working version for me) ... now with the 2.2 version it does not work anymore.

Apart from that i get the following error every start of openhabe2:

Feb 04 16:55:47 OpenHab2 karaf[13492]: Exception in thread "SessionThread" java.lang.IllegalArgumentException: Port out of range:-1
Feb 04 16:55:47 OpenHab2 karaf[13492]:         at java.net.DatagramPacket.setPort(DatagramPacket.java:295)
Feb 04 16:55:47 OpenHab2 karaf[13492]:         at org.openhab.binding.milight.internal.protocol.MilightV6SessionManager.send_search_for_broadcast(MilightV6SessionManager.java
Feb 04 16:55:47 OpenHab2 karaf[13492]:         at org.openhab.binding.milight.internal.protocol.MilightV6SessionManager.session_handshake_process(MilightV6SessionManager.java
Feb 04 16:55:47 OpenHab2 karaf[13492]:         at org.openhab.binding.milight.internal.protocol.MilightV6SessionManager.run(MilightV6SessionManager.java:435)
Feb 04 16:55:47 OpenHab2 karaf[13492]:         at java.lang.Thread.run(Thread.java:748)

**Comment by davidgraeff** [comment]
@martinvw Can be closed

**Comment by martinvw** [comment]
Thanks for mentioning
