### ISSUE TITLE
[homematic] HM-CC-RT-DN Temperature Offset not working

### ISSUE THREAD

**Issue by Nugman** [openhab/openhab2-addons#3026]
## Expected Behavior
When saving the Thing configuration of a HM-CC-RT-DN heating valve, I expect that the values are saved to the device.

## Current Behavior
When trying to configure the Temperature Offset, the configuration shows -3.5K, no matter what value I have selected.

## Steps to Reproduce (for Bugs)
1. Edit HM-CC-RT-DN Thing in PaperUI
2. Set "Temperature Offset" to e.g. 1.0K
3. Save the Thing configuration
4. Check the configuration by entering the Thing Editor again
5. "Temperature Offset" reads "-3,5K"

When I use the Homegear RPC server with the HomeMatic Configuration Software provided by EQ3, I'm able to configure the Temperature Offset properly. So I assume the error is in the OpenHab Binding and not in Homegear.

## Context
I tried to configure my heating valves, so that the temperatures it measures match the real temperature of the room. Usually the temperatures directly at the radiator are a little warmer than the rest of the room, so in order to reach the desired temperature an offset is necessary.

## Your Environment
* OpenHab 2.2.0 release, Homematic Binding 2.2.0
* Homegear  0.7.12-1492
* Firefox 57.0.2 (Win10)
* Raspbian Jessie (OpenHabian 1.3 with updated OpenHab)

**Comment by MHerbst** [comment]
I have tried to reproduce it but I have got a CCU and in this case I don't see this property in the thing configuration.

Can you enable Debug mode for the Homematic binding and attach the output? Mabe the problem has to do with "," and ".". In the CCU all decimal values are shown with decimal points. "-3.5" is the smallest allowed value.

**Comment by Nugman** [comment]
Thanks for the quick response. I activated the DEBUG log for org.openhab.binding.homematic, but the log shows nothing suspicious:

`2017-12-25 14:15:36.723 [DEBUG] [ommunicator.AbstractHomematicGateway] - Sending datapoint 'OEQ0240018:M_0#TEMPERATURE_OFFSET' with value '1.5K' to gateway with id 'f85
68d2b'
2017-12-25 14:15:36.733 [DEBUG] [ommunicator.AbstractHomematicGateway] - Received new (Boolean) value 'true' for 'OEQ0240018:0#CONFIG_PENDING' from gateway with id 'f85
68d2b'
[..]
2017-12-25 14:22:33.704 [DEBUG] [ommunicator.AbstractHomematicGateway] - Sending datapoint 'OEQ0240018:M_0#TEMPERATURE_OFFSET' with value '0.0K' to gateway with id 'f8568d2b'
2017-12-25 14:22:33.715 [DEBUG] [ommunicator.AbstractHomematicGateway] - Received new (Boolean) value 'true' for 'OEQ0240018:0#CONFIG_PENDING' from gateway with id 'f8568d2b'`

After each try the offset was set to -3.5K in the Thing configuration.
Anything special I should look for in the logs?

**Comment by Nugman** [comment]
Since changing the settings work using the Homematic Configuration Software from EQ3 via Homegear, I activated the DEBUG logs für Homegear and found something:

This is the log output when I try to set the TEMPERATURE_OFFSET to 1.0K using OpenHAB:
`12/25/17 14:40:39.683 Module HomeMatic BidCoS: Info: Parameter TEMPERATURE_OFFSET of peer 5 and channel 0 was set to 0x00.
12/25/17 14:40:39.684 Module HomeMatic BidCoS: HM-MOD-RPI-PCB "My-HM-MOD-RPI-PCB": Info: Sending (My-HM-MOD-RPI-PCB): 10C9A001FDC24656844600050000000000
12/25/17 14:40:40.674 Module HomeMatic BidCoS: HM-MOD-RPI-PCB "My-HM-MOD-RPI-PCB": Info: No answer to packet 10C9A001FDC24656844600050000000000`

This is the log output when I do the same in the EQ3 software:
`12/25/17 14:41:07.203 Module HomeMatic BidCoS: Info: Parameter TEMPERATURE_OFFSET of peer 5 and channel 0 was set to 0x09.`

So it seems, that OpenHAB is sending a 0x00 when the Homematic Configurator sends a 0x09. Is that something you can work with?

**Comment by MHerbst** [comment]
It seems that the OFFSET sent to Homegeara a special encoding. If an offset of +1 K is sent as 0x09 then 0K is probably encoded 0x08 and 0x00 means -3.5 K (which is the smallest possible value).

@gerrieg can you look at it?

**Comment by Nugman** [comment]
I checked the different settings in the logfile of homegear and found that the mappings for TEMPERATURE_OFFSET are as follows:
-3,5K = 0x00
-3,0K = 0x01
-2,5K = 0x02
-2,0K = 0x03
-1,5K = 0x04
-1,0K = 0x05
-0,5K = 0x06
0,0K = 0x07
0,5K = 0x08
1,0K = 0x09
1,5K = 0x0A
2,0K = 0x0B
2,5K = 0x0C
3,0K = 0x0D
3,5K = 0x0E

**Comment by gerrieg** [comment]
This is a very special case. Thank you @Nugman for providing the mapping table. This is very useful, we can implement it in one of the 2.4 snapshots.

**Comment by mdicke2s** [comment]
This issue was moved to eclipse/smarthome#5788
