### ISSUE TITLE
[milight] night mode not working with two channel CCT controller and V3 bridge

### ISSUE THREAD

**Issue by ducker2** [openhab/openhab2-addons#3028]
In general the milight addon works great! The only thing that does not work ist the nightmode
on CCT controllers (e.g. https://www.amazon.de/dp/B01I9PBIH6/ref=cm_sw_em_r_mt_dp_U_m7mqAbXFKRMGP) linked to a bridge V3.

Seems like switching nightmode on or off command is ignored. I am sure it did work in the past
(some version ~ 1.6) but not after migration to openhab 2 and the corresponding milight addon. 

Using the milight remote controll, nightmode can be activated manually by long press of "0"
(off). So hardware should be OK.

I am currently running openhab 2.2 and milight addon 2.2 on a debian host.

**Comment by MikeJMajor** [comment]
This might be fixed by #3093

[org.openhab.binding.milight-2.3.0-SNAPSHOT.jar](https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/org.openhab.binding.milight/2.3.0-SNAPSHOT/org.openhab.binding.milight-2.3.0-SNAPSHOT.jar)

**Comment by ducker2** [comment]
I just updated the installed addon to org.openhab.binding.milight-2.3.0-SNAPSHOT.jar, but no change regarding the not working night mode.

**Comment by MikeJMajor** [comment]
What do you have the night model channel defined as? There was an error in the readme example which was using "nightmode" rather than "lednightmode"

Did you uninstall the 2.2 version from paperui before putting the 2.3 version in the addons folder?

**Comment by ducker2** [comment]
Item channels are defined using lednighmode, e.g. milight:whiteLed:ACCFxyxyxyxyx:0:lednightmode

I upgraded the packages (Debian) using this apt repository:
deb https://openhab.jfrog.io/openhab/openhab-linuxpkg unstable main

After the upgrade openhab did not start. So I reinstalled (apt remove and then apt install) openhab2 and openhab2-addons package and can start the application again.

Then I've checked installed version using paper UI, it says: binding-milight - 2.3.0.SNAPSHOT

**Comment by MikeJMajor** [comment]
Sorry the URL no longer had my changes in by the time you downloaded it. I'll let you know when it's merged so you can test again.

**Comment by MikeJMajor** [comment]
The PR was merged today.

**Comment by ducker2** [comment]
Thanks for your support so far!
Just a short update: No change after upgrade to openhab-addons version "2.3.0~20180121033551-1" using apt source "https://openhab.jfrog.io/openhab/openhab-linuxpkg unstable main", nightmode is still not working.

**Comment by ducker2** [comment]
Hi davidgraeff, nightmode is actually available again! The channel '...:lednightmode' only supports to go into nightmode; sending OFF command to this channel has no effect. To turn off lights when nightmode is activated, you have to send ON command to channel '...:ledbrightness'. This makes sense as it reflects the original push button logic from milight, maybe a hint in the documentation might help others. But the binding is fully working as expected now, including nightmode. Thanks!

**Comment by davidgraeff** [comment]
Yeah like in the app. Night mode can only be enabled by the push button. I changed it to be a stateless trigger channel for that reason, but paperui doesn't support trigger channels, so someone changed it back to be a switch.

@martinvw Can be closed :)
