### ISSUE TITLE
[sonos] clearqueue channel doesn't work

### ISSUE THREAD

**Issue by Dan1001** [openhab/openhab2-addons#3029]
Hi,

The clearqueue channel doesn't seem to work at all on the Sonos binding.

If I create a queue on a Sonos devices, then all other of the openHAB channels work perfectly on that device, but clearqueue does nothing. There are no log entries.

thank you!

Dan

**Comment by cweitkamp** [comment]
Please note that the Sonos binding is maintained at https://github.com/eclipse/smarthome. If you encounter issues, report them at https://github.com/eclipse/smarthome/issues. Thanks!

**Comment by Dan1001** [comment]
thanks - will do!
