### ISSUE TITLE
Netatmo UTC Time instead Local Time

### ISSUE THREAD

**Issue by michaeljoos72** [openhab/openhab2-addons#3032]
It seems that all timestamps (e.g. last measurement, last upload, min/max-values) are in UTC-Time now. Personally I didn't see this in previous versions. Updated 2 days ago to latest snapshot openHAB 2.3.0 Build #1151.

openHABianPi 7.05.170509 (latest version)
Release = Raspbian GNU/Linux 8 (jessie)
Kernel = Linux 4.9.35-v7+
Platform = Raspberry Pi 3 Model B Rev 1.2

Raspi-Time seems to be OK:
[08:50:49] openhabian@openHABianPi: date
Wed Dec 27 08:51:32 CET 2017
[08:51:32] openhabian@openHABianPi: date --utc
Wed Dec 27 07:51:55 UTC 2017

And also all other dates and timestamps are OK in openHAB

**Comment by cweitkamp** [comment]
Confirmed. See also https://github.com/openhab/openhab2-addons/issues/2988#issuecomment-353732377.

**Comment by cweitkamp** [comment]
PR #3073
