### ISSUE TITLE
Add Backup Service IO

### ISSUE THREAD

**Issue by caffineehacker** [openhab/openhab2-addons#3047]
In OpenHAB 1.x we had a dropbox IO addon that backed up our settings. I'd propose adding a new backup IO addon (possibly one that supports multiple services like Google Drive, Dropbox, copying to another location, github, etc...). I'm willing to do the work on this, but no promises on timeline.

Would creating a new IO addon be the correct way to do this in OpenHAB 2.x?
Would it be preferred to have one addon for multiple services or just create one addon per service (possibly with some shared code as applicable)?
Can an addon restart the OpenHAB system? This may be a necessary step when restoring from backup due to the way the json config files are only read at startup.

**Comment by sebastienvermeille** [comment]
Hi @caffineehacker would love to see that!

**Comment by davidgraeff** [comment]
The developer forum is the place to do those kind of discussions now :)
And yes an io service, but probably in the core repository is the way to go.
