### ISSUE TITLE
OH2.2 - typos in homekit.config

### ISSUE THREAD

**Issue by Stefan136** [openhab/openhab2-addons#3049]
I recognized two typos in the homekit.config file.
(openHAB\userdata\config\org\openhab\homekit.config)

`thermostatHeatMode="HeatlOn" `<<< should be "HeatOn"

`useFahrenheitTemperature=B"false" ` <<<< should be ="false", without the 'B'

**Comment by kaikreuzer** [comment]
> should be "HeatOn"

Thanks, fixed with https://github.com/openhab/openhab2-addons/pull/3050

> should be ="false", without the 'B'

No, this format is correct, the "B" stands for "Boolean". This is an internal format of Felix ConfigAdmin, you should not have to worry about these files.

**Comment by Stefan136** [comment]
Many thanks for the clarification and swift Support. Usually I don't care about those files indeed, but I have some issues with unstable Homekit binding. That's why I was checking the config in Detail.
