### ISSUE TITLE
[Homematic] HM-RC-2-PBU-FM unsupported virtual datapoint 'CONT'

### ISSUE THREAD

**Issue by Stefan300381** [openhab/openhab2-addons#3053]
Hi,

this is the first time I submit a bugfix request. Please bear with me if I did something wrong:

## Expected Behavior
No error message in the logfile

## Current Behavior
In my *.rules file I have added some checks for the virtual datapoint PRESS, like:
when
Channel 'homematic:HM-RC-2-PBU-FM:ccu:NEQ1771086:1#PRESS' triggered SHORT
...

When I push the physical switch for a long time, the openhab.log shows an error message:
Unknown value 'CONT' for PRESS virtual datapoint, only SHORT,LONG,LONG_RELEASE allowed

This is inline with the documentation for the binding, no words about "CONT". The error message below is repeated very quickly as long as the physical switch is held!

## Possible Solution
The binding and its documentation need to be updated to support "CONT"

## Your Environment
openhab 2.2 and raspberrymatic 2.29.23.20171216 (on seperate device)

best regards
Stefan

**Comment by OzZyHH** [comment]
The same issue applies for HM-PB-2-WM55-2 device

**Comment by jboeddeker** [comment]
This datapoint is existing for almost all devices which contain keypresses. I see this message also with HM-RC-4-3 & HM-Sen-DB-PCB.

The datapoint definition also lists it.

[http://www.eq-3.de/Downloads/eq3/download%20bereich/hm_web_ui_doku/hm_devices_Endkunden.pdf](http://www.eq-3.de/Downloads/eq3/download%20bereich/hm_web_ui_doku/hm_devices_Endkunden.pdf)

**Comment by MHerbst** [comment]
Ping @gerrieg

**Comment by jboeddeker** [comment]
I understand the button logic like the following (i didn’t check the times, these are just examples):

- when a button is pressed only a short time, upon release the PRESS_SHORT channel is triggerd
- when a button is pressed for let’s say 5 seconds, PRESS_LONG channel is triggered
- when the button is still pressed 10 seconds later PRESS_CONT channel is triggered
- when the button is released after PRESS_LONG was triggered, PRESS_LONG_RELEASE is triggered

Additional to this, there is also a PRESS datapoint. This one gets the values SHORT, LONG, CONT, LONG_RELEASE according to the triggered channels. The enumeration behind this needs to be extended to include also the “CONT” value.

**Comment by gerrieg** [comment]
fixed with https://github.com/openhab/openhab2-addons/pull/3101

**Comment by slzbi** [comment]
Hi @gerrieg ,
sorry for the question, but i am very new in this stuff.
What do i have to do, to get the fix in my Homematic Binding?
Regards Jay

**Comment by gerrieg** [comment]
@slzbi you have to install the 2.3 snapshot

**Comment by slzbi** [comment]
@gerrieg 
Hi gerrieg,
where can i downlaod the file and is there an howto for the process installing the file?
regargs Jay

**Comment by gerrieg** [comment]
see [docs](https://docs.openhab.org/installation/linux.html)
