### ISSUE TITLE
[YamahaReceiver] ‘Zone_2’ of Yamaha HTR-xxx receiver completely incontrollable 

### ISSUE THREAD

**Issue by JacoEHV** [openhab/openhab2-addons#3062]
As already discussed with Tomasz Maruszak in https://community.openhab.org/t/yamahareceiver-binding-has-issue-with-zone-2/19731/43;
‘Zone_2’ of Yamaha receiver models HTR-xxx cannot be controlled with the actual binding. None of the ‘Zone_2’-functions seems to work.

## Expected Behavior

Control ‘Zone_2’ of HTR-xxx models, with functionality as much as possible like ‘older’ models

## Current Behavior

Control of ‘Zone_2’ isn’t possible at all.

## Possible Solution

As already discussed with Tomasz Maruszak, important information to analyse the cause of the problem can be read out of the YamahaRemoteControl/desc.xml-file. This file is already saved and send to Tomasz.

## Steps to Reproduce (for Bugs)

Can’t get any ‘life’ to ‘Zone_2’ using the current binding, therefore not reproducible.
(Second zone can be controlled using HTTP-commands and Yamaha-app, so the problem doesn’t seems to be on receiver side)

## Context

Control the second zone of my Yamaha HTX-4069 receiver, which is completely incontrollable through OpenHAB at this moment.

## Your Environment

- OpenHAB 2.2.0.010 running on Synology DisskStation NAS SD216+II
- OpenHAB 2.2 running on RaspberryPi 3B

**Comment by simonr44** [comment]
This also affects other current models, I have the RX-V583 which has the same problem.
Similar naming convention to the HTR series with zone 2 called Zone_B and they all fall under the Main_Zone element. e.g Main_Zone,Power_Control,Zone_B_Power. 
Control is limited again on this model to power, mute, volume with the addition of Interlock to combine the volume levels of both zones.

**Comment by zarusz** [comment]
@simonr44 thanks for sharing the info. I have proposed changes to accommodate for Zone_B and do a Zone_2 emulation. The custom build JAR for 2.3.0-snapshot is on [my DropBox](https://www.dropbox.com/sh/8y8gg6b4rnb7iuo/AADaIORB107VG9sgNNjF4ZjWa?dl=0). Once tested I plan to push a PR with all my other changes.
 
@JacoEHV is going to test on his HTR-xxx. Let me know if you also could test this?

By the way, it would be great if you could send me the response file from your RX-V583. I am collecting these descriptors as they will help developers support broad range of models.
```
http://<Your_Yamaha_IP>/YamahaRemoteControl/desc.xml
```

**Comment by simonr44** [comment]
I have tested the new jar and can confirm auto detection, volume and power seems to work well on zone 2 now. I do not have time now to test it fully but everything seems in order.

I have attached the response file as requested, glad I could help and if you need testers for this binding in the future let me know. Thanks for all your efforts.

[desc.xml.gz](https://github.com/openhab/openhab2-addons/files/1612891/desc.xml.gz)

**Comment by zarusz** [comment]
PR has be submitted: https://github.com/openhab/openhab2-addons/pull/3264
