### ISSUE TITLE
[homekit] Incorrect brightness values

### ISSUE THREAD

**Issue by Stefan136** [openhab/openhab2-addons#3063]
Hello,

Homekit binding does set arbitrary Color and brightness values sometimes.

Sometimes the brightness is jumping to 100% as well, when I set it on my iPad with the Homekit control. When you move up or down usually the percentage value does change smoothly. However, sometimes it jump up to 100% or down to 0% without any reason. Hence, the issue is not with the Scene but a general binding problem I think.

I did some further testing - with debugging enabled.
I used a fixed scene, with 40% brightness for one lamp only.
I enabled the Scene and in the debug I see the correct value 40 received for this lamp.
```
18:43:13.108 [TRACE] [ions.LengthPrefixedByteArrayProcessor] - Received message of length 310. Existing buffer is 0
18:43:13.131 [TRACE] [ions.LengthPrefixedByteArrayProcessor] - Attempting to read message of length 310
18:43:13.162 [TRACE] [ions.LengthPrefixedByteArrayProcessor] - Read complete message
18:43:13.179 [TRACE] [ions.LengthPrefixedByteArrayProcessor] - Returning 1 results
18:43:13.197 [TRACE] [ulfe.hap.impl.http.impl.BinaryHandler] - Received data [/192.168.5.120:52766]:
00000000 50 55 54 20 2F 63 68 61 72 61 63 74 65 72 69 73 PUT /characteris
........

00000110 69 64 22 3A 31 30 2C 22 76 61 6C 75 65 22 3A 34 id":10,"value":4
00000120 30 7D 5D 7D                                     0}]}

```

Howver then OpenHAB sent a value 0 back, which is causing the light to turn off!

```
18:43:13.470 [TRACE] [ulfe.hap.impl.http.impl.BinaryHandler] - Sending data [/192.168.5.120:52766]:
00000000 48 54 54 50 2F 31 2E 31 20 32 30 34 20 4E 6F 20 HTTP/1.1 204 No
00000010 43 6F 6E 74 65 6E 74 0D 0A 43 6F 6E 74 65 6E 74 Content..Content
00000020 2D 74 79 70 65 3A 20 61 70 70 6C 69 63 61 74 69 -type: applicati
.....

00000090 30 2C 22 76 61 6C 75 65 22 3A 30 7D 5D 7D       0,"value":0}]}
```

I did several tests, and sometimes the value 40 was sent again, causing the light to turn on with the correct brightness. Sometimes the value 100 was sent, even 40 was received before, causing the light being enabled with the highest brightness.

See below for more info:

https://community.openhab.org/t/issue-with-hue-and-homekit/37786

**Comment by J-N-K** [comment]
see #2782
