### ISSUE TITLE
Binding skeleton create script not working

### ISSUE THREAD

**Issue by LasseMoench** [openhab/openhab2-addons#3067]
The script ./openhab2-addons/addons/bindings/create_openhab_binding_skeleton.sh fails when run like described in the tutorial (https://docs.openhab.org/developers/development/bindings.html).

## Expected Behavior
The script should run, after a while ask for the authors name and create the binding skeleton.

## Current Behavior
The script fails with error message
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.0.1:generate (default-cli) on project pom: The desired archetype does not exist (org.eclipse.smarthome.archetype:org.eclipse.smarthome.archetype.binding:0.9.0-SNAPSHOT) -> [Help 1]`

## Possible Solution
Change the binding archetype version to 0.9.0 instead of 0.9.0-SNAPSHOT in line 11 of the script so that it looks like this:
`  -DarchetypeVersion=0.9.0 \`

## Steps to Reproduce (for Bugs)
1. Follow IDE setup tutorial (https://docs.openhab.org/developers/development/ide.html)
2. Follow binding development tutorial (https://docs.openhab.org/developers/development/bindings.html)

## Your Environment

* Version used: Git master branch
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...): Java8
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...): Arch linux

**Comment by kaikreuzer** [comment]
Please note that the current version of the script [references version 0.10.0-SNAPSHOT](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/create_openhab_binding_skeleton.sh#L11).
Are you sure that you are using the latest master?

**Comment by LasseMoench** [comment]
I am so sorry, I seem to have made a mistake when pulling. Closing this, thank you and sorry again!

**Comment by kaikreuzer** [comment]
No worries at all! Have fun and welcome at openHAB :-)
