### ISSUE TITLE
[Homematic] Updating a variable reloades all variables

### ISSUE THREAD

**Issue by Xento** [openhab/openhab2-addons#3068]
## Expected Behavior
I have one rule to trigger a variable update of three items
`rule "CCU Variablen aktualisieren"
when
	Item CUxDTaster_3_PressShort received update ON
then 
	sendCommand(GATEWAYEXTRAS_CCU_SV_Tabletseite, RefreshType.REFRESH)
	sendCommand(GATEWAYEXTRAS_CCU_SV_Briefkasten, RefreshType.REFRESH)
	sendCommand(GATEWAYEXTRAS_CCU_SV_Text2Speech, RefreshType.REFRESH)
end`

As described openhab should only update the values of these variables but it updates all variables.

## Your Environment
CCU2 and Openhab 2.2 Release

**Comment by gerrieg** [comment]
from the docs: _To reload all variable values, send a REFRESH command to any variable._
So it always update all variables

**Comment by mdicke2s** [comment]
This issue was moved to eclipse/smarthome#5789
