### ISSUE TITLE
[homekit] 2.3.0 not working for me

### ISSUE THREAD

**Issue by skatehouse** [openhab/openhab2-addons#3072]
Hi! 
I´m running openhabian 2.2.0 stable on a rpi3. 
Got homekit working for a few days using the 2.2.0 version. Somebody told me to install the 2.3.0 as an addon because it has updates in logging.
I always have the same phenomenon. 

1. Only after a smarthome:homekit clearPairings 
openhab comes alive on my Ipad and is searching for my items.

2. Newly Max eq3-thermostats are not installed due to duplicate issue described in 
[https://github.com/openhab/openhab2-addons/issues/1258](url) 

3. After a raspi reboot or after restart of the service, openhab is not longer available in the home app and all items get the status: no answer (keine antwort)
It worked flawless with the 2.2.0 about a week - due to a 
sudo chmod a-w /var/lib/openhab2/jsondb/homekit.json
like described here: https://github.com/openhab/openhab2-addons/issues/1822

4. 
## Expected Behavior
a) homekit binding should discover all of my devices - can´t find any duplicates concerning names or labels
b) After restart openhab should connect automatically to Ipad or Iphone using Homekit. 
c) i´m really not a professional, but i find it hard to understand that all issues concerning homekit that are not 100% solved have been closed.
d) the configuration in paperui is not quite clear to me. Can they be changed as on the picture? 

![unbenannt](https://user-images.githubusercontent.com/32622670/34545157-29ee6972-f0eb-11e7-90ef-2c07b3def3f0.JPG)
 ##
[log1.txt](https://github.com/openhab/openhab2-addons/files/1602078/log1.txt)

## Context
It would be so great if you get this Home-App working because it´s easy to handle for an apple user. 
Also much easier then any openhabcloud ios app.

**Comment by lastessa** [comment]
any suggestions?

**Comment by J-N-K** [comment]
Please check if this is still the case with a recent version of OH (i.e. 2.5 SNAPSHOT >= 1601).

**Comment by J-N-K** [comment]
Closing as ´current master shares only very little code with 2.3.0. Probably solved
