### ISSUE TITLE
[sonos] media channel WARN messages while thing is not added 

### ISSUE THREAD

**Issue by lsiepel** [openhab/openhab2-addons#3077]
The sonos binding shows warnings in the log while the corresponding thing is not yet added from the inbox (or in my case is hidden in the inbox).

I have a Playbar with two play 1's as left/right rear. The Playbar is added as Thing in openhab, the Play 1's are not. All works as expected except for these WARN messages in the log. The RINCON points to both play 1's. And that is a bit strange, because they are not used in openhab. No thing, no channels.

As far as i know there are two different warnings added to the log every time a different track is played on the Sonos Playbar:

[WARN ] [s.internal.handler.ZonePlayerHandler] - Cannot update media data for group member (Could not find handler for RINCON_XXXXXXXXXXXXX)
[WARN ] [s.internal.handler.ZonePlayerHandler] - Cannot update channel for group member (Could not find handler for RINCON_XXXXXXXXXXXXX)

This is with build 1162 and when i check my logs, this is happening for months, can't determine with what build it was introduced.

**Comment by cweitkamp** [comment]
Please note that the Sonos binding is maintained at https://github.com/eclipse/smarthome. If you encounter issues, report them at https://github.com/eclipse/smarthome/issues. Thanks!

**Comment by lsiepel** [comment]
Done:  https://github.com/eclipse/smarthome/issues/4850
