### ISSUE TITLE
[hueemulation] Allow disable 'off' for some devices

### ISSUE THREAD

**Issue by jhmartin** [openhab/openhab2-addons#3086]
Being able to voice-lock a smart lock is useful. Voice-unlocking potentially less so (don't want someone yelling through a window to unlock the door).  Please consider adding a function to the hue emulation such that an object can be labeled as on-only or off-only. I could then mark my locks as on-only to prevent voice unlocking.

**Comment by Vanshava** [comment]
Alternatively it may have proxy item (restapi loop back) /rule to restrict only "ON" for Hue Emulation. You may also use dummy proxy item and rule it for changed ON then lock.sendCommand(ON)

Example: Restapi loop back .. Dirty but work
Items
Switch doorlock {channel="zwave:something:command"}
Switch doorlockalexa "Door Lock" ["Switchable"] {http=">ON:POST:http://localhost:8080/rest/items/doorlock:ON]"}

Example: Rule
Items
Switch doorlock {channel="zwave:something:command"}
Switch doorlockalexa "Door Lock" ["Switchable"] 

Rule
when 
doorlockalexa changed to ON
then 
doorlock.sendCommand(ON)
end

**Comment by davidgraeff** [comment]
@martinvw Can be closed. A profile would solve this use case I guess?

**Comment by jhmartin** [comment]
@martinvw I see the page about profiles, but its not clear to me how I would customize it to do this.  Can you give me any pointers?

**Comment by martinvw** [comment]
I trusted @davidgraeff on this, so maybe he has any pointers on this.

**Comment by davidgraeff** [comment]
This feature just does not belong into the hue emulation. It needs to be realised on a different abstraction layer. Another way is a script and a proxy item.

**Comment by jhmartin** [comment]
That is a valid point; I'm open to anything that makes it easy to prevent a lock from being incorrectly opened.

**Comment by davidgraeff** [comment]
Closing, as not being related to hueemulation
