### ISSUE TITLE
[onkyo] Spotify album art does not show

### ISSUE THREAD

**Issue by Nebula83** [openhab/openhab2-addons#3088]
## Expected Behavior
When I configure album art, I expect an image and a URL to show in Paper UI console. 

## Current Behavior
When playing Spotify songs, all Metadata except for album art are displayed. Album art stays null. 

## Steps to Reproduce (for Bugs)
Configure album art and album art url:

    String OnkyoCoverUrl "Onkyo Cover Url [%s]"  {channel="onkyo:TX-NR525:<HASH>:player#albumArtUrl"}
    Image OnkyoCover "Onkyo Cover"  {channel="onkyo:TX-NR525:<HASH>:player#albumArt"}

Play song via Spotify Connect on TX-NR525. 
Observe that it does not show album art. 

## Your Environment
OpenHAB2.1
Onkyo TX-NR525
Spotify Connect

**Comment by paulianttila** [comment]
@Nebula83, does album art work e.g. in Basic UI?

**Comment by Nebula83** [comment]
Splendid, yes it does show in BasicUI. I didn't try before. 
It stil  does not, however, show in Control of paper UI. Shouldn't that work as well?

**Comment by paulianttila** [comment]
It has been working with paper UI as well, but openhab rawType (image) has been changed mean while. When mime type is not given, rawType seems to use ”application/octet-stream" mime type as a default and paper UI doesn’t show anything.

**Comment by Nebula83** [comment]
Would it be possible to specify the mim-type?

**Comment by paulianttila** [comment]
@Nebula83, PaperUI should be now fixed.

>Also, since I think the Spotify api sends it, would it be possible to expose the album art url?

Onkyo receiver send image or url, not both. So url channel is updated to undef when image is received as image url is not known.
