### ISSUE TITLE
[max!] show future Reading Time in Trace log

### ISSUE THREAD

**Issue by jmahmens** [openhab/openhab2-addons#3091]
I have some problems with the max binding, so i turn on the TRACE log.

## Expected Behavior
Show Information from Cube in correct form not one month in future.
## Current Behavior
On today (Sunday, 7. Jan) I get this Info from Binding:
`16:26:29.852 [TRACE] [internal.handler.MaxCubeBridgeHandler] -  Reading Time    : Mon Feb 07 16:26:00 CET 18`

## Steps to Reproduce (for Bugs)

1. `log:set TRACE org.openhab.binding.max`
2. wait 

## Context
active MAX Binding

## Environment

OH 2.2 on Raspberrypi3 with Raspian Strech

**Comment by cweitkamp** [comment]
@jmahmens I cannot find this trace log in the code of the `MaxCubeBridgeHandler` anymore. Does it still appear in OH 2.3 release?

**Comment by cweitkamp** [comment]
Confirmed. I was able to reproduce it. Provided a fix for it (see PR #3810).
