### ISSUE TITLE
Feature Request: Enable webapp folder and the ability to render local html sites

### ISSUE THREAD

**Issue by Marty56** [openhab/openhab2-addons#311]
OPENHAB 1 had the webapp folder and the possibility to locally render html sites that could be displayed within sitemaps via the weburl command.
webapp folder should be located within the "conf" folder.
The weather binding e.g. made use of it.

Please provide an (optional) configuration for jetty to enable this function also in openhab 2

**Comment by jenskastensson** [comment]
https://community.openhab.org/t/webapps-folder-is-discontinued-howto-make-files-available-through-http/3159/2

**Comment by kaikreuzer** [comment]
This is now possible - files put in `conf/html` are served as static resources at `http://localhost:8080/static/`.
