### ISSUE TITLE
[network] arping not working

### ISSUE THREAD

**Issue by gelsas** [openhab/openhab2-addons#3112]
Hello,

I am using openHabian on my raspberry pi and ran into an issue.
My openhab version is 2.2

## Expected Behavior
I am trying to use the Networks Binding arping function to check if the phones of my family are currently inside the network. (Presence check). 
Normally it should be able to sent the arping command via the network and receive an response.
 
## Current Behavior
Currently arping is not working for me because the issue is that in openhabian the connection used is not eth0 as it normally is. It is yahmbr0 (because of this: https://openhabdoc.readthedocs.io/de/latest/HomeMatic_YAHM/)

## Possible Solution
Adding the possiblity in configuration to set the connection (eth0/yahmbr0 etc) which should be used by the network binding.

(More information @ https://community.openhab.org/t/network-binding-iphone-presence-detection-arping-configuration-question/38637/16)

kind regards

**Comment by mherwege** [comment]
It does not work for me on my Raspberry running Stretch, with an extra interface either. When I turn on trace logging I see this:
```
2018-01-15 17:26:51.987 [TRACE] [g.network.internal.PresenceDetection] - Perform ARP ping presence detection for 192.168.0.163 on interface
2018-01-15 17:26:51.990 [TRACE] [g.network.internal.PresenceDetection] - Perform ARP ping presence detection for 192.168.0.163 on interface
```
Looking at the code, I don't understand how it does not get the interface name, that should be visible in the trace.

**Comment by kpanchen** [comment]
Have a look here:

[https://community.openhab.org/t/network-presence-binding-update/65461](url)
