### ISSUE TITLE
[Air Quality] station location channel gives not PointType

### ISSUE THREAD

**Issue by emme-g** [openhab/openhab2-addons#3114]
Hello,
I write because in the last days I was reorganizing my Openhab system and I had a problem about the Air Quality binding's stationLocation channel: the documentation about it explains that it can be linked to a Location Item and showed in the sitemap using a Mapview element. I set my system as explained in the documentation but in the sitemap I couldn't see any map showing the location of the Air Quality measuring Station.
I found in the post n. 50 of this discussion
https://community.openhab.org/t/air-quality-binding-looking-for-testers/20756/50
that somebody else had this problem, so I tried to see if this channel would work linking it with a String item and it did, so in my system (Openhab 2.2 Stable, binding downloaded from the repository with PaperUI) the channel stationLocation is a String not a Point.
I managed to have a map showed with a workaround using two rules to update a new PointType item:
file.items
`
String	AqiStationCoordinatesString	{channel="airquality:aqi:house:stationLocation"}
Number	AqiStationLatitude
Number	AqiStationLongitude
Location	AqiStationCoordinatesPoint
`
file.rules
`
rule "measuring station coordinates (string) program"
	when
		Item AqiStationCoordinatesString	changed
	then
		val latitude_String = AqiStationCoordinatesString.state.toString.split(',').get(0)
		val longitude_String = AqiStationCoordinatesString.state.toString.split(',').get(1)
		val latitude = Double::parseDouble(latitude_String)
		val longitude = Double::parseDouble(longitude_String)
		AqiStationLatitude.postUpdate(latitude)
		AqiStationLongitude.postUpdate(longitude)
end
rule "measuring station coordinates program"
	when
		Item AqiStationLatitude		changed	or
		Item AqiStationLongitude		changed
	then
		AqiStationCoordinatesPoint.postUpdate(new PointType(AqiStationLatitude.state, AqiStationLongitude.state))
end
`
I think it should be good to clear if this is a problem of few people's systems or to modify the binding documentation, because the possibility to show in a Mapview element the location of the Air Quality measuring Station is useful.
Bye,

**Comment by tobiasisenberg** [comment]
In OpenHAB 2.2 the behavior is even stranger: The station location airquality:aqi:home:stationLocation only reports "-", despite a call to the Web API of http://api.waqi.info/ reporting a correct geographic location.

**Comment by SiggiFR** [comment]
Hi, I also see only a "-" for the station location item. For me this also looks like an error in the binding ...
Regards, Siegmar

**Comment by martinvw** [comment]
@kubawolanin ping :-)

**Comment by emme-g** [comment]
Hi, I received the notification about the closing of this issue and I tried to verify in my system if the behavior I described in the first message of this discussion changed, but I keep on experiencing the same problem. So, in my system (Openhab 2.2 Stable, binding downloaded from the repository with PaperUI) the channel stationLocation works well if I link it to a String item but not if I link it to a Point item.
