### ISSUE TITLE
[zwave] Current status not reported correctly for 26933/zw3008

### ISSUE THREAD

**Issue by vishtx** [openhab/openhab2-addons#3119]
## Expected Behavior
1. Operating the switch should cause the switch state to be updated in the gui. 
2. Any motion should also result in the contact status to be updated in the gui.

## Current Behavior
Operating the switch doesn't result in the button state to change in the gui. The log just shows "zwave_serial_zstick_xxxx_serial_sof changed from 10634 to 10635" instead of showing "zwave_device_xxxx_nodexx_switch_dimmer changed from 0 to 100".

Similar issue is with motion detection. The log just shows zwave_serial_zstick_xxxx_serial_sof changed.

## Your Environment
* Version used: openhab2 2.2.0-1
* Environment name and version (firefox/openhab app):
* Operating System and version (Raspbian):

**Comment by cdjackson** [comment]
Please discuss this sort of issue on the community forum where more people will be able to help with the configuration. As a minimum you will need to provide a debug log.

**Comment by wborn** [comment]
@vishtx If you still have issues with the [Jasco 26933/ZW3008](http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/740) you can create a topic for this in the [Community Forum](https://community.openhab.org/tags/c/add-ons/bindings/zwave).
