### ISSUE TITLE
Add Philips Android TV Binding

### ISSUE THREAD

**Issue by cribskip** [openhab/openhab2-addons#3121]
Owning a PUS6412/12 myself, I stumbled upon https://github.com/suborb/philips_android_tv and also https://community.openhab.org/t/binding-to-philips-49pus7101-12-android-tv/12428.

I'll start writing my first binding for controlling Philips Android TVs.
But I have some questions, which I need assistance with:

- How to do pairing (PIN entry) with Openhab2?
- Powering ON is available with WOL. How do I depend on another binding? How to use it's WOL function?

I'm sure, I'll find the rest out by myself ;-)

Thanks, Sascha

**Comment by Flole998** [comment]
I'm doing it with exec currently, not very nice but it just works. As far as I know you can't depend on another binding, there are 2 possibilities: Do the wake on lan in your binding, or don't do it at all so people will have to use the WOL binding for that.

For pin entry you could probably use the configuration page to which it gets redirected after the device is discovered. Once it's entered it pairs and activates itself.

**Comment by cribskip** [comment]
Benjamin in the forums already provides a binding for this in the meantime
https://community.openhab.org/t/philips-tv-2016-binding/64579

Closing
