### ISSUE TITLE
[Enigma2] Power channel synchronization problem

### ISSUE THREAD

**Issue by emme-g** [openhab/openhab2-addons#3124]
Hello,
I write about a problem I experience with this binding: the lack of synchronization between the Openhab item linked to the channel “power” and the real power state of my enigma2 device.
When I set on/standby through the Openhab item everything works good and the power state showed in Openhab corresponds to the real state of the STB, when I set on/standby through the physical remote the Openhab item doesn’t update and so I experience the lack of synchronization.
It's a known problem (e.g. it is discussed, among others, here: https://community.openhab.org/t/enigma2-binding/20178/54) but no issue was opened yet here.
Bye.

**Comment by wborn** [comment]
If this is still an issue, please leave a comment for @tratho in https://github.com/openhab/openhab2-addons/pull/1706. This binding has not yet been merged and is still being worked on.
