### ISSUE TITLE
[YamahaReceiver] Selection item not working properly due to state/mapping mismatch

### ISSUE THREAD

**Issue by MaximeLussier** [openhab/openhab2-addons#3127]
Due to a mismatch between state and mappings (HDMI_X vs HDMI), the selection item does not work properly. The current value is not diplayed and an empty value is added as selected.

Selecting an input still works however due to the fact that is uses indexes.

There are some captures showing that the current selected input is not selected in:
https://github.com/openhab/openhab-android/issues/621

## Expected Behavior
Current value is displayed and selected when changing.

## Current Behavior
Current value not displayed on the selection item.
When trying to change the value, an empty item is added due to mismatch.
(The iOS app seems to have the same issue)

## Possible Solution
The mappings and state should both use the same format.
I've added a wokaround snippet in the following issue:
https://github.com/openhab/openhab-android/issues/621
The workaround is a loose matching (alphanumerical only, caseless).

## Steps to Reproduce (for Bugs)
Add a selection item for the input, try it in the android app, the current value is not displayed.
When trying to select, an empty selected entry is added due to the mismatch

## Context
The selection item does not work properly due to the mismatch.

## Your Environment
OpenHab 2.2.0-1
Ubuntu 16.04
Openhab for android.

**Comment by MaximeLussier** [comment]
@zarusz This may be a good candidate to include in your PR.

**Comment by zarusz** [comment]
@MaximeLussier this issue looks like a duplicate of #2758. 
Can you please check if the compiled version for 2.3.0-snapshot on [my DropBox](https://www.dropbox.com/sh/8y8gg6b4rnb7iuo/AADaIORB107VG9sgNNjF4ZjWa?dl=0) solves this?
Remember to use `HDMI1` in your sitemap selection ([example](https://docs.openhab.org/addons/bindings/yamahareceiver/readme.html#for-manually-linking)).

**Comment by MaximeLussier** [comment]
@zarusz I used the instance I installed for issue #3034 with your 2.3.0 jar and the problem seems fixed indeed. 

Do you have an idea when this will be released (in the apt packages)?

Do you wish for me to close this issue?

**Comment by mueller-ma** [comment]
When you use the stable channel, with oh 2.3. Since 2.2 was last month, it may take a few months.

**Comment by MaximeLussier** [comment]
@mueller-ma  Ok, that's fine, I made a workaround in the android app so I can wait.
Thanks!

**Comment by zarusz** [comment]
@MaximeLussier my plan is to [fix RX-3900](https://community.openhab.org/t/yamahareceiver-zone-discovery-not-working-with-rx-v3900/38350) compatibility. After that, I will push all my changes and make a PR. I will keep you in the loop when this happens.

Once the PR is reviewed and accepted, it will be available in the unstable channel as addons 2.3.0-snapshot. My understanding is that it will take another 6 months or so to get a stable 2.3.0 release (consistent with @mueller-ma above).

I was also [investigating options](https://community.openhab.org/t/preparing-the-openhab-2-2-release/36949/90?u=zarusz) to get this faster as a hotfix to 2.2.0 (as 2.2.1), but the process is not yet established.

Yes, please close this one as a duplicate of #2758.
