### ISSUE TITLE
Netatmo: Initializing handler takes more than 5000ms

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab2-addons#3132]
```
2018-01-17 19:23:09.956 [WARN ] [ome.core.thing.internal.ThingManager] - Initializing handler for thing 'netatmo:NACamera:maison:camera' takes more than 5000ms.
2018-01-17 19:23:09.961 [WARN ] [ome.core.thing.internal.ThingManager] - Initializing handler for thing 'netatmo:NAWelcomePerson:maison:Laurent' takes more than 5000ms.
```
Only things relative to camera are apparently impacted.

**Comment by lolodomo** [comment]
@clinique : I am trying to understand what could be wrong with that.
In my Eclipse environment, I was able to see that sometimes NetatmoModuleHandler.initialize takes several seconds (more than 3 seconds). What is blocking is the call to requestParentRefresh. Should it be done in a scheduled tasks ?

I can see that in parallel the rules are loading, maybe it locks the binding during a certain time.

But I can see too that the "parent" device is updating the child modules including downloading image snapshots. I have even not yet linked any channel so it should not happen. Maybe you forgot to check if a channel is linked before requesting the associated data ?

**Comment by lolodomo** [comment]
If I correctly understand, the call to requestParentRefresh is useless when your things are already existing because the parent will do it automatically. But this call is useful when you add a new camera thing for example. That's correct ?

**Comment by lolodomo** [comment]
If I put in comments the call to requestParentRefresh, the method initialize() ends immediately and everything seems to be ok after that.

**Comment by clinique** [comment]
@lolodomo : the requestParentRefresh can be usefull when a module knows that data has changed (for example when one changes schedule or set time on the thermostat) and so needs to grab updated dataset. 

One of the problem raised by a lazy reading is that a parent does not know his childs, and has no clue of their linked channels.

**Comment by lolodomo** [comment]
But with this call, in my example config with one home, one camera and one person, it leads at startup to 3 unneeded concurrent calls (at the same time) to get the home data.
It should be at least run in a separate thread to avoid the timing warning.

**Comment by clinique** [comment]
Yes, using a thread is a good option.
