### ISSUE TITLE
[Homematic] Error: rssiInfo method not found

### ISSUE THREAD

**Issue by lampi87** [openhab/openhab2-addons#3153]
Hello,

after OpenHAB2 restart I get an error in my logfiles
```
[WARN ] [matic.handler.HomematicBridgeHandler] - Unable to load RSSI values from bridge 'ccu'
[ERROR] [matic.handler.HomematicBridgeHandler] - -1 rssiInfo: unknown.method name (sending rssiInfo()
)
java.io.IOException: -1 rssiInfo: unknown.method name (sending rssiInfo()
)
```

## Expected Behavior
Error should not appear

## Current Behavior
Error shown in logfiles. Is something missing in my installation?

## Steps to Reproduce (for Bugs)
1. CCU2 is setup on RPI using YAHM
2. Add CCU2 to OpenHAB
3. Restart OpenHAB and watch logfile

## Your Environment
* Version used: 2.2.0 Release Build
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...): Openhabianpine

**Comment by MHerbst** [comment]
On a first look it seems that the message "unknown.method" is returned by CCU. But I need to have a closer look into the sources to be sure. You could try to enable the trace for the Homematic binding and restart openHAB. With the enabled trace the log file will contain more detailed information from the communication between openHAB and the CCU.

**Comment by ne0h** [comment]
I have the same issue. Where exactly do I have to set logging to trace to provide more information?

**Comment by maxx92** [comment]
Same here... no solution?

**Comment by maxx92** [comment]
Still no one?

**Comment by MHerbst** [comment]
Are you also using YAHM? Can you provide some more information (like a trace output)?

Maybe there is a general problem with YAHM and RSSI information. I found this entry on the Homematic forum: https://homematic-forum.de/forum/viewtopic.php?f=37&t=33522#p316388

**Comment by s0170071** [comment]
Same here. I use: 
RPi 3B+ (stretch) with 
piVCCU (lxc version of CCU) 
OH 2.2 stable
Mosquitto, influxDB, Telegraf, grafana.

**Comment by gerrieg** [comment]
Issue still valid? I have tested it with a CCU and RaspberryMatic, works as expected.

**Comment by maxx92** [comment]
Unfortunately: yes. Now I use pivccu but no improvement.

`2018-06-09 15:16:05.384 [ERROR] [matic.handler.HomematicBridgeHandler] - -1 rssiInfo: unknown.method name (sending rssiInfo()
java.io.IOException: -1 rssiInfo: unknown.method name (sending rssiInfo()
	at org.openhab.binding.homematic.internal.communicator.client.RpcClient.loadRssiInfo(RpcClient.java:385) ~[?:?]
	at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.loadRssiValues(AbstractHomematicGateway.java:520) ~[?:?]
`

**Comment by gerrieg** [comment]
Then i think it is a pivccu issue.

**Comment by s0170071** [comment]
Probably not as pivccu runs the original CCU binary.

**Comment by maxx92** [comment]
.. I had it on a CCU2 when I originally posted..

**Comment by gerrieg** [comment]
On a CCU2? I tried it yesterday on my CCU2. Hmmm, currently no idea why the gateway does not know the RPC method.

Can you please install [Homematic Manager](https://github.com/hobbyquaker/homematic-manager/releases), then click on RPC Konsole, select BidCos-RF and send the rssiInfo command.

**Comment by maxx92** [comment]
Hi Gerhard

As said, I changed from CCU2 to pivCCU about two weeks ago. However, I must add (maybe this has some importance) I use 95% Homematic IP components..
I installed Homematic Manager and sent the rssiInfo > send command. Here’s the output:
'{
  "OEQ0800785": {
    "PEQ0175517": [
      65536,
      -59
    ]
  },
  "OEQ0902127": {
    "PEQ0175517": [
      65536,
      -59
    ]
  },
  "PEQ0175517": {
    "OEQ0800785": [
      -59,
      65536
    ],
    "OEQ0902127": [
      -59,
      65536
    ]
  }
}
'

**Comment by mdicke2s** [comment]
This issue was moved to eclipse/smarthome#5790
