### ISSUE TITLE
[Helios] how is it possible to download and to start using the binding?

### ISSUE THREAD

**Issue by emme-g** [openhab/openhab2-addons#3161]
Hi, I recently found this binding to integrate the Helios IP doorphone in the Openhab system. I have long searched for this binding and now that I've seen that it exists I would be happy to test it, but I don't know how to insert it in my system.
@kgoderis Hello and thank you for your idea and effort in crating this binding, what do I have to do to integrate the binding? Can I use PaperUI or do I have to download a jar file from https://github.com/openhab/openhab2-addons/tree/master/addons/binding/org.openhab.binding.helios (but here I can't find any precompiled package, I'm still new in github so maybe it's there but I can't find it)?
Thank you.

**Comment by kaikreuzer** [comment]
@emme-g Please rather use the community forum for questions, not the issue tracker here.

The Helios binding is part of the official 2.3.0-SNAPSHOT build already, so you will find it directly in the Paper UI if you use a recent snapshot (e.g. from https://openhab.ci.cloudbees.com/job/openHAB-Distribution/)

**Comment by emme-g** [comment]
Ok, I'm sorry. I intended this problem as a lack of information in the documentation. I'm still not that used to the Github system, I'll use the community for these kind of questions next times.
Thank you anyway for your answer.
Bye
