### ISSUE TITLE
[homematic] Multiple firmware for HM-LC-Sw2-FM has to be supported

### ISSUE THREAD

**Issue by robbyb67** [openhab/openhab2-addons#3166]
After 2 years bought a second HM-LC-Sw2-FM, integrated it and found this log entry:
```
Multiple firmware versions for device type 'HM-LC-Sw2-FM' found (1.12, 2.8). Make sure, all devices of the same type have the same firmware version, otherwise you MAY have channel and/or datapoint errors in the logfile
```

For the HM-LC-Sw2-FM actors there is no way to update the firmware, so the binding has to handle this somehow.
Another question is what do I have to expect in the worst case ?

**Comment by tbail** [comment]
I have HM-LC-Sw1-Pl-2 with different firmwares, because the older one are not able to be updated over the air. I never encountered any problems.

Question: Why is ther no way to update the firmware?

**Comment by robbyb67** [comment]
> Question: Why is ther no way to update the firmware?
It's simply not enabled by the manufacturer.

> I never encountered any problems.
I expect this to be true. But this is only an expectation.

**Comment by gerrieg** [comment]
The binding does not support multiple firmwares for one device. I think it would be a configuration nightmare, because you have to add the firmware version to each channel. After an update, you have to reconfigure all channels.
