### ISSUE TITLE
[tplinksmarthome] HS110v2 emeter readings inconsistent with HS110v1

### ISSUE THREAD

**Issue by kcstonacek** [openhab/openhab2-addons#3172]
# [tplinksmarthome] HS110v2 emeter readings inconsistent with HS110v1

The HS110v2 emeter readings are in milliwatts, millivolts, milliamps, and watt hours where as the HS110v2 emeter readings are in watts, volts, amps, and kilowatt hours.

I introduced this in 2455f68f2da2dca6cf8308893173fbee91efa7b7

Proposed fix in PR #3173 

## Expected Behavior
HS110 v2 devices should show the readings in the same format as HS110 v1

volt: 230
amps: 2
watts: 460

## Current Behavior

HS110 v2 devices report the following
volt: 230000
amps: 2
watts: 460000

## Possible Solution
Apply the necessary v1 and v2 detection and calculations in modules/Realtime.java.

The proposed fix includes removing the SerializedName annotations and adding an new set of parameters specific to v2 devices.  The getter and setter methods are then used to determine if it's a V2 device and apply the appropriate calculations.  PR #3173

## Steps to Reproduce (for Bugs)
Use of HS110v2 device and compare to output of HS110v1

## Context
N/A

## Your Environment
SNAPSHOT based on 2455f68f2da2dca6cf8308893173fbee91efa7b7

**Comment by martinvw** [comment]
@Hilbrand

**Comment by Hilbrand** [comment]
@kcstonacek Thanks for the fixes. I've added some small change requests. If you'll fix those I'll update the binding in the eclipse marketplace.
