### ISSUE TITLE
[YamahaReceiver] Support for scenes

### ISSUE THREAD

**Issue by WizBangCrash** [openhab/openhab2-addons#3176]
The new Yamaha receivers (RX-Ax070) all have support for scenes that provide one touch power-on along with selection of the desired source and the appropriate DSP programmes.

Are there any plans to update the YamahaReciever binding to include support for scenes?

**Comment by zarusz** [comment]
Hi @WizBangCrash, could you please send me your device descriptor XML?
It is usually located under `http://<your_yamaha_ip>/YamahaRemoteControl/desc.xml` (or `http://<your_yamaha_ip>/YamahaRemoteControl/UnitDesc.xml` for older devices).

**Comment by WizBangCrash** [comment]
Hi @wborn, See attached for the device descriptor file I pulled off the RX-A3070.

[Yamaha_RX-A3070_Device_desc.zip](https://github.com/openhab/openhab2-addons/files/1965205/Yamaha_RX-A3070_Device_desc.zip)

**Comment by zarusz** [comment]
@WizBangCrash I made the changes to add scene and party mode support. Can you please test if this works for your AVR?

[Here](https://www.dropbox.com/sh/pa069i3bnbsptzj/AABqgJSrQ0lISfDNkUCbwWUma?dl=0) is the addon. Just remove the stock addon and add this one to the addons folder.

[Here](https://github.com/zarusz/openhab2-addons/tree/feature/yamaha_2.3.0_improvements/addons/binding/org.openhab.binding.yamahareceiver#for-manually-linking) is how to use scenes and party mode.
