### ISSUE TITLE
[openhabcloud] Plugin Requires HTTP and does not support HTTPS local connection

### ISSUE THREAD

**Issue by davidski** [openhab/openhab2-addons#3178]
The V2.2 OpenHabCloud plugin is hard-coded (reference https://github.com/openhab/openhab2-addons/blob/master/addons/io/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudService.java#L193) to connect to `http://localhost` for the local OH connection. If a user disables HTTP and enables HTTPS, the plugin will fail to connect to the local OpenHab connection.

Would love to see this plugin detect whether HTTPS is enabled and, if so, prefer that over bare HTTP connections. This would allow users to disable non-TLS protected endpoints, improving their overall security posture.

Thanks for the nifty plugin and service!

**Comment by davidgraeff** [comment]
Fixed
