### ISSUE TITLE
[hueemulation] Suggestion: Request for minissdpd support

### ISSUE THREAD

**Issue by trigrab** [openhab/openhab2-addons#3181]
## Expected Behavior

Hue Emulation works after configuring for minissdpd

## Current Behavior

For me the hue emulation does not work because many upnp services want to use ssdp on port 1900.

## Possible Solution

Minissdpd allows them all to work with port 1900. On the web page it looks very simple to implement: http://miniupnp.free.fr/minissdpd.html

## Your Environment

* Version used: openHAB 2.2.0
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...): Java 8
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...): bananapi m1 with latest armbian stretch

**Comment by davidgraeff** [comment]
@martinvw Not OH related and can be closed.
@trigrab Just install the mentioned 3rd party program and write a tutorial in the forum if it is a common problem.
