### ISSUE TITLE
[Homematic] HM-PB-2-WM55 PRESS_LONG event not fired until button released

### ISSUE THREAD

**Issue by lopez1de** [openhab/openhab2-addons#3200]
## Expected Behavior
PRESS_LONG event is fired 0.4 seconds after pressing the button.

## Current Behavior
PRESS_LONG (eg. #PRESS triggered LONG) is only fired after releasing the button.

## Your Environment
HM-PB-2-WM55
piVCCU
openhab 2.2.0-1 release

**Comment by MHerbst** [comment]
According to the discussion here https://community.openhab.org/t/homematic-hm-pb-2-wm55-press-long-event-not-fired-until-button-release/39493/11 this does not seem to be a problem of the binding.

So, please close the issue here.

**Comment by lopez1de** [comment]
The solution is to change the connection to standard (not secure). This changes the button behaviour.
