### ISSUE TITLE
(Un)supported hardware: Sensative Strips thing unsupported

### ISSUE THREAD

**Issue by cph0x00** [openhab/openhab2-addons#3201]
Trying to add the sensative strip still works. The strip is recognised, but then openhab complains the strip is unsupported. In fact, the strip is marked as supported, but I guess not this revision. 

I provide all infos I have as copy/paste. Don't hesitate to ask further questions of for further infos I can provide with you assistance (I am no pro, not yet). 

```
Status: ONLINE  

HIDE PROPERTIES

zwave_class_basic | ROUTING_SLAVE
-- | --
zwave_class_generic | SENSOR_NOTIFICATION
zwave_frequent | false
zwave_neighbours | 1,2
zwave_nodeid | 3
zwave_version | 0.0
zwave_listening | false
zwave_routing | true
zwave_plus_devicetype | UNKNOWN_TYPE
zwave_beaming | true
zwave_class_specific | NOTIFICATION_SENSOR

```
---
**Configuration | Things** view
Z-Wave Node 3 ONLINE
Unknown Device
zwave:device:6d57fce4:node3

---
**Infos I could extract from homee** 
Firmware revision: 4.05
Hardware version: 0.07 and 0.08 (2 strips)

**Comment by wborn** [comment]
If your Sensative Strips all still not recognized @cph0x00, please add this information to the [Z-Wave Device Database](http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guide). After a few days the updated database should be integrated in the openHAB 2.3.0-SNAPSHOT version.

For more help on this, there is a good [community thread](https://community.openhab.org/t/zwave-device-sensative-strip-11-01-011-not-recogniced/11111?u=wborn) about getting the Sensative Strips recognized. :-)
