### ISSUE TITLE
[network] Suggestion: Use netcat

### ISSUE THREAD

**Issue by kvolden** [openhab/openhab2-addons#3208]
The current implementation of the network binding uses ping, arping, dhcp sniffing and service detection to determine presence. Some smartphones however, do not reply to ping or arping in sleep mode and have no open ports, and even though dhcp sniffing helps determine when the connection happens, it doesn't detect when the phone disconnects. So presence determination of phones seems somewhat flimsy.

But it's possible to determine the presence of both computers and phones and other devices in a simple way using only netcat. When attempting to set up a socket connection to a given IP and port, one of a few things will happen: 1) The connection is sucessful, which means the device is present; 2) the connection is refused, which means the device is present; 3) the connection attempt reaches the device, but the device does not reply, and the attempt times out, which means the device is present; or 4) given a sufficiently high timeout value, the connection is determined to be unroutable and it terminates with a "no route to host" error, which means the device is absent.

The output of the following command will in my experience very consistently determine the presence or absence of a device on the network, whether it's a computer, an Android or an iPhone:

`netcat -v -z -w <TIMEOUT_IN_SECONDS> <IP> <PORT>`

I usually use a timeout of 10 seconds and port 80, but this should perhaps be configurable. Also worth noting is that netcat sends its output to stderr instead of stdout, so programmatically it might be useful to append " 2>&1" to the end of the command to pipe the output to stdout. Determining presence is then simply a matter of checking if netcat's output ends with "No route to host".

An example command follows:

`netcat -v -z -w 10 10.0.0.1 80 2>&1`

I suggest that you consider switching to, or at the very least adding, this as an option for network presence detection/determination.

**Comment by davidgraeff** [comment]
I'm closing this for now, because a normal ping will also trigger the routing table, ARP cache and IPv6 NDP cache. But I'd gladly accept any PR to add more tools to the network binding of course.
