### ISSUE TITLE
[hueemulation] Return newer firmware version for supporting Busch Jaeger Free@home

### ISSUE THREAD

**Issue by Reborn2** [openhab/openhab2-addons#3214]
Hello

Im wamt to use the hueemulation with a knx System called free@home. Now the system Checks the Firmware of the huebridge and told me its to old. Is there an Option too spoof it to a new one ?

Regards

**Comment by Reborn2** [comment]
Can’t, change it anywhere. Have someone a solution ?

**Comment by davidgraeff** [comment]
OH 2.4: The service is now emulating a 2nd gen Hue bridge
