### ISSUE TITLE
[homekit] Thermostats don't get created until restart when added via UI

### ISSUE THREAD

**Issue by magnayn** [openhab/openhab2-addons#3215]
I was attempting to configure a Thermostat, which requires a group and various tags. I could not
figure out why it was not appearing in HomeKit - burning lots of time.

After investigation, this is beccause the way the ChangeLIstener works. When, for example, the group item is changed to add the "thermostat" tag, it only calls the constructor to HomekitHermostatImpl, but the neccessary addCharacteristic is never called (presumably because these are not changed) - so the item does not have the correct children.

When I restarted, it evaluated correctly.

I suspect the logic around change detection needs to be more robust when (say) an individual tag is added to a group to reconsider all the children too.

**Comment by J-N-K** [comment]
Please check if this is still the case with a recent version of OH (i.e. 2.5 SNAPSHOT >= 1601).

**Comment by J-N-K** [comment]
no response
