### ISSUE TITLE
openHAB2-bundles hasn't built in over 2 days

### ISSUE THREAD

**Issue by mhilbush** [openhab/openhab2-addons#3219]
Not sure the best place to report this...

It appears openHAB2-bundles on CloudBees has not built in more than 2.5 days. On the dashboard I have seen where the build is running, but it appears to not be finishing (and not reporting an error).

**Comment by kaikreuzer** [comment]
There is a simple explanation: The build is triggered manually, Jenkins cannot figure out changes that happen in git submodules...
But to make you happy, I have just started a new build, 279 is now your lucky number :-)
https://openhab.ci.cloudbees.com/job/openHAB2-Bundles/279/

**Comment by mhilbush** [comment]
> 279 is now your lucky number

Thanks. I'll be using this number to play the lottery today. ;-)
