### ISSUE TITLE
Bindings will not autoinstall although registered in addons.cfg

### ISSUE THREAD

**Issue by NaScha** [openhab/openhab2-addons#3223]
This issue refers to this post: https://community.openhab.org/t/how-to-get-openhab2-run-in-docker-with-all-desired-bindings-auto-installed/39612/5

I am opening it as I was adviced to do so. At the moment, I am setting up OpenHAB 2.2.0 with docker. Problem is, that bindings registered to addons.cfg do not autoinstall. Even after manuell install via Paper UI, whenever I stop and restart the docker or reboot my machine, bindings are uninstalled again.

`# A comma-separated list of bindings to install (e.g. "sonos,knx,zwave")`
`binding = "ntp,avmfritz"`

In my forum post mentioned above, avmfritz did not install, but ntp did. After having pulled a new docker image, none of them autoinstalls.

I use fully text-based configuration and would like to have to do nothing with PaperUI. If I comment out the binding line in addons.cfg, I have to initially install all bindings once and then, they survive reboots of my machine. Documentation says, that bindings registered there will autoinstall, but it seems to be opposite - these items will be uninstalled.

**Comment by cweitkamp** [comment]
I'm not sure if this is a problem of the avmfritz binding. As you mentioned in the community the ntp binding didn't start either.

Maybe related to openhab/openhab-distro#635.

**Comment by NaScha** [comment]
Yes, you are right - that's why I edited my post above to add that after having pulled a new docker image, none of my bindings configured to autoinstall installs on its own. Unfortunately, I forgot to correct the caption, what I have immediatly done now.

**Comment by Rathna-K** [comment]
Also when they were installed thru feature:install option, they install but then uninstalls immediately.

**Comment by wborn** [comment]
The issue here is that you shouldn't add the quotes @NaScha . Instead use:

```
binding = ntp,avmfritz
```

I could reproduce and fix it this way.
