### ISSUE TITLE
[lgwebos] Add ability manually select the network the TV is on at the binding level

### ISSUE THREAD

**Issue by unparagoned** [openhab/openhab2-addons#3233]
@sprehn I hope this correctly summarises the issue. 

## Expected Behavior
I like others have strange setups where devices are on different networks. This is particularly true of TVs which don't usually play well with VPNs. The binding used to allow me to select the network the TV is on under the configuration settings in PaperUI

## Current Behavior
The latest version of the binding uses the global PaperUI default network. 
Users with devices on different networks may not be able to run conflicting bindings. 
Users with more complicated environments have mentioned issues selecting the correct network using the global PaperUI interface. 

## Possible Solution
It would be very useful to be able to select the network of the TV at the binding level. The binding used to have this option until very recently,
So use the PaperUI default first but let the user select a different network. (Selecting the network has previously been done by entering the opehab device ip)

## Context
Quite a few users have non-trivial setups where being able to select the network at the binding level would help.

## Your Environment
openhab 2.2.0-1
LG webOS Binding lgwebos.2.2.0
Linux debra 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux on ESXi
Two network adapters on two seperate networks.

**Comment by sprehn** [comment]
Perfect description, thx. I added the feature back. Pull request raised.

**Comment by unparagoned** [comment]
Thanks
