### ISSUE TITLE
[Zwave] : unable to interview secured node previously included

### ISSUE THREAD

**Issue by farfade** [openhab/openhab2-addons#3236]
Hi, and thanks for your great work !

## Current Behavior

My zwave network is : 
- one controller
- one dimmer included in non-secured mode
- one switch included in secured mode

All that stuff has been included by openzwave through jeedom.
As jeedom is not really well coded to me, I decided to move to openhab.

So I've setup openhab 2.2 and configured all the stuff, included my zwave network security key.

Openhab drives perfectly the controller and the dimmer (included in non-secured mode).

Openhab sees the switch (it reports its node id), but when I wake it up for the interview, the logs state : 

_NODE 28: SECURITY_ERROR Device message contained nonce that is unknown to us, id=70_

and nothing happens (the node remains as "unknown device" although it is an Aeotec Wallmote that should be supported according to the doc).

When I put a wrong security key, the log message is the same... but my key is the good one, I've triple checked !

Thanks for your help !

Regards,

Romain

**Comment by cdjackson** [comment]
Please [discuss on the forum](https://community.openhab.org/t/oh2-z-wave-refactoring-and-testing-and-security/21653) and close here.

It will also be hard to comment without more information such as what versions you are using, log files etc so I suggest to provide more information. My initial guess is that you are using a version of the that does not support security as you say you are using OH2.2.

**Comment by farfade** [comment]
Thank you and sorry, I did not find the forum.

Romain

**Comment by cdjackson** [comment]
Thanks.
