### ISSUE TITLE
[Network] Switch vs. Contact

### ISSUE THREAD

**Issue by kvolden** [openhab/openhab2-addons#3246]
Network presence is currently represented by a Switch item, while it makes a ton more sense to have it represented by a Contact item. It is effectively a sensor sensing whether a device or service is reachable, not an actuator that does anything at all at the flick of the switch.

The identical issue #2271 seems to have been erroneously closed as fixed by PR #2380.

**Comment by kaikreuzer** [comment]
A device is neither "open" nor "closed", so Contact is clearly wrong here.
It is a misconception that Switch is meant for actuators only - it is also applicable to any on/off sensor information (motion sensors e.g. use it). All that needs to be added to the channel definition is a "readOnly=true" to make it clear that it isn't an actuator channel.

**Comment by NeuerUser** [comment]
I am scratching my head now for hours and hours, trying to set some KNX channels to readOnly. Did I misunderstand something, or am I just using the wrong way?
Background is that I want to see the state of some heating actors, but do not want to be able to change the state. So, I thought "readOnly=true" would be the right way, or am I mistaken? Where would that need to be added?

**Comment by NeuerUser** [comment]
Maybe I should add that the items are defined as "Dimmer", as otherwise the values are shown as values between 0 and 1.
