### ISSUE TITLE
[foobot] Add Foobot Binding

### ISSUE THREAD

**Issue by divyachauhan25** [openhab/openhab2-addons#3247]
I am working on a new binding for the Indoor Air Quality Sensor "FOOBOT".
I will create the PR soon. 
The code for the binding is here - https://github.com/divyachauhan25/openhab2-addons

Expected Behavior -
Allow the sensor readings from the Foobot device to be displayed on the OpenHAB Control panel.

Current Behavior -
Binding does not exist.

My Environment -
Binding created for openHAB2-addons

**Comment by moorgogel** [comment]
how can i use the foobot item on paperui? I try it since hours, and didnt get it..

**Comment by wborn** [comment]
This issue should not have been closed because the Foobot PR still has not been merged, see: https://github.com/openhab/openhab2-addons/pull/3266
