### ISSUE TITLE
[onkyo] TX-NR636 discovered as unsupported receiver

### ISSUE THREAD

**Issue by TimmvonderMehden** [openhab/openhab2-addons#3249]
after installing this binding, my TX-NR636 is discovered as a new but unknown thing in OpenHAB, under things, i find:

`TX-NR636

Unsupported Onkyo AV Receiver

Network enabled Onkyo AV Receivers for models that are not officially supported. You may experience some odd behaviors.`

In the binding documentation https://docs.openhab.org/addons/bindings/onkyo/readme.html the 636 is listed as a supported device. Things and items work pretty well, i also could use all the items from above readme.html using them on a sitemap by just modifing the ip to my receivers ip. The controls in PaperUI work as well (good job by the way, thank you very much!)

When i look into Paper UI:bindings, the 636 is missing there, too.

best regards, Timm

## Your Environment

OpenHAB version 2.2.0, using Windows 7 x64 and also Raspberry PI

**Comment by Cossey** [comment]
Looking at the source code I don't see anything specifically for TX-NR636 although the readme does list it as supported for some reason. Maybe this was a typo or maybe support is implied with another model number? Probably should be added though. 

@TimmvonderMehden can you confirm this receiver supports `Zone 2` only? I can look at adding this in if you would be willing to test the add-on I can build to make sure it works correctly?

**Comment by Pockenfresse** [comment]
@Cossey Hi, I also have the TX-NR636. If you could do the programming, I would test it. However, I'm still quite new to OpenHab. Have a little patience with me.
The receiver has two zones. Zone 1 is for the living room for Home Cinema and Zone 2 for the kitchen.

best regards, Olf

My Enviroment: openHAB 2.4.0 on Ubuntu 18.04

**Comment by Cossey** [comment]
Hey Pockenfresse,

To confirm, did it discover your receiver successfully in the inbox on Paper UI and did you add it by clicking the Tick button and then Add Thing?

Once you do this and look in the Control section it should show your receiver (it should also show a Zone 2 section).

Remember that auto-detection doesn't auto add the Thing (unless you toggle the setting on in the config files).
