### ISSUE TITLE
Netatmo: updates every 30 seconds for camera

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab2-addons#3256]
In Eclipse dev env, I created a bridge thing and enabled only readCamera flag.
I can see in the logs that the update strategy is initialized with the default 300000 (5 minuites) refresh setting.
But I can see that updateChannels is called every 32 or 33 seconds with such logs:
```
2018-02-18 13:22:44.186 [DEBUG] [n.handler.NetatmoDeviceHandler:84   ] - Scheduling update channel thread in 30 s
...
2018-02-18 13:23:14.201 [DEBUG] [n.handler.NetatmoDeviceHandler:111  ] - Data aged of 1520418454 s
2018-02-18 13:23:14.201 [DEBUG] [n.handler.NetatmoDeviceHandler:113  ] - Trying to update channels on device xxxxxx
---> HTTP GET https://api.netatmo.net/api/gethomedata?home_id=xxxxxx
---> END HTTP (no body)
<--- HTTP 200 https://api.netatmo.net/api/gethomedata?home_id=xxxxxx (415ms)
...
2018-02-18 13:23:16.610 [DEBUG] [n.handler.NetatmoDeviceHandler:84   ] - Scheduling update channel thread in 30 s
```
It looks like that `refreshStrategy.dataAge()` is always very high and so `refreshStrategy.isDataOutdated()` returning always true.
Something looks not normal.

**Comment by lolodomo** [comment]
This issue is critical as it seems it can lead to banishment for 24 hours. It is apparently what happened to me yesterday.
I have now deleted my Welcome things in my production environment and I will try to debug again (after replacing the default 30s retry delay by a greater value).

@clinique for information.

**Comment by cweitkamp** [comment]
This could be a side effect of my PR #3218 as well. It occurred now because the jobs are rescheduled continuously which wasn't the case before.

The [RefreshStrategy](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/RefreshStrategy.java) assumes a default delay of 30 seconds which are added to the last known timestamp. If the difference of `dataValidityPeriod - dataAge()` is negative this will always be 30s. What about introducing a retry counter which tries to e.g. three times and raises the delay after the third failure?

**Comment by lolodomo** [comment]
The question is more why the dataAge() returns a value like 1520418454 ?!

**Comment by lolodomo** [comment]
I think I found the issue. Following the data retrieval, RefreshStrategy.setDataTimeStamp is called with a negative value of -935083. I think the problem is that the parameter is declared as Integer while it should be very probably declared as Long.
I will submit a fix.

**Comment by lolodomo** [comment]
Very annoying, Integer is used everywhere in the code for timestamp handling...

**Comment by lolodomo** [comment]
@clinique : any idea why device.getLastStatusStore from io.swagger.client.model.xxx is returning an Integer rather than a Long ?

**Comment by clinique** [comment]
I suspect an error in the swagger definition 

Envoyé de mon iPhone

**Comment by lolodomo** [comment]
Ok I found where was the problem and how to fix it. For Welcome, this timestamp is built wrongly by the binding and is not provided by the swagger.

**Comment by lolodomo** [comment]
Ok, I fixed the issue.

@cweitkamp : your refresh strategy adding systematically 30 seconds has the consequence for Welcome camera that the refresh frequency is not the value setup in the thing parameter (default to 300 seocnds) but in fact 329 seconds (300 + 30 - 1 while -1 is due to rounding). Why did you add systematically 30 seconds ?

**Comment by cweitkamp** [comment]
I think you misunderstood my post. I didn't introduced the addition of the delay. It was in the code before.

Before my fix the job wasn't rescheduled if an error occurred. Now it is rescheduled every 30 seconds if an error occurs. I guess the delay is only important for the weather station. Not for the cameras.

**Comment by lolodomo** [comment]
@cweitkamp : ok, I thought you added this delay, maybe to avoid an immediate rescheduling in case of error.
@clinique : can you explain the reason of this additional 30 seconds delay ?

**Comment by clinique** [comment]
@lolodomo : yes, I can. If for any reason the reread of weather data is done in a too narrow time (a delay of some seconds on Netatmo servers), we're at risk to read twice the same data. So, in this case, it is read once again 30 seconds later. I don't know if this can happen in real life, but I thought it as a security.

**Comment by lolodomo** [comment]
Ok but for Welcome camera, it has no sense as the timestamp is built by the binding. I will think about an improvement.

**Comment by lolodomo** [comment]
@clinique : testing my improvement, I discovered another strange thing:
https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/handler/NetatmoDeviceHandler.java#L140
I think the call to `super.updateChannels();` and `updateChildModules();` should be moved above to be run only when the data is outdated. Currently, when the data is not outdated, this leads in particular to a call to the netatmo API by the WelcomePerson hander.
WDYT ? Was there a valid reason to update child modules even when the data is not outdated ?

**Comment by clinique** [comment]
@lolodomo : AFAIR this was located here to avoid having a child module whith empty channels  until the next polling when it is just added.

**Comment by lolodomo** [comment]
Ok
