### ISSUE TITLE
[homematic] raspiMatic + openhab 2.2 - missing GATEWAY-EXTRAS when HUE items added to CCU

### ISSUE THREAD

**Issue by gaudihub** [openhab/openhab2-addons#3257]
## Expected Behavior

GATEWAY-EXTRAS should show up as a thing in paperUI, but it doesn't

## Current Behavior
after installation of the binding with paperUI and configuration of the gateway with gatewayType=ccu, the GATEAY-EXTRAS doesn't show up. All other things are properly identified and online.

When deleting all hue items from the CCU (incl. the hue bridge), the GATEWAYS-EXTRA showed up in paperUI

## Your Environment

* Version used: openhab 2.2
* CCU: RasperryMatic 2.31.25.20180120

**Comment by LosPommos** [comment]
This is a duplicate to: https://github.com/openhab/openhab2-addons/issues/3217
