### ISSUE TITLE
Grafana icon remains in dashboard although it has been uninstalled

### ISSUE THREAD

**Issue by Boby71** [openhab/openhab2-addons#3260]
Happens in current "unstable" version - when Grafana is being installed, an icon will be added to the UI's dashboard (/start/index). When Grafana is being uninstalled again, the icon remains in the dashboard.
Deleting the respective lines in the dashboard.cfg and restart doesn't help.

This issue seems to hit other users as well:
[https://community.openhab.org/t/remove-grafana-and-influxdb-icon-left-in-webfrontend/38436/2](url)

**Comment by wborn** [comment]
The Grafana dashboard tile is openHABian specific functionality. If this is still an issue, please open an issue for this in the openHABian [issue tracker](https://github.com/openhab/openhabian/issues).
