### ISSUE TITLE
[Kodi] Add "label" channel

### ISSUE THREAD

**Issue by mtzro2003** [openhab/openhab2-addons#3265]
@AnthraxLeprosyPi

Kodi binding already provides `title` and `showtitle` channels, but those work only for items in Kodi library.
I would like to request the addition of a new channel - `label` - to return the filename playing in Kodi.
Right now, I'm using an `exec` command to curl through Kodi's JSON-RPC API to get the label...

**Comment by cweitkamp** [comment]
May I ask you to post an example curl statement and response for a situation where this is true? TYVM.

**Comment by mtzro2003** [comment]
Sure thing!

Command:
`curl -s -D- -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","method":"Player.GetItem","params":{"playerid":1},"id":"1"}' -u USERNAME:PASSWORD http://KODI_IP:KODI_PORT/jsonrpc`

Response:
`{"id":"1","jsonrpc":"2.0","result":{"item":{"id":873,"label":"Brawl in Cell Block 99","type":"movie"}}}`

I repeat: this `label` is useful for movies/episodes not in Kodi's library. When the file played is in the library, the `label` matches the `title` like in my example.
Here a response for a video not in library:

`{"id":"1","jsonrpc":"2.0","result":{"item":{"label":"60 min Elefantul Cici  TraLaLa.mp4","type":"unknown"}}}`

You can see that, when the file played is not in the library, `label` matches the filename.
and an example of a tv show (also present in library):

`{"id":"1","jsonrpc":"2.0","result":{"item":{"id":6733,"label":"You’d Know What to Do","type":"episode"}}}`


One other thing I tried is to get the filename of the currently played media:
`curl -s -D- -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","method":"Player.GetItem","params":{"properties":["file"],"playerid":1},"id":"1"}' -u USERNAME:PASSWORD http://KODI_IP:KODI_PORT/jsonrpc`

Result:
`{"id":"1","jsonrpc":"2.0","result":{"item":{"file":"<PATH>/Brawl.in.Cell.Block.99.2017.720p.BluRay.DD5.1.x264-playHD.mkv","id":873,"label":"Brawl in Cell Block 99","type":"movie"}}}`

One more time: `title` and `showtitle` are very useful for items included in the library... What about those who are not in the library - like videos/home movies? I would like to "see" at least the filename (or `label`)

**Comment by cweitkamp** [comment]
Thank you for the very detailed explanation. If both properties are the same I suggest not adding a new channel for the label but to change the logic of the title channel a little bit. Currently the binding checks if the title property exists before using it else return an empty string. We could return the label property instead. Wdyt?

Maybe the file name is worth adding a new channel.

**Comment by mtzro2003** [comment]
Actually, you're totally right!
As `label` matches `title` for items in the library and filename for those not included returning it instead  makes sense.

Thank you very much!

**Comment by cweitkamp** [comment]
PR #3269
