### ISSUE TITLE
[Weatherunderground] Binding doesn't store private weather station ID

### ISSUE THREAD

**Issue by dk8pn** [openhab/openhab2-addons#3268]
If the location configuration of the thing is set to a private weather station ID, e.g. pws:ICOTTENW1, it works out as expected.

## Expected Behavior
This thing setting should be saved then.

## Current Behavior
After next restart of openHAB2.3.0 the location is set to the coordinates of my weather station and the private weather station ID is lost. I need to set it again manually after every restart.

Best regards,

Willi

**Comment by lolodomo** [comment]
Check that your rhink is not the default local thing in case you set a system location.
This is the only case I can imagine that could lead to what you noticed.

**Comment by dk8pn** [comment]
Hello,

 

thanks for this hint. I have indeed configured local location system coordinates. Do you propose to delete them?

 

Best regards,

 

Willi

 

Von: lolodomo [mailto:notifications@github.com] 
Gesendet: Freitag, 23. Februar 2018 19:46
An: openhab/openhab2-addons
Cc: dk8pn; Author
Betreff: Re: [openhab/openhab2-addons] [Weatherunderground] Binding doesn't store private weather station ID (#3268)

 

Check that your rhink is not the default local thing in case you set a system location.
This is the only case I can imagine that could lead to what you noticed.

**Comment by lolodomo** [comment]
No, I propose to not use the WU thing linked to the system location, that is the thing named weatherunderground:weather:local. Create another thing wioth a different UID.

You should have asked the community (forum) rather than declaring an issue for something that is not an issue,; and you even do it in the wrong git repo.

Please change your thing UID and then close this issue.

**Comment by dk8pn** [comment]
I would be happy if i would understand what you mean? The thing has been setup using the paperUI. Don't work with manually setup UID.

Please advise in more detail what i should do.

Thanks.

**Comment by lolodomo** [comment]
Please tell me first what is your current WU thing ID so that I can conclude my analysis is correct.

**Comment by wborn** [comment]
Please use the [Community Forum](https://community.openhab.org/t/new-weather-underground-binding-for-eclipse-smarthome-openhab2/19701?u=wborn) if you need help with using the Weather Underground binding @dk8pn. 

Defects and feature requests for this binding should be added to the Eclipse SmartHome [issue tracker](https://github.com/eclipse/smarthome/issues).
