### ISSUE TITLE
[tankerkoenig] Failure in JSON-Reading

### ISSUE THREAD

**Issue by koleesch1** [openhab/openhab2-addons#3282]
Hi,
i found a failure in your json-parser.  Tankkönig don't send json null-Strings in the prices... 
here is an example:

"prices": {
       "ab9d0fe4-64e8-4a61-808f-c2e4ac84c270": {
           "status": "open",
           "e5": 1.339,
           "e10": 1.319,
           "diesel": 1.149
       },
       "4af5e1d3-16b8-43bf-2887-304e64861987": {
           "status": "open",
           "e5": 1.349,
           "e10": false, <-- this is not a json-nullstring
           "diesel": 1.149
       },
       "4ba0682b-8de1-4544-be11-fed2ffa90342": {
           "status": "open",
           "e5": 1.369,
           "e10": 1.349,
           "diesel": 1.199
       }

**Comment by JueBag** [comment]
The log you posted shows what Tankerkoenig is responding, the binding is expected to give an under, displayed as NaN.
So it looks OK to me,.

**Comment by koleesch1** [comment]
Also Probieren wir es mal in Deutsch… 
Im Deserializer CustomTankerkoenigDetailResultDeserializer wird bei den Benzinpreisen (Diesel, E10, E5) nach JSON-NULL abgefragt, was ja richtig ist. Leider weicht hier der Webservice vom Tankerkönig vom Standard ab. Statt nicht vorhanden Benzinpreise einfach nicht mit zu liefern bzw. den Spritpreis nicht mit zu liefern (dann funktioniert die JSON-Null-Abfrage, wird einfach ein boolscher Wert zurückgeliefert. Dieser Wert ist definitiv nicht NULL. Also muss eine Exception ausgelöst werden und die ganze Tankstelle wird dann wahrscheinlich nicht mehr gepasst und somit ergeben sich keine gültigen Werte für eine Tankstelle. Siehe Beispiel im Anhang...

**Comment by JueBag** [comment]
Moin,
für eine Spritart SOLL von der Tankstelle (gem. den Vorgaben von Tankerkoenig.de bzw. derMarkttransparenzstelle), wenn diese nicht angeboten wird, FALSE gemeldet werden. Die wird von den Tankstellen NICHT stringent verfolgt (auch wenn ich zZ keine Beispiele habe). Eine Korrektur der Meldung findet m.E. an keiner Stelle statt.
Ergo muß die Meldung FALSE für einen Preis verarbeitet werden.
M.E. erfolgt diese Verarbeitung für jeden Preis, ein einzelnes FALSE führt nicht zum Abbruch der Preisfesrstellung einer Tankstelle (zumindest in der aktuellen Version, die Änderung hierzu ist aber schon länger eingebaut.).
Ob ich (Java und Open Source Neuling und Non-Profi) mich bei der Implementierung nicht an Standards gehalten habe ist mehr als möglich. Ich lerne aber gerne hinzu und lehne eine Änderung auch nicht prinzipiell ab. Nur verstehe ich das dargestellte Problem eher als eines der bereitgestellten Daten, auf die ich keinen Einfluss habe.

**Comment by JueBag** [comment]
Please use my EMail adress directly for further discussions in German language.

**Comment by koleesch1** [comment]
Ist es evtl. Möglich, mit den Beispielen das Ganze zu debuggen? Dann können wir das evtl. Ausschließen...

> Am 06.03.2018 um 09:04 schrieb Jürgen Baginski <notifications@github.com>:
> 
> n diese nicht angeboten wird, FALSE gemeldet werden. Die wird von den Tankstellen NICHT stringent verfolgt (auch wenn ich zZ keine Beispiele habe). Eine Korrektur der Meldung findet m.E. an keiner Stelle statt.
> Ergo muß die Meldung FALSE für einen Preis verarbeitet werden.
> M.E. erfolgt diese Verarbeitung für jeden Preis, ein einzelnes FALSE führt nicht zum Abbruch der Preisfesrstellung einer Tankstelle (zumindest in der aktuellen Version, die Änderung hierzu ist aber schon länger eingebaut.).
> Ob ich (Java und Open Source Neuling und Non-Profi) mich bei der Implementierung nicht an Standards gehalten habe ist me

**Comment by JueBag** [comment]
??I just did the test again, now I get NaN for all prices?  I'll have a deeper look when I'm back home.

**Comment by JueBag** [comment]
Forget the last report,  must have been due to the slow VPN connection. I get prices for E5 and Diesel,!

**Comment by JueBag** [comment]
@koleesch1 : Is this still a "failure" for you? I'd be happy to continue the discussion ( and do changes in the if deemed necessary ), if not you/we should close this one.

**Comment by koleesch1** [comment]
Hello,

For me it is a failure.

Greetings

**Comment by JueBag** [comment]
In this case, what are getting from the channels that you do see as a failure?

**Comment by JueBag** [comment]
Since there is no future input, I'll sum up the situation concerning this reported issue.

Whatever the "correct usage" of JSON is, the OH binding has to take what it gets delivered by the provider of the JSON. That is Tankerkoenig.de and they are most probably take the unchanged input from the MTS-K. I see no chance making them change the delivered JSON!
Concerning what the binding how the binding treats the data in case no price is delivered is driven by the need to handle inputs that are not according the documentation ( should be FALSE,  is sometimes NULL etc...) and the agreed desire by users (see the old issue linked above) to receive an UNDEF in order to easily discard such data from a persistence strategy.
In short I do NOT see an issue for the binding in here.

**Comment by JueBag** [comment]
👍
