### ISSUE TITLE
Netatmo: call of the netatmo API each time a Welcome Home channel is linked

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab2-addons#3286]
Each time a channel is linked (using Paper UI), the binding is calling the API with a `getlasteventof` request.
It might be the reason why I was banished few days ago.
I think the binding should cache the last API call result and use it when linking new channels.

@clinique: WDYT ?

**Comment by lolodomo** [comment]
The API seems to be even called twice.

**Comment by lolodomo** [comment]
channelLinked is called twice leading to two commands REFRESH. This is apparently the core framework that is doing that.

In fact, the unexpected call is done by the Person handler when updating the channels of the child module. In this case, the data age validity is not considered by the binding.

**Comment by lolodomo** [comment]
The problem concerns only the thermostat and the welcome person modules

**Comment by lolodomo** [comment]
]@clinique I have one question for you relative to this code line.
https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/welcome/NAWelcomePersonHandler.java#L49
Why are you requesting 10 events if you want to get only the last one ? Can't we get the last one just by setting the last parameter to 1 ?

**Comment by clinique** [comment]
@lolodomo : this code was not produced by me. I suppose we could try to grad only the last one.

**Comment by lolodomo** [comment]
Ok, finally I think I know how to fix that properly. I will add a boolean flag "readingsRequired" on the module.
I am just waiting for the merge of my current netatmo PR to switch to this new one.
