### ISSUE TITLE
Netatmo: internationalization is missing for Welcome Camera

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab2-addons#3288]
Missing internationalization needs to be added.

**Comment by cweitkamp** [comment]
IMHO we don't need an issue for this. The translations are missing in a lot of bindings and this one is not solved with adding e.g. French and German. Please be aware of https://github.com/openhab/openhab-core/issues/275 . We are looking for a global solution to translate all bindings in this repo with the help of the community.
