### ISSUE TITLE
[Homematic] Actual Temperature of Thermostats not updating

### ISSUE THREAD

**Issue by gelsas** [openhab/openhab2-addons#3307]
Hello,

I am using the latest openhab version 2.3 and the latest homematic binding for it. 

I just noticed that the values for the actual tempature of my thermostats is not updating automatically as before.

How can I get it working again?

**Comment by MHerbst** [comment]
I tested it in my environment and everything works fine.

Do you have any messages in the openhab.log resp. event.log?

Also please check the following:
1. Did you set a callback network address in bridge configuration? Especially when having more than one IP address this setting is important.
1. If you have a CCU please check the firewall settings of the CCU.

If everything looks fine we would need some more information about your environment:
* are you using a CCU or Homegear or ...
* where is openHAB running?

**Comment by gerrieg** [comment]
@gelsas Is the issue still valid?
