### ISSUE TITLE
MVN Clean Install build of openhab2-addons fails at AVM FRITZ! Binding

### ISSUE THREAD

**Issue by ncpe20012003** [openhab/openhab2-addons#3323]
I'm stumped, I have pulled from the master twice still same result.
[INFO] Reactor Summary:
[INFO] 
[INFO] openHAB 2 Add-ons 2.3.0-SNAPSHOT ................... SUCCESS [  0.363 s]
[INFO] openHAB Add-ons .................................... SUCCESS [  0.052 s]
[INFO] openHAB Bindings ................................... SUCCESS [  0.046 s]
[INFO] AirQuality Binding ................................. SUCCESS [ 11.939 s]
[INFO] AllPlay Binding .................................... SUCCESS [  6.953 s]
[INFO] Amazon Dash Button Binding ......................... SUCCESS [  5.759 s]
[INFO] Atlona Binding ..................................... SUCCESS [  7.007 s]
[INFO] Autelis Binding .................................... SUCCESS [  4.889 s]
[INFO] AVM FRITZ! Binding ................................. FAILURE [  0.510 s]
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:1.0.0:compile (default-compile) on project org.openhab.binding.avmfritz: Compilation failure: Compilation failure: 
[ERROR] /home/choyle/openhab2-master2/git/openhab2-addons/addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/discovery/AVMFritzDiscoveryService.java:[140] 
[ERROR] 	scanningJob = AbstractDiscoveryService.scheduler.scheduleWithFixedDelay(() -> {
[ERROR] 	                                       ^^^^^^^^^
[ERROR] The field AbstractDiscoveryService.scheduler is not visible

**Comment by martinvw** [comment]
It's not you, you are right, its related to:

https://github.com/openhab/openhab2-addons/pull/3324

**Comment by cweitkamp** [comment]
I assume it is working now.
In case the fix from #3324 fixes it for you please close this issue.
