### ISSUE TITLE
unable to run Exec on windos

### ISSUE THREAD

**Issue by aihysp** [openhab/openhab2-addons#3326]
Hi i have an issue to config Exec 2 to openhab map
i dont see any error in the logs 
i am trying to run a VBS script or any file
i dont knowh the exact path i need to provide 
please help!

**this what i was able to put togther:**

sitemap:
Switch item=YourTrigger

Items:
Switch YourTrigger { channel=“exec:command:myscript:run”}

things:
Thing exec:command:myscript [command=“vbs ./conf/scripts/XGame.vbs %2$s”, interval=0, autorun=false ]

runing openhab 2.2 on widnows mcahine with Karaf

**Comment by wborn** [comment]
It looks like you found out how to [run VBS files](https://community.openhab.org/t/how-to-run-vbs-scripts-on-windows-machine/41468?u=wborn) with the Exec binding yourself. Thanks for also taking the time to write down your wisdom! :smiley: 

Maybe you can even skip compiling the .vbs to .exe and run your .vbs file using wscript.exe?
