### ISSUE TITLE
[keba] Not a valid firmware

### ISSUE THREAD

**Issue by erik73** [openhab/openhab2-addons#3328]
Hi!
I am running the snapshot 2.3.0 Build #1225.
I have a KeContact P30x wallbox, and it runs firmware 3.08.7
I get the following exeption:

``` 
21:06:40.390 [WARN ] [ommon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception
java.lang.IllegalArgumentException: Not a valid firmware
	at org.openhab.binding.keba.KebaBindingConstants$KebaFirmware.getFirmware(KebaBindingConstants.java:127) [195:org.openhab.binding.keba:2.3.0.201803101457]
	at org.openhab.binding.keba.handler.KeContactHandler.onData(KeContactHandler.java:223) [195:org.openhab.binding.keba:2.3.0.201803101457]
	at org.openhab.binding.keba.handler.KeContactHandler$1.run(KeContactHandler.java:158) [195:org.openhab.binding.keba:2.3.0.201803101457]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```

I guess that is what makes non of the fields in the gui show correct data? Is it possible to add 3.08.7 as a valid firmware?

**Comment by elmario55** [comment]
The same problem with firmware P30 v 3.9.10 (171113-103030) ! What to do?

**Comment by wborn** [comment]
You can add missing firmwares to the KebaFirmware enum and test if all works well:

https://github.com/openhab/openhab2-addons/blob/8988ed72415209c1514bc32c9dc4ad8ffe05db99/addons/binding/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/KebaBindingConstants.java#L100-L110

Maybe @kgoderis already has some plans to do this?

**Comment by kgoderis** [comment]
@wborn I am not up to speed with the latest firmwares and I have to go through the release notes to see what has changed.

**Comment by elmario55** [comment]
Yesterday i tried to add Firmware V3.09.10 to the list of puplic enum. But by compiling the *.java to *.class i got 5 errors and no *.class file.
I have not really knowledge about programming with java, so may be i made one  (ore moore) mistakes.

**Comment by elmario55** [comment]
@kgoderis  I got a Mail from KEBA, ther are no changes on UDP wtih the new Firmware, so changing "puplic enum" could work? I also got "old" firmware 3.08.4, so i can rollback firmware till inding is working with new firmware

**Comment by Ollipu** [comment]
Is there already an update / snapshot available for this issue or does somebody managed to compile the file? 
@elmario55 How you manage the rollback to 3.08.4? Keba told me it is not possible.

**Comment by elmario55** [comment]
@ Ollipu  
Rollback works in the same way as firmwareupdate. See the procedure in your manual. The file to rollback to 3.08.4 is here:
https://github.com/openhab/openhab2-addons/files/206611/KEBA_P30_USB_3.08.4_.170307-132509.zip
I rolled back with this file and it worked.

**Comment by elmario55** [comment]
Sorry, the link is not working, try this one:
[KEBA_P30_USB_3.08.4_(170307-132509).zip](https://github.com/openhab/openhab2-addons/files/2066119/KEBA_P30_USB_3.08.4_.170307-132509.zip)

**Comment by AndiSteffen** [comment]
Hi all,

we have a Keba P30x with newest availible Firmware, reported in UDP Message as "Firmware":"P30 v 3.9.10 (171113-103030)". I can also see the the error Message in Openhab
What consequence does the error have for the functinality in openhab? Is this just to show the firmware Version? Or are there values that will not be availible in Openhab? I am asking, because I get some values like PlugStates and Session Energy. Other values like Operation State are without values.

**Comment by paalrune** [comment]
i have seen that the "trick" are to use the older firmware, but i think it will be a better sulution to fix the binding?

**Comment by elmario55** [comment]
if there is anybody who can fix the binding - i can't do it. 
I have no idea about programming, i'm still a silly user!

**Comment by kaikreuzer** [comment]
@kgoderis Any chance you can help out here?

**Comment by erik73** [comment]
Here is a version that I compiled, including all the released firmware versions that i know of.
[org.openhab.binding.keba-2.4.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab2-addons/files/2717494/org.openhab.binding.keba-2.4.0-SNAPSHOT.jar.zip)

**Comment by paalrune** [comment]
i think i have try a lot, but some funny thing even whit wrong ip i got "online status" in the GUI

**Comment by kaikreuzer** [comment]
FTR, https://github.com/openhab/openhab2-addons/pull/4987 works nicely for me with firmware 3.9.1 - so I hope it's gonna be merged soon!
