### ISSUE TITLE
[homematic] Jetty HttpClients are not stopped properly

### ISSUE THREAD

**Issue by FStolte** [openhab/openhab2-addons#3388]
## Expected Behavior
1. After initialization of a `DefaultHomematicGateway`, the httpClient that is created to load gateway infos is stopped again.
2. After disposing of a `DefaultHomematicGateway`, e.g. because the bridge thing has been deleted, the httpClient of its `XmlRpcClient` is stopped.
3. When deleting the bridge thing during its initialization, all its created httpClients are stopped finally.

## Current Behavior
All started threads for jetty httpClients from the Homematic Binding remain present after a bridge thing is deleted. If it is deleted during initialization, a httpClient is started even after disposing the `DefaultHomematicGateway` (i.e. the initialization is continued even after `dispose()` finished).

## Possible Solution
In the `XmlRpcClient`, `httpClient.destroy()` is called. The proper way to dispose of a jetty HttpClient is to call `httpClient.stop()`. I will provide a PR for this fix. However, it only adresses the first two problems. When `dispose()` is called on a `HomematicBridgeHandler` before `initialize()` of that handler finishes, the jetty httpClient is still initialized and not disposed.

One solution for all these problems would be to use the newly introduced `HttpClientFactory` and the shared http client provided by it. The only drawback I can currently see is that the custom timeout `
        httpClient.setConnectTimeout(config.getTimeout() * 1000L);` could not be used anymore. If you think this solution is acceptable, I will start working on a PR for that, as well.

## Context
When frequently adding and removing homematic bridges or when there is a bridge thing that cannot communicate with the homematic gateway (and thus repeats initialization again and again), more and more threads accumulate. Finally, there will be an OutOfMemoryError. This might also be the cause for problems mentioned in #2849.

**Comment by kaikreuzer** [comment]
FTR: This is how the [shared Jetty HTTP client instance](https://github.com/eclipse/smarthome/pull/5126/files#diff-2e37bb117262a383ce29b6928135e3d3R62) can be used (should be obtained through the handler factory and passed to the handlers through the constructor).

**Comment by FStolte** [comment]
Thanks for the hint, I already assumed that it needs to be injected at the HandlerFactory, but was not entirely sure.
