### ISSUE TITLE
[lgwebos] Use configuration parameter for deviceId instead of Thing ID

### ISSUE THREAD

**Issue by wborn** [openhab/openhab2-addons#3403]
The LGWebOSHandler uses the Thing ID for storing the LG device IDs. 

https://github.com/openhab/openhab2-addons/blob/968ec87e80d782250270992d823590168cee67fe/addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/handler/LGWebOSHandler.java#L232-L234

So if you would use .things files the Thing ID always has to match the LG deviceId. It would be better if the deviceId was stored using a Thing configuration parameter.

That would allow for creating .things files like:

```php
Thing lgwebos:WebOSTV:tv1 [ deviceId="289d7dd9-fe22-40ba-ad2c-2a575e3565f9" ]
Thing lgwebos:WebOSTV:tv2 [ deviceId="82cab4e7-853c-45ab-8cd2-f4cc9db91a0e" ]
```

The resulting .items files would also be more easy to read:

```php
Switch LG_TV1_Mute "TV1 Mute" { channel="lgwebos:WebOSTV:tv1:mute" }
Switch LG_TV2_Mute "TV2 Mute" { channel="lgwebos:WebOSTV:tv2:mute" }
```

**Comment by sprehn** [comment]
Thx, always looking for ways to improve the binding. The change does seem to be straight forward and I am almost done... , except for one thing. How would I migrate existing users to new Thing configuration. This would only be required once when they upgrade the binding version, I guess.

I was thinking to do this in the thing handler's initialize method:
```java
if (!getConfig().containsKey(PROPERTY_DEVICE_ID)) {
            getConfig().put(PROPERTY_DEVICE_ID, getThing().getUID().getId());
}
```
But I am not sure if this configuration change will be persisted.

**Comment by wborn** [comment]
That's excellent @sprehn! :+1: 

You can edit and update configurations in classes extending from BaseThingHandler with:

```java
Configuration configuration = editConfiguration();
configuration.put(key, value);
updateConfiguration(configuration);
```

Though I think you should also make the deviceId a required configuration parameter. But doubt that the framework will then try to create thing handlers for existing things missing the deviceId configuration parameter.

@kaikreuzer what would be the best way to handle such breaking changes?

**Comment by kaikreuzer** [comment]
Well, as users might have their Things defined in files as well, we usually require them to manually adjust or re-create their Things in such cases.

We [have a section in the release notes](https://github.com/openhab/openhab-distro/wiki/openHAB-2.1-Release-Notes#breaking-changes-that-require-manual-interaction-after-the-upgrade) and are also just about to [include those infos in the update script](https://github.com/openhab/openhab-distro/pull/662).

**Comment by sprehn** [comment]
So updateConfiguration(configuration) would probably not work in that case. 
How do I make a config property required?

**Comment by wborn** [comment]
By setting the required attribute to true. 

See for instance the Nest binding:

https://github.com/openhab/openhab2-addons/blob/be4ac388cb113e1ee3b349c050776c8367de4d56/addons/binding/org.openhab.binding.nest/ESH-INF/config/config.xml#L42-L46

See also the Eclipse SmartHome documentation on [configuration descriptions](https://www.eclipse.org/smarthome/documentation/development/bindings/xml-reference.html#xml-structure-for-configuration-descriptions).
