### ISSUE TITLE
[loxone] Miniserver version 9.3 does not connect anymore

### ISSUE THREAD

**Issue by TheSpirit** [openhab/openhab2-addons#3405]
today i update the loxone miniserver to version 9.3.
after that, the openhab binding does not connect anymore.

**Comment by wborn** [comment]
Do you see any warnings or errors in the openHAB log files @TheSpirit?

**Comment by TheSpirit** [comment]
Where are the log files stored?

**Comment by wborn** [comment]
It depends on what kind of installation method you are using, see also [Logging in openHAB](https://docs.openhab.org/administration/logging.html):

> ## File System
>
> Log files are written to either `userdata/log` (manual setup) or `/var/log/openhab2` (apt/deb-based setup) and can be accessed using standard OS tools for text files. The default installation of openHAB generates two log files:
>
> - `events.log`
> - `openhab.log`

**Comment by ppieczul** [comment]
@TheSpirit Can you confirm this works fine with 2.3 version?
