### ISSUE TITLE
[homematic] binding error message

### ISSUE THREAD

**Issue by maxx92** [openhab/openhab2-addons#3407]
[homematic] I get following reoccuring error message from all of my thermostats:
2018-03-28 12:16:09.629 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint '000A9709A0DD01:1#QUICK_VETO_TIME'

## Expected Behavior
There should be no poll of a parameter that does not exist

## Current Behavior
see above

## Possible Solution
see above

## Steps to Reproduce (for Bugs)

1. item: Homematic IP Wandthermostat mit Luftfeuchtigkeitssensor (HmIP-WTH-2)
2. channels used: set_point_temperature and actual_temperature

## Your Environment
Raspberry Pi 3
openHAB 2.2.0-1
homematic binding 2.2.0
openjdk version 1.8.0_152

**Comment by Zippochonda** [comment]
What is the Solution? Having the same behavior...

**Comment by maxx92** [comment]
If I remember correctly, this happens after updating the firmware on the thermostat. I think, only relearning the device in OH gets it fixed.
