### ISSUE TITLE
[KNX] color channel type (DPT 232.600) does not exist yet

### ISSUE THREAD

**Issue by FredericMa** [openhab/openhab2-addons#3411]
In KNX1 DPT 232.600 exists to send RGB values (3 bytes) to my LED controllers.
DPT 232.600 and the related color channel type is currently not available in KNX2.

**Comment by lewie** [comment]
@FredericMa, of course, all 232.xxx DTP's are mapped!  (232.600 is currently the only one in 232.xxx Group)

[KNXCoreTypeMapper Line 518:](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapper.java)
```
        /**
         * MainType: 232
         * 232.600: RGB, values: 0 0 0...255 255 255, r g b
         */
        dptMainTypeMap.put(232, HSBType.class);
        /** Exceptions Datapoint Types "RGB Color", Main number 232 */
// Example: dptTypeMap.put(DPTXlatorRGB.DPT_RGB.getID(), HSBType.class);
```

`dptMainTypeMap.put(232, HSBType.class);` is the default 'MainType' mapping to `HSBType` for all `232.xxx` DPT's beginning with `232.`. 
If later a DPT of this 'MainType' Group, does not fit with `HSBType`, it can be mapped to another type by putting it to dptTypeMap.

**Comment by FredericMa** [comment]
@lewie, indeed, I've also seen that code in the KNXCoreTypeMapper but at the moment there is no channel type available that I can use to link my Color items to.
Or am I missing something?

**Comment by FredericMa** [comment]
@lewie did you manage to get a look at this issue?
No stress, just curious :-)

**Comment by wborn** [comment]
Is this issue fixed for you @FredericMa?

**Comment by wborn** [comment]
Upon closer inspection I see that the PR that referenced this issue was never merged.
Looking at the day of the PR it could have been an April 1st joke. :wink:

**Comment by kaikreuzer** [comment]
Haha, yeah, just like the sentence " I soon will do a PR for all missing channels" - ping @lewie!

**Comment by FredericMa** [comment]
Haha, possible, I didn't even notice it 😀
But the PR itself seems legit to me!

**Comment by FredericMa** [comment]
@wborn is there a possibility to merge PR #3433 anyway so we can close this issue?
I checked the PR and I guess it was ready to be merged but @lewie closed it after making the changes from the code review.

**Comment by lewie** [comment]
@FredericMa, yes, that is annoying. I will handle as soon as possible.

**Comment by FredericMa** [comment]
@lewie no problem thanks for the response!

**Comment by FredericMa** [comment]
There is still an issue with the color as reported here in the PR: https://github.com/openhab/openhab2-addons/pull/3433#issuecomment-424668115

**Comment by FredericMa** [comment]
The error I'm facing is:
`2018-10-24 20:36:37.650 [DEBUG] [.internal.handler.DeviceThingHandler] - None of the configured GAs on channel 'knx:device:MDTIP:Ledcontroller3:LedColor' could handle the command '0.000000,67.796616,46.274509' of type 'HSBType'`

The thing is configured like this:
`Type color : LedColor [ hsb="232.600:0/5/7", switch="1.001:0/5/6" ]`

As far as I know it is configured correctly...

**Comment by FredericMa** [comment]
@lewie have you had the time to take a look at this?
Thanks!

**Comment by lewie** [comment]
@FredericMa, 
[it still works?! ](https://github.com/openhab/openhab2-addons/pull/4207) Then You can close this issue! 😉

**Comment by FredericMa** [comment]
@lewie 
It would be weird if it didn't work anymore now 😄
Thanks! Closing it!
