### ISSUE TITLE
[backup/restore] Binding installations are not restored from backup

### ISSUE THREAD

**Issue by tlc76** [openhab/openhab2-addons#3412]
## Expected Behavior
openhab2 backup/restore scripts should save entire openhab2 configuration

## Current Behavior
Bindings are not restored (no bindings appear "installed" after a restore performed on a fresh openhabian/openhab2 installation). As a consequence, all things are found in "Uninitialized" state.
The issue is resolved by:
- manually installing the bindings from Paper UI
- restarting openhab2 service (sudo service openhab2 restart)
- result: things are now fully functional, in "Online" state

## Steps to Reproduce (for Bugs)
1. backup performed on raspbian pi, openhab2 version 2.2
2. script used: $OPENHAB_HOME/runtime/bin/backup
3. fresh installation of openhabian on a different sd card
4. restore performed on the fresh openhabian os from the backup archive saved at step 1

## Context
issue occurred when performing backup/restore from raspbian to openhabian

## Your Environment
1. system at backup: sd card #1: raspbian + openhab2 v2.2 (installed via apt-get around 20-March-2018)
2. system at restore: sd card #2: openhabianpi-raspbian-201712171718-git30faec3-crccc053823.img.xz

**Comment by kaikreuzer** [comment]
Thanks for the report! May I ask you to submit it at https://github.com/openhab/openhab-distro/issues as this is where the backup script is maintained?

**Comment by tlc76** [comment]
I noticed right after submitting the issue that I've reported it in the wrong place :)
Thanks for posting the good location - job done!
