### ISSUE TITLE
Xiaomi Mi Smart Home Gateway - Error when trying to play sound or set illumination

### ISSUE THREAD

**Issue by AlessandroAU** [openhab/openhab2-addons#3413]
Using Xiaomi home gateway v3 which appears to be properly configured I get the following errors when trying to play a sound or set the led brightness/color on the gateway.

Furthermore, and unsure if related: I can't trigger anything with Xiaomi switch with the example rules, but the temperature/humidity sensor works fine.

Using 2.2.3 build #1244
Same problem in 2.2 stable release

![ohxierror](https://user-images.githubusercontent.com/22009829/38135012-277fdb10-3459-11e8-9db7-703568e065cb.PNG)
![ohxierror1](https://user-images.githubusercontent.com/22009829/38135013-2872cba4-3459-11e8-8faf-816784a3e6a6.PNG)
![ohxierror2](https://user-images.githubusercontent.com/22009829/38135015-2989365e-3459-11e8-9cae-00dbe695e509.PNG)

**Comment by dimalo** [comment]
Hi @AlessandroAU 
Thanks for the feedback and screenshots!
Looks like you have no dev key entered which is required to be able to write commands. Reading states is possible without...
There are a couple of issues in the pipeline at the moment regarding the NPE when the key or the token are missing. I’ll fix these in the near future.
Please make sure you have the dev key properly configured and the binding is receiving the cyclic heartbeat messages from the gateway containing the token (via debug logging).
Thanks!

**Comment by AlessandroAU** [comment]
Hi Dimalo,
Thanks for the quick reply ! :)
I believe I have entered the DEV key correctly, is this the only place it is required?
![xiaomihubthings](https://user-images.githubusercontent.com/22009829/38135996-bd63bbe2-345e-11e8-8d34-e7b2e2c7e9b4.PNG)

What should I set the log filter to see the heartbeat messages? I have a lot going on in my log when I set debug mode

Regards,
Alessandro

**Comment by dimalo** [comment]
Hi @AlessandroAU,
your config looks good. no need to put the key somewhere else.
basically I meant to activate debug logging only for this binding.
log in to [Karaf console](https://docs.openhab.org/administration/console.html) and set higher logging level for the binding:
```log:set DEBUG org.openhab.binding.mihome```

**Comment by stas-dovgodko** [comment]
Mi gateway uses not routed multicast, so your gateway and OH *should* be in the same network segment, 255.255.255.0 for example. Found the same problems when my gw was 192.168.1.x and OH 192.168.0.x

**Comment by AlessandroAU** [comment]
Thanks Stas,

It was indeed an error with multicast packets not being forwarded between subnets. A pity that's how the gateway works, makes it hard to isolate from other devices. 

Thanks all :)
