### ISSUE TITLE
[dlinksmarthome] Depends on Full JRE

### ISSUE THREAD

**Issue by svilenvul** [openhab/openhab2-addons#3417]
Looking at the report generated by https://github.com/openhab/static-code-analysis/pull/283, I see that several packages in dlinksmarthome binding depend on ` javax.xml.soap`:

- org.openhab.binding.dlinksmarthome.internal 
- org.openhab.binding.dlinksmarthome.internal.motionsensor

This is a violation of C.1 in the openHAB coding guidelines https://docs.openhab.org/developers/development/guidelines.html#c-language-levels-and-libraries.

It will be good if we can refactor it, so the bundle remains restricted to Compact Profile 2, or if it is not possible document that the binding is an exception.

**Comment by davidgraeff** [comment]
Because with Java 9+ there are basically no compact profiles anymore.
Everything is added via separate libraries and with the bnd migration we are also Java 11 compatible now, so including those libraries for just those addons that need it.
Closing this now.
