### ISSUE TITLE
[helios] Depends on Full JRE

### ISSUE THREAD

**Issue by svilenvul** [openhab/openhab2-addons#3418]
Looking at the report generated by https://github.com/openhab/static-code-analysis/pull/283, I see that several packages in helios binding depend on Full JRE:

- org.openhab.binding.helios.handler depends on javax.jws (Full JRE)
- org.openhab.binding.helios.handler depends on javax.xml.bind (Full JRE)
- org.openhab.binding.helios.handler depends on javax.xml.ws (Full JRE)
- org.openhab.binding.helios.handler depends on javax.xml.ws.soap (Full JRE)
- org.openhab.binding.helios.handler depends on javax.xml.ws.wsaddressing (Full JRE)
- org.openhab.binding.helios.internal.ws.soap depends on javax.xml.bind (Full JRE)
- org.openhab.binding.helios.internal.ws.soap depends on javax.xml.bind.annotation (Full JRE)
- org.openhab.binding.helios.internal.ws.soap depends on javax.xml.bind.annotation.adapters (Full JRE)
- org.openhab.binding.helios.internal.ws.soap depends on javax.xml.soap (Full JRE)
- org.openhab.binding.helios.internal.ws.soap depends on javax.xml.ws.handler (Full JRE)
- org.openhab.binding.helios.internal.ws.soap depends on javax.xml.ws.handler.soap (Full JRE)

This is a violation of C.1 in the openHAB coding guidelines https://docs.openhab.org/developers/development/guidelines.html#c-language-levels-and-libraries.

It will be good if we can refactor it, so the bundle remains restricted to Compact Profile 2, or if it is not possible document that the binding is an exception.

**Comment by kgoderis** [comment]
@svilenvul I am afraid that refactoring is not an option for this binding, because of the WS-* services used by the helios devices.

**Comment by davidgraeff** [comment]
I think that's fine for bindings as long as the user knows of it upfront. Can this be added to the readme?
