### ISSUE TITLE
[rfxcom] Depends on Full JRE

### ISSUE THREAD

**Issue by svilenvul** [openhab/openhab2-addons#3424]
Looking at the report generated by https://github.com/openhab/static-code-analysis/pull/283, I see that several packages in rfxcom binding depend on Full JRE:

- org.openhab.binding.rfxcom.handler depends on javax.xml.bind (Full JRE)
- org.openhab.binding.rfxcom.internal.connector depends on javax.xml.bind (Full JRE)
- org.openhab.binding.rfxcom.internal.messages depends on javax.xml.bind (Full JRE)

This is a violation of C.1 in the openHAB coding guidelines https://docs.openhab.org/developers/development/guidelines.html#c-language-levels-and-libraries.

It will be good if we can refactor it, so the bundle remains restricted to Compact Profile 2, or if it is not possible document that the binding is an exception.

**Comment by martinvw** [comment]
Checking the code here looks hopeful it seems to be caused by DatatypeConverter I believe printf or String.format can do something similar

**Comment by martinvw** [comment]
@kaikreuzer the code for the functionality (convert byte arrays to a hexadecimal string) we use is non trivial so ideal I would add it somewhere in ESH, what do you think that a proper place would be in esh or can we add commons codec as a dependency for ESH...

**Comment by kaikreuzer** [comment]
> convert byte arrays to a hexadecimal string

Sounds just like [this](https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/util/HexUtils.java#L38), doesn't it?

**Comment by martinvw** [comment]
@kaikreuzer I needed a small extension and some time to dust of my smarthome checkout :-)

https://github.com/eclipse/smarthome/pull/5331
