### ISSUE TITLE
[tellstick] Depends on Full JRE

### ISSUE THREAD

**Issue by svilenvul** [openhab/openhab2-addons#3425]
Looking at the report generated by https://github.com/openhab/static-code-analysis/pull/283, I see that several packages in tellstick binding depend on Full JRE:

- org.openhab.binding.tellstick.internal.live depends on javax.xml.bind (Full JRE)
- org.openhab.binding.tellstick.internal.live.xml depends on javax.xml.bind.annotation (Full JRE)
- org.openhab.binding.tellstick.internal.live.xml depends on javax.xml.bind.annotation.adapters (Full JRE)

This is a violation of C.1 in the openHAB coding guidelines https://docs.openhab.org/developers/development/guidelines.html#c-language-levels-and-libraries.

It will be good if we can refactor it, so the bundle remains restricted to Compact Profile 2, or if it is not possible document that the binding is an exception.

**Comment by davidgraeff** [comment]
Closing as invalid. `javax.xml.bind` is no longer part of the JDK (starting with Java 9 I think) but a separate EE library. bindings are allowed to link to external libraries without restrictions.
