### ISSUE TITLE
[marytts] Depends on Full JRE

### ISSUE THREAD

**Issue by svilenvul** [openhab/openhab2-addons#3428]
Looking at the report generated by https://github.com/openhab/static-code-analysis/pull/283, I see that one package in marytts bundle depends on Full JRE:

- org.openhab.voice.marytts.internal depends on javax.sound.sampled (Full JRE)

This is a violation of C.1 in the openHAB coding guidelines https://docs.openhab.org/developers/development/guidelines.html#c-language-levels-and-libraries.

It will be good if we can refactor it, so the bundle remains restricted to Compact Profile 2, or if it is not possible document that the binding is an exception.

**Comment by kaikreuzer** [comment]
MaryTTS is anyhow huge, so I would vote for treating this as an exception.
@svilenvul What do you think would be the best place to document this? Shall we simply add an exclude for this check?

**Comment by svilenvul** [comment]
I will add the exclusion.

I could not find appropriate place to document this exception in the openHAB documentation. (if it is included only in the filter, we will forget about it :) ) 

Does it make sense to open a discussion in https://github.com/openhab/openhab-docs for that.

**Comment by kaikreuzer** [comment]
> Does it make sense to open a discussion in https://github.com/openhab/openhab-docs for that.

No - openHAB itself anyhow requires a full JRE. The compatibility with CP2 is there in order to keep the add-ons fully compatible with ESH so that they potentially could be moved over there.
So having this information somewhere in the addon itself (e.g. by an exclusion in the pom) is imho enough.
