### ISSUE TITLE
[gardena] rechargeable_battery_status cannot be updated / new mower_stats

### ISSUE THREAD

**Issue by petmet** [openhab/openhab2-addons#3457]
Hi,
Gardena has removed the property "rechargeable_battery_status" from the mower battery properties.
The binding writes this warning every time it refreshes:
`2018-04-06 19:45:59.929 [WARN ] [.gardena.handler.GardenaThingHandler] - Channel 'gardena:mower:home:rasenmaeher:battery#rechargeable_battery_status' cannot be updated as device does not contain property 'battery:rechargeable_battery_status'
`
(I recently did an update of the gateway and mower. Maybe it's only missing in the new version.)

Additionally I found new interesting mower stats in the Gardena service:
<pre>        {
          "properties": [
            {
              "writeable": false, 
              "name": "cutting_time", 
              "timestamp": "2018-04-06T11:44:06.338Z", 
              "supported_values": [], 
              "value": 508, 
              "id": "xxx", 
              "unit": "h"
            }, 
            {
              "writeable": false, 
              "name": "charging_cycles", 
              "timestamp": "2018-04-06T16:44:06.274Z", 
              "supported_values": [], 
              "value": 418, 
              "id": "xxx"
            }, 
            {
              "writeable": false, 
              "name": "collisions", 
              "timestamp": "2018-04-06T16:59:05.483Z", 
              "supported_values": [], 
              "value": 51177, 
              "id": "xxx"
            }, 
            {
              "writeable": false, 
              "name": "running_time", 
              "timestamp": "2018-04-06T11:44:06.274Z", 
              "supported_values": [], 
              "value": 525, 
              "id": "xxx", 
              "unit": "h"
            }
          ], 
          "type": "robotic_mower_stats", 
          "id": "xxx", 
          "name": "mower_stats"
        }</pre>

Please remove the old property and add the new ones.

Thank you very much &
Best regards,
Peter
PS: I am running openHAB 2.2.0 Release Build with docker.

**Comment by dworan** [comment]
I have the same problem! Do you already have a solution? Can I change that myself?

**Comment by petmet** [comment]
I changed the gardena binding yesterday and built it for openhab-2.2.x.
- I removed the gardena binding from paper-ui
- copied the jar from the attached zip archive to the addons folder of my openhab installation
- and restarted openhab

I also added a diff-file with my changes:
- removed rechargeable_battery_status
- added timestamp_last_error_code
- added mower_stats
- added scheduling for watering_computer

[openhab-gardena.zip](https://github.com/openhab/openhab2-addons/files/1944411/openhab-gardena.zip)

**Comment by davidgraeff** [comment]
Please provide changes back to the community!
