### ISSUE TITLE
[homekit] Can't pair

### ISSUE THREAD

**Issue by Uspinhal** [openhab/openhab2-addons#3466]
I’m binding Home Kit on OH2.2 and first it´s working properly, but I disconect my network a few hours and now it doesn’t work anymore.

## Current Behavior
I’m binding homekit on OH2.2 and first it´s working properly, but I disconect my network a few hours and now it doesn’t work anymore.
I’m rebbot OH and reinstall homekt binding and ain’t work.
On the log file says that som file on /var/lib/openhab2/cache/org.eclipse,osgi/241 is missing, but there’s not this folder there.
I just really don’t know what’s is happening and what file is that.
Anyone has any clue about how can I fix this?

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Version used: (e.g., openhab and addon versions)
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):

**Comment by J-N-K** [comment]
Please check if this is still the case with a recent version of OH (i.e. 2.5 SNAPSHOT >= 1601).

**Comment by J-N-K** [comment]
no response, old OH version
