### ISSUE TITLE
javascript to raspberry pi 3B openhab2

### ISSUE THREAD

**Issue by mechelman** [openhab/openhab2-addons#3469]
## Context
Can someone please help me with a struggle.
my struggle is this.
I have some java programmes on my pc and I don't know how to let them work on my raspberry pi openhab2. If someone can help me I would like that.
thank you for your time.

## Your Environment
Environment
openhab2, java8, Windows 10, Raspbian, Jessie,PC

**Comment by kaikreuzer** [comment]
Please use our community at http://community.openhab.org/ for general support - thanks!
