### ISSUE TITLE
[GPIO] need help with GPIO binding on openhab2

### ISSUE THREAD

**Issue by jcl06** [openhab/openhab2-addons#3484]
Hi,
I tried to follow the guide on OPENHAB manual to bing GPIO but no luck. seems the guide is for OPENHAB1 as i'm stuck on how to make it work. Appreciate you help.

https://docs.openhab.org/addons/bindings/gpio1/readme.html

**Comment by kaikreuzer** [comment]
Please use our forum for support: https://community.openhab.org/
