### ISSUE TITLE
[network] servicedevice interprets ConnectException as device present

### ISSUE THREAD

**Issue by jsichi** [openhab/openhab2-addons#3499]
I have various switches defined corresponding to TCP services (not machines) whose running/stopped state I use for monitoring and automation.  I set these up a while ago, back before the split between pingdevice and servicedevice in the network binding.  At that time, I simply specified the IP and port to check, and everything worked well.

Later, when I upgraded to a newer version with the pingdevice/servicedevice split in the network binding, I changed the corresponding things/items to use servicedevice.  However, after that, these services always showed up as ON, even when there was no service listening on the corresponding port.  So my monitoring stopped working.

I tracked this down to the following code:

https://github.com/openhab/openhab2-addons/blob/2d34fd115fa279c34014f8c168076aac3634b257/addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/utils/NetworkUtils.java#L157

The comment "Connection refused, there is a device on the other end though" for ConnectException explains the current behavior.  But I think this interpretation is incorrect; we should not be looking for a device or open firewall port; we should be looking for a listening service.

## Expected Behavior

Given this thing/item pair:

```
network:servicedevice:central_http [ hostname="10.0.0.185", port=8081, retry=3 ]

Switch central_http "Central HTTP" <network> (gServices) { channel="network:servicedevice:central_http:online" }
```

I expect the state of item central_http be ON if there is a service listening on http://10.0.0.185:8081, and OFF otherwise.

## Current Behavior

The current behavior is that the item is always ON, as long as the corresponding port is not firewalled, regardless of whether the corresponding web server is running.

## Possible Solution

The obvious fix would be to change the servicePing switch statement referenced above to return false instead of true for the ConnectException case.

If there's a reason for wanting to distinguish ConnectException from NoRouteToHostException and SocketTimeoutException, then it should at least be made configurable so that we can restore the old behavior.

## Steps to Reproduce

Define a thing/item pair similar to the example given in the Expected Behavior section above, and point to a port on an existing machine which is open on the machine's firewall, but with no service listening.  The item state will always be ON.

## Context

I use this monitoring for knowing when there's a problem with one of the services on my network and automating corrective action such as restarting the service or rebooting the server.

## Your Environment

* Openhab 2.2.0-1
* Java 1.8.0_111
* Operating System and version:  Ubuntu 17.10

**Comment by martinvw** [comment]
@davidgraeff

**Comment by davidgraeff** [comment]
Yes the bindings task shifted a little from network health to presence detection. But I agree that the default behaviour should be changed for service device.
