### ISSUE TITLE
Network binding does not read cfg file.

### ISSUE THREAD

**Issue by AntonWedemeier** [openhab/openhab2-addons#3502]
## Expected Behavior
The network binding should read a cfg file as described inside the documentation: 
https://docs.openhab.org/addons/bindings/network/readme.html
E.g. you can specify the location of a arping program.

## Current Behavior
I expect a cfg file to be read.
Especially I want the specify the path to the arping tool. (Setting $PATH does not work either).

## Context
I tried several locations and names for this cfg file but it had never an effect on the network binding. Only changing the options with the PaperUI did the trick. I tested this on a windows pc.
I tested this during an investigation to an other problem, ping on a windows pc, which is solved.
https://community.openhab.org/t/windows-ping-does-not-work-correct/43776/25

## Your Environment
I tested on windows 10 with the latest snapshot, but the problem started with version 2.2. with the changed concept of the binding.

**Comment by wborn** [comment]
It looks like the documentation needs to be updated. I tested this with the latest 2.3.0-SNAPSHOT and what seems to work in that version is adding configuration lines to /conf/services/runtime.cfg, e.g.:

```
binding.network:allowSystemPings=true
binding.network:arpPingToolPath=/usr/bin/arping
```

You can also configure these settings in Paper UI via Configuration > Bindings > Network Binding (edit button on the right)

**Comment by AntonWedemeier** [comment]
@wborn That is what I would expect. But with me this does not work.

I do not know if this helps but I see (on my windows pc):
* the contents of the conf\services\runtime.cfg is copied to userdata\config\org\openhab\network.config
* the settings in the PaperUI are copied to userdata\config\binding\network.config
Changes inside the conf\services\runtime.cfg does not reflect to the settings in the PaperUI.
The settings from the PaperUI are used by the network-binding.
(The binding works for me when I directly change the file userdata\config\binding\network.config, but  a user should not edit these files directly,)

**Comment by wborn** [comment]
It looks like in 2.2.0 the configurationPid does not follow the standard naming scheme which was corrected in 2.3.0-SNAPSHOT with https://github.com/openhab/openhab2-addons/commit/14e4d62ac6707047b20a0e9c7a631887333ef500#diff-23449d2f3ae699a3ed68800c8f50410dR35. 

Can you test if it works as expected in 2.3.0-SNAPSHOT?

**Comment by AntonWedemeier** [comment]
I already did. I used the most recent version of 19 april in which the windows ping is corrected.
See: [I tested this during an investigation to an other problem, ping on a windows pc, which is solved.
https://community.openhab.org/t/windows-ping-does-not-work-correct/43776/25]()

**Comment by wborn** [comment]
I had a look at the JAR file in that thread and the OSGI-INF directory in the JAR also contains a `NetworkHandlerFactory.xml` which is not using `configuration-pid="binding.network"`. So when ESH is using that factory it might not use the right configuration. 

You might want to try if it works when you remove that file from the JAR or use a recently generated 2.3.0-SNAPSHOT JAR from the build server.

The JAR also contains `org.openhab.binding.network.internal.NetworkHandlerFactory.xml` which does have the right configuration PID.

**Comment by AntonWedemeier** [comment]
I did just what you asked. With 7zip I removed NetworkHandlerFactory.xml from OSGI-INF. Restarted openHAB. I did not see any change. 

A question: is my assumption correct, that the PaperUI and the network.cfg file both must result in the same network.config file (in userdata\config\org\openhab\network.config)?

Perhaps I have more time this afternoon to look into this.

**Comment by AntonWedemeier** [comment]
I tried to use the eclipse environment to look into the problem. But this environment seems to work differently from the normal operation. I never saw a network.config file created.
And I am not experienced enough to solve this issue.

**Comment by wborn** [comment]
> A question: is my assumption correct, that the PaperUI and the network.cfg file both must result in the same network.config file (in userdata\config\org\openhab\network.config)?

There's only a `userdata/config/binding/network.config` file on my test instance. It does not exist in `userdata/config/org/openhab`.

I did some testing with additional logging to the binding and in my setup the configuration was properly applied. However there is an issue with the boolean configuration parameters for which I've created a PR https://github.com/eclipse/smarthome/pull/5443. 

Do you also see a similar [exception](https://github.com/eclipse/smarthome/pull/5443#issue-183380660) logged @AntonWedemeier? I had to remove the network.config from userdata to remove the boolean configuration parameters.

**Comment by AntonWedemeier** [comment]
On my windows pc I have a network.cfg file inside the folder \conf\services with values for allowDHCPlisten, allowSystemPings, arpPingToolPath and cacheDeviceStateTimeInMS. When I start openHAB the contents of this file is copied to a file network.config inside \userdata\config\org\openhab.

On the running openHAB program I go to localhost and into the PaperUI. At that moment the network.config file appears inside \userdata\config\binding. It has two lines. If I change values of the binding and save, the contents gets four more lines with the parameters mentioned above.

When I look at the parameter values given in the PaperUI for the network binding they are not the values I set in my network.cfg file. When I change values inside the network.config created by the PaperUI these values are used for the network binding.

**Comment by AntonWedemeier** [comment]
> I did some testing with additional logging added to the binding and in my setup the configuration was properly applied. However there is an issue with the boolean configuration parameters for which I've created a PR eclipse/smarthome#5443.
> Do you also see a similar exception logged @AntonWedemeier? I had to remove the network.config from userdata to remove the boolean configuration parameters.

I did not had such an exception message. But I found out how to force it.
As said my network.cfg file is not used, so I use the network.config file generated through the PaperUI.
Inside this network.config file a line looks like: 
allowSystemPings=B"false"
Using this file I just changed "false" into "true" ore something like that.
Now I tried to remove the letter B. Then I got the same exception message that you mentioned. So at least inside the network.config file the letter 'B' seams to be nescessary for a boolean vale.
Hope that this helps you.

**Comment by wborn** [comment]
When I add a separate configuration file `conf/services/network.cfg` with content:

```
binding.network:cacheDeviceStateTimeInMS=1234
binding.network:arpPingToolPath=/usr/bin/arping
```

and start openHAB, the `userdata/config/org/openhab/network.config` file is created with content: 

```
_felix_.cm.newConfiguration=B"true"
service.pid="org.openhab.network"
```

and a `userdata/config/binding/network.config` file is created with content:

```
arpPingToolPath="/usr/bin/arping"
cacheDeviceStateTimeInMS="1234"
service.pid="binding.network"
```

* Paper UI and some logging I added to the binding both show that the right configuration values are used.  
* When openHAB is running and when I edit and save `conf/services/network.cfg` the Paper UI and the logging show that the updated values are used. The `userdata/config/binding/network.config` file is also updated.
* When changing the configuration via Paper UI these changes are stored in `userdata/config/binding/network.config`. The settings in `conf/services/network.cfg` are reapplied to  `userdata/config/binding/network.config` when restarting the runtime.

To be able to use boolean configuration values in network.cfg, there first needs to be a new ESH stable build with https://github.com/eclipse/smarthome/pull/5443. The default value of allowSystemPings and allowDHCPlisten is `true`.

So I'm unable to reproduce your issue with the latest openHAB 2.3.0-SNAPSHOT build. If you still have issues, maybe you can retest this on a new 2.3.0-SNAPSHOT installation that does not use the custom JAR from the thread?

I'll create a PR to update the binding documentation.

**Comment by AntonWedemeier** [comment]
> When I add a separate configuration file conf/services/network.cfg with content: ...

I do not use binding.network: in front of the parameters, but I tested that it makes no difference.

> and start openHAB, the userdata/config/org/openhab/network.config file is created with content:

Yes, i got the same

> and a userdata/config/binding/network.config file is created with content:

With me the contents of the network.cfg file is copied to a network.config file, but inside 
\userdata\config\org\openhab. In this directory almost all my cfg-files appear as config files (addons, basisui, logging, etc.). This is where we differ.

The PaperUI looks for the network.config in \userdata\config\binding. And when it does not find it, it creates a new one. Changing this new file does reflect in the PaperUI.

> If you still have issues, maybe you can retest this on a new 2.3.0-SNAPSHOT installation that does not use the custom JAR from the thread?

I already did that, because I got 2 network-bindings, one from the kar-file (dated 4 april) and one added by me. Therefore I removed the added binding already.

> So I'm unable to reproduce your issue with the latest openHAB 2.3.0-SNAPSHOT build.
 
If you can not reproduce my issue we can stop this. As I said in my thread about the ping problem, the issue is no big deal for me; I just change the network.config created by the PaperUI directly. 

I will try again after a few weeks when all the changed of the binding are merged inside a new snapshot.

Thank you for looking into this.
Sorry I can not make up my messages like you (with path grayed etc). I did not find out how to do that (yet).

**Comment by wborn** [comment]
> The binding.network: prefix is necessary see also the ESH documentation.

As the documentation also states, when the file is named `binding.network.cfg` you can omit the `binding.network:` prefix. I tested this and it also works.

**Comment by AntonWedemeier** [comment]
Strange, but you pointed me in the right direction.
I put an extra line at the beginning of the network.cfg file:
`pid:binding.network`
Now the network binding works correctly.
Without the line it goes wrong.

I do not understand exactly from your last entries what it does or what you fixed.
But for now it works.

**Comment by AntonWedemeier** [comment]
A last question. Even after almost complete removing the custom jar-file from my computer, it keeps coming back.
When I do a bundle:list I keep seeing two network bindings.
Is there some (hidden) place where OH2 stores a binding?

**Comment by wborn** [comment]
Great that you got it working by adding the PID.

Yes it keeps track of what bundles are installed and may also download missing JARs from the Internet again.

When you add a JAR to the addons directory without first removing the original binding via the UI you  get two bundles for the same binding. The first installed bundle will be active whereas the other is not. You can also remove bundles using the console. 

If you see the following with `bundle:list`  :

```
START LEVEL 100 , List Threshold: 50
 ID │ State    │ Lvl │ Version                │ Name
────┼──────────┼─────┼────────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 15 │ Active   │  80 │ 5.3.1.201602281253     │ OSGi JAX-RS Connector
 16 │ Active   │  80 │ 2.4.5                  │ Jackson-annotations
...
203 │ Active   │  80 │ 0.9.10.v20160429-1435  │ reflections (wrap)
204 │ Active   │  80 │ 1.5.8.v20160511-1038   │ swagger-jersey2-jaxrs (wrap)
205 │ Active   │  80 │ 2.3.0.201804241554     │ Network Binding
```

You can then remove the network binding with: `bundle:uninstall 205`

After executing that command it should still be possible to reinstall the binding again using Paper UI.
It will keep reinstalling JARs that are part of the `addons` directory so remove them if you don't want that.
