### ISSUE TITLE
TCP-binding updates item more then one time if data received

### ISSUE THREAD

**Issue by HomeOfSourceCode** [openhab/openhab2-addons#3508]
I configured udp binding to receive a string item by doing this:
String item tcp="<[192.168.0.2:3000:'REGEX((.*))']"

## Expected Behavior
If a packet received from 192.168.0.2:3000 the regex will handle the datas and at the end put them into the string.

## Current Behavior
String item data gets data update before REGEX and a second time after REGEX. This causes two changed trigger for rules. If I use String item tcp="<[192.168.0.2:3000:default]" only one update to String item.

And a second problem. Sometimes the trigger "Item xxx received update" is triggered a lot of times. Only one packet is arrived but the rule is tirggered up to 10 times within a second.

## Possible Solution
no idea

## Steps to Reproduce (for Bugs)
I use udp test tool at windows. I send one udp packet to OH udp binding and have a very simple rule
Item:
String item udptext {tcp="<[192.168.0.2:3000:'REGEX((.*))']"}

rule "udp update check"
when
 Item udptext received update
then
 logInfo("Logger", udptex.state.toString)
end

## Your Environment
OH 2.2 stable
Windwos 10 Home 32bit, current java version

**Comment by martinvw** [comment]
The TCP binding originates from version 1.x, it its maintained outside this repo. Can you check whether your issues has been reported and otherwise report it at:

https://github.com/openhab/openhab1-addons/issues
