### ISSUE TITLE
[onkyo] Volume dB support for newer Pioneer AVRs (e.g. VSX-1131)

### ISSUE THREAD

**Issue by hebs1** [openhab/openhab2-addons#3509]
## Expected Behavior
Newer Pioneer AVRs (since 2015) also works with Onkyo protocol. But volume control works different to Onkyo: AVRs have a volume range from -82dB to 0dB and cannot controlled with the existing volume channels of the Onkyo binding (e.g. onkyo:onkyoAVR:myavr:zone1#volume) because type dimmer doesn't fit to this values.
## Current Behavior
With current volume dimmer you can only set volume from -82dB (decimal 0, hex 00) to -32dB (decimal 100, hex 64).
## Possible Solution

My proposal is to add new channels "volumedb" as type number (for all three zones) and to convert the volume in OnkyoHandler.java.

I successfully tested it with my Pioneer VSX-1131. Necessary adjustments in the following files:
org.openhab.binding.onkyo_pioneer\README.md
org.openhab.binding.onkyo_pioneer\ESH-INF\thing\channel-groups.xml
org.openhab.binding.onkyo_pioneer\ESH-INF\thing\channels.xml
org.openhab.binding.onkyo_pioneer\ESH-INF\thing\vsx-1131.xml (new file)
org.openhab.binding.onkyo_pioneer\src\main\java\org\openhab\binding\onkyo\OnkyoBindingConstants.java
onkyo_backup\org.openhab.binding.onkyo_pioneer\ESH-INF\config\config.xml
onkyo_backup\org.openhab.binding.onkyo_pioneer\src\main\java\org\openhab\binding\onkyo\handler\OnkyoHandler.java
onkyo_backup\org.openhab.binding.onkyo_pioneer\src\main\java\org\openhab\binding\onkyo\internal\config\OnkyoDeviceConfiguration.java

## Steps to Reproduce (for Bugs)
n/a
## Your Environment
* Version used: openhab-distro and openhab2-addons
* Environment name and version: Chrome 65, Java 8 Version 162
* Development environment: Eclipse IDE for Java Developers Version: Oxygen.3 Release (4.7.3)
* Operating System: Windows 10

**Comment by hechtersheim** [comment]
Exactly the same issue here with my pioneer VSX-932. Would be nice to be able turn the volume higher.

**Comment by CodingSpiderFox** [comment]
Would be great if this makes it into the next release

**Comment by cweitkamp** [comment]
Hi all,

Can you please check if #4223 is a possible solution for your issue? Thanks.

**Comment by hebs1** [comment]
Hi Christoph,
solution works well - thank you very very much!!!

**Comment by hebs1** [comment]
Hi Christoph,
the new setting Volume Scale "0-100 in 0.5 steps" works well but I think I found one little issue:
the volume dimmer scale 0-100 allows only steps of 1 (e.g. 36 37 38) but now 0.5 steps are necessary (e.g. 36,0 36,5 37,0 37,5 38,0).

**Comment by cweitkamp** [comment]
@hebs1 Thanks for testing. I see what you mean.

@cguedel Can you check this out?

https://github.com/cguedel/openhab2-addons/blob/c957191500646647381e7ed676a413964b05b48e/addons/binding/org.openhab.binding.onkyo/ESH-INF/thing/channels.xml#L53-L59

**Comment by cguedel** [comment]
Well, I guess the step would need to be dynamically adjusted based on the scaling setting. Is that even possible?

**Comment by cweitkamp** [comment]
It is. You can implement a `DynamicStateDescriptionProvider` which allows you to modify the state options for a channel (see [Kodi](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/KodiDynamicStateDescriptionProvider.java) for an example). Do you think it is worth the effort? Maybe simply remove the step definition?

**Comment by cguedel** [comment]
I'll try and give it a shot, if I don't succeed in a reasonable amount of time, I'll remove the step property

**Comment by cguedel** [comment]
@cweitkamp Sorry it took so long. In the end, I gave up on implementing this dynamically, because I'm no longer using an onkyo AVR anyway. Find the PR to remove the step size here: https://github.com/openhab/openhab2-addons/pull/4799

**Comment by cweitkamp** [comment]
@cguedel Thanks for investing your time to find a solution for this issue. Imho removing the `step` value is sufficient for now.
