### ISSUE TITLE
[network] Arping not reported properly on PaperUI but seems to be used

### ISSUE THREAD

**Issue by rzwarts74** [openhab/openhab2-addons#3514]
## Expected Behavior
When adding a Network pingable device with arping installed I expect the binding to also use ARP for detection (also report using it in the Thing properties). This is currently not the case so I am unsure if it's actually using the output of ARP (because it is performing an ARP who-has).

## Current Behavior
Currently I am seeing this for 3 defined pingable devices every minute (as expected):
```
2018-04-24 16:11:50.641 [TRACE] [g.network.internal.PresenceDetection] - Perform ARP ping presence detection for 192.168.178.70 on interface
2018-04-24 16:11:50.641 [TRACE] [g.network.internal.PresenceDetection] - Perform native ping presence detection for 192.168.178.70

```
However on the Thing property page it says the following:

```
uses_dhcp_listen | no
-- | --
dhcp_state | No access right for port 67. Bound to port 6767 instead. Port forwarding necessary!
presence_detection_type | 
arp_state | THOMAS_HABERT_ARPING_WITHOUT_TIMEOUT
uses_ios_wakeup | On
icmp_state | MAC_OS_PING
uses_arp_pings | no
```
Note the "uses_arp_pings" is no and presence_detection_type is empty. The trace shows a different thing. So what is really going on?

## Possible Solution
Make sure the Thing info reflects what is really happening. Now I am unsure of what information is being used and what isnt. 

## Steps to Reproduce (for Bugs)

1. Add a pingable network device
2. log:set trace the network binding
3. Check the logs for ARPs
4. Look at the Thing properties

## Context

Presence detection of Phones is a bit of a nightmare. I know that deep sleep will always affect me and that even ARP won't work, but now I don't know what is going on. 

## Your Environment

OH 2.2
MacOS 10.13.3

**Comment by romgen** [comment]
I suffer the same problem on Debian with OH 2.4.
I used the paperUI to add the pingable network device (iPhone).

`arp_state | Disabled
-- | --
dhcp_state | No access right for port 67. Bound to port 6767 instead. Port forwarding necessary!
icmp_state | Java ping
presence_detection_type |  
uses_ios_wakeup | Yes
`
`2018-12-25 11:58:04.459 [TRACE] [g.network.internal.PresenceDetection] - Perform ARP ping presence detection for 192.168.XXX.XXX on interface: eth0
2018-12-25 11:58:04.460 [TRACE] [g.network.internal.PresenceDetection] - Perform java ping presence detection for 192.168.XXX.XXX`

I also tried to play with the network binding setting, but to no avail. Arping works, but isn't shown in the UI, same goes for presence_detection_type, which is still left empty.

![oh-network](https://user-images.githubusercontent.com/2144963/50421243-6ad6cc80-083d-11e9-877f-9882f6615dcd.png)
