### ISSUE TITLE
[Milight] Exception when starting

### ISSUE THREAD

**Issue by orzechszek** [openhab/openhab2-addons#3524]
Hi,

During start i’m getting and exceptions with milight:

`[ERROR] [org.openhab.binding.milight         ] - [org.openhab.binding.milight.internal.discovery.MilightBridgeDiscovery(24)] The activate method has thrown an exception
java.lang.IncompatibleClassChangeError: Expected static field org.openhab.binding.milight.internal.discovery.MilightBridgeDiscovery.scheduler`

ii  openhab2                            2.3.0 20180423102155-1
ii  openhab2-addons                     2.3.0 20180423102155-1

**Comment by wborn** [comment]
See https://github.com/openhab/openhab2-addons/issues/3525#issuecomment-385100592.
