### ISSUE TITLE
[Astro] Exception when starting

### ISSUE THREAD

**Issue by orzechszek** [openhab/openhab2-addons#3525]
Hi,

During start i’m getting and exceptios with Astro:

`[ERROR] [org.eclipse.smarthome.binding.astro ] - [org.eclipse.smarthome.binding.astro.internal.discovery.AstroDiscoveryService(17)] The activate method has thrown an exception
java.lang.IncompatibleClassChangeError: Expected static field org.eclipse.smarthome.binding.astro.internal.discovery.AstroDiscoveryService.scheduler`

ii  openhab2                            2.3.0 20180423102155-1
ii  openhab2-addons                     2.3.0 20180423102155-1

**Comment by martinvw** [comment]
Are you sure you cleared your caches, this error would appear if you mix version prior which had static field with versions after that. 

Did you use the upgrade script? See also: https://docs.openhab.org/installation/linux.html#upgrade

**Comment by wborn** [comment]
There was a breaking change in ESH so you'll get that exception when you use an old JAR with a newer openHAB version or vice versa. See also this [community discussion](https://community.openhab.org/t/unit-support-knx-2-karaf-4-1-5-upgrade-and-more/41904/6?u=wborn).

So use the latest greatest default Astro Binding (removing custom JARs) or get a recompiled version of your custom Astro Binding JAR.
