### ISSUE TITLE
[Xiaomi MI IO] Problem with parsing json data

### ISSUE THREAD

**Issue by orzechszek** [openhab/openhab2-addons#3526]
I’m getting error:

2018-04-07 13:39:14.287 [WARN ] [nal.transport.MiIoAsyncCommunication] - Could not parse '{"result":{"life":706814,"cfg_time":0,"token":"xxxx","mac":"xxxxx","fw_ver":"1.2.4_60","hw_ver":"MC200","model":"zhimi.airpurifier.m1","wifi_fw_ver":"SD878x-14.76.36.p79-702.1.0-WM","ap":{"rssi":-66,"ssid":"xxxxx","bssid":"xx:xx:xx:xx:xx:xx"},"netif":{"localIp":"xx.xx.xx.xx","mask":"255.255.255.0","gw":"xx.xx.xx.xx"},"mmfree":27480,,"otu_stat":[0,0,0,0,0,0],"ott_stat":[227655, 0, 32, 11]},"id":416}' <- {"id":416,"method":"miIO.info","params":[]} (Device: 033DE0FB) gave error com.google.gson.stream.MalformedJsonException: Expected name at line 1 column 382 path $.result.mmfree

As mentioned by @marcel_verpaalen: "The device is sending invalid json (double comma after mmfree) ." - needed update.

**Comment by wborn** [comment]
For completeness here is a link to the related [community topic](https://community.openhab.org/t/xiaomi-mi-air-purifier-xiaomi-mi-io/34840/42?u=wborn).

**Comment by wborn** [comment]
Can you attach the `openhab-bundle-list.txt` file generated by the following command in a comment @orzechszek ?

`/usr/share/openhab2/runtime/bin/client -p habopen "bundle:list -s -l" > openhab-bundle-list.txt`

That should show us the installed bundle versions and their location. The other issues you created (#3524, #3525) suggest that something in your upgrade did not go well. So you the workaround @marcelrv is referring to in the community topic may also be missing.

I've installed a fresh Debian 9 in a VM. Installed Oracle Java 8, openHAB 2.2.0 (including the Astro, MiHome, Milight bindings) and then upgraded to openHAB 2.3.0-SNAPSHOT which all went well. Did you also answer Y to overwrite existing configuration files?

```
wouter@debian:~$ sudo apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  openhab2
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 64.7 MB of archives.
After this operation, 4367 kB disk space will be freed.
Do you want to continue? [Y/n] y
Get:1 https://openhab.jfrog.io/openhab/openhab-linuxpkg unstable/main amd64 openhab2 all 2.3.0~20180427191516-1 [64.7 MB]
Fetched 64.7 MB in 27s (2344 kB/s)                                                                                                                                                                                                         
apt-listchanges: Can't set locale; make sure $LC_* and $LANG are correct!
Reading changelogs... Done
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_TIME = "nl_NL.UTF-8",
	LC_MONETARY = "nl_NL.UTF-8",
	LC_ADDRESS = "nl_NL.UTF-8",
	LC_TELEPHONE = "nl_NL.UTF-8",
	LC_NAME = "nl_NL.UTF-8",
	LC_MEASUREMENT = "nl_NL.UTF-8",
	LC_IDENTIFICATION = "nl_NL.UTF-8",
	LC_NUMERIC = "nl_NL.UTF-8",
	LC_PAPER = "nl_NL.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
locale: Cannot set LC_ALL to default locale: No such file or directory
(Reading database ... 130388 files and directories currently installed.)
Preparing to unpack .../openhab2_2.3.0~20180427191516-1_all.deb ...
Unpacking openhab2 (2.3.0~20180427191516-1) over (2.2.0-1) ...
Setting up openhab2 (2.3.0~20180427191516-1) ...
Installing new version of config file /etc/default/openhab2 ...
Installing new version of config file /etc/openhab2/services/addons.cfg ...

Configuration file '/var/lib/openhab2/etc/org.apache.felix.fileinstall-deploy.cfg'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** org.apache.felix.fileinstall-deploy.cfg (Y/I/N/O/D/Z) [default=N] ? y
Installing new version of config file /var/lib/openhab2/etc/org.apache.felix.fileinstall-deploy.cfg ...
Installing new version of config file /var/lib/openhab2/etc/org.apache.felix.eventadmin.impl.EventAdmin.cfg ...

Configuration file '/var/lib/openhab2/etc/jmx.acl.org.apache.karaf.config.cfg'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** jmx.acl.org.apache.karaf.config.cfg (Y/I/N/O/D/Z) [default=N] ? y
Installing new version of config file /var/lib/openhab2/etc/jmx.acl.org.apache.karaf.config.cfg ...

Configuration file '/var/lib/openhab2/etc/jmx.acl.org.apache.karaf.bundle.cfg'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** jmx.acl.org.apache.karaf.bundle.cfg (Y/I/N/O/D/Z) [default=N] ? y
Installing new version of config file /var/lib/openhab2/etc/jmx.acl.org.apache.karaf.bundle.cfg ...
Processing triggers for systemd (232-25+deb9u3) ...
```

**Comment by orzechszek** [comment]
I've updated openhab to the newest version and it didn't ask for upgrade mentioned files.
Bundle list attached.
[openhab-bundle-list.txt](https://github.com/openhab/openhab2-addons/files/1957874/openhab-bundle-list.txt)

**Comment by wborn** [comment]
The list shows that your openHAB is still using several outdated bundles:

```
206 │ Active   │  80 │ 0.10.0.201712141004    │ mvn:org.eclipse.smarthome.binding/org.eclipse.smarthome.binding.astro/0.10.0-SNAPSHOT                         │ org.eclipse.smarthome.binding.astro
223 │ Active   │  80 │ 0.10.0.201712141004    │ mvn:org.eclipse.smarthome.extension.ui/org.eclipse.smarthome.ui.basic/0.10.0-SNAPSHOT                         │ org.eclipse.smarthome.ui.basic
225 │ Active   │  80 │ 0.10.0.201712141004    │ mvn:org.eclipse.smarthome.extension.ui/org.eclipse.smarthome.ui.paper/0.10.0-SNAPSHOT                         │ org.eclipse.smarthome.ui.paper
230 │ Active   │  80 │ 2.3.0.201801032157     │ mvn:org.openhab.binding/org.openhab.binding.mihome/2.3.0-SNAPSHOT                                             │ org.openhab.binding.mihome
231 │ Active   │  80 │ 2.3.0.201801032157     │ mvn:org.openhab.binding/org.openhab.binding.milight/2.3.0-SNAPSHOT                                            │ org.openhab.binding.milight
```

The last part of the version number is the build date so it should start with 201804 for bundles build this month.

These are the same bundles on an openHAB I installed today with apt-get:

```
199 │ Active   │  80 │ 0.10.0.201804271558    │ mvn:org.eclipse.smarthome.binding/org.eclipse.smarthome.binding.astro/0.10.0-SNAPSHOT                   │ org.eclipse.smarthome.binding.astro
208 │ Active   │  80 │ 0.10.0.201804271558    │ mvn:org.eclipse.smarthome.extension.ui/org.eclipse.smarthome.ui.basic/0.10.0-SNAPSHOT                   │ org.eclipse.smarthome.ui.basic
209 │ Active   │  80 │ 0.10.0.201804271558    │ mvn:org.eclipse.smarthome.extension.ui/org.eclipse.smarthome.ui.paper/0.10.0-SNAPSHOT                   │ org.eclipse.smarthome.ui.paper
212 │ Active   │  80 │ 2.3.0.201804271648     │ mvn:org.openhab.binding/org.openhab.binding.mihome/2.3.0-SNAPSHOT                                       │ org.openhab.binding.mihome
213 │ Active   │  80 │ 2.3.0.201804271648     │ mvn:org.openhab.binding/org.openhab.binding.milight/2.3.0-SNAPSHOT                                      │ org.openhab.binding.milight
```

Did you already try to reinstall the packages with apt? 

E.g.:

`apt install --reinstall openhab2`

or when you don't use the online repositories:

`apt install --reinstall openhab2 openhab2-addons openhab2-addons-legacy`

Does it show any warnings/errors when you do this?

**Comment by orzechszek** [comment]
Yes, Previously I upgraded with last snapshot and now I've reinstalled openhab with mentioned command above: 
apt install --reinstall openhab2
I'm still getting that error. It seems that bundle list didn't change...
[openhab-bundle-list.txt](https://github.com/openhab/openhab2-addons/files/1957999/openhab-bundle-list.txt)

During install I got error with python:
`Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f1ee530a950>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f1ee530a950>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
`
I've read that it's an error with Python 3.5.3, but it's not problematic. I installed Python 3.6.4 but I don't know how to force to use it.

**Comment by orzechszek** [comment]
@marcelrv, yes, I know, after reinstall I have to install binding through PaperUI again. I generated list before I install it.
[openhab-bundle-list.txt](https://github.com/openhab/openhab2-addons/files/1958118/openhab-bundle-list.txt)
Previously I've reinstalled openhab2, openhab2-addons and now I've even uninstall addons and reinstall openhab2 - error still exists :(
Openhab version:
openhab2/unstable,now 2.3.0~20180427191516-1 all [installed]

**Comment by BClark09** [comment]
> Maybe @BClark09 knows of other ways to troubleshoot openHAB using the wrong bundle snapshot versions when using the apt installation?

Afraid not, I have just built a new Linux snapshot which make sure that the files you mentioned above (`org.apache.felix.fileinstall-deploy.cfg` etc) are always updated. But the best way to see if you're not using old files in the userdata directory is to check the /var/lib/openhab2 folder for any `.dpkg-new` files.

@orzechszek, do you have any `.dpkg-new` files in userdata? If so, which ones? Also, can you let us know what is in your addon folder (`/usr/share/openhab2/addons`)?

**Comment by kaikreuzer** [comment]
Guys, may I ask you to only create and discuss issues here for code that is actually part of the repository?
For the moment, all discussions around Mi IO should be done on https://github.com/openhab/openhab2-addons/pull/2548, until this is merged. The good news is that I own a Mi Robot since last week as well, so I will personally bother @marcelrv to get that to a mergeable state soon 😉.
