### ISSUE TITLE
[loxone] Value from openHAB not shown in loxone

### ISSUE THREAD

**Issue by TheSpirit** [openhab/openhab2-addons#3536]
HI.
I have a Dimmer within openhab with a slider.
If i move the slader within openhab, the physical device is dimming, but i do not see the value change within Loxone software.
What is wrong?
Thanks a lot,
Andreas

**Comment by ppieczul** [comment]
Please describe your configuration in more details - what is connected to what and how.

**Comment by ppieczul** [comment]
@TheSpirit do you have any update here? Thanks
