### ISSUE TITLE
[Homematic] HMW-IO-12-Sw14-DR cannot read inputs in **digital** mode / analog and writing outputs works.

### ISSUE THREAD

**Issue by s0170071** [openhab/openhab2-addons#3567]
I have a RasPi with an Homematic CCU (piVCCU) and OpenHab 2.2. I do also have a HMW-IO-12-Sw14-DR module attached to it. Its is working for years with the CCU now. 

## Expected Behavior
I can see the HMW-IO-12-Sw14-DR in the paper UI and can link channels. I expect it to accept data (works indeed) and I would like to read values from the inputs.  These inputs can be configured either analog or digital.  I use them as digital inputs.
The input should return OPEN / CLOSED.
Edit: I can read the vaules if the input is configured analog.

## Current Behavior
If I link anything to "VALUE" channels, the HMW-IO-12-Sw14-DR disappears from the Paper UI control menu. I can still write to the module, e.g. switch on lights etc. 
I cannot read from it. Events are visible in the CCU but not in Openhab. No log entry in events.log either.

Edit: above text only applies when the **input is configured digital** by the ccu. If it is configured analog it works as expected.

## Context
I have window contacts attached to the inputs.

The items file reads this line: 
Number          NKG_Gaeste_Fenster              "FensterGäste  %f]"     <window>          (KG_Gaeste, gFenster)                           {channel="homematic:HMW-IO-12-Sw14-DR:d60fe425:MEQ0807163:22#VALUE"}

The sitemap file has this entry: 
 Text item=NKG_Gaeste_Fenster label="Fenster Gäste [%.2f]" icon="window"

**Comment by s0170071** [comment]
digging through the CUXD logs I found this: 

1. 
If configured digital, the inputs are available as #STATE. The returned data type is Number.  Normally STATE would be an output, but it seems EQ3 mixed something up here. Example:

 
`Number         KG_W              "window  [MAP(onoff.map):%s]"     <window> (KG_W, gWindows)                {channel="homematic:HMW-IO-12-Sw14-DR:d60fe123:MEQ0123456:22#STATE"}`
Values are 0 and 1.

2. The STATE data point is not shown in paper UI.

**Comment by gerrieg** [comment]
Can you please update to OH 2.3? If it still does not work, please send me a TRACE log (see docs)

**Comment by s0170071** [comment]
did update, still working. But as I said, 

> If configured digital, the inputs are available as #STATE. The returned data type is Number. Normally STATE would be an output. 
You want me to set in org.ops4j.pax.logging.cfg

```
# openHAB specific logger configuration

log4j2.logger.openhab.name = org.openhab
log4j2.logger.openhab.level = INFO --> TRACE ?
```
and send you the openhab.log ? 
There is probably no error as it works if you read the input as "STATE" data point. 
The problem is, that normally a STATE data point is for writing (output only)

Have a look at these three inputs (all operational)

```
Contact         Rauchmelder                    "Rauchmelder"      <alarm>           (Haus)                                          {channel="homematic:HMW-IO-12-Sw14-DR:pivccu:MEQ0808163:21#VALUE"}
Number         EG_Wohnen_FensterOst           "Wohnen Ost"       <window>          (EG_Wohnen, gFenster)                           {channel="homematic:HMW-IO-12-Sw14-DR:pivccu:MEQ0808163:16#STATE"}
Contact         EG_Wohnen_FensterSuedOst       "FensterSüdOst"    <window>          (EG_Wohnen, gFenster)                           {channel="homematic:HMW-Sen-SC-12-DR:pivccu:KEQ0006336:7#SENSOR"}
```
First is the input configured as analog in, second as digital, third is digital

**Comment by gerrieg** [comment]
I don't have this device, so it's a little bit hard for me to understand the problem.

There is a special handling in the binding for this device, based on the information provided by another user. [See sourcecode](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/virtual/HmwIoModuleVirtualDatapointHandler.java)

This adds always all channels to the thing, regardless of the ananlog/digital configuration:
VALUE should be a Number
STATE should be a Contact

Can you please post the output of: http://OPENHAB_SERVER:OPENHAB_PORT/rest/things/homematic%3AHMW-IO-12-Sw14-DR%3Apivccu

**Comment by meins0273** [comment]
I have a problem with the Homematic Multi IO module hmw-io-12-sw14-dr. I use the file OH 2.4 and Raspberrymatic with the latest version. Where a test with a CCU2 with the latest version and OH2.4 came to the same result.
The binding has a problem with the input channels 15-20. With these channels you can usually choose whether you want to use the input as analog (frequency measurement) or digital (state). Openhab recognizes your input at first login and sets the configuration. After that, Openhab can no longer switch between analgo and digital. Openhab will not recreate the channel. Worse still, if you have more than one of these modules, all the other modules will be configured relative to channels 15-20 of the first one. Even if you deregister all modules and create new data points are not created again. Only after uninstalling Openhab and rebuilding it will the channels be recreated. But just as described above only once.

Here is the logfile of Openhab.
There are two modules registered. In the first channel 15 is digital and channel 16 is analog.
As soon as I send an analogue value over channel 15 on the second this entry comes up:

2019-02-03 15: 58: 33.959 [WARN] [ternal.handler.HomematicThingHandler] - Channel not found for datapoint ‘LEQ0251896: 15 # FREQUENCY’

How can I create the channel in OH?

**Comment by BOFH90** [comment]
Got the same Problem...

**Comment by meins0273** [comment]
Nobody news?
