### ISSUE TITLE
[astro] Feature request: Sun meridian as an event

### ISSUE THREAD

**Issue by berland** [openhab/openhab2-addons#3575]
It would be nice if the astro binding could also calculate the time during the day when the sun is at its highest position, probably called the sun meridian, as calculated on 
https://www.timeanddate.com/astronomy/uk/greenwich-city

**Comment by wborn** [comment]
I think you can already use the noon channel group for this.

![noon](https://user-images.githubusercontent.com/12213581/40241047-44f9a996-5aba-11e8-9c9c-75563a8e3af2.png)

[Wikipedia](https://en.wikipedia.org/wiki/Noon):
> Solar noon is the time when the Sun appears to contact the local celestial meridian. This is when the Sun apparently reaches its highest point in the sky, at 12 noon apparent solar time. The local or clock time of solar noon depends on the longitude and date

If that doesn't work for you, please open an issue in the Eclipse SmartHome [issue tracker](https://github.com/eclipse/smarthome/issues). That is the repository containing the Astro binding source code.
