### ISSUE TITLE
[kostalinverter] Physical unit correction and improvement of displaying item

### ISSUE THREAD

**Issue by ttweb** [openhab/openhab2-addons#3578]
## Expected Behavior
Improvement: Units should be the correct type in displaying the item: kwh should be kWh
Adjustment: The values for actual power and overall production should be displayed without decimal places as they always display "xxx,00". So a %.0f would be perfect instead of %.2f

Info: Binding works perfect with a Pico Solar 10.1

**Comment by cweitkamp** [comment]
PR #3593 should address the wrong spelling of the unit. For the format pattern I suggest to set it in the item label.
