### ISSUE TITLE
[dscalarm] LCD message not updated

### ISSUE THREAD

**Issue by scaprile** [openhab/openhab2-addons#3586]
Hi there,
I'm connected to my DSC through an IT-100. I can see the LCD updates on the serial port before openhab2 takes over.
Everything works fine except keypad_lcd_update is never updated (is blank).
Looking at the code (I'm not fluent in Java but in C, but I try...) I see what seems that ChannelUID is not being initialized for that particular Thing (and LCDCursor, btw)
Regards

**Comment by scaprile** [comment]
Fixed with this:
```
diff --git a/addons/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/handler/KeypadThingHandler.java b/addons/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/handler/KeypadThingHandler.java
index 527f5dc..12e9516 100644
--- a/addons/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/handler/KeypadThingHandler.java
+++ b/addons/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/handler/KeypadThingHandler.java
@@ -148,9 +148,11 @@ public class KeypadThingHandler extends DSCAlarmBaseThingHandler {
                     case KeypadLEDFlashState: /* 511 */
                         keypadLEDStateEventHandler(event);
                         break;
-                    case LCDUpdate:
-                    case LCDCursor:
-                        updateChannel(channelUID, 0, dscAlarmMessageData);
+                    case LCDUpdate: /* 901 */
+                        channelUID = new ChannelUID(getThing().getUID(), KEYPAD_LCD_UPDATE);
+                        updateChannel(channelUID, 0, dscAlarmMessageData.substring(5));
+                        break;
+                    case LCDCursor: /* 902 */
                         break;
                     case LEDStatus: /* 903 */
                         int data = Integer.parseInt(dscAlarmMessageData.substring(0, 1));
```
TBD: Processing the position information to properly get the data and show it as the DSC LCD will.
It works for me right now.
If creating a pull request can be done in less time than this took, then I will.
[Off-topic]: Is there a good tutorial on that ? I contributed to paho (MQTT stuff) straight from github just by following a nice tutorial.
Cheers

**Comment by RSStephens** [comment]
I will review the code over the weekend and get back to you as soon as possible.  Thanks

**Comment by scaprile** [comment]
@martinvw Hi, both the cursor and the LCD itself called updateChannel with a channelUID parameter that was defined to null before the switch. All other switch elements construct a channelUID object, so I followed what seems to be the rule. Now the function is called with a non null channelUID and the channel us updated. The substring removes the parameters after the control code (row, column,#chars). I left the cursor without being updated, though I skipped the method call with a null parameter. 
Perhaps the null object was intentional, but it was not working in my setup. Being an embedded C developer I assumed it was a mistake, tried what I considered the fix, and it worked.
@RSStephens Thanks, feel free to preach/lecture me, OO/Java is not my world.

Differences (compared to a DSC LCD keypad):
902(cursor): Position indicator to place a "cursor" that would blink/show on an LCD (or an image of it). Perhaps this is used for config stuff, didn't see where in the code (not that I have digged for too long anyway).
901(lcd): The IT-100 sends row number (1) column number (2) and number of characters (2), then the string would have to overwrite what is placed at that row and column position in "LCD memory". The DSC LCD I know is a 2x16-type and the first row rolls over to the second row, the IT-100 periodically (every minute) sends 32 chars at r0 c00 (90100032) to show the date and time: `90100032  Date     Time MAY 25/18 11:21a` which shows as:
```
  Date     Time 
MAY 25/18 11:21a
```
Not that it is a necessary add on, but perhaps some time later I'm in the mood for it.

Cheers.

**Comment by RSStephens** [comment]
Hello @scaprile,

Not going to preach/lecture you, just reiterate what @martinvw has already said; LCDCursor will be ignored.  You are on the right track though, and probably the first to utilize those channels.  So good catch.

LCDCursor would need to be redone also as seen here:

          case LCDUpdate: /* 901 */
              channelUID = new ChannelUID(getThing().getUID(), KEYPAD_LCD_UPDATE);
              updateChannel(channelUID, 0, dscAlarmMessageData);
              break;
          case LCDCursor: /* 902 */
              channelUID = new ChannelUID(getThing().getUID(), KEYPAD_LCD_CURSOR);
              updateChannel(channelUID, 0, dscAlarmMessageData);
              break;

My original intent wasn't really to do anything in the binding with those channels, just populate them with the information from the alarm panel, thus allowing anyone to use/parse the information externally.  Therefore, I would populate the channels with the entire string using

`updateChannel(channelUID, 0, dscAlarmMessageData);`

instead of

`updateChannel(channelUID, 0, dscAlarmMessageData.substring(5));`.

It appears that I didn't complete the coding for those channels.  Not sure why.  I must have gotten sidetracked.  Sorry about that.  I have some other issues to deal with in the binding, so I can look at this also, if you would like.  Although, It may be a couple of weeks before I can get to it.  Thanks for your input.

**Comment by scaprile** [comment]
@RSStephens Thanks, got it.
The thing gets the whole data and the LCD-like stuff can be done (if the user wants to do it) at a higher layer with a transformation (in, say, js for example).
So my version of the binding looks now like you suggested, like this:
```
diff --git a/addons/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/handler/KeypadThingHandler.java b/addons/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/handler/KeypadThingHandler.java
index 527f5dc..14d332b 100644
--- a/addons/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/handler/KeypadThingHandler.java
+++ b/addons/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/handler/KeypadThingHandler.java
@@ -148,8 +148,12 @@ public class KeypadThingHandler extends DSCAlarmBaseThingHandler {
                     case KeypadLEDFlashState: /* 511 */
                         keypadLEDStateEventHandler(event);
                         break;
-                    case LCDUpdate:
-                    case LCDCursor:
+                    case LCDUpdate: /* 901 */
+                        channelUID = new ChannelUID(getThing().getUID(), KEYPAD_LCD_UPDATE);
+                        updateChannel(channelUID, 0, dscAlarmMessageData);
+                        break;
+                    case LCDCursor: /* 902 */
+                        channelUID = new ChannelUID(getThing().getUID(), KEYPAD_LCD_CURSOR);
                         updateChannel(channelUID, 0, dscAlarmMessageData);
                         break;
                     case LEDStatus: /* 903 */
```
I can wait till you address all issues, let me know if I can help.
Best regards.
