### ISSUE TITLE
Add support for genre in kodi binding

### ISSUE THREAD

**Issue by CWempe** [openhab/openhab2-addons#3597]
According to this post there is a reasonable use case to get the genre of the current playing media from kodi.

https://community.openhab.org/t/kodi-anyone-able-to-get-the-genre-of-the-currently-playing-movie-using-the-kodi-xbmc-binding/45497

I think it would be nice if feature could be added.

Maybe even support any availabe Method from KODI`s JSON-RPC_API.

https://kodi.wiki/view/JSON-RPC_API/v8#Methods

**Comment by cweitkamp** [comment]
PR #3631 (for genre)

> Maybe even support any availabe Method from KODI`s JSON-RPC_API.

I will think about it. But I am afraid it won't be possible.
