### ISSUE TITLE
[Kostal] what unit is refreshInterval

### ISSUE THREAD

**Issue by CWempe** [openhab/openhab2-addons#3598]
I was wondering what unit the `refreshInterval` parameter for the `kostalinverter` thing is.

There is no description in the README.
https://github.com/openhab/openhab2-addons/tree/master/addons/binding/org.openhab.binding.kostalinverter

I guess it is `seconds` but the `thing-types.xml` says `ms`.
https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.kostalinverter/ESH-INF/thing/thing-types.xml#L36

So this issue is about fixing the `thing-types.xml` and/or add a description in the README.

I can do that if anybody can tell me the correct answer. :)

**Comment by cweitkamp** [comment]
I added the unit `ms` to the config-description of the thing-type in PR #3593 . Shall I add a sentence in the README, too?

**Comment by CWempe** [comment]
Actually I think it is `seconds`.

My assumption is base on these two facts:

`}, 0, config.refreshInterval, TimeUnit.SECONDS);`

see: https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostal/inverter/WebscrapeHandler.java#L64

and the default value `60` would not make sense for `ms`.

see: https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.kostalinverter/ESH-INF/thing/thing-types.xml#L37


Unfortunately I am not able to check this in my real setup at the moment.
Maybe tomorrow.

@wborn You might be able to help here. :)

**Comment by cweitkamp** [comment]
Good catch. I have to admit that I only added the `ms` unit to the config parameter according to the description. I changed it in PR #3593 and added a remark in the README.
