### ISSUE TITLE
[amazonechocontrol] Possible to use authentication token instead of password?

### ISSUE THREAD

**Issue by claell** [openhab/openhab2-addons#3606]
@mgeramb Just heard of your binding and it looks very promising. The only thing that felt a little bit problematic for me was that it stores my password in plaintext.

I know that Google offers some kind of authentication tokens to login to YouTube (https://developers.google.com/youtube/v3/guides/authentication) or Google Drive for example.

Is there a possibility to also use such token for this binding?

Possible problems:
- Amazon simply does not offer this
- Since a "hack" through alexa.amazon.com is used to communicate with the Echo device it might not be possible to use a token.

**Comment by mgeramb** [comment]
@kaikreuzer  this issue can be closed now

**Comment by claell** [comment]
@mgeramb Just discovered that you have fixed this in your big feature PR when going through the changelog of openHAB 2.4.

Thank you for finding a way of doing this and your continuous development of the binding!
