### ISSUE TITLE
[NEST] Binding not accepting command without unit

### ISSUE THREAD

**Issue by vzorglub** [openhab/openhab2-addons#3614]
When sending a command of 21 to the set_point channel the binding doesn't pick it up
When sending a command of `21|°C` from the rules or 21°C from the rest API the binding works

## Expected Behavior
When sending a command of 21 (or other) to the set_point channel the thermostat set_point should update. The binding should assume it's the same using as before and send the command to the thermostat.

## Current Behavior
When sending a command of 21 to the set_point channel the binding doesn't pick it up
When sendina a command of `21|°C` from the rules or 21°C from the rest API the binding works

## Possible Solution
For the binding to accept both unit AND not unit numbers

## Your Environment

2.4 SNAPSHOT

**Comment by lolodomo** [comment]
Such command is handled by the max and the netatmo bindings. This could help.
