### ISSUE TITLE
[WeatherUnderground] new Item pressureTrend isn't translated like conditions

### ISSUE THREAD

**Issue by jmahmens** [openhab/openhab2-addons#3625]
## Expected Behavior
The new Item current#pressureTrend is translated like current#conditions into the configures language
## Current Behavior
current#pressureTrend shows stable/up/down allways and is not translated like current#conditions clowdy->Wolkig (German) 

## Steps to Reproduce (for Bugs)
1. use WeatherUnderground Binding 
2. add item current#pressureTrend

## Your Environment
* Version used: openhab 2.3, WeatherUnderground 2.3.0
* Operating System: Raspbian Stretch

**Comment by kaikreuzer** [comment]
Please note that this binding is maintained at ESH - but its future is anyhow at risk right now, see https://github.com/eclipse/smarthome/issues/5659.
