### ISSUE TITLE
[JDBC MySQL] stopped persistence after modify item/rule/strategy

### ISSUE THREAD

**Issue by DubZyy** [openhab/openhab2-addons#3626]
Running OH 2.3 stable on Win10. When I modify any item/rule or persist file, the persistence dont update anything to database. I need to restart the OH service.

No error messages in log files.

**Comment by evorg** [comment]
I am experiencing exactly the same issue:
- openHAB 2.3.0 on openHABian
- KNX2 Binding
- MySQL Persistence

After editing the items configuration the "everyChange" strategy stops working, but when I add the "everyMinute" strategy it stores the correct values every minute ...

**Comment by cweitkamp** [comment]
I have introduced JDBC MariaDB persistence in my live environment yesterday. I have similar issues for my items after changing their configuration.

The JDBC persistence extension is not part of this repository. It is maintained in [openhab/openhab1-addons](https://github.com/openhab/openhab1-addons/issues/). But the persistence service itself is more or less maintained in the [ESH](https://github.com/eclipse/smarthome/issues) framework itself. 

@kaikreuzer Is this a binding or framework issue? Wdyt?

**Comment by kaikreuzer** [comment]
Well, it for sure isn't an issue with any code in openhab2-addons.

I'd suppose it is probably an issue within the ESH framework, so the best place to report it would be https://github.com/eclipse/smarthome/issues.
