### ISSUE TITLE
[Tado] Things go into Offline mode and dont recover on temporary connectivity issues

### ISSUE THREAD

**Issue by martink2** [openhab/openhab2-addons#3628]
## Expected Behavior
During internet Connectivity outages or temporary name resolution errors I would
expect the things to recover into online state, currently this requires a server restart.

## Current Behavior
When temporary connectivity problems occur like DSL disconnects or router
reboots in my home some of my Things go into the following state:

"Status: OFFLINE - COMMUNICATION_ERROR Could not connect to server due to my.tado.com"

This by itself would not be an issue since the thing is actually offline but unfortunately
they never recover until i restart the openhab server after which it immediately works again.

## Steps to Reproduce (for Bugs)
Remove internet access for a couple of minutes. 

I am unfortunately neither a great Java specialist nor a very experienced OpenHAB user,
so if you could give me a pointer on how to further debug the issue in more detail that would
be greatly appreciated. Is there for example a way to set the plugin into debug LOG ?

## Context
Asked by @dfrommi to move the bug here from the original repo of the addon.

## Your Environment
* Version used: openhab 2.3
* Environment name and version:
* Operating System and version openHABian stable

**Comment by dfrommi** [comment]
@martink2 Thanks for moving the issue.

Can someone tell me the recommended way of doing it? Should the binding have a scheduled job that is retrying from time to time? Or is there some OH functionality that can be configured to retry on a regular basis if the bridge is offline.

**Comment by kaikreuzer** [comment]
There is nothing in the framework - the binding should indeed have some scheduled job that regularly tries a reconnect, if it is OFFLINE.
Likewise, whenever some command is sent, you should not simply throw it away because the bridge is offline, but you should rather try to re-establish the connection in that moment as well.

**Comment by dfrommi** [comment]
I think this issue can be closed. The PR with the fix is merged.
