### ISSUE TITLE
Homematic HmIP-FROLL HmIP-BROLL different channels for read/write LEVEL

### ISSUE THREAD

**Issue by sVnsation** [openhab/openhab2-addons#3637]
The issue is also described [here](https://community.openhab.org/t/homematic-hmip-froll-shutter-actuator-rollershutter-icon-shows-always-closed/38827) and [here](https://github.com/thkl/homebridge-homematic/issues/181) 

On HmIP-FROLL/BROLL the channels look like this:

> HMIP-FROLL
> HmIP-RF.001157099Axxxx:0.ACTUAL_TEMPERATURE
> HmIP-RF.001157099Axxxx:0.CONFIG_PENDING
> HmIP-RF.001157099Axxxx:0.DUTY_CYCLE
> HmIP-RF.001157099Axxxx:0.ERROR_CODE
> HmIP-RF.001157099Axxxx:0.ERROR_OVERHEAT
> HmIP-RF.001157099Axxxx:0.ERROR_OVERLOAD
> HmIP-RF.001157099Axxxx:0.ERROR_UPDATE
> HmIP-RF.001157099Axxxx:0.OPERATING_VOLTAGE
> HmIP-RF.001157099Axxxx:0.RSSI_DEVICE
> HmIP-RF.001157099Axxxx:0.RSSI_PEER
> HmIP-RF.001157099Axxxx:0.UNREACH
> HmIP-RF.001157099Axxxx:0.UPDATE_PENDING
> HmIP-RF.001157099Axxxx:1.PRESS_LONG
> HmIP-RF.001157099Axxxx:1.PRESS_SHORT
> HmIP-RF.001157099Axxxx:2.PRESS_LONG
> HmIP-RF.001157099Axxxx:2.PRESS_SHORT
> HmIP-RF.001157099Axxxx:3.LEVEL
> HmIP-RF.001157099Axxxx:3.PROCESS
> HmIP-RF.001157099Axxxx:3.SECTION
> HmIP-RF.001157099Axxxx:4.LEVEL
> HmIP-RF.001157099Axxxx:4.PROCESS
> HmIP-RF.001157099Axxxx:4.SECTION
> HmIP-RF.001157099Axxxx:4.STOP
> HmIP-RF.001157099Axxxx:5.LEVEL
> HmIP-RF.001157099Axxxx:5.PROCESS
> HmIP-RF.001157099Axxxx:5.SECTION
> HmIP-RF.001157099Axxxx:5.STOP
> HmIP-RF.001157099Axxxx:6.LEVEL
> HmIP-RF.001157099Axxxx:6.PROCESS
> HmIP-RF.001157099Axxxx:6.SECTION
> HmIP-RF.001157099Axxxx:6.STOP
> HmIP-RF.001157099Axxxx:7.WEEK_PROGRAM_CHANNEL_LOCKS
> HmIP-RF.001157099Axxxx:7.WEEK_PROGRAM_TARGET_CHANNEL_LOCK
> HmIP-RF.001157099Axxxx:7.WEEK_PROGRAM_TARGET_CHANNEL_LOCKS

It is possible to read (only) the correct level status via channel 3. (0%, 25%, 50%, ...)
Whereas write level for UP, STOP, DOWN is channel 4 (it is read/write), but the read level status on channel 4 is almost always 100%.

I think this is a HmIP-FROLL/HmIP-BROLL specific behavior. 
Any ideas how to work around this?
Maybe like this:
- GET-Events with 3:LEVEL
- SET-Events with 4:LEVEL

**Comment by mdicke2s** [comment]
This issue was moved to eclipse/smarthome#5799
