### ISSUE TITLE
[CoolMasterNet] devices don't update - "Schedule runnable ended with exception" error

### ISSUE THREAD

**Issue by Dan1001** [openhab/openhab2-addons#3644]
Hi,

When the coolmasternet bundle starts, I get the following error in the logs:

```
20|2018-06-10 11:40:20.817 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception                  | 
20|java.lang.NullPointerException: null                                                                                                 | 
20|        at org.openhab.binding.coolmasternet.internal.ControllerHandler.lambda$0(ControllerHandler.java:72) ~[?:?]                   | 
20|        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]                                             |'
20|        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]                                                    | 
20|        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?| 
20|        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]      | 
20|        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]                                     |'
20|        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]                                     | 
20|        at java.lang.Thread.run(Thread.java:748) [?:?]            `
```
The binding correctly reads the devices' status at startup but then doesn't pick up subsequent changes. 

This is repeatable - I can bundle:restart the binding and the items will then update, but only do so once. I get the error every time.

Writing to the devices works fine at any time.

Thank you!

Dan

Running OH2.3 release on Ubuntu 16.04  (not containerised)

**Comment by wborn** [comment]
Can you test if adding a null check fixes this with this  [org.openhab.binding.coolmasternet-2.4.0-SNAPSHOT.zip](https://github.com/openhab/openhab2-addons/files/2091482/org.openhab.binding.coolmasternet-2.4.0-SNAPSHOT.zip)?

To test, uninstall the default binding and then add this .zip after renaming it to .jar to the /addons directory.

I don't have these devices or use this binding myself but adding a null check may just fix this. :smile:

**Comment by Dan1001** [comment]
You are a magician! 

Definite progress - the items now update when the device state changes - thank you!

I still get errors on starting/restarting the bundle - here are a couple of samples 

[log1.txt](https://github.com/openhab/openhab2-addons/files/2091772/log1.txt)
[log2.txt](https://github.com/openhab/openhab2-addons/files/2091773/log2.txt)

And then every 10 seconds or so in the logs I get:
`2018-06-11 22:09:12.575 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler ControllerHandler tried updating the thing status al|--
20|though the handler was already disposed.    `

Any further help greatly appreciated!

Dan

**Comment by wborn** [comment]
The errors in log2.txt are a bit difficult to pin point. 

I think this [org.openhab.binding.coolmasternet-2.4.0-SNAPSHOT.zip](https://github.com/openhab/openhab2-addons/files/2091809/org.openhab.binding.coolmasternet-2.4.0-SNAPSHOT.zip) may fix the others. 

To test it, rename it again to .jar and replace the existing file in your /addons directory with this one.

**Comment by Dan1001** [comment]
Thanks. I still get the "Exception occurred while informing handler: null" and the "handler was already disposed" errors.

Dan

**Comment by wborn** [comment]
There was a bug in the binding where it would schedule a reoccurring update task but it did not cancel it when the handler was disposed. So the error will keep showing until you restart openHAB. I added a line to cancel the job when the handler is disposed to fix that.

**Comment by Dan1001** [comment]
Thanks - it has indeed disappeared upon restarting openHAB. Thank you very much for solving this so quickly!

This may be a stupid question, but how do I know when the bugfix has been incorporated into the snapshot, so I can update, delete the JAR and use the binding normally?

**Comment by Dan1001** [comment]
thank you!

**Comment by Dan1001** [comment]
thank you!
