### ISSUE TITLE
[KNX2] Definition of the Group Address Notation in README.md wrong

### ISSUE THREAD

**Issue by NorbertHD** [openhab/openhab2-addons#3648]
The definition of the Group Address Notation in [README.md](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.knx/README.md) seems to be wrong.

This works for me:

```javascript
Type datetime      : Date1      "Alarm"       [ ga="11.001:<1/5/24" ]
```

But this doesn't:
```javascript
Type datetime      : Date1      "Alarm"       [ ga="<11.001:1/5/24" ]
```

So '<' must come after the dpt.

```
<config>="[<dpt>:][<]<mainGA>[[+[<]<listeningGA>]+[<]<listeningGA>..]]"
```

PS: How do I link this issue to the [topic](https://community.openhab.org/t/knx2-mismatch-between-declaration-and-example-of-dpt/46089) in the community forum?

**Comment by udo1toni** [comment]
Do you have successfully used more than one GA in a parameter? Like this one:
```
Type switch : Channel1 "Switch 1" [ ga="1/1/1+<1/1/2" ]
```

**Comment by NorbertHD** [comment]
@udo1toni 
According to the documentation the default dpt of type dimmer parameter position is 5.001.
So there should be no need for explicit defining it.
Could you please open a separate issue for this?

For my example I had to define dpt 11.001 because type datetime is dpt 19.001 and my knx display could only handle dpt 11.001 (date only).
