### ISSUE TITLE
System Info Binding

### ISSUE THREAD

**Issue by FallenRiteMonk** [openhab/openhab2-addons#365]
Hy,
I was looking through the bindings for OH1 and came across the System Info Binding. I would be interested in porting this binding to OH2, but I have some doubts about the libs (SIGAR) used in it.
In my point of view I think it would be better to use [OSHI](https://github.com/dblock/oshi) since it is still under active development. What do you think about this?
Another question is how would EPL license fit into OH2? (I'm not into licences so I would like clearance that it would be all right to use OSHI)

Thanks,
FallenRiteMonk
##

**Comment by kaikreuzer** [comment]
OSHI looks very interesting as it does not require any native parts, so yes, I would welcome such a new binding using this lib.

> Another question is how would EPL license fit into OH2?

It is the best fit possible, since OH2 is as well licensed under the EPL :-)

**Comment by FallenRiteMonk** [comment]
Thanks for the fast reply.
I guess me starting to work on this binding wont be that fast, but I'll keep you updated on how it is going.

**Comment by kaikreuzer** [comment]
Cool, good luck with it :-)

**Comment by FallenRiteMonk** [comment]
Since I'm new to implementing a binding for OH I've been looking into how to do it and started to think about the actual implementation for a system info binding. Before getting started I would like to ask which approach I should take (regarding the structure depending on the features OSHI has):
Have one thing type (system) and define the single OSHI features as channels or have more thing types (OS, CPU, RAM, Disk and Battery) and group the features correspondingly (ex.: Manufacturer, OS and version as channels for OS thing)

**Comment by kaikreuzer** [comment]
I would go for a single Thing - in general, you should try to choose the structure according to real physical units and there is only a single host computer that is to be monitored here.

**Comment by hakan42** [comment]
@FallenRiteMonk , did you have any progress on this?

**Comment by hakan42** [comment]
@FallenRiteMonk , any progress yet? If not, I'd love to try my hand on this as I need some monitoring on my OH2 server :smile:

**Comment by FallenRiteMonk** [comment]
@hakan42 sorry must have missed out on the first message, but I haven't done anything yet as I couldn't find any time for it!

**Comment by hakan42** [comment]
o.k., I started something at https://github.com/hakan42/openhab2/commits/systeminfo-binding

Let's see how it progresses and whether this will turn into yet another of my dead unfinished branches :smile:

**Comment by hakan42** [comment]
Small work-in-progress report: My binding progresses nicely, but there are a few stumbling blocks:

* OSHI does not (yet?) support process information. Therefore, using this to monitor the openhab process itself will be hard
* Disc read/writes and Network read/writes are similarly not available in OSHI

**Comment by hakan42** [comment]
> I would go for a single Thing - in general, you should try to choose the structure according to real physical units and there is only a single host computer that is to be monitored here.

Most of the information I have can be easily modeled onto one thing, but what about multiple CPUs and filesystems? Would you go with dynamically created channels or with multiple "filesystem" things which have channels like "freespace"?

**Comment by hkuhn42** [comment]
To give you my 50 cent: I would go for multiple generated channels. The system is one thing in a physical sense so i (from a users point of view) would expect only one. I am aware that this will be a fairly complex thing on some systems but as far as i know you can mark some of the channels as extended to hide them from basic views. Regarding free vs used disc space, i would probably expect a percentage value for used diskspace. This would also allow for warning rules when the size is under a certain percentage whereas with absolute values you would have to deal with the good old byte vs megabyte vs terabyte unit problem. So e.g. channel /logs has 60% usage...

**Comment by hkuhn42** [comment]
On the feature side: i think it would be nice to also have additional information (not currently part of OSHI) about  [network interfaces and addresses](https://docs.oracle.com/javase/tutorial/networking/nifs/listing.html). This should be relatively straightforward as its jdk only code.

**Comment by svilenvul** [comment]
Hi, after a talk with @hakan42, it seemed that nobody was working on this binding, so I implemented it in #785. If someone is interested, might take a look or try it out. I will appreciate any comments and help with it !

**Comment by svilenvul** [comment]
OSHI is evolving. New functionality is out there:
- [IO Wait information ](https://github.com/dblock/oshi/pull/137)
- [Process and thread counts](https://github.com/dblock/oshi/pull/140) 
- [Methods for getting swap](https://github.com/dblock/oshi/pull/142)
- [Network interface](https://github.com/dblock/oshi/issues/138)  will be available soon

I will take a closer look, how can I update the #785 Systeminfo openHAB2 binding

**Comment by dbwiddis** [comment]
OSHI developer here. Saw a link pop up on my issues to this issue. Glad to see our current network interface work is desired.

What other features do you need that we don't yet have?  I see process information mentioned. Haven't done it because I didn't know there was a need for it, but if you have a use case/example, it can help guide what we implement.

**Comment by dbwiddis** [comment]
OSHI 2.4 has just been released with the above referenced functionality.

**Comment by svilenvul** [comment]
I see that we can expect [USB device](https://github.com/dblock/oshi/issues/160) info from OSHI as well :)
 
Thank you so much @dbwiddis ! I am not sure what else the users might need from the [Systeminfo  binding](https://github.com/svilenvul/openhab2-addons/blob/365-Systeminfo-binding/addons/binding/org.openhab.binding.systeminfo/README.md), but may be @hakan42, @hkuhn42, or @FallenRiteMonk  can say something about that.

If I get it right from the code, we can take Read and Write information for hardware drives only on Linux currently ?

**Comment by paulianttila** [comment]
Great the see progress on OH2 system info binding.

> I am not sure what else the users might need from the Systeminfo binding
There are still many features, which are supported by the OH1 system info binding, but not yet available on OH2 binding. Old one can monitor e.g. folder/directory (files and usage) statistics, network interface statistics (sent and received bytes), disk statistics (written and read bytes) and also process specific statistics (cpu, memory, etc). 

When I implemented OH 1 binding, one of the goal was to be able to monitor openhab itself (memory consumption, cpu, uptime etc) to recognise the OH related problems. So, that could be great feature to be supported by the OH2 binding as well (when/if OSHI will support process specific statistics someday).

**Comment by dbwiddis** [comment]
You are correct that OSHI only supports disk reads/writes on Linux. I was not able to find out where that information is even available on Windows or OS X.

**Comment by hakan42** [comment]
About monitoring the OH process, I must admit that I am using a dedicated Pi for the OH installation, so having a generic system load is good enough for me. This, together with free filesystem space, makes my OH2 perfectly self-monitored :smile:

**Comment by dbwiddis** [comment]
As an "entry level" automation enthusiast (I've got a handful of zwave components) you are on the road to recruiting me to support this project as well. :-)  Possibly with a Pi like @hakan42 because that's just plain cool.

But more importantly... I'll see what I can do about process information. I've added an issue and hope to get to it in the next version... no promises but hopefully over the next month or so.  Faster if I get help. :-)

**Comment by dbwiddis** [comment]
I've just added process information.  You can get info for all processes, a specific process by pid, and find out the pid of the process you're running.  CPU, memory, uptime, other stats are included.  Feel free to grab the 2.5-SNAPSHOT to give it a spin.
```
   PID  %CPU %MEM       VSZ       RSS Name
 55977  27.9  0.2   6.8 GiB  34.3 MiB java
 51820  18.7  5.6   6.3 GiB 919.2 MiB eclipse
 39272  11.2 17.8   7.1 GiB   2.8 GiB prl_vm_app
 85316   6.5  2.9   5.6 GiB 471.4 MiB thunderbird
```

**Comment by svilenvul** [comment]
@dbwiddis , thank you very much, I will give it a try !

**Comment by dbwiddis** [comment]
@svilenvul Figured out the Windows and OS X [Disk reads/writes](https://github.com/dblock/oshi/issues/192), so that'll go in over the coming days/week.

**Comment by svilenvul** [comment]
@dbwiddis nice ! I will track your progress.

**Comment by dmcwhinnie** [comment]
For reference, looks like a library or pathing issue on ARM 64.  Posting here to try and connect the dots between OSHI and OpenHab,

https://github.com/dblock/oshi/issues/204

https://community.openhab.org/t/systeminfo-initialization-error-on-pine64/11726/9

**Comment by hmerk** [comment]
I guess this can be closed as the new systeminfo binding is in place now.
