### ISSUE TITLE
[keba] P30 missing Current and Total Energy

### ISSUE THREAD

**Issue by thl-mot** [openhab/openhab2-addons#3674]
I have a Keba P30 installed. I am running OpenHab2 on a Raspberry. 
I added The Keba Binding, and configured all items by the paper-ui.
OperationState, PlugState (Wallbox) and Energy (Session) is display corectly, all other Values Current, Energy (Total), Power is displayed as -NaN. Same on the Android APP.
When using the Web-Page of the Wallbox all Values exist.
Where do I have to look for the error.
sincerely Thomas

**Comment by wborn** [comment]
You can check the  log files for any errors, see: https://www.openhab.org/docs/administration/logging.html
