### ISSUE TITLE
[knx2] DPT 17.001 (Scene) does not work as expected

### ISSUE THREAD

**Issue by udo1toni** [openhab/openhab2-addons#3686]
When using the following thing definition:
```
    Thing device generic [ 
    ] {
        Type number-control         : scene1 "Lichtszene"       [ ga="17.001:3/0/0" ]
    }
```
the knx scene control does not work correctly. When sending a scene number from knx, this ends in a wrong number format:
```
2018-06-20 01:48:38.484 [WARN ] [nx.internal.client.AbstractKNXClient] - Value '3.0' could not be sent to the KNX bus using datapoint 'command DP 3/0/0 'knx:ip:bridge', DPT id 17.001, low priority': 17.001 Scene Number: wrong value format: 3.0. Giving up now.
2018-06-20 01:48:38.485 [WARN ] [.internal.handler.DeviceThingHandler] - An error occurred on channel knx:device:bridge:Virtuell:scene1: 17.001 Scene Number: wrong value format: 3.0
tuwien.auto.calimero.KNXFormatException: 17.001 Scene Number: wrong value format: 3.0
```
This is very strange, as 17.001 is of type integer, so why is the number changed to float?

If controlling the scene number through e.g. Paper UI, knx reacts as expected.

Afaik this is valid for all knx2 versions up to actual nightly version.

**Comment by NorbertHD** [comment]
One question. I thought that things of type *-control could only receive or read values **from** the knx bus.

But your debug output says that "Value '3.0' could not be **sent** to the KNX bus".

Do you try to write to the number-control?

**Comment by udo1toni** [comment]
No, it's the other way. 
There is no actuator which will store the value, so I'm using number-control.
In fact, I can't see any difference between number and number-control here, as there are no commands but only values to send. 

If I do a `scene1.sendCommand(3)` this works as expected. The Warning does only appear if I push the Scene rocker in the wall. It doesn't matter if I'm using number or number-control.
