### ISSUE TITLE
[homekit] Items are lost after .items file updated on openHAB 2.3

### ISSUE THREAD

**Issue by andrey-yantsen** [openhab/openhab2-addons#3687]
After updating any .items file, where any HomeKit items are stored (I was able to reproduce the issue with `Switchable` and `Temperature` items) those items disappear from the Home app until the restart of `homekit` bundle.

**Comment by fabiradi** [comment]
Even restarting the homekit bundle does not work for me. I have to do `clearPairings`, stop, and start openHab to re-add the bridge with all items. Of course, all room assignments are lost, any name change as well.

**Comment by marcusaram** [comment]
Same issue here, best is to restart homekit bundle before you access HomeKit on your device, otherwise you have to reset it.

**Comment by dfraser** [comment]
I’m experiencing this issue too. Fresh install from packages yesterday. Reloading .items file causes the homekit accessories contained in that file to vanish.

**Comment by hugoboss00** [comment]
i have the same issue here on a clean installation of openHAB

**Comment by marcusaram** [comment]
I fixed by removing all the spaces between the brackets and quotes. For example: [ "Switchable" ] to ["Switchable"]

Make sure you fix this for all your items. I came across this solution from openhab forum but also that some items disappeared but not all, I had some items without spaces.

**Comment by tomclaessens** [comment]
I have the same issue, rpi 3 B+ with a fresh install of OH 2.3

HomeKit integration is working fine but as soon as I edit the items file, openhab shows up as being unsupported. Only solution is to clear pairing and restart with adding everything which is a pain since I'm still expanding with lamps, sensors, etc.

**Comment by wuytens** [comment]
i have the same issue. Would be really good if someone cloud fix it.

**Comment by michaltrzaska** [comment]
Same here !

**Comment by Roelofzo** [comment]
I'm seeing the same. would even be great if we could have a config file to re populate the room names and locations of items.

**Comment by tomclaessens** [comment]
I switched my whole setup to Home Assistant because of this. It's definitely a lot more stable towards HomeKit functionality. Since I made the switch, I never had the "unsupported device" issue again.

**Comment by J-N-K** [comment]
Is this fixed in latest Snapshots?

**Comment by J-N-K** [comment]
since the item handling has been refactored, this is most likely fixed.
