### ISSUE TITLE
[max!] MAX! Binding keeps discovering Things which are already defined in *.things file

### ISSUE THREAD

**Issue by chiefymuc** [openhab/openhab2-addons#3689]
## Expected Behavior
MAX! Binding should ignore "discovered" things which are already defined as things in *.things file

## Current Behavior
MAX keeps showing these things as newly discovered in the Inbox.

## Steps to Reproduce (for Bugs)
1. define a thing in *.thing file
2. restart openhab
3. check Inbox -> Thing pops up

## Your Environment
latest OH2.4.0 on openhabian on RPi3B+

**Comment by cweitkamp** [comment]
I think this one can be solved by adding the missing representation-property tag to the bridge-type and thing- type definitions.

**Comment by cweitkamp** [comment]
I have added those tags in PR #3506.
