### ISSUE TITLE
Paper UI configuration bar annoyingly toggles scroll bar

### ISSUE THREAD

**Issue by Avamander** [openhab/openhab2-addons#3712]
## Expected Behavior
Paper UI doesn't touch scroll bar behaviour at all

## Current Behavior
When doing pretty much anything when a list is displayed it sometimes toggles the scroll bar (on->off->on) causing super annoying flashing (because the UI resizes).

## Possible Solution
Paper UI doesn't touch scroll bar behaviour at all.

## Steps to Reproduce (for Bugs)
1. Open Paper UI
2. Open configuration page, remove something from a long list of items

## Your Environment
* Version used: Latest in stretch's repositories + MySensors binding + InfluxDB persistence
* Environment name and version: Latest in stretch's repositories. Chrome 67 (behaviour existed in previous versions too, I just now got annoyed enough to report)
* Operating System and version: Raspbian GNU/Linux 9.4 (stretch) and Chrome on Windows 10

**Comment by wborn** [comment]
Please use the Eclipse SmartHome [issue tracker](https://github.com/eclipse/smarthome/issues) for reporting Paper UI issues.
That's the repository that contains the Paper UI source code.
