### ISSUE TITLE
[KNX2] Using free group address style causes KNXFormatException: invalid group address: 

### ISSUE THREAD

**Issue by kobold81** [openhab/openhab2-addons#3735]
## Expected Behavior
Using group address 0/0/313 triggers the action as programmed and available in ets5.
Option for the user to use the free group address style instead of the 2-tier or 3-tier (31/7/255) style

## Current Behavior
some group addresses like 0/0/329 and 0/0/330 work as expected in openhab, while others like 0/0/313 throw an 

## Possible Solution
support for free group address style.

## Steps to Reproduce (for Bugs)

1.
2.

## Context
Exception:
> 
>     2018-07-14 22:43:31.500 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception
> 
>     java.lang.IllegalArgumentException: tuwien.auto.calimero.KNXFormatException: invalid group address: 0/0/314
> 
>     at org.openhab.binding.knx.internal.channel.AbstractSpec.toGroupAddress(AbstractSpec.java:50) ~[?:?]
> 
>     at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:?]
> 
>     at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:?]
> 
>     at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:?]
> 
>     at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:?]
> 
>     at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:?]
> 
>     at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
> 
>     at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:?]
> 
>     at org.openhab.binding.knx.internal.channel.ListenSpecImpl.(ListenSpecImpl.java:35) ~[?:?]
> 
>     at org.openhab.binding.knx.internal.channel.KNXChannelType.lambda$2(KNXChannelType.java:186) ~[?:?]
> 
>     at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:?]
> 
>     at java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1574) ~[?:?]
> 
>     at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:?]
> 
>     at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) ~[?:?]
> 
>     at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:?]
> 
>     at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:?]
> 
>     at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:?]
> 
>     at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
> 
>     at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[?:?]
> 
>     at org.openhab.binding.knx.internal.channel.KNXChannelType.getListenSpec(KNXChannelType.java:188) ~[?:?]
> 
>     at org.openhab.binding.knx.internal.handler.DeviceThingHandler.lambda$8(DeviceThingHandler.java:270) ~[?:?]
> 
>     at org.openhab.binding.knx.internal.handler.DeviceThingHandler.withKNXType(DeviceThingHandler.java:121) ~[?:?]
> 
>     at org.openhab.binding.knx.internal.handler.DeviceThingHandler.onGroupWrite(DeviceThingHandler.java:269) ~[?:?]
> 
>     at org.openhab.binding.knx.internal.handler.DeviceThingHandler.onGroupReadResponse(DeviceThingHandler.java:259) ~[?:?]
> 
>     at org.openhab.binding.knx.internal.client.AbstractKNXClient$1.lambda$2(AbstractKNXClient.java:121) ~[?:?]
> 
>     at org.openhab.binding.knx.internal.client.AbstractKNXClient.lambda$8(AbstractKNXClient.java:254) ~[?:?]
> 
>     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
> 
>     at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
> 
>     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
> 
>     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
> 
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
> 
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
> 
>     at java.lang.Thread.run(Thread.java:748) [?:?]
> 
>     Caused by: tuwien.auto.calimero.KNXFormatException: invalid group address: 0/0/314
> 
>     at tuwien.auto.calimero.GroupAddress.init(GroupAddress.java:301) ~[?:?]
> 
>     at tuwien.auto.calimero.GroupAddress.(GroupAddress.java:128) ~[?:?]
> 
>     at org.openhab.binding.knx.internal.channel.AbstractSpec.toGroupAddress(AbstractSpec.java:48) ~[?:?]
> 
>     … 32 more
> 
>     Caused by: tuwien.auto.calimero.KNXIllegalArgumentException: address group out of range
> 
>     at tuwien.auto.calimero.GroupAddress.init(GroupAddress.java:308) ~[?:?]
> 
>     at tuwien.auto.calimero.GroupAddress.init(GroupAddress.java:297) ~[?:?]
> 
>     at tuwien.auto.calimero.GroupAddress.(GroupAddress.java:128) ~[?:?]
> 
>     at org.openhab.binding.knx.internal.channel.AbstractSpec.toGroupAddress(AbstractSpec.java:48) ~[?:?]
> 

## Your Environment
openhab 2.3

**Comment by sjka** [comment]
Having had a quick look, it seems like calimero indeed would support the free GA style notation when supplied without any `/` in there - which doesn't help _you_ much yet, as `KNXChannelType` isn't prepared for these. It'll need to be fixed.
