### ISSUE TITLE
[hueemulation] Tagging two items with the same attached channel causes a WARN log entry from ManagedMetadataProviderImpl with 2.3.0

### ISSUE THREAD

**Issue by cee-dee** [openhab/openhab2-addons#3755]
## Expected Behavior
If the are two items configured using the same channel, whereas both items are tagged with ["Switchable"], the binding should be able to handle this without problems. See context for an explanation of the use case.

## Current Behavior
If the are two items configured using the same channel, whereas both items are tagged with ["Switchable"], there will be warning displayed on system startup:
```
2018-07-20 16:39:05.671 [WARN ] [mon.registry.AbstractManagedProvider] - Could not update element with key _tags:IswitchableSfWrMonitor in ManagedMetadataProviderImpl, because it does not exists.
2018-07-20 16:39:05.681 [WARN ] [mon.registry.AbstractManagedProvider] - Could not update element with key _tags:IswitchableSfWrMonitor_Shortcut in ManagedMetadataProviderImpl, because it does not exists. 
```

## Possible Solution
I do not have a solution, but I'm willing to assist in investigation -- just let me know what to do.

## Steps to Reproduce (for Bugs)
1. Remove all ["Lighting"] tags from items. (I do not use this tag in my setup.)
2. Create two items using the same channel.
3. Tag those two items with ["Switchable"].
4. Restart openHAB.
5. Watch openhab.log.

## Context
I want to voice-address items via different names as different persons use a different language, so I create multiple items using different labels, but every item tagged with ["Switchable"].

## Your Environment
Hardware: Raspberry Pi Model 3 Model B+
OS: Linux 4.14.52-v7+
openjdk version "1.8.0_152"
OpenJDK Runtime Environment (Zulu Embedded 8.25.0.76-linux-aarch32hf) (build 1.8.0_152-b76)
OpenJDK Client VM (Zulu Embedded 8.25.0.76-linux-aarch32hf) (build 25.152-b76, mixed mode, Evaluation)
openHAB version: openHAB 2.3.0-1 (Release Build)

**Comment by davidgraeff** [comment]
OH 2.4: Should work now after the refactoring.
