### ISSUE TITLE
[OSRAM/Sylvania Lightify/SMART+ Binding] E

### ISSUE THREAD

**Issue by cee-dee** [openhab/openhab2-addons#3756]
I'm referring to the market place binding in version market:binding-3560149 - 1.0:
https://github.com/mjagdis/openhab2-addons/tree/osramlightify/addons/binding/org.openhab.binding.osramlightify

## Expected Behavior
On startup of the system there should be no ERRORs displayed in the log.

## Current Behavior
On startup there are a couple of WARNs and ERRORs logged, see attached file.
The actual operation of the plugin does not seem to be compromised.

Additional information.
Maybe the initial errors are compensated later on. One could assume that since the items come online later on, as can be seen in the attached log as well.
[abbreviated.log](https://github.com/openhab/openhab2-addons/files/2216898/abbreviated.log)

## Possible Solution
I do not have a solution, but I'm willing to assist in investigation -- just let me know what to do.

## Steps to Reproduce (for Bugs)
1. Install the binding from the market place.
2. Configure items with links to Osram channels.
3. Tag items with ["Switchable"] (unclear if needed for reproduction)
4. Reboot system.
5. Watch out in the logs.

## Context
For confidence in the system it helps not to have any exceptions in the logs.

## Your Environment
Hardware: Raspberry Pi Model 3 Model B+
OS: Linux 4.14.52-v7+
openjdk version "1.8.0_152"
OpenJDK Runtime Environment (Zulu Embedded 8.25.0.76-linux-aarch32hf) (build 1.8.0_152-b76)
OpenJDK Client VM (Zulu Embedded 8.25.0.76-linux-aarch32hf) (build 25.152-b76, mixed mode, Evaluation)
openHAB version: openHAB 2.3.0-1 (Release Build)

**Comment by mjagdis** [comment]
It's a known problem. The latest ESH release adopted by the latest openHAB release changed the API for handling firmware information. We didn't really use it except for making some information available so the API breakage has no effect other than to spew errors on start up. I haven't had the free time to remove it yet though.

**Comment by kaikreuzer** [comment]
@cee-dee, please do not open any issues for code that is not within this repository - better comment on the open PR https://github.com/openhab/openhab2-addons/pull/2486.

In any case, it is a good reminder that it would be nice to merge that PR soon - afaics, it is still waiting for some clean-up, correct, @mjagdis? Please ping me once you think it is ready to be merged - thanks!
