### ISSUE TITLE
[openhabcloud] Add a online status too thing 

### ISSUE THREAD

**Issue by sharpy420** [openhab/openhab2-addons#3760]
Im not fully sure how this works around here this is my first post.

this should report if the local machine is still connected too the openhab cloud too help with random disconnects and allow rules too function differently depending on the cloud connector status this is not currently possible

**Comment by davidgraeff** [comment]
The problem is that openHAB services do not have a status like Things do. That will change for a later openHAB release, for now there is nothing that can be done except watching the log file.
