### ISSUE TITLE
[network] Ping response state changes are slow

### ISSUE THREAD

**Issue by dastrix80** [openhab/openhab2-addons#3761]
Hi Guys

Running OH2.3 Stable, with the network binding

240 │ Active   │  80 │ 2.3.0                  │ Network Binding

Im using this to detect if my TV is on, by ping 192.168.0.200. It works fine however my issue is im using a rule to detect the TV state and the state is not being updated quick enough, its taking up to 1 minute in some instances.

All devices on a gigabit LAN, pings work and fail as expected when I turn the unit on/off so I know its not a network related issue.

Ive tried a log:set DEBUG org.openhab.binding.network but I get no output

The log does show the THING being updated, but again, slowly. I want very rapid state detection, less than 1 second for this device.

Thanks
Kris

**Comment by dastrix80** [comment]
**06:42:06.339 [INFO ] [smarthome.event.ItemCommandEvent     ] - Item 'TV' received command TVOnOff**
06:42:35.302 [INFO ] [smarthome.event.ThingUpdatedEvent    ] - Thing 'yamahareceiver:zone:dce3432d:Main_Zone' has been updated.
06:42:35.346 [INFO ] [smarthome.event.ThingUpdatedEvent    ] - Thing 'yamahareceiver:zone:dce3432d:Zone_2' has been updated.
06:42:35.354 [INFO ] [smarthome.event.ThingUpdatedEvent    ] - Thing 'yamahareceiver:zone:dce3432d:Zone_4' has been updated.
06:42:35.382 [INFO ] [smarthome.event.ThingUpdatedEvent    ] - Thing 'yamahareceiver:zone:dce3432d:Zone_3' has been updated.
06:42:35.687 [INFO ] [smarthome.event.ItemStateChangedEvent] - OpenHAB_Storage_Available changed from 19590 to 19589
06:42:36.688 [INFO ] [smarthome.event.ItemStateChangedEvent] - OpenHAB_Storage_Available changed from 19589 to 19590
06:42:40.420 [INFO ] [smarthome.event.ItemStateChangedEvent] - OpenHAB_Cpu_SystemUptime changed from 692.2 to 693.2
06:42:40.421 [INFO ] [smarthome.event.ItemStateChangedEvent] - OpenHAB_Storage_Available changed from 19590 to 60.6
06:42:40.423 [INFO ] [smarthome.event.ItemStateChangedEvent] - OpenHAB_Network_DataSent changed from 928 to 938
06:42:40.425 [INFO ] [smarthome.event.ItemStateChangedEvent] - OpenHAB_Network_PacketsRecevied changed from 1843146 to 1852915
06:42:40.427 [INFO ] [smarthome.event.ItemStateChangedEvent] - OpenHAB_Storage_Used changed from 12748 to 39.4
06:42:40.430 [INFO ] [smarthome.event.ItemStateChangedEvent] - OpenHAB_Cpu_Load changed from 1.7 to 2.4
06:42:40.433 [INFO ] [smarthome.event.ItemStateChangedEvent] - OpenHAB_Network_DataReceived changed from 1794 to 1805
06:42:40.434 [INFO ] [smarthome.event.ItemStateChangedEvent] - OpenHAB_Network_DataRecevied changed from 1794 to 1805
06:42:40.438 [INFO ] [smarthome.event.ItemStateChangedEvent] - OpenHAB_Network_PacketsSent changed from 1193156 to 1201079
06:42:40.698 [INFO ] [smarthome.event.ItemStateChangedEvent] - OpenHAB_Storage_Available changed from 60.6 to 19590
06:42:40.700 [INFO ] [smarthome.event.ItemStateChangedEvent] - OpenHAB_Storage_Used changed from 39.4 to 12748
**06:42:49.227 [INFO ] [smarthome.event.ItemStateChangedEvent] - TVStatus changed from OFF to ON**

**Comment by wborn** [comment]
Did you also try lowering the refresh interval?

![refresh](https://user-images.githubusercontent.com/12213581/47968097-55c39580-e065-11e8-8f79-5b2d071f2bab.png)

**Comment by chhorisberger** [comment]
I've been seeing the same behavior on my oh2 instance (ubuntu server 18.04) as well. my rule was pinging my mobile phone in order to set a hue light color. response times vary wildly between 10 seconds and one minute

**Comment by dastrix80** [comment]
Thanks I made those changes with some aggressive timings and its alot faster for me. Seems theres a bug in the binding with respect to timers using the UI
