### ISSUE TITLE
[yeelight] Add additional channels & controls from API

### ISSUE THREAD

**Issue by kmcbride3** [openhab/openhab2-addons#3763]
Looking through the Developer API documentation - it appears there are a number of unimplemented channels/controls for these devices.

Namely, only the brightness (bright), color (which appears to be an implementation of rgb - but as a percentage for each of the component values), and colorTemperature (CT). Even then, not all controls are available for the various Yeelight devices - for example, I cannot control the brightness of my Yeelight LED color light strip via OpenHAB, but I can via the native app.

We have no way of setting many of the other attributes/controls such as color_mode, delayoff, or the flow controls (for moving/pulsing lights). In fact, there isn't a method to simply toggle the light on and off (a software replication of the on-off button).

Appreciate all the work that's gone into this so far - hope that in the near future the additional controls outlined in Table 4-2 on Page 21 of the Inter-Operation Specification guide (https://www.yeelight.com/download/Yeelight_Inter-Operation_Spec.pdf) can be implemented for greater control over our Yeelight products.

**Comment by goodfore** [comment]
Thank you for providing the Spec. We can certainly look into some of the controls, such as color_mode.

The flow needs some more investigating. It needs flow parameters, which not sure how to fit it into openhab model. We can make a channel, but how do we supply the flow parameters?

Can flow and delay off etc, be done on openhab rules? Assuming rgb and CT is working correctly.

I only have the white bulbs, so I don't really know what what's the difference between RGB and HSV, and no CT on white bulb either. I am working in implementing adding duration the controls, which I should be able to submit a PR soon for that.

Thanks,
Joe

**Comment by alexeinz** [comment]
Hi I have both color and white bulbs , I can assist somewhat if needed.
I think, as long as we could have exposed control channel to send commands to the bulb, it probably could address most functionality : 
You may be able to send a ‘custom command’ to the lamp
set_power [“on|off”, “smooth”, 5000]

it may even need a mode after the 5000 part.e.g. set_power ["on", "smooth", 5000,1]

0: last mode
1: normal mode
2: rgb mode
3: hsv mode
4: color flow
5: moonlight

For exposed commands, there is the https://gitlab.com/stavros/yeecli/ which I currently use to be able to control modes / scenes /flows somewhat , its very clear python utility 



t# yeecli                                                                                                    
Usage: yeecli [OPTIONS] COMMAND [ARGS]...                                                                                                            
                                                                                                                                                     
  yeecli is a command-line utility for controlling the YeeLight RGB LED                                                                              
  lightbulb.                                                                                                                                         
                                                                                                                                                     
Options:                                                                                                                                             
  --version                   Show the version and exit.                                                                                             
  --ip IP                     The bulb's IP address.                                                                                                 
  --port PORT                 The bulb's port.                                                                                                       
  -e, --effect EFFECT         The transition effect.                                                                                                 
  -d, --duration DURATION_MS  The transition effect duration.                                                                                        
  -b, --bulb NAME             The name of the bulb in the config file.                                                                               
  --auto-on / --no-auto-on    Whether to turn the bulb on automatically before                                                                       
                              a command (on by default).                                                                                             
  -h, --help                  Show this message and exit.                                                                                            
                                                                                                                                                     
Commands:                                                                                                                                            
  brightness   Set the brightness of the bulb.                                                                                                       
  hsv          Set the HSV value of the bulb.                                                                                                        
  preset       Various presets.                                                                                                                      
  pulse        Pulse the bulb in a specific color.                                                                                                   
  rgb          Set the RGB value of the bulb.                                                                                                        
  save         Save the current settings as default.                                                                                                 
  status       Show the bulb's status.                                                                                                               
  temperature  Set the color temperature of the bulb.                                                                                                
  toggle       Toggle the bulb's state on or off.                                                                                                    
  turn         Turn the bulb on or off.                                                                                                              
root@AutomationServer:/home/homeassistant# yeecli --ip 192.168.100.150 status                                                                        
                                                                                                                                                     
Bulb parameters:                                                                                                                                     
* hue: None                                                                                                                                          
* color_mode: 2                                                                                                                                      
* name: None                                                                                                                                         
* power: on                                                                                                                                          
* music_on: 0                                                                                                                                        
* delayoff: 0                                                                                                                                        
* rgb: None                                                                                                                                          
* bright: 64                                                                                                                                         
* flowing: 0                                                                                                                                         
* ct: 3313                                                                                                                                           
* sat: None                                                                                                                                          
root@AutomationServer:/home/homeassistant# yeecli --ip 192.168.100.150 preset                                                                        
Usage: yeecli preset [OPTIONS] COMMAND [ARGS]...                                                                                                     
                                                                                                                                                     
  Various presets.                                                                                                                                   
                                                                                                                                                     
Options:                                                                                                                                             
  -h, --help  Show this message and exit.                                                                                                            
                                                                                                                                                     
Commands:                                                                                                                                            
  alarm         A red alarm.                                                                                                                         
  christmas     Christmas lights.                                                                                                                    
  disco         Party!                                                                                                                               
  lsd           Christmas lights.                                                                                                                    
  police        Police lights.                                                                                                                       
  police2       More police lights.                                                                                                                  
  random        Random colors.                                                                                                                       
  redgreenblue  Change from red to green to blue.                                                                                                    
  slowdown      Cycle with increasing transition time.                                                                                               
  stop          Stop any currently playing presets and return to the prior...                                                                        
  strobe        Epilepsy warning.                                                                                                                    
  temp          Slowly-changing color temperature.                                                                                                   
root@AutomationServer:/home/homeassistant# yeecli --ip 192.168.100.150 pulse                                                                         
Usage: yeecli pulse [OPTIONS] HEX_COLOR                                                                                                              
Try "yeecli pulse -h" for help.                                                                                                                      
                                                                                                                                                     
Error: Missing argument "HEX_COLOR".                                                                                                                 
root@AutomationServer:/home/homeassistant# yeecli --ip 192.168.100.150 pulse -h                                                                      
Usage: yeecli pulse [OPTIONS] HEX_COLOR                                                                                                              
                                                                                                                                                     
  Pulse the bulb in a specific color.                                                                                                                
                                                                                                                                                     
Options:                                                                                                                                             
  -p, --pulses COUNT  The number of times to pulse.                                                                                                  
  -h, --help          Show this message and exit.

**Comment by goodfore** [comment]
@alexeinz I think to begin, a custom command channel would be good. Let me give that a try.

Thanks,
Joe

**Comment by goodfore** [comment]
@alexeinz and @kmcbride3 I have a jar ready with the command channel, would you help me test? I only have white bulbs so not much command I can test with.

Thanks,
Joe

**Comment by kmcbride3** [comment]
@goodfore Sure, I should be able to play with it this weekend.

**Comment by goodfore** [comment]
@kmcbride3 Assuming you know how to stop/uninstall bundles, please download the test bundle [here](https://d.pr/free/f/2haof0). Once downloaded, rename it from .zip to .jar.

Please delete all Yeelight things first, then stop/uninstall 2.4 yeelight bundle and then add in the test bundle. Finally re-add all the things.

Once you have things added, you will see a command channel. Map it to a String item. I ususally use rules to send commands, e.g.

```
rule "Yeelight Custom Command"
when
        Item StudyRoom_Yeelight_Trigger received command
then
        StudyRoom_Yeelight_Command.sendCommand("set_power;\"on\",\"smooth\",2000")
end
```

Note that `set_power` is the command, then a separator `;` must be used. `\"on\",\"smooth\",2000` are the parameters.

Thanks,
Joe

**Comment by goodfore** [comment]
@kmcbride3 Have you a chance to test new binding?

**Comment by kmcbride3** [comment]
Sorry, finally had a chance to load it up and play around with it.

Couple of observations;
set_power seems to work as designed for using the on and off options. I couldn't seem to confirm whether the optional "mode" parameter worked. It will turn on the device with modes of 0-3, but ignores 4 (not sure about 5, as it isn't expected to work on my lightstrip).

Everything else appears to work (though I tried "cron_add" with success, I did not try "cron_get" or "cron_del"). I also did not play with "set_music", "set_name", nor the 'adjust' or 'dev' commands.

Great work! I would suggest adding a 'switch' type to the binding to give OpenHAB the ability to turn the lights on/off without having to send a toggle command via that type as a future change, but I think this is advanced enough to integrate into my overall system.

Thanks for putting in the work on this!

**Comment by goodfore** [comment]
@kmcbride3 thanks for testing.

If you look at the spec, I think mode is only 0 to 3, and it seems to be a optional parameter.

Have you tried binding a switch item to the color channel, to turn the light on and off?

Thanks,
Joe

**Comment by kmcbride3** [comment]
That seems to work, thanks, 

From a user friendly perspective, it would be nice if that option was available automatically when adding a Yeelight to the system.

**Comment by alexeinz** [comment]
sorry didnt see this... will test this evening at home and report back
------
Regards
Alex Einz

Tel - +81(0) 80-6749-1800
dj@alexeinz.info
http://www.alexeinz.info

Weekly quote:
“The true sign of intelligence is not knowledge but imagination
 - Albert Einstein

**Comment by alexeinz** [comment]
Trying, but have limited success,
was the command set used from the official api doc?
https://www.yeelight.com/download/Yeelight_Inter-Operation_Spec.pdf

**Comment by goodfore** [comment]
The channel doesn't check for which command. So as long as the device supports that command, it should work. Mind posting what you tired?

Thanks,
Joe
