### ISSUE TITLE
Milight Gateway V3 Discovery Packet Error Wrong IP Address in Log

### ISSUE THREAD

**Issue by asking23** [openhab/openhab2-addons#3798]
## Current Behavior

I am having Milight Wifi Gateway/Bridge v3, I am getting Continous Error logs in Openhab logs.

My IP address for Gateway/Bridge is 192.168.1.135, but in logs continous it reflects wrong ip address.

> 2018-08-04 21:34:48.963 [ERROR] [ht.internal.protocol.MilightDiscover] - Sending a V3 discovery packet to 192.168.1.136 failed. Socket is closed
> 
> 2018-08-04 21:34:48.965 [ERROR] [ht.internal.protocol.MilightDiscover] - Sending a V6 discovery packet to 192.168.1.136 failed. Socket is closed
> 
> 2018-08-04 21:34:49.167 [ERROR] [ht.internal.protocol.MilightDiscover] - Sending a V3 discovery packet to 192.168.1.136 failed. Socket is closed
> 
> 2018-08-04 21:34:49.169 [ERROR] [ht.internal.protocol.MilightDiscover] - Sending a V6 discovery packet to 192.168.1.136 failed. Socket is closed
> 
> 2018-08-04 21:34:49.370 [ERROR] [ht.internal.protocol.MilightDiscover] - Sending a V3 discovery packet to 192.168.1.136 failed. Socket is closed
> 
> 2018-08-04 21:34:49.372 [ERROR] [ht.internal.protocol.MilightDiscover] - Sending a V6 discovery packet to 192.168.1.136 failed. Socket is closed

![image](https://user-images.githubusercontent.com/6546108/43698855-ba0050f8-9969-11e8-922f-2a907241d6fd.png)

## Steps to Reproduce (for Bugs)

1. I aleady tried to uninstall Binding and Re-install, but no effects.
2.

## Context

How to get rid off this issue ? my logs is crazy filled with all Errors

## Your Environment

* Version used: (e.g., openhab and addon versions)
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):
Openhab Version 2.2
Milight Binding

**Comment by davidgraeff** [comment]
Thanks for the report. Will be fixed.
