### ISSUE TITLE
HM-PBI-4-FM not working with binding homeatic

### ISSUE THREAD

**Issue by sascha777** [openhab/openhab2-addons#3807]
Hi,

I am new to openhab 2.3.0-1 running on a pi 3 with an HM-MOD-RPI-PCB module and yahm 2.8.6.
I have some things and items from binding homeatic already up and running but struggle to get my new homeatic HM-PBI-4-FM (firmware 1.5) adressed. 

The HM-PBI-4-FM is properly configured in yahm and successfully tested as well. The paperUi automatically detects the new thing without any error. In VS Code I also added a new item for channel 1 pressShort (tried in paperUi as well). 

`Switch HM_EG_WZ_Schliesskontakt_1_State {channel="homematic:HM-PBI-4-FM:PEQ01xxxxx:OEQ11xxxxx:1#PRESS_SHORT"}`

Normally I see all my items state changes in the log and expected the HM-PBI-4-FM to do so too.
But when triggering the HM-PBI-4-FM I don't see any logs written nor does my rule fire.

I assume this is a bug in the binding. Could someone please check on that?

Regards,
Sascha

**Comment by wborn** [comment]
The Homematic binding source code is nowadays part of the Eclipse SmartHome repository. 
Can you create an issue for this in the ESH [issue tracker](https://github.com/eclipse/smarthome/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+homematic)?

**Comment by sascha777** [comment]
Hi wborn, thanks for the info!
I'll post it over there.
