### ISSUE TITLE
Pioneer binding support for VSX-932

### ISSUE THREAD

**Issue by CodingSpiderFox** [openhab/openhab2-addons#3817]
I'm running openhab 2.3 and I want to control my Pioneer VSX-932 remotely.
Is the support for this model already being added? I looked at the network traffic, the commands seem to be quite different than those for the older devices.

```
....!1MVLQSTN
ISCP.......
....!1MVL68.
ISCP.......
....!1TFRQSTN
ISCP............!1TFRB+1T+1.
ISCP.......
....!1CTLQSTN
ISCP............!1CTL-04.
ISCP.......
....!1SWLQSTN
ISCP............!1SWL+18.
ISCP.......
....!1TUNQSTN
ISCP.......
....!1TUN08750.
ISCP.......
```
(copied from wireshark)

I would implement it but I have soo many questions on the whole ecosystem so I would need quite a lot of support from you experienced addon developers ;)

**Comment by hechtersheim** [comment]
You can use the onkyo binding (see: https://github.com/openhab/openhab2-addons/issues/3509). There is a problem with the volume mapping though, so the volume range is limited.

**Comment by CodingSpiderFox** [comment]
Thanks!
