### ISSUE TITLE
[Tesla] Java error when installing / using binding

### ISSUE THREAD

**Issue by sstadlberger** [openhab/openhab2-addons#3866]
## Expected Behavior
Installing and using the binding as per documentation

## Current Behavior
Installation is shown as succesfull in the UI but the following output is written into the logs:
`10:56:25.123 [ERROR] [org.openhab.binding.tesla            ] - [org.openhab.binding.tesla.internal.command.TeslaCommandExtension(226)] Error during instantiation of the implementation object
java.lang.RuntimeException: java.lang.ClassNotFoundException: org.glassfish.jersey.client.JerseyClientBuilder cannot be found by javax.ws.rs-api_2.0.1
	at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:103) ~[?:?]`
See full errors in log:
[install.log.txt](https://github.com/openhab/openhab2-addons/files/2321463/install.log.txt)

When using the binding in the UI the thing can be added but it's shown as uninitialized with an error message.
`10:57:26.982 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'tesla:models:8fdf60c2' changed from UNINITIALIZED to UNINITIALIZED (HANDLER_REGISTERING_ERROR): org.glassfish.jersey.client.JerseyClientBuilder cannot be found by javax.ws.rs-api_2.0.1
`

## Possible Solution
?

## Steps to Reproduce (for Bugs)

1. Install binding
2. Use it

## Context
Use the binding according to the documentation

## Your Environment

* Version used: openHAB 2.3 and openHAB 2.4
* Docker on Synology (x86) with the following Docker images: openhab/openhab:2.3.0-amd64-debian and openhab/openhab:2.4.0-snapshot-amd64-debian
* The issue was reproducible with both versions, including clean installs.

**Comment by kaikreuzer** [comment]
@kgoderis Could you comment?

**Comment by sstadlberger** [comment]
Works now with the latest release. Thanks!
