### ISSUE TITLE
[TP-Link Smart Home] HS110 1.2.5 firmware upgrade causes energy usage issue

### ISSUE THREAD

**Issue by pmknowles** [openhab/openhab2-addons#3869]
## Expected Behavior
Upgraded firmware today. energyUsage on app has
Today =1.05kWh
Past 5 Days = 5.49kWh
Past 30 Days = 21.1kWh
CurrentPower =130W
## Current Behavior
CurrentPower = 130W
TV Energy = 0.347 (no units)
 
## Possible Solution
Is this because of the firmware upgrade? I think it was working correctly prior to this.

## Context
My graphing of energy daily consumption is failing for this device.
## Your Environment
* Version used: 2.3.0 Release Build
* Environment name and version Java 8:
* Operating System and version Windows 10:
Device = TP-Link HS110 v1.0

**Comment by Hilbrand** [comment]
@pmknowles It is very likely this was caused by the firmware upgrade. There has is a fix for this already merged. This fix is available in the Eclipse Market place version of the binding (FYI The bug has been fixed against version 2.4.0-SNAPSHOT, so I'm not sure if it will work with 2.3)

**Comment by pmknowles** [comment]
OK have amended the rule to calculate the daily values and will wait for 2.4 official release.

**Comment by SoluiNet** [comment]
I'm using openHAB 2.4.0 with binding-tplinksmarthome 2.4.0 on a Synology NAS with a HS110 SmartPlug on firmware version 1.2.5.

I've still got an issue with the energyUsage readings as well with all other properties except of switch. None of these properties seem to be readable from my SmartPlug.

If I take a look via HABmin all properties (except of Switch) are returned as None/Null.

**Comment by pmknowles** [comment]
My HS110 is on fw 1.2.5 and I'm running OH 2.4.0 and it's fine
The items are
`Switch TV "TV Switch" (LivingRoom) [ "Switchable" ] { channel="tplinksmarthome:hs110:TV:switch" }
Number TV_Power "TV Power" (LivingRoom) { channel="tplinksmarthome:hs110:TV:power" }
Number TV_Energy "TV Energy" (LivingRoom) { channel="tplinksmarthome:hs110:TV:energyUsage" }
Number TV_RSSI "TV RSSI" (LivingRoom) { channel="tplinksmarthome:hs110:TV:rssi" }
Number TV_LED "TV LED" (LivingRoom) { channel="tplinksmarthome:hs110:TV:led" }
`
And the things
`Thing tplinksmarthome:hs110:TV "TV" @ "Living Room" [deviceId="xxx", refresh=10 ]`

**Comment by Hilbrand** [comment]
@SoluiNet please don't post other problems on closed Issues. Either create a new issue if you know what causes this or post to the openHAB forum and we can help you identifying where the problem is.
