### ISSUE TITLE
No Sitemap Values with the Systeminfo Binding

### ISSUE THREAD

**Issue by luismauriz1** [openhab/openhab2-addons#3882]
Hello,
I installed the Systeminfo Binding on my Rpi 3. In the PaperUI, I get some Values of the Pi (Memory, CPU....) But when I write these Items to a Sitemap, they Show in the Sitemap no Value. Nothing. 
Thanks for your help!
![unbenannt](https://user-images.githubusercontent.com/36296227/44960490-def10b80-af00-11e8-9a2c-d1686c1c2f3f.PNG)

**Comment by cweitkamp** [comment]
@luismauriz1 can you please provide some information about your item configuration and or the sitemap? How does your setup look like? Can you post an example?

**Comment by luismauriz1** [comment]
Hi,
Okay. I Have a Raspberry 3B+ with the Latest Debian Rasberian. Latest OpenHab.
Every Item and Binding is working. With the exeption of this Systeminfo Binding.
Here is My Item Config:
![asdf](https://user-images.githubusercontent.com/36296227/45000862-9ac93e00-afc8-11e8-873a-95612ae1130a.PNG)

And here is my Sitemap Config:
![unbenannt](https://user-images.githubusercontent.com/36296227/45000869-a583d300-afc8-11e8-9d33-865b2f81b648.PNG)

**Comment by luismauriz1** [comment]
Ok, I found out that my stupidness killed my head ;) I have to take the First Name of the item, not the Label, Problem is solved.
