### ISSUE TITLE
[TP-Link Smart Home] Color Temperature ignored on Chanel Update

### ISSUE THREAD

**Issue by mgoellnitz** [openhab/openhab2-addons#3883]
## Expected Behavior

The color temperature of a bulb device stays stored as the item state.

## Current Behavior

When setting a new color temperature, that item value is stored internally and correctly transformed to kelvin value for communication with the device. After a periodic channel update (every 30s by default), that value gets overridden by UNDEF.

## Possible Solution

The color temperature values sent from the device are not handled on channel update and result in that UNDEF value.

## Steps to Reproduce (for Bugs)

* Change color temperature and have a look at the item update logging.

* Change the color temperature by Kasa app and note the missing update in OpenHAB UIs. (Do the same for brightness and see the success case.)

## Your Environment

* Version used: Open HAB 2.3

**Comment by Hilbrand** [comment]
@mgoellnitz Thanks for reporting the bug. I've created a bug fix that already has been merged! This should fix the bug. The tp-link binding in the Eclipse market place has been updated and contains the fixed version. (FYI The bug has been fixed against version 2.4.0-SNAPSHOT, so I'm not sure if it will work with 2.3)

**Comment by cweitkamp** [comment]
Thank you both.

Closed due to #3884.
