### ISSUE TITLE
Get Error with the Wether Underground Binding when Pasting into Sitemap

### ISSUE THREAD

**Issue by luismauriz1** [openhab/openhab2-addons#3887]
Hello,
I Use the Latest OH Version on My Rpi. All Bindings are working fine. Except of the WU Binding. First of all, I Got at mostly all Values behind the Number in the PaperUI a "Undefinded". And when I Paste these Items to the Sitemap, I got an err.
Here is a Screenshot of my Item Config:
![unbenannt12](https://user-images.githubusercontent.com/36296227/45003197-1da9c300-afe0-11e8-9456-9ed75235028b.PNG)

Here is a Screenshot of my PaperUI with the "Undefinded"
![unbenannt](https://user-images.githubusercontent.com/36296227/45003200-2c907580-afe0-11e8-9a3b-b5107f50ece0.PNG)
 Here is the Sitemap Screenshot:
![unbenannt123](https://user-images.githubusercontent.com/36296227/45003203-387c3780-afe0-11e8-8e8d-f1074c5be0ff.PNG)

**Comment by luismauriz1** [comment]
Hi,
thanks for your fast answer!
I configured the binding with the API and the Location. I think without the API, I won't get any value.
Yes, the Thing is Online. I get Wether Informations, but not with the Unit. And not in the Sitemap.
Thanks.

**Comment by HerzScheisse** [comment]
try to add the placeholder in sitemap like in the pressure item

`"WU Temperature [%.1f °C]"`

**Comment by luismauriz1** [comment]
I Forgot to wrote that at the beginning... At the Pressure, the Placeholder is working fine. But at the Temperatures, I get in the PUI a `"-"`. And in the Sitemap is a `"-°C"` So, I get with this tip no values.

**Comment by HerzScheisse** [comment]
which OH version are you using?

if you are on the latest... please check https://www.openhab.org/addons/bindings/weatherunderground/#channels

**Comment by luismauriz1** [comment]
OK. I Think we got it!
In my Items I Only wrote "Number" and not "Number:Temperature". This is a Significant Step. I try the rest of the Items tomorrow. When I don't have further problems, I close the Issue.
Thank you @HerzScheisse for your Great help!!!

**Comment by cweitkamp** [comment]
Please use the [openHAB Community](https://community.openhab.org/) for discussion and further questions. Thanks.
