### ISSUE TITLE
[squeezebox] 100% CPU load if squeezebox server is not reachable

### ISSUE THREAD

**Issue by maniac103** [openhab/openhab2-addons#3888]
If the squeezebox server socket is not reachable, the squeezebox binding causes OpenHAB to draw 100% CPU time.

## Expected Behavior
The binding shouldn't cause 100% CPU load (presumably caused by constantly retrying server socket connection), but instead wait a bit (5 seconds? 10 seconds? something in that ballpark...) before attempting reconnection

## Current Behavior
See above

## Steps to Reproduce (for Bugs)
1. Enable squeezebox binding in OpenHAB
2. Stop squeezebox server

## Context
I encountered this after upgrading my server to a new distro version. I was digging into why OpenHAB was shown drawing 200% CPU time in top, and it took my quite a while to realize it's connected to squeezebox server needing an update after said distro update.

## Your Environment
* OpenHAB 2.3
* LMS 7.9 (later 7.9.1)
* Ubuntu 18.04 LTS

**Comment by mhilbush** [comment]
Thanks for the report. Hmm. It's supposed to try to reconnect every 60 seconds.

But, you're right. My last change broke the 60 second reconnect...

**Comment by maniac103** [comment]
Thanks for the quick fix!
