### ISSUE TITLE
[Homematic] Errors like Connection refused are permanent

### ISSUE THREAD

**Issue by Flole998** [openhab/openhab2-addons#3893]
I'm using the Homematic binding to communicate with my Homegear Installation. Unfortunately when I reboot or disable the homegear service, the gateway and all items go offline with "no route to host" or "connection refused" error until the bundle is restartet. I would expect automatic reconnection in this case.

**Comment by kaikreuzer** [comment]
Please report at https://github.com/eclipse/smarthome/issues as this is there the Homematic binding lives.
