### ISSUE TITLE
[RFXcom] RFXcom Lighting4 sends wrong command code

### ISSUE THREAD

**Issue by TheOriginalMrWolf** [openhab/openhab2-addons#3894]
Hi,

Running openHAB 2.3.0 Release Build with RFXCOM RFXtrx433E installed and working for a number of devices (blinds, gate opener, etc).

Am am now trying to control some fans.  These respond perfectly as Packettype Lighting4 / subtype PT2262 / Pulse 303 usec when controlled directly via RFXmngr.

Control codes are:
- Speed UP - 0xD (13)
- OFF - 0x8 (8)
- FWD/REV - 0x7 (7)
- Speed DOWN - 0x5 (5)
- Learn - 0x2 (2)

However, when I try to control via openHAB UP, OFF, and DOWN do not work.

Looking at TRACE logs (karaf: log:set TRACE org.openhab.binding.rfxcom) I see that rfxcom sends:

- FWD/REV (CORRECT): [TRACE] [rnal.connector.RFXComSerialConnector] - Send data (len=10): 091300000xxxx7012F00 <== command code '7' (after xxxx) sent correctly
- OFF (INCORRECT): [TRACE] [rnal.connector.RFXComSerialConnector] - Send data (len=10): 091300000xxxxF012F00 <== command code '8' munged to 'F'

Unfortunately, it looks like when defining the Thing in Paper UI, command values 5, 8, 13, and 15 are 'UNKNOWN' (that is, not showing as "ON" or "OFF" in Paper UI, instead just "value x"), and when I try to use the value option (ie "value 5") it looks like RFXcom is munging those values to 0xF before sending the command.

Looking into the code (RFXComLighting4Message.java --> public enum Commands implements ByteEnumWrapper) I see that UNKNOWN maps to -1 (0xFFFF -> least significant nibble is 0xF), so that makes sense...

Soooooo...  the question --- how do I force openHAB to send the correct command codes & not 0xF?

Cheers!

**Comment by martinvw** [comment]
How do you trigger the actual sending of the data and can you maybe give some more context of the logging don't forget to wrap them between two \`\`\`

Note that the current code takes the commandId and not the value of the command:

https://github.com/openhab/openhab2-addons/blame/master/addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting4Message.java#L182

I had reports that it worked and I believe its also covered by tests:

```java
testMessage("091300CA0F8D2801AA70", PT2262, "63698", 426, (byte)8, 202, 2, 8, 1);

**Comment by TheOriginalMrWolf** [comment]
Ahhhh, I see.  CommandID works, Command doesn't.

I just created a thing in Paper UI (to be controlled via Paper UI) that represents the fan.  If I configure it to send Command (with a value for each of "on" and "off"), then that doesn't work for 'unknown' commands.

If I instead configure it for CommandID, then I can set a numeric value which gets sent (regardless or not of whether the commands are 'known' -- though it does complain in the log).

Thanks.

**Comment by martinvw** [comment]
No problem!
