### ISSUE TITLE
[onkyo] TX-RZ720 Volume between 0 & 184

### ISSUE THREAD

**Issue by lukas12582** [openhab/openhab2-addons#3906]
## Expected Behavior
Setting the volume to 100% in Openhab should also set the volume on the Onkyo to 100%

## Current Behavior
Setting the volume to 100% in Openhab sets the volume on the Onkyo to 50%
If the volume is set to more than 50% on the amplifier (100%+ on Openhab) the dimmer item will be set to undefined.

## Possible Solution
Something like a manual mapping/switch for the volume which will be sent to the Onkyo.
Standard 0-100 = 0-100
Adapted 0-100 = 0-184

## Steps to Reproduce (for Bugs)
Needs to be tested with a TX-RZ720. or similar?

## Context
I can't set the Onkyo to more than 50% volume via Openhab.
If I am right the normal onkyo amplifiers do a volume range between 0 and 100 but it looks like the TX-RZ720 does a range between 0 and 184.

All other functions are working as expected, just for info ;)

## Your Environment
Onkyo: TX-RZ720
FW: 1081-0020-2050-0010-0000
Binding version: 2.3.0 & self-compiled 2.4.0

## Additional Infos
Setting the Volume via onkyo-eiscp
Lukass-MacBook:~ ldonig$ onkyo --host 192.168.178.30 volume=0
TX-RZ720: master-volume = 0
Lukass-MacBook:~ ldonig$ onkyo --host 192.168.178.30 volume=199
TX-RZ720: master-volume = 184

Event Log from setting the volume on the onkyo :
2018-09-10 20:08:21.360 [vent.ItemStateChangedEvent] - onkyoZ1_Volume changed from 99 to UNDEF
2018-09-10 20:08:23.054 [vent.ItemStateChangedEvent] - onkyoZ1_Volume changed from UNDEF to 100
2018-09-10 20:08:23.159 [vent.ItemStateChangedEvent] - onkyoZ1_Volume changed from 100 to 98

**Comment by lukas12582** [comment]
Looks like this https://github.com/openhab/openhab2-addons/issues/3509 also affects the Onkyo TX-RZ720, I will have a look if this is the right patch for this.

**Comment by lukas12582** [comment]
Hmm okay looks like with the patch mentioned above I could use the extra volumedb number item. But there is no good option to get it together with a slider in the openhab UI's.
I did a patch with the mapping mentioned above for my own system, but the code is really bad so I won't upload it. If someone has the same problem like me I could provide the binding.

**Comment by Ontrackx** [comment]
Onkyo TX-RZ720 i have the same problem in 2.4.0
