### ISSUE TITLE
AVMFritz Binding DECT 200 Support 

### ISSUE THREAD

**Issue by dnobel** [openhab/openhab2-addons#392]
Hello,

is it possible that the DECT 200 for the AVM FritzBinding is not fully supported at the moment? I receive updates for temperature and power but if I link an item to the outlet Channel I get NPE in DeviceHandler when sending a command to it in line 162: https://github.com/openhab/openhab2/blob/master/addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/handler/DeviceHandler.java#L1621

Looking at the code, it seems the connection is only initialized for the PL546E standalone thing type: https://github.com/openhab/openhab2/blob/master/addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/handler/DeviceHandler.java#L83.

Isn´t it possible to switch the DECT 200 or am I doing something wrong?

(see also https://community.openhab.org/t/avmfritz-binding-dect-200-support/2650)

Regards

Dennis

**Comment by kaikreuzer** [comment]
@robbyb67 Could you have a look, please?

**Comment by robbyb67** [comment]
I'll do it shortly.

**Comment by kaikreuzer** [comment]
@robbyb67 Any update on this?

**Comment by kaikreuzer** [comment]
@robbyb67 Any news?

**Comment by hfanieng** [comment]
@robbyb67 would be great if all the functions of one germans biggest supplier of routers will be fully supported with OH2.

discussion continues at the official OH-Forum here:
https://community.openhab.org/t/fritz-dect-200-remains-in-status-initializing-changed-to-binding-reacts-not-on-fixed-status/8148/8
