### ISSUE TITLE
[onewire] Missing source code for OneWire binding version 2

### ISSUE THREAD

**Issue by mgwoj** [openhab/openhab2-addons#3943]
Documentation at page https://www.openhab.org/addons/bindings/onewire1/ mention that version 1 of OneWire binding is obsolete and suggests to use version 2.

> OBSOLETE BINDING
>
> This 1.x binding is obsolete; it has been replaced by the 2.x onewire binding which you should use instead.

There is nice documentation at page https://www.openhab.org/addons/bindings/onewire/ for version 2, however there is no source code for this binding at the https://github.com/openhab/openhab2-addons/tree/master/addons/binding.onewire

## Expected Behavior

Please provide missing source code and make this binding available for installation.

**Comment by martinvw** [comment]
That seems to be a bug in the documentation, it would

**Comment by mgwoj** [comment]
I think you are not right - based on the documentation - OneWire and OneWireGPIO seems to be different bindings. First on is using One Wire Server, second is using only local IO ports.

**Comment by martinvw** [comment]
I asked some clarification to @kaikreuzer who moved it to the legacy bindings 18 days ago.

**Comment by wborn** [comment]
This OneWire binding is part of Eclipse SmartHome repository now so that's why you can't find it in this repository.

[Follow me](https://github.com/eclipse/smarthome/tree/master/extensions/binding/org.eclipse.smarthome.binding.onewire) to find the source code. :smile:

**Comment by J-N-K** [comment]
The OneWire v2 binding is part of ESH, therefore it is in eclipse/smarthome, not in openhab2-addons. It obsoletes the OneWire v1 binding, but not the OneWire GPIO binding.

**Comment by martinvw** [comment]
Great, so the problem might be:

- that @mgwoj might not be the latest snapshot
- that docs does not render links to ESH correctly

**Comment by wborn** [comment]
> that docs does not render links to ESH correctly

The link in the footer is wrong for sure:

> Caught a mistake or want to contribute to the documentation? Edit this page on GitHub

It points to:
https://github.com/openhab/openhab2-addons/edit/master/addons/binding/org.openhab.binding.onewire/README.md

**Comment by wborn** [comment]
Looks like we are missing a feature for thet ESH OneWire binding so it will not show up in the openHAB addons. The website also uses the feature definitions to determine if it is an ESH project and adds a proper footer accordingly. E.g. [Astro Binding](https://www.openhab.org/addons/bindings/astro) has an ESH footer. 

I'll create a openhab-distro PR to add the OneWire binding.

**Comment by wborn** [comment]
> Please provide missing source code and make this binding available for installation.

Thanks for creating the issue. It should be possible to install the binding in the next 2.4.0-SNAPSHOT build (1364 or newer) since it will contain https://github.com/openhab/openhab-distro/pull/765 .

**Comment by mgwoj** [comment]
After updating OpenHab instance to the latest version the binding is available for the installation. 
Thank you for the prompt response.

However link on the page https://www.openhab.org/addons/bindings/onewire/ to edit the document is still pointing to the non-existent location
https://github.com/openhab/openhab2-addons/edit/master/addons/binding/org.openhab.binding.onewire/README.md

**Comment by kaikreuzer** [comment]
I've just triggered https://openhab.ci.cloudbees.com/view/Documentation/job/gather-external-docs/, which should update the docs within the next hour.
