### ISSUE TITLE
[Homematic] Partial no updates from homematic binding

### ISSUE THREAD

**Issue by e36Alex** [openhab/openhab2-addons#3951]
Hello,

i am trying out homematic binding two things, a radiator valve (HM-CC-RT-DN) and a door sensor (HmIP-SRH). if a value of the radiator valve changes, it gets updated in openhab. if the door sensor changes its state, there is no update to openhab - i have to “reload from gateway” to get the new values.

in the log i got no errors (even no entries at loglevel debug or trace), so i even integrated homematic in an test-installation of iobroker - there the state of the sensor changes immidiatly, so it should be a problem on openhab.

actually i am using 2.4.0 Build #1365 but had the same problem on 2.4M2 and 2.4M3.

https://community.openhab.org/t/partial-no-updates-from-homematic-binding/51582

## Expected Behavior
State of the HmIP-SRH should update directly after change.

## Current Behavior
Stata of the HmIP-SRH changes just, if i reload all values from the gateway

## Possible Solution
-

## Steps to Reproduce (for Bugs)
1. Open or close a window
2. Check out, if state in homematic, openhab and iobroker changes

## Context
-

## Your Environment
Distributor ID: Debian
Description: Debian GNU/Linux 9.5 (stretch)
Release: 9.5
Codename: stretch

OpenHAB 2.4.0 Build #1365 but had the same problem on 2.4M2 and 2.4M3

Homematic CCU3

Thanks for help!

Alex

**Comment by kaikreuzer** [comment]
Please note that the homematic binding is part of ESH, so please be so kind and report this issue at https://github.com/eclipse/smarthome/issues instead. Thanks!
