### ISSUE TITLE
Enocean EEP Omnio

### ISSUE THREAD

**Issue by gadjodilo83** [openhab/openhab2-addons#3989]
please add following EEP`s:

D2-01-03 Omnio multi universal dimmer 1-channel 300 VA
D2-01-11 Omnio multi switching actuator 2-channels
D2-01-01 Omnio multi switching actuator 1-channels

thanks!

**Comment by kaikreuzer** [comment]
There isn't even an EnOcean binding in this repo (yet), so no EEPs can be added to it...
