### ISSUE TITLE
[ONKYO] TX-NR575E shows up as unsupported device

### ISSUE THREAD

**Issue by cribskip** [openhab/openhab2-addons#4010]
Receiver is automatically detected by the binding but shows up as //unsupported device// and some channels are missing (Zone2 f.e.)

How to add this new device to the binding?

Best,
Sascha

**Comment by wborn** [comment]
You can add support by creating a PR similar to the [Add support for TX-NR708 receiver PR](https://github.com/openhab/openhab2-addons/pull/3863).

**Comment by cweitkamp** [comment]
Closed with #4118
