### ISSUE TITLE
[Lutron] Bridge connection resiliency

### ISSUE THREAD

**Issue by bobadair** [openhab/openhab2-addons#4050]
The current Lutron binding, specifically IPBridgeHandler, suffers from an inability to reliably detect failure of the telnet connection to the bridge device and re-connect.

Allan Tong developed some changes last year to resolve this, which he made available in a test version of the binding.  With his permission, I have merged a slightly modified version of that code in to a current branch. 

I have been testing it together with the changes in PR 4031, and it has been working as expected. I expect to be able to create a PR for it shortly.

**Comment by cweitkamp** [comment]
Can this issue be closed because of the changes of #4056?

Just as a side note - it is possible to [close issues by using keywords](https://help.github.com/articles/closing-issues-using-keywords/) in a related PR. :wink:

**Comment by bobadair** [comment]
Yes, this issue was resolved by PR #4056. Thanks.
