### ISSUE TITLE
[OneWire] Missing binding

### ISSUE THREAD

**Issue by lunxer** [openhab/openhab2-addons#4052]
If i search for onewire in paperUI>Add-ons i only get this:
![image](https://user-images.githubusercontent.com/4370034/46207830-0503a300-c329-11e8-96ed-ae6f9120f1fa.png)

## Expected Behavior
Want this binding https://www.openhab.org/addons/bindings/onewire/

## Current Behavior
Getting https://www.openhab.org/addons/bindings/onewire1/ and its outdated.

Looking around the forum and looks like i'm not the only one having this issue.

## Your Environment

* Version used: openHAB 2.3.0
* Environment: chrome 69.0.3497.100
* Operating System:  Raspbian on Rpi1B

**Comment by kaikreuzer** [comment]
It's only part of 2.4.0, for which there are currently only milestone releases available.

**Comment by lunxer** [comment]
Thank you very much! 
Here i was running stable release for once :D
