### ISSUE TITLE
[milight] RF collisions causing sporadic responses from globes

### ISSUE THREAD

**Issue by DriperPulse** [openhab/openhab2-addons#4064]
[milight] binding not accounting for RF collisions causing sporadic responses from multiple bridges. My testing environment has 2 ibox2 devices which work perfectly if you restrict commands to 1 of the 2 devices. The moment both bridges are included in an action the outcome become random. It may fully function or some bulbs may not respond.
When sending data to multiple bridges there needs to be a delay between sending packets to each bridge otherwise I believe RF collisions may occur (i.e. both bridges transmit data and the packets collide cause the globe to miss the packet).
Whilst there is a delay between re-transmits this appears to be accounting for delaying in transmitting to the same bridge. There appears to be no consideration for multiple bridges that are within range of each other (which in my place seems to be anywhere).
As what I've described will not have anything in logs of any value as programmatically there is no 'visible' error I'm not sure on the point of providing logs. I will note I've tried to resolve this myself using a dirty file creation (file used as locking mechanism) in one of the routines but I don't believe it's the best way. Therefore my logs probably aren’t overly helpful. If however someone feels default logs will in some way help just let me know and I’ll go back to the standard code and provide logs. 
## Possible Solution
I was simply trying to add some sort of thread lock or global 'transmission in progress flag' but it's somewhat beyond my programming skills.
## Steps to Reproduce (for Bugs)
Simply setup 2 bridges with a few zones each. Send commands to zones across 2 bridges at the same time. In my case in roughly 10 - 40% of cases the expected outcome (e.g. all lights on) will not fully occur (typically 1 or 2 lights do not respond). Send to only 1 bridge but all 4 zones (individually, not via zone 0) and I get a 100% success rate. 
## Context
Based on the lighting being a bit unreliable full deployment to the rest of the house isn't really an option.
## Your Environment
Openhab 2.3 (on PI3)
Milight binding 2.4.0
Currently testing with 2 ibox2 devices. Full deployment will be 15+ devices for full house individual light control.
Previously using about 7 ibox2 devices with my own nodeJS script to control lights with zero retransmits but serial communication (i.e. no parallel communication) to all bridges with 100% success rate. i.e. RF environment and globes are just fine.

**Comment by davidgraeff** [comment]
Thanks for the report.
I will introduce a global transmit queue for the binding.

**Comment by DriperPulse** [comment]
Awesome. I'd happily do it but it's beyond my skills to do it well. I'll happily test and/or assist in any way I can.

**Comment by buzink** [comment]
Hi @davidgraeff,

Thanks for fixing this. I am having the same issue. Is this fix part of the openHAB 2.4 release? I upgraded to 2.4 but I am still experiencing unreliable responses when using groups to switch on/off multiple bulbs from multiple milight controllers vs 100% reliability when switching on/off bulbs separately.

**Comment by davidgraeff** [comment]
There is a global transmit queue implemented. You may need to adapt the timing and repeat configuration. Repeat is 1 by default.
