### ISSUE TITLE
[samsungtv] Model UN32J5205AF (2015) Support?

### ISSUE THREAD

**Issue by meingraham** [openhab/openhab2-addons#4076]
openHABian on Raspberry Pi 3B
openHAB 2.4.0~20181001112604-1 (Build #1378)
Karaf bundle listing output:
`209 │ Active   │  80 │ 2.4.0.201810010846     │ Samsung Tv Binding`

I installed the binding and my TV was auto-discovered. I linked the Thing's power channel to a self-declared Switch Item.

`Switch  Bedroom_TV "Bedroom TV" [Switchable]`

The following message is logged when I change the state of the switch Item to ON in my Sitemap.

`[WARN ] [tv.internal.handler.SamsungTvHandler] - Channel 'samsungtv:tv:{thing_ID}:power' not supported`

The binding documentation lists a limited number (for obvious reasons) of Samsung TV models as having been tested with the binding. Is this a problem with my declarations or is this 2015 TV model truly not supported? If the latter, any plans for updates to the binding?

Regards.

Mike

**Comment by Cossey** [comment]
Try the most recent file linked in Pull Request 4169. arjanmels has added support for modern TVs except the most recent ones with the latest firmware. Try it out and comment your model and release year in that pull request if it works.
