### ISSUE TITLE
[solaredge] Weekly aggregate production showing NaN in PaperUI, UNDEF in REST API

### ISSUE THREAD

**Issue by bkpsu** [openhab/openhab2-addons#4116]
The weekly aggregate value is not showing anything, even though it's available in the API (I'm using a newer, SE7600HD, model inverter). The string "Status" and "Load" values are also blank.

This error occurs in both the PaperUI and REST. 

Using openhabian on RasPi3, SE inverter is connected via Ethernet.

**Comment by grizzlyfred** [comment]
Again, same here with my plant installed this September with SE9K => I had only two values yesterday, e.g. "current power" and "daily production". But if I call the SE-official API directly, all "current" value, i.e. production, consumption, grid load and grid feed and link status are retrieved.
Aggregates on top would be nice, but aren't.

I have tried to directly read from the Modbus meter (as "slave1" as outlined in various openHAB posts and SolarEdge's own Sunspec-Guide with no luck... Ideally, I would want the local meter data as well as the SE data for comparison/plausibility checks...

**Comment by alexf2015** [comment]
This is only available when 'meterInstalled' is set. I will adopt the readme as this is not clear.
