### ISSUE TITLE
[solaredge] Consumption values blank, meterInstalled option not shown in Thing configuration

### ISSUE THREAD

**Issue by bkpsu** [openhab/openhab2-addons#4117]
In my setup (using SE7600HD inverter with a standalone Consumption meter), none of the Consumption values are receiving data (showing "NaN"). Looking at the Readme, I should have the "meterInstalled" flag set for the binding to look for Consumption values, but I do not see the option in the SolarEdge inverter thing configuration.

**Comment by grizzlyfred** [comment]
Same here with SE9K and openhasbian 2.4.0 Snapshot 4, trying to access the private API tells me I should have set the "meter installed" flag which is not shown.

**Comment by alexf2015** [comment]
please try the "legacyMode" switch. set it to true. I will fix this, the option will be named correctly in future versions.
