### ISSUE TITLE
[max!] Autorefresh don't work anymore

### ISSUE THREAD

**Issue by jmahmens** [openhab/openhab2-addons#4119]
## Expected Behavior
Autorefresh of temperature works in the configured intervall.

## Current Behavior
No refresh in this Intervall.

## Steps to Reproduce (for Bugs)
1. Configure Thermostat things with a refreshrate >10
2. set Loglevel to TRACE for org.openhab.binding.max binding

## Context
I have update from 2.3 to 2.4.0.m4.
All actuell temeratures from my devices are logged and shown in a chart, but after upgarding this don't work anymore. I reset the cube and reconnect all devices. Also i tried to delete all max things from openhab and reinstall.
I've tried different refresh intervalls from 10,11,12,13 Minutes to 60,70,80,90 which worked before.
During summertime with all devices set to manual (with OH2.3) I recognised that my room 1+2 are update correct but in room 3+4 somtimes the temperature isn't set back correctly, So it grows day by day and must be reset manualy to eco temperature.

## Your Environment
* Openhab 2.4.0.m4
* Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
* Raspian strech
* Max cube v1.13
* 2x MAX! Elektronischer Heizkörperthermostat (room 1+2)
* 2x MAX!-Fensterkontakt (room 1+2)
* 2x MAX! Heizkörperthermostat basic (room 3+4)

**Comment by cweitkamp** [comment]
This issue maybe relates to #4114. I observed an error sending a QuantityType command. The refresh of temperature values is based on sending a QuantityType command.
