### ISSUE TITLE
[Velux Binding] KLF200 new API documentation

### ISSUE THREAD

**Issue by mqtt-fan** [openhab/openhab2-addons#4121]
Here is a new Firmware and API documentation available on https://www.velux.com/api/klf200

Maybe you can increase the feature set of the binding

**Comment by wborn** [comment]
Thanks for the info! But I'll close this issue because the [Velux binding PR](https://github.com/openhab/openhab2-addons/pull/2531) hasn't been merged. Just create an issue when the PR is merged when you want to report a bug or request some missing functionality.
