### ISSUE TITLE
[mihome] Bridge Online - Everything else Offline

### ISSUE THREAD

**Issue by NicoSoftware** [openhab/openhab2-addons#4127]
So configuring my things like this:
```
Bridge mihome:bridge:781 "VS Xiaomi Bridge" [ serialNumber="7811", ipAddress="192.168.1", port=9898, key="yrncwn", pollingInterval=6000 ] {
  Things:
 gateway 7811d"VS Xiaomi Mi Smart Home Gateway" 			[itemId="7811"]
 sensor_cube 158d00 "VS Xiaomi Cube #1" [itemId="158d0"]
 sensor_cube 158d00 "VS Xiaomi Cube #2" [itemId="158d00"]

 sensor_motion 158d0 "VS Xiaomi Motion Sensor" [itemId="158d89"]
 sensor_magnet 158de20 "VS Xiaomi Door Sensor" [itemId="158d0"]

 sensor_switch_aq2 158d9 "VS Xiaomi Switch #1" [itemId="158d00"]
 sensor_switch_aq2 158d8 "VS Xiaomi Switch #2" [itemId="158d"]
 sensor_switch_aq2 158df "VS Xiaomi Switch #3" [itemId="158d000"]

 sensor_weather_v1 158da817 "VS Xiaomi Temperatur #1" [itemId="158"]
 sensor_weather_v1 1580c60 "VS Xiaomi Temperatur #2" [itemId="158d00"]
 sensor_weather_v1 158a9f "VS Xiaomi Temperatur #3" [itemId="158d0f"]
  } 
```
(ItemsIDs and MAC are cut out)
get's me a offline gateway/sensors and a always online gateway.
 
Did a tcpdump from my router and I'm receiving proper JSON formated data packages from my gateway to my Server/Client (9898)

I do get a TTL Error (RFC 3171) when receiving package from port 4321 (rwhois)
More Infos:
https://community.openhab.org/t/openhab2-xiaomi-mi-gateway-does-not-respond/52963/8

**Comment by dimalo** [comment]
Hi @NicoSoftware,
please check your Things and compare to [the readme](https://www.openhab.org/addons/bindings/mihome/#configuration-examples).
So instead of writing
`sensor_cube 158d00 "VS Xiaomi Cube #1" [itemId="158d0"]`
I'd go for
`Thing mihome:sensor_cube:158d0001XXXXXX "Xiaomi Cube" [itemId="158d0001XXXXXX"]`

**Comment by davidgraeff** [comment]
Seem to be solved in the community thread. If this is still an issue please reopen.
