### ISSUE TITLE
[homekit] openHAB shows up as “not supported” on iOS after successful pairing

### ISSUE THREAD

**Issue by ivan1970** [openhab/openhab2-addons#4134]
Hello 
I have an OpenHab 2.3 installed on raspi and HomeKit on Iphone with IOS 12.
I'm trying to connect in with IOS homekit, but after successfull pairing, into HomeKit app there is an OpenHab icon with "not supported" word inside and I'm not able to see any device.
I have these items at beginning of my .items file:

> Switch	SwitchGarage <blinds>	[ "Switchable" ] {mqtt=">[HOME_IVAN:openhab/garage:command:ON:default],>[HOME_IVAN:openhab/garage:command:OFF:default],<[HOME_IVAN:openhab/garage:state:default:.*]"}

> Switch	SwitchGate	<garagedoor> [ "Switchable" ] {mqtt=">[HOME_IVAN:openhab/gate:command:ON:default],>[HOME_IVAN:openhab/gate:command:OFF:default],<[HOME_IVAN:openhab/gate:state:default:.*]"}

attached you can find my openhab log where i didn't find any strange message. 
Could you help me to solve this issue?
thanks,
Ivan
[openhab.zip](https://github.com/openhab/openhab2-addons/files/2476219/openhab.zip)

**Comment by ivan1970** [comment]
I solved thiss issue.
My rpi2 have a fixed ip address but due to dhcpcd5 installed package it get also a DHCP address.
Then, I removed dhcpcd5 package and after restart with single IP Address (the fixed one) I was able to connect homekit to my OH Items.
Now I have another issue, I’m trying to connect a second IOS device to OH2 but the HomeKit doesn’t able to view any OH device on my network. There is a limit to a single IOS device for HomeKit-Addon?

**Comment by chrjs** [comment]
I have the same issue but seems caused by the presence of the {binding} section.
For example this works:
Switch Test1 "Test1" ["Lighting"] 

But this one gives "not supported" and the device Test1 does not appear:
Switch Test1 "Test1" ["Lighting"]  {bticino="if=webserver;who=1;what=1;where=33"}

**Comment by ivan1970** [comment]
You should try to put a space after and before braces.. 
{ bticino=“.....” }

**Comment by chrjs** [comment]
Thanks Ivan. Now seems working: maybe is the "space" issue but I'm not 100% sure because each time I update the .items file, the HomeKit goes to "unsuppored" and I've to restart the OpenHAB service each time, so maybe some previous trials could have been ok but I had no restarted the service.

Is this normal or the system should get the .items update without restart need?

**Comment by J-N-K** [comment]
Please check if this is still the case with latest Snapshots

**Comment by J-N-K** [comment]
seems to be only loosely connected to homekit, seems to be resolved according to last comment
