### ISSUE TITLE
[AVMFritz] next_change channel no longer works correctly

### ISSUE THREAD

**Issue by tobiasisenberg** [openhab/openhab2-addons#4138]
## Expected Behavior

The channel should display the next time the connected device is supposed to change.

## Current Behavior

The channel displays a completely incorrect date/time; e.g. currently 1970-01-18T20:40:24.600+0100 for one of my devices (for a change that is supposed to happen today at 19:30 at currently UTC+2). The time of the system otherwise is correct, all my devices do, in fact, switch at the set times. I also noticed that the displayed time is changing about a minute every day, but I have not tracked this precisely. I remember seeing switch times between 20:33 and 20:39 in the last days, yet all still on the same date. I also rebooted the entire machine and restarted OpenHAB, with no change. The issue affects all my connected Comet DECT devices equally, for example another device shows 1970-01-18T20:41:02.400+0100 as its next_change (for a change that is supposed to happen at 06:00 tomorrow morning. Other scheduled changes (other items for other bindings) happen at the correct times.

## Possible Solution

No idea. I also don't know when this started, maybe at my upgrade from version 2.2 to 2.3 (but this is really just a hunch, I only noticed about two or three weeks ago). When I initially had created the items, the correct dates/times were shown. I initially installed the system with OpenHAB 2.2 and have not touched the next_change items after initially creating them.

## Steps to Reproduce (for Bugs)

I assume:
1. follow the example setup
2. look at one of the next_change items.

## Context

normal use context of seeing the next change date and time

## Your Environment

* Version used: OpenHAB 2.3.0-1; AVM FRITZ! Binding installed using PaperUI
* Environment name and version: value incorrect on the system itself, regardless of browser, can be confirmed with REST API
* Operating System and version: OpenHABian (all apt-get updates done yesterday); Fritz!OS 7.01 on Fritz!Box 7490 (channel already showed incorrect values under the previous 6.x version of Fritz!OS)

**Comment by cweitkamp** [comment]
@tobiasisenberg I cannot see such issues with my current binding version. But I am using latest OH2.4.0 milestone 4. Is it possible for you to perform a test with a new binding version?

**Comment by tobiasisenberg** [comment]
@cweitkamp I'll send you a personal message to sort it out.

**Comment by cweitkamp** [comment]
Has been fixed in #3684 (see https://github.com/openhab/openhab2-addons/pull/3684/files#diff-bd72c5c4d5010dd42a9b6940a70ad50bR269).

Thanks for your patience.

**Comment by cweitkamp** [comment]
@tobiasisenberg Do you like to add something? I close this issue for now.
