### ISSUE TITLE
[HomeMatic] Connection lost to gateway

### ISSUE THREAD

**Issue by McLive** [openhab/openhab2-addons#4144]
Recently I had the issue that the homematic binding lost it's connection to the gateway.

I tried upading the binidng to 2.4.0 but I'm getting lots of errors with that version:
https://upl0ad.cloud/1SMu

I can't even change the settings for the homematic bridge. (Exception during HTTP PUT request for update config at 'things/homematic:bridge:fe7f373f/config')

The homematic log shows errors like these:
https://upl0ad.cloud/AP9fQ20eNcwbuzNqj0IQ-3RGigN8

What's going on here?

**Comment by McLive** [comment]
I've now configured the correct IP in Network settings as it was using the wrong 192.168.50.2 from openVPN.

![image](https://user-images.githubusercontent.com/5620071/47247737-cd5ab900-d405-11e8-96c5-7c3facb4b7bc.png)

Now it says this:
https://upl0ad.cloud/wtHn

**Comment by cweitkamp** [comment]
Please note that the homematic binding is part of ESH, so please be so kind and report this issue at https://github.com/eclipse/smarthome/issues instead. Thanks!
