### ISSUE TITLE
[AmazonEchoControl] Losing credentials

### ISSUE THREAD

**Issue by TommySharpNZ** [openhab/openhab2-addons#4145]
I'm finding that if my windows OH2 2.3 instance restarts then the echo control binding loses credentials and I have to log it back in.... And I notice in the logs that when I do this there is this error generated.

`2018-10-20 07:55:39.095 [ERROR] [me.storage.json.internal.JsonStorage] - Error writing JsonDB to C:\OPENHA~2\userdata\jsondb\amazonechocontrol:account:account1.json. Cause C:\OPENHA~2\userdata\jsondb\amazonechocontrol:account:account1.json (The filename, directory name, or volume label syntax is incorrect).`

It's possible that this is why the credentials are not being properly saved?

**Comment by mgeramb** [comment]
@kaikreuzer  this issue can be closed, it is related to the JsonStorage bug on windows bases systems
