### ISSUE TITLE
[mihome] No token received from the gateway yet. Unable to encrypt the access key

### ISSUE THREAD

**Issue by ghasemikasra39** [openhab/openhab2-addons#4178]
openHAB 2.3.0
I have the Xiaomi gateway with the latest firmware. It was working for a couple of weeks. Then, when I ran openHAB, I get this error in console:

> No token received from the gateway yet. Unable to encrypt the access key

Now nothing works in paper UI and I can't control my gateway and the other xiaomi sensors.

**Comment by wborn** [comment]
Closing this issue because it is a duplicate of https://github.com/openhab/openhab2-addons/issues/3577.
