### ISSUE TITLE
[onewire gpio] nice to have

### ISSUE THREAD

**Issue by LukaNoah** [openhab/openhab2-addons#4179]
hi,
it would be nice to have more paramters for the temperature-sensors
- decimalplaces (e.g. 0, 1, 2, 3)
- offset for sensor (e.g. -0,5°C)

thx
LN

**Comment by wborn** [comment]
The OneWire binding source code is maintained in the Eclipse SmartHome repository.
Please use the ESH [issue tracker](https://github.com/eclipse/smarthome/issues?q=is%3Aopen+is%3Aissue+label%3ABinding-OneWire) for OneWire issues and feature requests.
