### ISSUE TITLE
[mihome] thing write json format error

### ISSUE THREAD

**Issue by lumigit** [openhab/openhab2-addons#4190]
## Expected Behavior

control xiaomi thing
{"cmd": "write", "model": "gateway", "sid": "286c0785b643", "short_id": "0", "data": "{\\\"rgb\\\": 1694498815, \\\"key\\\": \\\"22F9802DC5DA73478D8A307C592CC9FE"}"}
maybe should change to 
{"cmd": "write", "model": "gateway", "sid": "286c0785b643", "short_id": "0", "data": "{\\\"rgb\\\": 1694498815, \\\"key\\\": \\\"22F9802DC5DA73478D8A307C592CC9FE\\\"}"}

data's key:
\\\"22F9802DC5DA73478D8A307C592CC9FE"
change to 
\\\"22F9802DC5DA73478D8A307C592CC9FE\\\"

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Version used: (e.g., openhab and addon versions)
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):

**Comment by wborn** [comment]
Please provide some more information:
* Is this an issue about the Xiaomi [milight binding](https://www.openhab.org/addons/bindings/milight) or the [miio binding](https://github.com/openhab/openhab2-addons/pull/2548) which hasn't been merged? 
* Which openHAB version do you use?
* Where do you see this JSON?
* Is there any functional issue besides the missing backslash?

**Comment by lumigit** [comment]
1.  openHAB version do you use?
 openHAB win10
2. Where do you see this JSON?
    use wireshrk to capture the package.
3. Is there any functional issue besides the missing backslash?
    It can not control aqara homekit gateway(linux version).
