### ISSUE TITLE
[amazonechocontrol] Login failed: POST url ‘https://www.amazon.com/ap/signin’ failed: Not Found

### ISSUE THREAD

**Issue by chimeranzl** [openhab/openhab2-addons#4201]
OH 2.4.0, Amazon echo binding stops working logging the following every ~1 minute:

Login failed: POST url ‘https://www.amazon.com/ap/signin’ failed: Not Found

If I go to the above web site, it does not exist.  Assume Amazon have changed the sign in page which has broken the binding???

**Comment by chimeranzl** [comment]
My bad, found mention of the issue on OH site. Workaround install beta version from here... https://community.openhab.org/t/released-openhab2-amazon-echo-control-binding-controlling-alexa-from-openhab2/37844

**Comment by mgeramb** [comment]
@kaikreuzer  this issue can be closed now
