### ISSUE TITLE
[neeo] 52.x features

### ISSUE THREAD

**Issue by tmrobert8** [openhab/openhab2-addons#4210]
Added 52.x features:

1. Driver versioning - allow updating to devices without the need to drop/readd
2. List builder improvements - support new click action features

**Comment by wborn** [comment]
What is this issue exactly about @tmrobert8?

**Comment by wborn** [comment]
I already thought so but now I also see the PR https://github.com/openhab/openhab2-addons/pull/4212. :wink:

**Comment by wborn** [comment]
Can this issue be closed now @tmrobert8 now the PR is merged?

**Comment by tmrobert8** [comment]
Merged
