### ISSUE TITLE
[innogysmarthome] Invalid token request

### ISSUE THREAD

**Issue by JohannGa** [openhab/openhab2-addons#4214]

**Comment by JohannGa** [comment]
2018-11-10 15:13:53.088 [ERROR] [marthome.handler.InnogyBridgeHandler] - Error initializing innogy SmartHome client.

com.google.api.client.auth.oauth2.TokenResponseException: 403 Forbidden

{

  "errorcode" : 2002,

  "description" : "Invalid token request",

  "messages" : [ "Reason: invalid_grant" ]

}

	at com.google.api.client.auth.oauth2.TokenResponseException.from(TokenResponseException.java:105) ~[240:org.openhab.binding.innogysmarthome:2.3.0]

	at com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:287) [240:org.openhab.binding.innogysmarthome:2.3.0]

	at com.google.api.client.auth.oauth2.TokenRequest.execute(TokenRequest.java:307) [240:org.openhab.binding.innogysmarthome:2.3.0]

	at org.openhab.binding.innogysmarthome.internal.client.InnogyClient.getAccessToken(InnogyClient.java:269) [240:org.openhab.binding.innogysmarthome:2.3.0]

	at org.openhab.binding.innogysmarthome.internal.client.InnogyClient.initialize(InnogyClient.java:131) [240:org.openhab.binding.innogysmarthome:2.3.0]

	at org.openhab.binding.innogysmarthome.handler.InnogyBridgeHandler$Initializer.run(InnogyBridgeHandler.java:107) [240:org.openhab.binding.innogysmarthome:2.3.0]

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]

	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]

	at java.lang.Thread.run(Thread.java:748) [?:?]

**Comment by wborn** [comment]
Looks like an authorization issue:


https://tools.ietf.org/html/rfc6749#section-5.2

```
        invalid_grant
               The provided authorization grant (e.g., authorization
               code, resource owner credentials) or refresh token is
               invalid, expired, revoked, does not match the redirection
               URI used in the authorization request, or was issued to
               another client.
```

Maybe you can start over and reconfigure it using the [Thing Configuration](https://www.openhab.org/addons/bindings/innogysmarthome/#thing-configuration) paragraph in the docs?

**Comment by kaikreuzer** [comment]
@ollie-dev Even if this might be a user/configuration error, the binding should not do such an error log, but rather provide feedback about the problem through the Thing status. Could you look into this?

**Comment by JohannGa** [comment]
> Sieht aus wie ein Berechtigungsproblem:
> 
> https://tools.ietf.org/html/rfc6749#section-5.2
> 
> ```
>         invalid_grant
>                The provided authorization grant (e.g., authorization
>                code, resource owner credentials) or refresh token is
>                invalid, expired, revoked, does not match the redirection
>                URI used in the authorization request, or was issued to
>                another client.
> ```
> Vielleicht können Sie von vorne beginnen und es mit dem Abschnitt " [Thing-Konfiguration"](https://www.openhab.org/addons/bindings/innogysmarthome/#thing-configuration) in den Dokumenten neu [konfigurieren](https://www.openhab.org/addons/bindings/innogysmarthome/#thing-configuration) ?



> Looks like an authorization issue:
> 
> https://tools.ietf.org/html/rfc6749#section-5.2
> 
> ```
>         invalid_grant
>                The provided authorization grant (e.g., authorization
>                code, resource owner credentials) or refresh token is
>                invalid, expired, revoked, does not match the redirection
>                URI used in the authorization request, or was issued to
>                another client.
> ```
> Maybe you can start over and reconfigure it using the [Thing Configuration](https://www.openhab.org/addons/bindings/innogysmarthome/#thing-configuration) paragraph in the docs?

I have installed it three times but without success. I also requested more tokens.

**Comment by ollie-dev** [comment]
> @ollie-dev Even if this might be a user/configuration error, the binding should not do such an error log, but rather provide feedback about the problem through the Thing status. Could you look into this?

@kaikreuzer, yes - I'll have a look. So you propose only changing the thing status including an error message, but not logging anything (only debug logging), right?

**Comment by ollie-dev** [comment]
@JohannGa Do you use the configuration via Paper UI or textual configuration files? In the first case, please make sure the right brand is selected in the drop down of the bridge thing configuration and you get the auth-code from the right url - depending on the brand. You can find the urls [here](https://www.openhab.org/addons/bindings/innogysmarthome/#obtaining-the-authorization-code-and-tokens).

**Comment by kaikreuzer** [comment]
> So you propose only changing the thing status including an error message, but not logging anything (only debug logging), right?

Right, see also https://www.openhab.org/docs/developer/development/guidelines.html#e-logging.

**Comment by ollie-dev** [comment]
> Thank you for reply. I use the first Linke innogy SmartHome authorization page and in the PaperUI is correct, too. Innogy released a new device software (2.0.824.747), but in the Bottom is a label with: "Current firmware version": 1.913, could it be a problem?

This is correct and you can see it in the innogy client as well. I started the latest software update today and the binding came up again without any issue. 

Some further debugging questions:

1. Does the innogy client under https://home.innogy-smarthome.de work?
2. Does the innogy app with on your mobile device work as well while you are at home in your local WiFi?
3. Is your OH2 installation in the same local network as the one tested in 2.?
4. Do you use the latest stable OH2 release (2.3) and the innogy binding included in that version?
5. Did you try removing the innogy controller in Paper UI, re-adding it again and trying a new authcode to get the controller connected?

**Comment by JohannGa** [comment]
Hi, sorry for my late reply, I uninstalled Innogy Binding and then I updated OpenHAB. In the meantime inoogy released  new software version for the brigth. I updated all software and installed the Binding(Innogy..), and ordered new Auth-Code. After that the system is working normaly.  

I can't figure out what the problem was =(.

Thank you for your help.

**Comment by davidgraeff** [comment]
Seem to be solved.
