### ISSUE TITLE
[samsungtv] Add LE40C650 to tested models list

### ISSUE THREAD

**Issue by mc9662** [openhab/openhab2-addons#4227]
I can confirm that the SamsungTV Binding works with my OpenHab 2.3 and LE40C650 L1KXXU

Thank you for all your efforts on this.

Matt

**Comment by wborn** [comment]
That's good news! :-)

Maybe you can edit the documentation and add your model to the list of tested models?

There's an [Edit this page on GitHub](https://github.com/openhab/openhab2-addons/edit/master/addons/binding/org.openhab.binding.samsungtv/README.md) link for this at the bottom of the [Samsung TV Binding documentation](https://www.openhab.org/addons/bindings/samsungtv/#samsung-tv-binding).

**Comment by mc9662** [comment]
Thanks.  I've done that and created the PR

**Comment by wborn** [comment]
Thanks! Can you also create a PR for the `openhab/openhab2-addons` repo? 
https://github.com/mc9662/openhab2-addons/pull/1 is for your own repo. :wink:

**Comment by mc9662** [comment]
Think I've managed that now, that was my first proper PR...
