### ISSUE TITLE
[milight] Milight Binding - Only one bridge of each type goes online (openHAB 2.4.0 Build #1426)

### ISSUE THREAD

**Issue by TomaSpeed** [openhab/openhab2-addons#4232]
After switching to 2.4.0 Build #1426 only the first V3 bridge goes online. The next 4 ones that I add are staying offline.
When I delete the Online-bridge one Offline-bridge instantly changes to online.

It's the same behavior with V6 bridges. I added one iBox and one iBox2. (More V6 bridges are ordered)

And detected right now that adding a second Color bulb (on other Zone) to an Online-bridge the bulb stays offline. Only tested this on V6.

If online, V3 bridge is working as expected but V6 doesn't.

I removed all bulbs and all bridges and reinstalled the binding before testing.

Another minor issue: The V6 bridges are detected only once. I need to restart the openHAB service or re-install the binding to re-detect them.

Thanks for your support.

## Environment
* openHAB 2.4.0 Build #1426
* Paper UI
* Windows 7

**Comment by TomaSpeed** [comment]
No news about this issue?
Does someone encounter similar problems or am I the only one?
If I'm the only one, what did I possibly wrong?

This issue is preventing me from upgrading to higher builds, ....

**Comment by patpanu** [comment]
I am having same exact problem. I have 4 V6-bridges. After switching to Build#1426, only one bridge is online at a time. Now I need to rollback to prior build and cannot upgrade to higher builds.

**Comment by TomaSpeed** [comment]
@patpanu 
Did your V6 bridge work?
If yes, I need to do some more testing, as mine did not work at all.

@davidgraeff
Is it possible to provide the old jar-file (build 1422 works for V3) so that I can continue upgrading?

**Comment by TomaSpeed** [comment]
> If anybody want to have a look at the code, I'm happy to guide and review.

@davidgraeff
As I'm not very good at all this coding stuff used here, I think it's better for me not to try understanding nor manipulating your code ;)
Your binding is very easy to use, but according to your recent statement, I need to find another, perhaps more complex, solution for my multi bridge setup.
Thanks for your support.

**Comment by pfink** [comment]
> I consider a multi bridge setup rather unusual

Why? A normal home has usually more than 4 lights that should be controlleable independently from each other. So I think many people need multiple bridges (including myself).

> and want the binding to work good for the one bridge scenario for the moment.

In a few days, we want to publish the next stable release. The question is, should a stable release break existing functionality in favor of other bug fixes? I tend to say 'No', as the user would not expect that when he upgrades from one stable version to another stable version...

**Comment by davidgraeff** [comment]
The milightv6 works stable now and V3 works with one bridge at least. I assume more people have a V6 bridge then V3 bridges. I don't want to argue that this multiple bridges bug exists. Someone need to sit down and fix it and I can do this as well but not for oh 2.4. it would be a bad idea to revert this bug fix pr though, at least I would veto that.

**Comment by pfink** [comment]
Fortunately, the error is easy to fix. I attached #4341. Would be cool if somebody could test it with a real bridge.

**Comment by davidgraeff** [comment]
The V3 bridges were sending broadcast packets, which increased the load on every additional handler. I changed that to a unicast transmission, if the address is known. Together with your changes, each socket receive thread should now only process response packets of exactly one bridge.
