### ISSUE TITLE
yamahareceiver - Disable Auto Discovery (or making it smarter?)

### ISSUE THREAD

**Issue by SeLLeRoNe** [openhab/openhab2-addons#4259]
Hi,

I am configuring some pre-defined things and Items for my OpenHAB and I would like to disable auto discovery when a spcific "thing" is already configured (in this particular case, a Yamaha Amplifier).

What I did is to create a services/yamaha.cfg with this content:
org.openhab.yamahareceiver:enableAutoDiscovery=false

Following a suggestion for a different binding, but it doesn't seems to work, therefore my question, is that possible? Can be implemented?

Also, maybe stupid maybe not, does exist a config parameter that to "don't show already configured things"? (example matching IDs).

Thanks 
Best regards
Andrea

**Comment by davidgraeff** [comment]
Already configured things are automatically filtered out usually. openHAB doesn't seem to be convinced that the auto discovery receiver is the same as the textual configured one in this case though. The host config parameter need to match exactly.

**Comment by davidgraeff** [comment]
@cweitkamp Yes definitely. I thought that's the case already. Even better than the "host" would be the "mac" of the receiver.
