### ISSUE TITLE
[squeezebox] IllegalStateException from Jetty when downloading cover art

### ISSUE THREAD

**Issue by mhilbush** [openhab/openhab2-addons#4260]
Jetty can throw an IllegalStateException if the host computer running openHAB has a large number of cores. See [here](https://community.openhab.org/t/fix-for-jetty-error-when-running-on-host-with-many-cores/57449).

If this occurs when the binding downloads coverart, the exception is not caught, and the listener thread exits.

**Comment by cweitkamp** [comment]
Closing this. Will be fixed by eclipse/smarthome#6588.
