### ISSUE TITLE
[Homematic] 2.4 snapshot binding not working on Mac OS X (Jetty start failed)

### ISSUE THREAD

**Issue by jewesta** [openhab/openhab2-addons#4262]
I cannot get the Homematic binding working when running 2.4 snapshot under Mac OS X Mojave.

## Expected Behavior
After a fresh install, the binding should auto discover the HomeMatic Bridge and find all connected things.

## Current Behavior
The binding discovers only one bridge ("eQ3-HmIP-CCU3-App - <ip address>"). Adding it results in it being "OFFLINE - COMMUNICATION_ERROR Jetty start failed". The "Homematic Bridge" is not auto discovered. Adding it manually results in it being "OFFLINE - COMMUNICATION_ERROR Jetty start failed" as well.

## Steps to Reproduce (for Bugs)
2.3 (working)
- Unzip openhab-2.3.0.zip
- cd to install directory and ./start.sh
- Access <ip>:8080 and choose "Standard" UI configuration
- PaperUI --> Addons --> Bindings --> Install Homematic Binding
- PaperUI --> Configuration --> Things --> Add Homematic Bridge manually
- All things (switches, contacts, etc.) are discovered as expected

2.4 snapshot (not working)
- Unzip openhab-2.4.0-SNAPSHOT (tested build #1424 and later)
- cd to install directory and ./start.sh
- Access <ip>:8080 and choose "Standard" UI configuration
- PaperUI --> Addons --> Bindings --> Install Homematic Binding
- Installation takes a long time / does not come to an end "naturally"
- Log entry:
`Discovery Result with UID 'homematic:bridge:MEQxyz123' has been added.`
- Bridge "eQ3-HmIP-CCU3-App" discovered (in inbox). On a Raspberry, the "Homematic Bridge" would have been discovered as well but is missing here.
- PaperUI --> Configuration --> Things --> Add Homematic Bridge manually
- "Homematic Bridge" shows "Status: OFFLINE - COMMUNICATION_ERROR Jetty start failed"
- Log entry:
`2018-11-21 22:22:30.683 [hingStatusInfoChangedEvent] - 'homematic:bridge:a44c9e2b' changed from UNINITIALIZED to INITIALIZING
2018-11-21 22:22:30.873 [hingStatusInfoChangedEvent] - 'homematic:bridge:a44c9e2b' changed from INITIALIZING to OFFLINE (COMMUNICATION_ERROR): Jetty start failed`
- No things (switches, contacts, etc.) are discovered

## Context
I came from an openHABian scenario running 2.4 snapshots for quite a while. But as the Raspberry got too slow, I decided to migrate to a Mac mini 2012 running Mojave. Having failed to resolve the issue mentioned above, I set up openHAB 2.3, which runs without any problems. I also use a few other addons in addition to HomeMatic, namely MySQL, AVM Fritz, etc. and all works well.

## Your Environment
HomeMatic:
- Raspberry Pi with RaspberryMatic
- Latest firmware 3.37.8.20181026

openHAB:
- Mac mini 2012 Core i5 16GB RAM / 512GB SSD
- Mac OS X Mojave
- User account with admin priviledges
- Firewall off

**Comment by MHerbst** [comment]
The HomeMatic binding has moved to the Eclipse Smarthome Rep. Please create the issue here: https://github.com/eclipse/smarthome/issues and close this issue. Thanks.

**Comment by jewesta** [comment]
Sorry for filing it in the wrong place & thanks for pointing me to the right repo.
The issue can now be found here: [Eclipse Smarthome #6576](https://github.com/eclipse/smarthome/issues/6576)
