### ISSUE TITLE
[gardena]   “Unsupported json value object” warning

### ISSUE THREAD

**Issue by Dan1001** [openhab/openhab2-addons#4265]
From around 19 November 2018, the gardena binding started to write a warning in the log every minute:

`[WARN ] [odel.deser.PropertyValueDeserializer] - Unsupported json value object, returning empty value`

A number of people saw this starting at the same time, so seems most likely it's a change in the Gardena api (although the binding still seems to be working)

A temporary workaround is to suppress gardena warning logging.

See thread here: https://community.openhab.org/t/unsupported-json-value-object-warning/57339

**Comment by Dan1001** [comment]
Perhaps I jumped to the conclusion it's the api, when it could be e.g. a recent Ubuntu update. Is anyone experiencing the problem but not on Ubuntu 16.04?

**Comment by kaikreuzer** [comment]
I'm on macOS, clearly no Ubuntu :-)

**Comment by Dan1001** [comment]
Excellent - so over to @gerrieg to do the hard bit...
