### ISSUE TITLE
[openhabcloud] Rollershutter don't allow do be switched on or off

### ISSUE THREAD

**Issue by Xento** [openhab/openhab2-addons#4296]
## Expected Behavior
1. If I say Alexa turn off/on Rolladen Wohnzimmer than the rollershutter should move down or up
2. If I turn off/on Rolladen Wohnzimmer in the Alexa app than the rollershutter should move down or up
3. I want to add a rollershutter to a routine via the Alexa app, the device should be added

## Current Behavior
1. Alexa says that the device doesn't support this command
2. The app says that the server isn't responding
3. The app displays a blank page and when I go back to the routine, the device is missing

## Context
I wanted to add a rollershutter to a routine but this doesn't work.
Maybe the routine sends a combined command for example on and the percentage and than the server is not responding, so nothing is added.
I can control the rollershutter via Alexa app or Echo when I say a percentage which should be set.

## Your Environment
* Version used: openHAB 2.4.0 Build #1330

**Comment by davidgraeff** [comment]
That's a shortcoming of Alexa
