### ISSUE TITLE
[milight] Milight Binding - Can't add Led strips (openHAB 2.4.0 Build #1426)

### ISSUE THREAD

**Issue by orzechszek** [openhab/openhab2-addons#4306]
Hi,

When I've updated Openhab to version 2.4.0 Build #1426 I couldn't initialize my milight bridge and strips, so I decided to remove from Paper UI and add it again. 
I remove these things in PaperUI, remove binding, stop openhab, cleanup cache and tmp folders, start openhab and install milight binding again. Finally, only bridge V3 appears. I added it and no rgbLed appear. What could happen? 

Environment:
openHAB 2.4.0 Build #1426
Paper UI
Debian

**Comment by davidgraeff** [comment]
The "discovery" has been removed. It was a fake one actually, milight doesn't allow to discover light bulbs.

Just add a manual one in paperui or textual. They will not appear in the inbox anymore.

**Comment by wborn** [comment]
The milight discovery was flooding the inbox with non-existing Things so it was removed. See also   https://github.com/openhab/openhab2-addons/issues/2918 .
