### ISSUE TITLE
[deconz] Things are online, but linked items don’t change the value

### ISSUE THREAD

**Issue by Markkuuss** [openhab/openhab2-addons#4355]
The deconz things go online, but the linked items don't change their values.

When I link the items for the first time, they take over the current status of the Zigbee devices:
```csv
TestSwitch changed from NULL to OFF
TestNumber changed from NULL to 2230.0
```
The values do not change after this.

Here some more detailed information about the configuration.

**_Things:_**
The configuration in my file _Deconz.things_ looks like this:
```csv
Bridge deconz:deconz:LightlinkPi	"LightlinkPi"	[ host="LightlinkPi", apikey="AFxxxxxxF7" ]
{
	presencesensor HueMotionPresence	"Presence"	[ id="9" ]
	temperaturesensor HueMotionTemperature	"Temperature"	[ id="10" ]
}
```

Here also the corresponding excerpt from the API of my Deconz-Bridge:

    {
        "config": {
            "UTC": "2018-12-11T15:48:33",
            "apiversion": "1.0.9",
            "backup": {
                "errorcode": 0,
                "status": "idle"
            },
            "bridgeid": "00212EFFFF004D54",
            "datastoreversion": "60",
            "devicename": "RaspBee",
            "dhcp": true,
            "factorynew": false,
            "fwversion": "0x262f0500",
            "gateway": "192.168.86.1",
            "internetservices": {
                "remoteaccess": "disconnected"
            },
            "ipaddress": "192.168.86.51",
            "linkbutton": false,
            "localtime": "2018-12-11T16:48:33",
            "mac": "b8:27:eb:49:82:dd",
            "modelid": "deCONZ",
            "name": "RaspBee-GW",
            "netmask": "255.255.255.0",
            "networkopenduration": 60,
            "panid": 64272,
            "portalconnection": "disconnected",
            "portalservices": false,
            "portalstate": {
                "communication": "disconnected",
                "incoming": false,
                "outgoing": false,
                "signedon": false
            },
            "proxyaddress": "none",
            "proxyport": 0,
            "replacesbridgeid": null,
            "rfconnected": true,
            "starterkitid": "",
            "swupdate": {
                "checkforupdate": false,
                "devicetypes": {
                    "bridge": false,
                    "lights": [],
                    "sensors": []
                },
                "notify": false,
                "text": "",
                "updatestate": 0,
                "url": ""
            },
            "swupdate2": {
                "autoinstall": {
                    "on": false,
                    "updatetime": ""
                },
                "bridge": {
                    "lastinstall": "",
                    "state": "allreadytoinstall"
                },
                "checkforupdate": false,
                "install": false,
                "lastchange": "",
                "lastinstall": "",
                "state": "allreadytoinstall"
            },
            "swversion": "2.5.20",
            "timeformat": "24h",
            "timezone": "Etc/GMT-1",
            "uuid": "876ca19e-74ba-4cb4-8f42-c6820478c3af",
            "websocketnotifyall": true,
            "websocketport": 8088,
            "whitelist": {
                [...]
            },
            "zigbeechannel": 15
        },
        "sensors": {
           [......]
            "9": {
                "config": {
                    "alert": "none",
                    "battery": 66,
                    "delay": 12,
                    "ledindication": false,
                    "on": true,
                    "pending": [],
                    "reachable": true,
                    "sensitivity": 2,
                    "sensitivitymax": 2,
                    "usertest": false
                },
                "ep": 2,
                "etag": "239845bdba7f74fb36d8d7cc449e0523",
                "manufacturername": "Philips",
                "modelid": "SML001",
                "name": "Bewegungsmelder",
                "state": {
                    "lastupdated": "2018-12-11T15:48:16",
                    "presence": false
                },
                "swversion": "6.1.0.18912",
                "type": "ZHAPresence",
                "uniqueid": "00:17:88:01:02:00:72:3b-02-0406"
            },
            "10": {
                "config": {
                    "alert": "none",
                    "battery": 66,
                    "ledindication": false,
                    "offset": 0,
                    "on": true,
                    "pending": [],
                    "reachable": true,
                    "usertest": false
                },
                "ep": 2,
                "etag": "d5866110648ce612ff832c6dc802e9cf",
                "manufacturername": "Philips",
                "modelid": "SML001",
                "name": "Bewegungsmelder",
                "state": {
                    "lastupdated": "2018-12-11T15:46:34",
                    "temperature": 2230
                },
                "swversion": "6.1.0.18912",
                "type": "ZHATemperature",
                "uniqueid": "00:17:88:01:02:00:72:3b-02-0402"
            }
        }
    }

I think this should all be correct so far as Paper UI displays _LightlinkPi_, _Presence_ and _Temperature_ all as online.

**_Items:_**
The configuration in my file _Deconz.items_ looks like this:

```csv
Switch	TestSwitch	"Pres"  {channel="deconz:presencesensor:LightlinkPi:HueMotionPresence:presence"}
Number	TestNumber	"Temp"	{channel="deconz:temperaturesensor:LightlinkPi:HueMotionTemperature:temperature"}
```

Any idea where the mistake might be? There are also no error messages in the log. I already set the logger level of the binding to trace, but unfortunately the binding doesn't return much information. Would it be possible to integrate a few more outputs to debug the issue?

I am currently testing the binding _Dresden Elektronik deCONZ Binding_ with openHAB 2.4.0~M8-1 (Milestone Build) and the latest deconz stable release 2.5.20, but unfortunately without success.

I tested the Websocket interface with the Chrome Addon _Simple WebSocket Client_ and it works too:
![websocket](https://user-images.githubusercontent.com/10926460/49867541-23971780-fe0b-11e8-81f7-3ae85ab33ec6.PNG)

**Comment by davidgraeff** [comment]
Looks like faulty websocket message receive parsing. The Thing would go offline if the websocket connection itself could not be established or is lost in some way.

**Comment by Markkuuss** [comment]
Is there an easy way to debug this?  Or how can I find out if it is?

**Comment by Markkuuss** [comment]
The [problem that the websocket connection is now established](https://github.com/openhab/openhab2-addons/pull/4359) should be solved, at least the corresponding entry appears in the log file now.

However, the problem described here still exists. The values of the items are not updated. Here is the excerpt from the log file:

```
2018-12-13 14:05:46.650 [DEBUG] [org.openhab.binding.deconz          ] - ServiceEvent REGISTERED - {org.eclipse.smarthome.config.discovery.upnp.UpnpDiscoveryParticipant}={service.id=129, service.bundleid=209, service.scope=bundle, component.name=org.openhab.binding.deconz.internal.discovery.BridgeDiscoveryParticipant, component.id=22} - org.openhab.binding.deconz
2018-12-13 14:05:46.660 [DEBUG] [org.openhab.binding.deconz          ] - BundleEvent STARTING - org.openhab.binding.deconz
2018-12-13 14:05:46.667 [DEBUG] [org.openhab.binding.deconz          ] - BundleEvent STARTED - org.openhab.binding.deconz
2018-12-13 14:05:57.856 [DEBUG] [org.openhab.binding.deconz          ] - ServiceEvent REGISTERED - {org.eclipse.smarthome.core.thing.binding.ThingHandlerFactory}={service.id=255, service.bundleid=209, service.scope=bundle, component.name=org.openhab.binding.deconz.internal.HandlerFactory, component.id=21} - org.openhab.binding.deconz
2018-12-13 14:07:45.463 [.ItemChannelLinkAddedEvent] - Link 'TestSwitch-deconz:presencesensor:LightlinkPi:HueMotionPresence:presence' has been added.
2018-12-13 14:07:46.003 [.ItemChannelLinkAddedEvent] - Link 'TestNumber-deconz:temperaturesensor:LightlinkPi:HueMotionTemperature:temperature' has been added.
2018-12-13 14:07:53.225 [hingStatusInfoChangedEvent] - 'deconz:deconz:LightlinkPi' changed from UNINITIALIZED to INITIALIZING
2018-12-13 14:07:53.247 [DEBUG] [internal.handler.DeconzBridgeHandler] - Start initializing!
2018-12-13 14:07:53.516 [hingStatusInfoChangedEvent] - 'deconz:presencesensor:LightlinkPi:HueMotionPresence' changed from UNINITIALIZED to UNINITIALIZED (BRIDGE_UNINITIALIZED)
2018-12-13 14:07:54.029 [me.event.ThingUpdatedEvent] - Thing 'deconz:deconz:LightlinkPi' has been updated.
2018-12-13 14:07:54.069 [DEBUG] [nternal.netutils.WebSocketConnection] - Connecting to: ws://LightlinkPi:8088
2018-12-13 14:07:54.596 [DEBUG] [nternal.netutils.WebSocketConnection] - Connect: lightlinkpi/192.168.86.51
2018-12-13 14:07:54.606 [hingStatusInfoChangedEvent] - 'deconz:deconz:LightlinkPi' changed from INITIALIZING to ONLINE
2018-12-13 14:07:54.696 [hingStatusInfoChangedEvent] - 'deconz:presencesensor:LightlinkPi:HueMotionPresence' changed from UNINITIALIZED (BRIDGE_UNINITIALIZED) to INITIALIZING
2018-12-13 14:07:54.715 [hingStatusInfoChangedEvent] - 'deconz:presencesensor:LightlinkPi:HueMotionPresence' changed from INITIALIZING to OFFLINE (CONFIGURATION_PENDING)
2018-12-13 14:07:54.838 [me.event.ThingUpdatedEvent] - Thing 'deconz:temperaturesensor:LightlinkPi:HueMotionTemperature' has been updated.
2018-12-13 14:07:54.842 [me.event.ThingUpdatedEvent] - Thing 'deconz:presencesensor:LightlinkPi:HueMotionPresence' has been updated.
2018-12-13 14:07:54.846 [hingStatusInfoChangedEvent] - 'deconz:presencesensor:LightlinkPi:HueMotionPresence' changed from OFFLINE (CONFIGURATION_PENDING) to ONLINE
```

**Comment by davidgraeff** [comment]
Hm. This is bad. Please reopen the issue in this case. Two possibilities:
1. The websocket doesn't receive anything for some reason.
2. The line `ValueUpdateListener listener = valueListener.get(changedMessage.id);` resolves to `null` because the id doesn't match with one of the added sensor ids.

I'm really low on time though and the OH release is imminent. Are you familiar with Eclipse and Java? :D

**Comment by Markkuuss** [comment]
> Hm. This is bad. Please reopen the issue in this case.
@kaikreuzer, can you please reopen?

**Comment by Markkuuss** [comment]
I just set up an IDE. But I have to say, I'm not that deep into Openhab development yet. However, I noticed the following:
1. the websocket interface receives the packages correctly.
2. the line `ValueUpdateListener listener = valueListener.get(changedMessage.id);` does not resolve to `null`.

But for me the following function in the file `SensorThingHandler.java` makes no sense:

```
    public void valueUpdated(String id, SensorState state) {
        [....]
        switch (id) {
            case BindingConstants.CHANNEL_DAYLIGHT:
                 [....]
```

You're comparing a sensor id string with a channel string? Am I seeing that right? There will never be a case that applies here.

**Comment by davidgraeff** [comment]
True. The method is meant to be called like this:

```
@Override
    public void handleCommand(ChannelUID channelUID, Command command) {
        if (!(command instanceof RefreshType)) {
            return;
        }

        state.buttonevent = null;
        valueUpdated(channelUID.getId(), state);
    }
```
