### ISSUE TITLE
[netatmo] API Error "Access Failed"

### ISSUE THREAD

**Issue by OpenSpeedy** [openhab/openhab2-addons#4356]
Hi everybody,

I’m new here in this community and working since 2 weeks with openHAB on my Raspberry Pi 3B+.
After the first configuration and working with Phillips Hue and other bindings I want to try the Netatmo Binding.

First I create a Netatmo app to get the Client ID and the Secret. Then I create the Netatmo API in openHAB.
After this configuration everything works fine but then my Netatmo API changed from Initializing to Offline. In my log I found this entry:

`2018-12-10 19:45:10.154 [hingStatusInfoChangedEvent] - 'netatmo:netatmoapi:13539d91' changed from INITIALIZING to OFFLINE (COMMUNICATION_ERROR): Netatmo Access Failed, will retry in 5400 seconds.`

My openHAB version is 2.3.0-1 installed with Raspbian which is based on Debian 9 Stretch.

I try many things. First I reset my Netatmo API, then I install my whole Pi new. New OS and new openHAB installation but nothing helps. I have no more ideas.

If there is anyone who can helps me I will be very lucky.

Thanks for all

Regards Speedy

**Comment by mapo31** [comment]
Hello Speedy,

Did you find a solution for this issue ?
If yes, could you share it please ?

Thanks
Matt

**Comment by Hoerli1337** [comment]
I've had the same problem for a week.
Netatmo stays offline.
I also generated a new key and left the query offline for several hours.
Unfortunately it doesn't work.

Paper UI: OFFLINE - COMMUNICATION_ERROR
LOG: `2019-03-31 03:33:23.667 [hingStatusInfoChangedEvent] - 'netatmo:NAMain:MyIDofTheNetAtmo' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): Unable to connect Netatmo API : Verbindungsaufbau abgelehnt (Connection refused)`
