### ISSUE TITLE
[gpstracker] Add threshold setting for GPS accuracy channel 

### ISSUE THREAD

**Issue by h4lloween** [openhab/openhab2-addons#4362]
New feature request
---------------------

## Expected Behavior
Once the GPS accuracy exceeds a value (which can be set in the binding) updates should be ignored and not trigger a region enter/leave event

## Current Behavior
Sometimes, when hving a bad connection or bein underground (subway) the accuracy has very high values and triggers enter/leave events even though the device is far away from the "homezone".

## Possible Solution
- allow the user to set a threshold value in the binding (probably in "System Distance" channel
- if the accuracy channel value exceeds that threshold, ignore the location update (but still update battery, etc.)

**Comment by martinvw** [comment]
I fear we need @kaikreuzer for that you first need to be added to a team

**Comment by kaikreuzer** [comment]
@gbicskei Welcome 😄

**Comment by gbicskei** [comment]
@kaikreuzer 
Now I have a feeling that I did something wrong... 😄 Isn't it the right way fixing an issue to assign it to responsible first?

**Comment by kaikreuzer** [comment]
Every binding contributor should be a member of the https://github.com/orgs/openhab/teams/contributors team, but this unfortunately does not happen automatically, so pinging me is absolutely the right move 👍.
