### ISSUE TITLE
[Hue Emulation] Number Items are never discovered

### ISSUE THREAD

**Issue by openhab-5iver** [openhab/openhab2-addons#4378]
Before #4216, Number Items could be tagged and discovered. Using OH S1461 (and older) with hueemulation 2.4.0.201812141755, they are not discovered (even if they are tagged with "Lighting"). 

The workaround is to use a Dimmer Item, but in my case this is flawed. I use a Number Item for tracking car mileage and driving efficiency. Most times this is <100, and Dimmer would work for those times, but the car does get driven >100 miles too. To start charging the car, we tell Alexa the mileage, but if >100 it was set through Karaf. Limited to Dimmer, we can no longer drive >100 miles between charges :(.

**Comment by davidgraeff** [comment]
The Hue API is made for lights (and got extended to support wall plugs). How should a number item with an arbitrary value be mapped to a limited brightness value?

**Comment by openhab-5iver** [comment]
> How should a number item with an arbitrary value be mapped to a limited brightness value?

I'm not sure what you mean, unless the hueemulation is now reporting states to Alexa. If Alexa is asked to set a number (0-100) for a DimmableLight, then the Number Item should be updated to that value. The Number Item can be changed to a number >100, but I do not see how that would affect the hueemulation. This was working previously.

**Comment by davidgraeff** [comment]
Ahh I see. That is not how the hue emulation works.

Yes it reports states back to Alexa, but the Echo/Alexa device itself usually doesn't care (the Alexa App does, it shows you the exact value). So the Hue emulated brightness state and openHAB item state need to be bijective.

**Comment by openhab-5iver** [comment]
Understood... sounds like this is no longer possible. I'll need to look at the Alexa skill and use a temperature setpoint or something. Thank you for confirming!
