### ISSUE TITLE
[deconz] Add open/close sensor support

### ISSUE THREAD

**Issue by Markkuuss** [openhab/openhab2-addons#4400]
A support of the open/close sensor would be nice.

JSON via the API looks like this:
```
"18": {
    "config": {
        "battery": 100,
        "on": true,
        "reachable": true,
        "temperature": 0
    },
    "ep": 1,
    "etag": "d4e8e099a565f6326b9a87b3615ee483",
    "manufacturername": "LUMI",
    "modelid": "lumi.sensor_magnet",
    "name": "OpenClose",
    "state": {
        "lastupdated": "2018-12-16T00:02:47",
        "open": false
    },
    "type": "ZHAOpenClose",
    "uniqueid": "00:15:8d:00:01:f3:87:a2-01-0006"
}
```

It is very similar to the issue https://github.com/openhab/openhab2-addons/issues/4399.

**Comment by Smarthomeclub** [comment]
+1
I`ve seen its already implemented in the SensorState.java.

**Comment by Smarthomeclub** [comment]
I see. Do you know how to compile the binding after the changes? I added the (supposed) missing parts.

**Comment by Smarthomeclub** [comment]
ThingDiscoveryService.java:
`else if (sensor.type.contains("ZHAOpenClose")) { // ZHAOpenClose
            thingTypeUID = BindingConstants.THING_TYPE_OPEN_SENSOR;
        }`
SensorThingHandler.java:
`            case BindingConstants.CHANNEL_OPEN:
                if (open != null) {
                    updateState(channelID, OnOffType.from(open));
                }
                break;`
BindingConstants.java:
`public static final ThingTypeUID THING_TYPE_OPEN_SENSOR = new ThingTypeUID(BINDING_ID, "opensensor");`
and
`public static final String CHANNEL_OPEN = "open";`
thing-types.xml:
`<thing-type id="open">
		<supported-bridge-type-refs>
			<bridge-type-ref id="deconz" />
		</supported-bridge-type-refs>
		<label>Open sensor</label>
		<description>An Open sensor</description>
		<channels>
			<channel typeId="open" id="open"></channel>
		</channels>
		<config-description>
			<parameter name="id" type="text" required="true">
				<label>Sensor ID</label>
				<description>The deCONZ bridge assigns an integer number ID to each sensor.</description>
			</parameter>
		</config-description>
	</thing-type>

	<channel-type id="open">
		<item-type>Switch</item-type>
		<label>Open</label>
		<description>Open detected</description>
		<state readOnly="true"></state>
	</channel-type>`

**Comment by davidgraeff** [comment]
Guys, please create Pull Requests. As soon as the PRs are accepted and merged, it takes maybe 2 days and you have the changes in openHAB 2.5 snapshot.

**Comment by stefanbraun1** [comment]
Would be great to also pass the temperature to Openhab. Thanks in advance.

**Comment by Markkuuss** [comment]
> Would be great to also pass the temperature to Openhab. Thanks in advance.

The temperature is already included since the first release of the addon. The thing is called `temperaturesensor`
https://www.openhab.org/addons/bindings/deconz/#supported-things

**Comment by stefanbraun1** [comment]
I don't mean the temperature sensor as such. The open/close sensor also provides the temperature, similar to the battery level as config element. Would be great being able to capture this as well.

**Comment by davidgraeff** [comment]
This binding doesn't expose physical devices, it exposes all found values. So the temperature value should be covered, no matter which device is providing it.

**Comment by stefanbraun1** [comment]
Not so sure. From reading the code it only captures the battery level but not temperature as config items. Please refer to the JSON in the initial posting above. Hope this clarifies what I mean.

**Comment by davidgraeff** [comment]
I see. It is not under "state" but under "config".

**Comment by Smarthomeclub** [comment]
After trying out the new support I have the "fault" that the Open/Close Thing gets offline after a few hours of no action. I have no idea how to solve this problem. The phoscon user interface has no problems. In the phoscon its shown as offline too, but after the next action its shown as online again. I use the (CMIT ID: 2015DP0291) Xiaomi door sensors.

**Comment by Markkuuss** [comment]
I have the same problem.  All sensors work fine, only the Open/Close sensor goes offline.  Is there a timeout if there is no action for a long time?

I suspect that it only appears with the Open/Close sensor, because the other sensors (temperature, motion, ...) report regularly.

@Smarthomeclub are you opening a new issue with a link to PR #4418?
