### ISSUE TITLE
[astro] Can't update state for channel :position#elevation

### ISSUE THREAD

**Issue by janb14** [openhab/openhab2-addons#4404]
After sucessful using the astro binding for over a year now, a couple of days ago i noticed missing/incomplete data provided by the position#elevation and position#azimuth channels. Does anyone has anything similar in his logs/can help me with a workaround?

## Expected Behavior
I was updating two Nu´mber Variables and saving them to mysql persistance to visualize in Grafana and to tell artificial and natural light apart. Suddenly two channels dowsnt seem to work anymore even if testwise upgrading to 2.5.0-SNAPSHOT opr using the latest 2.4.0-SNAPSHOT

## Current Behavior
Currently my rules fire but only produce either null states or garbage data as u can see in the log/pictures.

> 2018-12-18 08:09:19.875 [ERROR] [ding.astro.handler.AstroThingHandler] - Can't update state for channel astro:sun:home:position#elevation : null
> java.lang.reflect.InvocationTargetException: null
>         at sun.reflect.GeneratedMethodAccessor80.invoke(Unknown Source) ~[?:?]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
>         at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
>         at org.eclipse.smarthome.binding.astro.internal.util.PropertyUtils.getPropertyValue(PropertyUtils.java:98) [199:org.eclipse.smarthome.binding.astro:0.10.0.201808242044]
>         at org.eclipse.smarthome.binding.astro.internal.util.PropertyUtils.getPropertyValue(PropertyUtils.java:100) [199:org.eclipse.smarthome.binding.astro:0.10.0.201808242044]
>         at org.eclipse.smarthome.binding.astro.internal.util.PropertyUtils.getPropertyValue(PropertyUtils.java:88) [199:org.eclipse.smarthome.binding.astro:0.10.0.201808242044]
>         at org.eclipse.smarthome.binding.astro.internal.util.PropertyUtils.getState(PropertyUtils.java:53) [199:org.eclipse.smarthome.binding.astro:0.10.0.201808242044]
>         at org.eclipse.smarthome.binding.astro.handler.AstroThingHandler.publishChannelIfLinked(AstroThingHandler.java:156) [199:org.eclipse.smarthome.binding.astro:0.10.0.201808242044]
>         at org.eclipse.smarthome.binding.astro.handler.AstroThingHandler.publishPlanet(AstroThingHandler.java:139) [199:org.eclipse.smarthome.binding.astro:0.10.0.201808242044]
>         at org.eclipse.smarthome.binding.astro.handler.SunHandler.publishPositionalInfo(SunHandler.java:61) [199:org.eclipse.smarthome.binding.astro:0.10.0.201808242044]
>         at org.eclipse.smarthome.binding.astro.internal.job.PositionalJob.run(PositionalJob.java:45) [199:org.eclipse.smarthome.binding.astro:0.10.0.201808242044]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
>         at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
>         at java.lang.Thread.run(Thread.java:748) [?:?]
> Caused by: java.lang.NumberFormatException
>         at java.math.BigDecimal.<init>(BigDecimal.java:494) ~[?:?]
>         at java.math.BigDecimal.<init>(BigDecimal.java:383) ~[?:?]
>         at java.math.BigDecimal.<init>(BigDecimal.java:806) ~[?:?]
>         at org.eclipse.smarthome.core.library.types.QuantityType.<init>(QuantityType.java:104) ~[?:?]
>         at org.eclipse.smarthome.binding.astro.internal.model.Position.getElevation(Position.java:62) ~[?:?]
>         ... 18 more

[Picture 1 shows old vs new behaviour](https://ibb.co/9HLVKNV)
[Picture 2 shows the error in more detail](https://ibb.co/sCNfXcs)

Obviously the sun should be down at midnight in winter and not go up and down like this (Picture 2).

## Steps to Reproduce (for Bugs)

My things:
> astro:sun:home          [geolocation="50.7778258,6.09564,163"   ,interval=60]
> astro:moon:home       [geolocation="50.7778258,6.09564"       ,interval=60]

My Items:
> Number Sun_Elevation "Elevation [%.2f]" <sun> (Persist)channel="astro:sun:home:position#elevation"}
> Number Sun_Azimuth "Azimuth [%.2f]" <sun> (ThirtyM)                                                                   {channel="astro:sun:home:position#azimuth" }

My Sitemap:
> Frame label="Astro"{
>                 Text item=Sun_Elevation
>                 Text item=Sun_Azimuth
>  }

My Rules:

> rule "Sunset Rule"

> when
>     Channel 'astro:sun:home:set#event' triggered START
> then
>     postUpdate(Sunset_Azimuth,Sun_Azimuth.state)
>     logInfo("Shaddow","Setting Sunset Azimuth.")
> end
> rule "Sunrise Rule"
> when
>     Channel 'astro:sun:home:rise#event' triggered START
> then
>     postUpdate(Sunrise_Azimuth,Sun_Azimuth.state)
>     logInfo("Shaddow","Setting Sunrise Azimuth.")
> end

## Context
Im not needing the elevation for something mission critical but it seems something broke a couple of days ago and im unshure if im the problem or the astro api broke.

## Your Environment
openjdk version "1.8.0_192"
FreeBSD 11.2 (FreeNAS Jail)
currently openHAB 2.4.0 Build #1340 (last working built,also tried latest 2.4.0-Snapshot and 2.5.0-Snapshot without success)
Addon Version 2.4.0 Snapshot shown in PaperUI

**Comment by wborn** [comment]
Thanks for the comprehensive issue @janb14 ! Can you create it in the Eclipse SmartHome [issue tracker](https://github.com/eclipse/smarthome/issues?q=is%3Aopen+is%3Aissue+label%3ABinding-Astro) instead? That's the repository where the Astro Binding source code is maintained.
