### ISSUE TITLE
[mySQL Persistence] No connection to DB, SQLException: The server time zone value 'AEDT' is unrecognized.

### ISSUE THREAD

**Issue by dp3049** [openhab/openhab2-addons#4412]
## Expected Behavior
Successful connection to the persistence DB (mySQL) to allow persistence information to be stored in the DB.

## Current Behavior
This behaviour only started being exhibited following an in-place update from OH2.4 M8 to OH2.4.0 Stable. No other system or config changes were made, reverting back to M8 resolves the issue.

On OH startup, as devices are being brought up, persistence fails with the following error messages in the log:

````
Loading class com.mysql.jdbc.Driver'. This is deprecated. The new driver class iscom.mysql.cj.jdbc.Driver’. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.

No connection to database. Cannot persist item 'light_study (Type=DimmerItem, State=100)'! Will retry connecting to database when error count:0 equals errReconnectThreshold:0

14:20:41.388 [ERROR] [ysql.internal.MysqlPersistenceService] - mySQL: Failed connecting to the SQL database using: driverClass=com.mysql.jdbc.Driver, url=jdbc:mysql://localhost:3306/OpenHAB, user=openhab2

java.sql.SQLException: The server time zone value 'AEDT' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.
````

## Steps to Reproduce (for Bugs)
1. Build a working OH2.4 M8 environment, with mySQL persistence add-on,
2. update using the OH update command to 2.4.0 stable.

## Context
Persistence data fails to be written to the mySQL database following update.

## Your Environment
* Version used: (fails) 2.4.0 Stable 
* Version used: (works) 2.4.0-SNAPSHOT Build #1399  
* Bindings:
  + zwave
  + Nest
  + Wemo
  + MQTT
* Services:
  + OpenHab Cloud
  + mySQL Persistence
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
    * Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
    * Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):
  + OS X 10.14.2 (Mojave)

**Comment by wborn** [comment]
If this is an issue in the addon the openhab1-addons [issue tracker](https://github.com/openhab/openhab1-addons/issues) should be used to report it.
That's the repository where the mysql persistence addon code is maintained.

**Comment by mhilbush** [comment]
Possibly the same as [this](https://github.com/openhab/openhab1-addons/issues/5706)? Unfortunately, I forgot to add a note to the README...

Did you try restarting the mySQL service?

**Comment by dp3049** [comment]
Thanks Wouter, moved to openhab1-addons issue #5739.

**Comment by wborn** [comment]
Thanks for creating https://github.com/openhab/openhab1-addons/issues/5739 @dp3049 !

**Comment by dp3049** [comment]
@mhilbush it does appear to be related, however, the system has been rebooted several times while running 2.4.0 stable. And as mentioned, 2.4.0 M8 consistently does not exhibit the issue, switching back to 2.4.0 stable and it consistently fails.
