### ISSUE TITLE
[sonos] Add support for night mode and speech enhancement

### ISSUE THREAD

**Issue by pdcemulator** [openhab/openhab2-addons#4414]
As a user of a Sonos Beam Soundbar, I would like to control night mode and speech enhancement.
This mode is available on Sonos Beam, Playbar and Playbase devices.

As those modes can controlled with node-sonos-http-api, I suppose there is a Sonos API available for :-)

- [Sonos Support information](https://support.sonos.com/s/article/1948?language=en_US)
- [node-sonos-http-api](https://github.com/jishi/node-sonos-http-api)

**Comment by wborn** [comment]
The Sonos Binding is maintained at Eclipse SmartHome. So it's best to communicate with the Sonos Binding developers using the Eclipse SmartHome [issue tracker](https://github.com/eclipse/smarthome/issues). Can you create an issue in that tracker instead?
