### ISSUE TITLE
[miio] Add support for controlling devices from another network

### ISSUE THREAD

**Issue by mpuff** [openhab/openhab2-addons#4422]
Hello,

i have an own network for the xiaomi devices, on this nat is blocked.
i cant control the xiaomi devices, becaus openhab is in the fritzbox network, can you add a funktion that i can control the xiaomi devices only with the ip, without checking if the xiaomi device is online?
i can get the token with an secound debian device in the secound network, so i can copy it.

**Comment by marcelrv** [comment]
The binding does not limit you in selecting the necessary ip addresses. There is no restricting in the binding to whatever network.

However, some of the devices won't allow connections outside of their subnet. Note that behaviour  is not uniform for all Xiaomi devices.
