### ISSUE TITLE
[hueemulation] Items with state UNDEF do not receive OFF commands

### ISSUE THREAD

**Issue by ngrodum** [openhab/openhab2-addons#4436]
## Expected Behavior
I have an item in state UNDEF / null, when I use Alexa to turn it off, the item should receive a command/state change to OFF, and the event should trigger a rule so I can e.g. instruct by IR blaster to turn my Christmas tree off 🎄→ 🌲.

## Current Behavior
I have an item in state UNDEF / null, when I use Alexa to turn it off, the item does not receive a command/state change to OFF, and the event does not trigger a rule.
Nothing in debug log of hueemulation, unlike when turning ON, where I see:
[DEBUG] [ulation.internal.HueEmulationService] - sending ON to XmasTreeOnOff

This used to work pre 2.4, and I believe it is a regression.

## Possible Solution
I'm not sure it is due to an internal change in huemulation (that the event stops there), or if it is because of how the state of items are exposed in 2.4 (and the event never even reached the hue emulator). I can see that they are reported as "off" (or on=false) in the hue rest api:
{
“state”: {
“bri”: 0,
“ct”: 500,
“on”: false,
“reachable”: true,
“mode”: “homeautomation”,
“alert”: “none”
},

https://community.openhab.org/t/hueemulation-and-expire-undef-ignores-off-comands/60720

## Steps to Reproduce (for Bugs)
Create this item (note that Switchable for me means white light (switched in hue emulation config due to US Amazon account)). I use the expire binding because openhab cannot know the state reliable enough (e.g. IR miss, another physical remote etc), and I need to be able to send ON or OFF at any time. I have been using the expire binding to accomplish this.

Switch XmasTreeOnOff "Christmas Tree" (gLightsLivingRoom) [ "Switchable" ] { expire="2s" }

I have a rule something like this:
val org.eclipse.xtext.xbase.lib.Functions$Function1<String, String> sendIR = [ String cmdKey |  executeCommandLine("irblastcmd " + cmdKey, 1000) ]

rule "XmasTree onoff"
  when Item XmasTreeOnOff received command
then
 sendIR.apply('xmas_' + receivedCommand) //xmas_ON or xmas_OFF
end

## Context
I can't turn off my Christmas tree 🎄! And other lights and items where the state is UNDEF.

## Your Environment
Just upgraded from 2.3 to 2.4 when this started happening.

**Comment by Carlos-35** [comment]
I can confirm the behavior. If I want to control my vacuum cleaner or the lamps via the Philips Hue emulation then after updating to openHAB 2.4 this only works if I set the device to the other state before. For example, I can only switch on my vacuum cleaner if I have explicitly switched it off before.

**Comment by Matthy1810** [comment]
I can confirm the issue. I experience the same behaviour.
Furtheremore Alexa (or the hue emulation?) does not send the command if the command is the same as the last observed state.

**Comment by Matthy1810** [comment]
This PR should fix it: https://github.com/openhab/openhab2-addons/pull/4478
I'll test it as soon as a new build is online.

**Comment by Matthy1810** [comment]
It's fixed in the snapshot-build.

**Comment by Carlos-35** [comment]
Thanks, it is working again with the snapshot build.
