### ISSUE TITLE
[openweathermap] Enhancement - provide icon ID data channel

### ISSUE THREAD

**Issue by Rossko57** [openhab/openhab2-addons#4448]
OpenWeatherMap API provides weather condition codes for current & forecasts.
Textual condition e.g "Light showers"
numeric condition ID e.g. "521"
icon ID e.g "12n"
The icon ID is from a less numerous graphic symbol set than the full condition, but additionally includes day/night coding.   It is not straightforward to directly calculate an icon ID from the general condition ID.

The OWM binding uses this icon ID to calculate a URL and retrieve OWM images.  But the URL or icon ID are not currently exposed to openHAB users.

Enhancement request - expose the icon ID as a string data channel in a similar manner to condition ID.
This would allow users to implement their own icon schemes.

**Comment by cweitkamp** [comment]
Thanks for reporting this issue.
Can you create an issue for this in the Eclipse SmartHome project [issue tracker](https://github.com/eclipse/smarthome/issues) instead?
That is the repository where the source code for the OWM binding is maintained.

**Comment by Rossko57** [comment]
Done -
https://github.com/eclipse/smarthome/issues/6732

Sorry, I struggle to find the correct filing place for issues :)
