### ISSUE TITLE
[network] Use sudo access to arping if available

### ISSUE THREAD

**Issue by yuergen** [openhab/openhab2-addons#4455]
## Expected Behavior
The documentation of the binding makes note of the default permissions of arping (only root may use it). The solution offered is to set the suid bit (chmod u+s /usr/sbin/arping), allowing all users on the machine to run it.
Sudo is a well established technique to manage access to root owned ressources. I would have expected for the binding to probe is arping is available via sudo.

## Current Behavior
Probing of devices with arping fails, if arping is not suid root.

### Regarding the binding
- Probe if arping is available via sudo.
- Usage of "sudo arping ..." when sudo access is available.

### Regarding the documentation
- Mentioning of the possibility of adding arping to the sudo configuration
  - \# cat /etc/sudoers.d/openhab
  - openhab ALL=(ALL) NOPASSWD: /usr/sbin/arping
- Providing an example on how to test sudo access to arping
  - The following example works when logged in as root or as openhabian:
  - \# sudo -u openhab **sudo** arping 192.168.178.22
  - Note that there are two sudo calls in that command line.

## Context
I want to use the binding to detect the presence of mobile phones while having the the platform openHAB runs on configured as secure as possible.

## Your Environment
Raspberry Pi running openhabian with all updates installed (openhab 2.4.0-1 as of writing).

**Comment by davidgraeff** [comment]
This is only a workaround. Soon windows people will ask to add "runas" support, too.
On linux you should nowadays use a policykit helper application to gain privileged permissions.

openHAB should instead gain a uniform way to execute privileged processes.

I vote for won't fix. WDYT @wborn @martinvw?

**Comment by J-N-K** [comment]
I agree with @davidgraeff. 

BTW: I didn’t check but: wouldn‘t „sudo arping“ as path in the binding config achieve the same?
