### ISSUE TITLE
[modbus] CONFIGURATION_ERROR status has no status description

### ISSUE THREAD

**Issue by ssalonen** [openhab/openhab2-addons#4459]
All configuration errors in `data` thing are missing the status description. As discussed in [community forums](https://community.openhab.org/t/modbus-binding-with-wago-controller/60642/21?u=ssalonen), this is a regression caused in #4304 (not passing description to `updateStatus`).

## Expected Behavior

Configuration errors (`CONFIGURATION_ERROR`) have description explaining the error.

## Current Behavior

Thing has no thing description.

## Possible Solution

PR to follow

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Version used: (e.g., openhab and addon versions)
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):

**Comment by sharmmoh1983** [comment]
@ssalonen 
I ma still getting this issue while creating ModbuS data Thing
Configuration chevron_right Things chevron_right Modbus data
 
Modbus data
Modbus data

Data thing extracts values from binary data received from Modbus slave. Similarly, it it responsible of tranlating openHAB commands to Modbus write requests

Status: OFFLINE - CONFIGURATION_ERROR


Channels

**Comment by ssalonen** [comment]
@sharmmoh1983 what version of openhab and what version of binding you are using?

Please note that latest stable release 2.4.0 still has the bug, there has not been a new release since then yet.

**Comment by sharmmoh1983** [comment]
@ssalonen 
Thanks for the reply. Are there any plans for future release ? Also we want to make use of Modbus data feature so what is the best way out now.

Sorry for asking question out of context,  I want to see and project  data read from master slave on to openhab ui and Read poll is showing online 

Please let me know to achieve the same

**Comment by ssalonen** [comment]
@sharmmoh1983 you are asking the wrong guy and at a wrong place, the community forums might be the right place to engage core developers working on this. 

When it comes to modbus, you have an option to update the binding to a snapshot version, or actually even update the whole openhab and bindings to 2.5.0 milestone release (it's kind of semistable prerelease). Regarding openhab milestone release, see e.g. this thread https://community.openhab.org/t/openhab-milestone-builds/50359/332. The download page on openhab.org also has instructions.

**Comment by ssalonen** [comment]
One more thing : when it comes to this issue, you can tune the logging settings such that the configuration error is visible at least in the logs. No need to update anything 

See https://community.openhab.org/t/modbus-binding-with-wago-controller/60642/14
