### ISSUE TITLE
No way of publishing with retain with [MQTT] 2.4 addon

### ISSUE THREAD

**Issue by robygi** [openhab/openhab2-addons#4466]
## Current Behavior
I made a thing:
`Thing topic mytopic "Description"  {
     Type string : mytopicstring "Description2" [
         stateTopic="OH2/mytopic",
         commandTopic="OH2/mytopic",
         retained=true
    ]
}
`

Then I linked it via PAPER UI to the following item:
`String mytestItem "My test item" { channel="mqtt:topic:mytopic:mytopicstring" }`

I wrote a rule for the switch item _test_ :
`rule "Test switch changed"
when
     Item test changed
then
    if (test.state == ON) {
        sendCommand(mytestItem, "testvalue1")
    } else {
        sendCommand(mytestItem, "testvalue2")
    }
`

When the item test changes no message is publish to the mqtt broker.
The log shows the following messages:
`12:59:53.733 [INFO ] [smarthome.event.ItemCommandEvent     ] - Item 'test' received command ON
12:59:53.759 [INFO ] [smarthome.event.ItemStateChangedEvent] - test changed from OFF to ON
12:59:53.770 [INFO ] [smarthome.event.ItemCommandEvent     ] - Item 'mytestItem' received command testvalue1
12:59:53.781 [INFO ] [arthome.event.ItemStatePredictedEvent] - mytestItem predicted to become testvalue1
12:59:55.646 [INFO ] [smarthome.event.ItemCommandEvent     ] - Item 'test' received command OFF
12:59:55.663 [INFO ] [smarthome.event.ItemStateChangedEvent] - test changed from ON to OFF
12:59:55.677 [INFO ] [smarthome.event.ItemCommandEvent     ] - Item 'mytestItem' received command testvalue2
12:59:55.687 [INFO ] [arthome.event.ItemStatePredictedEvent] - mytestItem predicted to become testvalue1`

Even using postUpdate instead of sendCommad no message is published to mqtt. The log is as follow:
`12:57:25.657 [INFO ] [smarthome.event.ItemCommandEvent     ] - Item 'test' received command ON
12:57:25.688 [INFO ] [smarthome.event.ItemStateChangedEvent] - test changed from OFF to ON
12:57:25.710 [INFO ] [smarthome.event.ItemStateChangedEvent] - mytestItem changed from testvalue2 to testvalue1
12:57:27.279 [INFO ] [smarthome.event.ItemCommandEvent     ] - Item 'test' received command OFF
12:57:27.304 [INFO ] [smarthome.event.ItemStateChangedEvent] - test changed from ON to OFF
12:57:27.408 [INFO ] [smarthome.event.ItemStateChangedEvent] - mytestItem changed from testvalue1 to testvalue2` 

It seems that with sendCommand the value of the item is “predicted” to became always the last updated value (in this case testvalue1, from a previous test), while with postUpdate the value in OH is changed accordingly to the statement but in both cases there is no publish to mqtt.

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Version used: openHAB 2.4.0, openhab-binding-mqtt 2.4.0, mosquitto 1.5.5
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...): Raspbian Stretch

**Comment by wborn** [comment]
Please use the Eclipse SmartHome [issue tracker](https://github.com/eclipse/smarthome/issues) for reporting MQTT Binding issues. That's the repository where the source code of that addon is maintained.
