### ISSUE TITLE
[enocean] USB300 Dongle does not show any events

### ISSUE THREAD

**Issue by edgarjung** [openhab/openhab2-addons#4476]
## Expected Behavior

Using USB300 Dongle (FT1S8I7G), I'd like to receive  events from Simple Switch D5-00-01. No events will be sent thru openhab

## Current Behavior

looking up openhab.log or events.log. No event has been thrown open or closing the switch.

1. Testet with DolphinView Advanced (works fine)  - Windows - getting Signals (ON/OFF)
2. Switched to UBUNTU, did a cat </dev/ttyUSB0 - works fine
3. reboot an installed Dongle and Switch - both green in paperUI - no reaction in events.log nor openhab.log
4. added openhab to group dialout, /dev/ttyUSB0, crw-rw----
5. For Testing, changed to RockerSwitch - does not help
6. added EXTRA_JAVA_OPTS="-Dgnu.io.rxtx.SerialPorts=/dev/ttyUSB0" to /etc/defaults/openhab2 - does not help
7. After all - reinstalled enocean (Standard openhab) - an the devices - does not help either.
8. Set KARAF (enocean binding) to DEBUG/TRACE - no reaction

stty -F /dev/ttyUSB0 shows

speed 57600 baud; line = 0;
min = 1; time = 1;
-brkint -icrnl -imaxbel
-opost -onlcr
-isig -icanon -iexten -echo -echoe -echok -echoctl -echoke

## Steps to Reproduce (for Bugs)

1.
2.

## Context

using a virtual machine on Synology DSM 918+ as Openhab Server

## Your Environment

* Version used: (e.g., openhab and addon versions)
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):

JAVA
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-0ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

UBUNTU
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

**Comment by fruggy83** [comment]
Hi @edgarjung,

can we also close this issue here as we did it in the openocean [repo](https://github.com/fruggy83/openocean/issues/41)?

Best regards
Daniel

**Comment by edgarjung** [comment]
I am using a Solar Switch. I tested it on my desk with enough light, when it worked.
Now I found out, once installed on my door, it does not have enough light, to send the status change.
So no OPENHAB or openocean issue.
