### ISSUE TITLE
[hueemulation] Configuration documentation is unclear about where Hue Emulation may be configured

### ISSUE THREAD

**Issue by ScottKinSF** [openhab/openhab2-addons#4482]
I am confused by the configuration found in the Configuration section of the binding documentation. It is clear that the binding may be configured via the PaperUI, but some of the configuration specifics make it appear as though it may also be possible to configure the binding via a text configuration file, for [example](https://github.com/openhab/openhab2-addons/tree/master/addons/io/org.openhab.io.hueemulation#configuration):
> Configuration:
> All options are available in Paper UI.
>
> Pairing can be turned on and off:
>
> org.openhab.hueemulation:pairingEnabled=false
> You can define a pairing timeout in seconds. After that timeout, the pairingEnabled is automatically set to false.
>
> org.openhab.hueemulation:pairingTimeout=60

Is it possible to configure the pairing settings in a text file? The way they are shown in the documentation makes it appear (to me, anyway) that they may be configured in a text file. If it is indeed possible to configure the Hue Emulation binding with a text file, what name must that file have and where is it stored? What, if any, other settings may be specified?

If it is not possible to configure the binding with a text file, an explicit statement to that affect would help users like me who prefer to configure their systems using text configuration files.

I am happy to submit a PR for the documentation if it is possible to config Hue Emulation settings via a text file, I just need the detailed information before I can prepare a PR.

-- Thanks!

**Comment by davidgraeff** [comment]
Not related to hueemulation. Closing therefore.

FYI: Every openHAB service can be configured via textual means, the console and the REST interface (Paper UI). The documentation is currently improved to point that out.
