### ISSUE TITLE
[lutron] Add support for new keypad models

### ISSUE THREAD

**Issue by LoungeFlyZ** [openhab/openhab2-addons#4484]
The lutron binding doesn't seem to handle new keypad models such as `RRD-HN6BRL-XX` due to the model numbers not being supported in the keypadhandlers configureComponents method.

The offending code is here i believe:
https://github.com/openhab/openhab2-addons/blob/f1606b8b13455cfe382136c58db5850437cbc89a/addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/KeypadHandler.java#L159

@bobadair given your familiarity with this binding could you comment?  Is it as simple as adding the model variants in the switch statement? 

The particular keypad i have in the HN6BRL.  It looks like the switch handles the H6BRL, but not this slightly newer model.

I would have not contributed to this repo before, and could do so if desired.

**Comment by LoungeFlyZ** [comment]
Thanks @bobadair that would be great! I noticed because during the auto-discovery i noticed it wasn't picking up the "N" keypads.

**Comment by bobadair** [comment]
Well, you always have to select the correct keypad model after auto-discovery.  By default, the type will be set to “Generic”.  If you mean that auto-discovery is not detecting the HN-type hybrid keypad devices at all, then that would require a separate fix in the discovery code.

I did some quick testing on my own RA2 system with a dummy HN3S device, and it appears in DbXmlInfo.xml from the main repeater as DeviceType="HYBRID_SEETOUCH_KEYPAD".  That is the same as it would be for an older device like an H3S, so auto-discovery should work with it. If you do see a problem with HN* hybrid keypad models not being auto-discovered at all, please add another note here.  Please also try to include the “device” line for one from your own DbXmlInfo.xml file, which you can pull from the main repeater at http://<repeater_ip>/DbXmlInfo.xml.  It would look something like:

<Device UUID="13504" Name="Test CL Hybrid Keypad" SortOrder="0" IntegrationID="79" GangPosition="0" DeviceType="HYBRID_SEETOUCH_KEYPAD" SerialNumber="0">
