### ISSUE TITLE
[onkyo] Exception in statusUpdateReceived: Value must be between 0 and 100

### ISSUE THREAD

**Issue by AlexKay88** [openhab/openhab2-addons#4488]
Device: Onkyo A/V Receiver TX-NR474
Since update to openHAB 2.4 stable release I get every 30 seconds this warning in openhab.log:
[WARN ] [.onkyo.internal.handler.OnkyoHandler] - Exception in statusUpdateReceived for Onkyo Receiver @192.168.99.222:60128. Cause: Value must be between 0 and 100, data received: [command=MVL, value=42]
I got no such warnings running openHAB 2.3 stable before upgrade.
What could be done to get rid of these warning messages?
Do you any configs, logs or debug logs for deeper analysis?

**Comment by cweitkamp** [comment]
Would be nice to have a stack trace of the exception. May I ask you to enable DEBUG logging for the binding and post the results?

**Comment by AlexKay88** [comment]
Thanks for your helping hand, Christoph!
Meanwhile the exception disappeared since a few days and did not came back.
Good that it disappeared, but bad to find out the root cause.
If there will be a next occurrence, I am prepared to enable DEBUG logging.

**Comment by cweitkamp** [comment]
You are welcome. Please let me know when the problem occurres again. In the meanwhile I close this issue.
