### ISSUE TITLE
[deconz] Add open/closed sensor offline - not reachable - after some time 

### ISSUE THREAD

**Issue by Smarthomeclub** [openhab/openhab2-addons#4505]
[deconz] Add open/closed sensor offline - not reachable - after some time 

Binding: Deconz version 2.5

After adding the open/closed sensor in openhab, the sensor gets offline after a while. Whenever the state changed to offline it is not possible to get any data from the sensor.

## Expected Behavior

Normally the sensor should be online after/while it published anything.

## Current Behavior

After adding the open/closed sensor in the open hab binding, the sensor gets offline after a while. After the state changed to offline it is not possible to get any data from the sensor. The only way to start running again ist to delete the sensor in paper UI or the file.things and reinitiate the sensor. From this moment it starts working for approximately one hour if the sensor does not publish anything. The time range extends if the sensor publish any data.

In the phoscon user interface the sensor is although offline but after publishing anything its getting online again.

## Possible Solution
At the moment I have no idea how to solve the problem. Maybe there is a timeout for the sensor in openhab. If the binding emulates an action (last state) the timeout issue might be fixed.

## Your Environment

Openhab 2.4 release based on the preconfigured openhab-image. 
Binding Version 2.5 from December 2018

PR #4418 
Closed Issue #4400 
Involved person @Markkuuss

**Comment by Smarthomeclub** [comment]
Still have this issue...
What about you @Markkuuss?

**Comment by Hex-3-En** [comment]
Hey,
I'm currently rewriting the whole binding.
Can you please give me some details about the sensor like manufacturer and model?
I'd like to know especially, whether it's a ZGPSensor, as this will be handled by my rewrite with no extra fixes, due to all ZGPSensors actually not beeing reachable all the time on purpose.

**Comment by Smarthomeclub** [comment]
Hey,

the sensor is a ZHAOpenClose Type. Its a door sensor from Xiaomi. As long as the sensor is reachable in phoscon you are able to pair the sensor with openhab. Due to the timeout-issue the sensor gets online if the binding is reconnected to phoscon and the sensor is reachable in phoscon.

`{
"config":{"battery": null, "on": true, "reachable": false, "temperature": 0},
"ep": 1,
"etag": "xxxx",
"manufacturername": "LUMI",
"modelid": "lumi.sensor_magnet",
"name": "Fenster- / Türkontaksensor",
"state":{
"lastupdated": "2019-01-17T06:39:20",
"open": false
},
"type": "ZHAOpenClose",
"uniqueid": "xxxx"
},
 `

**Comment by cweitkamp** [comment]
The `ONLINE` / `OFFLINE` status of the sensor thing is based on the `config.reachable` property of the deCONZ REST API response. This is `false` in your example which leads me to the assumption that the sensor is either not reachable in your Zigbee mesh or the interface reports it incorrectly.

What do you mean by "the sensor is reachable in phoscon". Does it report / indicate changes over there?

**Comment by Hex-3-En** [comment]
It's bad handling by the binding.
Even if the guys of the Zigbee-Binding tell people Xiaomi is not following standards... they ARE.
All Xiaomi/Lumi devices I looked up recently are Zigbee 3.0 IASZone(Security) devices.
As the zigbee spec-douments at zigbee.org tell, your sensor is specified as sleepy end device, which means it's not reachable in case of no event to save battery. Thats why those devices report battery low trigger, as you would not recognize battery going down in time.

Conclusion:
It's "offline" on purpose and will be handled better in my new binding.

Hope to have beta released within next 7 days.

**Comment by Smarthomeclub** [comment]
As soon as the thing gets offline in deconz, its not reachable anymore. If I move the window the sensor gets online in deconz but ist still not reachable in openhab. It‘s a low energy device so you wont be able to get an answer from a request.

**Comment by Smarthomeclub** [comment]
Update:
Since i do not get and websocket timeout the sensor Problem is solved.
