### ISSUE TITLE
[mihome] Add Support for Xiaomi Aqara Smart Wall Socket (86plug)

### ISSUE THREAD

**Issue by github4pbp** [openhab/openhab2-addons#4511]
Binding: mihome-2.5.0-SNAPSHOT.jar
OpenHAB 2.4
Raspberry Jessy

@dimalo

This device is not supported by the binding but it can be added to OpenHAB configuration using Basic Xiaomi MiHome Device configuration.

here some traces:
{"cmd":"report","model":"ctrl_86plug.aq1","sid":"158d000201017c","short_id":34496,"data":"{\"status\":\"on\"}"}
{"cmd":"report","model":"ctrl_86plug.aq1","sid":"158d000201017c","short_id":34496,"data":"{\"status\":\"off\"}"}
{"cmd":"heartbeat","model":"ctrl_86plug.aq1","sid":"158d000201017c","short_id":34496,"data":"{\"voltage\":3600,\"status\":\"off\",\"inuse\":\"0\",\"power_consumed\":\"23\",\"load_power\":\"0.00\"}"}

This is my second issue, so I would like to thank all the OpenHAB team for the excellent work and support available on the web.

**Comment by dimalo** [comment]
You're welcome, sir!
If you add it as a basic device can you copy the output of all channels, as soon as they have values?
For write_ack of course you have to send a command to it... 😄 
Just want to make sure we don't miss any info. Thanks!

**Comment by dimalo** [comment]
For the time being, if there is no new info the plug sends I added it to the models. It's just two lines as there is already a plug device implemented 👍

**Comment by dimalo** [comment]
Thanks @github4pbp!
There is no new data the plug sends, so the old implementation can be used.
Please make suer you have that change in the snapshot version, I'm pretty sure it should work - even if it doesn't look like that in your tests.
If you look [here](https://github.com/openhab/openhab2-addons/pull/4300/files) and [here](https://github.com/openhab/openhab2-addons/pull/4279/files) it has worked with other models as well.

**Comment by github4pbp** [comment]
Tested with the latest snapshot version and everything is working as designed with no issues.

One suggestion - the new plug should be  recognized as Xiaomi Aqara Smart Wall Socket instead Xiaomi Aqara Smart Socket Plug
![socket](https://user-images.githubusercontent.com/36746189/51088484-fff82180-1768-11e9-8091-1ca8ba053b7b.jpg)

and as well should be added to the binding supported things (ctrl_86plug.aq1) here:
![sc](https://user-images.githubusercontent.com/36746189/51088566-ed321c80-1769-11e9-954e-8eb0be240769.png)

@dimalo Thank you very much!

**Comment by roha999** [comment]
hi
i install Binding: mihome-2.5.0-SNAPSHOT.jar , 
209 │ Active   │  80 │ 2.5.0.201902140720     │ Xiaomi Mi Smart Home Binding

restart openhab but still get
Unsupported Xiaomi MiHome Device "86plug"
Basic Xiaomi MiHome Device

what i am doing wrong?

**Comment by github4pbp** [comment]
@roha999

try using configuration files and it should work. Example for things:

Thing mihome:sensor_plug:158d000xxxxxxx "Aqara Socket Plug" @ "Kitchen" [item
Id="158d000xxxxxxx"]

**Comment by roha999** [comment]
try for this one "Unsupported Xiaomi MiHome Device "86plug"
Basic Xiaomi MiHome Device
158d000182450a"

add a record to things file as 
Thing mihome:sensor_plug:158d000182450a "Aqara Socket Plug" @ "Kitchen" [itemId="158d000182450a"]
and get no new device
http://prntscr.com/mot8yq

**Comment by github4pbp** [comment]
You sould define it also as switch in items for example try creating test.items file (/etc/openhab2/items/test.items) with a following line:

Switch 86plug_test "Power socket" <switch> {channel="mihome:senso
r_plug:158d000182450a:power"}

**Comment by github4pbp** [comment]
But first this thing should be defined as child of your gateway (hub) in things file.

As example:

Bridge mihome:bridge:7811dc64xxxx "Control hub" [serialNumber="7811dc64xxxx",
 ipAddress="192.168.x.x", port=9898, key="1sit7w7srrweujfd", pollingInterval=
6000] {
Thing mihome:sensor_plug:158d000182450a "Aqara Socket Plug" @ "Kitchen" [itemId="158d000182450a"]
}

**Comment by roha999** [comment]
thanks, problem solved, forgot to link it to bridge :(

do you know can we get Power Consumed data on aqara wall switch same as on wall socket?

**Comment by github4pbp** [comment]
Think that this is not yet supported by the binding. There is only control channel(s) and e.g. ":powerConsumed" channel is unavailable.
