### ISSUE TITLE
Update persistence.html

### ISSUE THREAD

**Issue by staehler** [openhab/openhab2-addons#4514]
I don't know the handling of git, but could you please update the startup-behavior (e.g. Workaround 3) of
https://www.openhab.org/docs/configuration/persistence.html#startup-behavior
with this solution, which work quite easy:
https://community.openhab.org/t/cleaning-up-the-startup-process-renaming-rules-windows-possible/38438/1

# The solution:
If you are on stretch-based openhabian, you may use sudo systemctl edit openhab2.service, otherwise you have to use sudo nano /etc/systemd/system/openhab2.service.d/override.conf

```
[Service]
ExecStartPre=-/bin/bash -c '/usr/bin/find ${OPENHAB_CONF} -name "*.rules" -exec /usr/bin/rename.ul .rules .rules_away {} \\;'
ExecStartPre=-/bin/bash -c '/usr/bin/find ${OPENHAB_CONF} -name "*.script" -exec /usr/bin/rename.ul .script .script_away {} \\;'
ExecStartPost=/bin/sleep 240
ExecStartPost=-/bin/bash -c '/usr/bin/find ${OPENHAB_CONF} -name "*.script_away" -exec /usr/bin/rename.ul .script_away .script {} \\;'
ExecStartPost=-/bin/bash -c '/usr/bin/find ${OPENHAB_CONF} -name "*.rules_away" -exec /usr/bin/rename.ul .rules_away .rules {} \\;'
TimeoutStartSec=360

```

**Comment by wborn** [comment]
It's not really a solution but a workaround that solves some of the startup issues. There's already https://github.com/eclipse/smarthome/issues/1896 for solving the underlying issue.

**Comment by staehler** [comment]
Thanks for your hint, hope this issue will be fixed within the eclipse project.
You are right, that's not a solution, but a workaround, as the other two workarounds described in the regarding docu.
I thought it could be quite interesting for others, as this workaround is quite easy and reliably. If nobody finds this worth to mention, it is OK for me.
