### ISSUE TITLE
[deconz] Capture temperature provided by open/close sensors

### ISSUE THREAD

**Issue by stefanbraun1** [openhab/openhab2-addons#4515]
Within the config section, Xiaomi open/close sensors provide the temperature. It would be great to capture this as well. Note that this cannot be captured with the regular temperature sensors things existing already.

```
"18": {
    "config":    ###{
        "battery": 100,
        "on": true,
        "reachable": true,
        "temperature": 0
    },
    "ep": 1,
    "etag": "d4e8e099a565f6326b9a87b3615ee483",
    "manufacturername": "LUMI",
    "modelid": "lumi.sensor_magnet",
    "name": "OpenClose",
    "state": {
        "lastupdated": "2018-12-16T00:02:47",
        "open": false
    },
    "type": "ZHAOpenClose",
    "uniqueid": "00:15:8d:00:01:f3:87:a2-01-0006"
}
``` 

In addition, capturing the battery level would be the icing on the cake. Thanks. 

Related to #4400

**Comment by cweitkamp** [comment]
It should be no big deal to add a Channel for that but as we do not receive an event from the websocket for changes in the config section, I assume that the values of these channels do not change immediately - only if a call for the "initial data" will be performed. Is that sufficient?

**Comment by stefanbraun1** [comment]
I would appreciate this, since the sensors provide this information.

**Comment by cweitkamp** [comment]
See PR #4596

**Comment by Hex-3-En** [comment]
> It should be no big deal to add a Channel for that but as we do not receive an event from the websocket for changes in the config section, I assume that the values of these channels do not change immediately - only if a call for the "initial data" will be performed. Is that sufficient?

Yes and no....

This binding doesn't handle config messages on websocket, so yes.
The Websocket actually sends config changes, so no.

Actually this will be working in my rewrite, but this will take another week or two to be available for testing, as my rewrite currently evolves to an all new binding, as the current solution is really a quick and dirty, handling almost nothing and even the sensor api incorrectly...
