### ISSUE TITLE
KNX Setpoint temperatur not working with PaperUI/Habmin

### ISSUE THREAD

**Issue by compunited** [openhab/openhab2-addons#4519]
Hi
i want to change the room temperature via openhab. it was 'easy' in the former version to set it up via sitemap etc

But in the new version there is no way to set up a Setpoint or selection item via PaperUI or HABmin. If i put the Setpoint into the sitmap like that
Selection item=HZ_Betriebsart label="Wohnen Heizung Betriebsart" mappings=[1="Komfort", 2="Standby", 3="Nacht",4="Frost"]
Setpoint item=HZ_Temperature label="Basis Sollwert [%.1f °C]" minValue=4.5 maxValue=30 step=0.5

i cannot access them from the PaperUI GUI

**Comment by wborn** [comment]
Paper UI and HABmin are only used for administrative purposes. Sitemaps are used for designing your own UIs. Sitemaps can be used with Basic UI, Classic UI and the mobile Apps.
