### ISSUE TITLE
[Bug] Rule Engine - enable/disable rules

### ISSUE THREAD

**Issue by itskeKs** [openhab/openhab2-addons#4520]
The Rule Engine within Version 2.4 and 2.5 (also within beta releases of 2.5) does not properly reenable Rules.

## Expected Behavior
If a Rule is disabled and reenabled through another rule it should be active and working.

## Current Behavior
When the Rule disables another rule it first changes to "uninitialized" state then switches to disabled. When such a rule gets executed it does not execute included commands for example turn on the lights.

## Possible Solution
none btw. i had to downgrade oh to 2.3 to get it back to work as expected.

## Steps to Reproduce (for Bugs)
1. Create a rule which disables another rule, Create a rule which enables the disabled rule. Execute the disabler then the enabler.
2. Execute the disabled and then reenblaed rule. This should end up with not executing the included actions.

## Context
I have rules which disable rules for turning on lights during daytime. For example i disable rules which turn on the lights through movement detection after 8am and enable them back at 6pm.

## Your Environment
RasPi 3, OpenHab 2.3.0 (at the moment) tried with 2.4.0 and above (including betas). Installed from the repo through apt-get.

**Comment by wborn** [comment]
Please create an issue for this in the Eclipse SmartHome [issue tracker](https://github.com/eclipse/smarthome/issues). That's the repository where the code for this functionality is maintained.
