### ISSUE TITLE
[deconz] Add "dark" channel from Ikea Trådfri motion sensor

### ISSUE THREAD

**Issue by slundell** [openhab/openhab2-addons#4524]
The IKEA Trådfri motion sensor provides a "dark" boolean attribute at config.dark. It would be nice to have that as a channel. Also battery level would be a nice to have. See below JSON from my motion sensor

`{
"config":{
"alert": "none",
"battery": 60,
"delay": 60,
"duration": 60,
"group": "53372",
"on": true,
"reachable": true
},
"ep": 1,
"etag": "986612993cac4328153ab129c9ce2212",
"manufacturername": "IKEA of Sweden",
"modelid": "TRADFRI motion sensor",
"name": "TRADFRI motion sensor ",
"state":{
"dark": true,
"lastupdated": "2019-01-05T20:38:59",
"presence": false
},
"swversion": "1.2.214",
"type": "ZHAPresence",
"uniqueid": "d0:cf:5e:ff:fe:12:4c:0e-01-0006"
}`

**Comment by cweitkamp** [comment]
Do you know how the `dark` boolean property behaves? Is the value forwarded from the sensor itself? Or is it a calculate feature? If so, how is it implemented (thresholds, algorithm, etc.)? There is not very much information about it in the [deCONZ REST API documentation](http://dresden-elektronik.github.io/deconz-rest-doc/).

**Comment by slundell** [comment]
I am still to figure out how this attribute works, and it's relation to the light/dark dial on the back of the sensor. Even the IKEA manual (both English and Swedish version) is a bit unclear about it!

ebaauw provides some insight here: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/398#issuecomment-363575384

**Comment by cweitkamp** [comment]
Thanks for the link. Sounds not like a very useful information. Is it? Adding a Channel for it is not a big deal but I am not sure if there is a real use-case for it - if we consider that the value only changes when the sensors measurement changes.

**Comment by cweitkamp** [comment]
I added more light sensor channels (e.g. lightlevel, dark and daylight) and I added a check for the optional channel dark for presence sensors in PR #4545.
