### ISSUE TITLE
[deconz] Handling websocket timeouts and future features

### ISSUE THREAD

**Issue by cweitkamp** [openhab/openhab2-addons#4525]
Continuation of the discussion from https://github.com/openhab/openhab2-addons/pull/4513/files#r245442404

> This exactly 5 minutes happen due to a timeout every 5 minutes on the websocket connection to the deconz rest api and is not related to pulling.
As I didn't find where the exact time for the timeout is comming from I'd have to use magic numbers for fixing this for now.

> We should watch the deconz web UI. They probably send a keep-alive to the websocket connection every now and then.

> ## 5-Minute timeout on websocket
> I still didn't find where this is set, but may be a default in the Qt-Sockets, so for the current state this is the best fix I can provide quickly.
>
> ## Why web app gets no timeout
> Actually the web app has scheduled polling of all states (groups, lights, config, sensors) on an average of every 15 seconds. Which seems to force deconz to keep the clients websocket running.
> Also the api-decription here mentions the expectation of polls. I guess they expect people use their API completely and not only the sensors part.
>
> ## So whats next?
> On the path to next stable release, I think a rewrite including polls and also event triggers for all sensors should be done. I would start with it right away and make a new PR replacing this one then, as it should become obsolete.
> Oh and I experienced this #4518 over and over again, too, would take a look at it too smile
>
> As the polling actually needs the basic rest implementation already, I'd suggest implementing the lights in a second step, too, so people without a hue bridge at home can drive their conbee/raspbee setup with only the deconz-binding, which is expected behaviour in my eyes.
> 
> **what do you think?**

// CC @Hex-3-en @davidgraeff

**Comment by cweitkamp** [comment]
> I think a rewrite including polls and also event triggers for all sensors should be done.

What kind of polling do you like to introduce? Like a recurring "ping"? Or polling the API endpoints for lights/sensors? The idea behind the deCONZ binding was to omit using polling because they support a websocket connection to handle events immediately.

What about reusing the Thing discovery for instance? How does it work? Don't we use a polling strategy for it?

> I'd suggest implementing the lights in a second step, too

I second that. On the one hand it ist a very nice feature and on the other hand because of personal interest - I am interested in using some ZigBee Light Link relays which combine a Switch/Dimmer and a scene remote control in one device. Furthermore the Hue Bridge / API has some issue with handling third party devices (e.g. OSRAM devices always shown as offline or the TRADFRI colored bulb has wrong ZLL specification which does not allow to control the color temperature).

**Comment by Hex-3-En** [comment]
> What kind of polling do you like to introduce? Like a recurring "ping"? Or polling the API endpoints for lights/sensors? The idea behind the deCONZ binding was to omit using polling because they support a websocket connection to handle events immediately.

Actually the websocket only pushes sensor/switch events and no light-events. Because of this implementing the lights you need to send a state request every now and then at least for the lights as they could be changed e.g. by the phoscon app. Luckily the API provide hash-values indicating the known state you can put in your request, so the API answers just a statuscode on "no-change", which keeps traffic and work pretty low.
I'd recommend copying the phoscon behaviour of requesting the state every 15 seconds.
For the sensors, polling is absolutely obsolete of course, as the websocket should give updates immediately.
I'd also recommend letting people choose to use deconz only or with hue binding with a "standalone"-boolean in the config.
This can also result in polling sensors, if false and lights in case of true.

> What about reusing the Thing discovery for instance? How does it work? Don't we use a polling strategy for it?

To be honest currently auto discovery is completely broken in the binding and I will start digging into that while the rewrite, as I guess it could solve itself while cleaning up communication 😄 
If it works it should be detection via Upnp-broadcast or the Dresden-Elektronik web-discovery-service as a fallback(not yet implemented, but I will). So no polling needed here.

> I second that. On the one hand it ist a very nice feature and on the other hand because of personal interest - I am interested in using some ZigBee Light Link relays which combine a Switch/Dimmer and a scene remote control in one device. Furthermore the Hue Bridge / API has some issue with handling third party devices (e.g. OSRAM devices always shown as offline or the TRADFRI colored bulb has wrong ZLL specification which does not allow to control the color temperature).

Yeh, Hue-Binding seems to have growing amount of issues in the most recent time, and lacks a lot of zigbee-support, which is why I waited for this binding and in a lack of patience am now throwing in my freetime to get things done 😛

**Comment by Hex-3-En** [comment]
Nevermind... the websocket actually pushes light- and group-events too 🙄 
So polling would be somehow redundant, but seems it needs to be done in a certain intervall to prevent the gateway from killing the websocket...

**Comment by davidgraeff** [comment]
This binding was really just for building up on the websocket connection. If lights are to be integrated this binding will make the hue binding superfluous (because it supports lights, sensors and on top a real time update strategy).

I'm not sure if work should be replicated. 
But the hue binding is in bad condition in parts of the code and would need fresh code for websocket support to be integrated.

**Comment by cweitkamp** [comment]
> Just point the hue binding to your Deconz instance.

That is a very good reason for not implementing support for the light API but rather invest the time to improve the Hue binding.

**Comment by davidgraeff** [comment]
@cweitkamp My priorities moved. If time permits, can you please fix the non-port-80 bug and https support in the hue binding? There are more problems that I found in my PR, but I doubt that I can really rebase that. Some fixes are urgent though.

**Comment by cweitkamp** [comment]
@davidgraeff Yes, of course. I will put it onto my TO-DO list. Let`s see what I can reuse from your PR.

**Comment by davidgraeff** [comment]
I think the tests are useful. Otherwise it is really just what I have mentioned + how the keep-alive is implemented at the moment (It tries to connect with a presumably not existing user -> I replaced that with checking for /api/config which is existing and accessible for non authorised users)

**Comment by Hex-3-En** [comment]
> I am interested in using some ZigBee Light Link relays which combine a Switch/Dimmer and a scene remote control in one device.

@cweitkamp can you tell what device you want to use and how you would like to see the functionality implemented?
As far as I understand the deCONZ Code base, one can set the mode of e.g. Dresden Elektroniks multimode switches and they will change button-codes sent over rest-api/websocket. Don't know if this is the case for e.g. Busch-Jaeger too 🤔 
If I got this right, it could be a use case for the new profiling feature or maybe channel-groups beeing replaced dynamically on mode change I guess?

**Comment by Hex-3-En** [comment]
Uh, just realized there are zigbee devices with multiple clusters, that are published on deconz as multiple devices... That will make removing them from network a little more complicated... I guess the Busch Jaeger is one zigbee device with two function clusters right (will try to find specs later if you don't now for sure 😉 )?

Do you actually think it's a good idea to tell deconz to remove devices from network when removing the thing in openhab? I like the idea of consistency through platforms and beeing able to add and remove devices with openhab only and no need to use phoscon(old or new) at all.

**Comment by davidgraeff** [comment]
> deconz to remove devices from network when removing the thing in openhab?

That would be surprising to the average user, because openHAB never does this in other bindings.
As soon as we gain "Thing Actions" we could provide an action "Remove from deCONZ".

Regarding the initial problem: Did anybody had websocket timeout problems recently or is this fixed?

**Comment by cweitkamp** [comment]
> Did anybody had websocket timeout problems recently or is this fixed?

No, I do not face timeouts. For me it is working smoothly. I am only struggeling with #4518.

**Comment by davidgraeff** [comment]
Please reopen if this is still a problem. Thanks.

**Comment by se3** [comment]
` this.client.setMaxIdleTimeout(0)` worked for me to get rid of reconnect websockets and deconz bridge errors and warnings.
![image](https://user-images.githubusercontent.com/189112/64865143-f77a2280-d638-11e9-987c-ab623e2bbc83.png)
@cweitkamp, @davidgraeff Please feel free to reopen ticket and fix this annoying issue.
thanks all for supporting this project

**Comment by davidgraeff** [comment]
Thanks. An easy fix.

**Comment by cweitkamp** [comment]
I added the `setMaxIdleTimeout(0)` to my current PR #6118.
