### ISSUE TITLE
[deconz] Tradfri Remote triggers not triggered

### ISSUE THREAD

**Issue by slundell** [openhab/openhab2-addons#4533]
Using 2.5.0-SNAPSHOT

Using the Trådfri Remote works "fine". (I experience the known button-event-on-websocket-reconnect issue, but I filtered out spurious clicks by checking the event id from phoscon api).

This issue is that when Openhab is restarted, the button trigger is not triggered. If I disable then enable the button thing, it starts to work again. I guess this might be due to some unordered initialization on start.

The trigger line is:     `Item Sovrumsknapp_Button received update`

The item and thing is added through PaperUI

**Comment by Hex-3-En** [comment]
Are you using the Rule-Engine in PaperUI and a rule not triggering after restart?

**Comment by cweitkamp** [comment]
@slundell Might I ask you to comment on @Hex-3-En  question? I am using three TRADFRI remotes in my environment without any issues.

**Comment by slundell** [comment]
This is working now. It was fixed a few commits after I reported. Sorry for not getting back to you.
