### ISSUE TITLE
[network] Discovery does not work anymore with OH 2.4

### ISSUE THREAD

**Issue by Tost69** [openhab/openhab2-addons#4559]
## Expected Behavior
Scan for new Things for The Network binding should discover Network Things (as it worked before  OH 2.4)

## Current Behavior
Scan for new Things for the Network binding discovers nothing. Network discovery is not working. Adding Network Things manually is working correctly.

**Comment by zupy666** [comment]
I'm having the same issue. openHAB 2.4
