### ISSUE TITLE
[deconz] Provide support for water leakage sensors

### ISSUE THREAD

**Issue by stefanbraun1** [openhab/openhab2-addons#4588]
It would be super also to support this one for water leakage detection. DECONZ provides this already. Thanks. 

`{"config":"battery":100,"on":true,"reachable":true,"temperature":3000},"ep":1,"etag":"xxx","manufacturername":"LUMI","modelid":"lumi.sensor_wleak.aq1","name":"Water",
"state":{"lastupdated":"2019-01-13T18:38:36","lowbattery":false,"tampered":false,"water":false},"type":"ZHAWater","uniqueid":"xxxx"}`

**Comment by cweitkamp** [comment]
See PR #4596
