### ISSUE TITLE
[enocean] Add metadata channels

### ISSUE THREAD

**Issue by dominikkv** [openhab/openhab2-addons#4591]
I think of splitting the channel "receivingState" into its parts RSSI & repeater count to log these values in database, to see anomalies. I think the best would be to remove "receivingState", because one can build this string on his own. Furthermore, I'd like to add a channel for the time when the last telegram was received.

See https://github.com/fruggy83/openocean/issues/37

**Comment by dominikkv** [comment]
Hi @wborn, thanks for assigning me. Does that mean I have to take any action? Right now, I don't know what I can do for #4765. Please let me know if there is anything to do for me.

**Comment by wborn** [comment]
By assigning issues it's immediately clear to everyone who works on an issue.
