### ISSUE TITLE
[max] Improve texts

### ISSUE THREAD

**Issue by cubistico** [openhab/openhab2-addons#4605]
## Expected Behavior
Texts should not be ambiguous. :-)

## Current Behavior
Some texts are ambiguous or not easy to understand.

See discussion in https://community.openhab.org/t/solved-max-what-is-thermostat-window-open-duration/61343 plus a few more minor text problems.

## Possible Solution
Improve texts

## Steps to Reproduce (for Bugs)
View advanced settings of the binding

## Context
It's confusing the user. At least, it confused me. 

## Your Environment
openHAB 2.4.0

**Comment by cubistico** [comment]
I would assign this issue to myself, but obviously I can't do that.

**Comment by wborn** [comment]
You have been assigned. :-)
