### ISSUE TITLE
[Homematic] HmIP Door Window Contact paired as String, not as Contact - not yet corrected for HmIP-SWDM-B2

### ISSUE THREAD

**Issue by c--r** [openhab/openhab2-addons#4614]
As a follow-up to these already closed issues:
https://github.com/openhab/openhab2-addons/issues/2817
https://github.com/openhab/openhab2-addons/issues/1564

The Door Window Contact HmIP-SWDM-B2 (sold by Lidl/Silvercrest) only works when using item type "String" in openhab 2.4.0. Can you please also add the virtual datapoint "STATE_CONTACT" with item type "Contact"?

**Comment by wborn** [comment]
Please create an issue for this in the Eclipse SmartHome [issue tracker](https://github.com/eclipse/smarthome/issues). That's the repository where the code for this addon is maintained.

**Comment by towo** [comment]
As per eclipse/smarthome#6905, this fix should be applied here, as far as I can tell. Please reopen.

**Comment by ev0lister** [comment]
Same issue for me. It only works by using StringItem not Contact. Please reopen.

**Comment by MHerbst** [comment]
@towo @ev0lister It is probably easier to create a new issue. Please add the name of the affected devices. Is it only the one names HmIP-SWDM-B2 or are there other devices, too?
