### ISSUE TITLE
[deconz] Add support for Innr Power Socket SP120

### ISSUE THREAD

**Issue by SuperSchelli** [openhab/openhab2-addons#4627]
Some Values of the Innr SP120 power socket are not evaluated

## Expected Behavior
* Add Channels for Voltage and Current (in ZHAPower)

## Current Behavior
* ZHAConsuption part works perfectly
* ZHAPower part only evaluates Power at the moment

## Context
* Just a nice to have as soon as time is available

## Deconz Rest API output
''''
"26": {
    "config": {
      "on": true,
      "reachable": true
    },
    "ep": 1,
    "etag": "e17cc691e4b5cb21fec02524b81225e7",
    "manufacturername": "innr",
    "modelid": "SP 120",
    "name": "Consumption 26",
    "state": {
      "consumption": 200,
      "lastupdated": "2019-01-19T11:39:27"
    },
    "swversion": "2.0",
    "type": "ZHAConsumption",
    "uniqueid": "00:15:8d:00:03:2a:fc:ea-01-0702"
  },
  "27": {
    "config": {
      "on": true,
      "reachable": true
    },
    "ep": 1,
    "etag": "bccef30cd3c3bd333898612922904992",
    "manufacturername": "innr",
    "modelid": "SP 120",
    "name": "Power 27",
    "state": {
      "current": 0,
      "lastupdated": "2019-01-19T11:40:38",
      "power": 0,
      "voltage": 230
    },
    "swversion": "2.0",
    "type": "ZHAPower",
    "uniqueid": "00:15:8d:00:03:2a:fc:ea-01-0b04"
  },
''''
Output of an Innr Power Socket SP120

## Your Environment
* OH Addons 2.5.0 snapshot, updated at 19.01.2019
* Raspberry Pi Model 3B+
* Openhabian installed

**Comment by cweitkamp** [comment]
Which snapshot version we are talking about? IIRC build 1502 was the latest (16.01.2019 03:33:07). PR #4596 was about adding support for the requested channels but it has been merged later.

**Comment by SuperSchelli** [comment]
couldnt really check it completely since i updated to Snapshot S1503-1 and i can't load all bindings atm ...

2019-01-22 12:19:51.361 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-hue, openhab-ui-basic, openhab-transformation-map, openhab-binding-ntp, openhab-binding-openweathermap, openhab-binding-astro, openhab-ui-paper'

but deconz is loaded and the Innr Power Item, still only has the Power Channel and the Last Updated Channel... I cleaned the cache and restarted ...

**Comment by SuperSchelli** [comment]
ok, after updating today, the voltage and current are showing, perfect, thx a lot for adding this.

**Comment by cweitkamp** [comment]
Sounds good. Thanks for testing.
