### ISSUE TITLE
[rfxcom] Issues with thermostat3 commands

### ISSUE THREAD

**Issue by martinvw** [openhab/openhab2-addons#4633]
The commands for rfxcom:thermostat3 are defined as a switch but are suppossed to send and receive up/down commands, somehow this worked on older versions of openHAB but that loophole seems to have been closed.

The original support for  the message was added in:

https://github.com/openhab/openhab2-addons/pull/2981

I remember being suprised by it working back then but we merged it like this anyway.

**Comment by martinvw** [comment]
@openhab/2-x-add-ons-maintainers what would be the best modelling here.

At the external world side of things I have a single command having up to six different channels:

Off / On (could be a seperate channel)
Up / Down (Up and down would be available in the shutter bit it feels mismodelled)
Off / On (second) (could be a seperate channel)
Run Up / Run Down (feels like up/down)
Stop (player item?)

I could maybe just make it a String with those values but that also does not feel to pure.

Suggestions are welcome!

**Comment by paulianttila** [comment]
E.g. Lighting2 message have already command (Switch), contact (Contact) and dimminglevel (Dimmer) channels to handle different item types.

**Comment by martinvw** [comment]
> E.g. Lighting2 message have already command (Switch), contact (Contact) and dimminglevel (Dimmer) channels to handle different item/channel types.

Indeed but then I still need to map the up-down to something, or should I even map it two two different channels.But how should the interaction work between all those different channels?

**Comment by paulianttila** [comment]
> Indeed but then I still need to map the up-down to something

Do you mean up-down command from thermostat to OH. Maybe trigger channels should be introduced to rfxcom binding.

**Comment by cweitkamp** [comment]
From my point of view a state channel of item type String with a fixed options list fits best. Additionally handling of `OnOffType` could be feasible. Of course you can use several channels or items for it but that sounds confusing too.

A trigger channel will be nice too.

**Comment by martinvw** [comment]
Do triggers work one way from a binding to a rule, or could I also have a trigger channel that works the other way around? My first feeling would be that its like a normal channel without state?

``` 
HeaterUp.trigger()
```

**Comment by ahr85** [comment]
Any updates on this topic so far? Using the Switch-Command allows me to turn my fire place on and off, but I cannot change the flame-heigt or change the second flame.
Reference to my community-entry: https://community.openhab.org/t/using-rfxcom-command-with-multiple-values-but-binding-expects-switch/73573

**Comment by martinvw** [comment]
> Any updates on this topic so far? Using the Switch-Command allows me to turn my fire place on and off, but I cannot change the flame-heigt or change the second flame.
> Reference to my community-entry: https://community.openhab.org/t/using-rfxcom-command-with-multiple-values-but-binding-expects-switch/73573

Yes, I just created a pull-request, please test and report back!
