### ISSUE TITLE
[openweathermap] Capitalize first letter of strings

### ISSUE THREAD

**Issue by BasvanH** [openhab/openhab2-addons#4650]
The capitalization of the first letters of strings is not consistent. In some itmes it is captilized, and in some not. Please make it consistent and always capitalize the first character of a string.

Expected Behavior
Condition

Current Behavior
condition

Possible Solution
Change code to always capatilize the first character of a string.

Your Environment
openHAB 2.5.0 Build 1493

**Comment by BasvanH** [comment]
When I save my items file, suddenly the all lowercase strings do get the first character capatilized. But after a while, they fall back to all lowercase. Realy strange.

**Comment by BasvanH** [comment]
After a while, you see the inproper capatilization:
![image](https://user-images.githubusercontent.com/1708136/51526815-749b2200-1e33-11e9-9489-8dddf07d538a.png)

**Comment by 9037568** [comment]
Aren't these just strings in your configuration?
They don't occur in the OWM binding.

Please show your item definitions and HabPanel configuration.

**Comment by cweitkamp** [comment]
@BasvanH Might I ask you to comment on @9037568 question? As you can see in the XML file containing the channel type configuration (see [channel-types.xml](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.openweathermap/ESH-INF/thing/channel-types.xml#L105)) all labels are written in camel case letters. Currently I expect this not to be a problem inside the binding.

**Comment by BasvanH** [comment]
@cweitkamp , from my screenshot the white text is my own input, the name given on Dummy widget. The blue text is output from the channels, not the labels. String output from the channels is not formatted. If the binding is just forwarding the OWM API's values, apparently they aren't very consistent in casing.

**Comment by cweitkamp** [comment]
> String output from the channels is not formatted. If the binding is just forwarding the OWM API's values, apparently they aren't very consistent in casing.

Yes, the binding just forwards data received from OWM API. It does neither applies a formatter nor a translation on values. To be honest we will not fix that. If you like to have optimized casing I have to ask you to look for a solution elsewhere (e.g. by creating a rule).

**Comment by Flole998** [comment]
You don't even need a rule for this, transformation would be enough. That's how I am going to solve this.
