### ISSUE TITLE
[yeelight] Add effect and duration support

### ISSUE THREAD

**Issue by goodfore** [openhab/openhab2-addons#4656]
I think the Yeelight supports effect and duration (at least some models do). I poked around the binding code a bit, it seems currently it's hard coded to "Smooth" and 0.5 Sec in the lib.

Maybe we can add support for these?

@claell Do you think adding the two settings as optional Thing config, and pass it down to device then to lib would work?

I probability will give it a try, but I have no experience in binding dev so it will take some time.

Thanks,
Joe

**Comment by claell** [comment]
I am not sure what these settings do. I guess duration is the time it takes to change from one applied "setting" to another? This is probably a good one to implement as optional thing config which gets passed on, at least I don't know a better way to do this.

For effect, I don't know what you mean by it. Like sunrise, circling through colours etc.?

**Comment by goodfore** [comment]
I only have V1 white bulb, and from using the python library, there are only 2 "effects", smooth and sudden.

For sudden, bulb should transition to new brightness (maybe color too, not sure) almost instantly. It ignores the duration value.

For smooth, it will transition to the brightness in the amount of time given in duration, in milliseconds.

**Comment by goodfore** [comment]
I will need to test out with "Smooth" and 0 duration = Sudden. If that case is correct, then we can just have one configuration item for Thing, namely Duration?

I see that the lib already implemented the two parameters, in DeviceBase.java, methods such as this have them hardcoded in:

`    public void open() {
        mConnection.invoke(new DeviceMethod(MethodAction.SWITCH, new Object[] { "on", "smooth", 500 }));
}`

So my plan is to update the Thing XML, grab the value in Handler base and pass it to DeviceBase, does that sound like a good plan?

Thanks,
Joe

**Comment by goodfore** [comment]
I confirmed that Smooth and 0 duration has the same effect as sudden. So I will try with just one configuration option.

I started implementing some code on my local repo last night, hopefully have something soon.

Thanks,
Joe

**Comment by goodfore** [comment]
I got it working for my setup. I can only test the white bulb with on/off and brightness. They are all working as expected now.

@claell can you please guide me thru the openhab binding testing process? I want to fully test it before commit and PR.

Thanks,
Joe

**Comment by claell** [comment]
> So my plan is to update the Thing XML, grab the value in Handler base and pass it to DeviceBase, does that sound like a good plan?

I can currently not help you with that since I am not that much into how this is done anymore. But you can look at how other (bigger / official) bindings do it or maybe there is a documentation for that.

> I got it working for my setup. I can only test the white bulb with on/off and brightness. They are all working as expected now.

Nice, that was fast 😃

> can you please guide me thru the openhab binding testing process? I want to fully test it before commit and PR.

I don't know whether there is an official way how to do this. You can look at their contribution guidelines, maybe they say something about it there.
