### ISSUE TITLE
[mqtt] Save .things file and mqtt messages are ignored until OH restart

### ISSUE THREAD

**Issue by macdroid53** [openhab/openhab2-addons#4731]
## Expected Behavior
After saving .things file previously defined mqtt messages trigger appropriate rules and modifications take effect.

## Current Behavior
1. mqtt messages trigger rules as desried
2. modify .things file containing working mqtt bridge, thing topics, and channels
3. save .things file
4. mqtt messages no longer trigger rules.
5. restart OH and mqtt rules trigger correctly.

## Steps to Reproduce (for Bugs)
1. modify existing .things file with Bridge and various topics/channels
2. save file
3. Now inbound mqtt messages are ignored until OH is restarted

## Your Environment
openHAB 2.5.0~S1507-1 (Build #1507)
Raspberry Pi
OH forum thread: https://community.openhab.org/t/mqtt-2-x-binding-can-send-cant-receive/65393?u=drmacro

**Comment by davidgraeff** [comment]
I have one question: Are the mqtt messages send as retained, qos=1? Otherwise not restoring the mqtt messages is the correct behavior actually.

**Comment by davidgraeff** [comment]
Probably fixed since OH 2.5M1
