### ISSUE TITLE
[Tradfri] [Californium] Update to 1.0.7?

### ISSUE THREAD

**Issue by hreichert** [openhab/openhab2-addons#4733]
Recently californium 1.0.7 was released that contains a bugfix needed for Tradfri (https://github.com/eclipse/smarthome/issues/6065)

I can't find a way to integrate this new version in the OpenHAB build.
Maybe this has to be done by a OpenHAB maintainer; or please tell me what's the correct procedure.

**Comment by cweitkamp** [comment]
Currently the californium version is defined in the [feature.xml](
https://github.com/eclipse/smarthome/blob/e25f1bd548126ef44fbdc90dd1dd0f85e83bdef0/features/karaf/esh-tp/src/main/feature/feature.xml#L42) of ESH. The feature itself is exposed as `esh-io-transport-coap` in [esh-core features](https://github.com/eclipse/smarthome/blob/e25f1bd548126ef44fbdc90dd1dd0f85e83bdef0/features/karaf/esh-core/src/main/feature/feature.xml#L310) and additionally referenced as `openhab-transport-coap` in [openhab-core features](https://github.com/openhab/openhab-core/blob/master/features/openhab-core/src/main/feature/feature.xml#L77).

After https://github.com/openhab/openhab-core/pull/467 will have been merged we will have to change the version in the [feature.xml](https://github.com/openhab/openhab-core/blob/5b781728c87701ef7988b9f58e52c6a421f051df/features/karaf/openhab-tp/src/main/feature/feature.xml) of the new openHAB2 core.

I guess we have to wait for https://github.com/openhab/openhab-core/pull/467, but I expect it to be merged soon.

**Comment by cweitkamp** [comment]
I created a PR https://github.com/openhab/openhab-core/pull/475.
