### ISSUE TITLE
[network] Add a support for Windows arp tool arp-ping.exe

### ISSUE THREAD

**Issue by kpanchen** [openhab/openhab2-addons#4751]
## Current Behavior
Currently only supported tool for Windows is Thomas Habets arping, which is not supported by author for Windows, not complied by him and requires additional libraries.

Similar existing tool is arp-ping.exe by Eli Fulkerson:
https://www.elifulkerson.com/projects/arp-ping.php
which has very similar functionality and command line parameters.

## Possible Solution
Add to detection sub-rooting:

if (result.contains("Usage: arp-ping.exe")) {
            return ArpPingUtilEnum.ELI_FULKERSON_ARP_PING_FOR_WINDOWS;
}

Add to invoke sub-rooting:

if (arpingTool == ArpPingUtilEnum.ELI_FULKERSON_ARP_PING_FOR_WINDOWS) {
            proc = new ProcessBuilder(arpUtilPath, "-n", String.valueOf(numberOfAttempts), "-w", String.valueOf(timeoutInMS), "-x", ipV4address).start();

Add to enum definition:

ELI_FULKERSON_ARP_PING_FOR_WINDOWS("Eli Fulkerson ARPing tool for Windows");

## Context
Arp ping presence detection method doesn't work on Open Hab running on Windows systems.

## Your Environment
OpenHab 2.4 / any MS Windows systems.

Community discussion:
https://community.openhab.org/t/network-presence-binding-update/65461

**Comment by davidgraeff** [comment]
I know you have a fork of the network binding going. But could you just edit the necessary files for example here in the online editor on github and carefully adding the tool? That would be great. Travis-CI will make sure that your change still compiles and I'll merge ASAP.

**Comment by kpanchen** [comment]
I could add necessary code, the problem is that original code use threads for each interface, not sure why this is required, all the tools I've tested can detect interface automatically perfectly fine, this is just producing additional load in my opinion. Unfortunately Eli's tool does not support Interfaces and all the threads would basically do the same thing. In my testing on Windows machine I have 31 interface and 31 threads invoked, this will just flood the network. I think this has to be adjusted.

P.s. Also RegExp for Thomas Habert tool is still wrong, it is still not detecting tool with timeout.

**Comment by davidgraeff** [comment]
A PR is welcome at any time, but the open Issue will not solve it.
