### ISSUE TITLE
[HueEmulation] Feature Request: Control of color temperature

### ISSUE THREAD

**Issue by Alestrix** [openhab/openhab2-addons#4784]
## Current Behavior
According to the documentation of Alexa and Philips Hue it is possible to control Hue lamps' color temperature with Alexa.
This feature is not available when using Openhab hue emulation (brightness, color, on/off working well though).

## Context
I have various MiLights in my setup and they can be controlled well via the paper UI, including temperature of the white setting.
Via Alexa it is also possible to change color to "white" but this is a very cold while. Changing color to warm white (no change) or making light warmer ("not supported by that device") is not possible.

**Comment by davidgraeff** [comment]
The hue emulation also exposes color temperature. But there are several reasons why this feature request can not be implemented unfortunately:

* Echos support for local Hue bridges vary by firmware version and country. For most people in the US not even the color control works. My guess is that color temperature control will not work for local bridges, only for cloud connections.
* The color item type (remember we are exposing items, not Channels / Things) does not support a color temperature and openHAB has no means to connect items semantically together (color<->on/off<->temperature etc).

A workaround for now is a second item that is linked to the temperature channel of your light and that is exposed via the "Lighting" tag.
