### ISSUE TITLE
[chromecast] Add feature to stop playback

### ISSUE THREAD

**Issue by zbot473** [openhab/openhab2-addons#4794]
It currently isn't possible to disconnect a Chromecast Stream, although the API supports it. I think a switch should be sufficient to accomplish this. For example, we send ON to the switch, then we call the stop method, and then we turn off the switch.

**Comment by zbot473** [comment]
Thanks to @cweitkamp, we have a testing version.
https://github.com/cweitkamp/openhab2-addons/tree/feature-4794-chromecast-stop

**Comment by cweitkamp** [comment]
PR #4860
