### ISSUE TITLE
[mqtt embedded] Update documentation from blog post "MQTT Arrives in the Modern openHAB 2.x Architecture"

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhab2-addons#4797]
The documentation at [docs.openhab.org](https://www.openhab.org/addons/integrations/mqttembeddedbroker/#embedded-mqtt-broker) for the MQTT Embedded software component is lacking a lot of relevant information. The blog post written prior to the release (found [here](https://www.openhab.org/blog/2018-12-16-mqtt-arrives-in-the-modern-openhab-2-x-architecture.html)) contains some of the missing information in my opinion. 

Merging some part of the blogpost into the documentation would be good. 
I miss the following information:
* Example on textual configuration
* Short explanation how `mqtt binding`, `mqtt embedded broker` and `mqtt broker "external"` differ from each other.
* Known limitation vs external mqtt brokers

**Comment by simoneluconi** [comment]
Agree, i'm trying to moving from mqtt binding 1.x to 2.x but i can't figure out how it works, the docs lacks a lot of information.

**Comment by davidgraeff** [comment]
An Issue here is not going to fix this guys ^^ If anybody of you could just add the required information and make a PR, I'll merge that ASAP. Thanks.

**Comment by davidgraeff** [comment]
Fixed in master
