### ISSUE TITLE
[sony] Checkstyle Invalid Token

### ISSUE THREAD

**Issue by tmrobert8** [openhab/openhab2-addons#4816]
I'm updating the sony addon and ran into an issue with checkstyle.  If you have the following method definition:
```
protected ScalarWebChannel createChannel(String name, String @Nullable... addtlPaths) {
//code here
}
```
Checkstyle will start giving you a bunch of unexpected token messages (on various lines of code) and will eventually fail with "expecting EOF but found ..." (where ... is whatever code it eventually landed on).

The issue is the "@Nullable..." - removing the @Nullable from it fixes checkstyle.  Apparently didn't expect a token combination like that..

EDIT: appears to be in this thread: https://github.com/checkstyle/checkstyle/issues/3238

**Comment by davidgraeff** [comment]
Hm. I think the repository is wrong to report this. 

You would rather report this in https://github.com/openhab/static-code-analysis.

But we do not have any influence on the checkstyle implementation and need to wait for those guys to fix it. Closing this now.

Thanks for the report though.
