### ISSUE TITLE
[mqtt.generic] transformationPatternOut does not work

### ISSUE THREAD

**Issue by sirea07** [openhab/openhab2-addons#4829]
## Expected Behavior
The [documentation](https://www.openhab.org/addons/bindings/mqtt.generic/#common-channel-configuration-parameters) mentions the configuration parameter 'transformationPatternOut', which should behave in a similar way for outgoing messages as the parameter 'transformationPattern' for incoming messages. While 'transformationPattern' works perfectly fine, 'transformationPatternOut' doesn't seem to work at all. The only option to modify the value for outgoing messages seems to be 'formatBeforePublish', however this is not suitable for my needs as I have to calculate a completely new value from the input. 

## Current Behavior
Doesn't seem to have any effect at all. I have tried all kinds of configuration variations, but nothing worked, so I guess this feature is not implemented at all (yet?).

## Possible Solution
If this feature is planned for a next release, remove it from the current documentation or at least add a corresponding note.

## Steps to Reproduce (for Bugs)
1. Create the file *things/mqtt.things* with following content:
```
Bridge mqtt:broker:zigbee2mqttBroker [ host="mosquitto", secure=true, clientID="openhab", username="foo", password="bar" ]
{
    Thing topic light1 {
        Type dimmer : lamp_brightness "Stehlampe" [ stateTopic="zigbee2mqtt/lightbulb-1", transformationPattern="JS:getZigbeeBrightness.js", transformationPatternOut="JS:setZigbeeBrightness.js", commandTopic="zigbee2mqtt/lightbulb-1/set", on="ON", off="OFF" ]
    }
}
```
2. Change the value
3. Check the message content (e.g. by subscribing to the same topic from another client) -> It will be exactly the same as the changed value, thus the transformation (setZigbeeBrightness.js) is not applied at all

## Context
If no one is currently working on this feature I might be able to implement it. I just would like to avoid any duplicated work... :)

## Your Environment

* Version used: openhab 2.4
* Operating System and version: Docker - openhab/openhab:2.4.0-amd64-alpine

**Comment by JueBag** [comment]
The documentation displayed is by default the the latest, which is the development version, and not the actual stable version. You can select the documentation version in the top left corner of the page.
The feature you read about belongs to the version 2.5, you need to update to the snapshot version to get it.

**Comment by sirea07** [comment]
Oh thx, i hadn't spotted the versioning in the documentation. I'll try my luck with the snapshot then. 

I have just tried to setup the IDE using the Eclipse Installer and almost all packages unless mqtt were be built successfully. The mqtt package however is not able to resolve the annotations `@ActionInput` and `@RuleAction` in the package *org.openhab.core.automation.annotation*. Do you have any idea what might be the problem?

**Comment by JueBag** [comment]
Nope,  Sorry.

**Comment by sirea07** [comment]
Ok thx anyway!
