### ISSUE TITLE
[knx] DPT 232.600 sends percentage values instead of byte values

### ISSUE THREAD

**Issue by neoterianer** [openhab/openhab2-addons#4844]
## Expected Behavior
The DPT 232.600 is defined as byte values (0..255), one for each color. Pure red should be transmitted e.g. as "r:255 g:0 b:0" to the KNX Bus.

## Current Behavior
OpenHAB sends percentage values (0..100). Pure red is transmitted as "r:100 g:0 b:0" to the KNX Bus.
 
## Possible Solution
The KNX Binding uses the getRed() etc. functions of the HSBType, which returns a percentage. (See line 610 in KNXCoreTypeMapper.java) These values should be converted to a byte value.

## Steps to Reproduce (for Bugs)
1. Create KNX Channel from Type color and hsb=232.600:<groupAddress>
2. Create a color-item and link with channel
3. Select color in color-item and watch at the group monitor in ETS

## Context
I'am using a MDT LED Controller and want to set the color of a LED RGB stripe with only a single group address. The solution with 3 single addresses, each for each color and rules to set the values worked for me too. But I think this is only an awkward workaround. 

## Your Environment

* Version used: 2.5.0 (openHAB and knx-addon)

**Comment by lewie** [comment]
@neoterianer, 
please can you test these file:
https://github.com/lewie/openhab2/raw/DPT_232.600_sends_percentage_instead_of_byte_TESTFILE/addons/binding/org.openhab.binding.knx/org.openhab.binding.knx-2.5.0-SNAPSHOT.jar

**Comment by neoterianer** [comment]
@lewie ,
thx, it works perfect now. :)

**Comment by lewie** [comment]
#4864 is merged.

**Comment by petrklus** [comment]
Hi, not sure if this is the best place to comment - how about RGBW -> 251.600?

**Comment by petrklus** [comment]
Hi, not sure if this is the best place to comment - how about RGBW -> 251.600?

@lewie , any idea how to best implement?

**Comment by lewie** [comment]
@petrklus, we use calimero to communicate with KNX, and current used version has not implemented 251.600 and some other new DTP Types. In addition, KNX.org has not yet officially released this new DTPs.
I have an MDT AKD-024R.02 actuator in front of me, but I don't have the time to go forward yet. We are currently testing, but it may still take some time:
 https://github.com/calimero-project/calimero-core/issues/75

Meanwhile you have to configure the actuator differently and transfer the 3 color and one white value individually.

**Comment by petrklus** [comment]
Hi @lewie , I can see that the issue has been resolved in Calimero, will this be coming soon to OH's KNX add-on?

**Comment by lewie** [comment]
Hello @petrklus, it is on my looong todo list!

**Comment by petrklus** [comment]
> Hello @petrklus, it is on my looong todo list!

Thank you for your quick response and all your work! 🙌
