### ISSUE TITLE
[logreader] Getting log entries as digest

### ISSUE THREAD

**Issue by semperor** [openhab/openhab2-addons#4888]
## Expected Behavior
I think it would be nice if one could configure a digest event with all entries from the last n seconds (for example).

## Context
At the moment I send every warning and error direct to telegram. That's quiet a mess when starting oh (~ 50 messages). Or during development of new rules or something else where errors and warnings are likely to occur. On message with all errors per hour would be enough.
Furthermore one message (or email or whatever) with all warnings per day would be enough.

**Comment by paulianttila** [comment]
This can be done by the rules. You can collect message e.g. to list and then concatenated messages to one email post when certain amount of messages (~50) are collected or time (hour/day) threshold is exeeded.

If you decide to do this kind of rule, it can be added as an example to binding documentation page.

**Comment by davidgraeff** [comment]
Thanks for the idea :) As @paulianttila said, that can be handled by a rule. For OH3 there will also be a service that offers the log as websocket stream. But there is not more that we can do for now.

Closing.
