### ISSUE TITLE
[smtp-action] port mail action to openhab2-addons

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab2-addons#4915]
The OH1-Mail action (send mail via an external mail server) should be ported to OH2. This is different from #2147 which provides the possibility to control OH by receiving mails.

My idea is: a SMTP-server thing (which holds address, username, etc) and an action that uses this thing. Any comments?

**Comment by cweitkamp** [comment]
The only thought I like to add is if we should introduce a more flexible way for sending the mails. Instead it defining several actions with different parameters we could discuss something like a builder pattern for creating messages.

**Comment by J-N-K** [comment]
Another thought: wouldn‘t it be nice to have the possibility to send the logs via mail every day (or maybe only parts of that, like „all error“ and have that as configurable Option in UI without rules?

**Comment by davidgraeff** [comment]
The builder pattern could be realized by Things, where the Thing configuration is used to store text/html. Is that an option?

**Comment by J-N-K** [comment]
I think it is quite easy to realize the builder pattern within the binding (i.e. in java). The question is how this could be transported to the rule engine.

@davidgraeff, I don‘t fully understand what you propose.

**Comment by davidgraeff** [comment]
@J-N-K I thought about a visual way to use this. But never mind. Rules can be edited in a graphical fashion as well. Stupid me.

**Comment by cweitkamp** [comment]
@J-N-K Have a look at the OH1 Pushover binding (https://github.com/openhab/openhab1-addons/pull/5527). It already implemented a builder pattern. The rule actions can be moved / mapped to `ThingAction`s.

**Comment by J-N-K** [comment]
Before it gets to large: what is a good name for this? And is addons/binding really the best place? We had addons/action in OH1.

**Comment by cweitkamp** [comment]
I think it should be `org.openhab.io.smtp` or `org.openhab.io.transport.smtp`. `o.o.io.mail` would be too much because one could expect it to receive mails as well.

**Comment by kaikreuzer** [comment]
> The OH1-Mail action (send mail via an external mail server) should be ported to OH2.

Hm. You could also say "the oh1 actions should be ported to OH2". We therefore need to regard this not isolated, but as a general concept. So far the new rule engine is still marked experimental and @openhab-5iver is pushing it to become "standard" - and with it, we will have to define how "action addons" exactly look like.
Currently, we only allow bindings to additionally also carry actions in OH2 - so from this perspective, it would make sense to have a "mail" binding (probably something like https://github.com/openhab/openhab2-addons/pull/2147) and have mail actions being part of it.

**Comment by hakan42** [comment]
I asked a similiar question in the forum ( https://community.openhab.org/t/in-which-packages-should-oh2-actions-go/68363 )

The consensus (between all three authors in five messages :) ) was to go with "binding", considering that whatever is implemented could become a data source as well a write-only action that just sends data out.

**Comment by J-N-K** [comment]
One could probably do one binding for both but receiving mail with an OpenHAB-integrated SMTP Server to control something and sending mail via an external mail server as a notification has not much in common.

Also I do not think that integrating a SMTP Server in OH is any useful. There is a lot of good software out there and for receiving mail POP3/IMAP seems to be a better fit.

**Comment by kaikreuzer** [comment]
> Also I do not think that integrating a SMTP Server in OH is any useful.

I agree with you. So the action should rather go into a "mail" binding, which potentially also allows to provide the number of new messages in (external) IMAP/POP3 accounts or similar things. Let's leave the "mailserver" out of scope here.

**Comment by J-N-K** [comment]
That‘s a bit more than I was thinking about, but ok. I‘ll give it a try. 

I would suggest to create things per email-Account (i.e. address, name, password). Then make fixes channels for „unread mail“ and „total mail count“, action „send mail“ and extensible channels with configuration „from“ and „subject“ which provide mail-content. 

Does it make sense to have the server-information (hostname, Port, protocol etc.) included in the account-thing or as bridge on top of that? A bridge makes it easier to have several accounts on one server, having it all in things makes it less complex when defining only one or two accounts on different servers.

**Comment by kaikreuzer** [comment]
> That‘s a bit more than I was thinking about, but ok. I‘ll give it a try

I didn't want to say that you have to implement this right away (if you want, even better).
It should just be considered to be in the scope of this binding and thus its structure should be set up accordingly.

I'd think it would be ok to have server information part of the "account thing" (and not introduce a nother bridge layer here) -  or rather actually have the account info (e-mail & pwd) as part of "server things". This is how most e-Mail clients are set up as well. It might make sense to have "Incoming (IMAP/POP3) Server" and "Outgoing (SMTP) Server" as separate things. Wdyt?

**Comment by J-N-K** [comment]
I didn’t think that far in the beginning, but I like the idea. May take some time. Maybe we can merge that in two steps: the sending first, the inbox-part later.

**Comment by J-N-K** [comment]
#4989 solved this
