### ISSUE TITLE
[mail] can't set port on ssl

### ISSUE THREAD

**Issue by fabian727** [openhab/openhab2-addons#4937]
## Expected Behavior
configuring SSL=true and port=custom, should set port to the custom value, but is set to 465

I would propose trying both ports (if user set one) and using the working one, prefering the user port if both are working.

## Current Behavior
port is set to 465, though a custom one was set

## Steps to Reproduce (for Bugs)
1. just set ssl=true and port=25 (e.g.)
2. and you get a log entry for port 465. Openhab2 won't be able to contact the host, as the port is wrong

## Context
I cannot use ssl

## Your Environment
does not matter

**Comment by fabian727** [comment]
allready started discussing this topic in [here](https://community.openhab.org/t/email-addon-is-using-wrong-port/67860/9)

**Comment by 9037568** [comment]
This is the wrong issue tracker. The mail action is in the [OH1 addons](http://github.com/openhab/openhab1-addons) repo. And there's a ticket open there already, as noted in the community thread you linked.
