### ISSUE TITLE
[knx] Too many connections

### ISSUE THREAD

**Issue by bertmelis** [openhab/openhab2-addons#4941]
## Expected Behavior
Limit the number of simultaneous connections to the KNX/IP router

## Current Behavior
I don't know how to investigate in detail, but from what I suspect is that KNX creates 5 connections to my KNX. I have a Weinzierl 730 which is limited to 5 connections so I cannot access the bus anymore with other devices.
I don't know if there are 5 open connections or just 1 open and 4 half-open.
When trying to connect with my ETS5 it says "it's maximum amount of concurrent connections is already used"

## Steps to Reproduce (for Bugs)
I just installed OpenHAB2 (apt) and installed KNX via the paper ui.
2 KNX bridges are defined: one for the "real" things and one for the "generic" things.

## Your Environment
Debian 4.9.0-8-amd64
connected through vlan to KNX Router (Wienzierl 730) configured with DHCP.

**Comment by bertmelis** [comment]
closing.
The device actually only accepted one connection. additional connections have to be made by physically pushing the "learn" button on the device. (quite unhandy)

**Comment by lewie** [comment]
KNX IP connections there is a difference between a TUNNELING (direct fixed from Hardware to Hardware and maximum 4 Connections/Interface) and a ROUTING (on a common broadcasting IP with n Routers which can use this common IP to connect the KNX-bus) connections. If you have configured your 


KNX IP **Interfaces** like [KNX IP Interface 730](https://www.weinzierl.de/index.php/de/alles-knx1/knx-devices/produktarchiv/knx-ip-interface-730) use **TUNNELING** mode: Works with direct and a exclusive connection "channel" from Hardware to Hardware. Normally Interfaces allow a maximum of 4 Connections.

KNX IP **Routers** like [KNX IP Router 751](https://www.weinzierl.de/index.php/de/alles-knx1/knx-devices/knx-ip-router-751-de) additionally can connect in **ROUTING** mode: Routers communicate over a common broadcasting IP (239.0.23.12) and 0-n Routers can use this IP to connect the KNX-bus.

To be able to establish more than 4 connections to the KNX bus in your case, you can install [knxd ](https://github.com/knxd/knxd) somewhere in your network. Then you can use your interface to establish one of the 4 tunneling connections to knxd. knxd can then make this connection available to many more routers in ROUTING mode.

Knxd is small, fast and needs few resources. For example, it can run on any Raspi next to openHAB.

So finally, the behavior is not a bug, but unfortunately a feature

**Comment by lewie** [comment]
> 
> 
> closing.
> The device actually only accepted one connection. additional connections have to be made by physically pushing the "learn" button on the device. (quite unhandy)

![grafik](https://user-images.githubusercontent.com/5707426/53089487-023e6000-350d-11e9-9715-a023a56773fb.png)

Up to 5 Connections. Not 4! :-)
