### ISSUE TITLE
Remove stale branches

### ISSUE THREAD

**Issue by davidgraeff** [openhab/openhab2-addons#4969]
There is still a 2.x and 2.2.x branch existing. Can those be removed?

@openhab/2-x-add-ons-maintainers

**Comment by kaikreuzer** [comment]
As long as all tags are kept, that's imho fine.

**Comment by wborn** [comment]
I've deleted the stale branches and all tags are still there.
Shall we also cleanup the openhab-core and openhab-distro stale branches?
