### ISSUE TITLE
[rfxcom] rfy thing throws java.lang.NumberFormatException

### ISSUE THREAD

**Issue by DirkHBo** [openhab/openhab2-addons#4975]
## Expected Behavior

Command (up/down/stop) should be executed in RFXCom-Bridge. 
For example: a rollershutter-item is configured for usage in the basic-ui. Clicking the down button will make the related rollershutter go down.

## Current Behavior

Clicking on the command will come to nothing. Instead an exception is thrown within in the openhab.log.
> ==> /var/log/openhab2/openhab.log <==
> 2019-02-23 10:44:14.616 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.handleCommand()' on 'org.openhab.binding.rfxcom.handler.RFXComHandler@25d03f25': For input string: "‭327937‬"
java.lang.NumberFormatException: For input string: "‭327937‬"
>        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
>       at java.lang.Integer.parseInt(Integer.java:580) ~[?:?]
>        at java.lang.Integer.parseInt(Integer.java:615) ~[?:?]
>        at org.openhab.binding.rfxcom.internal.messages.RFXComRfyMessage.setDeviceId(RFXComRfyMessage.java:159) ~[?:?]
>        at org.openhab.binding.rfxcom.internal.messages.RFXComDeviceMessageImpl.setConfig(RFXComDeviceMessageImpl.java:43) ~[?:?]
>        at org.openhab.binding.rfxcom.internal.messages.RFXComRfyMessage.setConfig(RFXComRfyMessage.java:1) ~[?:?]
>        at org.openhab.binding.rfxcom.handler.RFXComHandler.handleCommand(RFXComHandler.java:75) ~[?:?]
>        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
>        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
>        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
>        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
>        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [102:org.eclipse.smarthome.core:0.11.0.oh250M1]
>        at org.eclipse.smarthome.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [102:org.eclipse.smarthome.core:0.11.0.oh250M1]
>        at com.sun.proxy.$Proxy122.handleCommand(Unknown Source) [202:org.openhab.binding.rfxcom:2.5.0.M1]
>        at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:75) [109:org.eclipse.smarthome.core.thing:0.11.0.oh250M1]
>        at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:49) [109:org.eclipse.smarthome.core.thing:0.11.0.oh250M1]
>        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
>        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
>        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
>        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
>        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [102:org.eclipse.smarthome.core:0.11.0.oh250M1]
>        at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [102:org.eclipse.smarthome.core:0.11.0.oh250M1]
>        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
>        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
>        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
>        at java.lang.Thread.run(Thread.java:748) [?:?]

## Steps to Reproduce (for Bugs)

1. Install openhab2
2. define Bridge rfxcom:bridge:usb0 [ serialPort="/dev/ttyUSB0" ]
3. define Thing rfy RolloKueche [deviceId="‭327937‬.1", subType="RFY"]
4. do some linking in Paper-UI or for Basic-UI for the Things
5. click the up/down/stop button in the UI and inspect the openhab.log

## Your Environment
* Opering System: Debian Stretch as QEMU-guest and Raspbian Stretch on RPi3 (both with stable packages only)
* Evironment: tested with Zulu-8 and Oracle JDK 8r192 (64bit) (JDK just on debian)
* OpenHab-Version: 2.4 and 2.5M1 (last know working version is 2.2)

Configuration:
>Bridge rfxcom:bridge:usb0 [ serialPort="/dev/ttyUSB0" ] {
>    Thing rfy GF_LivingRoom_Shutter [deviceId="‭327937‬.0", subType="RFY"]
>    Thing rfy RolloKueche [deviceId="‭327937‬.1", subType="RFY"]
>}

**Comment by DirkHBo** [comment]
As I can not estimate the effort needed to fix this issue, my suggestion is that there is just a smaller problem with a number or string conversion. I put a little bounty on that  - hopefully the expense is reasonable.

**Comment by martinvw** [comment]
Its reproducible also with an item created through paperUI, this should be feasible to fix

**Comment by martinvw** [comment]
And solved, but I don't want the bounty for it 😄 

If you go to https://www.branah.com/unicode-converter and paste the string '327937‬.0' you will find that it contains some evil zero width character in between:

https://www.fileformat.info/info/unicode/char/202c/index.htm

Just remove everything an type it by hand or copy the following:

'327937.0' 
'327937.1'

**Comment by martinvw** [comment]
@DirkHBo if you can't get your money back I'm willing to accept and put it on another openHAB issue, just let me know.

**Comment by maggu2810** [comment]
@martinvw Good catch!

**Comment by DirkHBo** [comment]
> If you go to https://www.branah.com/unicode-converter and paste the string '327937‬.0' you will find that it contains some evil zero width character in between:

Thats it - never thought about searching in my documentation. Background: About a year ago I started to document all devices with an Excel sheet. Excel seems to hide some extra unicode symbols for formatting the fields. So I can reproduce that in my own documentation - shame on me.

@martinvw Thanks a lot - I'm quite sure I would never find this documentation-bug. And kudos for catching this evil zero. Feel free to claim the bounty - and of course I would be glad to support another openhab2 issue of your choice.
