### ISSUE TITLE
[deconz] Support for Resource Type : ZHAAlarm

### ISSUE THREAD

**Issue by SuperSchelli** [openhab/openhab2-addons#4976]
As stated in the topic the Resource Type ZHAAlarm is not yet supported

## Your Environment
Using Openhab Unstable  2.5.0~M1-1
Openhabian on Raspi 3B+

2 of the 3 Channels are already supported ZHAPresence and ZHALightLevel

Here is a complete Rest API printout of the 3rd Channel ZHA Alarm
````
"88": {
    "config": {
      "battery": 100,
      "on": true,
      "pending": [],
      "reachable": true,
      "temperature": 2500
    },
    "ep": 1,
    "etag": "xxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "manufacturername": "LUMI",
    "modelid": "lumi.sensor_motion.aq2",
    "name": "Motion 4",
    "state": {
      "alarm": false,
      "lastupdated": "none",
      "lowbattery": false,
      "tampered": false
    },
    "swversion": "20170627",
    "type": "ZHAAlarm",
    "uniqueid": "xx:xx:xx:xx:02:e9:f7:xx-01-0500"
  },
````

Hardware Model :  Xiaomi RTCGQ11LM Smart Home Aqara Human Motion Sensor - White
https://www.gearbest.com/alarm-systems/pp_659226.html?wgu=11079_196673_15509232647219_f4c92e5037&wgexpiry=1558699264&siteid=196673&utm_source=webgains&utm_campaign=GearbestDE

**Comment by cweitkamp** [comment]
Hi @SuperSchelli,

I added support for the "ZHAAlarm" cluster and the optional channel "tampered". Here is a test version: [org.openhab.binding.deconz-2.5.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab2-addons/files/2942331/org.openhab.binding.deconz-2.5.0-SNAPSHOT.jar.zip)

[Documentation](https://github.com/cweitkamp/openhab2-addons/commit/a9f4d2311ab729a3db4b1ec7722e23691615c115#diff-c2399132e663b87994fcd9507ba586cb)

Please let me know if it works for you.

**Comment by SuperSchelli** [comment]
OK, thx a lot for implementing the thing channel.
It works perfectly i can add the alarm sensor via UI and via Config file.
I don´t know how i can trigger an alarm, so i cant really test it, but all show OFF atm...

Unfortunatly my REST APi call shows all tampered items as null atm, thus they are not getting added and i can't test them, but from looking at the source code all looks ok to me... so it should work. if they somehow start reporting another state for tampered i ll write here, if that one works as well

i found one typo in the documentation though
````
alarmesensor        basement-alarm          "Basement Alarm Sensor"     [ id="8" ]
````
must be alarmsensor, one sneaky "e" somehow made its way in there

**Comment by cweitkamp** [comment]
Thank you for the feedback.

> i found one typo in the documentation

I fixed it.

> where that is coming from, maybe i screwed something up

No you did not. It is related to https://github.com/openhab/openhab-core/issues/607
