### ISSUE TITLE
Add MelCloud Binding

### ISSUE THREAD

**Issue by SepuWeb** [openhab/openhab2-addons#4992]
Hi all, I plan to develop new binding for MelCloud.

https://community.openhab.org/t/melcloud-binding-mitubishi/62199/5

I open this issue because is requested in develop guide.

https://www.openhab.org/docs/developer/development/bindings.html#before-you-start

**Comment by lucacalcaterra** [comment]
Hi, i've already developed it, but to complete, test and cleanup... I'll very proud to collaborate... how i can share it ? It's not ready to create a PR as indicates in guide lines...

**Comment by SepuWeb** [comment]
Hi, Luca, good to know! (Yes i'm Italian).
I've created this branch, we can share project here and when will be ready we can create tag and create new Pull Request in WIP mode in OpenHab. 

Branch: 
https://github.com/SepuWeb/OpenHab-MelCloud-Binding.git

**Comment by lucacalcaterra** [comment]
Your branch is as mine :-) For now it's private, must fix some things and share with you (and others). One or two days .

**Comment by lucacalcaterra** [comment]
I've developed it, Need testers:
Can download initial beta to releases section of my github repo:

https://github.com/lucacalcaterra/org.openhab.binding.melcloud

ASAP want to fix and create a PR for pushing to Openba2 Addons Repo

**Comment by wborn** [comment]
It got recently merged with https://github.com/openhab/openhab2-addons/pull/6059
