### ISSUE TITLE
[meteoblue] why the weather condition is a number rather than a text ?

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab2-addons#5024]
Using the metoblue binding, I tried to translate in French the weather conditions provided by the binding in English.
Here is an extract of my fr.map file in which I escaped the spaces:
```
Sunny,\ cloudless\ sky=Ciel ensoleillé
Sunny\ and\ few\ clouds=Ensoleillé et quelques nuages
Partly\ cloudy=Partiellement nuageux
Overcast=Couvert
Fog=Brouillard
Overcast\ with\ rain=Couvert avec pluie
Mixed\ with\ showers=Variable avec averses
Showers,\ thunderstorms\ likely=Averses, orages probables
Overcast\ with\ snow=Couvert avec neige
Mixed\ with\ snow\ showers=Variable avec des averses de neige
Mostly\ cloudy\ with\ a\ mixture\ of\ snow\ and\ rain=Nuageux avec un mélange de neige et de pluie
Overcast\ with\ light\ rain=Couvert avec faible pluie
Overcast\ with\ light\ snow=Couvert avec quelques chutes de neige
Mostly\ cloudy\ with\ rain=Nuageux avec pluie
Mostly\ cloudy\ with\ snow=Nuageux avec neige
Mostly\ cloudy\ with\ light\ rain=Nuageux avec avec faible pluie
Mostly\ cloudy\ with\ light\ snow=Nuageux avec quelques chutes de neige
```
and my item definition:
```
String meteoblueCondition "Conditions prévues [%s]" {channel="meteoblue:weather:api:maison:forecastToday#condition"}
String meteoblueCondition2 "Conditions prévues [MAP(fr.map):%s]" {channel="meteoblue:weather:api:maison:forecastToday#condition"}
```
The UI displays "Mostly cloudy with light rain" for the first item but nothing for the second item with mapping (I am expecting "Nuageux avec avec faible pluie").

I tried without escaping the spaces but it does not help.

**Comment by lolodomo** [comment]
If I update the item with a console command, it seems to work.
smarthome:update meteoblueCondition2 "Fog"
Then I get "Brouillard" in UI.
smarthome:update meteoblueCondition2 "Mostly cloudy with light rain"
Then I get "Nuageux avec avec faible pluie" in UI.
So mapping seems to work in this case.

Does it mean the meteoblue service does not use a real space in weather condition values ?

**Comment by lolodomo** [comment]
smarthome:items list meteoblueCondition
meteoblueCondition (Type=StringItem, State=16, Label=Conditions prévues, Category=null, Groups=[GMeteo])

It looks like the state is not really a text but a number in a string !

Confirmed by looking at the channel definition. There is a list of options and the value is 1 to 17.

**Comment by 9037568** [comment]
All these values are found in thing-types.xml.
You could leave this ticket open as a request for allowing mapping/translating them...

**Comment by lolodomo** [comment]
In my opinion, this channel should have been a simple text, then it could be usable (without adding a mapping) in a rule. What is the need for the integer value for the user ?

That being said, I will probably provide a translation in French for the binding.

**Comment by lolodomo** [comment]
I close this issue after having created a PR to add the french translation for the "condition" channel.
By the way, in a DSL rule, you need to define and use a MAP transformation to get the textual value as a text. Not very practical.
