### ISSUE TITLE
[mqtt] homeassistant binding ignores "payload_on"/"payload_off" directives

### ISSUE THREAD

**Issue by wildwiz** [openhab/openhab2-addons#5027]
The MQTT binding successfully discovers the devices (via HASS discovery),
properly reports them as online, but it then fails to control them.

## Expected Behavior
Flipping an MQTT bound Item from PaperUI/Control should cause the appropriate MQTT message to be sent to the broker.

## Current Behavior
Flipping an MQTT bound Item from PaperUI/Control causes the following WARNs in openhab.log. The MQTT message is actually sent, but with the wrong content.
Details

## Details
Configuration JSON of the discovered Thing attached to the Item (discovered with HASS discovery):
```
{"name":"sw1","platform":"mqtt","state_topic":"sw1/relay/0",
 "command_topic":"sw1/relay/0/set","payload_on":"1","payload_off":"0",
 "availability_topic":"sw1/status","payload_available":"1","payload_not_available":"0"}
```
note "payload_on":"1","payload_off":"0"

Warning registered in logs:
```
2019-02-05 21:22:14.710 [WARN ] [eneric.internal.generic.ChannelState] - Command '1' not supported by type 'OnOffValue': No enum constant org.eclipse.smarthome.core.library.types.OnOffType.1
2019-02-05 21:22:17.224 [WARN ] [eneric.internal.generic.ChannelState] - Command '0' not supported by type 'OnOffValue': No enum constant org.eclipse.smarthome.core.library.types.OnOffType.0
```

Content in the MQTT message actually sent contains the text "true"/"false" rather than "1"/"0", which the device does not recognize.

## Steps to Reproduce
Via Paper UI:
1.  Discover a Thing via HASS discovery from MQTT with discovered content as mentioned in JSON configuration.
1. Link the Thing to an Item.
1. Operate the Item flipping the switch on and off.
1. Check the MQTT output carrying the wrong payload.

Additionally, I suspect that the capture of the actual state from MQTT is failing as well for similar reasons.

## Environment
OpenHab reinstalled from scratch, no other configurations or status in the way.
Version used: OpenHab and addons 2.5.0.M1

Java: both
* Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
* Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

Operating System and version: both
* Ubuntu 16.04.5 LTS
* QNAP TS-669 Pro, QTS 4.3.4.0752

**Comment by davidgraeff** [comment]
With openHAB 2.4 the priority was to push the MQTT binding and Homie support out, with a rudimentary support for HASS devices. At the moment there is a huge contribution from @jochen314 coming in, that makes this support a lot more specification compliant and probably solve your issue.

After those patches are in, I first need to move the mqtt bindings to the new build system though and fix outstanding issues before we can aim for a 100% HASS compliance.

**Comment by jochen314** [comment]
The problem seems to be in the OnOffValue with the MQTT configuration.
The MQTT configuration calls for different values for the state and the command topic.
So reading in from the `state_topic` the `state_on`/`state_off` values are expected.
But when setting the value to the `command_topic` then 'playload_on`/`payload_off` are expected.

So it is an interessting device, which uses a different representation for the state than for the command.

But we should tage this in to account, as the specification allows it.

@davidgraeff Would it make sense to allow for a list of on/off Strings in the OnOffValue (and maybe others) and use the first one of each list for the publish value?

**Comment by davidgraeff** [comment]
Hm. A list might not make sense, hopefully nobody has a device with an MQTT topic that sends multiple different values to represent one and the same state.

I suggest to have a custom state on/off and command on/off, defaulting to openHABs OnOffType enum values: ON and OFF. If someone requires further on/off strings, there is still the map transformations to the rescue.

**Comment by jochen314** [comment]
Ok, 
So we make `ChannelStateTransformation` an interface and we add the out-transformation using an anonymous object to the channel, when needed?

**Comment by davidgraeff** [comment]
Nah. For making the homeassistant specification happy we only need to change
https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/values/OnOffValue.java

and have:
```
    private final String customOnState; // OnOffType.ON.name()
    private final String customOffState; // OnOffType.OFF.name()

    private final String customOnCommand; // OnOffType.ON.name()
    private final String customOffCommand; // OnOffType.OFF.name()
```
