### ISSUE TITLE
[Z-wave] - add dimmer device (McoHome)

### ISSUE THREAD

**Issue by kanebullen** [openhab/openhab2-addons#5066]
Hi

I have just installed OpenHAB to test it out with a couple z-wave devices I am looking at for my new house.

It was able to detect one of the devices (McoHome MH-S513 Touch Panel Switch), but it doesn't seem to recognise the dimmer switch (same manufacturer, MH-P511)     It is coming up as an Unknown Device.

Looking at the supported devices list, there is the "MH-P311 MCO Home Dimmer Switch", which I'd assume this device is pretty similar to?

Hopefully the following is enough information to help get this device in the database!

zwave_beaming | true
zwave_class_basic | BASIC_TYPE_ROUTING_SLAVE
zwave_class_generic | GENERIC_TYPE_SWITCH_MULTILEVEL
zwave_class_specific | SPECIFIC_TYPE_SCENE_SWITCH_MULTILEVEL
zwave_deviceid | 5203
zwave_devicetype | 20762
zwave_frequent | false
zwave_listening | true
zwave_manufacturer | 351
zwave_neighbours |  
zwave_nodeid | 3
zwave_plus_devicetype | NODE_TYPE_ZWAVEPLUS_NODE
zwave_plus_roletype | ROLE_TYPE_SLAVE_ALWAYS_ON
zwave_routing | true
zwave_secure | false
zwave_version | 3.3

Thank you!
Kane

**Comment by openhab-5iver** [comment]
The zwave binding is [maitained in its own repo](https://github.com/openhab/org.openhab.binding.zwave) (not this one). BUT, the device database is exported from this website, which [you can update yourself](https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guide). If you have issues, please create a topic in the [forum](https://community.openhab.org/c/add-ons/bindings), as there are people there that can assist.

**Comment by kanebullen** [comment]
thanks - will do!
