### ISSUE TITLE
[squeezebox] Wrong IP for stream URLs (play/say) when using Docker

### ISSUE THREAD

**Issue by solars** [openhab/openhab2-addons#5074]
hi there,

I noticed that if I'm running OpenHab inside a docker container, squeezebox is not able to use my audio sinks to play notifications or TTS streams.

The reason is visible in this log output:

https://gist.github.com/solars/9ea1a555ad6195758617efffbaa38ee1`

The URL it uses for the stream, uses the internal docker IP. The actual IP my Openhab is running on is 192.168.1.25. If I substitute it, the stream is accessible.

Are there any ways to handle this?

**Comment by wborn** [comment]
Looks like @mhilbush already put some effort in creating a version supporting a `callbackUrl` configuration parameter on the binding. See this [community topic](https://community.openhab.org/t/squeezebox-binding-callbackurl-for-reverse-proxy-configuration/40787?u=wborn).

The `callbackUrl` is also used in the [Chromecast](https://www.openhab.org/addons/bindings/chromecast/#chromecast-binding) and [Sonos](https://www.openhab.org/addons/bindings/sonos/#binding-configuration) bindings

**Comment by solars** [comment]
Thanks! I'll discuss that here: https://community.openhab.org/t/squeezebox-cant-get-audio-sink-to-work-for-notifications/69824/3
