### ISSUE TITLE
[millheat] Add Millheat Binding

### ISSUE THREAD

**Issue by seime** [openhab/openhab2-addons#5076]
I have started working on a binding for Mill home heaters https://www.millheat.com/mill-wifi

* A first alpha binary to be placed in your addons folder can be found here: https://github.com/seime/openhab2-addons/releases/tag/2.5.0.M1.millheat.alpha1

* [Make sure you read the readme file](https://github.com/seime/openhab2-addons/blob/millheat/addons/binding/org.openhab.binding.millheat/README.md)

* Code resides here: https://github.com/seime/openhab2-addons/tree/millheat/addons/binding/org.openhab.binding.millheat

**Comment by libo** [comment]
IT WORKS! 
Thanks a lot!

I tested with you example config files and, adding a couple of taggings, even managed to connect to HomeKit Integration I run on my openhab2. 

<img width="246" alt="Screenshot 2019-03-10 at 17 36 27" src="https://user-images.githubusercontent.com/37512/54088141-15e62500-435b-11e9-9b6d-5a3ede4997b1.png">

Now it would be awesome to have 2 more parameters:
- TargetTemperature Number R/W
- CurrentHeatMode String R/W (this will be comfort, away or sleep)

Once we have those we can use it with HomeKIT :-)

**Comment by seime** [comment]
New beta release available for testing:

https://github.com/seime/openhab2-addons/releases/tag/2.5.0.M1.millheat.beta1

Updated docs: https://github.com/seime/openhab2-addons/tree/millheat/addons/binding/org.openhab.binding.millheat

**Comment by bjovas** [comment]
@seime, tested the org.openhab.binding.millheat-2.5.0-SNAPSHOT.jar release in 2.5 milestone 6 in openhabian, it seems to be working really smooth.

Am currently only using the mill wallplugs. 



Some smaller things in the log:

 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler MillheatAccountHandler tried updating the thing status although the handler was already disposed.

 [hingStatusInfoChangedEvent] - 'millheat:account:c******' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): Error sending request to Millheat server: Total timeout 5000 ms elapsed
