### ISSUE TITLE
[avmfritz] documentation is gone

### ISSUE THREAD

**Issue by alexf2015** [openhab/openhab2-addons#5108]
I guess due to #5050 the documentation is no longer available at: https://www.openhab.org/addons/bindings/avmfritz/

**Comment by J-N-K** [comment]
That's probably related to the change in the build System since Astro is missing, too.

**Comment by wborn** [comment]
I've created an issue in openhab-docs for this instead: https://github.com/openhab/openhab-docs/issues/918.
