### ISSUE TITLE
[denonmarantz] Not java 11 compatible

### ISSUE THREAD

**Issue by davidgraeff** [openhab/openhab2-addons#5148]
Requires a 
```
<dependency>
  <groupId>com.sun.xml.bind</groupId>
  <artifactId>jaxb-impl</artifactId>
  <version>2.3.2</version>
</dependency>
```
or similar for the bnd port to provide `javax.xml` again.

**Comment by cweitkamp** [comment]
And others too, I guess:

- org.openhab.binding.avmfritz
- org.openhab.binding.helios
- org.openhab.binding.tellstick

- org.openhab.binding.dlinksmarthome

Last one uses `javax.xml.soap`.

**Comment by J-N-K** [comment]
I'll port it to bnd and add the missing dependencies.
