### ISSUE TITLE
Java 11 compatibility required

### ISSUE THREAD

**Issue by davidgraeff** [openhab/openhab2-addons#5162]
All new add-ons must be compatible to Java 11 without deprecation warnings from here on.

To be ported:

- [x] org.openhab.binding.avmfritz
- [x] org.openhab.binding.dlinksmarthome
- [x] org.openhab.binding.denonmarantz
- [x] org.openhab.binding.dwdunwetter
- [x] org.openhab.binding.helios
- [x] org.openhab.binding.homematic
- [ ] org.openhab.binding.ihc
- [x] org.openhab.binding.tellstick
- [ ] org.openhab.binding.toon
- [x] org.openhab.binding.yamahareceiver
- [ ] org.openhab.transform.xpath

**Comment by EliasGabrielsson** [comment]
@davidgraeff When will openHAB have a strict requirement on Java 11. Will that transition happen in next version? Need to know that so we can have migration code ready in openhabian.

**Comment by davidgraeff** [comment]
Not this year. The core and majority of bindings will be Java 8 and 11 compatible, that's the goal.

But I remember a discussion with Kai that certain bundles may be allowed to require more than Java 8 (my question at that time was regarding the DTLS support which greatly improved in Java 9).

**Comment by EliasGabrielsson** [comment]
Nice, that gives us a great update window. When does openHAB aim be java 11 compatible™, i.e. when can we start the transition to Java 11?

**Comment by davidgraeff** [comment]
That depends on how important openhab1-addon users are to you, because we will not migrate those bindings anymore. As soon as you switch over to 11 half of those bindings will fail probably :/

At the moment it looks like OH 2.5 Core and Addons (minus the OH1-combat layer) will be java 11 compatible.

**Comment by wborn** [comment]
Currently nrjavaserial (required by all bindings using serial comms) crashes the whole runtime on Windows with Java 11 (https://github.com/NeuronRobotics/nrjavaserial/issues/131). So I'd like to see that fixed too before declaring openHAB to be Java 11 compatible. Most known issues are linked to https://github.com/openhab/openhab-distro/issues/768.

Hopefully the visibility of this issue also makes contributors create PRs for better Java 11 compatibility. :-) Most Travis CI builds now also have a Java 11 build so it has become more visible what still needs to be fixed.

**Comment by J-N-K** [comment]
Can you confirm that the proposed fix indeed is everything that is needed in nrjavaserial? The linked issues seems to state that there are more problems.

**Comment by wborn** [comment]
I'm only occasionally using Windows myself. So I haven't thoroughly tested the nrjavaserial Java 11 Windows fix myself.

**Comment by J-N-K** [comment]
What exactly is the problem with homematic? It compiles and passes feature verification on Java 11 without modification.

**Comment by davidgraeff** [comment]
Tick it off ^^

**Comment by cweitkamp** [comment]
Maybe it is a false positive because of `javax.xml.bind` in its manifest.

https://github.com/openhab/openhab2-addons/blob/6f84f1562474f4512ff5ef97d71bd1ce24d7b820/addons/binding/org.openhab.binding.homematic/META-INF/MANIFEST.MF#L22

**Comment by wborn** [comment]
Now that #5338 is merged we enforce that all code compiles with Java 11.

The add-ons were still open in the list use the javax.xml.xpath, javax.ws.rs packages which are still available in Java 11. See [Dependencies On Java EE Modules](https://blog.codefx.org/java/java-9-migration-guide/#Dependencies-On-Java-EE-Modules) for all packages that are impacted.

**Comment by davidgraeff** [comment]
Has someone changed Travis already to enforce j11? Then we can close this issue

**Comment by dbadia** [comment]
I see consistent JVM crashes on windows due to the nrjavaserial issue with Java 11 (NeuronRobotics/nrjavaserial#131) as mentioned by @wborn.  I am working on the zwave addon

Is this problem being tracked in a different issue as this one is closed?

**Comment by wborn** [comment]
There's also a https://github.com/openhab/openhab-distro/issues/768#issuecomment-446794070 for this. That's the overarching issue to fix issues encountered while running openHAB with Java 11.
