### ISSUE TITLE
[rfxcom] Suppress usage of library JD2xx

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab2-addons#5169]
I open this issue to follow the discussion started in #5005 .

If we decide to suppress the use of the library JD2xx from the RFXCOM binding, all users having a bridge thing that was created through automatic discovery will be impacted.

I propose for these existing things to keep them but to set the status to OFFLINE with a clear message asking to switch to the manual configuration bridge type.

@paulianttila : what do you think about that ? And do you want to implement the change ?

**Comment by paulianttila** [comment]
@lolodomo,I like the offline idea and yes i can do it. It will take couple weeks before i can concentrate on this as i’m currently under the sun far a way from home :-) 

If this is a blocker for the bnd migration, maybe @martinvw could do it earlier as well?

**Comment by lolodomo** [comment]
I can do it as soon as my today PR is merged.

**Comment by lolodomo** [comment]
I hope that the user will be able to move all his RFXCOM things from the JD2xx bridge to the generic serial bridge. If not, he could be very annoying.
I think this feature is available in Paper UI but to be honest I never tried it.
Of course, for users having their setup in config files, the change will be simpler and faster.

**Comment by lolodomo** [comment]
I got a better idea. We can just add the serialPort config setting to the JD2xx bridge things and make these things OFFLINE when this setting is not set (with a clear message).
Doing like that, the users will have no bridge or things to create again, they will only have to set the user port on their existing bridge thing.
Very simple to implement and with minor impact on users.

**Comment by lolodomo** [comment]
I close this issue, I don't want to generate difficulty to users. What trigger this change was the migration to bnd and the problem with external libraries, but a solution has been found now for that and we can keep the JD2xx library.

**Comment by lolodomo** [comment]
Close it
