### ISSUE TITLE
[mqtt] Binding is displayed as "MQTT Homie Binding" in Paper UI

### ISSUE THREAD

**Issue by hakan42** [openhab/openhab2-addons#5373]
## Expected Behavior

With Build 1564 as of 31.3.2019, the binding shows as "MQTT Homie Binding" in the Paper UI. This description seems to come from the package bundles/org.openhab.binding.mqtt.homie

## Current Behavior

This should be "MQTT Thing and Channels Binding" as defined in the main mqtt binding.

## Steps to Reproduce (for Bugs)

1. Open Paper UI
2. Select "Configuration", then "Bindings"

## Context

This is a bit misleading when selecting Inbox -> Auto Discover, as it suggest that only Homie devices can be found. Whereas, when choosing "Add Manually", all options including "Generic MQTT Thing" is available.

## Your Environment

* Version used: dockerized openHAB, build 1564.

**Comment by davidgraeff** [comment]
This only affects paper UI does it? Paper UI is not in this repository.

Can you verify with the OSGi openHAB console with the command bundle:list please

**Comment by hakan42** [comment]
Well, before the move to bnd and split into three bundles, it used to work in PaperUI... Now, it is a bit misleading.

The Bluetooth binding, which also consists of three bundles, looks o.k. in PaperUI.

MQTT, in the console:

```
openhab> bundle:list | grep -i mqtt
229 x Active x  80 x 1.2.0                 x Paho MQTT Client
235 x Active x  80 x 2.5.0.201903310938    x openHAB Add-ons :: Bundles :: MQTT Broker Binding
236 x Active x  81 x 2.5.0.201903310938    x openHAB Add-ons :: Bundles :: MQTT Things and Channels
237 x Active x  82 x 2.5.0.201903310938    x openHAB Add-ons :: Bundles :: MQTT HomeAssistant Convention
238 x Active x  82 x 2.5.0.201903310938    x openHAB Add-ons :: Bundles :: MQTT Homie Convention
252 x Active x  80 x 2.5.0.201903281431    x openHAB Core :: Bundles :: MQTT Transport
```

**Comment by davidgraeff** [comment]
Might be the binding.xml file. Copy paste error I assume. Thanks for the report.

**Comment by davidgraeff** [comment]
Fixed in master
