### ISSUE TITLE
[MQTT Binding] Manual configuration not described in https://www.openhab.org/addons/bindings/mqtt/

### ISSUE THREAD

**Issue by euphi** [openhab/openhab2-addons#5431]
The documentation (based on README.MD) of the MQTT bindings lacks a description of how to configure an MQTT thing with a .thing text file (https://www.openhab.org/addons/bindings/mqtt/)

Textual thing configuration of a (generic) MQTT thing  is only possible by making some gueses based on the general configuration help, e. g. in https://www.openhab.org/docs/configuration/things.html

**Comment by davidgraeff** [comment]
See https://community.openhab.org/t/mqtt-2-x-why-the-easy-way-when-you-can-have-it-complicated/71332/9?u=david_graeff

**Comment by euphi** [comment]
Ok, you meant https://github.com/openhab/openhab2-addons/blob/master/bundles/org.openhab.binding.mqtt.generic/xtend_examples.md ?

I'll try some configuration - but I guess I will have furthe questions ....

**Comment by davidgraeff** [comment]
Closing for now. I'm in contact with the web team and also created an issue here and on core already to consider example markdown files.
