### ISSUE TITLE
[mqtt] Homie channels lose their unit and other information after an openHAB restart

### ISSUE THREAD

**Issue by bodiroga** [openhab/openhab2-addons#5469]
Hi @davidgraeff!

I've found that, after restarting openHAB, Homie channels lose their 'secondary' information (the information provided by the 'property' attributes). I've been digging in the code and the reason for this is that, even if the channel is correctly created, the channel-type doesn't exist after the reboot! The channel (and the item) continues to receive the information, because the mqtt subscription is set, but the behavior of the channel is really weird (for example, if you remove the link to the actual item, you are not able to link it anymore). Although that doesn't seem to be strange, because we have a channel with a non-existent channel type :rofl: 

Ok, here is the cause of the error:

- In the [211th line of the Device class](https://github.com/openhab/openhab2-addons/blob/master/bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/homie300/Device.java#L211), in the 'initialize' method, after checking the previously existing channels, the "createChannelFromAttribute()" method is called for the 'property'.
- The '[createChannelFromAttribute()](https://github.com/openhab/openhab2-addons/blob/master/bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/homie300/Property.java#L157)' method calls the '[createChannelType](https://github.com/openhab/openhab2-addons/blob/master/bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/homie300/Property.java#L133)' method and the channelType is created through the ChannelTypeBuilder. But...
- Nobody is calling the '[propertyAddedOrChannged](https://github.com/openhab/openhab2-addons/blob/master/bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/handler/HomieThingHandler.java#L186)' method of the HomieThingHandler and, thus, the 'MqttChannelTypeProvider' doesn't add the channelType!

Two possible solutions:

- In the Device's initialize function, instead of calling '[createChannelFromAttribute()](https://github.com/openhab/openhab2-addons/blob/master/bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/homie300/Device.java#L211)', we can call the '[attributesReceived()](https://github.com/openhab/openhab2-addons/blob/master/bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/homie300/Property.java#L120)' method. The 'attributesReceived()' function takes care of calling the 'propertyAddedOrChanged' callback.
- Remove the 'attributesReceived()' function, change all its appearances with the 'createChannelFromAttribute()' function and call the 'propertyAddedOrChanged()' function at the end of the 'createChannelFromAttribute' function (line 221).

What do you think? Which one do you prefer? The first one seems simpler and cleaner, don't you think?

I will provide the corresponding PR after hearing your opinion :wink:

Best regards,

Aitor

**Comment by davidgraeff** [comment]
I have the feeling there was a reason for having both methods. So yes, going with solution one is also my preference.

Thanks for the catch.

I thought I had covered everything by test cases, but I now it does come to my mind that I never simulated a node/property restore from channel configuration so didn't catch this behavior.
