### ISSUE TITLE
[ALL] Abuse of core thread pool classes

### ISSUE THREAD

**Issue by davidgraeff** [openhab/openhab2-addons#5505]
openHAB core allows to request a named `ScheduledExecutorService` via `ThreadPoolManager.getScheduledPool(name)` with a default of 5 idle threads.

A lot of bindings are requesting their own executor and are scheduling exactly one task at a time.

See https://github.com/openhab/openhab2-addons/search?q=ThreadPoolManager&unscoped_q=ThreadPoolManager

The average thread count per binding should be 1 (a binding usually either schedules or has a permanent network thread) and core itself should not use more than 5 threads. It's really nuts at the moment with about 200 threads on small systems.

**Comment by kaikreuzer** [comment]
> A lot of bindings are requesting their own executor

Most of the ones I am seeing from that query are situations that have been discussed in depth in the individual binding review - i.e. those are accepted exceptions to the rule that bindings should not use their own pool.

There might be cases, where it has slipped through in a review and where the code should be changed - but I'd suggest to open an individual issue for such situations, where you feel that a binding creates a separate pool without any good reason and without using it decently.

**Comment by davidgraeff** [comment]
For example the dashbutton in https://github.com/openhab/openhab2-addons/blob/e97d52598a748c576051739b05c48fd147d5b72c/bundles/org.openhab.binding.amazondashbutton/src/main/java/org/openhab/binding/amazondashbutton/internal/pcap/PcapNetworkInterfaceService.java

It allocates its own pool and it uses exactly 1 thread to schedule polling. And that's what most bindings do.

This issue is actually about scripted mass changes. I don't want to open 24 issues, because as far as I see every binding in this list is using the pool API wrong. Maybe it's lack of API documentation. I don't think that all binding authors know that a thread of that pool auto-timesout after 60 seconds (if I read the code correctly).

**Comment by kaikreuzer** [comment]
I remember at least 5 in-depth discussions where it has been approved to do it that way.
Very often it was due to long running threads that would exhaust the common/binding pool easily.
And what you are maybe missing about such pools is the fact that they collapse to just one active thread, if no concurrent jobs are scheduled (and if this isn't true, we might rather consider a fix of this behavior in openhab-core).
