### ISSUE TITLE
[groheondus] Add support for GROHE BLUE HOME device

### ISSUE THREAD

**Issue by Sprocket02** [openhab/openhab2-addons#5513]
Is it possible to add the support for [GROHE BLUE HOME](https://www.grohe.de/de_de/kueche-kollektion/kuechenarmaturen-grohe-blue-home.html) device?

**Comment by Sprocket02** [comment]
Is it possible to at the support for [GROGE BLUE HOME](https://www.grohe.de/de_de/kueche-kollektion/kuechenarmaturen-grohe-blue-home.html) device?

**Comment by Sprocket02** [comment]
Is it possible to add the support for [GROHE BLUE HOME](https://www.grohe.de/de_de/kueche-kollektion/kuechenarmaturen-grohe-blue-home.html) device?

**Comment by davidgraeff** [comment]
This is not the place for questions, I'm afraid. Please ask this question in out community forum at community.openhab.org, thanks.
