### ISSUE TITLE
old logback config files

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab2-addons#553]
Do we still need this files for the Eclipse IDE?
* logback.xml
* ogback_debug.xml

The files are added to the karaf runtime (runtime/etc/).

**Comment by kaikreuzer** [comment]
No, I think we don't. I actually wanted to remove them already with my log PR, but I missed to do so.

**Comment by kaikreuzer** [comment]
But wait - we should maybe move them somewhere for the IDE launch config to pick it up!

**Comment by dvanherbergen** [comment]
How about changing to pax-logging-logback? The left truncated class names are a real pain and displaying the full package and class names also doesn't make things more readable.
And personally, I always liked having a dedicated log config for running in debug mode.

**Comment by maggu2810** [comment]
FYI #384

**Comment by kaikreuzer** [comment]
solved in https://github.com/openhab/openhab-distro
