### ISSUE TITLE
[Mail] Warning when sending mail

### ISSUE THREAD

**Issue by clinique** [openhab/openhab2-addons#5530]
This is just a warning, mail are correctly sent but wanted to mention it : 
`2019-05-01 10:27:42.267 [WARN ] [javax.mail                          ] - expected resource not found: /META-INF/javamail.default.address.map
`

**Comment by J-N-K** [comment]
Can you try https://janessa.me/org.openhab.binding.mail-2.5.0-fe.jar?

**Comment by clinique** [comment]
@J-N-K  : the link seems broken

**Comment by J-N-K** [comment]
Updated.

**Comment by clinique** [comment]
Error raised when installing the JAR : 
`2019-05-02 17:03:30.431 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/usr/share/openhab2/addons/org.openhab.binding.mail-2.5.0-fe.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.mail [294]
  Unresolved requirement: Import-Package: javax.mail; version="[1.6.0,2.0.0)"
`

**Comment by J-N-K** [comment]
Which version of OH are you running!

**Comment by clinique** [comment]
Updated recently : openHAB 2.5.0 Build #1583

**Comment by J-N-K** [comment]
`bundle: install mvn:com.sun.mail/javax.mail/1.6.2`

Not so nice that we have to install dependencies manually now.

**Comment by clinique** [comment]
I had to add also 
`bundle:install mvn:org.apache.commons/commons-email/1.5`
...but unfortunately still the same warning message.

**Comment by J-N-K** [comment]
I have created another version. Link above is still correct.

**Comment by clinique** [comment]
Still the same WARN

**Comment by J-N-K** [comment]
I‘ll have a look at the weekend

**Comment by mhilbush** [comment]
@J-N-K Sorry to barge in on this issue, but I think my question is relevant given the above discussion. OTOH, if you'd prefer that I open a separate issue, let me know.

In order to run this binding from the addons directory, exactly which 3rd party jars need to be dropped in addons? I added the following, but I can't get the smtp action to work.
```
http://central.maven.org/maven2/org/apache/commons/commons-email/1.5/commons-email-1.5.jar
http://central.maven.org/maven2/com/sun/mail/javax.mail/1.6.2/javax.mail-1.6.2.jar
```

In the console, I can see that the binding is active.
```
openhab> list -s | grep mail                                                                            
282 │ Active   │  80 │ 2.5.0.201905040410     │ org.openhab.binding.mail
285 │ Active   │  80 │ 1.6.2                  │ com.sun.mail.javax.mail
286 │ Active   │  80 │ 1.5.0                  │ org.apache.commons.email
```

And, I'm able to create a mail SMTP Server thing.

In my rule, I put this.
```
    val mailActions = getActions("mail","mail:smtp:mymailserviceprovider")
    mailActions.sendMail("me@me.com", "Test from mail binding", "This is the mail content.")
```

However, when my rule runs, I get this.
```
2019-05-04 12:46:57.249 [ERROR] [ntime.internal.engine.RuleEngineImpl] - Error during the execution of startup rule 'Test Rule': Instance is not SendMailActions class.
```

> Not so nice that we have to install dependencies manually now.

Amen to that! Hunting around for what to install is nasty, especially the trial and error to find all the additional dependencies. It's even much worse if the jars are not already OSGI-ified

**Comment by J-N-K** [comment]
@mhilbush, this is totally different. I would suggest a different issue. The bundles are ok. It seems that for some reason `getActions` is not returning the correct instance. Which is somewhat suprising.

**Comment by mhilbush** [comment]
Ok, thanks. I'll open a separate issue.

**Comment by J-N-K** [comment]
I did a lot of tests today and I think after tring every solution in OSGi-environments seems to be to set the log-level of javax.mail to ERROR. This needs to be done in openhab-distro.
