### ISSUE TITLE
[Mail] Unable to define thing via file - error in syntax

### ISSUE THREAD

**Issue by clinique** [openhab/openhab2-addons#5531]
I suspect there is a syntax collision when defining channels via .things file on the keyword "type".
I copy /pasted the definition coming from the [documentation](https://www.openhab.org/addons/bindings/mail/) : 
```
Thing mail:imap:neo "Neo IMAP" @ "System" [ hostname="blblabla", security="SSL", username="user", password="pass", port=993 ] {
    Channels:
        Type mailcount : inbox_total [ 
            folder="INBOX" type="TOTAL"
        ]
}
```
but it leads to this error : 
`2019-05-01 10:44:56.399 [WARN ] [el.core.internal.ModelRepositoryImpl] - Configuration model 'mail.things' has errors, therefore ignoring it: [5,28]: mismatched input 'type' expecting ']'
[7,39]: mismatched input '[' expecting ':'
[10,1]: extraneous input '}' expecting EOF
`
When I comment out `type="TOTAL"` it works fine.

**Comment by J-N-K** [comment]
there is a `,` missing between folder and type

**Comment by clinique** [comment]
Good catch, not well awaken this morning. Documentation PR submitted.
