### ISSUE TITLE
[Mail] Imap connection issue

### ISSUE THREAD

**Issue by clinique** [openhab/openhab2-addons#5537]
I created an imap thing using the documentation, tested either TLS or SSL but I get these infos in the log : 
`2019-05-02 18:33:11.581 [INFO ] [inding.mail.internal.POP3IMAPHandler] - error when trying to refresh IMAP: No login methods supported!
2019-05-02 18:33:33.227 [INFO ] [inding.mail.internal.POP3IMAPHandler] - error when trying to refresh IMAP: Connection dropped by server?
`

On server side  I find many lines : 
`May  2 18:33:11 serveur-1 dovecot: imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=xx.xx.xxx.xxx, lip=yy.yy.yy.yyy, session=<8J+iMOqH9DklR+i2>
May  2 18:33:33 serveur-1 dovecot: imap-login: Disconnected: Inactivity (no auth attempts in 180 secs): user=<>, rip=xx.xx.xxx.xxx, lip=yy.yy.yy.yyy, TLS handshaking, session=<2/7qMeqHsp8lR+i2>
`
Using the same mailbox with Thunderbird, I see that mailboxes access are configured with STARTTLS and could need non encrypted password.

**Comment by clinique** [comment]
Yes, just tried also with PaperUI

Envoyé de mon iPhone

**Comment by J-N-K** [comment]
That works for me. Can you show the configuration?

**Comment by clinique** [comment]
![image](https://user-images.githubusercontent.com/3328789/57142980-1da3d200-6dbe-11e9-8f9b-24536cbb4a67.png)

**Comment by J-N-K** [comment]
You should be able to configure the port. I‘ll have a look why this is not possible. I guess the port is wrong.

**Comment by clinique** [comment]
yes, I did this, but on Thunderbird, that works properly, they are either configured in SSL on 993 or on STARTTLS on 143.
