### ISSUE TITLE
[rfxcom] Lighting5/LightwaveRF Shutter support

### ISSUE THREAD

**Issue by thigger** [openhab/openhab2-addons#5539]
Lighting5 (LightwaveRF) Shutter items are supported in the v1 binding but not in v2 - is there any chance they could be added?

The relevant commands are OPEN_RELAY, CLOSE_RELAY and STOP_RELAY

The relay I'm using will work as a "switch" item (on/off) but there's no way to stop the blind in an intermediate position by disconnecting both terminals (stop_relay)

Thanks!

**Comment by martinvw** [comment]
Yes it can be added, but its a little bit tricky, see also problems we have at https://github.com/openhab/openhab2-addons/issues/4633

**Comment by thigger** [comment]
Cheers - shame; I've just bought a fire with thermostat3 controls too! My (fairly naive) vote would be for exposing multiple channels for the Thing, though I appreciate the binding would end up having to update secondary channels when one changes.

**Comment by martinvw** [comment]
> Cheers - shame; I've just bought a fire with thermostat3 controls too! My (fairly naive) vote would be for exposing multiple channels for the Thing, though I appreciate the binding would end up having to update secondary channels when one changes.

I'll try to make some time for this, unfortunately there isn't that much of that (time) left these days ;-)

**Comment by martinvw** [comment]
> Cheers - shame; I've just bought a fire with thermostat3 controls too! My (fairly naive) vote would be for exposing multiple channels for the Thing, though I appreciate the binding would end up having to update secondary channels when one changes.

I made some serious progress here, I have a busy weekend but hope to be able to wrap this up next week :-)

**Comment by martinvw** [comment]
[org.openhab.binding.rfxcom-2.5.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab2-addons/files/3356362/org.openhab.binding.rfxcom-2.5.0-SNAPSHOT.jar.zip)

Given this release you should be able to handle it given: Lighting5CommandString.sendCommand("OPEN_RELAY")
