### ISSUE TITLE
[harmony] Hub does not send a keystroke to the current activity

### ISSUE THREAD

**Issue by MisterBJ** [openhab/openhab2-addons#5540]
I would like control (volume, channel, etc.) with the current activity.

Quote from doc:

> **Hubs can also send a button press to a device associated with the current activity**. A String item can be used to send any button name/label or a Player item can be used to send Play/Pause/FastForward/Rewind/SkipForward/SkipBackward. This mimics the physical remote where buttons are mapped differently depending on which activity is running.
For example the play button may be sent to a DVD player when running a "Watch DVD" activity, or it may be sent to a AppleTV when running a "Watch Movie" activity.

But when I create an item with the following channel openHAB responds to the event but nothing is sent to the hub:
`String  harmony_HubWohnzimmer_ButtonPress
              "harmony Remote"
              { channel="harmonyhub:hub:Wohnzimmer:buttonPress" }`

My output from Kara konsole by using the item:
`20:07:31.532 [INFO ] [smarthome.event.ItemCommandEvent     ] - Item 'harmony_HubWohnzimmer_ButtonPress' received command DirectionDown`
`20:07:31.564 [INFO ] [arthome.event.ItemStatePredictedEvent] - harmony_HubWohnzimmer_ButtonPress predicted to become NULL`

I use openHAB 2.4.0 Release Build.

Best regards,
Björn

**Comment by wborn** [comment]
That functionality was added in https://github.com/openhab/openhab2-addons/pull/4972 which is only available in 2.5.0-SNAPSHOT. The website shows the documentation of the snapshot release and not the latest stable release. 

You can switch to the docs for 2.4.0 in the top right corner:

![docs](https://user-images.githubusercontent.com/12213581/57101817-52fae200-6d22-11e9-8bb8-d509dfec2381.png)

**Comment by MisterBJ** [comment]
Ah okay. Thanks for the information, I had not noticed. Many Thanks.
