### ISSUE TITLE
[mail] Error is rule when using sendMail action

### ISSUE THREAD

**Issue by mhilbush** [openhab/openhab2-addons#5556]
I'm having trouble getting the sendMail action to work in a rule.

I'm running this binding from the addons directory. These are the 3rd party jars I dropped in addons in order to resolve the dependencies
```
http://central.maven.org/maven2/org/apache/commons/commons-email/1.5/commons-email-1.5.jar
http://central.maven.org/maven2/com/sun/mail/javax.mail/1.6.2/javax.mail-1.6.2.jar
```

In the console, I can see that the binding is active.
```
openhab> list -s | grep mail                                                                            
282 │ Active   │  80 │ 2.5.0.201905040410     │ org.openhab.binding.mail
285 │ Active   │  80 │ 1.6.2                  │ com.sun.mail.javax.mail
286 │ Active   │  80 │ 1.5.0                  │ org.apache.commons.email
```

And, I'm able to create a mail SMTP Server thing.

As described in the documentation, I put this in my rule.
```
    val mailActions = getActions("mail","mail:smtp:mymailserviceprovider")
    mailActions.sendMail("me@me.com", "Test from mail binding", "This is the mail content.")
```

However, when my rule runs, I get this.
```
2019-05-04 12:46:57.249 [ERROR] [ntime.internal.engine.RuleEngineImpl] - Error during the execution of startup rule 'Test Rule': Instance is not SendMailActions class.
```

I added a logInfo to the rule.
```
    val mailActions = getActions("mail","mail:smtp:mymailserviceprovider")
    logInfo("test", "mailActions: {}", mailActions.class)
    mailActions.sendMail("me@me.com", "Test from mail binding", "This is the mail content.")
```

With this result.
```
2019-05-04 13:18:41.327 [INFO ] [.eclipse.smarthome.model.script.test] - mailActions: class org.openhab.binding.mail.action.SendMailActions
2019-05-04 13:18:41.327 [ERROR] [ntime.internal.engine.RuleEngineImpl] - Error during the execution of startup rule 'Test Rule': Instance is not SendMailActions class.
```

**Comment by mhilbush** [comment]
After a restart of openHAB, it's now sending the email, but I'm getting this in the log, which I think is the same as the other issue.

```
2019-05-04 13:38:59.390 [WARN ] [javax.mail                          ] - expected resource not found: /META-INF/javamail.default.address.map
```

A possible explanation for the error I originally reported... I had removed the OH1 mail action before installing the new mail binding. I suspect there were some artifacts remaining in memory from the OH1 action that were causing the error? The restart must've cleared those.

If you agree with the above, I can close this issue.

**Comment by J-N-K** [comment]
Maybe. I have never seen that and the error above is not really an error but - IMO - a bug in javax.mail. Because the file IS present (at least in the jar linked in the other thread) and also in the javax.mail bundle itself.

**Comment by maffi91** [comment]
Hey guys, any ideas to fix the warn? I get the same warning with every mail .. :S
[WARN ] [javax.mail                          ] - expected resource not found: /META-INF/javamail.default.address.map

openhab-distro  : 2.5.0

openhab> list -s | grep mail
256 x Active x  80 x 1.6.2                   x com.sun.mail.javax.mail
257 x Active x  80 x 2.5.0                   x org.openhab.binding.mail
