### ISSUE TITLE
Consistent Bunde naming

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab2-addons#5571]
The project names are not very constistent. E.g.

- `org.openhab.io.mqttembeddedbroker`  is named `openHAB Add-ons :: Bundles :: IO :: MQTT Broker Moquette` while `org.openhab.io.homekit` is named `openHAB Add-ons :: Bundles :: Homekit` and not `openHAB Add-ons :: Bundles :: IO :: Homekit`
- `org.openhab.extensionservice.marketplace` is named `openHAB Add-ons :: Extension Service :: Eclipse IoT Marketplace` why is `org.openhab.transform.exec` named `openHAB Add-ons :: Bundles :: Exec Transformation Service` and not `openHAB Add-ons :: Transformation Service :: Exec`

My suggestion would be:

- omit "Bundles" at all
- use "Binding", "Extension Service", "IO", "Transformation Service", "Persistence Service" and "Integration Tests"

@openhab/2-x-add-ons-maintainers, WDYT?

**Comment by maggu2810** [comment]
The WebUI repository has not been migrated by me.
IMHO all repos should use the same scheme for group ID, artifact ID and project name.

**Comment by maggu2810** [comment]
The openHAB WebUI repository has not been migrated by me.
IMHO all repos should use the same scheme for directories, group IDs, artifact IDs, bundle names, etc.

**Comment by J-N-K** [comment]
So what would you prefer?

1. `openHAB Add-ons :: Transformation Service :: Exec`
2. `openHAB Add-ons :: Bundles :: Transformation Service :: Exec`
3. `openHAB Add-ons :: Bundles :: Transformation Service Exec`
4. `openHAB Add-ons :: Bundles :: Exec Transformation Service`

I would vote for 2. We should also discuss what features should be named. We have similar "problems" there:

- `openhab-binding-airvisualnode`  - `org.openhab.binding.airvisualnode` (ok from my POV)
- `openhab-misc-market` - `org.openhab.extensionservice.market`
- `openhab-misc-homekit` - `org.openhab.io.homekit` 
- `openhab-io-javasound` - `org.openhab.io.javasound`
- `openhab-transport-modbus` - `org.openhab.transport.modbus`
- `openhab-transformation-exec` - ` org.openhab.transformation.exec`

**Comment by maggu2810** [comment]
I would vote for 2 for the bundle name, too.

**Comment by davidgraeff** [comment]
2
