### ISSUE TITLE
VSCode/gitignore

### ISSUE THREAD

**Issue by tmrobert8** [openhab/openhab2-addons#5693]
We need to add .vscode (used by visual studio code) to the gitignore.  

HOWEVER - the question becomes, what needs to be added to the gitignore?  

Seems we can go two ways:
1. Just added ```**/.vscode" to ignore all vscode settings
2. Go with the recommendation from [github vscode](https://github.com/github/gitignore/blob/master/Global/VisualStudioCode.gitignore) that will exclude everything but the important vscode files (like tasks.json, settings.json, etc), 

We should go with 1 if we want the addons directory as IDE neutral as possible (although we already are blowing that since we have .classpath and .project in it).

We should go with 2 if we want to make it easier for developers (because they won't need to recreate those files everytime).

Not sure what the right direction is here...

Related to: https://github.com/openhab/openhab2-addons/issues/5670

**Comment by Cossey** [comment]
I’ve switched to using VSCode as my IDE for add-ons dev now that its a viable option. I vote that method 1 should be considered. I customize the tasks file in my case to my specific environment when working on the add-ons I have interest in. whilst the other option would be beneficial to first timers; they can easily follow the guides to add the defaults.

**Comment by tmrobert8** [comment]
Agreed - I went ahead and added it with option 1

**Comment by tmrobert8** [comment]
Merged
