### ISSUE TITLE
[buienradar] Incorrect lat/lon format results in unnecessary redirects when fetching forecast data

### ISSUE THREAD

**Issue by shutterfreak** [openhab/openhab2-addons#5745]
The buienradar widget makes use of the following web service URI: `gpsgadget.buienradar.nl/data/raintext?lat=XX.XXXXX&lon=YY.YYYYY`

When manually fetching the forecast info, I noticed that the web service redirects to (lat, lon) coodinates with 2-digit precision, i.e.: `gpsgadget.buienradar.nl/data/raintext?lat=XX.XX&lon=YY.YY`

This may explain why the buienradar binding frequently misses out on fetching forecast info.

Discussion at OH Community: https://community.openhab.org/t/buienradar-binding-store-lat-lon-with-2-digit-precision/76632
 
## Expected Behavior
Avoid the redirect by constructing the URI with 2-digit precision for lat/lon.

## Current Behavior
Currently lat/lon are provided with 8-digit precision, see **BuienradarPredictionAPI.java**, line 131:
```
    @Override
    public List<Prediction> getPredictions(PointType location) throws IOException {
        final String address = String.format(Locale.ENGLISH, BASE_ADDRESS + "?lat=%.8f&lon=%.8f",
                location.getLatitude().doubleValue(), location.getLongitude().doubleValue());
```

## Possible Solution

Edit the `address` definition as follows:
```
        final String address = String.format(Locale.ENGLISH, BASE_ADDRESS + "?lat=%.2f&lon=%.2f",
```
## Workaround

Provide the location info with 2-digit precision in the binding config (may still yield redirects due to floating point conversion / accuracy).

## Steps to Reproduce (for Bugs)
Perform the HTTPS request by hand, e.g. with `wget -O - https://gpsgadget.buienradar.nl/data/raintext...` and confirm the redirect.

## Context
The buienradar binding very frequently times out. It expect a response within 3000 ms. If an avoidable redirect can be removed, (1) the binding will less frequently time out and (2) the buienradar web API will be less hammered.

## Your Environment
OH2.5.0 snapshot build S1601 on RPi3B+ with OpenHABian.

**Comment by justClouds** [comment]
I can confirm that the timeouts become rare with this changed Lang./Lat. format.
