### ISSUE TITLE
OpenHAB REST API seems to redirect to amazonechocontrol binding if fields are specified for /rest/items

### ISSUE THREAD

**Issue by gramineo** [openhab/openhab2-addons#5803]
It appears that if I try to use the REST API for items and specify any list of fields, the data that is returned seems to be a callout to https://alexa.amazon.com instead of my openHAB server. Without any fields specified, I get exactly what I expect.

I can use this command to successfully get a very long list of items from my openHAB server:

curl -X GET --header "Accept: application/json" "http://127.0.0.1:8080/rest/items?recursive=false"

However, if I add '&fields=editable':

curl -X GET --header "Accept: application/json" "http://127.0.0.1:8080/rest/items?recursive=false&fields=editable"

I get the following output:

{"error":{"message":"GET url \u0027https://alexa.amazon.com/api/behaviors/entities?skillId\u003damzn1.ask.1p.music\u0027 failed: Bad Request","http-code":500,"exception":{"class":"org.openhab.binding.amazonechocontrol.internal.HttpException","message":"GET url \u0027https://alexa.amazon.com/api/behaviors/entities?skillId\u003damzn1.ask.1p.music\u0027 failed: Bad Request","localized-message":"GET url \u0027https://alexa.amazon.com/api/behaviors/entities?skillId\u003damzn1.ask.1p.music\u0027 failed: Bad Request"}}}

I do have the Amazon Echo Control Binding enabled on my openHAB server. It doesn't matter which field(s) I try to specify to get items from the REST API, I always get a result which details bad requests to alexa.amazon.com. Without any fields specified, it works correctly.

The contents of my /var/lib/openhab2/etc/version.properties file contains:
openHAB Distribution Version Information
----------------------------------------
build-no        : Release Build
online-repo     : https://dl.bintray.com/openhab/mvn/online-repo/2.4

Repository        Version
----------------------------------------
openhab-distro  : 2.4.0
smarthome       : 0.10.0.oh240
openhab-core    : 2.4.0
openhab1-addons : 1.13.0
openhab2-addons : 2.4.0
karaf           : 4.2.1

**Comment by kaikreuzer** [comment]
This seems to be an issue with the Alexa Control binding, I have therefore moved this issue to the openhab2-addons repo.
@mgeramb Could you analyse/comment?

**Comment by mgeramb** [comment]
Hi, this is a known issue in the 2.4 version because there was a dynamic state provider which have made a lookup. Please use the beta version from here: https://community.openhab.org/t/released-openhab2-amazon-echo-control-binding-controlling-alexa-from-openhab2/37844 (This should be save, this beta is a stable one). Or update to openHAB 2.5 snapshot build, but this could be a dangerous because it's a developer build.

**Comment by mgeramb** [comment]
@kaikreuzer Please close this issue. See my comment above.

**Comment by kaikreuzer** [comment]
Thanks for your extremely quick answer, @mgeramb!
