### ISSUE TITLE
non riesco ad installare scs/bus bticino

### ISSUE THREAD

**Issue by Francescobrt** [openhab/openhab2-addons#5838]
## Your Environment

* Version used: (e.g., openhab and addon versions)
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):

**Comment by Hilbrand** [comment]
English please. If you have problems installing bindings first try the openhab forum https://community.openhab.org and report here if you have found a bug.
