### ISSUE TITLE
[chromecast] Chromecast library spams log file with errors

### ISSUE THREAD

**Issue by mhilbush** [openhab/openhab2-addons#5873]
I see this Chromecast API error repeatedly in the openHAB log.
```
2019-07-30 09:32:31.250 [WARN ] [su.litvak.chromecast.api.v2.Channel ] - Error while handling, caused by java.lang.NullPointerException
```

It's due to a bug in how the `chromecast-java-api-v2` is handling MEDIA_STATUS messages. See [here](https://github.com/vitalidze/chromecast-java-api-v2/issues/113). Once the fix is included in a release, I'll submit a PR to bump the library version.

**Comment by cweitkamp** [comment]
@mhilbush Thanks for taking care of. I assigned you to this issue.

**Comment by cweitkamp** [comment]
@mhilbush New version of `su.litvak.chromecast` has been released. As I was on it too, I submitted a version bump (see #5989).

**Comment by cweitkamp** [comment]
Yes, it is because of #5949 which is kind of critical.
