### ISSUE TITLE
[mqtt] sendCommand to read-only channel silently ignored

### ISSUE THREAD

**Issue by lsiepel** [openhab/openhab2-addons#5880]
**Current Behavior**
When a mqtt channel is not provided with a commandTopic it is markes as read-only. Calling  sendCommand from a rule on a read-only channel will try to update the binding and the binding immediate (< 1 ms) send the old value back to the channel again.

**Expected Behavior**
1. Add a `WARN` message to the openhab.log that you are trying to write to a read-only channel. 
2. Add minor clarification to documentation that read-only channel means that sendCommand won't work while postUpdate does.

**Steps to Reproduce**
1. Create a MQTT bridge with an item that only has stateTopic:
```
Bridge mqtt:broker:lplxvibroker "Bridge Label" [host="192.168.1.10", port=1883, secure="OFF",retainMessages=false] {
    Thing topic slimmemeter "MQTT Slimmemeter" {
        Channels:
        Type number : stroom_in_stand_laag      "Meterstand in laag"    [ stateTopic="/lplxvi/meterkast/stroom/in/laag" ]
	}
}
```
2. Create item:
```
Number	verd0_meterkast_stroom		"Meterstand in laagtarief"		    <energy>	{ channel="mqtt:topic:lplxvibroker:slimmemeter:stroom_in_stand_laag"}
```
3. Setup rule and trigger it:
```
rule  "test rule"
when
    Item virtual_switch changed
then
    verd0_meterkast_stroom.sendCommand(12.3)   
end
```
4. The event.log would contain something like:
```
2019-08-01 23:24:38.850 [vent.ItemStateChangedEvent] - verd0_meterkast_stroom_in_laag changed from UNDEF to 12.3
2019-08-01 23:24:38.851 [vent.ItemStateChangedEvent] - verd0_meterkast_stroom_in_laag changed from 12.3 to UNDEF
```

**Context**
Was troubleshooting some other bug and just used sendCommand not realizing that it won't work for read-only channels. Costing me several hours to move to realise i had to use  postUpdate.

**Workaround**
n/a

**Environment**
openHAB build #1651

**Comment by Rossko57** [comment]
Comment; it is permissible to have multiple channels linked to an Item, any of which may be "read-write", "read-only", or "write-only" so far as each channel is concerned.
A channel should not assume any "unexpected" events are any kind of problem.

To further complicate this area, a few bindings (including MQTT) can issue commands and/or respond to event bus state updates, so nothing can be assumed about whether a command/update should be viewed as "inbound"/"outbound" ("read/write") either.

Silently ignoring commands or state updates for which a channel/Thing/binding is not configured is the desired behaviour.

**Comment by lsiepel** [comment]
I still think it is good to log a WARN message and clarify the documentation. It won't change the way everything works, it just helps people setup and troubleshoot these problems.

If silently ignoring the command is the desired way, why is the binding sending the old state again? If it would be truely silent, it would just do nothing (like a postUpdate). By sending the old state again it could interfere with the other item bound channels.

**Comment by J-N-K** [comment]
I agree with @Rossko57. If at all, log a TRACE level

**Comment by lsiepel** [comment]
Oke, it took me hours to find out what the problem was in my use case. With little help from the system it could have saved me hours. If nobody feels that the system should tell the user they do something wrong (that is not that obvious), i'll close the issue.

**Comment by Rossko57** [comment]
It's not that you did something wrong.  The issue is not about channel configuring or read/write capabilities.  It looks to me that the binding is doing the wrong thing by issuing an UNDEF update.

As you correctly note, your channel is "read only" and shouldn't be responding to any commands in any way (well, with the exception of REFRESH maybe).

Your observed problem is real, but the fix is not messages or docs.

**Comment by davidgraeff** [comment]
The binding is not executing a channel command without a command topic. That is the desired behavior. Current values are reflected because of the OH core autoupdate feature I assume. So I do not see the problem that is reported here?

> Was troubleshooting some other bug and just used sendCommand not realizing that it won't work for read-only channels. Costing me several hours to move to realise i had to use postUpdate.

Maybe the main documentation can be improved? That is not mqtt specific.

**Comment by Rossko57** [comment]
> The binding is not executing a channel command without a command topic. That is the desired behavior.

Absolutely.   I fully accept your analysis is correct, the observed issue is really about the postUpdate produced by autoupdate, following on from the command.

I still think UNDEF is the wrong response to _that_, but it's being dealt with in https://github.com/openhab/openhab2-addons/issues/5879

**Comment by J-N-K** [comment]
Isn't https://github.com/openhab/openhab2-addons/blob/1d1cdbe8f238b740159fd691ad5118e68923bfdf/bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelState.java#L336-L341 what is requested here? And 'DEBUG' seems to be the correct log level for that.

**Comment by lsiepel** [comment]
I couldn't find any good documentation on logging level and definitions, so i believe you if `DEBUG` is the right level. I hoped it could be set to `INFO ` as `WARN `might be too much. A lot has to go wrong before a user (if ever) decides to set the MQTT binding into DEBUG logging.

**Comment by Rossko57** [comment]
Just to repeat, a command arriving at a read-only channel is not "something stupid".
Items can have multiple linked channels - it's not unusual.
Commands to an Item are distributed to all linked channels ; none or one or more may be configured to act on command.  It is expected that read-only channels silently ignore.
It is even perfectly legitimate to send a command to an Item with no "write" channels at all, and have a rule trigger on it, or simply let autoupdate do its thing.
It's not an exception, it's not a fault, it's not an error.

To be clear, I see no issue with DEBUG reporting ignored commands.

**Comment by lsiepel** [comment]
Thanks for looking into this, the 'UNDEF' discussen is done elsewhere. #5879
