### ISSUE TITLE
Not able to control echo using binding

### ISSUE THREAD

**Issue by daksh1305** [openhab/openhab2-addons#5887]
Hi, 

I am trying to control my echo device using openhab but i am unable to do so. Does the binding support amazon.in accounts i am from india .The account gets linked but i am unable to control my echo device.

Can anyone help me with this please

**Comment by openhab-5iver** [comment]
Assuming you're talking about the amazonechocontrol binding, it's best to ask in the forum. There's a thread for it... https://community.openhab.org/t/released-openhab2-amazon-echo-control-binding-controlling-alexa-from-openhab2/37844.

**Comment by daksh1305** [comment]
Thank you openhab-5iver will do that
