### ISSUE TITLE
OH 2.5M2: no initial load of status of knx items at startup anymore

### ISSUE THREAD

**Issue by logos37** [openhab/openhab2-addons#5920]
Since updating to 2.5. M2 states of knx items are not loaded at startup anymore. Did I do a mistake or is it a bug?

Thanks for any hints…

**Comment by Alex5719** [comment]
Seems to be related to issue #5916

**Comment by nanosonde** [comment]
I guess this issue should also be solved by https://github.com/openhab/openhab2-addons/pull/5938.
