### ISSUE TITLE
Adapt Milight binding for openhab2

### ISSUE THREAD

**Issue by cschneider** [openhab/openhab2-addons#593]
I recently bought some milight lamps and would be interested in using them in openhab2 natively. 

Does anyone already work on a milight binding for openhab2? If not I am willing to work on it.

**Comment by hakan42** [comment]
The 1.x binding works pretty fine for me in my OH2 installation.

**Comment by cschneider** [comment]
Yes. It works using the compat layer. As far as I understood the goal is to move the bindings over to pure openhab2. Is it too early for this?

**Comment by kaikreuzer** [comment]
If the openHAB 1 version works well, there isn't really much pressure to port it to openHAB 2, since the "old" bindings will continue to be supported. So unless discovery is a much wished feature for the Milight binding, it is probably not worth spending the effort at the moment.

**Comment by hmerk** [comment]
I absolutely agree to @hakan42 and @kaikreuzer ,  the binding works fine with openHAB 2.0, so there is no preasure or porting it.
On the other hand, I already started thinking on porting it, as there are questions on item definitioans every now and again. I am trying to evolve a way to prevent such questions by having clear definitions for the different LED light types in combination with auto discovery ofthe bridge (and it's version).
@cschneider might be a good idea to join forces on this, but as said, with a very low priority.
Best
Hans-Jörg

**Comment by monnimeter** [comment]
Maybe the support for Milight is something which could be simply added to the OH2 wifi led binding, see #496 and PR #513...

**Comment by cschneider** [comment]
I agree that it is not urgent to convert the milight binding to openhab2. Especially as it would create two source trees that have to be maintained. So probably the best solution is to wait until openhab 2 is out and then switch active development to it at some point. @hmerk let me know when you want to do this and I will try to help out. Have you already looked into the possibilities for auto discovery? 

@monnimeter I will look into the wifi led binding code. If it is similar enough then merging the code might be a good idea.

**Comment by hmerk** [comment]
@cschneider there is a autodiscovery for the newer bridge Versions (> V3.0), so I will give it a try to see if this also works with the older versions.

If autodiscovery could be achieved for all MiLight bridge Versions, we indeed coud have a combinded binding. Just need seperate LightHandler for different BridgeTypes.

**Comment by davidgraeff** [comment]
I added a merge request for a new milight binding implementation for OH2 where the binding itself or parts of it can be of any use. I separated the protocol from the binding boilerplate so it may be reused in the Wifi led binding. #666 

I have some concerns though: I do not thing it is that clever to merge all kind of vendors and protocols into one binding, so I'm not really sure if this fits into the Wifi led binding.

**Comment by davidgraeff** [comment]
@cschneider Could you test the new OH2 milight binding and update this issue? :)

**Comment by cschneider** [comment]
It will take a bit as I am currently on vacation but I will test it.

**Comment by mannes** [comment]
Not really working for milight rgbw bulbs on the current snapshot build #433 
Autodetects the bridge well, light controls don't seem to work at all. When i touch the controls they either turn off, turn red or (when turned off) randomly flash white (maybe 100ms). Also white/nightmode toggle are missing in paperUI

**Comment by hmerk** [comment]
@davidgraeff Could you please have a look at this issue and also #1131.

**Comment by mannes** [comment]
I have been trying with installing through paper, using through habmin has some better results.
+ on/off seems to work pretty well
- picking a color on the 'all' device often doesn't update all bulbs. I suspect the required delay between address and function message isn't long enough.
- No (functional) brightness setting or white/night mode.

is was looking at https://github.com/openhab/openhab2-addons/blob/c888d1804b52fc416587560561f41eeb2a0aef57/addons/binding/org.openhab.binding.milight/ESH-INF/thing/thing-types.xml and it seems to be lacking a definition for RGBW leds. There is thee types, White, RGB, RGBW (and maybe RGBWW? not sure about that). 

- White has on/off, brightness, nightmode, (colorTemperature)
- RGB on/off, brightness, color
- RGBW on/off, brightness, color, nightmode, white

not considering disco modes

It has been working before. but i can't get the 1.8.3 version to work OH2

**Comment by hmerk** [comment]
@mannes what errors do you face running the 1.8.3 version on OH2 ? As there is nothin special, it should work, at least it does here.

**Comment by mannes** [comment]
I've got the one 1.8.3 jar in the addons folder.

conf/services/milight.cfg
```
bridge1.host=192.168.1.210
bridge1.port=8899
```
conf/items/milight.items
```
Switch RGBW1    {milight="bridge1;7"}
Switch RGBW2    {milight="bridge1;8"}
Switch RGBW3    {milight="bridge1;9"}
Switch RGBW4    {milight="bridge1;10"}
```
conf/sitemaps/default.sitemap
```
sitemap default label="Main Menu" {
    Frame label="Lights" {
        Switch item=RGBW1
        Switch item=RGBW2
        Switch item=RGBW3
        Switch item=RGBW4
...
```
openhab log doesn't seem to say anything about milight, no error, but also no 'message sent' or anything

**Comment by davidgraeff** [comment]
@mannes 
* white/night mode isn't supposed to work with RGBW lights as far as I can remember (it is just not supported by the bulbs).
* sending a command to ALL bulbs is just one command to the bridge. The addon sends this just once, while the app is sending it repeatedly to make sure all bulbs receive it. Your bulbs aren't in proper range to the bridge, but we can imitate the behaviour of the app of course.
* Brightness is part of the color channel actually (color is encoded in HSB: Hue, Saturation, Brightness). I just was too lazy to also support an extra brigthness channel, but this can be added.

**Comment by davidgraeff** [comment]
@all: I just tested with the PaperUI. I do not use the thing definition file, but if the behaviour of those two differ from each other I consider this an OH or ESH bug

**Comment by mannes** [comment]
I've got RGBW bulbs with nightmode and white mode, supported by the remote and a variaty of apps and shellscripts. All of them behaving as they should, range isn't the problem.

I found this in the logs when using the 1.8.3
```
2016-08-09 00:25:11.813 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'milight.items'
2016-08-09 00:25:23.593 [DEBUG] [e.osgi.LoggingCommandSessionListener] - Executing command: 'log:display | grep milight'
2016-08-09 00:25:24.286 [DEBUG] [e.osgi.LoggingCommandSessionListener] - Command: 'log:display | grep milight' returned 'null'
2016-08-09 00:25:41.736 [DEBUG] [mpl.info.InfoBundleTrackerCustomizer] - Ignore incorrect info null provided by bundle org.openhab.binding.milight
2016-08-09 00:25:41.737 [INFO ] [g.apache.aries.spifly.dynamic.bundle] - Bundle Considered for SPI providers: org.openhab.binding.milight
2016-08-09 00:25:41.738 [INFO ] [g.apache.aries.spifly.dynamic.bundle] - No 'SPI-Provider' Manifest header. Skipping bundle: org.openhab.binding.milight
2016-08-09 00:26:27.287 [DEBUG] [e.osgi.LoggingCommandSessionListener] - Executing command: 'log:display | grep milight'
2016-08-09 00:26:27.708 [DEBUG] [e.osgi.LoggingCommandSessionListener] - Command: 'log:display | grep milight' returned 'null'
2016-08-09 00:27:11.067 [DEBUG] [ell.impl.action.osgi.CommandExtender] - org.openhab.binding.milight (207): Starting destruction process
2016-08-09 00:27:11.068 [DEBUG] [ell.impl.action.osgi.CommandExtender] - org.openhab.binding.milight (207): Not an extended bundle or destruction of extension already finished
2016-08-09 00:27:11.068 [DEBUG] [ell.impl.action.osgi.CommandExtender] - org.openhab.binding.milight (207): Starting destruction process
2016-08-09 00:27:11.069 [DEBUG] [ell.impl.action.osgi.CommandExtender] - org.openhab.binding.milight (207): Not an extended bundle or destruction of extension already finished
2016-08-09 00:27:11.071 [DEBUG] [ell.impl.action.osgi.CommandExtender] - org.openhab.binding.milight (207): Starting destruction process
2016-08-09 00:27:11.071 [DEBUG] [ell.impl.action.osgi.CommandExtender] - org.openhab.binding.milight (207): Not an extended bundle or destruction of extension already finished
```

**Comment by mannes** [comment]
```
SET COLOR TO WHITE (GROUP ALL)  0x42    100ms followed by:	0xC2
SET COLOR TO WHITE (GROUP 1)    0x45	100ms followed by:	0xC5
SET COLOR TO WHITE (GROUP 2)    0x47	100ms followed by:	0xC7
SET COLOR TO WHITE (GROUP 3)    0x49	100ms followed by:	0xC9
SET COLOR TO WHITE (GROUP 4)    0x4B	100ms followed by:	0xCB
```
http://www.limitlessled.com/dev/

**Comment by davidgraeff** [comment]
@mannes Could you open separate issues for each bug you encounter, please? Thanks for your findings, though. I've added a separate brightness channel for the rgbw leds and a switch channel for nightmode, too.

**Comment by mannes** [comment]
@davidgraeff thanks for the fast fix. do i have to build your repo to test it? or could you supply me with a jar?

**Comment by davidgraeff** [comment]
Just wait a few days for the changes to be applied to the main repository :) I'm traveling through NZ, so not beeing able to generate jars atm.

**Comment by Xento** [comment]
Would it be possible that you can add support for my version of the openmili sketch for arduino: https://github.com/Xento/openmili
It supports bidirectional communication, so when you control your lights with a remote you will receive the commands and you could change the state in openhab2.
I although wrote a node-js module (https://github.com/Xento/node-milight-rf24) and added support for it to the pimatic-led-light addon (https://github.com/Xento/pimatic-led-light)

**Comment by hmerk** [comment]
@Xento 
Sorry, but I would not suggest this as a good idea, as this is not about talking directly to the bridge.
If you like, feel free to create your own binding by refactoring the milight Binding and contribute it with its own name.

**Comment by davidgraeff** [comment]
@xento
I also thing this binding should focus on the milight product line. It's already complicated because of white, RGBW and RGB products and actually the protocol is not even pretty and doesn't allow full RGB color control

**Comment by Xento** [comment]
Yeah full RGB control is not possible, but it is possible to convert the color from a colorpicker to the commands used by the lights. It works pretty god in pimatic.
I will try to write an own binding for it. Maybe you could help me, when I have done the first steps, because I'm new to openhab ;-)

**Comment by sveco** [comment]
There is actually a whitemode command, that turns Milight on/off. Now the only way to turn it on, is to manually drag brightness slider. On/off switch does not turn it on or off. It sets the brightness to 100 when turned on, but bulb does not go on until I manually touch the slider. This manual config with previous version was working fine to turn it on/off:
Switch  Lamp_MiLight_White1  "Bedroom"   <light>         (LIGHT)     {milight="milight1;7;whiteMode"}
