### ISSUE TITLE
Add Sponsor button

### ISSUE THREAD

**Issue by wborn** [openhab/openhab2-addons#5948]
WDYT about adding a Sponsor button to this/all openHAB repos @openhab/2-x-add-ons-maintainers + @hmerk?

It's done by adding a funding file and enabling the right setting:
https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository#displaying-a-sponsor-button-in-your-repository

As a test I added such a file to my fork with the foundation and Bountysource URLs, see:
* https://github.com/wborn/openhab2-addons
* https://github.com/wborn/openhab2-addons/commit/91bbe6340a067513bd3645a12461fe727b04281f

If we create a `.github` repo we can also enable it on all the repositories globally:
https://help.github.com/en/articles/creating-a-default-community-health-file-for-your-organization

**Comment by martinvw** [comment]
I also like the part about the global files it would also be helpful for the security notes

**Comment by openhab-5iver** [comment]
[Github Sponsors](https://github.com/sponsors) would be interesting too, once it gets out of beta.

**Comment by hmerk** [comment]
I have to check the implications of sponsoring to our charity non profit state. AFAIK, this could bring us into trouble with german tax authorities.
Will come back later.
@wborn please remove it from your fork until I have checked.

**Comment by davidgraeff** [comment]
@hmerk The foundation and its goals (promotion of openHAB) are independent of the source code here on github that can be financed in any possible way, I assume? And the Smarthome days were sponsored as well the last years.

**Comment by martinvw** [comment]
the sponsor link just links to becoming a member of the foundation and a link to bountysource so nothing which would be conflicting I would think

**Comment by wborn** [comment]
Thanks for looking into it @hmerk! I've disabled the button again on my fork.

**Comment by hmerk** [comment]
> @hmerk The foundation and its goals (promotion of openHAB) are independent of the source code here on github that can be financed in any possible way, I assume? And the Smarthome days were sponsored as well the last years.

@wborn refered to the foundation, that‘s why I had concerns. If it´s just a link to the membership page, there are no tax implications with the foundation. Bountysource is absolutely fine.
Smart Home Days had an indirekt sponsoring, which was ok taxwise.

**Comment by wborn** [comment]
Yes all the Sponsor button would do is provide links to pages that already exist today. So it increases the discoverability of these ways to "Sponsor" openHAB.

The Bountysource link for sending money to openHAB may not be widely known. Would it be a viable option to "Sponsor" openHAB and could money received on it be spent on development?

**Comment by hmerk** [comment]
No, money donated to the foundation cannot be spent for development.
I understood bountysource as a way to donate money to issue directly.

**Comment by kaikreuzer** [comment]
I agree that the bountysource link is the best fit and imho it's fine to add it.

> But who will „manage“ the money?

@hmerk What do you mean by this? If you refer to Bountysource, that's their service that they take care of the money flow - we are not involved.

Wrt adding a link to the Foundation, I am a but undecided. Yes, the foundation does not sponsor any development, but it sponsors openHAB in other ways (events, etc.), so I don't think it would be wrong to list it there. If we only have the link to Bountysource, it might rather be misleading that this is the only way people can help the project financially, which is not correct. Having both links would show both sides of the medal. But that's just my 2 cents, if @hmerk does not feel good about it, it's fine for me to leave it away.

**Comment by wborn** [comment]
> we are not involved

People can also transfer money to openHAB directly using:

https://salt.bountysource.com/checkout/amount?team=openhab

They might get there when choosing the [openHAB team](https://salt.bountysource.com/teams/openhab) in Bountysource and click the Support button. 

When money is transferred this way it needs to be managed and the person who owns the account may need to pay taxes over it.

**Comment by hmerk** [comment]
@kaikreuzer what @wborn wrote is exactly what I meant. I that case, money is transfered to openHAB, not bound to an issue directly. So somebody has to decide which issue will get the money.

Regarding the Foundation listing, if it is just a link to our membership page, it's fine for me.

**Comment by kaikreuzer** [comment]
> I that case, money is transfered to openHAB

Actually, the money is still owned by Bountysource. Only if one does a cash out, it is considered income that is then tax relevant.
Anyhow, the Foundation has nothing to do with Bountysource and I am accessing the openHAB account as the project (development) lead of openHAB privately. I have never done and will never do a cash out from it, but assign the bounties to the most important issues. But there has hardly been any money on that account, and I think it makes more sense for people to put bounties on issues directly.

But I see your point @wborn, we do not have a good url to point to to explain people that they can put bounties on openHAB issues - and we would not want them to give money to the openHAB Bountysource account (as I think it is better given to the Foundation instead, since Bountysource does not seem to be very effective...). So it might hence be even the best solution to only add a link to the Foundation then. Wdyt?

**Comment by wborn** [comment]
> So it might hence be even the best solution to only add a link to the Foundation then.

I agree that would be the best solution for now until we have some page that explains in what other ways openHAB can be supported.

**Comment by wborn** [comment]
Can you create a `.github` project for [default files](https://help.github.com/en/articles/creating-a-default-community-health-file-for-your-organization) @kaikreuzer ? Then we can add the link in the FUNDING file.

Adding a SUPPORT file to this project with a link to the community forums would also help to reduce "support question issues".

**Comment by kaikreuzer** [comment]
This name looks pretty weird: https://github.com/openhab/.github

Feel free to add the suggested files to it - you have access (but best do it through PRs as on any other repo).
