### ISSUE TITLE
RFXcom binding not able to connect USB

### ISSUE THREAD

**Issue by nielsvanharen** [openhab/openhab2-addons#598]
When having more then 1 USB device connected on a RaspBerry Pi. The RFXcom binding seems to be unable to connect to the proper device. 

dev/ttyUSB0 - RFXCom connection by USB Serial
dev/ttyUSB1 - Mysensors Gateway.

creating udev rules, or connecting by serialid for both ports do not have any affect.

The following error occurs : RXTX fhs_lock() Error: opening lock file: /var/lock/LCK..mysensors: File exists. It is mine

removing this lock file does not resolve the issue, it is recreated when the other usb device (in my case the mysensors gateway ) is configured during startup, so it seems the rfxcom binding tries to get a status or even tries to connect to the other device

When only 1 device is registered in the openhab configuration, all seems to go well.
##

**Comment by buzink** [comment]
Have you tried running openhab as root? It solved a similar problem for me in Openhab 1 on the Pi.

    sudo /etc/init.d/openhab stop
    sudo /opt/openhab/start_debug.sh

**Comment by nielsvanharen** [comment]
I tried running as root, same results. The binding in Openhab 1 is working as expected.

**Comment by kaikreuzer** [comment]
@paulianttila Any idea?

**Comment by sachinacharya** [comment]
Even i got the same problem what is the solution.Please help me.

**Comment by paulianttila** [comment]
duplicate to #671

**Comment by martinvw** [comment]
If this problem is still around open a new issue or maybe even better ask around in the community forum
