### ISSUE TITLE
Issues with homie auto detection and configuration

### ISSUE THREAD

**Issue by backinabit** [openhab/openhab2-addons#6000]
1) When multiple nodes are defined on a single device, all of the properties are jumbled together as if only a single node was defined. According to homie specification, each node should be independent or logically separable;

https://homieiot.github.io/specification/#topology

For example, if I define a device called "HVAC", and give it 3 nodes called "Upstairs Thermostat", "Main Thermostat", "Basement Thermostat", then I should be able to identify and interact individually with each of the three separate thermostats, and it should be clear which one I am interacting with.

2) OpenHAB is unable to autodetect homie devices having a base-topic other than "homie". According to specification, controllers must by default auto-discover based on the wildcard topic "+/+/$homie", and restrict to a single base topic only if such is configured by the user.

https://homieiot.github.io/specification/#base-topic

3) This is more of an annoyance than a bug; OpenHAB orders properties alphabetically rather than as they are ordered by the device itself.

It would be more reasonable to order properties in the same order they are given in the $properties attribute.

4) Some "misbehavior" can be found with regards to the "$settable" attribute. When the $settable attribute is not included, the result is that the property may end up being either settable or not settable (I've seen it both ways, not certain if it is random or if there is a pattern). According to specifications, $settable has a default value of "false", so when the attribute is not set, it should be understood as if it was set, to false.

https://homieiot.github.io/specification/#property-attributes

**Comment by cweitkamp** [comment]
> Can someone please move this to openhab2-addons?

Sure. Done.

**Comment by boc-tothefuture** [comment]
We will need an example for your first issue.  Provide the output of the list of topics published.  
I have one device with many nodes with many individual properties and it is working ok for me.

You second issue is an RFE to support Homie 4.0.

**Comment by backinabit** [comment]
I appreciate the consideration, but I'm going to be going in a different direction than openHAB.
