### ISSUE TITLE
[squeezebox] Log is flooded with currentPlayingTime Logs

### ISSUE THREAD

**Issue by blilleike** [openhab/openhab2-addons#6022]
The default install log is set to INFO for all ItemStateChangedEvent

Each squeezebox_squeezeboxplayer logs a currentPlayingTime changed trigger every second on INFO level.

I would think this as a debug-logging at max as it is nothing to be used in typical rules or any configuration.
And a log-entry each second for maybe multiple players adds lots of unwanted noise in the log-files

Suggestion is to reduce log level to trace or debug for this entry.

**Comment by mhilbush** [comment]
This is a state change, which cannot be suppressed by changing the log level in the binding. You could unlink the item that's linked to the `duration` channel, which should cause the state change to not be logged.

**Comment by udo1toni** [comment]
Please see this posting https://community.openhab.org/t/how-to-set-a-item-log-level-to-warn-or-error-only/41284, there are different options to suppress single items logs.

**Comment by blilleike** [comment]
Yes, I learned about that. But it is kind of the wrong way around to have to adjust the log settings for a production system.

My point would then be to set the LogLevel of this unconfigurable ItemStateChangedEvent to Warn in the first place (or downgrade this loggings to debug).
An experienced user who learned about Logs and does want to use it can easily adjust logging level when needed.

Currently all basic users get unreadable logs by default that spam the sd-cards of typical installs on raspi with 4k lines per hour listening to music.

**Comment by mhilbush** [comment]
Did you try deleting the item that's linked to `currentPlayingTime`?

**Comment by blilleike** [comment]
This issue is not a personal problem. I know now how to handle that.
It is an issue on how default setup is handled for all users not willing to dive so deep.

**Comment by Hilbrand** [comment]
Yes this is a bit of an issue. I see the same happening with the Spotify binding. However this is not a specific binding issue and this discussion should best take place on opehab-core repo I think. Maybe report it there.

**Comment by udo1toni** [comment]
In fact, as `events.log` is to log all events, and a status change IS an event, yes, it's a very frequent event, but no, it's not an issue. just my opinion ;)

**Comment by mhilbush** [comment]
Not sure I understand why it's an issue, as I see several easy solutions:

- If you don't use `currentPlayingTime`, just don't link an item to that channel.

- If you use `currentPlayingTime`, and you don't want the entries in `events.log`, just filter those entries as described in the post above.

- Alternatively, if you're concerned about SD card life (which I agree is a real issue, as it's not a question of **if** the SD card will fail, but more a question of **when** it will fail), replace the SD card with an SSD.

**Comment by rkoshak** [comment]
This isn't completely on topic here, but does it make sense to have events.log turned on by default? Those who need it and find use in it can turn it on by editing the logger config or from the Karaf console. The rest of the users never look at it and it is a very chatty log, sometimes hundreds of entries per minute on some systems (without something like Squeeze box changing an Item every second).

I agree with the consensus here though. There would be no way to "fix" this problem without breaking the very purpose of events.log.

**Comment by blilleike** [comment]
I think, it is exactly on topic. 

> My point would then be to set the LogLevel of this unconfigurable ItemStateChangedEvent to Warn in the first place (or downgrade this loggings to debug).
An experienced user who learned about Logs and does want to use it can easily adjust logging level when needed.

Not in the code but in the log configuration of course. 
I opened an issue in core for this and will now close this one.

**Comment by rkoshak** [comment]
It's usually good practice to provide a link to the new issue when moving issues to a new repo.

And don't miss my statement. I think trying to change the logging level of these statements in events.log is a non-starter. You will not get anywhere with that. For those who use events.log, an item change event _is_ an INFO level event.

You might get somewhere by pursuing turning off events.log in the first place though. The entire log file, not just piece parts.

**Comment by blilleike** [comment]
I think I have provided links in both directions.
If this is still not clear, I will still comment on it in the new issue.
https://github.com/openhab/openhab-core/issues/1025
