### ISSUE TITLE
[tado] Request a Channel to be added for Battery Low indication

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab2-addons#6028]
I am using Tado thermostatic radiator valves(TRV) in my home. These devices are battery powered; and the Tado app will send notifications in my phone when the battery needs replacing. However the low battery warning is currently not available as a channel on the OH binding. Would it be possible to add a low battery (switch) channel to this binding please?

**Comment by Timtam** [comment]
yeah, would like this feature to be available as well.

**Comment by andrewfg** [comment]
Hi @Timtam, I have developed a solution myself already :) and there is a pull request to merge it into OH..

https://github.com/openhab/openhab2-addons/pull/6057#issuecomment-531878194
