### ISSUE TITLE
[Hue Binding] Doesn't find Ledvance Downlight OSRAM

### ISSUE THREAD

**Issue by lons81** [openhab/openhab2-addons#6037]
Hi
Great plugin but doesn't work correctly with the Phoscon Raspbee Gateway.

I have some Hue Lights, some Gledopto driver, Osram Plug these work all great,
but my Osram Ledvance Downlight would not be find... 10 of them...
In the Phoscon Gateway and Hue Essential on android they work fine.
Openhab with Hue binding will not find them.

So how can i help to find a solution?

Thanks, Marcel

**Comment by cweitkamp** [comment]
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1835.
