### ISSUE TITLE
Automate PR quality check

### ISSUE THREAD

**Issue by dvanherbergen** [openhab/openhab2-addons#608]
To do an initial automated quality check of a PR, an [automatic build](https://documentation.cloudbees.com/docs/cje-user-guide/pull-request-builder-for-github-sect-creating.html) should be triggered for the PR.
Ideally, this build will [fai] (http://docs.sonarqube.org/display/PLUG/Build+Breaker+Plugin)l if it doesn't comply with a predefined set of Sonar rules.

**Comment by teichsta** [comment]
... would be also very interested. Do you have any experience in setting up Sonar?

**Comment by hakan42** [comment]
I have some experience with Sonar as well but am not aware of any way to run it on something like cloudbees.

If we have access to a root server somewhere near (networkwise) to cloudbees, it would be quite easy.

Be aware that sonar analysis of large projects can add quite some time to the build though.

**Comment by kaikreuzer** [comment]
@dvanherbergen, @hakan42: If any of you would want trying this out on Cloudbees, let us know and we can give you access to it.

**Comment by maggu2810** [comment]
Sonar:
I have used sonar for some time, but move currently to FindBugs, PMD, CheckStyle...
It does not require a sonar server instance and are also supported by the Eclipse IDE.

PR builder:
I am using this with Jenkins and a Gitlab instance on some projects.
It would be great if we could add it to the OH2 repos, too.

IMHO we should start with the PR builder and add the quality checks later.

**Comment by dvanherbergen** [comment]
> IMHO we should start with the PR builder and add the quality checks later.

+1 ... one step at the time

> I have used sonar for some time, but move currently to FindBugs, PMD, CheckStyle...

That could be another option. What type of reporting do you then use? Eclipse IDE integrated only?

> Be aware that sonar analysis of large projects can add quite some time to the build though.

This could indeed be an issue. I usually only run Sonar on a nightly schedule due to the duration. Running it for a PR will only work if it can be done very selectively.

>  If any of you would want trying this out on Cloudbees, let us know and we can give you access to it.

Yes, please.

**Comment by hakan42** [comment]
> If any of you would want trying this out on Cloudbees, let us know and we can give you access to it.

Yes, this would be nice. I believe I already have an account at cloudbees with my email address of hakan@gurkensalat.com if this helps setting up access.

**Comment by kaikreuzer** [comment]
@hakan42 Perfect, I added your user
@dvanherbergen, Could you also create an account, which I can then add? This is easiest as you can directly define your username, pwd, etc.

**Comment by maggu2810** [comment]
> What type of reporting do you then use?

Not only. Jenkins evaluates the reported numbers and there are quality gates...
https://img42.com/OmPU4

**Comment by sja** [comment]
I scare about build-per-pullrequest because we're an open source Project. Anybody can make a PR and add some ugly tasks to maven. Our Buildserver would execute that and maybe do some bad stuff.

I think it's a good idea to have a server which can execute the build in a dockerized build slave, created by jenkins docker plugin. What do you think?

**Comment by maggu2810** [comment]
Good point.
But if the PR build job is executed sequential, the bad stuff is that is runs all the time (one after the other). I do not see any problem here. If there are a bad guy that adds a lot of bad PRs we should block that person (can we do this) and report it to the Gihub stuff.

**Comment by dvanherbergen** [comment]
I've linked my github (dvanherbergen) account to cloudbees.

**Comment by dvanherbergen** [comment]
> Not only. Jenkins evaluates the reported numbers and there are quality gates...
https://img42.com/OmPU4

That looks like a good solution too. Let's first see how long the PR build will take and then take it from there.

**Comment by sja** [comment]
I think about guys, who add a "Send spam" task. 
Another szenario is to add the buildserver to a botnet or to use it for bitcoin mining. A typical buildserver has a lot of power. You can also use it to serve phishing sites.
Of course only until somebody stops the "hanging" build job. So a maximum runtime of a buildjob to say 1h should be set.
The classic run enables builds also to install a user-cron entry. So you can - after the job was stopped by e.g. a timeout - restart you malware from the workspace dir of jenkins.

**Comment by kaikreuzer** [comment]
@sja: Now we know how you earn some extra money at night ;-)

**Comment by hakan42** [comment]
I think the builds are pretty well isolated on Cloudbees.

In one of my other projects ( http://ksp-ckan.org/ ) we also build all incoming PRs. Until now, no one had the necessary criminal energy to send evil changes :smiling_imp:

**Comment by kaikreuzer** [comment]
@dvanherbergen added you.

**Comment by dvanherbergen** [comment]
@hakan42  What's your planning? Are you looking into this or shall I have a look? I would like to avoid duplication of effort.

**Comment by hakan42** [comment]
@dvanherbergen , if you have time, please start. I'll get around to look at it earliest tomorrow ( $WORK  requires some time :blush: )

**Comment by dvanherbergen** [comment]
A short status update: the automatic triggering of a build from a PR has been setup for the openhab, openhab2-addons and openhab-distro. The triggering part appears to be working.
A test PR build on the distro succeeded: https://github.com/openhab/openhab-distro/pull/64
A second test on the openhab2-addons resulted in a build failure : https://github.com/openhab/openhab2-addons/pull/619
No test was done yet on openhab1-addons.
The reason for build failure needs further investigation. 
Using commands in the comments like 'retest this please' doesn't seem to work.
To be continued.

**Comment by dvanherbergen** [comment]
PR builds are now fully working for openhab, openhab2-addons and openhab-distro.
As per @sja 's suggestion, I've added a time limit to the build execution.
I've also tweaked the build history settings a little, so that more build history is kept (but only 1 set of artifacts).
@kaikreuzer, the one which is still missing is the kaikreuzer/openhab-core build. To enable this one, the openhab user requires access or alternatively the repository could move to openhab.

**Comment by hakan42** [comment]
Nice :smile:

Can the distribution archive still be reliably built? AFAIR it depends on SNAPSHOT Artifacts from the previous builds, and a PR could very well create quite old versions of everything except what is currently worked on in the PR, depending on when the branch was created.

**Comment by dvanherbergen** [comment]
> Can the distribution archive still be reliably built?

Good point. Not yet. I will disable the install part for PR builds.

**Comment by kaikreuzer** [comment]
Do you know what impact these builds have on our quota and build minutes for Cloudbees? Do we run the risk that we exceed our monthly allowance in a single day now? @teichsta, as you did that before, can you comment?

**Comment by dvanherbergen** [comment]
It seems that the child builds (distro) are also kicking in after a pull request build. I'll disable them for now and investigate.
I'll also check if we can speed up the builds.
How many pull requests/month do we expect?

**Comment by kaikreuzer** [comment]
At least one per day: https://github.com/openhab/openhab2-addons/pulse/monthly

**Comment by dvanherbergen** [comment]
After looking at this for a bit, I think we really need to split the Jenkins build configurations between regular builds and pull request builds (sort of like is done at https://builds.apache.org/view/PreCommit%20Builds/). There are too many options configured on the build profile itself which should be set specifically depending on the build type (e.g. archive artifacts, deploy artifacts etc., build triggered by other build, etc.) It will also allow us to easily disable only a PR build if required.

**Comment by maggu2810** [comment]
On projects I am working we split the master build (CI) and the PR build, always.

The PR build
* merges the master and the PR
* does a build
* does not deploy artifacts (also no snapshot ones)
* could use compare the quality gate of the latest master and fail if there are new stuff broken (findbugs, codestyle, etc.)

**Comment by hakan42** [comment]
From looking at Cloudbees Status on Jenkins, the main problem would be the disc usage.

This can be worked around by deleting the workspace on successful builds (or maybe even on unsuccessful ones, the main information is kept in the build log anyway).

**Comment by dvanherbergen** [comment]
> Do you know what impact these builds have on our quota and build minutes for Cloudbees

The PR builds for the distro and openhab2-addons are now built on a small cloudbees instance, so this should not interfere with the available minutes for the standard builds. I also really tried to get the PR build for the openhab1 addons on there, but it will just not fit. At least not as long as the org.openhab.model.* bundles are part of the build. The generation process in there forks new JVMs causing the instance to run out of memory.

I also noticed, that dependency retrieval of files from the local cloudbees repo is very fast:
```
[INFO] Downloaded: http://repo.cloudbees.com/content/repositories/central/org/apache/maven/maven-settings/3.0/maven-settings-3.0.jar (46 KB at 2278.7 KB/sec)
[INFO] Downloading: http://repo.cloudbees.com/content/repositories/central/org/apache/maven/maven-aether-provider/3.0/maven-aether-provider-3.0.jar
[INFO] Downloaded: http://repo.cloudbees.com/content/repositories/central/org/apache/maven/maven-model/3.0/maven-model-3.0.jar (161 KB at 5956.5 KB/sec)
[INFO] Downloading: http://repo.cloudbees.com/content/repositories/central/org/sonatype/aether/aether-impl/1.7/aether-impl-1.7.jar
[INFO] Downloaded: http://repo.cloudbees.com/content/repositories/central/org/apache/maven/maven-artifact/3.0/maven-artifact-3.0.jar (51 KB at 1810.4 KB/sec)
[INFO] Downloading: http://repo.cloudbees.com/content/repositories/central/org/sonatype/aether/aether-spi/1.7/aether-spi-1.7.jar
[INFO] Downloaded: http://repo.cloudbees.com/content/repositories/central/org/apache/maven/maven-core/3.0/maven-core-3.0.jar (515 KB at 15596.6 KB/sec)
[INFO] Downloading: http://repo.cloudbees.com/content/repositories/central/org/sonatype/aether/aether-api/1.7/aether-api-1.7.jar
[INFO] Downloaded: http://repo.cloudbees.com/content/repositories/central/org/apache/maven/maven-aether-provider/3.0/maven-aether-provider-3.0.jar (50 KB at 1562.2 KB/sec)
[INFO] Downloading: http://repo.cloudbees.com/content/repositories/central/org/sonatype/sisu/sisu-inject-plexus/1.4.2/sisu-inject-plexus-1.4.2.jar
[INFO]
```
The fetching of eclipse resources is a lot slower:
```
[INFO] Fetching content.jar from http://download.eclipse.org/eclipse/updates/4.2/R-4.2.2-201302041200/ (119.9kB of 360.98kB at 118.49kB/s)
[INFO] Fetching content.jar from http://download.eclipse.org/eclipse/updates/4.2/R-4.2.2-201302041200/ (213.23kB of 360.98kB at 97.42kB/s)
[INFO] Fetching content.jar from http://download.eclipse.org/eclipse/updates/4.2/R-4.2.2-201302041200/ (360.29kB of 360.98kB at 119.15kB/s)
[INFO] Fetching content.jar from http://download.eclipse.org/eclipse/updates/4.2/R-4.2.1-201209141800/ (0B of 356.5kB at 0B/s)
[INFO] Fetching content.jar from http://download.eclipse.org/eclipse/updates/4.2/R-4.2.1-201209141800/ (334.84kB of 356.5kB at 333.43kB/s)
[INFO] Fetching content.jar from http://download.eclipse.org/eclipse/updates/4.2/R-4.2-201206081400/ (0B of 352.49kB at 0B/s)
[INFO] Fetching content.jar from http://download.eclipse.org/eclipse/updates/4.2/R-4.2-201206081400/ (129.8kB of 352.49kB at 128.39kB/s)
[INFO] Fetching content.jar from http://download.eclipse.org/eclipse/updates/4.2/R-4.2-201206081400/ (324.7kB of 352.49kB at 159.64kB/s)
```
So once the build starts depending on openhab-core rather than building the core part itself, it should require less memory and run a lot faster and as a result consume less of the quota.

Ideally, we would be able to run all the PR builds only on the small instances.

**Comment by teichsta** [comment]
> Do we run the risk that we exceed our monthly allowance in a single day now? @teichsta, as you did that before, can you comment?

unfortunately, yes! That is why i set up another Jenkins at innoQ to build the PRs. In order to reduce minutes we should at least remove e.g. the feature-verifying tasks as they blew up the build-time to over 20 minutes.

**Comment by dvanherbergen** [comment]
To avoid depleting all the build minutes, the PR builds have been disabled for the time being. Once the builds are faster, we can enable them again.

When looking at the openhab2-addons-PR build, I'm seeing the following times:
Total duration : 7 minutes
Initial download of maven dependencies: 26 seconds
Initial download of p2 dependencies: 2m 20s
Building feature verification module (which does a lot of downloading internally): 2m 27s. 
So that means that more than 5 out of 7 minutes build time is spent on resolving artifacts...

Something seems off with the maven dependency loading. It tries to download every dependency 3 times and succeeds twice:
```
12:38:12.285  |  [INFO] Downloading: http://repo.cloudbees.com/content/repositories/central/org/codehaus/plexus/plexus-io/2.4.1/plexus-io-2.4.1.pom
12:38:12.297  |  [INFO] Downloaded: http://repo.cloudbees.com/content/repositories/central/org/codehaus/plexus/plexus-io/2.4.1/plexus-io-2.4.1.pom (4 KB at 303.7 KB/sec)
12:38:12.299  |  [INFO] Downloading: https://repository-openhab.forge.cloudbees.com/release/org/codehaus/plexus/plexus-io/2.4.1/plexus-io-2.4.1.pom
12:38:12.310  |  [INFO] Downloading: http://repo1.maven.org/maven2/org/codehaus/plexus/plexus-io/2.4.1/plexus-io-2.4.1.pom
12:38:12.331  |  [INFO] Downloaded: http://repo1.maven.org/maven2/org/codehaus/plexus/plexus-io/2.4.1/plexus-io-2.4.1.pom (4 KB at 182.2 KB/sec)
```
There is probably an error in the cloudbees global maven settings.

Any ideas on how we can improve p2 loading time are welcome...

**Comment by kaikreuzer** [comment]
This is by now in place at https://openhab.ci.cloudbees.com/job/PR-openHAB2-Addons

**Comment by dvanherbergen** [comment]
The PR builds have been implemented, but there is no Sonar/PMD quality check not yet...
