### ISSUE TITLE
[mqtt] not supported by type 'NumberValue' on NumericValue

### ISSUE THREAD

**Issue by RobertHerter** [openhab/openhab2-addons#6096]
Getting the following warning.

`2019-09-18 16:28:25.561 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Incoming payload '{"Time":"2019-09-18T15:28:25","ENERGY":{"TotalStartTime":"2019-07-07T17:33:44","Total":0.034,"Yesterday":0.009,"Today":0.025,"Period":0,"Power":8,"ApparentPower":38,"ReactivePower":37,"Factor":0.21,"Voltage":226,"Current":0.167}}' not supported by type 'NumberValue'`

Is have 4 Channels configured.
1. JSONPATH:$.ENERGY.Power
2. JSONPATH:$.ENERGY.Total
3. JSONPATH:$.ENERGY.Voltage
4. JSONPATH:$.ENERGY.Current

Looking at the payload all are valid Numbers. So where is the warning coming from.

Using openhab 2.5 Build 1694

**Comment by jochen314** [comment]
It looks as if the incomming value is not transformed and the whole value is given to the NumberValue.

Do you have 'Add-ons'->'TRANSFORMATIONS' -> 'JSONPath Tranformation' installed? This Add-on is in charge of extracting the value.

**Comment by J-N-K** [comment]
Works with exactly that configuration in latest SNAPSHOT.
