### ISSUE TITLE
Numerous bindings failing to work in OH2 since moving to karaf

### ISSUE THREAD

**Issue by Tavalin** [openhab/openhab2-addons#610]
Kai suggested this is because karaf is stricter with respect to requiring packages to be stated in the Import-Packages section of the MANIFEST.MF files.

So far the most common errors are occuring for javax packages which previously did not require an entry.

Initial thoughts:
1) We could update each binding to add the missing imports, but currently unknown how many are affected
2) Try and implement some sort of workaround

**Comment by maggu2810** [comment]
I don't think we should add workarounds, as this is the concept how OSGi works. I assume we would like to create OSGi bundles that work in every OSGi compliant framework and not only in a product that adds workarounds that broken OSGi bundles are able to be loaded.

The OSGi specification mandates that a bundle declare all package depenencies using either Import-Package or Require-Bundle. The one exception to this rule is the java.* packages which is always delegated to the boot classpath. All other packages dependencies must be declared in the bundle's manifest file.

https://wiki.eclipse.org/Equinox_Boot_Delegation

**Comment by kaikreuzer** [comment]
@Tavalin: Can you name the bindings?
I tested many and I fixed the manifests for all that I noticed.
Please simply do the same: Whereever an entry is missing, create a PR for that binding to add the missing entry and all should be fine.
