### ISSUE TITLE
[Panasonic TV Binding] Get 500 Error on TV Actions

### ISSUE THREAD

**Issue by volbrene** [openhab/openhab2-addons#6104]
Hello,

i have a Problem with my new Panasonic 2019 TV. Openhab says:

`2019-09-19 09:01:52.446 [WARN ] [asonictv.internal.PanasonicTVBinding] - Command POWER to TV with IP 192.168.178.69 failed with HTTP Reponse Code 500`

I found the following issue on another Github project, which was fixed this issue: florianholzapfel/panasonic-viera#9

Apparently missing the request of a pin for the new Panasonic TVs Later 2019.

Is it possible to add this solution for the panasonic tv bindung in openhab?

**Comment by 9037568** [comment]
The panasonictv binding is an OH1 binding, and you've already opened an issue there.
