### ISSUE TITLE
[knx] DPT 1.003 not working in KNX Binding 2.4.0 (but was in Binding 1.X [1.13.0])

### ISSUE THREAD

**Issue by Ronny-GitHub** [openhab/openhab2-addons#6108]
I noticed that when I updated my openHAB installation to release 2.4.0 and migrated from KNX 1.X binding to the 2.4.0 binding that all my "motion" detection rules and especially my alarm detection were not working anymore. 
Here is a channel definition I have, which is a 1:1 Kopie of the 1.X binding settings:

`Type switch        : Motion_Alarm_Aktiv       "Motion .. alarm aktivated"        [ ga="<1.003:15/1/9" ]`

Since I in parallel also switch a red LED on on those motion detectors I was under the impression the communication openHAB - KNX is working fine. Also the website was reflecting the status change (item ON/OFF).
I could not find out why my motion detection rules are not fired anymore.
After some debugging I found that when I switch the alarm object from ETS directly all the sudden my motion/alarm detection rule gets fired. At the same time I don't see the status change of the alarm detection object to switch to activated/deactivated when I do this via ETS.
So my assumption is that the 2.4.0 KNX binding is not capable to make use of the DPT 1.003.
It would be great to get this fixed/implemented as this seems to be a rather simple data type and should not be complicated to add.
If you feel my setup is wrong - please let me know.
Thanks a lot for the support of this project.

FYI - the motion detector used is: "MDT SCN-BWM55.01"
(This is my first issue reported - please let me know in case I forgot something. I did check the other KNX issues and did not find my problem to be mentioned, if I oversaw some please let me know or cancel this ticket.)

**Comment by kschn** [comment]
Same as in #6109:

Try changing `[ ga="<1.003:15/1/9" ]` to `[ ga="1.003:<15/1/9" ]`

**Comment by Ronny-GitHub** [comment]
Yes - thanks for pointing this out. 
This really works a little different in KNX 2.4.0 binding. 
Will close the issue.
