### ISSUE TITLE
Removing bindings through PaperUI does not work

### ISSUE THREAD

**Issue by xsnrg** [openhab/openhab2-addons#613]
In the current build, in PaperUI, removing a binding does not work.

Open PaperUI, go to extensions, click Uninstall on an installed binding.  In this case avmfritz

    07:58:26.246 [ERROR] [st.core.extensions.ExtensionResource] - Exception while uninstalling extension: java.lang.IllegalArgumentException: Feature named 'openhab-binding-avmfritz/0.0.0' is not installed
    07:58:26.249 [INFO ] [smarthome.event.ExtensionEvent      ] - binding-avmfritz: java.lang.IllegalArgumentException: Feature named 'openhab-binding-avmfritz/0.0.0' is not installed

**Comment by xsnrg** [comment]
Playing some more, it may be just fritz, or it may have to do with bindings added in the distribution.  Adding a binding such as sysinfo from PaperUI, and then removing it seems to work.  Perhaps the DB was not populated with the bundled addon information, so there is no reference to remove with?

**Comment by kaikreuzer** [comment]
I assume you have still installed the demo package, right?
I suppose this is due to the fact that the openhab-package-demo feature is installed, which contains the openhab-binding-avmfritz feature, which is then not marked in Karaf as being installed.

@maggu2810 Can we change the demo feature in some way way, so that the included features are individually de-installable?

**Comment by kaikreuzer** [comment]
@xsnrg: As a workaround, switch to the standard package (in addon.cfg) and all should be fine.

**Comment by xsnrg** [comment]
Thanks @kaikreuzer .  I switched to standard.  Seems to be working as described.  Populating the demo addons in Karaf is probably a low priority in that case.  I'll ask on the community forum what the vision is for updates/upgrades to both addons and core OH2 is,  as config changes such as this would get overwritten.

**Comment by kaikreuzer** [comment]
> as config changes such as this would get overwritten.

No, on updates, neither the conf nor the userdata folder should be touched, that's the idea.

**Comment by xsnrg** [comment]
userdata I understand.  Did the cfg files get created automatically if they did not exist, or were they in the bundle that was extracted?  If in the bundle, would get overwritten unless there is another way to update core openhab now?

**Comment by kaikreuzer** [comment]
Well, the question is how the update process should look like - currently, I would suggest that you extract it to a new location and copy over your conf and userdata folder. Since unzipping the content of runtime over an old runtime might be a bad idea as well.

**Comment by kaikreuzer** [comment]
But what I would like to have is directly an update possibility of Karaf features, i.e. go to a newer snapshot of a binding - this would not require an update of the distro at all.

**Comment by xsnrg** [comment]
Do we not get a newer snapshot of a binding by doing Uninstall/Install process again as it is today, or is the downloaded version cached somewhere and just re-installed from local?  (assuming the online package is installed).

This is great for addons, and that may already be solved then.  Upgrading core is a extract/copy process still, and that is certainly workable as well.  I managed it with the previous OH2 with a script, and will do so again.  I just didn't want to miss out on some super-cool feature of Karaf that solves everything.  :)

**Comment by kaikreuzer** [comment]
> Do we not get a newer snapshot of a binding by doing Uninstall/Install process again as it is today

Good question, I haven't actually tested this yet. But I am sure that it won't work for the offline distro ;-)

> Upgrading core is a extract/copy process still, and that is certainly workable as well.

All core bundles are packaged as Karaf features as well - so my hope is that we will even be able to upgrade them this way. So the only stuff that would remain old is the Karaf container itself and the scripts around it.

**Comment by maggu2810** [comment]
> @maggu2810 Can we change the demo feature in some way way, so that the included features are individually de-installable?

I (think I) understand what you mean.

But if we define that feature A needs feature B, I don't believe it would be correct if feature B could be de-installed. What should be the state of feature A? Installed-a-little-bit? :wink: 

The installation of features is currently be done using an extension service implementation.
Perhaps we should create a separate setup UI for such stuff.
So we could define a switch / button that triggers the installation of all features that we define to be part of a demo package. We can then drop the feature of the demo and just state "install NOW all parts of the demo".

We could add to that UI a log file viewer (something I mentioned about the FQN in events.log) that can handle all log files and other stuff.

We could also use something similar to the Karaf webconsole to edit configuration admin etc.

**Comment by xsnrg** [comment]
I think we can close this as it has not been an issue beyond the initial trying to remove stuff from demo.  The answer was to not start up in demo mode.  If not in demo, the karaf console can be used to remove bindings.
