### ISSUE TITLE
[opensprinkler] Remove support for OpenSprinkler PI bridge

### ISSUE THREAD

**Issue by FlorianSW** [openhab/openhab2-addons#6147]
**Current situation**
The opensprinkler binding currently has two bridges, which can be used to communicate with an opensprinkler server:
* the http based bridge, which controls opensprinkler by sending commands to the opensprinkler server via HTTP requests authorized with a password.
* the pi bridge, which requires, that the opensprinkler server is installed on the same Raspberry Pi as the openhab server, which uses the GPIO pin, on which a station is connected to, in order to control the state. There's no authentication, as this only works, if openhab is on the same device as the opensprinkler server (and where the statiosn are connected to), so anything is local

**Obstacles**
Having to maintain two ways of communicating with a specific opensprinkler server is possible, but introduces a bit of complexity. This would not be a big problem, the software architecture of the binding allows to implement features and maintain them with multiple bridges, as the bridge logic is encapsulated from the rest of the bindings functionality.

However, the biggest problems comes to the functionalities provided by both bridges: Maintaining two different, but function-wise similar interfaces, would be pretty easy. However, the HTTP interface allows a much more richer configuration and control of the opensprinkler server. While the PI interface allows us to control the state of a station (ON/OFF) only. It actually bypasses the logic of opensprinkler as a whole, which might or might not result in problems.

That means, that a user gets a different set of features based on the bridge they're using, however, the station thing of the openhab binding actually exposes the same set of features for both bridges. Whenever a channel is used, which is only supported in the http bridge, the API interface will throw an exception. This is bad in multiple ways: It has a bad user experience, a user can actually configure everything correctly and will, at the end of the process, get a weird error message once they actually want to use the feature they configured just a moment ago. It also makes it more difficult to actually propose new features to the binding, as the PI interface will most likely not support it, and there's some work involved in actually handling these cases.

**Proposal**
Because of the mentioned difficulties I propose the following:
* Remove the support of the PI bridge from opensprinkler
OR
* Deprecate the PI bridge with the next release of openhab and remove it in the release after

This would allow us to focus on one specific interface, which provides a lot more functionality as the PI interface actually does and ever will be.

The migration for existing users of the PI interface would involve changing the type of bridge they're actually using. This requires also to set up authentication, however, the traffic does not necessairly leave the localhost, as the http bridge is able to communicate with localhost as well. A documentation for migrating an existing bridge, both in textual and graphical (=PaperUI) configuration would need to be created as part of the removal/deprecation Pull request.

**Next step**
As I do not really know how such things (removal of previous functionality) works in the community, I would like to get feedback about how to proceed. First of all: Do you (openhab2-addon maintainers) support removing the PI bridge support from the binding (based on the obstacles I posted above)? And if so, is getting a pull request ready the only thing needed to be done (I would do it then), or do we need to do something else? If so, what? :)

**Comment by smhswiss** [comment]
@FlorianSW 
Thank you for starting this discussion. I resently got my watering built in and started running OpenSprinkler device. It is not yet productive owever. I started to experiment with openHAB2 M3 and the implementation of OpenSprinkler binding. My first thought was it should be simple, but I very quickly noticed that the binding itself does not cover what I would like to get.
I mean control the station is one thing, getting data of OpenSprinkler the other.

For this I removed the binding and started to get what I need using the HTTP binding. The API of OpenSprinkler allows me to do all that things without having a binding at all, it is more time consuming to get the things done. But in the end of the day why should I use a binding that doesn't deliver what it should?

For Instance with the HTTP Binding I'm able to read out the firmware version and the type of device used and display this as text values in openHAB. The OpenSprinkler binding doesn't allow this.
Using the HTTP binding I'm also able to address more or less every single parameter of OpenSprinkler, I don't see this possibility with the current OpenSprinkler binding.

So based on that my question is more like is that OpenSprinkler Binding needed at all (for what it offers)? Or would it make more sense to migrate HTTP binding to OH2 version and improve its handling?

**Comment by FlorianSW** [comment]
Hi @smhswiss!

Thanks for joining the discussion :) I would like to start with your last statement/question:

> So based on that my question is more like is that OpenSprinkler Binding needed at all (for what it offers)? Or would it make more sense to migrate HTTP binding to OH2 version and improve its handling?

Basically, I've a completely different opinion here and would say: Yes, the binding is needed and should exist. The idea of a binding (at least from my point of view) is to abstract the individual way a smarthome device is working from the actual logic of your smarthome (like turning things off and on based on other events or whatever). Moving the communication with the opensprinkler stations and devices to the rules by using the HTTP binding makes the rules unnecessary complex, hard to maintain and unreadable. Also, the rules engine from what I know of, is not very suited to communicate with devices, as it was not build for it. It was build to automate things inside of the openHAB system. A binding is an adapter to bring an outside system/device into the openHAB world and expose their functionality using the defined APIs openHAB is used to.

So, instead of moving the HTTP binding to OH2, I think the underlying problem is:

> The OpenSprinkler binding doesn't allow this

Maybe it should. There is probably just the functionality missing to expose the firmware version, to have more parameters when doing stuff or getting the info from the device instead of just acting with it.

I would be very happy to implement a lot of these features, however, they require the HTTP API, and are not doable with the PI interface. In order to have a better binding, supporting of both interfaces is a burden in the code, which does not seem to bring a lot of benefits. Therefore I proposed the removal of the PI interface.

Btw.: All of the features you're looking for, which are not possible with the binding at the moment, would you please open a new issue for each single one of them? That would be awesome and would allow us to track the progress of the implementation and discuss them individually :) Thanks in advance already!
