### ISSUE TITLE
Astro binding throws warning when changing locations

### ISSUE THREAD

**Issue by xsnrg** [openhab/openhab2-addons#616]
Steps:

Install v2 astro binding, or use the demo binding that is installed
Change the location in PaperUI and save.  The result is a WARN:

    11:19:19.756 [WARN ] [mon.registry.AbstractManagedProvider] - Could not update element with key astro:sun:home in ManagedThingProvider, because it does not exists.

**Comment by kaikreuzer** [comment]
This is expected behavior. The sun:home is defined in the (read-only) file `conf/things/demo.things`, so if you want to edit the location, do it in there. Alternatively, create the thing in the Paper UI and you can manage it from there.
And if you are not happy with this answer, feel free to join the discussion at https://www.eclipse.org/forums/index.php?t=msg&th=1072808&goto=1718043&#msg_1718043 or even better, directly implement my suggestion 4 in it ;-)

**Comment by xsnrg** [comment]
I am sensing a pattern.  The install I am playing with was first based off demo, and this seems to be getting in my way a lot.  If I want the online version of OH2 but clean/no demo, do I download the online distribution and change the configuration before first run or is the DB pre-populated at that point and I should remove the DB and start over?

**Comment by xsnrg** [comment]
I read through the chat over there.  That is the larger issue for certain.  At least for the case of DEMO though, why not get rid of flat files all together for OH2 and use a pre-populated DB?  This would then allow any of the demo items to be updated/removed, etc.  If a user screws up their demo, just re-install it.

**Comment by kaikreuzer** [comment]
You should read the thread up to here at least: https://www.eclipse.org/forums/index.php?t=msg&th=1072808&goto=1719710&#msg_1719710

**Comment by xsnrg** [comment]
Thanks Kai, I did read the whole thing.  Maybe I am missing something.  The thread over at eclipse is talking about the overall problem of configuration persistence and I was just talking about not being able to modify the demo configuration. 

My thought was that, no matter the store, the demo config could be in whatever DB, and then be able to be modified.  It is often easier for people to modify something that to come up with it on their own.

Sorry if I am being dense on this.  If there is no desire to change how demo works, my question was answered above with the flat file description.  Thank you.
