### ISSUE TITLE
Problems with binding hue and linking

### ISSUE THREAD

**Issue by jrcourtois** [openhab/openhab2-addons#622]
I installed beta version, and I tried demo version before going back to standard (in conf/addons.cfg).
I am trying to use Hue lamps and I got some issue with PaperUI.
It appears automatically, and when I checked in the interface, it did not seems I clicked so I clicked on it.
![screen shot 2016-01-14 at 5 40 13 pm](https://cloud.githubusercontent.com/assets/5859493/12330441/75be0792-bae5-11e5-8450-c035b70b4349.png)

I didn't manage to do anything on it and got the following traces

```
17:30:56.475 [INFO ] [smarthome.event.ThingAddedEvent     ] - Thing 'hue:LCT001:001788182930:2'  has been added.
17:30:56.492 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'hue:LCT001:001788182930:2' changed from INITIALIZING to ONLINE
17:30:56.493 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'hue:LCT001:001788182930:2' changed from UNINITIALIZED to INITIALIZING
17:30:56.495 [INFO ] [smarthome.event.ThingUpdatedEvent   ] - Thing 'hue:LCT001:001788182930:2' has been updated.
17:30:56.510 [INFO ] [smarthome.event.ItemAddedEvent      ] - Item 'hue_LCT001_001788182930_2' has been added.
17:30:56.523 [INFO ] [rthome.event.ItemThingLinkAddedEvent] - Link 'hue_LCT001_001788182930_2-hue:LCT001:001788182930:2' has been added.
17:30:56.546 [INFO ] [smarthome.event.ItemUpdatedEvent    ] - Item 'hue_LCT001_001788182930_2' has been updated.
17:31:07.684 [INFO ] [home.event.ItemChannelLinkAddedEvent] - Link 'true-hue:LCT001:001788182930:1:color' has been added.
```

Which leads me to the major problem I faced when I tried to retrieve the item which should have been selected
```java
        Thing t = thingSetupManager.getThing(objIdentifier);
        if (t != null) {
            for (Channel c : t.getChannels()) {
                Set<String> channels = ItemChannelLinkRegistry().getLinkedItems(c.getUID());
```
```java
['RGBColor', 'value']
```
For the first issue, I can get through with it, but for the second one I would like to know if it is an expected behaviour or face by anyone else.

**Comment by kaikreuzer** [comment]
Please note that the Hue binding is maintained here: https://github.com/eclipse/smarthome
If you move your issue over there, I promise to answer tomorrow ;-)

**Comment by jrcourtois** [comment]
OK then 
https://github.com/eclipse/smarthome/issues/855

Thanks Kai
