### ISSUE TITLE
 Paper UI - linking a channel to several items

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab2-addons#624]
Paper UI allows to link a particular thing channel to a unique item.
The ability to link a channel to several items would be appreciated.
For example, for any dimming light (hue light for example), I define a switch item + a dimmer item.
Waiting for this enhancement, of course, any link can be done by editing the item files.

**Comment by kaikreuzer** [comment]
Please note that the Paper UI source code (and such its issue tracker) is here: https://github.com/eclipse/smarthome

> I define a switch item + a dimmer item.

My I ask why? A dimmer item should be good enough, since you can send ON/OFF commands as well?
