### ISSUE TITLE
MQTT binding, MqttService and custom binding using MQTT proto

### ISSUE THREAD

**Issue by aisebastian** [openhab/openhab2-addons#6256]
Hello, I am trying to understand how the MQTT binding is supposed to be used, and what is it's purpose. I am using the mqtt binding (org.openhab.bindings.mqtt) which gives me the ability to easily use an MQTT subscription based discovery service in my own binding, but what I cannot access are the mqtt connections to publish messages during discovery process.

I can't find my mqtt connections in MqttService created for things created with MqttBindingConstants.BRIDGE_TYPE_BROKER and I can't seem to figure out how to configure a thing typed MqttBindingConstants.BRIDGE_TYPE_SYSTEMBROKER (I would prefer the first option for ease of configuration).

Can somebody please shed some light on how this infrastructure is supposed to be used? If it's a RTFM thing, please point me to the right docs, I could not get clarity on this matter from the existing documentation with the best of my effort.

L.E.: Is it a desired feature to register the MqttBindingConstants.BRIDGE_TYPE_BROKER typed things to MqttService? I can submit a PR for this. If not, how can we use a MqttBindingConstants.BRIDGE_TYPE_BROKER typed broker conenction to publish things?

Thanks!

**Comment by davidgraeff** [comment]
MqttService is not really used anymore. In OH1 days it was the only way to configure mqtt brokers (via an mqtt.cfg file). Nowadays MqttService can potentially be used the same way, but no one does as far as I know.

For your own binding you must be in the MQTT binding namespace. That's a limitation of openHAB and Core denied my idea / patch to lift this restriction. If you are, you have access to the Mqtt brokers defined in the main mqtt binding.
