### ISSUE TITLE
[hue] - Tap Switch not showing in paper ui / triggering in rules

### ISSUE THREAD

**Issue by Lovett1991** [openhab/openhab2-addons#6266]
Got several tap switches but can't get them to show in paperui or work with rules.

things:
```
Bridge hue:bridge:hue_id [ ipAddress="...", userName="..."] {
  //Living Room
  Thing 0830 Living_Room_Switch "Switch" @ "Living-Room" [ sensorID="36" ]
}
```

rules:
```
rule "Button pressed"
when
  Channel "hue:hue_id:Living_Room_Switch:tap_switch_event" triggered
then
  logInfo("livingroom", "button pressed")
end
```

Have I done anything wrong with this? Bulbs, motion sensors all working fine.

**Comment by wborn** [comment]
Please use the community for these support questions. After a quick search I found this [community post](https://community.openhab.org/t/hue-binding-dimmer-switch/29761/39?u=wborn) which suggests the channel ID in your rule is missing the thing type ID (0830) so try using:

`Channel "hue:0830:hue_id:Living_Room_Switch:tap_switch_event" triggered`
