### ISSUE TITLE
Freebox binding: channels of type String not displayed in UI

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab2-addons#635]
For example the channel "IP Address": I link it to this item:
```
String Freebox_cs_ipv4 "ipV4 [%s]" (GFreebox)
```
No value displayed (Classic UI or HADdroid) but the item is correctly set:
It could be the same kind of issue I discovered for dates with the Astro binding.

**Comment by lolodomo** [comment]
As an additional, if I break the link in Paper UI and set it in my item file like that:
```
String Freebox_cs_ipv4 "ipV4 [%s]" (GFreebox) {channel="freebox:server:2d65986d:ipv4"}
```
It does not work better (no value displayed in UI while the item is correctly set).

**Comment by lolodomo** [comment]
If I suppress the "[%s]", it does not change anything.

**Comment by kaikreuzer** [comment]
> It could be the same kind of issue I discovered for dates with the Astro binding.

It very likely is, so first wait for https://github.com/eclipse/smarthome/issues/871 to be fixed - when this is fixed and this issue here still occurs, please simply re-open it!

**Comment by kaikreuzer** [comment]
Fixed by https://github.com/eclipse/smarthome/issues/871, which is now available in OH2.
