### ISSUE TITLE
Error while calling function "transform"

### ISSUE THREAD

**Issue by thomasjetzinger** [openhab/openhab2-addons#636]
The following error message is thrown, when I'm trying to call ```transform("JSONPATH", "$.value", test)``` in a rule:

```
The name 'transform(<XStringLiteralImpl>,<XStringLiteralImpl>,<XFeatureCallImplCustom>)' cannot be resolved to an item or type.
```

I'm using the openHAB 2 Beta Snapshot from today, The same error also occurs with the openHAB 2 beta 1.

Best Regards,
Thomas

**Comment by kaikreuzer** [comment]
Thanks! May I ask you to move this issue over to https://github.com/openhab/openhab-distro (since it is not related to any add-on?
