### ISSUE TITLE
[deconz] No battery or BatteryLevel channel from Xiaomi/Aqara Temperature sensors

### ISSUE THREAD

**Issue by frest-de** [openhab/openhab2-addons#6362]
Hardware: Raspberry 4B, Conbee II stick
Software: Openhabian buster, Openhab 2.5.0-M1, org.openhab.binding.deconz-2.5.0-SNAPSHOT

I have all kind of Xiaomi and Aqara sensors working fine, but the temperature sensors lumi.weather (Aqara) and lumi.sensor_ht (Xiaomi) does not provide the channels for battery or BatteryLevel. The deconz REST api provides the information:

` "53": {
    "config": {
      "battery": 91,
      "offset": 0,
      "on": true,
      "reachable": true
    },
    "ep": 1,
    "etag": "a730ed68f97afceb3f3bef38c1b005a5",
    "manufacturername": "LUMI",
    "modelid": "lumi.sensor_ht",
    "name": "Multisensor",
    "state": {
      "lastupdated": "2019-11-09T08:05:06",
      "temperature": 2141
    },
    "swversion": "20160516",
    "type": "ZHATemperature",
    "uniqueid": "00:15:8d:00:02:3d:06:14-01-0402"
  },`

Is that a bug @davidgraeff?

**Comment by davidgraeff** [comment]
Each value has to be supported individually and the binding might just not have support yet for those battery values.

**Comment by cweitkamp** [comment]
In general the handler will add the `battery-level` and `low-battery` channels if a value for it is present in the config.

https://github.com/openhab/openhab2-addons/blob/eb6d591d1a348bc6c7ab6fe23f2072e847d11aab/bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorThingHandler.java#L235-L242

Did you try to to disable -> enable the handler or restart the binding? I guess you did.

**Comment by frest-de** [comment]
I did, I waited one day longer, now its working! ;)
