### ISSUE TITLE
[homematic] HM-CC-RT-DN does not expose WEATHER_RECEIVER

### ISSUE THREAD

**Issue by iimehl** [openhab/openhab2-addons#6418]
According to page 28 on https://www.eq-3.de/Downloads/eq3/download%20bereich/hm_web_ui_doku/HM-Script_4-Datenpunkte.pdf
the HM-CC-RT-DN thermostat has an input option WEATHER_RECEIVER  on channel 1. 
This input allows to feed temperature measurements to the thermostat as control input, e.g. from the other side of the room. Unfortunately this value is not exposed on paperUI.

**System**:
Openhab Snapshot 2.5 (#1759)
Raspberry PI
Homegear version 0.8.0-2820

**Comment by MHerbst** [comment]
Where did you get the information that WEATHER_RECEIVER can be used to feed temperature measurements?
The Homematic documentation clearly says on page 28 that this channel has no data points ("Der Kanal besitzt keine Datenpunkte"). If there are not data points than you can use it from external software like openHAB.

**Comment by iimehl** [comment]
Dear Martin,

I found this forum post, stating that this is possible in FHEM

https://openhabforum.de/viewtopic.php?t=486

**Comment by MHerbst** [comment]
@iimehl As far as I understand it, the weather channel can only be used together with other HomeMatic devices like the wall thermostats. If you create a group containing eg. several HM-CC-RT-DN with a wall thermostats the wall thermostat will directly send temperature values to the HM-CC-RT-DN (I am using this configuration in several rooms). 
Other options are not documented by EQ3 and I don't think that FHEM can do more. I found this remark in the Wiki (https://wiki.fhem.de/wiki/HM-CC-RT-DN_Funk-Heizk%C3%B6rperthermostat#Channel_.28Kanal.29_01_Weather): 

> Dieser Kanal dient zur Einspeisung der (gemessenen) Ist-Temperatur. Als Sensor können zum Beispiel das HM-TC-IT-WM-W-EU Funk-Wandthermostat oder ein HM-WDS40-TH-I Funk-Temperatur-/Feuchtesensor dienen.

For me this means that FHEM does exactly what happens in the CCU when forming groups.

**Comment by iimehl** [comment]
Thanks for the explanation. So if the channel is used to input external 
temperature readings "Dieser Kanal dient zur Einspeisung der 
(gemessenen) Ist-Temperatur", must it not somehow be exposed and 
therefore be usable via Openhab?

But I am no EQ3 expert and if you think it isn't possible, we can close 
this issue.

**Comment by iimehl** [comment]
I looked at this again. As @MHerbst pointed out the EQ3 document https://www.eq-3.de/Downloads/eq3/download%20bereich/hm_web_ui_doku/HM-Script_4-Datenpunkte.pdf says "Kanaltyp WEATHER_RECEIVER Der Kanal besitzt keine Datenpunkte." The same doc also says "Kanaltyp WINDOW_SWITCH_RECEIVER Der Kanal besitzt keine Datenpunkte." 
But Openhab2 provides a "Window Switch Receiver" with a data point "Window State"

To me this seems to indicate that it should be possible to expose the WEATHER_RECEIVER channel.

**Comment by MHerbst** [comment]
> But Openhab2 provides a "Window Switch Receiver" with a data point "Window State"
@iimehl Where did you find this? I have checked the channels of my HM-CC-RT-DN devices and there is no such channel. 
It is possible that Homegear provides more data points than Raspberrymatic or the original CCU. But does it really work?

**Comment by iimehl** [comment]
I am using homegear and yes the channel works, well at least if I trigger it, an "open window" icon is displayed on the LCD of the HM-CC-RT-DN. The window channel is also defined in the xml file: https://github.com/eq-3/occu/blob/master/firmware/rftypes/rf_cc_rt_dn.xml
The file also mentions the WEATHER_RECEIVER but I am not familiar with the specific syntax so I have a hard time understanding the code.

**Comment by MHerbst** [comment]
That's interesting. The Homematic binding creates for devices like the thermostats all channels dynamically based on the information that it receives from the Homematic controller. In this case, it seems that Homegear provides more data points than other controllers like Raspberrymatic.
This means, if Homegear would provide WEATHER_RECEIVER datapoint, the Homematic binding should automatically detect it and create a respective channel. I would recommend to ask the Homegear developers whether they can provide this data point.

**Comment by iimehl** [comment]
Thanks for the explanation. I'll contact the homegear forum and close this one.
