### ISSUE TITLE
[mqtt] Warnings when sending commands: "read-only channel, ignoring command"

### ISSUE THREAD

**Issue by servim** [openhab/openhab2-addons#6435]
Hi!
After upgrading from build 1736 to 1759, 1761
in the log, when sending a command via mqtt, warnings:

```

2019-11-22 19:27:52.337 [WARN ] [qtt.generic.AbstractMQTTThingHandler] - Channel mqtt:topic:g_mqtt:box_heater_ir_things:state is a read-only channel, ignoring command OFF
2019-11-22 19:27:54.074 [WARN ] [qtt.generic.AbstractMQTTThingHandler] - Channel mqtt:topic:g_mqtt:box_heater_ir_things:state is a read-only channel, ignoring command ON
2019-11-22 19:27:56.374 [WARN ] [qtt.generic.AbstractMQTTThingHandler] - Channel mqtt:topic:g_mqtt:box_heater_ir_things:state is a read-only channel, ignoring command OFF


```
I didn’t find a similar problem by searching, does it have one for me?
How can this be cured?
Thanks!

**Comment by J-N-K** [comment]
Please show your configuration. In general that means that you send commands to a channel that has a state-topic, but not a command-topic, so openhab doesn’t know where to send the command to. If you have a command topic defined, it‘s a bug.

**Comment by servim** [comment]
I understand you, now it’s not in place, when there will be an opportunity, I will look for my mistake. Thanks!

**Comment by servim** [comment]
I found what you are talking about, but for now I don’t understand how to fix it.
things:

```
    Thing topic box_heater_air_things "Heater (AIR)" @ "Box" {
    Channels:
        Type switch : power     "Power"                 [stateTopic="stat/box-heater-air/POWER1", commandTopic="cmnd/box-heater-air/cmnd/POWER1"]
        Type switch : state     "State"                 [stateTopic="tele/box-heater-air/STATE",  transformationPattern="JSONPATH:$.POWER1"]

```
items:
```

Switch	box_heater_air				"Box Heater [%s]"					    <radiator>		(gBox,gHistory,gGarageScene1_OFF)			[ "Switchable" ]	{ channel="mqtt:topic:g_mqtt:box_heater_air_things:power",
                                                                                                                                                              channel="mqtt:topic:g_mqtt:box_heater_air_things:state",
                                                                                                                                                              autoupdate="false"  }	

```
item - box_heater_air, must change its state from two (or even more) state topics:
1. stateTopic="stat/box-heater-air/POWER1"
2. stateTopic="tele/box-heater-air/STATE",  transformationPattern="JSONPATH:$.POWER1"
How to do it right?
Could it be possible, in some way, to use two or more status topics in one channel?
Thanks!

**Comment by jochen314** [comment]
Yes, you should define it in one channel:
```
Thing topic box_heater_air_things "Heater (AIR)" @ "Box" {
    Channels:
        Type switch : power     "Power"                 [stateTopic="tele/box-heater-air/STATE",  transformationPattern="JSONPATH:$.POWER1", commandTopic="cmnd/box-heater-air/cmnd/POWER1"]
```

assuming that commands to the device are send over the topic <code>cmnd/box-heater-air/cmnd/POWER1</code> and the device sends its state over <code>tele/box-heater-air/STATE</code>.
The item one has one channel then.

**Comment by servim** [comment]
`
stateTopic="stat/box-heater-air/POWER1"
`
It is transmitted by the device when a switch command was sent or the device was switched manually.
`
stateTopic="tele/box-heater-air/STATE",  transformationPattern="JSONPATH:$.POWER1"

`
The device sends its status periodically, for example, once a minute.
If I refuse the first and leave only the second status, I will not receive confirmation from the device that it switched in real time, but only when the periodic status arrives.
If I refuse the second one and leave only the first status, I won’t get the real status of the device after rebooting openHAB, if the device changes its state while the openHAB reboots.

**Comment by jochen314** [comment]
I was a little bit too fast on the first read.
From what I understand now, we usually would use 
<code>stateTopic="stat/box-heater-air/POWER1</code>
and ignore the periodical state.
Currently there is no concept of an item receiving information frmo 2 different topics.
But the only disadvantage is, that the state of the item remains unkown until a state change occurs.

**Comment by servim** [comment]
> But the only disadvantage is, that the state of the item remains unkown until a state change occurs.

This is a very significant drawback :(

**Comment by Rossko57** [comment]
Comment: it **is** legitimate to send commands to an Item, where a channel may be configured as "read-only" i.e. that binding has no channel config to handle command.
The commands may be intended to trigger rules, or the Item may have another channel that does handle commands.

The binding author could/should choose to pop a message about it, seems sensible.  But where it's a deliberate user read-only config that becomes a nuisance message at every command.  Maybe this particular message should be at TRACE or DEBUG level rather than WARN ?

A fancy way would be to WARN only at the first occurrence, and afterwards at TRACE, but that seems like over engineering.

**Comment by servim** [comment]
> it **is** legitimate to send commands to an Item
Most likely, it works!

> Maybe this particular message should be at TRACE or DEBUG level rather than WARN ?

Because this is not a mistake (if so), then I agree, it should be TRACE or DEBUG level.
