### ISSUE TITLE
DMX-Binding: Add possibility to configure IP and Universe (Artnet)

### ISSUE THREAD

**Issue by dvanherbergen** [openhab/openhab2-addons#645]
[Original Issue](https://github.com/openhab/openhab/issues/2622) raised by @spacemanspiff2007  : 

> As of now the DMX Universe is hardcoded.
> This limits the use of different universes, since it only allows a total of 512DMX-Channels (Very Bad!).
> In the Google-Groups is already an elegant solution described for this.
> With an extended configuration like this
> 
> ``` dmx:name1.ip=192.168.1.1
> dmx:name1.universe=0
> dmx:name2.ip=192.168.1.1
> dmx:name2.universe=1
> ```
> 
> it would be possible to Identify the exact ArtNet Node.
> (In this example 2 ArtNet nodes with different IPs and Universes, both with LEDs on Channel 7)
> 
> ```
> Color rgb_strip_living_room1 "RGB Ledstrip Living Room1" {dmx="name1:CHANNEL[7:1000]"}
> Color rgb_strip_living_room2 "RGB Ledstrip Living Room2" {dmx="name2:CHANNEL[7:1000]"}
> ```
> 
> Could you please add the extended configuration to the DMX-Binding?
> Thank you.
##

**Comment by cristianm** [comment]
Same issue here. Openhab need best DMX binding.

**Comment by J-N-K** [comment]
Please see [this thread](https://community.openhab.org/t/oh2-esh-dmx-binding/16592). The ESH binding supports that, I doubt someone will update the old binding.

**Comment by wborn** [comment]
Please create an issue for this in the openhab1-addons [issue tracker](https://github.com/openhab/openhab1-addons/issues) if you still want to have this added to the old binding.
