### ISSUE TITLE
Freebox binding: call timestamp cannot be linked to a DateTime item

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab2-addons#647]
Using Paper UI, DateTime items are not populated in the list of available items for the call timestamp channel.

**Comment by kaikreuzer** [comment]
This sounds clearly like a bug of the Paper UI - may I ask you to open an issue at https://github.com/eclipse/smarthome/issues instead? Thanks!

**Comment by lolodomo** [comment]
My feeling is that the list is populated depending on the channel type, isn't it ?
Maybe this channel was defined as a string rather than a datetime ?

**Comment by kaikreuzer** [comment]
Yes, you are absolutely right. The channel type of call_timestamp is of type String and it would indeed make sense to use DateTime instead.

**Comment by clinique** [comment]
Will take a look at this issue soon

**Comment by clinique** [comment]
@lolodomo , you were right, while it's handle as a DateTimeType in the binding, it was declared as a String in ESH_INF. Correcting this.
