### ISSUE TITLE
samsungtv binding: Program titles are converted to uppercase

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab2-addons#653]
I have tried the Samsung TV binding, which works quite well with my TV. 
But there is one issue with (I assume) all channels that return a string. I have added the programTitle to my items and sitemap and the following happens.
According to the log file the following string is returned:
````
16:26:28.293 [INFO ] [home.event.ItemChannelLinkAddedEvent] - Link 'samProgramTitle-samsungtv:tv:0f7f4900_0004_1000_8162_1c5a3ede70f5:programTitle' has been added.
16:26:29.288 [INFO ] [marthome.event.ItemStateChangedEvent] - samProgramTitle changed from NULL to SOKO Wien
````
The item is configured as:
````
String samProgramTitle "Program Title [%s]" 
````
Removing the formatting info ("[%s]") does not change the behaviour.

In the sitemap it appears as:
**Program Title**      SOKO WIEN

I am not sure whether this a problem of this binding or a general openHab issue.

**Comment by MHerbst** [comment]
I did some further research and checked the HTML code of the Basic UI. Here I found the reason for the uppercase letters: in smarthome.css the class "mdl-form__control" contains "text-transform: uppercase". I am not sure whether this is a bug or a feature.
Is it possible to overwrite this behaviour with an own CSS file?

**Comment by kaikreuzer** [comment]
@resetnow I assume this was meant to be a feature, could you comment on it?

**Comment by resetnow** [comment]
It was meant to be a feature, yes. This was done because in material design it is recommended to capitalize the text in certain places (like buttons and actions). In my opinion, it looks better this way too. 

I would recommend using Stylish browser extension. You can add the following style:

```css
.mdl-form__value {
    text-transform: none !important;
}
```

This way you can tune the stylesheet the way you want.

**Comment by watou** [comment]
> In my opinion, it looks better this way too.

It would be cool to have an option in the Basic UI (as opposed to needing a browser extension) for those who disagree! :smile:

**Comment by resetnow** [comment]
I just don't want to flood the configuration with lots of options. I suggest to wait some time to see how many people are affected by this.

**Comment by MHerbst** [comment]
> I just don't want to flood the configuration with lots of options
I absolutely agree with you. But I think it would be nice to have a user-specific stylesheet where one could overwrite the styles in smarthome.css. This would allow e.g. to use other colours or fonts or ...

**Comment by watou** [comment]
It is a matter of preference and my opinion is one of very many, but forcing all text to uppercase unless the source is patched or a browser extension is used, is not to my liking, and potentially obscures true state values should one want to write rules against them, for example.

**Comment by resetnow** [comment]
@watou do you think an option to use a custom CSS file would solve the problem?

**Comment by resetnow** [comment]
I just remembered there are other things which are CSS-related too and require an option. So, yes, there will be an option to disable capitalization.

**Comment by kaikreuzer** [comment]
>  potentially obscures true state values

This is also my main concern - all other UIs show the states as they ARE and don't do any changes to them; I would prefer to have this as the default in the Basic UI as well. If a user wants to "prettify" his UI appearance, he could then enable to option to have it al capitalized.

**Comment by resetnow** [comment]
#1005
