### ISSUE TITLE
Squeezebox addon not initializing when manually config things file

### ISSUE THREAD

**Issue by hans99** [openhab/openhab2-addons#656]
Added Bridge and Things in a "squeezebox.things" file as:
Bridge squeezebox:squeezeboxserver:X[ ipAddress="1.2.3.4", webport=9000, cliport=9090 ]
Thing squeezebox:squeezeboxplayer:X:Y[ mac="00:01:02:03:04:05" ]

Both show up in "paper-ui" under things and the bridge is "ONLINE" but at least in my debugging the things never gets the "bridgeHandlerInitialized" and stays in "INITIALIZING".

Could it be something to do with naming, since "discovery" looks like using mac as name?
##

**Comment by jhuizingh** [comment]
It seems this issue may be out of date. The configuration for the .things is now

```
Bridge squeezebox:squeezeboxserver:myServer [ ipAddress="192.168.1.10", webport=9000, cliport=9090 ]
{
    Thing squeezeboxplayer myplayer[ mac="00:f1:bb:00:00:f1" ]
}
```

according to https://github.com/openhab/openhab2-addons/tree/master/addons/binding/org.openhab.binding.squeezebox.

**Comment by mhilbush** [comment]
Since the documentation has been updated to reflect the correct .things configuration, I believe this issue can be closed.
