### ISSUE TITLE
[shelly] Provide information to install 2.5 release on 2.4 and 2.5M3..M6

### ISSUE THREAD

**Issue by markus7017** [openhab/openhab2-addons#6570]
Version 2.5 does no longer package the Californium libraries with the Shelly binding jar.
openHAB 2.5 provides the platform feature &lt;openhab-transport-coap&gt;

To support existing installations we need to provide some information how to install the 2 Californium libs before installing the Shelly binding (maybe as file copy in the addons folder or bundle:install, both from a defined source).

**Comment by kaikreuzer** [comment]
No, this is not officially supported. People who want to use the binding, should use the 2.5 runtime, which includes the binding.

**Comment by markus7017** [comment]
In don't mean as part of the release, but as additional information e,.g. in the community thread
Don't expect that all users will move to a fresh release asap.

**Comment by kaikreuzer** [comment]
If it isn't code related, it should not be here in the issue tracker, that's why I closed it.
