### ISSUE TITLE
PaperUI: no link to /control from menu

### ISSUE THREAD

**Issue by azim0ff** [openhab/openhab2-addons#658]
I noticed the menu in upper left corner does not have a link that would take the browser to `/ui/index.html#/control` which is the main control panel. How to navigate back to control panel after changing settings/configuration? Right now, the only way I can do it is by typing `/control` directly into the address box in the browser.

**Comment by kaikreuzer** [comment]
> which is the main control panel.

No, it is not - the main control UIs are the Classic UI, the Basic UI or the native smartphone apps.
The Paper UI controls are not yet ready for users, that's why openHAB 2 does not include them yet.

**Comment by azim0ff** [comment]
But what to do in the meanwhile? PaperUI used to take you to the control panel if you closed whatever window you were in ('x' in upper right).

**Comment by kaikreuzer** [comment]
> But what to do in the meanwhile?

Many options:
- use the other apps as stated above
- wait and see
- help implementing stuff like [this](https://www.eclipse.org/forums/index.php/t/1072530/) or [that](https://github.com/eclipse/smarthome/issues/1039).

**Comment by azim0ff** [comment]
Correct me if I am wrong, but other apps don't do discovery.

I am working on a binding/device(s) combination and I am targeting PaperUI. I would like to use it in whatever state it currently is. However, I am finding it hard to work with the menus without a way to go to the control panel without typing in the URL. That is all I am trying to say.

**Comment by kaikreuzer** [comment]
Correcting you: HABmin and the Android app also support discovery, also the shell supports it. And it does not matter: Discovery is not a feature of a UI, but of the runtime.

> and I am targeting PaperUI

You cannot target a specific UI from a binding. Binding implementations must not have any direct link to UIs.

> hard to work

Is your "work" the testing of the binding and thus you need it for playing around? In that case, you can switch to the "pure" ESH mode of the Paper UI by removing the fragment `org.openhab.ui.paperui` from your launch config.

**Comment by azim0ff** [comment]
> Discovery is not a feature of a UI

Indeed, but you must use a UI that supports it. Hence my "targeting" of PaperUI. I did not know about Android app and HABmin being able to do this also. I will try them out in the coming days.

> In that case, you can switch to the "pure" ESH mode

Yes! Thank you, that's what I was looking for.
