### ISSUE TITLE
MQTT - no operation after upgrade to 2.5.0RC1

### ISSUE THREAD

**Issue by s0170071** [openhab/openhab2-addons#6594]
HW: RPi4
SW: openhabian, Mosquitto, MQTT v2 binding

I had it all up and running for over a year, however, when I upgrade to 2.5.0 MQTT fails silently. 
MQTTFx shows there is activity on Mosquitto, however, it is not going in or out the event bus. 

Log shows: 
`2019-12-09 21:08:25.934 [INFO ] [.transport.mqtt.MqttBrokerConnection] - Starting MQTT broker connection to '192.168.1.52' with clientid 5e577693-853c-4ef4-a2bd-d26330bd9da4`

Odd thing: the IP x.x.x.52 used to be my old RPI3 hardware, the current RPI4 uses x.x.x.30
although I updated mqtt.cfg: 
`raspimqtt.url=tcp://192.168.1.30:1883
`
In paperUI, Configuration > Things > Edit > MQTT Broker also shows 192.168.1.30

When I downgrade to OH 2.4.0 stable, things work as expected, even with the RPi4  x.x.x.30 MQTT server. Nothing was configured with paperUI except for the binding installation.
And yes, I did countless reboots...

**Comment by J-N-K** [comment]
And you did not use „search“. This was reported multiple times and is fixed.

**Comment by s0170071** [comment]
solved by clearing the cache: 
```
sudo systemctl stop openhab2 (openhab-cli stop did not work, Msg: `Can't connect to the container. The container is not running.`)
openhab-cli clean-cache
openhab-cli start
```

@J-N-K I would consider this fixed if the cache was cleared automatically during the upgrade.
