### ISSUE TITLE
Shelly Dimmer thing can set dimmer value without turning ON light

### ISSUE THREAD

**Issue by VanadiumJade** [openhab/openhab2-addons#6599]
Shelly Dimmer (N line)
The thing from Paper UI doesnt have a power option available to assign to an item.
As a result you can see status of light (on or off)
Openhab 2.5RC1
shelly binding installed from addon screen
Shelly is up to date with  20191127-095910/v1.5.6
I setup shelly1PM this works as expected (just dimmer doesnt work)

## Expected Behavior
Paper UI should have power object so it can be assigned an item
Shelly should send output action on url and openhab binding should update item

## Current Behavior
No power object is available in paper ui and as a result you cant assign an item to the power object.
Openhab is unable to see state of object

## Possible Solution
add power object to paper ui

## Steps to Reproduce (for Bugs)
install shelly binding
add automaticly detected shelly dimmer
no power object available

## Your Environment
Openhab 2.5RC1
Docker image openhab/openhab:2.5RC1
Dell power edge r710 server / vmware / ubuntu / docker

**Comment by hmerk** [comment]
Did you check the Readme ? The power switch has to be bound to the brightness channel. This is the same for all Dimmer devices in openHAB.
Also, please consider upgrading to openHAB 2.5 stable release from last night.

**Comment by VanadiumJade** [comment]
Thanks I didn't see that. I don't use paper ui for control.

The device treats brightness and output separately. How it works now is like an old stereo when volume knob and power are on same knob.

Gives you the control to change brightness by time or any other rule you want. So can preload a brightness before switch on wall is used.

For example I want to set my 6 months baby's light to 10% from 7pm and 1% from 9pm then back to 100% at 7am. Then when ever my wife turns on the light at the switch or via app it's already at correct brightness.

I am doing this with 2.4. With mqtt and I could do this with this 2.5 binding and using Mqtt or http binding and some rules. But tbh it's a bit of a hack.
I would like to know what the brightness is set to when device output is off.

Would really love if there was a separate control for power and brightness.
Maybe keep the current channel so people can choose what way they want to control of people are strong on that method.

**Comment by hmerk** [comment]
In openHAB, a brightness channel nit just accepts percentage values, but ON/OFF also. This is why you can add a switch item to the brightness channel. Switching the device through this channel will store the last value in case of an OFF command or restore the last value in case of an ON command.
Changing the brigthness while switched off should just update the stored value.
So this would perfectly cover your usecase.

**Comment by VanadiumJade** [comment]
> Changing the brigthness while switched off should just update the stored value.

This is not my experience right now.

**This is my scenario:**
I want to run a rule to set all lights to 10% at 11pm. (or even different %s depending on room)

**Current state:**
if I set the value of the dimmer item - it will set the brightness **(but if the brightness request is above zero then the light will turn on too)**
**This will make kids and then wife very unhappy!**

I would also like like to see what the % is now even if switch is off. Currently if you switch the light off the brightness gets nulled. if you then update the brightness above zero then it will turn on the light to that brightness.

I might be misunderstanding please explain how I can obtain this solution with current binding?

Thanks Jade

**Comment by VanadiumJade** [comment]
> Also, please consider upgrading to openHAB 2.5 stable release from last night.

I have struggled to find the stable 2.5 docker tag - I have tried openhab/openhab:latest (that just gets 2.4)
so the latest one I could find was 2.5.0.RC1

Thanks in advance.

**Comment by hmerk** [comment]
Sorry, my bad, i checked again and confirm this behavior, which is the intended according to openHAB semantics.
Please change the title of this issue to something like feature request for nightmode settings. We will check how such a feature can be implemented
According to your docker issue, please check the community, there are post around this already.

**Comment by VanadiumJade** [comment]
I have raised an enhancement for this feature
