### ISSUE TITLE
Using ESH Paper UI instead of OpenHAB 2 Paper UI on Offline Distro

### ISSUE THREAD

**Issue by iakko** [openhab/openhab2-addons#678]
Hello there,

I'm not sure if this is the right place to ask, sorry about that, but I'm using the Offline Distro environment found [here](http://www.openhab.org/getting-started/downloads.html) to test OpenHAB 2 and I'm trying to figure out how to use the native ESH Paper UI instead of the OpenHAB version.

Looking around I found this [link](https://github.com/openhab/openhab2-addons/issues/658) that explains how to exclude the OpenHAB version, but it relates to the pure OSGi version, while the current Offline Distro uses Karaf, which is really new to me.

I've tried to uninstall the bundle from the OpenHAB Karaf console, but even if the bundle is no more present, I'm still getting it running and appears when I launch the browser. Do someone know how to setup the environment to give the ESH Paper UI?

Thanks!
IP

**Comment by iakko** [comment]
Ok, I guess I did a mistake, I can see an **openhab-distro** GitHub project, I've posted the same [here](https://github.com/openhab/openhab-distro/issues/143). Sorry guys.

**Comment by kaikreuzer** [comment]
No worries, closing it here then!
