### ISSUE TITLE
Z-Wave feature request:  download zwave network to secondary controller

### ISSUE THREAD

**Issue by TheKorn2** [openhab/openhab2-addons#714]
habmnin2 feature request:  button to force download network to secondary controller from primary zwave controller when openhab's controller is not the primary controller.

**Comment by cdjackson** [comment]
This is implemented (I think!). I recently implemented an option to synchronise the network with other controllers - this will send a request to the SUC to download any updates to the network.

I think this is what you are looking for?

#1162

**Comment by cdjackson** [comment]
Going to close this as we're moving home and I think it's resolved. If there's further work then please open a new issue [in the new Z-Wave repository](https://github.com/openhab/org.openhab.binding.zwave/issues).
