### ISSUE TITLE
Lifx Eclipse Smarthome Binding has been updated

### ISSUE THREAD

**Issue by hadees** [openhab/openhab2-addons#720]
The [Lifx Eclipse Smarthome Binding](https://github.com/eclipse/smarthome/pull/483) has been updated to use the new LIFX api.

**Comment by kaikreuzer** [comment]
Right, but why enter an issue about it here?

**Comment by hadees** [comment]
@kaikreuzer i guess I thought it had to added here in order to be added into openhab2.  I'm not really sure the correct way to add a Eclipse Smarthome binding to Openhab2.

**Comment by maggu2810** [comment]
The ESH bindings are wrapped by this file:
https://github.com/openhab/openhab-distro/blob/master/features/openhab-esh-addons/src/main/feature/feature.xml

**Comment by maggu2810** [comment]
You can see, that there is already the LIFX binding.
For a new version you have to wait for a new ESH build that is used by OH

**Comment by kaikreuzer** [comment]
No need to wait for anything, it is already part of the openHAB distro since March 1, see https://hudson.eclipse.org/smarthome/job/SmartHomeDistribution-Stable/changes
