### ISSUE TITLE
Feed binding 

### ISSUE THREAD

**Issue by svilenvul** [openhab/openhab2-addons#724]
Hello everybody,
I have implemented a binding that integrates Web Feed with openHAB. I thought that it can be used to provide other devices with feed data in XML format. 

This binding will have the following features:
- Fetch feed data from URL 
- Convert different feed formats to one output format (e.g. Atom 1.0)
- Check regularly for updates 
- Stores predefined number of feed entries 
- Handle REFRESH command, send to the channel.

The binding is using the [ROME](http://rometools.github.io/rome/) library , so a wide range of feed formats is supported - RSS 0.90, RSS 0.91 Netscape, RSS 0.91 Userland, RSS 0.92, RSS 0.93, RSS 0.94, RSS 1.0, RSS 2.0, Atom 0.3, Atom 1.0.
##

**Comment by svilenvul** [comment]
I can see that some users in the [forum ](https://community.openhab.org/t/output-rss-feed/4268) requested to push item data in RSS format. Please share your opinion, if this would be a good enhancement to the #762  ?

**Comment by svilenvul** [comment]
As discussed with Kai Kreuzer, in the PR, the feed convert functionality will be moved to a Transformation Service.

@kaikreuzer, should you create a PR in the eclipse/smarthome repository for the Transformation Service? All the Transformation Services, that I have found, are located there.

**Comment by kaikreuzer** [comment]
> @kaikreuzer, should you create a PR in the eclipse/smarthome repository for the Transformation Service? 

You are right, currently they all are at ESH.
It probably depends a bit on how much code you need to share and what external libs are required for the transformation service. Can you already say if code needs to be shared (you say that the binding can be used independently of the transformation service, so is hence no sharing required?) What 3rd party libs will you need for the transformation?

**Comment by svilenvul** [comment]
@kaikreuzer
I will need the same 3rd party libs as for the binding - [ROME](https://github.com/rometools/rome/tree/master/rome) and [jdom](https://github.com/hunterhacker/jdom/)
Currently the binding is not dependent on any other bundle and it is not using this transformation service. (no sharing is required).

**Comment by kaikreuzer** [comment]
> no sharing is required

Well, sharing is required if you split the code in two bundles and they both require ROME and jdom - you definitely should not put these libs into both bundles.
So coming back to your question above: I think it is simpler if you also create the transformation add-on in the OH2 repo - we won't require CQs at ESH then and the add-on is pretty related to the feed binding anyhow.

**Comment by staehler** [comment]
Hi,
I like the idea of your feed binding. Would it also be possible, to generate a feed, e.g. from events?
I'ld like to present a feed of some important events on my mobile feed reader or I would like to generate a feed of my daily appointments, which could be streamed on my squeezebox display.

Rules generate a stringtriggered by an event, which is sent as a new feed post.

Is this request the right place here?

Best regards,
Michael

**Comment by svilenvul** [comment]
Hi @staehler,

I am happy to hear, that you find the binding useful.

> Would it also be possible, to generate a feed, e.g. from events?

Yes, the library that is used supports writing feeds. Should this be a part of the binding is another question that I can't give an answer.

**Comment by staehler** [comment]
@svilenvul 
Do you feel to implement such a feature in your binding? Otherwise I could create an issue with this feature request. 
It should be something like the logInfo method, like
rss ("feedname", "this is my feed text and this is an item state:" + item.state)
The feedname is already defined as a thing.

Kind regards,
michael

**Comment by svilenvul** [comment]
Please create an issue with this feature request, this sounds really cool, but I don't think I will find soon time.

BR,
Svilen

**Comment by wborn** [comment]
This binding is available since openHAB 2.0.0.

**Comment by nishant2019** [comment]
How can I see multiple item with  feed binding
