### ISSUE TITLE
Zwave: Wake-up enhancement

### ISSUE THREAD

**Issue by jspuij** [openhab/openhab2-addons#737]
While I was upgrading from 1.6 to 2.0 the following happened:

I decided to have the binding autodiscover all devices and also create new XML files for the nodes. So it was like starting the binding for the first time with an existing, fully configured Z-wave network. As expected all powered nodes were discovered pretty fast.

However my battery operated devices took between a couple of hours to a whopping 3 days to appear in the inbox as discovered items. This is of course because of the short wake-up time and the large wake-up intervals (between 1 hour and several hours) I have configured on the nodes to preserve battery usage.

Now I'm pretty experienced with Z-wave, but a novice user would probably have reset the binding effectively resetting the node advancer and making matters worse.

I could have lowered the wake-up interval value with the old binding or openzwave-control-panel to speed up initialization, but of course it would be nicer to have the binding take care of this automatically. Therefore I propose the following enhancement:
- During node initialization of a battery node when a WAKEUP_NOTIFICATION is received, first a WAKEUP_GET is sent to retreive the current wakeup interval(s) and report node.
- Subsequently WAKUP_SET is sent with a short interval (have to look up a minimum value but 30 to 60 seconds, seems reasonable) during initialization.
- After initialization the last command to the node is WAKEUP_SET with the original values.

Probably the original values need to be persisted somehow to be able to reset the original values if the binding is stopped and started during discovery. This way we prevent accidental increased battery consumption because of a stopped or crashed binding.

Does this seem like a good idea? I'd love to implement this, as I'm quite rusty with the current code base as so many good things have happened while I was away.

Anyway just my two cents. Feel free to comment.
##

**Comment by cdjackson** [comment]
I agree - it was always a concern and something Ive been pushing to resolve in ESH…

I think the guts of this problem will go away tomorrow… Originally, we had to know the device data for discovery of a device to be fed into the inbox as we had to know it’s thing-type, and this takes time with battery devices. A month or so back there was an addition into ESH to allow changing thing types after they are created and now the device will go into the inbox immediately on startup/discovery. It still won’t be available for use until after discovery is completed the first time, but at leat it is visible to people.

We could do something with wakeup, but I’d suggest this might not be necessary once this change is included (which is today - there’s a binary on the HABmin site if you want to test). Once this is complete, then it will work in the same way as it did in OH1 with respect to visibility of devices at least...

I’m not against the idea, but also it adds some complexity that might not be needed. Another thing that may also help that was discussed a while back (but I can’t remember if it was implemented) is to increase the awake time when the device is initialising - this would be simpler since it doesn’t require updating the device configuration and persisting information...

**Comment by jspuij** [comment]
Yeah, changing thing types was a second idea. As now the thing-id depends on e.g.  the application version, which is late in the proces to query. But still no channels (ok, maybe basic) will be created during initialization before the final thing-id is known. You could use the discovered thing to set the wake-up interval, but still, the nicest way is to temporarily shorten the wake-up interval.

As for extending the awake time, I have seen some WAKEUP_NOMOREINFORMATION in my logs, which is strange while initialization is not complete, but even then, my fibaro door sensors have such a short non configurable timeout and are also far in my network, so they need to be relayed, that only 1 to 3 messages are processed each cycle.

Since OpenHAB2 is pushing for user friendlyness, I feel we can help the novice (and advanced) user by temporarily shortening the wake-up interval.

I'd rather find better ways to prevent accidental draining of the battery than prolonging discovery and initialization of battery nodes.

**Comment by cdjackson** [comment]
> I have seen some WAKEUP_NOMOREINFORMATION 

Yes - this is what I meant to hold off, but you are right, some devices already set a maximum time that is very short...

> I'd rather find better ways to prevent accidental draining of the battery than prolonging discovery and initialization of battery nodes.

What do you mean? My concern would be if we set the wakeup time to (say) 30 seconds, that it gets left there. From memory, once the wakeup is 1 hour or so, it makes little difference to battery life if you make it 1 hour or 1 day (I spent some time a while back to calculate this). If it gets left at a very low period, then it’s game over quite quick.

I think the change in the latest binding will stop your original issue at least. If you want to make a PR with this feature, then feel free to do so and we can see how it looks… As I said earlier, I’m not against it, but I’d want to be sure we can’t leave wakeup as a low value...

**Comment by jspuij** [comment]
> What do you mean? My concern would be if we set the wakeup time to (say) 30 seconds, that it gets left there. From memory, once the wakeup is 1 hour or so, it makes little difference to battery life if you make it 1 hour or 1 day (I spent some time a while back to calculate this). If it gets left at a very low period, then it’s game over quite quick.

This is what I mean and I agree that this is the weak point of the solution. Proper persistence and recovery is key. Also if the node advancer detects many retries or slow progress in advancement it could decide to give up and reset the battery interval.

Another idea I already had while I was active (and you probably as well) is to persist progres of node advancement so you can pick up where you left off, when restarting the binding, not just when the node information is complete to be serialized.

**Comment by wborn** [comment]
If this is still an issue it shoud be added to the [ZWave issues tracker](https://github.com/openhab/org.openhab.binding.zwave/issues).
