### ISSUE TITLE
Basic UI: format string not used on asynchronous update of item in basic ui. 

### ISSUE THREAD

**Issue by jspuij** [openhab/openhab2-addons#743]
I have a couple of items in my .items files with format strings, e.g:

`Number Power_Powerbar_Subwoofer "Subwoofer actueel verbruik  [%.1f W]" (GF_Living,GF_Energy)` 

When first opening the basic ui, the format string is used. On subsequent asynchronous updates however, the format string is ignored. See attached files.

before:

<img width="1086" alt="schermafbeelding 2016-03-17 om 00 24 21" src="https://cloud.githubusercontent.com/assets/985974/13831908/714393e4-ebd7-11e5-9ec7-c5f50763ab18.png">

after:

<img width="1085" alt="schermafbeelding 2016-03-17 om 00 23 52" src="https://cloud.githubusercontent.com/assets/985974/13831907/713ff842-ebd7-11e5-8558-4edcb58cabf4.png">

**Comment by shorty707** [comment]
See
https://github.com/eclipse/smarthome/issues/640

**Comment by jspuij** [comment]
OK, wrong repository then. Thanks.
