### ISSUE TITLE
BasicUI: renders "mappings" vice versa

### ISSUE THREAD

**Issue by shorty707** [openhab/openhab2-addons#750]
Switch item=sonos_zoneplayer_RINCON_5CAAFD4404DA01400_control label="Control" mappings=[PREVIOUS='<<', PLAY='>', PAUSE='||', NEXT='>>'] icon="player"

BasicUI
![zz](https://cloud.githubusercontent.com/assets/13987575/13905028/41af7000-eeb4-11e5-860b-d480a9520f6c.JPG)

ClassicUI
![zz3](https://cloud.githubusercontent.com/assets/13987575/13905030/47d3c90e-eeb4-11e5-9d2c-2411f0b9ed3f.JPG)

**Comment by watou** [comment]
Sorted alphabetically?

**Comment by kaikreuzer** [comment]
Classic UI does it as expected, so it looks like a bug in the Basic UI - please report at https://github.com/eclipse/smarthome/issues.
