### ISSUE TITLE
RFXCOM Energy Meter issue

### ISSUE THREAD

**Issue by mccaffm** [openhab/openhab2-addons#754]
Im getting the following when trying to add and energymeter thing in paper UI

> 2016-03-22 19:39:00.772 [ERROR] [home.core.thing.binding.ThingFactory] - Thing factory (class org.openhab.binding.rfxcom.internal.RFXComHandlerFactory) returned null on create thing when it reports to support the thing type (rfxcom:energyusage).
2016-03-22 19:39:00.787 [WARN ] [g.discovery.internal.PersistentInbox] - Cannot create thing. No binding found that supports creating a thing of type rfxcom:energyusage.

my coding skills are as ancient as I am but i think the problem is in openhab2-addons/addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/RFXComBindingConstants.java

line 162 reads 

`.put(PacketType.ENERGY, RFXComBindingConstants.THING_TYPE_ENERGY_USAGE)`

but i have a sneaky suspicion it shoud read

`.put(PacketType.ENERGY_USAGE, RFXComBindingConstants.THING_TYPE_ENERGY_USAGE)`

of course i may be talking absolute rubbish, in which case  - i cant add an energy monitor to RFX

**Comment by mccaffm** [comment]
@paulianttila is my analysis correct ?

**Comment by paulianttila** [comment]
@mccaffm: I agree that energy message does not work correctly. Reason seems to be that, thing descriptor file have incorrect type id. Type id is "energy" though it should be "energyusage".

I will create pull request soon.

**Comment by mccaffm** [comment]
Thanks Pali, I thought it had not been noticed.

M

**Comment by mccaffm** [comment]
any plans to address this in the short term @paulianttila

**Comment by lumachan** [comment]
Same issue here with an energy meter (OWL Micro +)

I can't find anymore the PR build on Cloudbees. So I can't test. 

@mccaffm : could you post a jar somewhere ?

Thanks

**Comment by mccaffm** [comment]
Try getting it from here

https://1drv.ms/u/s!Aof7D8ZClXFOgZ1yBGWJw4BVqq5ZBw
