### ISSUE TITLE
OH2 Beta 2 - Paper UI - Inbox Issue

### ISSUE THREAD

**Issue by p5ych017** [openhab/openhab2-addons#760]
After initial startup the paper ui is not reacting.
I cannot click anything. Reboot doesn't help.

![bug](https://cloud.githubusercontent.com/assets/15014519/14044897/678f2d8a-f295-11e5-98e5-af5773d6ae12.JPG)

I had to install JDK that the "Server-mode" warning disappears.
The JAVA_HOME variable has to be set...otherwise OH2 won't start!

Config is default

Enabled addons:
org.openhab.binding.exec-1.8.2
org.openhab.binding.sonos-1.8.2
org.openhab.binding.samsungtv-1.8.2

Any ideas?

**Comment by kaikreuzer** [comment]
Latest snapshot from https://openhab.ci.cloudbees.com/job/openHAB-Distribution/ works fine.

Please report future problems with the distribution at https://github.com/openhab/openhab-distro - thanks!
