### ISSUE TITLE
binding.avmfritz detect Powerline 1240E as 546E

### ISSUE THREAD

**Issue by renenulsch** [openhab/openhab2-addons#763]
latest OH2 snapshot. 

The avmfritz binding detects the 1240E PowerLine adapter as a 546E.

The 1240E has no power consumption interface.
##

**Comment by cweitkamp** [comment]
Hey there, I am going to look into this. First of all by adding all FRITZ!Powerline devices to the thing type defining xml file. Hope that helps.

**Comment by martinvw** [comment]
@renenulsch did you ever retest this? Does it work?

If you did not test can you please test it then, thanks!

**Comment by renenulsch** [comment]
Hi Martin,

Thank you, I‘ve switched to an different home automation platform to implement my requirements and I can‘t retest this.

Sorry
BR
René


Am 03.11.2017 um 16:13 schrieb Martin van Wingerden <notifications@github.com<mailto:notifications@github.com>>:


@renenulsch<https://github.com/renenulsch> did you ever retest this? Does it work?

If you did not test can you please test it then, thanks!

**Comment by martinvw** [comment]
Thanks for the message and sorry to see you go :-)
