### ISSUE TITLE
Add Froeling Binding

### ISSUE THREAD

**Issue by codeworkx** [openhab/openhab2-addons#771]
Just want you let to know that i'm working on a Froeling binding which will allow to get data from Froeling furnace controllers.

I'm currently testing on a Froeling PE1 Pellet (http://www.froeling.com/en/products/pellet/pe1-pellet.html) with P3200 touch controller.
It's being accessed on controller com port 1 via Korenix JetPort Serial-to-LAN converter.

It's already working quite good but still needs some work and cleanup:
https://github.com/codeworkx/openhab2-addons

Testbuild (copy jar to addon folder):
https://www.codeworkx.de/dl/openhab/
##

**Comment by kaikreuzer** [comment]
nice, thanks for the info!

**Comment by ooswald** [comment]
great, will give it a try

**Comment by codeworkx** [comment]
The lan port used for froeling connect? Thats not the same and doesnt allow reading the data as easy as the serial port does.

**Comment by codeworkx** [comment]
Afaik the froeling controller tries to establish a VPN connection to froeling (connectcmd.froeling.com, connectvpn.froeling.com, connect1.froeling.com, connect2.froeling.com) and will then communicate with their backend. If you manage to crack the encryption and create a backend which is acting exactly like the froeling server then there's a chance. But that will never happen. ;-)

**Comment by Gardener74** [comment]
Alright, just wondered. Thanks for your support and the link. Will try it using the Serial to LAN converter.

**Comment by davidgraeff** [comment]
Please reopen or provide a pull request to the official openhab repository.

That way you have advantages like the maintainers will care about infrastructure and API changes.
