### ISSUE TITLE
module.timer.test module fails to compile

### ISSUE THREAD

**Issue by 9037568** [openhab/openhab2-addons#774]
[INFO] Eclipse SmartHome Automation Timer Modules ......... SUCCESS [  0.490 s]
[INFO] Eclipse SmartHome Automation Module Timer Tests .... FAILURE [  0.733 s]
[INFO] Eclipse SmartHome Automation Script Modules ........ SKIPPED
...
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-surefire-plugin:0.23.1:test (default-test) on project org.eclipse.smarthome.automation.module.timer.test: Execution default-test of goal org.eclipse.tycho:tycho-surefire-plugin:0.23.1:test failed: Cannot resolve dependencies of MavenProject: org.eclipse.smarthome.bundles:org.eclipse.smarthome.automation.module.timer.test:0.8.0-SNAPSHOT @ C:\Users\Jack\openhab2-master\git\smarthome\bundles\automation\org.eclipse.smarthome.automation.module.timer.test\pom.xml: See log for details -> [Help 1]

**Comment by kaikreuzer** [comment]
Shouldn't this be rather reported at https://github.com/eclipse/smarthome/issues?
