### ISSUE TITLE
Z-wave device (Aeon) ZW075 not working in OH2

### ISSUE THREAD

**Issue by mdilger** [openhab/openhab2-addons#790]
Sorry Chris, I hope I am in the right place this time  (x2....)  ??

Anyway, hope you can help. Please let me know if you need any more detail.

I have a number of devices that are working perfectly with the latest snaphot of OH2, latest binding and latest HABmin2. The one exception is the ZW075 power switch. I have checked the database and the device is present but for some reason I am unable to configure it.

![habmin2 screen](https://cloud.githubusercontent.com/assets/14153720/14452248/8023a86c-00e1-11e6-87b9-2b2c657e2ae1.PNG)

The device itself is working correctly when I use the Zensys PC controller.

![zwave controller screen](https://cloud.githubusercontent.com/assets/14153720/14452252/8303b5f4-00e1-11e6-8aa7-54ff31f299ed.PNG)

Hopefully the issue is something obvious and easy to solve.

Cheers,
Mike

**Comment by cdjackson** [comment]
Thanks for moving the issue over here :)

I just checked the database and your device isn't in there (the type/id for your device is different). I'll add your codes in tonight.

**Comment by mdilger** [comment]
Thanks for that.

What do I need to do tomorrow to check and confirm all OK? Just download a new snapshot of the binding or...

Sorry, but I am a newbie to OH2.

Mike

**Comment by cdjackson** [comment]
Yes - assuming I get this into the build chain tonight, then you should be able to use paper ui to uninstall, and then re-install the binding which should grab the updated build.

**Comment by mdilger** [comment]
Thanks, no hurry.  I have been trying to sort this for a few days myself before asking for help.  I have been readind and am learning heaps about z-wave at present ;-) 

I am planning to to start with MQTT tomorrow.

**Comment by mdilger** [comment]
Thank you Chris, all sorted. Cheers, Mike
