### ISSUE TITLE
ZWave - Dimmer fluctuating values

### ISSUE THREAD

**Issue by christianwaite** [openhab/openhab2-addons#794]
I have a thread on the community but it's going unanswered. I am of the thinking this is a bug rather than a setup issue as it's all pretty standard and only these particular devices display this kind of behaviour (the TKB Dimmer Plug UK).
https://community.openhab.org/t/dimmer-slider-springs-back-doesnt-hold-state/7961/9

Here is latest log:
http://pastebin.com/Ke8BNjCj

And a more verbose log:
http://pastebin.com/ELkLmadV

**Comment by cdjackson** [comment]
I think it’s unlikely this is the zwave binding, but if you provide a debug log, I’m happy to take a look.

**Comment by cdjackson** [comment]
Ah - and also, if possible, please provide a short log only that shows the time around when you sent the command. IF you want to provide a longer log, then please tell me what time you changed the configuration so I know where and when to look.

Thanks.

**Comment by christianwaite** [comment]
Thanks, I've run in debug and tried to nab the relevant bit.
You can see here it goes from 22 to zero, then back to 22 again.

23:42:03.619 [DEBUG] [org.eclipse.jetty.server.HttpChannel] - HttpChannelOverHttp@19d7cec9{r=1,c=false,a=DISPATCHED,uri=/rest/items/bedroom_lamp1} action REQUEST_DISPATCH
23:42:03.619 [DEBUG] [org.eclipse.jetty.server.Server     ] - REQUEST POST /rest/items/bedroom_lamp1 on HttpChannelOverHttp@19d7cec9{r=1,c=false,a=DISPATCHED,uri=/rest/items/bedroom_lamp1}
23:42:03.619 [DEBUG] [ax.web.service.spi.model.ServerModel] - Matching [/rest/items/bedroom_lamp1]...
23:42:03.620 [DEBUG] [ax.web.service.spi.model.ServerModel] - Path [/rest/items/bedroom_lamp1] matched to {pattern=/rest/.*,model=ServletModel{id=org.ops4j.pax.web.service.spi.model.ServletModel-4,name=org.ops4j.pax.web.service.spi.model.ServletModel-4,urlPatterns=[/rest/*],alias=/rest,servlet=com.eclipsesource.jaxrs.publisher.internal.ServletContainerBridge@14def055,initParams={},context=ContextModel{id=org.ops4j.pax.web.service.spi.model.ContextModel-3,name=,httpContext=DefaultHttpContext [bundle=com.eclipsesource.jaxrs.publisher_5.3.0.201512270850 [12], contextID=default],contextParams={},virtualHosts={},connectors={}}}}
23:42:03.620 [DEBUG] [.jetty.server.handler.ContextHandler] - scope null||/rest/items/bedroom_lamp1 @ HttpServiceContext{httpContext=DefaultHttpContext [bundle=com.eclipsesource.jaxrs.publisher_5.3.0.201512270850 [12], contextID=default]}
23:42:03.620 [DEBUG] [.jetty.server.handler.ContextHandler] - context=||/rest/items/bedroom_lamp1 @ HttpServiceContext{httpContext=DefaultHttpContext [bundle=com.eclipsesource.jaxrs.publisher_5.3.0.201512270850 [12], contextID=default]}
23:42:03.620 [DEBUG] [org.eclipse.jetty.server.session    ] - sessionManager=org.ops4j.pax.web.service.jetty.internal.LateInvalidatingHashSessionManager@4064ef32
23:42:03.621 [DEBUG] [org.eclipse.jetty.server.session    ] - session=null
23:42:03.621 [DEBUG] [eclipse.jetty.servlet.ServletHandler] - servlet |/rest|/items/bedroom_lamp1 -> org.ops4j.pax.web.service.spi.model.ServletModel-4@378be0fc==com.eclipsesource.jaxrs.publisher.internal.ServletContainerBridge,-1,true
23:42:03.621 [DEBUG] [ce.jetty.internal.HttpServiceContext] - Handling request for [/rest/items/bedroom_lamp1] using http context [DefaultHttpContext [bundle=com.eclipsesource.jaxrs.publisher_5.3.0.201512270850 [12], contextID=default]]
23:42:03.621 [DEBUG] [y.internal.HttpServiceServletHandler] - handling request org.ops4j.pax.web.service.jetty.internal.HttpServiceRequestWrapper@27e7ec5e, org.ops4j.pax.web.service.jetty.internal.HttpServiceResponseWrapper@5712af
23:42:03.622 [DEBUG] [eclipse.jetty.servlet.ServletHandler] - chain=null
23:42:03.624 [DEBUG] [org.eclipse.jetty.http.HttpParser   ] - parseNext s=CONTENT HeapByteBuffer@60d98e98[p=338,l=339,c=8192,r=1]={POST /rest/items/...ip, deflate\r\n\r\n<<<0>>>eflate\r\n\r\n==\r\nAcc...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
23:42:03.624 [DEBUG] [org.eclipse.jetty.server.HttpChannel] - HttpChannelOverHttp@19d7cec9{r=1,c=false,a=DISPATCHED,uri=/rest/items/bedroom_lamp1} content java.nio.HeapByteBufferR[pos=338 lim=339 cap=8192]
23:42:03.625 [DEBUG] [org.eclipse.jetty.http.HttpParser   ] - parseNext s=CONTENT HeapByteBuffer@60d98e98[p=339,l=339,c=8192,r=0]={POST /rest/items/...p, deflate\r\n\r\n0<<<>>>eflate\r\n\r\n==\r\nAcc...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
23:42:03.625 [DEBUG] [org.eclipse.jetty.http.HttpParser   ] - CONTENT --> END
23:42:03.626 [DEBUG] [org.eclipse.jetty.server.HttpChannel] - HttpChannelOverHttp@19d7cec9{r=1,c=false,a=DISPATCHED,uri=/rest/items/bedroom_lamp1} messageComplete
23:42:03.626 [DEBUG] [org.eclipse.jetty.server.HttpInput  ] - HttpInputOverHTTP@613a5b10 EOF
23:42:03.627 [DEBUG] [org.eclipse.jetty.io.ChannelEndPoint] - filled 0 SelectChannelEndPoint@1e67c3fd{/192.168.1.89:52022<->8080,Open,in,out,-,-,16/30000,HttpConnection}{io=0,kio=0,kro=1}
23:42:03.627 [DEBUG] [.eclipse.jetty.server.HttpConnection] - HttpConnection@490469fe{FILLING} filled 0
23:42:03.627 [DEBUG] [org.eclipse.jetty.server.HttpInput  ] - HttpInputOverHTTP@613a5b10 elf EOF
23:42:03.627 [DEBUG] [org.eclipse.jetty.server.HttpInput  ] - HttpInputOverHTTP@613a5b10 elf EOF
23:42:03.628 [DEBUG] [org.eclipse.jetty.server.HttpInput  ] - HttpInputOverHTTP@613a5b10 elf EOF
23:42:03.629 [DEBUG] [.jetty.server.handler.ContextHandler] - scope null||/rest/items/bedroom_lamp1 @ o.e.j.s.h.ContextHandler@65fdbd02{/static,null,AVAILABLE}
23:42:03.629 [DEBUG] [.jetty.server.handler.ContextHandler] - scope null||/rest/items/bedroom_lamp1 @ HttpServiceContext{httpContext=DefaultHttpContext [bundle=org.openhab.ui.habmin_2.0.0.201604102246 [48], contextID=default]}
23:42:03.630 [DEBUG] [.jetty.server.handler.ContextHandler] - scope null||/rest/items/bedroom_lamp1 @ HttpServiceContext{httpContext=DefaultHttpContext [bundle=org.openhab.ui.habmin_2.0.0.201604102246 [48], contextID=default]}
23:42:03.630 [DEBUG] [.jetty.server.handler.ContextHandler] - scope null||/rest/items/bedroom_lamp1 @ HttpServiceContext{httpContext=DefaultHttpContext [bundle=org.eclipse.smarthome.ui_0.8.0.201604082328 [122], contextID=default]}
23:42:03.630 [DEBUG] [.jetty.server.handler.ContextHandler] - scope null||/rest/items/bedroom_lamp1 @ HttpServiceContext{httpContext=DefaultHttpContext [bundle=org.eclipse.smarthome.ui.icon_0.8.0.201604082328 [123], contextID=default]}
23:42:03.630 [DEBUG] [.jetty.server.handler.ContextHandler] - scope null||/rest/items/bedroom_lamp1 @ HttpServiceContext{httpContext=DefaultHttpContext [bundle=org.openhab.io.rest.docs_2.0.0.201603280103 [142], contextID=default]}
23:42:03.630 [DEBUG] [.jetty.server.handler.ContextHandler] - scope null||/rest/items/bedroom_lamp1 @ HttpServiceContext{httpContext=DefaultHttpContext [bundle=org.openhab.ui.dashboard_2.0.0.201603280103 [143], contextID=default]}
23:42:03.630 [DEBUG] [.jetty.server.handler.ContextHandler] - scope null||/rest/items/bedroom_lamp1 @ HttpServiceContext{httpContext=DefaultHttpContext [bundle=org.eclipse.smarthome.ui.basic_0.8.0.201604082328 [144], contextID=default]}
23:42:03.630 [DEBUG] [.jetty.server.handler.ContextHandler] - scope null||/rest/items/bedroom_lamp1 @ HttpServiceContext{httpContext=DefaultHttpContext [bundle=org.eclipse.smarthome.ui.paper_0.8.0.201604082328 [147], contextID=default]}
23:42:03.631 [DEBUG] [.jetty.server.handler.ContextHandler] - scope null||/rest/items/bedroom_lamp1 @ HttpServiceContext{httpContext=org.jupnp.transport.impl.osgi.DisableAuthenticationHttpContext@7b5e16b7}
23:42:03.631 [DEBUG] [.jetty.server.handler.ContextHandler] - scope null||/rest/items/bedroom_lamp1 @ HttpServiceContext{httpContext=org.openhab.io.net.http.SecureHttpContext@7bea727a}
23:42:03.631 [DEBUG] [.jetty.server.handler.ContextHandler] - scope null||/rest/items/bedroom_lamp1 @ HttpServiceContext{httpContext=DefaultHttpContext [bundle=org.openhab.core_2.0.0.201603280103 [133], contextID=default]}
23:42:03.631 [DEBUG] [org.eclipse.jetty.server.Server     ] - RESPONSE /rest/items/bedroom_lamp1  200 handled=true
23:42:03.631 [DEBUG] [clipse.jetty.server.HttpChannelState] - HttpChannelState@defe20e{s=DISPATCHED i=true a=null} unhand DISPATCHED
23:42:03.631 [DEBUG] [.eclipse.jetty.server.HttpConnection] - org.eclipse.jetty.server.HttpConnection$SendCallback@247edcdd[PROCESSING][i=ResponseInfo{HTTP/1.1 200 OK,-1,false},cb=org.eclipse.jetty.server.HttpChannel$CommitCallback@3ce34110] generate: NEED_HEADER (null,[p=0,l=0,c=0,r=0],true)@START
23:42:03.631 [DEBUG] [.eclipse.jetty.server.HttpConnection] - org.eclipse.jetty.server.HttpConnection$SendCallback@247edcdd[PROCESSING][i=ResponseInfo{HTTP/1.1 200 OK,-1,false},cb=org.eclipse.jetty.server.HttpChannel$CommitCallback@3ce34110] generate: FLUSH ([p=0,l=134,c=8192,r=134],[p=0,l=0,c=0,r=0],true)@COMPLETING
23:42:03.632 [DEBUG] [org.eclipse.jetty.io.ChannelEndPoint] - flushed 134 SelectChannelEndPoint@1e67c3fd{/192.168.1.89:52022<->8080,Open,in,out,-,W,22/30000,HttpConnection}{io=0,kio=0,kro=1}
23:42:03.632 [DEBUG] [.eclipse.jetty.server.HttpConnection] - org.eclipse.jetty.server.HttpConnection$SendCallback@247edcdd[PROCESSING][i=ResponseInfo{HTTP/1.1 200 OK,-1,false},cb=org.eclipse.jetty.server.HttpChannel$CommitCallback@3ce34110] generate: DONE ([p=134,l=134,c=8192,r=0],[p=0,l=0,c=0,r=0],true)@END
23:42:03.632 [DEBUG] [org.eclipse.jetty.http.HttpParser   ] - reset HttpParser{s=END,1 of 1}
23:42:03.632 [DEBUG] [org.eclipse.jetty.http.HttpParser   ] - END --> START
23:42:03.632 [DEBUG] [org.eclipse.jetty.server.HttpChannel] - HttpChannelOverHttp@19d7cec9{r=1,c=false,a=IDLE,uri=-} handle exit, result COMPLETE
23:42:03.633 [DEBUG] [org.eclipse.jetty.io.ChannelEndPoint] - filled 0 SelectChannelEndPoint@1e67c3fd{/192.168.1.89:52022<->8080,Open,in,out,-,-,0/30000,HttpConnection}{io=0,kio=0,kro=1}
23:42:03.633 [DEBUG] [org.eclipse.jetty.io.ChannelEndPoint] - filled 0 SelectChannelEndPoint@1e67c3fd{/192.168.1.89:52022<->8080,Open,in,out,-,-,1/30000,HttpConnection}{io=0,kio=0,kro=1}
23:42:03.633 [DEBUG] [org.eclipse.jetty.http.HttpParser   ] - parseNext s=START HeapByteBuffer@34835c52[p=0,l=0,c=8192,r=0]={<<<>>>HTTP/1.1 200 OK\r\n...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
23:42:03.633 [DEBUG] [.eclipse.jetty.io.AbstractConnection] - fillInterested HttpConnection@490469fe{FILLING}
23:42:03.633 [DEBUG] [.eclipse.jetty.io.AbstractConnection] - FILLING-->FILLING_FILL_INTERESTED HttpConnection@490469fe{FILLING_FILL_INTERESTED}
23:42:03.633 [DEBUG] [.eclipse.jetty.io.AbstractConnection] - FILLING_FILL_INTERESTED-->FILL_INTERESTED HttpConnection@490469fe{FILL_INTERESTED}
23:42:03.633 [DEBUG] [lipse.jetty.io.SelectChannelEndPoint] - Local interests updating 0 -> 1 for SelectChannelEndPoint@1e67c3fd{/192.168.1.89:52022<->8080,Open,in,out,R,-,0/30000,HttpConnection}{io=1,kio=0,kro=1}
23:42:03.633 [DEBUG] [org.eclipse.jetty.io.SelectorManager] - Running change org.eclipse.jetty.io.SelectChannelEndPoint$1@69dc2308
23:42:03.634 [DEBUG] [lipse.jetty.io.SelectChannelEndPoint] - Key interests updated 0 -> 1 on SelectChannelEndPoint@1e67c3fd{/192.168.1.89:52022<->8080,Open,in,out,R,-,1/30000,HttpConnection}{io=1,kio=1,kro=1}
23:42:03.634 [DEBUG] [org.eclipse.jetty.io.SelectorManager] - Selector loop woken up from select, 0/2 selected
23:42:03.639 [DEBUG] [org.eclipse.jetty.io.SelectorManager] - Selector loop waiting on select
23:42:03.648 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'bedroom_lamp1' received command 0
23:42:03.652 [INFO ] [marthome.event.ItemStateChangedEvent] - bedroom_lamp1 changed from 22 to 0
23:42:03.654 [DEBUG] [io.socket.client.Manager            ] - writing packet io.socket.parser.Packet@33f19f6b
23:42:03.654 [DEBUG] [io.socket.parser.Parser             ] - encoding packet io.socket.parser.Packet@33f19f6b
23:42:03.654 [DEBUG] [io.socket.parser.Parser             ] - encoded io.socket.parser.Packet@33f19f6b as 2["itemupdate",{"itemName":"bedroom_lamp1","itemStatus":"0"}]
23:42:03.655 [DEBUG] [io.socket.engineio.client.Socket    ] - flushing 1 packets in socket
23:42:03.693 [INFO ] [marthome.event.ItemStateChangedEvent] - bedroom_lamp1 changed from 0 to 22
23:42:03.694 [DEBUG] [io.socket.client.Manager            ] - writing packet io.socket.parser.Packet@53ada98
23:42:03.694 [DEBUG] [io.socket.parser.Parser             ] - encoding packet io.socket.parser.Packet@53ada98
23:42:03.695 [DEBUG] [io.socket.parser.Parser             ] - encoded io.socket.parser.Packet@53ada98 as 2["itemupdate",{"itemName":"bedroom_lamp1","itemStatus":"22"}]
23:42:03.695 [DEBUG] [io.socket.engineio.client.Socket    ] - flushing 1 packets in socket
23:42:03.756 [DEBUG] [e.internal.WriterInterceptorExecutor] - Message body writer (class com.eclipsesource.jaxrs.provider.gson.GsonProvider) is trying to close the entity output stream. Not closing.
23:42:03.757 [DEBUG] [.eclipse.jetty.server.HttpConnection] - org.eclipse.jetty.server.HttpConnection$SendCallback@62696535[PROCESSING][i=ResponseInfo{HTTP/1.1 200 OK,2053,false},cb=org.eclipse.jetty.server.HttpChannel$CommitCallback@1bd23ed7] generate: NEED_HEADER (null,[p=0,l=2053,c=8192,r=2053],true)@START
23:42:03.758 [DEBUG] [.eclipse.jetty.server.HttpConnection] - org.eclipse.jetty.server.HttpConnection$SendCallback@62696535[PROCESSING][i=ResponseInfo{HTTP/1.1 200 OK,2053,false},cb=org.eclipse.jetty.server.HttpChannel$CommitCallback@1bd23ed7] generate: FLUSH ([p=0,l=143,c=8192,r=143],[p=0,l=2053,c=8192,r=2053],true)@COMPLETING
23:42:03.758 [DEBUG] [org.eclipse.jetty.io.ChannelEndPoint] - flushed 2196 SelectChannelEndPoint@7af32fc1{/192.168.1.89:52018<->8080,Open,in,out,-,W,6616/30000,HttpConnection}{io=0,kio=0,kro=1}
23:42:03.759 [DEBUG] [.eclipse.jetty.server.HttpConnection] - org.eclipse.jetty.server.HttpConnection$SendCallback@62696535[PROCESSING][i=ResponseInfo{HTTP/1.1 200 OK,2053,false},cb=org.eclipse.jetty.server.HttpChannel$CommitCallback@1bd23ed7] generate: DONE ([p=143,l=143,c=8192,r=0],[p=2053,l=2053,c=8192,r=0],true)@END
23:42:03.759 [DEBUG] [.jetty.server.handler.ContextHandler] - scope null||/rest/sitemaps/main/main @ o.e.j.s.h.ContextHandler@65fdbd02{/static,null,AVAILABLE}
```

**Comment by cdjackson** [comment]
You say you think this is a bug, but where do you think the problem is? I assumed you thought it was a problem with ZWave, but I guess not as you're not providing any logging so do you think this is an issue in the core? Sorry - it's a bit confusing where you want me to look :(

**Comment by christianwaite** [comment]
That is just my incompetence I'm afraid.
I set the log level to debug. Is that not what you need?
I have no idea where or why it's happening, just that it is and it only happens on these zwave nodes.

Here is the bit that I move the slider to zero, then it springs back to 23:
```
23:42:03.652 [INFO ] [marthome.event.ItemStateChangedEvent] - bedroom_lamp1 changed from 22 to 0
23:42:03.654 [DEBUG] [io.socket.client.Manager ] - writing packet io.socket.parser.Packet@33f19f6
23:42:03.654 [DEBUG] [io.socket.parser.Parser ] - encoding packet io.socket.parser.Packet@33f19f6
23:42:03.654 [DEBUG] [io.socket.parser.Parser ] - encoded io.socket.parser.Packet@33f19f6 as 2["itemupdate",{"itemName":"bedroom_lamp1","itemStatus":"0"}]
23:42:03.655 [DEBUG] [io.socket.engineio.client.Socket ] - flushing 1 packets in socket
23:42:03.693 [INFO ] [marthome.event.ItemStateChangedEvent] - bedroom_lamp1 changed from 0 to 22
```

If I need to provide a different type of log, could you inform me of where to look for this?
Thanks for your time and patience.
Christian

**Comment by cdjackson** [comment]
If we think this potential bug is related to Zwave then I need some Zwave logging. Normally enabling debug should enable all bindings I think, but otherwise you can type log:set debug org.openhab.binding.zwave command to enable it.

**Comment by christianwaite** [comment]
Ok sorry I found the log:list which makes everything a lot more clear as to what was going on with everything. Thanks for that! SO I hope this is more in line with what you need.

```
20:13:22.182 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 9: Command received zwave:device:15406e20b1c:node9:switch_dimmer --> 0
20:13:22.182 [DEBUG] [ss.ZWaveMultiLevelSwitchCommandClass] - NODE 9: Creating new message for command SWITCH_MULTILEVEL_SET
20:13:22.183 [DEBUG] [ss.ZWaveMultiLevelSwitchCommandClass] - NODE 9: Creating new message for command SWITCH_MULTILEVEL_GET
20:13:22.185 [DEBUG] [ve.internal.protocol.ZWaveController] - Message queued. Queue length = 1. Queue={}
20:13:22.185 [DEBUG] [ve.internal.protocol.ZWaveController] - Message queued. Queue length = 1. Queue={}
20:13:22.185 [DEBUG] [ocol.ZWaveController$ZWaveSendThread] - Took message from queue for sending. Queue length = 0
20:13:22.188 [DEBUG] [wave.internal.protocol.SerialMessage] - Assembled message buffer = 01 0A 00 13 09 03 26 01 00 25 15 FB 
20:13:22.188 [DEBUG] [ing.zwave.handler.ZWaveSerialHandler] - NODE 9: Sending REQUEST Message = 01 0A 00 13 09 03 26 01 00 25 15 FB 
20:13:22.189 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'bedroom_lamp1' received command 0
20:13:22.194 [DEBUG] [WaveSerialHandler$ZWaveReceiveThread] - Receive Message = 01 04 01 13 01 E8 
20:13:22.195 [DEBUG] [ve.internal.protocol.ZWaveController] - Receive queue TAKE: Length=0
20:13:22.195 [DEBUG] [wave.internal.protocol.SerialMessage] - Assembled message buffer = 01 04 01 13 01 E8 
20:13:22.195 [INFO ] [marthome.event.ItemStateChangedEvent] - bedroom_lamp1 changed from 34 to 0
20:13:22.198 [DEBUG] [ve.internal.protocol.ZWaveController] - Process Message = 01 04 01 13 01 E8 
20:13:22.199 [DEBUG] [ve.internal.protocol.ZWaveController] - Message: class=SendData[0x13], type=Response[0x01], priority=High, dest=255, callback=0, payload=01 
20:13:22.200 [DEBUG] [l.serialmessage.SendDataMessageClass] - NODE 9: Sent Data successfully placed on stack.
20:13:22.206 [DEBUG] [WaveSerialHandler$ZWaveReceiveThread] - Receive Message = 01 05 00 13 15 00 FC 
20:13:22.207 [DEBUG] [ve.internal.protocol.ZWaveController] - Receive queue TAKE: Length=0
20:13:22.207 [DEBUG] [wave.internal.protocol.SerialMessage] - Assembled message buffer = 01 07 00 13 15 00 00 00 FE 
20:13:22.207 [DEBUG] [ve.internal.protocol.ZWaveController] - Process Message = 01 07 00 13 15 00 00 00 FE 
20:13:22.208 [DEBUG] [ve.internal.protocol.ZWaveController] - Message: class=SendData[0x13], type=Request[0x00], priority=High, dest=255, callback=0, payload=15 00 
20:13:22.208 [DEBUG] [l.serialmessage.SendDataMessageClass] - NODE 9: SendData Request. CallBack ID = 21, Status = Transmission complete and ACK received(0)
20:13:22.209 [DEBUG] [.serialmessage.ZWaveCommandProcessor] - Checking transaction complete: Sent Message: class=SendData[0x13], type=Request[0x00], priority=Set, dest=9, callback=21, payload=09 03 26 01 00 
20:13:22.209 [DEBUG] [.serialmessage.ZWaveCommandProcessor] - Checking transaction complete: Recv Message: class=SendData[0x13], type=Request[0x00], priority=High, dest=255, callback=0, payload=15 00 
20:13:22.209 [DEBUG] [.serialmessage.ZWaveCommandProcessor] - Checking transaction complete: class=SendData, callback id=21, expected=SendData, cancelled=false        transaction complete!
20:13:22.210 [DEBUG] [ve.internal.protocol.ZWaveController] - Notifying event listeners: ZWaveTransactionCompletedEvent
20:13:22.210 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 9: Got an event from Z-Wave network: ZWaveTransactionCompletedEvent
20:13:22.210 [DEBUG] [ocol.ZWaveController$ZWaveSendThread] - NODE 9: Response processed after 22ms/147ms.
20:13:22.210 [DEBUG] [ocol.ZWaveController$ZWaveSendThread] - Took message from queue for sending. Queue length = 0
20:13:22.211 [DEBUG] [wave.internal.protocol.SerialMessage] - Assembled message buffer = 01 09 00 13 09 02 26 02 25 16 F9 
20:13:22.211 [DEBUG] [ing.zwave.handler.ZWaveSerialHandler] - NODE 9: Sending REQUEST Message = 01 09 00 13 09 02 26 02 25 16 F9 
20:13:22.216 [DEBUG] [WaveSerialHandler$ZWaveReceiveThread] - Receive Message = 01 04 01 13 01 E8 
20:13:22.217 [DEBUG] [ve.internal.protocol.ZWaveController] - Receive queue TAKE: Length=0
20:13:22.217 [DEBUG] [wave.internal.protocol.SerialMessage] - Assembled message buffer = 01 04 01 13 01 E8 
20:13:22.217 [DEBUG] [ve.internal.protocol.ZWaveController] - Process Message = 01 04 01 13 01 E8 
20:13:22.218 [DEBUG] [ve.internal.protocol.ZWaveController] - Message: class=SendData[0x13], type=Response[0x01], priority=High, dest=255, callback=0, payload=01 
20:13:22.218 [DEBUG] [l.serialmessage.SendDataMessageClass] - NODE 9: Sent Data successfully placed on stack.
20:13:22.228 [DEBUG] [WaveSerialHandler$ZWaveReceiveThread] - Receive Message = 01 05 00 13 16 00 FF 
20:13:22.229 [DEBUG] [ve.internal.protocol.ZWaveController] - Receive queue TAKE: Length=0
20:13:22.229 [DEBUG] [wave.internal.protocol.SerialMessage] - Assembled message buffer = 01 07 00 13 16 00 00 00 FD 
20:13:22.229 [DEBUG] [ve.internal.protocol.ZWaveController] - Process Message = 01 07 00 13 16 00 00 00 FD 
20:13:22.230 [DEBUG] [ve.internal.protocol.ZWaveController] - Message: class=SendData[0x13], type=Request[0x00], priority=High, dest=255, callback=0, payload=16 00 
20:13:22.230 [DEBUG] [l.serialmessage.SendDataMessageClass] - NODE 9: SendData Request. CallBack ID = 22, Status = Transmission complete and ACK received(0)
20:13:22.231 [DEBUG] [.serialmessage.ZWaveCommandProcessor] - Checking transaction complete: Sent Message: class=SendData[0x13], type=Request[0x00], priority=Get, dest=9, callback=22, payload=09 02 26 02 
20:13:22.231 [DEBUG] [.serialmessage.ZWaveCommandProcessor] - Checking transaction complete: Recv Message: class=SendData[0x13], type=Request[0x00], priority=High, dest=255, callback=0, payload=16 00 
20:13:22.231 [DEBUG] [.serialmessage.ZWaveCommandProcessor] - Checking transaction complete: class=SendData, callback id=22, expected=ApplicationCommandHandler, cancelled=false      MISMATCH
20:13:22.235 [DEBUG] [WaveSerialHandler$ZWaveReceiveThread] - Receive Message = 01 09 00 04 00 09 03 26 03 21 FC 
20:13:22.236 [DEBUG] [ve.internal.protocol.ZWaveController] - Receive queue TAKE: Length=0
20:13:22.236 [DEBUG] [wave.internal.protocol.SerialMessage] - Assembled message buffer = 01 09 00 04 00 09 03 26 03 21 FC 
20:13:22.236 [DEBUG] [ve.internal.protocol.ZWaveController] - Process Message = 01 09 00 04 00 09 03 26 03 21 FC 
20:13:22.237 [DEBUG] [ve.internal.protocol.ZWaveController] - Message: class=ApplicationCommandHandler[0x04], type=Request[0x00], priority=High, dest=255, callback=0, payload=00 09 03 26 03 21 
20:13:22.237 [DEBUG] [ssage.ApplicationCommandMessageClass] - NODE 9: Application Command Request (ALIVE:DONE)
20:13:22.238 [DEBUG] [ssage.ApplicationCommandMessageClass] - NODE 9: Incoming command class SWITCH_MULTILEVEL
20:13:22.238 [DEBUG] [ss.ZWaveMultiLevelSwitchCommandClass] - NODE 9: Received Switch Multi Level Request
20:13:22.238 [DEBUG] [ss.ZWaveMultiLevelSwitchCommandClass] - NODE 9: Switch Multi Level report, value = 33
20:13:22.239 [DEBUG] [ve.internal.protocol.ZWaveController] - Notifying event listeners: ZWaveCommandClassValueEvent
20:13:22.239 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 9: Got an event from Z-Wave network: ZWaveCommandClassValueEvent
20:13:22.239 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 9: Got a value event from Z-Wave network, endpoint = 0, command class = SWITCH_MULTILEVEL, value = 33
20:13:22.240 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - Updating zwave:device:15406e20b1c:node9:switch_dimmer to 33
20:13:22.240 [DEBUG] [.serialmessage.ZWaveCommandProcessor] - Checking transaction complete: Sent Message: class=SendData[0x13], type=Request[0x00], priority=Get, dest=9, callback=22, payload=09 02 26 02 
20:13:22.241 [DEBUG] [.serialmessage.ZWaveCommandProcessor] - Checking transaction complete: Recv Message: class=ApplicationCommandHandler[0x04], type=Request[0x00], priority=High, dest=255, callback=0, payload=00 09 03 26 03 21 
20:13:22.241 [DEBUG] [.serialmessage.ZWaveCommandProcessor] - Checking transaction complete: class=ApplicationCommandHandler, callback id=22, expected=ApplicationCommandHandler, cancelled=false        transaction complete!
20:13:22.241 [INFO ] [marthome.event.ItemStateChangedEvent] - bedroom_lamp1 changed from 0 to 33
20:13:22.242 [DEBUG] [ve.internal.protocol.ZWaveController] - Notifying event listeners: ZWaveTransactionCompletedEvent
20:13:22.242 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 9: Got an event from Z-Wave network: ZWaveTransactionCompletedEvent
20:13:22.242 [DEBUG] [ocol.ZWaveController$ZWaveSendThread] - NODE 9: Response processed after 31ms/147ms.
```

**Comment by cdjackson** [comment]
Thanks :)

So, what this log shows is the device reported that it was at 33% when it was read back after the update. What I suspect is happening is that the command to set the device is sent, and the read back is updated before the device has actually changed (or at least before it has fully changed). So, you are seeing the data before the update is complete…

I’ll need to have a think about how to handle this...

**Comment by christianwaite** [comment]
Cool well I'm glad it's not just me.
Of note, the devices that this is happening with don't have association group back to the controller so have to be polled to update their state.

**Comment by cdjackson** [comment]
This should now be solved.

**Comment by christianwaite** [comment]
Awesome! I'll test it out. Thanks.

**Comment by christianwaite** [comment]
I can confirm this is now fixed.
Thanks for the effort!
