### ISSUE TITLE
Netatmo | Bindind won't work with thermostat

### ISSUE THREAD

**Issue by jsiobj** [openhab/openhab2-addons#805]
Hello,

I just tried the newly merged netatmo binding and I can't get it to work.
I jave just a thermostat, no weather station.

When adding Netatmo API thing, I keyed in required parameters and only select Thermostat. API thing is added and claim to be "online". 

Logs are showing the following : 

```
17:21:34.832 [INFO ] [smarthome.event.ItemAddedEvent      ] - Item 'netatmo_netatmoapi_63c511be' has been added.
17:21:34.880 [INFO ] [rthome.event.ItemThingLinkAddedEvent] - Link 'netatmo_netatmoapi_63c511be-netatmo:netatmoapi:63c511be' has been added.
17:21:35.402 [WARN ] [covery.NetatmoModuleDiscoveryService] - 404 Not Found
17:21:35.601 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'netatmo:netatmoapi:63c511be' changed from INITIALIZING to ONLINE
```

But if I am going back to API thing config, both Weather station and Thermostat are selected.

I am not sure at this point if thermostat should be discovered 

I tried anyway to add it as a new thing and add a new "Thermostat module" using the following params :

```
{
  "body": {
    "modules": [
      {
        "_id": "xx:xx:xx:xx:xx:xx", <= used for Module ID
        ...
        "main_device": "yy:yy:yy:yy:yy:yy", <= used as device ID
        "module_name": "Thermostat",
        "type": "NATherm1",
       ...
```

It then also show up "online"

I then added Thermostat relay using the following params :

```
"devices": [
      {
        "_id": "zz:zz:zz:zz:zz:zz", <= used as equipement ID
        "cipher_id": "aaaaaaaaaaa...
```

This time it won't go online and I get the following error :

```
17:34:20.527 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'netatmo:NAPlug:2a0453b1' changed from ONLINE to OFFLINE: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 1880 path $.body.devices[0].therm_program..program_id
```

As I understand it, a third party lib based on swagger.io and @cbornet Netatmo swagger declaration is used.

In startScan call, [here](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/discovery/NetatmoModuleDiscoveryService.java#L68-L72), devicelist is used. But as it is deprecated, I wanted to try the new getthermostatdata with the new json file @clinique proposed [here](https://github.com/cbornet/netatmo-swagger-decl/issues/2).  But I could not find a way to build the lib. How do you build netatmo-java-retrofit-1.0.0.jar ? Directly using swagger-code-gen ?

Also, it runs (or at list tries) devicelist for both weather station and thermostat, which, I guess should not be the case if one of them is not selected. In my case, It seems the second call to devicelist is never reached because the first fails with 404 error.

I am not really a java developper... and OpenHAB is a quite complex software... so if anyone could give me some directions, that would be great.

Thanks !
JS
##

**Comment by kaikreuzer** [comment]
@clinique can you help?

**Comment by clinique** [comment]
@kaikreuzer  : sure, taking a look asap. @jsiobj : thanks for your detailed bug report.

**Comment by jsiobj** [comment]
Hello again,

I tried to have a deeper look but it always comes down to Swagger lib not being up to date (using obsolete calls which seems not to work for thermostat). I tried to rebuild the lib but I have no clue how to generate the JAR file which would be replacing netatmo-java-retrofit-1.0.3.jar. I managed to build the java files... not not the final jar. Once I have that, I could try to update the code with new getthermostatsdata call.

So any direction on how to build the netatmo-java-retrofit jar file is welcome.

Thanks.
JS

**Comment by clinique** [comment]
Get it. IIRW I had a discussion with cbornet, the author of the swagger lib for Netatmo regarding the fact that Netatmo-swagger-api was not generating each and every client libraries (https://github.com/cbornet/netatmo-swagger-api/pull/1). 
=> You need to set swagger version to 2.1.5 in download_swagger-codegen-cli.sh 
and then launch
=> ./all-netatmo.sh

**Comment by jsiobj** [comment]
Hello @clinique, I actually managed to run the script. It create the java code but it does not create the jar file packing everything together. How is this jar file getting generated from raw code files so I can drop it into the binding sources and replace the old one ?

**Comment by clinique** [comment]
Hi @jsiobj , I managed to create the jar by myself. Will take a look and manage to provide it.

**Comment by LukaNoah** [comment]
Hi,

I've tested the 2.0 snapshot. I could'nt receive values. I miss the input for the refresh-token, Where can I found it?

thx

**Comment by clinique** [comment]
You dont néed to setup thé reftesh token in v2 of the binding

**Comment by LukaNoah** [comment]
and whats about the error-mesaage? sorry I've edit my post ;)

**Comment by jsiobj** [comment]
Hello @clinique ,

So, after struggling a bit, I finally managed to build the jar file ("simply" by using `mvn clean package` in the java retrofit client) and replace it within eclipse (which was also a bit tricky as I am not familiar with this...).

I'd like to help to get this working, but I kind of realize (but I believe you already knew that...) that using new API calls is not that easy. I can try to make this work but I need some advice / directions.

Here is my understanding.

The way the API worked before was kind of more generic as it was addressing all devices the same way and all modules the same way with common API calls. Especially, a weather station device was using the very same class and thermostat device, that is `NADevice`. Discovery of devices was based on commuon API call `devicelist`. And the same applies to modules with class `NAModule`.

Now, those common API calls are deprecated (and even fails for me) and specific classes for weather station and thermostat are used, along with specific API calls : `NAPlug `and `NAThermostat `for thermostat, `NAStation` and whatever for weather station.

Thing is... there are classes called `NAPlugHandler `and `NAMainHandler `which are both a subclass of `NetatmoDeviceHandler `and use `NADevice` member. But in `NAPlugHandler`, it should be using `NAPlug `class instead if `NADevice `so `getthermostatsdata` can be used. Is making `NAPlugHandler `a subclass of `AbstractNetatmoThingHandler `and add a `NAPlug `member the way to go ?

No sure I am being quite clear here... but hopefully, you can understand what I mean.
Thanks !

JS

**Comment by jsiobj** [comment]
Hello @clinique,

I managed to make it work with the new API (by the way, Netatmo dev website has been entirely revamped...) but it required some changes. As I am new to openHAB and java development... my code still need some work... There I still a few things in openHAB and ESH I need to understand (especially on data updates).

May be you could have a look and tell me what you think. It is all here : https://github.com/jsiobj/openhab2-addons/tree/netatmo-thermostat/addons/binding/org.openhab.binding.netatmo

Any comment, suggestion, remark... is quite welcome.

Also, I think that the swagger io lib should be updated to include new weather station API so that the code is consistent for both thermostat and weather station. I'll try to have a look at it.

Thanks !
JS

**Comment by clinique** [comment]
Hello @jsiobj ,
Thanks for your update - I will not be in position to review it until this week-end, but I will.
I agree that the whole swagger lib shall be updated, but I'm currently stuck with a bug on swagger codegen that hanged my last updates - don't you face the same (problem with inheritence commented here https://github.com/openhab/openhab2-addons/issues/866#issuecomment-220419450) ?

**Comment by clinique** [comment]
@jsiobj : good news, cbornet remove the use of AllOf that was generating the issue, I'll be able to move on !

**Comment by jsiobj** [comment]
Hello @Clinique, no rush for the review... I need to do some (big) corrections anyway. 

Once I sort this out, I'll have a look at the swagger definition file. I saw #866 but it did not occured for me as I did not make any change to the swagger lib, just build from latest available one.

**Comment by Chanete** [comment]
HI, I'm also having trouble setting up the Netatmo binding with Thermostat (is the only device I own). 

First, I have to enable the weather station AND the thermostat. If I don't enable both, the binding remains Offline. 

After this, the Bridge comes Online, but it doesn't discover the Thermostat. I've added manually the Thermostat/Relay plug thing and now, I can see in the "Control" tag a nice map of my home and the signal strength. Now I've tried to add the thermostat itself,  but I don't know where to get the device ID. 

Can you please help me? 

Thx in advance
Chano

**Comment by jsiobj** [comment]
Hello @Chanete,

To get IDs, go to https://dev.netatmo.com/, login with your Netatmo user, go to "Our resources" => "Thermostat" => "Getthermostatsdata" and clic on "Try this method by yourself with our try it module" => "Try it". It should spit out all thermostat data. Especially, _Id under devices is the ID of the relay and _Id under modules is the ID of the thermostat.

Unfortunalely, I think it won't work... as there is an issue with current version of the API... But it will hopefully get fixed !

JS

**Comment by Chanete** [comment]
Thx @jsiobj, I've finally found the id following your instructions but, as you said, it doesnt work :( 

We will have to wait till @Clinique can fixit... 

Thank you very much for your help!!

**Comment by jsiobj** [comment]
Hello @clinique,

Did you have a chance to look at my code ? Do you think it is the way to go ?
I tried to see if I could update swagger description file... but I am not sure where to start.

Thanks.
JS

**Comment by clinique** [comment]
Done here https://github.com/jsiobj/openhab2-addons/commit/eeb722f5ff860d143b038785db2e33d1c9f98abf

**Comment by clinique** [comment]
I've just pushed an update of swagger declaration file. Once merged, I'll remove all obsolete function calls from the binding.

**Comment by jsiobj** [comment]
I have also done some test and have good news :-)

Changing program_id definition in swagger file from
```
                 "program_id": {
                    "type": "string"
                 }, 
```
to
```
                 "program_id": {
                    "type": "string"
                    "type": "object",
                    "additionalProperties": {
                        "$id": {
                            "type": "string"
                        }
                    }
                 }, 
```
seems to solve my problem !
I'll see if I can also push my update to cbornet.

**Comment by mccaffm** [comment]
is there an problem with getting these merged, hoping it will fix my relay issues to

**Comment by clinique** [comment]
Yes, hopefully. The swagger definition file is updated and I'm currently reviewing all the binding to remove obsolete API calls. Sorry, takes a bit of time.

**Comment by mccaffm** [comment]
Thanks, understand the time it takes, I just couldn’t see the relevant merge in the swagger-api.. must have missed it

**Comment by clinique** [comment]
Well,
I've pushed a major review of the binding in order to remove all calls to deprecated API, and also lower the number of requests made to Netatmo servers. This also reintroduces usage of GetMeasure, that shall ease migration from currently v1.8.x only features of the binding into the 2.0 branch.

On my side everything seems to work fine. Hope it'll be the same for you.

**Comment by jsiobj** [comment]
Great ! I'll test that and keep you posted
Thanks.

**Comment by mccaffm** [comment]
ive also tested 805 branch and all is looking good, all my modules internal, external, wind and rain work as before, but more importantly for me thermostat and its relay are now online and reporting data.

**Comment by lolodomo** [comment]
Issue to close
