### ISSUE TITLE
ZWave: controller configuration miss default values

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab2-addons#809]
I got warning after adding a USB serial controller.
I assume there are some defaults missing.

See: https://github.com/eclipse/smarthome/issues/1400#issue-149244219

**Comment by cdjackson** [comment]
Defaults are provided for all statically defined parameters in the controller. I suspect defaults may not be applied for dynamically defined parameters though.

**Comment by cdjackson** [comment]
Hmmm - some defaults are empty though… Maybe this is the issue….

**Comment by kaikreuzer** [comment]
If they are then interpreted as an empty string, yes, that might be the cause (see https://github.com/eclipse/smarthome/issues/1400#issuecomment-211567851)

**Comment by maggu2810** [comment]
@cdjackson Does your PR openhab2-addons/pull/810 that also contains changes of _controller_serial.xml address this issue? Should I retest?

**Comment by cdjackson** [comment]
Hi Markus,
Yes - it was updated… If you can retest it would be great.

Chris

**Comment by maggu2810** [comment]
Seems to be solved. Thanks @cdjackson
