### ISSUE TITLE
Build failure: ConfigStatusThingHandler

### ISSUE THREAD

**Issue by cdjackson** [openhab/openhab2-addons#821]
@kaikreuzer the current build failure in Z-Wave is showing the following error on CI -:

```
The import org.eclipse.smarthome.core.thing.binding.ConfigStatusThingHandler cannot be resolved
```

Any idea why this now starts? (I guess you didn't remove this class).

**Comment by kaikreuzer** [comment]
I have no clue, I am also just looking at the build (also triggered by https://github.com/openhab/openhab-distro/commit/623134ee9ecdf75033f4f0d4adf5a87fbbf59070#commitcomment-17215819).

Just running a new ESH stable build (https://hudson.eclipse.org/smarthome/job/SmartHomeDistribution-Stable/53/), maybe the last one was corrupted in some way...?

**Comment by kaikreuzer** [comment]
Fixed: https://openhab.ci.cloudbees.com/job/openHAB2-Addons/576/
