### ISSUE TITLE
Add Homeduino Binding

### ISSUE THREAD

**Issue by martinvw** [openhab/openhab2-addons#849]
Hello,

As discussed on the forum I'm working on a binding for homeduino. Currently I'm extending the existing RFXCom binding to support this.

See: https://community.openhab.org/t/interest-in-a-homeduino-binding/8017/11

_The https://github.com/openhab/openhab-distro/blob/master/CONTRIBUTING.md states that issues should be created, so here it is._

Regards,

Martin
##

**Comment by kaikreuzer** [comment]
Thanks for the info, Martin, and good luck :-)

**Comment by martinvw** [comment]
A very early test version with (limited) support for pir1, switch1, switch2, switch4 and shutter3

[org.openhab.binding.homeduino-2.1.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab2-addons/files/761897/org.openhab.binding.homeduino-2.1.0-SNAPSHOT.jar.zip)

Comments place them here or in the forum thread:

https://community.openhab.org/t/interest-in-a-homeduino-binding/8017/34

**Comment by davidgraeff** [comment]
Martin please reopen when you are still using that hardware and you are still interested :)
