### ISSUE TITLE
Add TinkerForge Binding

### ISSUE THREAD

**Issue by theoweiss** [openhab/openhab2-addons#85]
I will start working on this in the first quarter of 2015.
##

**Comment by andiikaa** [comment]
Hi,
are you still working on that binding? I'm asking cause i need it for some work in the university. If you don't have the time, i will try it on my own. 
Unfortunately i'm completely new in openhab(2), so it may take some time.

Regards,
André

**Comment by teichsta** [comment]
> I'm asking cause i need it for some work in the university

at which university are you studying at?

**Comment by andiikaa** [comment]
> at which university are you studying at?
I'm studying at the TU Dresden

**Comment by kaikreuzer** [comment]
Hi @andiikaa, thanks for your offer!
@theoweiss, I think the question is for you to answer :-)

**Comment by theoweiss** [comment]
Hi @andiikaa,

it's great to hear that TU Dresden wants to work with openHAB and the TinkerForge binding! 
Yes, it's alive and I'm constantly working on it. Unfortunately until now the binding is only available for openhab1. I've planned to work on the openhab2 port after openHAB 1.7.0 is released.  May be this would be a major effort and therefore need some month to be implemented, because the binding uses an EMF model as a facade around the Tinkerforge API and may be this should be replaced with a new API wrapper.
What are your demands on the binding and what's missing?
If possible, for now use openhab 1 and let me know which functionality you are missing.

Regards,
Theo

**Comment by kaikreuzer** [comment]
It would be great if any of you could at least test the compatibility of the 1.x binding with openHAB 2 - this entry is still missing on the compat matrix https://github.com/openhab/openhab2/blob/master/docs/sources/installation/compatibility.md.

**Comment by andiikaa** [comment]
Thanks for the answers. I'll try to use the binding from openHAB 1.x and let you know if that works. 

I want to use openHAB as a 'middleware' and access all our devices via the rest api. I have also to build some new bindings for specific devices. 
In openHAB 2, the configuration procedure seems a lot easier, cause it can completely done over the webinterface (i mean, adding new items/things).

For the tinkerforge binding, we want to get the temperature, the luminosity and the humidity from the bricklet and access the values over the rest api from openHAB.

**Comment by davidgraeff** [comment]
@wborn I think it makes sense to close all "new binding" issues as soon as the PR has been created. In this case the issue is from 2014 (4 years) and we can assume that nothing will happen and if, by another author who should not be confused by such an issue.

**Comment by kaikreuzer** [comment]
I think @theoweiss IS actually indeed still working on it - but not having had any update here for 3.5 years indeed qualifies the issue to be closed.
@theoweiss, if you still proceed this, the next logical step would be a PR (can also be a WIP PR, if you don't consider it final yet).

**Comment by theoweiss** [comment]
Yes  indeed I'm still working on it. You can have look at the dev here: https://github.com/theoweiss/openhab2-addons/tree/tinkerforge3 and there are still a bunch people using and testing the new binding as you can see here: https://www.tinkerunity.org/forum/index.php/topic,1769.435.html (the thread has over 96000 reads since 2013). As @kaikreuzer suggested I will open a WIP PR during the next month to get this work integrated. 
Thanks for your patience.

**Comment by MHerbst** [comment]
There is a beta version of the Tinkerforge Binding for OH 2.5.0 available at https://www.tinkerunity.org/forum/index.php/topic,5090.0.html
