### ISSUE TITLE
ZWave: Unknown thingType: 0108:0004:000A::1.8

### ISSUE THREAD

**Issue by thopiekar** [openhab/openhab2-addons#854]
After adding a "mydlink Z-Wave Siren" (http://products.z-wavealliance.org/products/1262) there are no channels to bind and I just found this message in the log:

```
19:59:25.612 [WARN ] [wave.discovery.ZWaveDiscoveryService] - NODE 5: Device could not be resolved to a thingType! 0108:0004:000A::1.8
```

Looks like a siren is not defined to far.

Additionally:
```
19:59:31.170 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'zwave:device:5ec07f15:node5' changed from OFFLINE to ONLINE
19:59:36.172 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Timeout while sending message. Requeueing - 2 attempts left!
19:59:36.172 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 5: Got an error while sending data. Resending message.
19:59:41.174 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Timeout while sending message. Requeueing - 1 attempts left!
19:59:41.174 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 5: Got an error while sending data. Resending message.
19:59:46.177 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Timeout while sending message. Requeueing - 0 attempts left!
19:59:46.177 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 5: Got an error while sending data. Resending message.
19:59:51.179 [WARN ] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Too many retries. Discarding message: Message: class=SendData[0x13], type=Request[0x00], priority=Get, dest=5, callback=22, payload=05 02 25 02 
19:59:56.181 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Timeout while sending message. Requeueing - 2 attempts left!
19:59:56.181 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 5: Got an error while sending data. Resending message.
20:00:01.183 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Timeout while sending message. Requeueing - 1 attempts left!
20:00:01.183 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 5: Got an error while sending data. Resending message.
20:00:06.184 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Timeout while sending message. Requeueing - 0 attempts left!
20:00:06.185 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 5: Got an error while sending data. Resending message.
20:00:11.186 [WARN ] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Too many retries. Discarding message: Message: class=SendData[0x13], type=Request[0x00], priority=Get, dest=5, callback=26, payload=05 02 25 02 
20:00:16.188 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Timeout while sending message. Requeueing - 2 attempts left!
20:00:16.188 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 5: Got an error while sending data. Resending message.
20:00:21.189 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Timeout while sending message. Requeueing - 1 attempts left!
20:00:21.190 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 5: Got an error while sending data. Resending message.
20:00:26.191 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Timeout while sending message. Requeueing - 0 attempts left!
20:00:26.191 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 5: Got an error while sending data. Resending message.
20:00:31.193 [WARN ] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Too many retries. Discarding message: Message: class=SendData[0x13], type=Request[0x00], priority=Get, dest=5, callback=30, payload=05 02 25 02 
20:00:36.196 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Timeout while sending message. Requeueing - 2 attempts left!
20:00:36.197 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 5: Got an error while sending data. Resending message.
20:00:41.199 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Timeout while sending message. Requeueing - 1 attempts left!
20:00:41.199 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 5: Got an error while sending data. Resending message.
20:00:46.200 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Timeout while sending message. Requeueing - 0 attempts left!
20:00:46.204 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 5: Got an error while sending data. Resending message.
20:00:51.205 [WARN ] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Too many retries. Discarding message: Message: class=SendData[0x13], type=Request[0x00], priority=Get, dest=5, callback=33, payload=05 02 25 02 
20:00:56.206 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Timeout while sending message. Requeueing - 2 attempts left!
20:00:56.207 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 5: Got an error while sending data. Resending message.
20:01:01.208 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Timeout while sending message. Requeueing - 1 attempts left!
20:01:01.210 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 5: Got an error while sending data. Resending message.
20:01:06.212 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Timeout while sending message. Requeueing - 0 attempts left!
20:01:06.212 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 5: Got an error while sending data. Resending message.
20:01:11.215 [WARN ] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Too many retries. Discarding message: Message: class=SendData[0x13], type=Request[0x00], priority=Get, dest=5, callback=37, payload=05 02 25 02
```

**Comment by cdjackson** [comment]
> Looks like a siren is not defined to far.

Please feel free to add it to the database.

http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/330

> Additionally:

I would prefer no 'additionally' items :) Really, if there are two problems, then please raise two issues otherwise it's hard to track them.

In this case, retries normally indicate bad communication - either because the device is too far from the controller, or there's an issue with the configuation. In order to tell this, we need the debug log. If this is the problem, please raise a separate issue.

**Comment by thopiekar** [comment]
@cdjackson Ok, will do this until adding that thing is done.

There are a lot of details (at least for me) which I have to provide in your database. If there is something missing can you give me some hints?

Thanks!

**Comment by cdjackson** [comment]
If you can just load the xml file for this node that openhab has hopefully generated automatically, I think that should fill in everything needed.

**Comment by thopiekar** [comment]
Adding the basic information for the device was easy, but there are a lot of fields for the commands I have to fill out.
Is there a resource explaining which info is relevant? Or could you give me some instructions?
And where does ```  <version>4</version>``` go? Firmware Versions or Protocol Version?

_xml_
```
<node>
  <deviceClass>
    <basicDeviceClass>ROUTING_SLAVE</basicDeviceClass>
    <genericDeviceClass>BINARY_SWITCH</genericDeviceClass>
    <specificDeviceClass>SIREN_SWITCH_BINARY</specificDeviceClass>
  </deviceClass>
  <homeId>YXZ</homeId>
  <nodeId>Z</nodeId>
  <version>4</version>
  <manufacturer>0x108</manufacturer>
  <deviceId>0xa</deviceId>
  <deviceType>0x4</deviceType>
  <listening>true</listening>
  <frequentlyListening>false</frequentlyListening>
  <routing>true</routing>
  <security>false</security>
  <beaming>true</beaming>
  <maxBaudRate>40000</maxBaudRate>
  <nodeInformationFrame>
    <int>94</int>
    <int>114</int>
    <int>134</int>
    <int>89</int>
    <int>115</int>
    <int>90</int>
    <int>152</int>
    <int>122</int>
  </nodeInformationFrame>
  <supportedCommandClasses>
    <entry>
      <commandClass>MANUFACTURER_SPECIFIC</commandClass>
      <manufacturerSpecificCommandClass>
        <version>1</version>
        <instances>1</instances>
      </manufacturerSpecificCommandClass>
    </entry>
    <entry>
      <commandClass>ZWAVE_PLUS_INFO</commandClass>
      <zwavePlusCommandClass>
        <version>1</version>
        <instances>1</instances>
        <zwPlusVersion>1</zwPlusVersion>
        <zwPlusRole>5</zwPlusRole>
        <zwPlusNodeType>0</zwPlusNodeType>
        <zwPlusDeviceType>0xf00</zwPlusDeviceType>
        <zwPlusInstallerIcon>0xf00</zwPlusInstallerIcon>
        <isGetSupported>true</isGetSupported>
      </zwavePlusCommandClass>
    </entry>
    <entry>
      <commandClass>BASIC</commandClass>
      <basicCommandClass>
        <version>1</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
      </basicCommandClass>
    </entry>
    <entry>
      <commandClass>SWITCH_BINARY</commandClass>
      <binarySwitchCommandClass>
        <version>1</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
      </binarySwitchCommandClass>
    </entry>
    <entry>
      <commandClass>DEVICE_RESET_LOCALLY</commandClass>
      <deviceResetLocallyCommandClass>
        <version>1</version>
        <instances>1</instances>
      </deviceResetLocallyCommandClass>
    </entry>
    <entry>
      <commandClass>NO_OPERATION</commandClass>
      <noOperationCommandClass>
        <version>1</version>
        <instances>1</instances>
      </noOperationCommandClass>
    </entry>
    <entry>
      <commandClass>VERSION</commandClass>
      <versionCommandClass>
        <version>1</version>
        <instances>1</instances>
        <libraryType>LIB_SLAVE_ENHANCED</libraryType>
        <protocolVersion>3.95</protocolVersion>
        <applicationVersion>1.8</applicationVersion>
      </versionCommandClass>
    </entry>
    <entry>
      <commandClass>POWERLEVEL</commandClass>
      <powerLevelCommandClass>
        <version>1</version>
        <instances>1</instances>
      </powerLevelCommandClass>
    </entry>
  </supportedCommandClasses>
  <securedCommandClasses/>
  <nodeNeighbors>
    <int>XY</int>
    <int>YX</int>
  </nodeNeighbors>
  <lastSent>2016-04-29 12:29:07.5 UTC</lastSent>
  <lastReceived>2016-04-29 12:29:07.50 UTC</lastReceived>
</node>
```

Thanks!

**Comment by cdjackson** [comment]
Uploading the XML to the website will add all the basic information required - you aren’t advised to type it in by hand if you can avoid it as you’ll likely make mistakes - currently the basic info still needs to be added…. 

There is the guide you could read - its on the website - or does that not answer the questions? If not, please be specific and I’ll try and provide information.

**Comment by xsnrg** [comment]
Ah, don't try to enter the XML by hand.  There is the ability to upload it and those things will populate automatically.  Hit the gear button in the top right, then select update device.  This will give you a text field to paste the XML file contents into.  That should save you a great deal of time and error.

**Comment by thopiekar** [comment]
Found it :+1:

**Comment by cdjackson** [comment]
Cool - thanks.

Last thing remaining is to add the config parameters and association groups... The config information is in the manual...

**Comment by thopiekar** [comment]
Filled out the rest, but your site gives me:
```There are 1 association groups but none are linked to the controller. Is this correct?```
I can't answer this. No idea what that mean as I'm new to ZWave :sweat_smile: 

The user manual gave no good details, so I used http://products.z-wavealliance.org/products/1262 to fill in the info.

**Comment by cdjackson** [comment]
No probs - thanks. I’ll take a look at this, but the answer is probably no… I’ll update if so…

Thanks for making the effort to get this in - I’ll get the device into the binding tonight.

**Comment by thopiekar** [comment]
No problem! Thank you for caring about the ZWave binding here on GitHub :+1:

**Comment by thopiekar** [comment]
Reinstalled the binding but no changes.

This is what I've done in the distro shell approx one hour ago:
```
feature:uninstall openhab-binding-zwave
feature:repo-refresh
feature:install openhab-binding-zwave
```

Is that correct?

**Comment by cdjackson** [comment]
The binding didn't get created last night due to a problem with another binding and it looks like the version from this morning hasn't compiled properly (at least it doesn't run here, but a locally created version does).

**Comment by thopiekar** [comment]
Ok, thank you for the feedback :+1:

**Comment by thopiekar** [comment]
I updated the binding again and still get this:
```2016-05-02 08:29:36.500 [WARN ] [wave.discovery.ZWaveDiscoveryService] - NODE 5: Device could not be resolved to a thingType! 0108:0004:000A::1.8```

I looked that the contents of the jar file and the xml file got updated. Maybe some info missing that the binding expects?

**Comment by cdjackson** [comment]
Yes - you will keep getting this error until the problem is fixed - currently it hasn’t been fixed. The issue is nothing to do with the XML, or even the ZWave binding.

**Comment by cdjackson** [comment]
For reference, this bug is probably the cause of the issue -:

https://github.com/eclipse/smarthome/issues/1143 <https://github.com/eclipse/smarthome/issues/1143>

**Comment by thopiekar** [comment]
Ok, the device now appears with one binary_switch.
There is just one question left: How do I play now any sound? I made it a simple switch, but it does not play. Additionally how do I choose a sound?

Here is the section from the manual:
![manual_section](https://cloud.githubusercontent.com/assets/1847437/15008405/5b8edf16-11e0-11e6-877c-c73b088b84c1.png)

**Comment by cdjackson** [comment]
The documentation indicates that you can use a switch to start and stop the sound. IF that doesn't work, then please provide a log. However, I would look at the configuration of the device, but this is not something I can advise you on - you need to read the manual.

**Comment by thopiekar** [comment]
I found time to look for reasons why the siren doesn't work at the moment and according to the log it seems to me that the siren isn't responding.

When restarting openHAB2 I get this:
```
2016-05-06 14:37:37.704 [WARN ] [ding.zwave.handler.ZWaveThingHandler] - NODE 5: Initialising Thing Node...
2016-05-06 14:37:45.503 [ERROR] [nitialization.ZWaveNodeStageAdvancer] - NODE 5: Node advancer: GET_CONFIGURATION - CONFIGURATION class not supported
2016-05-06 14:37:50.509 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Timeout while sending message. Requeueing - 2 attempts left!
2016-05-06 14:37:50.510 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 5: Got an error while sending data. Resending message.
2016-05-06 14:37:55.513 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Timeout while sending message. Requeueing - 1 attempts left!
2016-05-06 14:37:55.517 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 5: Got an error while sending data. Resending message.
2016-05-06 14:38:00.525 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Timeout while sending message. Requeueing - 0 attempts left!
2016-05-06 14:38:00.527 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 5: Got an error while sending data. Resending message.
2016-05-06 14:38:05.536 [WARN ] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Too many retries. Discarding message: Message: class=SendData[0x13], type=Request[0x00], priority=Get, dest=5, callback=23, payload=05 02 25 02 
2016-05-06 14:38:10.539 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Timeout while sending message. Requeueing - 2 attempts left!
2016-05-06 14:38:10.540 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 5: Got an error while sending data. Resending message.
2016-05-06 14:38:15.544 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Timeout while sending message. Requeueing - 1 attempts left!
2016-05-06 14:38:15.548 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 5: Got an error while sending data. Resending message.
2016-05-06 14:38:20.550 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Timeout while sending message. Requeueing - 0 attempts left!
2016-05-06 14:38:20.553 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 5: Got an error while sending data. Resending message.
2016-05-06 14:38:25.567 [WARN ] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Too many retries. Discarding message: Message: class=SendData[0x13], type=Request[0x00], priority=Get, dest=5, callback=27, payload=05 02 25 02 
2016-05-06 14:38:30.576 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Timeout while sending message. Requeueing - 2 attempts left!
2016-05-06 14:38:30.577 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 5: Got an error while sending data. Resending message.
2016-05-06 14:38:35.579 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Timeout while sending message. Requeueing - 1 attempts left!
2016-05-06 14:38:35.580 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 5: Got an error while sending data. Resending message.
2016-05-06 14:38:40.582 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Timeout while sending message. Requeueing - 0 attempts left!
2016-05-06 14:38:40.583 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 5: Got an error while sending data. Resending message.
2016-05-06 14:38:45.585 [WARN ] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Too many retries. Discarding message: Message: class=SendData[0x13], type=Request[0x00], priority=Get, dest=5, callback=31, payload=05 02 25 02 
2016-05-06 14:38:50.589 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Timeout while sending message. Requeueing - 2 attempts left!
2016-05-06 14:38:50.595 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 5: Got an error while sending data. Resending message.
2016-05-06 14:38:55.603 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Timeout while sending message. Requeueing - 1 attempts left!
2016-05-06 14:38:55.605 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 5: Got an error while sending data. Resending message.
2016-05-06 14:39:00.609 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Timeout while sending message. Requeueing - 0 attempts left!
2016-05-06 14:39:00.610 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 5: Got an error while sending data. Resending message.
2016-05-06 14:39:05.613 [WARN ] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Too many retries. Discarding message: Message: class=SendData[0x13], type=Request[0x00], priority=Get, dest=5, callback=34, payload=05 02 25 02 
2016-05-06 14:39:10.615 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Timeout while sending message. Requeueing - 2 attempts left!
2016-05-06 14:39:10.617 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 5: Got an error while sending data. Resending message.
2016-05-06 14:39:15.621 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Timeout while sending message. Requeueing - 1 attempts left!
2016-05-06 14:39:15.624 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 5: Got an error while sending data. Resending message.
2016-05-06 14:39:20.629 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Timeout while sending message. Requeueing - 0 attempts left!
2016-05-06 14:39:20.635 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 5: Got an error while sending data. Resending message.
2016-05-06 14:39:25.642 [WARN ] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Too many retries. Discarding message: Message: class=SendData[0x13], type=Request[0x00], priority=Get, dest=5, callback=38, payload=05 02 25 02 
2016-05-06 14:40:30.504 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Timeout while sending message. Requeueing - 2 attempts left!
2016-05-06 14:40:30.506 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 5: Got an error while sending data. Resending message.
2016-05-06 14:40:35.511 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Timeout while sending message. Requeueing - 1 attempts left!
2016-05-06 14:40:35.513 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 5: Got an error while sending data. Resending message.
2016-05-06 14:40:40.517 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Timeout while sending message. Requeueing - 0 attempts left!
2016-05-06 14:40:40.518 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 5: Got an error while sending data. Resending message.
2016-05-06 14:40:45.523 [WARN ] [ocol.ZWaveController$ZWaveSendThread] - NODE 5: Too many retries. Discarding message: Message: class=SendData[0x13], type=Request[0x00], priority=Get, dest=5, callback=42, payload=05 02 25 02
```

And when trying to change from "Notification Report (V4)" to "Sensor Binary Report (V2)" I get:
```
2016-05-06 14:32:32.731 [ERROR] [ding.zwave.handler.ZWaveThingHandler] - NODE 5: Error getting configurationCommandClass
2016-05-06 14:32:32.734 [ERROR] [ding.zwave.handler.ZWaveThingHandler] - NODE 5: Error getting configurationCommandClass
2016-05-06 14:32:32.736 [ERROR] [ding.zwave.handler.ZWaveThingHandler] - NODE 5: Error getting configurationCommandClass
```

**Comment by cdjackson** [comment]
Please provide the log file for starters. It would probably also be useful to delete the XML if it exists and restart and send the log for that as well.

**Comment by thopiekar** [comment]
I compared the old with the new log and I see no differences related to my siren at NODE 5.
As attachment you'll find my log where I started openHAB2, made one scan and clicked the binary_switch ON and OFF.

[openhab.log.txt](https://github.com/openhab/openhab2-addons/files/252262/openhab.log.txt)

Don't know whether a more detailed log is needed (DEBUG). Just let me know if you need DEBUG messages of a specific extension.

**Comment by cdjackson** [comment]
> Don't know whether a more detailed log is needed (DEBUG).
> 
I ALWAYS need a debug log - the errors mean absolutely nothing without information that can allow me to work out what actually caused them. The ERRORS mean there is a problem, but there is no information about what the problem is without the debug information.

**Comment by thopiekar** [comment]
Ok, I just ran ```log:set DEBUG``` and disabled some bindings so the log will be less noisy.
Again, I removed all zwave xml's, made a zwave scan, tried to change the report mode and triggered the switch. Hope this log will be now more useful.

[openhab.debug.log.txt](https://github.com/openhab/openhab2-addons/files/252339/openhab.debug.log.txt)

**Comment by cdjackson** [comment]
Thanks.

You can enable ZWave debugging only with...

log:set debug org.openhab.binding.zwave.

**Comment by cdjackson** [comment]
Hmmm - did you look in the log? There is no debug messages that I can see...

**Comment by thopiekar** [comment]
That's strange. As the binding wasn't listed in log:list I expected that using ```log:set DEBUG``` will also enable DEBUG on the ZWave binding, too.
Sorry, I'll take a look on that (again) :disappointed:

**Comment by thopiekar** [comment]
[openhab.log.txt](https://github.com/openhab/openhab2-addons/files/252373/openhab.log.txt)
(Fingers crossed)

**Comment by cdjackson** [comment]
Are you running this device on batteries, or mains power?

**Comment by thopiekar** [comment]
At the moment it is only running on mains. A battery is optional and
currently not inserted.

**Comment by cdjackson** [comment]
Has it ever been run on batteries?

The issue is that it's not responding to the basic messages to get the manufacturer information. Clearly it should, otherwise you wouldn't get as far as having the type/id and getting an XML. I don't know why it's not responding - is it close to the controller (ie within a few meters)?

**Comment by thopiekar** [comment]
Nope, it was always running on mains so far. Well, I guess the manufacturer
just made it act like a battery powered device. So in case it has to work
on batteries only, it will still work the same and save energy.
I assembled the siren already, but I can dismantle it again and tap the
wakeup button if needed.

**Comment by cdjackson** [comment]
How far from the controller is it?

**Comment by thopiekar** [comment]
Approx 5 meters. When I start habmin and use the network viewer it looks good for me.

![habmin](https://cloud.githubusercontent.com/assets/1847437/15078688/ace5a1f8-13b4-11e6-8134-03db7db8f3ee.png)

And the siren was always directly connected to Node1 (USB controller) so far.

**Comment by maggu2810** [comment]
@thopiekar
Using <code>log:set</code> without any logger (package) will change the root logger.
openHAB Distro sets already a different log level for org.openhab (see: https://github.com/openhab/openhab-distro/blob/0b05b62/distributions/distribution-resources/src/main/resources/etc/org.ops4j.pax.logging.cfg#L10), so all changes to the root logger will not change org.openhab stuff (and so not org.openhab.binding.zwave).

@cdjackson Perhaps you should publish a Wiki page how to get Z-Wave debug logs. :wink:

**Comment by thopiekar** [comment]
@cdjackson So at the moment there is no clear explanation why it doesn't work? Now I have the siren less then 1 meter from the controller and got still the same behaviour.

**Comment by cdjackson** [comment]
Well, to be more precise, we don't know why this device isn't responding to this particular message now when it presumably used to respond in the past (given that you have the manufacturer information in the title to this issue).
I don't know why that is - it seems to be something with the device. It is acking the message that is sent, but it never sends a response back. Maybe you can try factory resetting the device to see if it responds then.

**Comment by thopiekar** [comment]
Thanks! I didn't beleaved it will make any difference, but I made a factory reset and it simply works!

It would be great if you could give me one offtopic hint/information at the end:
I tried to exclude the siren to remove the node from the controller (and also openHAB), but wasn't successful. Now after factory reset the node is still there. Is there a way to remove this dead node from the controller?

Many thanks again!

**Comment by cdjackson** [comment]
> I made a factory reset and it simply works!

:) Thanks.


> . Is there a way to remove this dead node from the controller?

With the old node added as a thing, you can select 'Advanced mode' from the tools menu, and you should have one or two options. One might say something like "Move node to failed node list" and the other something like "Delete the device".

You can only delete a node when it is on the controllers "Failed nodes list". For mains powered devices, they will be moved there automatically by the controller, however for battery devices, they never seem to be moved there. So, you need to use the option to remove to the failed items list, and then from there use the option to delete it.

Let me know how that works - it doesn't always work unfortunately...

**Comment by thopiekar** [comment]
It worked on the old node from my siren and one of two old nodes of my remote control. The one which I can't get removed is still always marked as ONLINE. Don't understand why.
The other two which have been removed were correctly marked as OFFLINE.

It is called Node 6 and maybe you'll be able to find something in the logs above.
If you like I can openen an new issue for that.

**Comment by cdjackson** [comment]
If it's a battery node, then it might well show up as ONLINE in the binding, but that doesn't necessarily mean it's online... If you delete this thing and then restart the binding, is it found again?
