### ISSUE TITLE
[ZWave] Unknown thingType: 7FFFFFFF:7FFFFFFF:7FFFFFFF::0.0

### ISSUE THREAD

**Issue by thopiekar** [openhab/openhab2-addons#855]
Another new thingType I found when adding a "Secure 4 Button Key Chain Controller" by ZWave.me (here branded by devolo) (http://products.z-wavealliance.org/products/1282)

```
21:18:16.818 [WARN ] [wave.discovery.ZWaveDiscoveryService] - NODE 6: Device could not be resolved to a thingType! 7FFFFFFF:7FFFFFFF:7FFFFFFF::0.0
21:18:16.880 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'zwave:device:5ec07f15:node6' to inbox.
21:18:16.881 [INFO ] [smarthome.event.InboxAddedEvent     ] - Discovery Result with UID 'zwave:device:5ec07f15:node6' has been added.
```

**Comment by xsnrg** [comment]
When you see the 7FFFFFFF stuff, that means the device (typically battery devices) has not initialized yet and the binding does not have all the information it needs about the device.  Give it more time, or force it to wake up a few times.  The XML file is not created yet at this point either.

**Comment by thopiekar** [comment]
@xsnrg Thanks! I'll give feedback if I know something new :+1:

**Comment by cdjackson** [comment]
As @xsnrg said, this is normal. The binding will add the device before it knows the manufacturer information. Once this is known it will be updated.
