### ISSUE TITLE
Netatmo binding stops to work once it starts to rain

### ISSUE THREAD

**Issue by pail23** [openhab/openhab2-addons#866]
I have a netatmo station with a rain module installed. Once it starts to rain, the netatmo binding creates the following exception:
com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 6.06 at line 1 column 788 path $.body.modules[1].dashboard_data.sum_rain_24
##

**Comment by clinique** [comment]
@pail23 : second incident raised on this matter. Will take a look very soon.

**Comment by clinique** [comment]
Yes, got it. In swagger, rain is described as an Integer, need to correct this.

**Comment by clinique** [comment]
Was about to correct this, but currently not able to generate new version of swagger client due to opened issue in swagger codegen (https://github.com/swagger-api/swagger-codegen/issues/2096) - will have to wait a bit :(

**Comment by cbornet** [comment]
@clinique I removed the use of allOf in the swagger declaration to workaround the inheritance issue. Can you have a look ?

**Comment by clinique** [comment]
@cbornet : thanks a lot, I'll go on with this this week-end.

**Comment by clinique** [comment]
@cbornet : done, it works! Thanks a lot

**Comment by clinique** [comment]
PR pushed

**Comment by lolodomo** [comment]
@clinique : this issue should be closed ?

**Comment by clinique** [comment]
@lolodomo , it should be closeable while merged  #1099

**Comment by lolodomo** [comment]
Issue to close.
