### ISSUE TITLE
Configuration Needed.

### ISSUE THREAD

**Issue by carryonrewardless** [openhab/openhab2-addons#894]
How do I develop configuration parameters for Device 325 from the attached  Users Manual:
[ZWS12Conf.pdf](https://github.com/openhab/openhab2-addons/files/251444/ZWS12Conf.pdf)

Perhaps Parameters 10, 12, 14, 18 & 22 from Device 116 could be adopted?

**Comment by cdjackson** [comment]
I don't see any informaiton on the configuration in the manual. You need to find this information somewhere - ultimately it needs to come from the manufacturer.

**Comment by carryonrewardless** [comment]
The page 5 info doesn't help?

**Comment by cdjackson** [comment]
No- I couldn't see any configuration parameters in this document.

**Comment by carryonrewardless** [comment]
Concerning the manufacturer if Fakro are anything like Wintop I will have little or no chance there but will try.

**Comment by cdjackson** [comment]
You could also check openZwave database, and the pepper1 database to see if the device is in either of those…

**Comment by carryonrewardless** [comment]
For OpenZwave it is on their recordnotfound list.
The pepper1.net xml file is attached to the device list item and is quite scant.
The Zwave Alliance has little: http://products.z-wavealliance.org/products/105

**Comment by cdjackson** [comment]
Ok - I don't think there's much more we can do. I propose to close this issue until someone can find more information?

**Comment by carryonrewardless** [comment]
I will post back when I here from Fakro.

**Comment by carryonrewardless** [comment]
Nothing forthcoming from Fakro but he device is sort of ok. It is curious that this device - a motorised chain actuator to open windows - shows as having channels for a switch and one for brightness i.e. a dimmer. In creating Items I cannot select Item Type "Rollershutter" as it only works when selecting "Dimmer".
This comes from Command Class - Switch Multi-Level but this is where my understanding is limited. Is this something that can be " adjusted" or is it just the way it is with this device? In OH1 it would work ok with "Rollershutter" as the Item Type in the Items file.
Also is there a way to get % opening working? Previously used %d.

**Comment by cdjackson** [comment]
> On 23 Jun 2016, at 10:46, carryonrewardless <notifications@github.com> wrote:
> 
> Nothing forthcoming from Fakro but he device is sort of ok. It is curious that this device - a motorised chain actuator to open windows - shows as having channels for a switch and one for brightness i.e. a dimmer. In creating Items I cannot select Item Type "Rollershutter" as it only works when selecting "Dimmer”.
> 
Then we need to change the channels. The database makes a best guess when selecting the channel type, but this can be changed quite easily to correctly reflect the device.


> This comes from Command Class - Switch Multi-Level but this is where my understanding is limited. Is this something that can be " adjusted" or is it just the way it is with this device? In OH1 it would work ok with "Rollershutter" as the Item Type in the Items file.
> 
I’m not sure I understand the question, but I suspect you need to update the channel. I thought I’d added some blinds channels last week for the FGRM222 (I think) but I’m not sure if that is included so I’d need to check.

**Comment by carryonrewardless** [comment]
> I suspect you need to update the channel.

Updated to 2.0.0.201606220105    | ZWave Binding, deleted Item and created anew. Same behaviour observed i.e. need to select Item Type = Dimmer. Selecting Rollershutter results in 
Command for unknown channel zwave:device:15577aece38:node5:switch_dimmer with UpDownType.

> Then we need to change the channels.

Do I need to do something for this?

**Comment by cdjackson** [comment]
> 
> I suspect you need to update the channel.
> 
> Updated to 2.0.0.201606220105 | ZWave Binding, deleted Item and created anew. Same behaviour observed i.e. need to select Item Type = Dimmer. Selecting Rollershutter results in 
> Command for unknown channel zwave:device:15577aece38:node5:switch_dimmer with UpDownType.
> 
Ummm, the database hasn’t been changed has it to update the channels, so of course there will have the same behaviour.  You can’t just change the item type - this isn’t the same thing as the channel type.

> Then we need to change the channels.
> 
> Do I need to do something for this?
> 
I first need to add the channels to the binding, then we need to update the database.

**Comment by cdjackson** [comment]
I'm not sure where we are with this one. If there are still open points then please open a new issue [in the new Z-Wave repository](https://github.com/openhab/org.openhab.binding.zwave/issues).
