### ISSUE TITLE
Freebox binding: add automatic discovery of things

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab2-addons#897]
One another enhancement would be to add automatic discovery of the Freebox server and other things.

I will implement this enhancement.

**Comment by lolodomo** [comment]
The automatic discovery of the Freebox server is implemented and relies on mDNS discovery service. It was not tested because the mDNS discovery service is apparently no working as expected in OH2, meaning it does not discover the Freebox Server service type.

**Comment by kaikreuzer** [comment]
> mDNS discovery service is apparently no working as expected in OH2

It is working...

**Comment by lolodomo** [comment]
Implemented with PR #919.

Note that automatic discovery of the Freebox Revolution is not working as expected because the mDNS discovery service is not yet working in all circonstances.
Discovery of things (phone, network devices and network interfaces) is working well.
