### ISSUE TITLE
zwave2.0-SNAPSHOT: InvalidKeyException: No installed provider supports this key: (null)

### ISSUE THREAD

**Issue by grizzlyjere** [openhab/openhab2-addons#902]
Not sure if this is a known issue due to the work occurring on the Security protocols.

In the recent builds my Z-Wave lock is no longer working -- openHAB no longer seems to get status updates and is unable to control the lock.  So far I haven't found anything in the trace logs that show anything amiss, except....

If I try to manually unlock it the logs show an InvalidKeyException (previously as reported in #770 it would generate an error about an unknown alarm status).  I'm not sure if this exception is related to the lock status not updating or just part of the work under #770.  Trace logs are attached

[ZWave Lock Trace logs.txt](https://github.com/openhab/openhab2-addons/files/253462/ZWave.Lock.Trace.logs.txt)

**Comment by grizzlyjere** [comment]
I believe this issue is because _encryptKey_ is set in not being set as it's expected to be in the _ZWaveSecurityCommandClass_ constructor.  The object is created in _ApplicationCommandMessageClass.handleRequest()_ via a cast -- would that cause the constructor to not be called?

I tried instantiating _ZWaveSecurityCommandClassWithInitialization_ and setting the values instead of doing the cast and while the exception went away, there were errors stating it couldn't decrypt the message.

I was able to get everything to work by adding the following code to decryptMessage (the code was taken from sendNextMessageUsingDeviceNonce).  I believe it also will be needed in other methods.
```
            if (encryptKey == null) {
                setupNetworkKey(false);
            }
```

I'm happy to submit a PR to add the code above, but instead wanted to see if there was a better way to handle address this.  I saw some TODOs  in _ApplicationCommandMessageClass.handleRequest_ stating the code need to be refactored.  Maybe the above could be a stopgap until that work is done?  I'm not too familiar with the intricacies of Java and the OpenHAB code base, so I'm not sure if there is a better way.

**Comment by cdjackson** [comment]
Feel free to submit a PR and I’ll take a look, but note that I am actively working on the security classes to fix issues with transaction handling so really I’m not looking at any security issues until I have it working satisfactorily here.

**Comment by cdjackson** [comment]
Closing for now. Once we have the secure class support in OH2 we can revisit this.
