### ISSUE TITLE
Running Designer IDE on WIndows using leads to an SWT Exception

### ISSUE THREAD

**Issue by ChristophRathfelder** [openhab/openhab2-addons#915]
After getting the SmartHome Designer building, I tried to start the Designer. I tried it with JDK1.7 and JDK1.8 on my Windows machine. Since there is only a MAC RunConfig, I tried to this one, which leads to a org.eclipse.swt.SWTException Invalid thread access exception. Furthermore some bindings of components can not be performed.
Is there anything different between a MAC runconfig and a Windows runconfig?

!SESSION 2016-05-11 16:17:53.849 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.7.0_21
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product org.eclipse.smarthome.designer.core.product
Command-line arguments:  -product org.eclipse.smarthome.designer.core.product -data C:\development\SmartHome\smarthome-master\ws/../smarthome-designer -dev file:C:/development/SmartHome/smarthome-master/ws/.metadata/.plugins/org.eclipse.pde.core/SmartHome Designer (Mac)/dev.properties -os win32 -ws win32 -consoleLog

!ENTRY org.eclipse.equinox.ds 1 0 2016-05-11 16:17:54.995
!MESSAGE Could not bind a reference of component ConfigDescriptionRegistry. The reference is: Reference[name = ConfigOptionProvider, interface = org.eclipse.smarthome.config.core.ConfigOptionProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addConfigOptionProvider, unbind = removeConfigOptionProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2016-05-11 16:17:54.998
!MESSAGE Could not bind a reference of component ConfigDescriptionRegistry. The reference is: Reference[name = ConfigDescriptionProvider, interface = org.eclipse.smarthome.config.core.ConfigDescriptionProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addConfigDescriptionProvider, unbind = removeConfigDescriptionProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2016-05-11 16:17:55.573
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.binding.BindingInfoRegistry. The reference is: Reference[name = BindingInfoProvider, interface = org.eclipse.smarthome.core.binding.BindingInfoProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addBindingInfoProvider, unbind = removeBindingInfoProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2016-05-11 16:17:55.766
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.itemregistry. The reference is: Reference[name = ItemProvider, interface = org.eclipse.smarthome.core.items.ItemProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addProvider, unbind = removeProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2016-05-11 16:17:55.769
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.itemregistry. The reference is: Reference[name = EventPublisher, interface = org.eclipse.smarthome.core.events.EventPublisher, policy = dynamic, cardinality = 0..1, target = null, bind = setEventPublisher, unbind = unsetEventPublisher]

!ENTRY org.eclipse.equinox.ds 1 0 2016-05-11 16:17:55.804
!MESSAGE Could not bind a reference of component ConfigStatusService. The reference is: Reference[name = ConfigStatusProvider, interface = org.eclipse.smarthome.config.core.status.ConfigStatusProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addConfigStatusProvider, unbind = removeConfigStatusProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2016-05-11 16:17:55.828
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.type.ChannelTypeRegistry. The reference is: Reference[name = ChannelTypeProvider, interface = org.eclipse.smarthome.core.thing.type.ChannelTypeProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addChannelTypeProvider, unbind = removeChannelTypeProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2016-05-11 16:17:55.839
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.link.ItemThingLinkRegistry. The reference is: Reference[name = ItemThingLinkProvider, interface = org.eclipse.smarthome.core.thing.link.ItemThingLinkProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addProvider, unbind = removeProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2016-05-11 16:17:55.865
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.ThingRegistry. The reference is: Reference[name = ThingProvider, interface = org.eclipse.smarthome.core.thing.ThingProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addProvider, unbind = removeProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2016-05-11 16:17:55.877
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.ThingRegistry. The reference is: Reference[name = ThingHandlerFactory, interface = org.eclipse.smarthome.core.thing.binding.ThingHandlerFactory, policy = dynamic, cardinality = 0..n, target = null, bind = addThingHandlerFactory, unbind = removeThingHandlerFactory]

!ENTRY org.eclipse.equinox.ds 1 0 2016-05-11 16:17:55.883
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.link.ItemChannelLinkRegistry. The reference is: Reference[name = ItemChannelLinkProvider, interface = org.eclipse.smarthome.core.thing.link.ItemChannelLinkProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addProvider, unbind = removeProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2016-05-11 16:17:55.894
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.type.ThingTypeRegistry. The reference is: Reference[name = ThingTypeProvider, interface = org.eclipse.smarthome.core.thing.binding.ThingTypeProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addThingTypeProvider, unbind = removeThingTypeProvider]

!ENTRY org.eclipse.osgi 4 0 2016-05-11 16:21:47.826
!MESSAGE Application error
!STACK 1
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4441)
	at org.eclipse.swt.SWT.error(SWT.java:4356)
	at org.eclipse.swt.SWT.error(SWT.java:4327)
	at org.eclipse.swt.widgets.Display.error(Display.java:1258)
	at org.eclipse.swt.widgets.Display.checkDevice(Display.java:764)
	at org.eclipse.swt.widgets.Display.getHighContrast(Display.java:1864)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.setCSSContextVariables(E4Application.java:327)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:305)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:601)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.smarthome.designer.ui.internal.application.Application.start(Application.java:32)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:382)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:236)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)

**Comment by kaikreuzer** [comment]
> Is there anything different between a MAC runconfig and a Windows runconfig?

Yes, the SWT components need to be changed and maybe some other stuff. Since we do not have any maintainer on Windows, we do not maintain a Windows launch config, so you have to try to get it working yourself.

Note that the Designer is anyhow currently in a rather messy state (see also https://github.com/eclipse/smarthome/issues/1442), which needs to be solved.

So my advice is to rather use the 0.7.0 version from [our download site](https://www.eclipse.org/smarthome/documentation/community/downloads.html#designer-builds).

**Comment by kaikreuzer** [comment]
Btw, why did you open this issue at openhab2-addons and not eclipse/smarthome? It does not really belong here...

**Comment by ChristophRathfelder** [comment]
open the issue on openhab2-addons was my fault. Should be in eclipse/smarthome. To be honest, I did not realize, that i was in openhab2-addons.
