### ISSUE TITLE
Adding GPIO support to openHAB 2

### ISSUE THREAD

**Issue by danielbarron42** [openhab/openhab2-addons#945]
I am working on adding GPIO support by adding the 1.9 version of the GPIO binding to the distribution following the instructions here:
https://github.com/openhab/openhab-distro/blob/master/docs/sources/features/compatibilitylayer.md#how-to-add-a-successfully-tested-1x-add-on-to-the-distribution

Adding this issue for tracking purposes.

**Comment by danielbarron42** [comment]
This is as far as I've got:

https://github.com/danielbarron42/openhab2-addons/tree/945-GPIOopenHAB2

I've not used github actively before, nor used Maven so it's taking me time to learn it.

Currently working on this error:

[ERROR] Failed to execute goal org.apache.karaf.tooling:karaf-maven-plugin:4.0.4:verify (verify) on project openhab2-addons-verify: Feature resolution failed for [openhab-binding-gpio/2.0.0.SNAPSHOT]
[ERROR] Message: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-binding-gpio; type=karaf.feature; version=2.0.0.SNAPSHOT; filter:="(&(osgi.identity=openhab-binding-gpio)(type=karaf.feature)(version>=2.0.0.SNAPSHOT))" [caused by: Unable to resolve openhab-binding-gpio/2.0.0.SNAPSHOT: missing requirement [openhab-binding-gpio/2.0.0.SNAPSHOT] osgi.identity; osgi.identity=org.openhab.binding.gpio; type=osgi.bundle; version="[2.0.0.201605201609,2.0.0.201605201609]"; resolution:=mandatory [caused by: Unable to resolve org.openhab.binding.gpio/2.0.0.201605201609: missing requirement [org.openhab.binding.gpio/2.0.0.201605201609] osgi.wiring.package; filter:="(osgi.wiring.package=org.openhab.io.gpio)"]]

**Comment by danielbarron42** [comment]
So I've been looking at this for quite a while now.  My approach has been to learn by example and diff OH1 and OH2 addons to see what needs to be changed.  I've also followed the instructions I linked above.

The problem is I don't know what I'm doing and the error is probably simple to fix such as a change to a manifest file or something.

Running mvn install after mvn clean in Git Shell I get the following trimmed error:
[INFO] openHAB Feature Addons External .................... SUCCESS [  0.656 s]
[INFO] openHAB 2 Feature Addons ........................... SUCCESS [  1.886 s]
[INFO] openHAB 2 Feature Verification ..................... FAILURE [ 33.355 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:29 min
[INFO] Finished at: 2016-05-24T10:01:24+01:00
[INFO] Final Memory: 62M/985M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.karaf.tooling:karaf-maven-plugin:4.0.4:verify (verify) on project openhab2-addons-verify: Feature resolution failed for [openhab-binding-gpio/2.0.0.SNAPSHOT]
[ERROR] Message: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-binding-gpio; type=karaf.feature; version=2.0.0.SNAPSHOT; filter:="(&(osgi.identity=openhab-binding-gpio)(type=karaf.feature)(version>=2.0.0.SNAPSHOT))" [caused by: Unable to resolve openhab-binding-gpio/2.0.0.SNAPSHOT: missing requirement [openhab-binding-gpio/2.0.0.SNAPSHOT] osgi.identity; osgi.identity=org.openhab.binding.gpio; type=osgi.bundle; version="[2.0.0.201605240900,2.0.0.201605240900]"; resolution:=mandatory [caused by: Unable to resolve org.openhab.binding.gpio/2.0.0.201605240900: missing requirement [org.openhab.binding.gpio/2.0.0.201605240900] osgi.wiring.package; filter:="(osgi.wiring.package=org.openhab.io.gpio)"]]
[ERROR] Repositories: {
[ERROR] mvn:org.apache.karaf.features/framework/4.0.4/xml/features
[ERROR] mvn:org.apache.karaf.features/standard/4.0.4/xml/features
[ERROR] mvn:org.eclipse.smarthome/karaf-tp/0.8.0-SNAPSHOT/xml/features
[ERROR] mvn:org.eclipse.smarthome/karaf/0.8.0-SNAPSHOT/xml/features
[ERROR] mvn:org.openhab.addons/openhab2-addons/2.0.0-SNAPSHOT/xml/features
[ERROR] mvn:org.openhab.core/openhab-core/2.0.0-SNAPSHOT/xml/features
[ERROR] mvn:org.ops4j.pax.web/pax-web-features/4.2.4/xml/features
[ERROR] }
[ERROR] Resources: {
[ERROR] mvn:com.eclipsesource.jaxrs/provider-gson/2.3
[ERROR] mvn:com.eclipsesource.jaxrs/publisher/5.3.1
[ERROR] mvn:com.fasterxml.jackson.core/jackson-annotations/2.4.5

**Comment by maggu2810** [comment]
Your feature "openhab-binding-gpio" for the binding "openhab-binding-gpio" cannot be completely resolved.
The feature does not install anything that brings the package "org.openhab.io.gpio".

* osgi.identity=openhab-binding-gpio; type=karaf.feature; version=2.0.0.SNAPSHOT
the openhab-binding-gpio feature

* missing requirement
there is a missing requirement

* osgi.identity; osgi.identity=org.openhab.binding.gpio; type=osgi.bundle; version="[2.0.0.201605240900,2.0.0.201605240900]"

=> the bundle "org.openhab.binding.gpio" requires something that is not available

* osgi.wiring.package; filter:="(osgi.wiring.package=org.openhab.io.gpio)"
the package "org.openhab.io.gpio" is missing

So you should depend no the io.gpio feature or bundle.

**Comment by danielbarron42** [comment]
Thanks that helps me understand the error message.

org.openhab.io.gpio is needed as it's imported in the java files.

I've managed to track down the problem to a line missing in feature.xml

It compiles now without error!  Hurray.  Thanks!  Next some testing.

**Comment by danielbarron42** [comment]
Initial PR made.

**Comment by macsito07** [comment]
Any documentation on how to install gpio binding in openhab2?

**Comment by Bagunda** [comment]
How to control GPIO from OH2?????????
I don't understand

**Comment by ThomDietrich** [comment]
@Bagunda please respect that the issue tracker is used for development coordination. End user support is done via the community forum: https://community.openhab.org

* GPIO Binding README: http://docs.openhab.org/addons/bindings/gpio1/readme.html
* A forum search for GPIO: https://community.openhab.org/search?q=gpio%20binding

If you have a specific question the readme and an extensive search do not answer please open a new thread stating your goal and problem clearly (ten question marks do not have that effect).
