### ISSUE TITLE
Formatting of readme wrong for MAX! binding in documentation site

### ISSUE THREAD

**Issue by marcelrv** [openhab/openhab2-addons#956]
In GH it seems the document is formatted fine, but on the docu pages the sections around max.items
and sitemap are formatted wrong.

https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.max/README.md

http://docs.openhab.org/features/bindings/max/readme.html

Is this something I need to fix from my side (did not see directly an obvious cause) or is this because Jekyll conversion somehow?

Same is for the formatting of the bullets on the bottom side of the page in the 'Action Buttons' section. Are bullets not allowed/possible or do I need to format them in some soft of different way?

**Comment by watou** [comment]
It looks like Jekyll needs a blank line before the \`\`\` delimiter. Also it looks like the charset isn't specified because the degree symbol comes through incorrectly.

**Comment by marcelrv** [comment]
Thanks,
Will create pr tonight to fix that than

**Comment by kaikreuzer** [comment]
@marcelrv This problem exists for quite some other bindings as well - if you happen to find the time to address them in the same run, I would appreciate it :-)

**Comment by marcelrv** [comment]
created PR to fix the issue for the code blocks formatting.

Bullets still seem an issue. Still not clear how to fix those (possibly all list also need a blank line, though that line is not always wanted)

Note see also
https://github.com/jekyll/jekyll/issues/4448

**Comment by marcelrv** [comment]
fixed another formatting issue where space is missing in the headings generates a formatting problem in the docu site
