### ISSUE TITLE
[homematic] Bridge (and things) can only be found after restart

### ISSUE THREAD

**Issue by mastix** [openhab/openhab2-addons#967]
Hey guys,

first of all: Thanks for the great community!

I'm currently running OH 2.0.0.b3 on my mac. I've installed the homematic binding and added the bridge manually (address: IP of CCU2 and type: Auto).

Log output:

> 2016-05-25 12:44:58.728 [INFO ] [smarthome.event.ThingAddedEvent     ] - Thing 'homematic:bridge:5532d659' has been added.
> 2016-05-25 12:44:58.735 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'homematic:bridge:5532d659' changed from UNINITIALIZED to INITIALIZING
> 2016-05-25 12:44:59.131 [INFO ] [ternal.communicator.HomematicGateway] - Interface 'WIRED' on gateway '5532d659' not available, disabling support
> 2016-05-25 12:44:59.134 [INFO ] [ternal.communicator.HomematicGateway] - Interface 'CUXD' on gateway '5532d659' not available, disabling support
> 2016-05-25 12:44:59.163 [INFO ] [ternal.communicator.HomematicGateway] - HmGatewayInfo[id=CCU,type=CCU2,firmware=2.19.9,address=LEQ0418945]
> 2016-05-25 12:44:59.517 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'homematic:bridge:5532d659' changed from INITIALIZING to UNINITIALIZED (HANDLER_INITIALIZING_ERROR): Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1bfa0452 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@2ac63c94[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 34]
> 2016-05-25 12:44:59.518 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occured while initializing handler of thing 'homematic:bridge:5532d659': java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1bfa0452 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@2ac63c94[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 34]
> java.util.concurrent.ExecutionException: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1bfa0452 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@2ac63c94[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 34]
>         at java.util.concurrent.FutureTask.report(FutureTask.java:122)[:1.8.0_31]
>         at java.util.concurrent.FutureTask.get(FutureTask.java:206)[:1.8.0_31]
>         at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:179)[98:org.eclipse.smarthome.core:0.8.0.b5]
>         at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:72)[98:org.eclipse.smarthome.core:0.8.0.b5]
>         at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:56)[98:org.eclipse.smarthome.core:0.8.0.b5]
>         at org.eclipse.smarthome.core.thing.internal.ThingManager$7.run(ThingManager.java:684)[104:org.eclipse.smarthome.core.thing:0.8.0.b5]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_31]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_31]
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_31]
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_31]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_31]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_31]
>         at java.lang.Thread.run(Thread.java:745)[:1.8.0_31]
> Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1bfa0452 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@2ac63c94[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 34]
>         at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)[:1.8.0_31]
>         at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)[:1.8.0_31]
>         at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)[:1.8.0_31]
>         at java.util.concurrent.ScheduledThreadPoolExecutor.scheduleWithFixedDelay(ScheduledThreadPoolExecutor.java:597)[:1.8.0_31]
>         at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.startWatchdogs(AbstractHomematicGateway.java:238)[191:org.openhab.binding.homematic:2.0.0.b3]
>         at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.initialize(AbstractHomematicGateway.java:147)[191:org.openhab.binding.homematic:2.0.0.b3]
>         at org.openhab.binding.homematic.handler.HomematicBridgeHandler.initialize(HomematicBridgeHandler.java:71)[191:org.openhab.binding.homematic:2.0.0.b3]
>         at org.eclipse.smarthome.core.thing.internal.ThingManager$7$1.call(ThingManager.java:687)[104:org.eclipse.smarthome.core.thing:0.8.0.b5]
>         at org.eclipse.smarthome.core.thing.internal.ThingManager$7$1.call(ThingManager.java:1)[104:org.eclipse.smarthome.core.thing:0.8.0.b5]
>         at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:170)[98:org.eclipse.smarthome.core:0.8.0.b5]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_31]

Then I do a restart of OH:

Log output:

> 2016-05-25 12:45:46.592 [INFO ] [b.core.service.AbstractActiveService] - HTTP Refresh Service has been started
> 2016-05-25 12:45:46.950 [INFO ] [assic.internal.servlet.WebAppServlet] - Started Classic UI at /classicui/app
> 2016-05-25 12:45:46.958 [INFO ] [basic.internal.servlet.WebAppServlet] - Started Basic UI at /basicui/app
> 2016-05-25 12:45:47.115 [INFO ] [ternal.communicator.HomematicGateway] - Interface 'WIRED' on gateway '5532d659' not available, disabling support
> 2016-05-25 12:45:47.117 [INFO ] [ternal.communicator.HomematicGateway] - Interface 'CUXD' on gateway '5532d659' not available, disabling support
> 2016-05-25 12:45:47.141 [INFO ] [ternal.communicator.HomematicGateway] - HmGatewayInfo[id=CCU,type=CCU2,firmware=2.19.9,address=LEQ0418945]
> 2016-05-25 12:45:48.853 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'homematic:HM-RCV-50:5532d659:BidCoS-RF' to inbox.
> [... skipped lines...]
> 2016-05-25 12:45:49.451 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'homematic:HM-CC-RT-DN:5532d659:LEQ0584610' to inbox.
> 2016-05-25 12:45:49.452 [INFO ] [smarthome.event.InboxAddedEvent     ] - Discovery Result with UID 'homematic:HM-CC-RT-DN:5532d659:LEQ0584610' has been added.
> 2016-05-25 12:45:49.463 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'homematic:HM-CC-RT-DN:5532d659:LEQ1067393' to inbox.
> 2016-05-25 12:45:49.463 [INFO ] [smarthome.event.InboxAddedEvent     ] - Discovery Result with UID 'homematic:HM-CC-RT-DN:5532d659:LEQ1067393' has been added.
> 2016-05-25 12:45:49.488 [INFO ] [ng.homematic.internal.misc.MiscUtils] - Datapoint name 'Alarmzone 1' contains invalid characters, new Datapoint name 'Alarmzone_1'
> 2016-05-25 12:45:49.517 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'homematic:GATEWAY-EXTRAS-5532D659:5532d659:GWE00000000' to inbox.
> 2016-05-25 12:45:49.518 [INFO ] [smarthome.event.InboxAddedEvent     ] - Discovery Result with UID 'homematic:GATEWAY-EXTRAS-5532D659:5532d659:GWE00000000' has been added.
> 2016-05-25 12:45:49.524 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'homematic:bridge:5532d659' changed from INITIALIZING to ONLINE

Seems like the things are only added to the inbox during a restart.

Is that a known issue? Or am I doing something wrong? :)

Greetz,

Sascha

**Comment by kaikreuzer** [comment]
@gerrieg Could you have a look?

**Comment by gerrieg** [comment]
@kaikreuzer 
I think that this has nothing todo with the Homematic binding, the exception comes from the ThreadPoolManager when the binding schedules a job: [Source](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/AbstractHomematicGateway.java#L235)

**Comment by kaikreuzer** [comment]
It says that the thread pool is already terminated when the job is tried to be executed.

It seems that the Homematic binding uses a custom thread pool, but I am not sure where its size is actually configured and maybe it is also a problem that it is terminated in dispose(), but not reconstructed in initialize() (I am not sure if the same handler instance might get reused).

@gerrieg: Is it required to use a custom pool or could you use the default one from BaseThingHandler?

**Comment by gerrieg** [comment]
Sure, i can use another pool. I am going to change that in the next days.
