### ISSUE TITLE
ZWave SECURITY_ERROR MAC / Failed to decrypt 

### ISSUE THREAD

**Issue by ingermaa** [openhab/openhab2-addons#968]
Device is Fibaro FGMS001 Motion sensor. After i added the device i get these errors in the log:

08:31:39.746 [ERROR] [mmandclass.ZWaveSecurityCommandClass] - NODE 8: SECURITY_ERROR MAC Authentication of packet failed. Dropping.
08:31:39.750 [ERROR] [ssage.ApplicationCommandMessageClass] - NODE 8: Failed to decrypt message out of Message: class=ApplicationCommandHandler[0x04], type=Request[0x00], priority=High, dest=255, callback=0, payload=00 08 1D 98 81 78 09 3B 0F A4 24 30 B2 7D AC D1 63 3E 38 33 57 ED 88 0B 1A 84 68 11 89 CA 9A 48  .
08:31:39.757 [ERROR] [col.security.ZWaveSecureNonceTracker] - NODE 8: SECURITY_ERROR Device message contained nonce that was previously used, id=14.
08:31:39.759 [ERROR] [col.security.ZWaveSecureNonceTracker] - NODE 8: SECURITY_ERROR Device message contained nonce that was previously used, id=55.
08:31:39.761 [ERROR] [col.security.ZWaveSecureNonceTracker] - NODE 8: SECURITY_ERROR Device message contained nonce that is unknown to us, id=64

Using 2.0.0.beta3

**Comment by cdjackson** [comment]
I would prefer to close this for now. Currently the security is not well supported in OH and work is ongoing to resolve this. I don't think there is any point in opening issues until we get to a point that support for the security classes is properly available.

**Comment by ingermaa** [comment]
Ok. I was not aware of the current status of the security implementation.
