### ISSUE TITLE
[System Info] Add Used % channel to Memory group

### ISSUE THREAD

**Issue by metbril** [openhab/openhab2-addons#972]
Feature request.

The Memory group currently provides 4 channels:
- Total
- Available
- Used
- Available (%)

For system monitoring I'd like to use the Used percentage (in combination with CPU Load)

I could create a rule that computes this (proper workaround for now) but that puts a lot of extra stress on the system.

So it would be great if the Used Percent channel is natively available.
##

**Comment by rtvb** [comment]
Current workaround rule:

```
rule "Memory Used Changed"
when
	Item System_Memory_Used changed
then
	logDebug("MemoryUsedChanged", "Item System_Memory_Used changed to " + System_Memory_Used.state.toString)

	var Number t = System_Memory_Total.state
	var Number u = System_Memory_Used.state
	var Number p = ((u / t) * 100)
	
	// System Info delivers percentages in 1 decimal. Replicate this behavior.
	p = (Math::round(p.floatValue*10.0)/10.0)

	postUpdate(System_Memory_UsedPercent, p)

end 
```

**Comment by martinvw** [comment]
Hello @metbril (did you rename yourself?)

Does the following merged PR resolve your issue: 
https://github.com/openhab/openhab2-addons/pull/2207

If so can we or your close the issue.

Regards

**Comment by metbril** [comment]
Yes I renamed my account. 

I will test it in the coming days. Feel free to test it yourself, too. The RFC was pretty straightforward.

**Comment by metbril** [comment]
Have it running this evening. Seems to be OK.

**Comment by martinvw** [comment]
Thanks for testing!
