### ISSUE TITLE
Z-Wave DATABASE: Evolve LFM-20 Relay Switch

### ISSUE THREAD

**Issue by BradyRosino** [openhab/openhab2-addons#979]
I'd like to see the Evolve LFM-20 Relay Switch added to the zwave database. It is actually exactly the same as the Linear FS20Z. The two share the exact same manufacturerRef value but different manufacturerId, so it must simply be a minor rebranding.

Looking in the OpenHAB1 products.xml the LFM-20 is defined, but there is no associated config file. Attached is what the config file should be.

OpenHAB2 is seeing it, but not generating the node#.xml file. Let me know if any additional information is required.

[evolve_lfm20_0_0.xml.txt](https://github.com/openhab/openhab2-addons/files/288429/evolve_lfm20_0_0.xml.txt)

**Comment by cdjackson** [comment]
Hi Brady,
Do you have the XML file that OH2 creates (or OH1 of you don’t have one from OH2)?

Chris

**Comment by BradyRosino** [comment]
Hey Chris,

OpenHAB2 is not generating the node.xml file when adding the switch. I will spin up my 1.8.3 environment tonight to see if that generates it.

If all else fails I'll grab debug logs when adding the node.

**Comment by BradyRosino** [comment]
XML is attached. OpenHAB 1.8.3 was more willing to create it.

[node6.xml.txt](https://github.com/openhab/openhab2-addons/files/288651/node6.xml.txt)

**Comment by BradyRosino** [comment]
Also, just realized that while I was grabbing that file... This zwave device works perfect on 1.8.3. Not sure if it is actually sharing the same configuration as the FS20Z relay switch.

I suppose if there were other zwave devices that were configured in this way in the OpenHAB 1 binding, they could potentially have this same issue in OpenHAB 2 zwave bindings?

Just thought I'd throw that out there as well.

**Comment by cdjackson** [comment]
The device doesn’t have much in the way of configuration (just 1 parameter I think), but it needs the database in OH2, and not in OH1 as the channels are now defined in the database (i.e. what was the item strings in OH1).

If OH2 isn’t generating an XML, can you provide a debug log during the initialisation so I can see where it’s going wrong?

Cheers
Chris

**Comment by BradyRosino** [comment]
I don't have access to my OpenHAB box for a few days. I'm actually not sure why the FS20Z xml had the night light config parameter... This is not a feature of the device.

The entry in the pepper database much more accurate on device capabilities. It actually shows no config parameters (is that possible)? Everything in the linked entry below is accurate except these should change on the new entry.

Product Name: LFM-20
Brand: Evolve
Device Data:
     Manufacturer: 0x0113 

http://www.pepper1.net/zwavedb/device/479

**Comment by cdjackson** [comment]
It is possible that the pepper database is correct that there are no parameters, but the pepper database also shows that the configuration class is supported. This would be strange (no configuration, but the configuration class is supported!).

Anyway, when you get the XML from OH, please either load to the database, or load here and I'll ad to the database.

**Comment by BradyRosino** [comment]
Hey Chris,

Finally got around to getting 1.8.3 to generate the XML attached. Last I tried I didn't seem to have permission to add to the database (or I was looking in the wrong place).

Thanks for all your work on the z-wave binding. I'm migrating my home automation and hoping to make OpenHAB 2 my home.

[node6.xml.txt](https://github.com/openhab/openhab2-addons/files/299158/node6.xml.txt)

**Comment by cdjackson** [comment]
Thanks - I've updated the database. I guess there's still a question about he configuration, but we can look at that later...

I'll update the binding in the next day or so.

**Comment by cdjackson** [comment]
I found a manual which states -:

LED indication
The LED on the LFM-20 will turn on when the load attached is ON. The LED can be user configured however
to turn ON when the load attached is OFF, if so desired. The LFM-20 will flicker its LED when it is transmitting
to any of its 4 groups. **This can be changed if desired**.

This leads me to believe configuration should be supported....

**Comment by BradyRosino** [comment]
Manuals for this hardware branded from 3 manufactures had no information on the configuration variables... not well documented.

Sent a few commands to my device and I am able to confirm the following - 

Config Parameter 3
0 = LED ON when load attached is OFF
1 = LED OFF when the load attached is ON

**Comment by cdjackson** [comment]
This device has been added (http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/356) can we close this?

**Comment by BradyRosino** [comment]
Yep, closing his issue as I have tested successfully. Thanks!
