### ISSUE TITLE
Problem running 1.0 binding org.openhab.binding.mpower on openhab2

### ISSUE THREAD

**Issue by Chanete** [openhab/openhab2-addons#987]
Hi, I'm trying to use this binding (I'm not the author, but I've been unable to contact him)  which was running smoothless in openhab 1 but it doesn't start in OH2. I get this error: 

 [ERROR] [org.openhab.binding.mpower          ] - FrameworkEvent ERROR - org.openhab.binding.mpower
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.mpower [193]
  Unresolved requirement: Require-Bundle: org.apache.commons.httpclient

can anyone give a clue on how to solve it?? 

I'm stuck in a dead-lock. I need openhab2 to use part of the bindings I need because I have things not supported in OH1 (Netatmo Thermostat) but I have a lot of ubiquiti mpower wifi plugs that work perfect in OH1 but no way to start the plugin in OH2. 

Thank's again!!

**Comment by kaikreuzer** [comment]
Could you please create this issue at https://github.com/openhab/openhab/issues as this is where the code is located? Thanks!

**Comment by lintweaker** [comment]
Any tips on how to adapt the current mpower binding code so it will work on OH2?

**Comment by Chanete** [comment]
Sorry, no time to debug... As soon as I figure out how to make it work on
OH2 I'll publish here the new version.



2016-10-02 17:24 GMT+02:00 Jurgen Kramer <notifications@github.com>:

**Comment by lintweaker** [comment]
Thanks, hope you'll manage to get it going on OH2

**Comment by Cuarento** [comment]
Anything new about the OH2 Binding?

**Comment by watou** [comment]
@Chanete: You must use `Import-Package` and not `Require-Bundle` in the MANIFEST.MF.  Also, you would need to make sure the binding has changes similar to [these](https://github.com/openhab/openhab/pull/3948) to work on OH2.
