### ISSUE TITLE
RFXcom binding and Somfy enable sun-wind detector

### ISSUE THREAD

**Issue by daballiemo** [openhab/openhab2-addons#995]
Recently I bought an RFXCom to communicate to my balcony Somfy motorised sunscreen (6m \* 5m). I have used the rollershutter item to declare my sunscreen in the items list and are now able to open and close my sunscreen. With the current setup it is not possible to enable/disable the sun-wind detector and hence the screen sometimes closes when i want it to be open and so on. I can't find a way to give such a command through the binding because valid values are OPEN/CLOSE/STOP.
Would it be possible to add these commands to the binding?

(Domotiga calls them:)
STOP/MY
UP
DOWN
ENSUNFLAG - Enable sun+wind detector
DISSUNFLAG - Disable sun detector

Beside the above there is also the fact that a "long" press on the "My" button of the remote (RFXCom calls it a 2 second stop) will change the preset of how far the sunscreen will unroll.

LONG STOP/MY

If any extra info is needed let me know and I will gladly provide it.
##

**Comment by daballiemo** [comment]
has there been any progress on this subject?

**Comment by martinvw** [comment]
Not from my side, but @mjagdis is working very hard on a lot of great improvements to the rfxcom binding so maybe you can convince him to work on it :-)

**Comment by mjagdis** [comment]
Try this:
[org.openhab.binding.rfxcom-2.1.0-SNAPSHOT.zip](https://github.com/openhab/openhab2-addons/files/1049121/org.openhab.binding.rfxcom-2.1.0-SNAPSHOT.zip)

**Comment by Rado77** [comment]
Hello, Is there a chance that you can integrate the MY position from the somfy remote in openhab?
With all the respect for the work you already delivered to this amazing addon.

**Comment by mjagdis** [comment]
I suspect not. I don't actually have any of these things myself but I suspect what you're taking about are what RFXCOM refer to as set position operations and they are listed as not supported. I think everything that is supported via RFXCOM is there now. Just not necessarily well tested yet...

**Comment by joostwestra** [comment]
You can move it to the "My position" by sending the stop command when it is not moving.

**Comment by klejb** [comment]
I might remember wrong but I think that the "MY" command and "sun sensor
on/off" command is supported by Domoticz with RFXCOM?

2017-06-26 21:10 GMT+02:00 joostwestra <notifications@github.com>:

**Comment by Rado77** [comment]
RFXCOM refers this as STOP/MY. I did try what joostwestra said and that seems to do the tric just send the stop command when the rollerschutters are not moving and they go to the MY positions.So problem solved thanks a lot.
